/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef CVA_TABLE_STRUCT_H__
#define CVA_TABLE_STRUCT_H__

#define CVA_VLAN_RESERVED1_LSP         24u
#define CVA_VLAN_RESERVED1_LEN         8u
#define CVA_VLAN_INTERFACE_ID_LSP      18u
#define CVA_VLAN_INTERFACE_ID_LEN      6u
#define CVA_VLAN_INTERFACE_VALID_LSP   17u
#define CVA_VLAN_INTERFACE_VALID_LEN   1u
#define CVA_VLAN_STATEFUL_CHK_MASK_LSP 0u
#define CVA_VLAN_STATEFUL_CHK_MASK_LEN 17u
#define CVA_VLAN_RESERVED2_LSP         17u
#define CVA_VLAN_RESERVED2_LEN         15u
#define CVA_VLAN_MBR_LSP               0u
#define CVA_VLAN_MBR_LEN               17u
#define CVA_VLAN_RESERVED3_LSP         24u
#define CVA_VLAN_RESERVED3_LEN         8u
#define CVA_VLAN_UTAG_LSP              7u
#define CVA_VLAN_UTAG_LEN              17u
#define CVA_VLAN_FID_LSP               3u
#define CVA_VLAN_FID_LEN               4u
#define CVA_VLAN_ULFID_LSP             2u
#define CVA_VLAN_ULFID_LEN             1u
#define CVA_VLAN_VLAN_BASE_FWD_LSP     1u
#define CVA_VLAN_VLAN_BASE_FWD_LEN     1u
#define CVA_VLAN_VALID_LSP             0u
#define CVA_VLAN_VALID_LEN             1u

#define CVA_RESERVED_RESERVED1_LSP 0u
#define CVA_RESERVED_RESERVED1_LEN 1u

#define CVA_L2_TABLE_RESERVED1_LSP 20u
#define CVA_L2_TABLE_RESERVED1_LEN 12u
#define CVA_L2_TABLE_LUT_ADDR1_LSP 0u
#define CVA_L2_TABLE_LUT_ADDR1_LEN 20u
#define CVA_L2_TABLE_LUT_ADDR0_LSP 0u
#define CVA_L2_TABLE_LUT_ADDR0_LEN 32u
#define CVA_L2_TABLE_RESERVED2_LSP 26u
#define CVA_L2_TABLE_RESERVED2_LEN 6u
#define CVA_L2_TABLE_DATA_LSP      0u
#define CVA_L2_TABLE_DATA_LEN      26u

#define CVA_LUT_BCAM_RESERVED1_LSP    29u
#define CVA_LUT_BCAM_RESERVED1_LEN    3u
#define CVA_LUT_BCAM_L2BCAM_ADDR1_LSP 0u
#define CVA_LUT_BCAM_L2BCAM_ADDR1_LEN 29u
#define CVA_LUT_BCAM_L2BCAM_ADDR0_LSP 0u
#define CVA_LUT_BCAM_L2BCAM_ADDR0_LEN 32u
#define CVA_LUT_BCAM_RESERVED2_LSP    26u
#define CVA_LUT_BCAM_RESERVED2_LEN    6u
#define CVA_LUT_BCAM_DATA_LSP         0u
#define CVA_LUT_BCAM_DATA_LEN         26u

#define CVA_ACTION_TABLE_AIF3_LSP          0u
#define CVA_ACTION_TABLE_AIF3_LEN          32u
#define CVA_ACTION_TABLE_AIF2_LSP          0u
#define CVA_ACTION_TABLE_AIF2_LEN          32u
#define CVA_ACTION_TABLE_AIF1_LSP          0u
#define CVA_ACTION_TABLE_AIF1_LEN          32u
#define CVA_ACTION_TABLE_FLOW_LSP          31u
#define CVA_ACTION_TABLE_FLOW_LEN          1u
#define CVA_ACTION_TABLE_DROP_LSP          29u
#define CVA_ACTION_TABLE_DROP_LEN          2u
#define CVA_ACTION_TABLE_CP2CPU_LSP        28u
#define CVA_ACTION_TABLE_CP2CPU_LEN        1u
#define CVA_ACTION_TABLE_MIRROR1_LSP       27u
#define CVA_ACTION_TABLE_MIRROR1_LEN       1u
#define CVA_ACTION_TABLE_MIRROR0_LSP       26u
#define CVA_ACTION_TABLE_MIRROR0_LEN       1u
#define CVA_ACTION_TABLE_OTAG_LSP          25u
#define CVA_ACTION_TABLE_OTAG_LEN          1u
#define CVA_ACTION_TABLE_ITAG_LSP          24u
#define CVA_ACTION_TABLE_ITAG_LEN          1u
#define CVA_ACTION_TABLE_PRIRMK_LSP        23u
#define CVA_ACTION_TABLE_PRIRMK_LEN        1u
#define CVA_ACTION_TABLE_REDIR_LSP         22u
#define CVA_ACTION_TABLE_REDIR_LEN         1u
#define CVA_ACTION_TABLE_DSCPRMK_LSP       21u
#define CVA_ACTION_TABLE_DSCPRMK_LEN       1u
#define CVA_ACTION_TABLE_PRIORITY_LSP      20u
#define CVA_ACTION_TABLE_PRIORITY_LEN      1u
#define CVA_ACTION_TABLE_BYRATELMT_LSP     19u
#define CVA_ACTION_TABLE_BYRATELMT_LEN     1u
#define CVA_ACTION_TABLE_UC_LSP            18u
#define CVA_ACTION_TABLE_UC_LEN            1u
#define CVA_ACTION_TABLE_MC_LSP            17u
#define CVA_ACTION_TABLE_MC_LEN            1u
#define CVA_ACTION_TABLE_TIMER_DISCARD_LSP 16u
#define CVA_ACTION_TABLE_TIMER_DISCARD_LEN 1u
#define CVA_ACTION_TABLE_HEADER_DUMP_LSP   15u
#define CVA_ACTION_TABLE_HEADER_DUMP_LEN   1u
#define CVA_ACTION_TABLE_RESERVED1_LSP     0u
#define CVA_ACTION_TABLE_RESERVED1_LEN     15u

#define CVA_ACL_COUNTER_COUNTER_31_0_LSP  0u
#define CVA_ACL_COUNTER_COUNTER_31_0_LEN  32u
#define CVA_ACL_COUNTER_TYPE_LSP          31u
#define CVA_ACL_COUNTER_TYPE_LEN          1u
#define CVA_ACL_COUNTER_RESERVED1_LSP     17u
#define CVA_ACL_COUNTER_RESERVED1_LEN     14u
#define CVA_ACL_COUNTER_CNTMODE_LSP       16u
#define CVA_ACL_COUNTER_CNTMODE_LEN       1u
#define CVA_ACL_COUNTER_COUNTER_47_32_LSP 0u
#define CVA_ACL_COUNTER_COUNTER_47_32_LEN 16u

#define CVA_POLICER_RESERVED1_LSP     20u
#define CVA_POLICER_RESERVED1_LEN     12u
#define CVA_POLICER_RATE_LSP          0u
#define CVA_POLICER_RATE_LEN          20u
#define CVA_POLICER_TYPE_LSP          31u
#define CVA_POLICER_TYPE_LEN          1u
#define CVA_POLICER_RESERVED2_LSP     29u
#define CVA_POLICER_RESERVED2_LEN     2u
#define CVA_POLICER_TOKEN_COUNTER_LSP 8u
#define CVA_POLICER_TOKEN_COUNTER_LEN 21u
#define CVA_POLICER_THRESHOLD_LSP     0u
#define CVA_POLICER_THRESHOLD_LEN     8u

#define CVA_PIE_TABLE_PIE_CARE_191_160_LSP 0u
#define CVA_PIE_TABLE_PIE_CARE_191_160_LEN 32u
#define CVA_PIE_TABLE_PIE_CARE_159_128_LSP 0u
#define CVA_PIE_TABLE_PIE_CARE_159_128_LEN 32u
#define CVA_PIE_TABLE_PIE_CARE_127_96_LSP  0u
#define CVA_PIE_TABLE_PIE_CARE_127_96_LEN  32u
#define CVA_PIE_TABLE_PIE_CARE_95_64_LSP   0u
#define CVA_PIE_TABLE_PIE_CARE_95_64_LEN   32u
#define CVA_PIE_TABLE_PIE_CARE_63_32_LSP   0u
#define CVA_PIE_TABLE_PIE_CARE_63_32_LEN   32u
#define CVA_PIE_TABLE_PIE_CARE_31_0_LSP    0u
#define CVA_PIE_TABLE_PIE_CARE_31_0_LEN    32u
#define CVA_PIE_TABLE_RESERVED1_LSP        1u
#define CVA_PIE_TABLE_RESERVED1_LEN        31u
#define CVA_PIE_TABLE_VALID_INDIRECT_LSP   0u
#define CVA_PIE_TABLE_VALID_INDIRECT_LEN   1u
#define CVA_PIE_TABLE_PIE_DATA_191_160_LSP 0u
#define CVA_PIE_TABLE_PIE_DATA_191_160_LEN 32u
#define CVA_PIE_TABLE_PIE_DATA_159_128_LSP 0u
#define CVA_PIE_TABLE_PIE_DATA_159_128_LEN 32u
#define CVA_PIE_TABLE_PIE_DATA_127_96_LSP  0u
#define CVA_PIE_TABLE_PIE_DATA_127_96_LEN  32u
#define CVA_PIE_TABLE_PIE_DATA_95_64_LSP   0u
#define CVA_PIE_TABLE_PIE_DATA_95_64_LEN   32u
#define CVA_PIE_TABLE_PIE_DATA_63_32_LSP   0u
#define CVA_PIE_TABLE_PIE_DATA_63_32_LEN   32u
#define CVA_PIE_TABLE_PIE_DATA_31_0_LSP    0u
#define CVA_PIE_TABLE_PIE_DATA_31_0_LEN    32u

#define CVA_GROUP_RESERVED1_LSP 28u
#define CVA_GROUP_RESERVED1_LEN 4u
#define CVA_GROUP_IP_ADDR_LSP   0u
#define CVA_GROUP_IP_ADDR_LEN   28u
#define CVA_GROUP_RESERVED2_LSP 17u
#define CVA_GROUP_RESERVED2_LEN 15u
#define CVA_GROUP_IP_MASK_LSP   0u
#define CVA_GROUP_IP_MASK_LEN   17u

#define CVA_QBV_GATE_CONTROL_LIST_TABLE_RESERVED1_LSP     15u
#define CVA_QBV_GATE_CONTROL_LIST_TABLE_RESERVED1_LEN     17u
#define CVA_QBV_GATE_CONTROL_LIST_TABLE_OP_MODE_LSP       8u
#define CVA_QBV_GATE_CONTROL_LIST_TABLE_OP_MODE_LEN       7u
#define CVA_QBV_GATE_CONTROL_LIST_TABLE_GATE_STATE_LSP    0u
#define CVA_QBV_GATE_CONTROL_LIST_TABLE_GATE_STATE_LEN    8u
#define CVA_QBV_GATE_CONTROL_LIST_TABLE_RESERVED2_LSP     29u
#define CVA_QBV_GATE_CONTROL_LIST_TABLE_RESERVED2_LEN     3u
#define CVA_QBV_GATE_CONTROL_LIST_TABLE_TIME_INTERVAL_LSP 0u
#define CVA_QBV_GATE_CONTROL_LIST_TABLE_TIME_INTERVAL_LEN 29u

#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q7_LSP   31u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q7_LEN   1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q7_LSP       30u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q7_LEN       1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q7_LSP  29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q7_LEN  1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q7_LSP 0u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q7_LEN 29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q6_LSP   31u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q6_LEN   1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q6_LSP       30u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q6_LEN       1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q6_LSP  29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q6_LEN  1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q6_LSP 0u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q6_LEN 29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_RESERVED1_LSP    0u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_RESERVED1_LEN    32u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q5_LSP   31u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q5_LEN   1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q5_LSP       30u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q5_LEN       1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q5_LSP  29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q5_LEN  1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q5_LSP 0u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q5_LEN 29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q4_LSP   31u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q4_LEN   1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q4_LSP       30u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q4_LEN       1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q4_LSP  29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q4_LEN  1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q4_LSP 0u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q4_LEN 29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q3_LSP   31u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q3_LEN   1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q3_LSP       30u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q3_LEN       1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q3_LSP  29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q3_LEN  1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q3_LSP 0u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q3_LEN 29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q2_LSP   31u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q2_LEN   1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q2_LSP       30u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q2_LEN       1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q2_LSP  29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q2_LEN  1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q2_LSP 0u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q2_LEN 29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q1_LSP   31u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q1_LEN   1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q1_LSP       30u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q1_LEN       1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q1_LSP  29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q1_LEN  1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q1_LSP 0u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q1_LEN 29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q0_LSP   31u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SPECIAL_Q0_LEN   1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q0_LSP       30u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_EOR_Q0_LEN       1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q0_LSP  29u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_BOUNDARY_Q0_LEN  1u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q0_LSP 0u
#define CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE_SGOT_TIME_Q0_LEN 29u

#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD14_LSP    0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD14_LEN    32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD13_LSP    0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD13_LEN    32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD12_LSP    0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD12_LEN    32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD11_LSP    0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD11_LEN    32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD10_LSP    0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD10_LEN    32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD9_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD9_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD8_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD8_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD7_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD7_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD6_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD6_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD5_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD5_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD4_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD4_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD3_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD3_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD2_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD2_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD1_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD1_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD0_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_CARE_FIELD0_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_RESERVED1_LSP       0u
#define CVA_STREAM_IDENTIFICATION_TABLE_RESERVED1_LEN       32u
#define CVA_STREAM_IDENTIFICATION_TABLE_RESERVED2_LSP       18u
#define CVA_STREAM_IDENTIFICATION_TABLE_RESERVED2_LEN       14u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTPORTINVALID_LSP  17u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTPORTINVALID_LEN  1u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTPORT_15_0_LSP    1u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTPORT_15_0_LEN    16u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCPORTINVALID_LSP  0u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCPORTINVALID_LEN  1u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCPORT_15_0_LSP    16u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCPORT_15_0_LEN    16u
#define CVA_STREAM_IDENTIFICATION_TABLE_NEXTPROCINVALID_LSP 15u
#define CVA_STREAM_IDENTIFICATION_TABLE_NEXTPROCINVALID_LEN 1u
#define CVA_STREAM_IDENTIFICATION_TABLE_NEXTPROC_7_0_LSP    7u
#define CVA_STREAM_IDENTIFICATION_TABLE_NEXTPROC_7_0_LEN    8u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSCPINVALID_LSP     6u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSCPINVALID_LEN     1u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSCP_5_0_LSP        0u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSCP_5_0_LEN        6u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIPINVALID_LSP    31u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIPINVALID_LEN    1u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIP_127_97_LSP    0u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIP_127_97_LEN    31u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIP_96_65_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIP_96_65_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIP_64_33_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIP_64_33_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIP_32_1_LSP      0u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIP_32_1_LEN      32u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIP_0_0_LSP       31u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTIP_0_0_LEN       1u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIPINVALID_LSP    30u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIPINVALID_LEN    1u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIP_127_98_LSP    0u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIP_127_98_LEN    30u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIP_97_66_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIP_97_66_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_RESERVED3_LSP       1u
#define CVA_STREAM_IDENTIFICATION_TABLE_RESERVED3_LEN       31u
#define CVA_STREAM_IDENTIFICATION_TABLE_VALID_INDIRECT_LSP  0u
#define CVA_STREAM_IDENTIFICATION_TABLE_VALID_INDIRECT_LEN  1u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIP_65_34_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIP_65_34_LEN     32u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIP_33_2_LSP      0u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIP_33_2_LEN      32u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIP_1_0_LSP       30u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCIP_1_0_LEN       2u
#define CVA_STREAM_IDENTIFICATION_TABLE_VLANIDINVALID_LSP   29u
#define CVA_STREAM_IDENTIFICATION_TABLE_VLANIDINVALID_LEN   1u
#define CVA_STREAM_IDENTIFICATION_TABLE_VLANID_LSP          17u
#define CVA_STREAM_IDENTIFICATION_TABLE_VLANID_LEN          12u
#define CVA_STREAM_IDENTIFICATION_TABLE_ETYPEINVALID_LSP    16u
#define CVA_STREAM_IDENTIFICATION_TABLE_ETYPEINVALID_LEN    1u
#define CVA_STREAM_IDENTIFICATION_TABLE_ETYPE_15_0_LSP      0u
#define CVA_STREAM_IDENTIFICATION_TABLE_ETYPE_15_0_LEN      16u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCMAC_47_16_LSP    0u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCMAC_47_16_LEN    32u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCMAC_31_0_LSP     16u
#define CVA_STREAM_IDENTIFICATION_TABLE_SRCMAC_31_0_LEN     16u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTMAC_47_32_LSP    0u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTMAC_47_32_LEN    16u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTMAC_31_0_LSP     0u
#define CVA_STREAM_IDENTIFICATION_TABLE_DSTMAC_31_0_LEN     32u

#define CVA_CB_LOOK_UP_TABLE_RESERVED1_LSP             1u
#define CVA_CB_LOOK_UP_TABLE_RESERVED1_LEN             31u
#define CVA_CB_LOOK_UP_TABLE_CB_INDRCV_IDX_6_LSP       0u
#define CVA_CB_LOOK_UP_TABLE_CB_INDRCV_IDX_6_LEN       1u
#define CVA_CB_LOOK_UP_TABLE_CB_INDRCV_IDX_5_0_LSP     26u
#define CVA_CB_LOOK_UP_TABLE_CB_INDRCV_IDX_5_0_LEN     6u
#define CVA_CB_LOOK_UP_TABLE_CB_INDRCV_EN_LSP          25u
#define CVA_CB_LOOK_UP_TABLE_CB_INDRCV_EN_LEN          1u
#define CVA_CB_LOOK_UP_TABLE_CB_SEQRCV_IDX_LSP         19u
#define CVA_CB_LOOK_UP_TABLE_CB_SEQRCV_IDX_LEN         6u
#define CVA_CB_LOOK_UP_TABLE_CB_SEQRCV_EN_LSP          18u
#define CVA_CB_LOOK_UP_TABLE_CB_SEQRCV_EN_LEN          1u
#define CVA_CB_LOOK_UP_TABLE_CB_SPLIT_DPM_LSP          2u
#define CVA_CB_LOOK_UP_TABLE_CB_SPLIT_DPM_LEN          16u
#define CVA_CB_LOOK_UP_TABLE_CB_SPLIT_EN_LSP           1u
#define CVA_CB_LOOK_UP_TABLE_CB_SPLIT_EN_LEN           1u
#define CVA_CB_LOOK_UP_TABLE_CB_SEQGEN_SEQNUM_15_LSP   0u
#define CVA_CB_LOOK_UP_TABLE_CB_SEQGEN_SEQNUM_15_LEN   1u
#define CVA_CB_LOOK_UP_TABLE_CB_SEQGEN_SEQNUM_14_0_LSP 17u
#define CVA_CB_LOOK_UP_TABLE_CB_SEQGEN_SEQNUM_14_0_LEN 15u
#define CVA_CB_LOOK_UP_TABLE_CB_SEQGEN_EN_LSP          16u
#define CVA_CB_LOOK_UP_TABLE_CB_SEQGEN_EN_LEN          1u
#define CVA_CB_LOOK_UP_TABLE_CB_ACTSEQ_IDX_LSP         2u
#define CVA_CB_LOOK_UP_TABLE_CB_ACTSEQ_IDX_LEN         14u
#define CVA_CB_LOOK_UP_TABLE_CB_ACTSEQ_EN_LSP          1u
#define CVA_CB_LOOK_UP_TABLE_CB_ACTSEQ_EN_LEN          1u
#define CVA_CB_LOOK_UP_TABLE_CB_ADDRTAG_LSP            0u
#define CVA_CB_LOOK_UP_TABLE_CB_ADDRTAG_LEN            1u

#define CVA_CB_SEQUENCY_RECOVERY_TABLE_RESERVED1_LSP              0u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_RESERVED1_LEN              32u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_RESERVED2_LSP              19u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_RESERVED2_LEN              13u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_HISLEN_15_0_LSP  3u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_HISLEN_15_0_LEN  16u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_HISIDX_15_13_LSP 0u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_HISIDX_15_13_LEN 3u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_HISIDX_12_0_LSP  19u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_HISIDX_12_0_LEN  13u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_SEQNUM_LSP       3u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_SEQNUM_LEN       16u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_TAKE_NO_LSP      2u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_TAKE_NO_LEN      1u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_ALGO_LSP         1u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_ALGO_LEN         1u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_VALID_LSP        0u
#define CVA_CB_SEQUENCY_RECOVERY_TABLE_CB_SEQRCV_VALID_LEN        1u

#define CVA_CB_HISTORY_TABLE_CB_HISTORY_511_480_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_511_480_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_479_448_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_479_448_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_447_416_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_447_416_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_415_384_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_415_384_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_383_352_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_383_352_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_351_320_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_351_320_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_319_288_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_319_288_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_287_256_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_287_256_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_255_224_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_255_224_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_223_192_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_223_192_LEN 32u
#define CVA_CB_HISTORY_TABLE_RESERVED1_LSP          0u
#define CVA_CB_HISTORY_TABLE_RESERVED1_LEN          32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_191_160_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_191_160_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_159_128_LSP 0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_159_128_LEN 32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_127_96_LSP  0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_127_96_LEN  32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_95_64_LSP   0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_95_64_LEN   32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_63_32_LSP   0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_63_32_LEN   32u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_31_0_LSP    0u
#define CVA_CB_HISTORY_TABLE_CB_HISTORY_31_0_LEN    32u

#define CVA_RH_TABLE_RESERVED1_LSP  14u
#define CVA_RH_TABLE_RESERVED1_LEN  18u
#define CVA_RH_TABLE_P14_RH_IDX_LSP 0u
#define CVA_RH_TABLE_P14_RH_IDX_LEN 14u
#define CVA_RH_TABLE_RESERVED2_LSP  30u
#define CVA_RH_TABLE_RESERVED2_LEN  2u
#define CVA_RH_TABLE_P13_RH_IDX_LSP 16u
#define CVA_RH_TABLE_P13_RH_IDX_LEN 14u
#define CVA_RH_TABLE_RESERVED3_LSP  14u
#define CVA_RH_TABLE_RESERVED3_LEN  2u
#define CVA_RH_TABLE_P12_RH_IDX_LSP 0u
#define CVA_RH_TABLE_P12_RH_IDX_LEN 14u
#define CVA_RH_TABLE_RESERVED4_LSP  0u
#define CVA_RH_TABLE_RESERVED4_LEN  32u
#define CVA_RH_TABLE_RESERVED5_LSP  30u
#define CVA_RH_TABLE_RESERVED5_LEN  2u
#define CVA_RH_TABLE_P11_RH_IDX_LSP 16u
#define CVA_RH_TABLE_P11_RH_IDX_LEN 14u
#define CVA_RH_TABLE_RESERVED6_LSP  14u
#define CVA_RH_TABLE_RESERVED6_LEN  2u
#define CVA_RH_TABLE_P10_RH_IDX_LSP 0u
#define CVA_RH_TABLE_P10_RH_IDX_LEN 14u
#define CVA_RH_TABLE_RESERVED7_LSP  30u
#define CVA_RH_TABLE_RESERVED7_LEN  2u
#define CVA_RH_TABLE_P9_RH_IDX_LSP  16u
#define CVA_RH_TABLE_P9_RH_IDX_LEN  14u
#define CVA_RH_TABLE_RESERVED8_LSP  14u
#define CVA_RH_TABLE_RESERVED8_LEN  2u
#define CVA_RH_TABLE_P8_RH_IDX_LSP  0u
#define CVA_RH_TABLE_P8_RH_IDX_LEN  14u
#define CVA_RH_TABLE_RESERVED9_LSP  30u
#define CVA_RH_TABLE_RESERVED9_LEN  2u
#define CVA_RH_TABLE_P7_RH_IDX_LSP  16u
#define CVA_RH_TABLE_P7_RH_IDX_LEN  14u
#define CVA_RH_TABLE_RESERVED10_LSP 14u
#define CVA_RH_TABLE_RESERVED10_LEN 2u
#define CVA_RH_TABLE_P6_RH_IDX_LSP  0u
#define CVA_RH_TABLE_P6_RH_IDX_LEN  14u
#define CVA_RH_TABLE_RESERVED11_LSP 30u
#define CVA_RH_TABLE_RESERVED11_LEN 2u
#define CVA_RH_TABLE_P5_RH_IDX_LSP  16u
#define CVA_RH_TABLE_P5_RH_IDX_LEN  14u
#define CVA_RH_TABLE_RESERVED12_LSP 14u
#define CVA_RH_TABLE_RESERVED12_LEN 2u
#define CVA_RH_TABLE_P4_RH_IDX_LSP  0u
#define CVA_RH_TABLE_P4_RH_IDX_LEN  14u
#define CVA_RH_TABLE_RESERVED13_LSP 30u
#define CVA_RH_TABLE_RESERVED13_LEN 2u
#define CVA_RH_TABLE_P3_RH_IDX_LSP  16u
#define CVA_RH_TABLE_P3_RH_IDX_LEN  14u
#define CVA_RH_TABLE_RESERVED14_LSP 14u
#define CVA_RH_TABLE_RESERVED14_LEN 2u
#define CVA_RH_TABLE_P2_RH_IDX_LSP  0u
#define CVA_RH_TABLE_P2_RH_IDX_LEN  14u
#define CVA_RH_TABLE_RESERVED15_LSP 30u
#define CVA_RH_TABLE_RESERVED15_LEN 2u
#define CVA_RH_TABLE_P1_RH_IDX_LSP  16u
#define CVA_RH_TABLE_P1_RH_IDX_LEN  14u
#define CVA_RH_TABLE_RESERVED16_LSP 14u
#define CVA_RH_TABLE_RESERVED16_LEN 2u
#define CVA_RH_TABLE_P0_RH_IDX_LSP  0u
#define CVA_RH_TABLE_P0_RH_IDX_LEN  14u

#define CVA_OIL_TABLE_RESERVED1_LSP  24u
#define CVA_OIL_TABLE_RESERVED1_LEN  8u
#define CVA_OIL_TABLE_OIL_NEXT_LSP   10u
#define CVA_OIL_TABLE_OIL_NEXT_LEN   14u
#define CVA_OIL_TABLE_EGR_IF_IDX_LSP 2u
#define CVA_OIL_TABLE_EGR_IF_IDX_LEN 8u
#define CVA_OIL_TABLE_TTL_DEC_LSP    1u
#define CVA_OIL_TABLE_TTL_DEC_LEN    1u
#define CVA_OIL_TABLE_TTL_CHK_LSP    0u
#define CVA_OIL_TABLE_TTL_CHK_LEN    1u

#define CVA_EGIF_TABLE_RPF_FAIL_ACT_LSP         30u
#define CVA_EGIF_TABLE_RPF_FAIL_ACT_LEN         2u
#define CVA_EGIF_TABLE_RPF_CHK_EN_LSP           29u
#define CVA_EGIF_TABLE_RPF_CHK_EN_LEN           1u
#define CVA_EGIF_TABLE_ICMP_REDIRECT_ACT_LSP    27u
#define CVA_EGIF_TABLE_ICMP_REDIRECT_ACT_LEN    2u
#define CVA_EGIF_TABLE_ICMP_REDIRECT_CHK_EN_LSP 26u
#define CVA_EGIF_TABLE_ICMP_REDIRECT_CHK_EN_LEN 1u
#define CVA_EGIF_TABLE_IP6MC_HL_LSP             18u
#define CVA_EGIF_TABLE_IP6MC_HL_LEN             8u
#define CVA_EGIF_TABLE_IPMC_TTL_LSP             10u
#define CVA_EGIF_TABLE_IPMC_TTL_LEN             8u
#define CVA_EGIF_TABLE_IP6_MTU_IDX_LSP          7u
#define CVA_EGIF_TABLE_IP6_MTU_IDX_LEN          3u
#define CVA_EGIF_TABLE_IP_MTU_IDX_LSP           4u
#define CVA_EGIF_TABLE_IP_MTU_IDX_LEN           3u
#define CVA_EGIF_TABLE_PCP_REPLACE_LSP          3u
#define CVA_EGIF_TABLE_PCP_REPLACE_LEN          1u
#define CVA_EGIF_TABLE_PCP_LSP                  0u
#define CVA_EGIF_TABLE_PCP_LEN                  3u
#define CVA_EGIF_TABLE_RESERVED1_LSP            31u
#define CVA_EGIF_TABLE_RESERVED1_LEN            1u
#define CVA_EGIF_TABLE_VID_REPLACE_LSP          30u
#define CVA_EGIF_TABLE_VID_REPLACE_LEN          1u
#define CVA_EGIF_TABLE_VID_LSP                  18u
#define CVA_EGIF_TABLE_VID_LEN                  12u
#define CVA_EGIF_TABLE_MAC_REPLACE_LSP          17u
#define CVA_EGIF_TABLE_MAC_REPLACE_LEN          1u
#define CVA_EGIF_TABLE_MAC_FMT_SEL_LSP          16u
#define CVA_EGIF_TABLE_MAC_FMT_SEL_LEN          1u
#define CVA_EGIF_TABLE_MACID_47_32_LSP          0u
#define CVA_EGIF_TABLE_MACID_47_32_LEN          16u
#define CVA_EGIF_TABLE_MACID_31_0_LSP           0u
#define CVA_EGIF_TABLE_MACID_31_0_LEN           32u

#define CVA_INGIF_TABLE_DPORT_CARE_LSP             16u
#define CVA_INGIF_TABLE_DPORT_CARE_LEN             16u
#define CVA_INGIF_TABLE_SPORT_CARE_LSP             0u
#define CVA_INGIF_TABLE_SPORT_CARE_LEN             16u
#define CVA_INGIF_TABLE_MAC_ADDR_47_16_CARE_LSP    0u
#define CVA_INGIF_TABLE_MAC_ADDR_47_16_CARE_LEN    32u
#define CVA_INGIF_TABLE_RESERVED1_LSP              1u
#define CVA_INGIF_TABLE_RESERVED1_LEN              31u
#define CVA_INGIF_TABLE_VALID_INDIRECT_LSP         0u
#define CVA_INGIF_TABLE_VALID_INDIRECT_LEN         1u
#define CVA_INGIF_TABLE_MAC_ADDR_15_0_CARE_LSP     16u
#define CVA_INGIF_TABLE_MAC_ADDR_15_0_CARE_LEN     16u
#define CVA_INGIF_TABLE_IVID_CARE_LSP              4u
#define CVA_INGIF_TABLE_IVID_CARE_LEN              12u
#define CVA_INGIF_TABLE_PORT_ID_CARE_LSP           0u
#define CVA_INGIF_TABLE_PORT_ID_CARE_LEN           4u
#define CVA_INGIF_TABLE_RESERVED2_LSP              8u
#define CVA_INGIF_TABLE_RESERVED2_LEN              24u
#define CVA_INGIF_TABLE_VID_NOCARE_LSP             7u
#define CVA_INGIF_TABLE_VID_NOCARE_LEN             1u
#define CVA_INGIF_TABLE_SIP_NOCARE_LSP             6u
#define CVA_INGIF_TABLE_SIP_NOCARE_LEN             1u
#define CVA_INGIF_TABLE_DIP_NOCARE_LSP             5u
#define CVA_INGIF_TABLE_DIP_NOCARE_LEN             1u
#define CVA_INGIF_TABLE_CMP_0_GIP_LSP              4u
#define CVA_INGIF_TABLE_CMP_0_GIP_LEN              1u
#define CVA_INGIF_TABLE_IP6MC_ROUTE_LU_MIS_ACT_LSP 2u
#define CVA_INGIF_TABLE_IP6MC_ROUTE_LU_MIS_ACT_LEN 2u
#define CVA_INGIF_TABLE_IPMC_ROUTE_LU_MIS_ACT_LSP  0u
#define CVA_INGIF_TABLE_IPMC_ROUTE_LU_MIS_ACT_LEN  2u
#define CVA_INGIF_TABLE_FIREWALL_MODE_LSP          31u
#define CVA_INGIF_TABLE_FIREWALL_MODE_LEN          1u
#define CVA_INGIF_TABLE_IP6_URPF_CHK_MODE_LSP      30u
#define CVA_INGIF_TABLE_IP6_URPF_CHK_MODE_LEN      1u
#define CVA_INGIF_TABLE_IP6_URPF_DFLT_ROUTE_EN_LSP 29u
#define CVA_INGIF_TABLE_IP6_URPF_DFLT_ROUTE_EN_LEN 1u
#define CVA_INGIF_TABLE_IP6_URPF_CHK_EN_LSP        28u
#define CVA_INGIF_TABLE_IP6_URPF_CHK_EN_LEN        1u
#define CVA_INGIF_TABLE_IP6_URPF_FAIL_ACT_LSP      26u
#define CVA_INGIF_TABLE_IP6_URPF_FAIL_ACT_LEN      2u
#define CVA_INGIF_TABLE_IP_URPF_CHK_MODE_LSP       25u
#define CVA_INGIF_TABLE_IP_URPF_CHK_MODE_LEN       1u
#define CVA_INGIF_TABLE_IP_URPF_DFLT_ROUTE_EN_LSP  24u
#define CVA_INGIF_TABLE_IP_URPF_DFLT_ROUTE_EN_LEN  1u
#define CVA_INGIF_TABLE_IP_URPF_CHK_EN_LSP         23u
#define CVA_INGIF_TABLE_IP_URPF_CHK_EN_LEN         1u
#define CVA_INGIF_TABLE_IP_URPF_FAIL_ACT_LSP       21u
#define CVA_INGIF_TABLE_IP_URPF_FAIL_ACT_LEN       2u
#define CVA_INGIF_TABLE_RESERVED3_LSP              19u
#define CVA_INGIF_TABLE_RESERVED3_LEN              2u
#define CVA_INGIF_TABLE_IP6MC_ROUTE_EN_LSP         18u
#define CVA_INGIF_TABLE_IP6MC_ROUTE_EN_LEN         1u
#define CVA_INGIF_TABLE_IPMC_ROUTE_EN_LSP          17u
#define CVA_INGIF_TABLE_IPMC_ROUTE_EN_LEN          1u
#define CVA_INGIF_TABLE_IP6UC_ROUTE_EN_LSP         16u
#define CVA_INGIF_TABLE_IP6UC_ROUTE_EN_LEN         1u
#define CVA_INGIF_TABLE_IPUC_ROUTE_EN_LSP          15u
#define CVA_INGIF_TABLE_IPUC_ROUTE_EN_LEN          1u
#define CVA_INGIF_TABLE_ACT_LSP                    13u
#define CVA_INGIF_TABLE_ACT_LEN                    2u
#define CVA_INGIF_TABLE_DPORT_FMT_LSP              11u
#define CVA_INGIF_TABLE_DPORT_FMT_LEN              2u
#define CVA_INGIF_TABLE_SPORT_FMT_LSP              9u
#define CVA_INGIF_TABLE_SPORT_FMT_LEN              2u
#define CVA_INGIF_TABLE_INTFID_LSP                 2u
#define CVA_INGIF_TABLE_INTFID_LEN                 7u
#define CVA_INGIF_TABLE_INTFID_VID_KEY_SEL_LSP     1u
#define CVA_INGIF_TABLE_INTFID_VID_KEY_SEL_LEN     1u
#define CVA_INGIF_TABLE_VALID_LSP                  0u
#define CVA_INGIF_TABLE_VALID_LEN                  1u
#define CVA_INGIF_TABLE_DPORT_LSP                  16u
#define CVA_INGIF_TABLE_DPORT_LEN                  16u
#define CVA_INGIF_TABLE_SPORT_LSP                  0u
#define CVA_INGIF_TABLE_SPORT_LEN                  16u
#define CVA_INGIF_TABLE_MAC_ADDR_47_16_LSP         0u
#define CVA_INGIF_TABLE_MAC_ADDR_47_16_LEN         32u
#define CVA_INGIF_TABLE_MAC_ADDR_15_0_LSP          16u
#define CVA_INGIF_TABLE_MAC_ADDR_15_0_LEN          16u
#define CVA_INGIF_TABLE_IVID_LSP                   4u
#define CVA_INGIF_TABLE_IVID_LEN                   12u
#define CVA_INGIF_TABLE_PORT_ID_LSP                0u
#define CVA_INGIF_TABLE_PORT_ID_LEN                4u

#define CVA_HOST_ROUTE_TABLE_RESERVED1_LSP           16u
#define CVA_HOST_ROUTE_TABLE_RESERVED1_LEN           16u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_815_800_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_815_800_LEN 16u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_799_768_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_799_768_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_767_736_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_767_736_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_735_704_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_735_704_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_703_672_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_703_672_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_671_640_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_671_640_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_639_608_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_639_608_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_607_576_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_607_576_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_575_544_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_575_544_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_543_512_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_543_512_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_511_480_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_511_480_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_479_448_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_479_448_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_447_416_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_447_416_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_415_384_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_415_384_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_383_352_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_383_352_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_351_320_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_351_320_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_319_288_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_319_288_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_287_256_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_287_256_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_255_224_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_255_224_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_223_192_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_223_192_LEN 32u
#define CVA_HOST_ROUTE_TABLE_RESERVED2_LSP           0u
#define CVA_HOST_ROUTE_TABLE_RESERVED2_LEN           32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_191_160_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_191_160_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_159_128_LSP 0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_159_128_LEN 32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_127_96_LSP  0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_127_96_LEN  32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_95_64_LSP   0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_95_64_LEN   32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_63_32_LSP   0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_63_32_LEN   32u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_31_0_LSP    0u
#define CVA_HOST_ROUTE_TABLE_HOSTBL_WDAT_31_0_LEN    32u

#define CVA_NETWORK_ROUTE_TABLE_RESERVED1_LSP       21u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED1_LEN       11u
#define CVA_NETWORK_ROUTE_TABLE_VID_CARE_LSP        9u
#define CVA_NETWORK_ROUTE_TABLE_VID_CARE_LEN        12u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED2_LSP       0u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED2_LEN       9u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED3_LSP       24u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED3_LEN       8u
#define CVA_NETWORK_ROUTE_TABLE_DPORT_FMT_CARE_LSP  22u
#define CVA_NETWORK_ROUTE_TABLE_DPORT_FMT_CARE_LEN  2u
#define CVA_NETWORK_ROUTE_TABLE_SPORT_FMT_CARE_LSP  20u
#define CVA_NETWORK_ROUTE_TABLE_SPORT_FMT_CARE_LEN  2u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED4_LSP       4u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED4_LEN       16u
#define CVA_NETWORK_ROUTE_TABLE_TYPE_CARE_LSP       1u
#define CVA_NETWORK_ROUTE_TABLE_TYPE_CARE_LEN       3u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED5_LSP       0u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED5_LEN       1u
#define CVA_NETWORK_ROUTE_TABLE_DPORT_CARE_LSP      16u
#define CVA_NETWORK_ROUTE_TABLE_DPORT_CARE_LEN      16u
#define CVA_NETWORK_ROUTE_TABLE_SPORT_CARE_LSP      0u
#define CVA_NETWORK_ROUTE_TABLE_SPORT_CARE_LEN      16u
#define CVA_NETWORK_ROUTE_TABLE_DIP_127_96_CARE_LSP 0u
#define CVA_NETWORK_ROUTE_TABLE_DIP_127_96_CARE_LEN 32u
#define CVA_NETWORK_ROUTE_TABLE_DIP_95_64_CARE_LSP  0u
#define CVA_NETWORK_ROUTE_TABLE_DIP_95_64_CARE_LEN  32u
#define CVA_NETWORK_ROUTE_TABLE_DIP_63_32_CARE_LSP  0u
#define CVA_NETWORK_ROUTE_TABLE_DIP_63_32_CARE_LEN  32u
#define CVA_NETWORK_ROUTE_TABLE_DIP_31_0_CARE_LSP   0u
#define CVA_NETWORK_ROUTE_TABLE_DIP_31_0_CARE_LEN   32u
#define CVA_NETWORK_ROUTE_TABLE_SIP_127_96_CARE_LSP 0u
#define CVA_NETWORK_ROUTE_TABLE_SIP_127_96_CARE_LEN 32u
#define CVA_NETWORK_ROUTE_TABLE_SIP_95_64_CARE_LSP  0u
#define CVA_NETWORK_ROUTE_TABLE_SIP_95_64_CARE_LEN  32u
#define CVA_NETWORK_ROUTE_TABLE_SIP_63_32_CARE_LSP  0u
#define CVA_NETWORK_ROUTE_TABLE_SIP_63_32_CARE_LEN  32u
#define CVA_NETWORK_ROUTE_TABLE_SIP_31_0_CARE_LSP   0u
#define CVA_NETWORK_ROUTE_TABLE_SIP_31_0_CARE_LEN   32u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED6_LSP       23u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED6_LEN       9u
#define CVA_NETWORK_ROUTE_TABLE_ARB_MODE_LSP        22u
#define CVA_NETWORK_ROUTE_TABLE_ARB_MODE_LEN        1u
#define CVA_NETWORK_ROUTE_TABLE_ARB_VALID_LSP       21u
#define CVA_NETWORK_ROUTE_TABLE_ARB_VALID_LEN       1u
#define CVA_NETWORK_ROUTE_TABLE_VID_LSP             9u
#define CVA_NETWORK_ROUTE_TABLE_VID_LEN             12u
#define CVA_NETWORK_ROUTE_TABLE_EPPIDX_LSP          3u
#define CVA_NETWORK_ROUTE_TABLE_EPPIDX_LEN          6u
#define CVA_NETWORK_ROUTE_TABLE_QOS_PRI_LSP         0u
#define CVA_NETWORK_ROUTE_TABLE_QOS_PRI_LEN         3u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED7_LSP       30u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED7_LEN       2u
#define CVA_NETWORK_ROUTE_TABLE_QOS_EN_LSP          29u
#define CVA_NETWORK_ROUTE_TABLE_QOS_EN_LEN          1u
#define CVA_NETWORK_ROUTE_TABLE_TTL_CHK_LSP         28u
#define CVA_NETWORK_ROUTE_TABLE_TTL_CHK_LEN         1u
#define CVA_NETWORK_ROUTE_TABLE_TTL_DEC_LSP         27u
#define CVA_NETWORK_ROUTE_TABLE_TTL_DEC_LEN         1u
#define CVA_NETWORK_ROUTE_TABLE_ACT_LSP             24u
#define CVA_NETWORK_ROUTE_TABLE_ACT_LEN             3u
#define CVA_NETWORK_ROUTE_TABLE_DPORT_FMT_LSP       22u
#define CVA_NETWORK_ROUTE_TABLE_DPORT_FMT_LEN       2u
#define CVA_NETWORK_ROUTE_TABLE_SPORT_FMT_LSP       20u
#define CVA_NETWORK_ROUTE_TABLE_SPORT_FMT_LEN       2u
#define CVA_NETWORK_ROUTE_TABLE_DST_NULL_INTF_LSP   19u
#define CVA_NETWORK_ROUTE_TABLE_DST_NULL_INTF_LEN   1u
#define CVA_NETWORK_ROUTE_TABLE_DFLT_ROUTE_LSP      18u
#define CVA_NETWORK_ROUTE_TABLE_DFLT_ROUTE_LEN      1u
#define CVA_NETWORK_ROUTE_TABLE_HOST_ROUTE_LSP      17u
#define CVA_NETWORK_ROUTE_TABLE_HOST_ROUTE_LEN      1u
#define CVA_NETWORK_ROUTE_TABLE_NH_IDX_LSP          5u
#define CVA_NETWORK_ROUTE_TABLE_NH_IDX_LEN          12u
#define CVA_NETWORK_ROUTE_TABLE_HIT_LSP             4u
#define CVA_NETWORK_ROUTE_TABLE_HIT_LEN             1u
#define CVA_NETWORK_ROUTE_TABLE_TYPE_LSP            1u
#define CVA_NETWORK_ROUTE_TABLE_TYPE_LEN            3u
#define CVA_NETWORK_ROUTE_TABLE_VALID_LSP           0u
#define CVA_NETWORK_ROUTE_TABLE_VALID_LEN           1u
#define CVA_NETWORK_ROUTE_TABLE_DPORT_LSP           16u
#define CVA_NETWORK_ROUTE_TABLE_DPORT_LEN           16u
#define CVA_NETWORK_ROUTE_TABLE_SPORT_LSP           0u
#define CVA_NETWORK_ROUTE_TABLE_SPORT_LEN           16u
#define CVA_NETWORK_ROUTE_TABLE_DIP_127_96_LSP      0u
#define CVA_NETWORK_ROUTE_TABLE_DIP_127_96_LEN      32u
#define CVA_NETWORK_ROUTE_TABLE_DIP_95_64_LSP       0u
#define CVA_NETWORK_ROUTE_TABLE_DIP_95_64_LEN       32u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED8_LSP       1u
#define CVA_NETWORK_ROUTE_TABLE_RESERVED8_LEN       31u
#define CVA_NETWORK_ROUTE_TABLE_VALID_INDIRECT_LSP  0u
#define CVA_NETWORK_ROUTE_TABLE_VALID_INDIRECT_LEN  1u
#define CVA_NETWORK_ROUTE_TABLE_DIP_63_32_LSP       0u
#define CVA_NETWORK_ROUTE_TABLE_DIP_63_32_LEN       32u
#define CVA_NETWORK_ROUTE_TABLE_DIP_31_0_LSP        0u
#define CVA_NETWORK_ROUTE_TABLE_DIP_31_0_LEN        32u
#define CVA_NETWORK_ROUTE_TABLE_SIP_127_96_LSP      0u
#define CVA_NETWORK_ROUTE_TABLE_SIP_127_96_LEN      32u
#define CVA_NETWORK_ROUTE_TABLE_SIP_95_64_LSP       0u
#define CVA_NETWORK_ROUTE_TABLE_SIP_95_64_LEN       32u
#define CVA_NETWORK_ROUTE_TABLE_SIP_63_32_LSP       0u
#define CVA_NETWORK_ROUTE_TABLE_SIP_63_32_LEN       32u
#define CVA_NETWORK_ROUTE_TABLE_SIP_31_0_LSP        0u
#define CVA_NETWORK_ROUTE_TABLE_SIP_31_0_LEN        32u

#define CVA_MULTICAST_COL_TABLE_RESERVED1_LSP    19u
#define CVA_MULTICAST_COL_TABLE_RESERVED1_LEN    13u
#define CVA_MULTICAST_COL_TABLE_ARB_MODE_LSP     18u
#define CVA_MULTICAST_COL_TABLE_ARB_MODE_LEN     1u
#define CVA_MULTICAST_COL_TABLE_ARB_VALID_LSP    17u
#define CVA_MULTICAST_COL_TABLE_ARB_VALID_LEN    1u
#define CVA_MULTICAST_COL_TABLE_VID_LSP          5u
#define CVA_MULTICAST_COL_TABLE_VID_LEN          12u
#define CVA_MULTICAST_COL_TABLE_RPF_FAIL_ACT_LSP 3u
#define CVA_MULTICAST_COL_TABLE_RPF_FAIL_ACT_LEN 2u
#define CVA_MULTICAST_COL_TABLE_QOS_RPI_LSP      0u
#define CVA_MULTICAST_COL_TABLE_QOS_RPI_LEN      3u
#define CVA_MULTICAST_COL_TABLE_QOS_EN_LSP       31u
#define CVA_MULTICAST_COL_TABLE_QOS_EN_LEN       1u
#define CVA_MULTICAST_COL_TABLE_RPF_CHK_EN_LSP   30u
#define CVA_MULTICAST_COL_TABLE_RPF_CHK_EN_LEN   1u
#define CVA_MULTICAST_COL_TABLE_MTU_MAX_LSP      16u
#define CVA_MULTICAST_COL_TABLE_MTU_MAX_LEN      14u
#define CVA_MULTICAST_COL_TABLE_DPM_LSP          0u
#define CVA_MULTICAST_COL_TABLE_DPM_LEN          16u
#define CVA_MULTICAST_COL_TABLE_RESERVED2_LSP    31u
#define CVA_MULTICAST_COL_TABLE_RESERVED2_LEN    1u
#define CVA_MULTICAST_COL_TABLE_TTL_MIN_LSP      23u
#define CVA_MULTICAST_COL_TABLE_TTL_MIN_LEN      8u
#define CVA_MULTICAST_COL_TABLE_ACT_LSP          21u
#define CVA_MULTICAST_COL_TABLE_ACT_LEN          2u
#define CVA_MULTICAST_COL_TABLE_RH_IDX_LSP       9u
#define CVA_MULTICAST_COL_TABLE_RH_IDX_LEN       12u
#define CVA_MULTICAST_COL_TABLE_HIT_LSP          8u
#define CVA_MULTICAST_COL_TABLE_HIT_LEN          1u
#define CVA_MULTICAST_COL_TABLE_DPORT_FMT_LSP    6u
#define CVA_MULTICAST_COL_TABLE_DPORT_FMT_LEN    2u
#define CVA_MULTICAST_COL_TABLE_SPORT_FMT_LSP    4u
#define CVA_MULTICAST_COL_TABLE_SPORT_FMT_LEN    2u
#define CVA_MULTICAST_COL_TABLE_TYPE_LSP         1u
#define CVA_MULTICAST_COL_TABLE_TYPE_LEN         3u
#define CVA_MULTICAST_COL_TABLE_VALID_LSP        0u
#define CVA_MULTICAST_COL_TABLE_VALID_LEN        1u
#define CVA_MULTICAST_COL_TABLE_DPORT_LSP        16u
#define CVA_MULTICAST_COL_TABLE_DPORT_LEN        16u
#define CVA_MULTICAST_COL_TABLE_SPORT_LSP        0u
#define CVA_MULTICAST_COL_TABLE_SPORT_LEN        16u
#define CVA_MULTICAST_COL_TABLE_GIP_127_96_LSP   0u
#define CVA_MULTICAST_COL_TABLE_GIP_127_96_LEN   32u
#define CVA_MULTICAST_COL_TABLE_GIP_95_64_LSP    0u
#define CVA_MULTICAST_COL_TABLE_GIP_95_64_LEN    32u
#define CVA_MULTICAST_COL_TABLE_RESERVED3_LSP    0u
#define CVA_MULTICAST_COL_TABLE_RESERVED3_LEN    32u
#define CVA_MULTICAST_COL_TABLE_GIP_63_32_LSP    0u
#define CVA_MULTICAST_COL_TABLE_GIP_63_32_LEN    32u
#define CVA_MULTICAST_COL_TABLE_GIP_31_0_LSP     0u
#define CVA_MULTICAST_COL_TABLE_GIP_31_0_LEN     32u
#define CVA_MULTICAST_COL_TABLE_SIP_127_96_LSP   0u
#define CVA_MULTICAST_COL_TABLE_SIP_127_96_LEN   32u
#define CVA_MULTICAST_COL_TABLE_SIP_95_64_LSP    0u
#define CVA_MULTICAST_COL_TABLE_SIP_95_64_LEN    32u
#define CVA_MULTICAST_COL_TABLE_SIP_63_32_LSP    0u
#define CVA_MULTICAST_COL_TABLE_SIP_63_32_LEN    32u
#define CVA_MULTICAST_COL_TABLE_SIP_31_0_LSP     0u
#define CVA_MULTICAST_COL_TABLE_SIP_31_0_LEN     32u

#define CVA_NEXT_HOP_TABLE_RESERVED1_LSP 19u
#define CVA_NEXT_HOP_TABLE_RESERVED1_LEN 13u
#define CVA_NEXT_HOP_TABLE_L2_DA_IDX_LSP 6u
#define CVA_NEXT_HOP_TABLE_L2_DA_IDX_LEN 13u
#define CVA_NEXT_HOP_TABLE_EGRIF_IDX_LSP 0u
#define CVA_NEXT_HOP_TABLE_EGRIF_IDX_LEN 6u

#define CVA_QCI_HIT_COUNTER_COUNTER_63_32_LSP 0u
#define CVA_QCI_HIT_COUNTER_COUNTER_63_32_LEN 32u
#define CVA_QCI_HIT_COUNTER_COUNTER_31_0_LSP  0u
#define CVA_QCI_HIT_COUNTER_COUNTER_31_0_LEN  32u

#define CVA_QCI_GATE_PASS_COUNTER_COUNTER_63_32_LSP 0u
#define CVA_QCI_GATE_PASS_COUNTER_COUNTER_63_32_LEN 32u
#define CVA_QCI_GATE_PASS_COUNTER_COUNTER_31_0_LSP  0u
#define CVA_QCI_GATE_PASS_COUNTER_COUNTER_31_0_LEN  32u

#define CVA_QCI_GATE_DROP_COUNTER_COUNTER_63_32_LSP 0u
#define CVA_QCI_GATE_DROP_COUNTER_COUNTER_63_32_LEN 32u
#define CVA_QCI_GATE_DROP_COUNTER_COUNTER_31_0_LSP  0u
#define CVA_QCI_GATE_DROP_COUNTER_COUNTER_31_0_LEN  32u

#define CVA_QCI_SDU_PASS_COUNTER_COUNTER_63_32_LSP 0u
#define CVA_QCI_SDU_PASS_COUNTER_COUNTER_63_32_LEN 32u
#define CVA_QCI_SDU_PASS_COUNTER_COUNTER_31_0_LSP  0u
#define CVA_QCI_SDU_PASS_COUNTER_COUNTER_31_0_LEN  32u

#define CVA_QCI_SDU_DROP_COUNTER_COUNTER_63_32_LSP 0u
#define CVA_QCI_SDU_DROP_COUNTER_COUNTER_63_32_LEN 32u
#define CVA_QCI_SDU_DROP_COUNTER_COUNTER_31_0_LSP  0u
#define CVA_QCI_SDU_DROP_COUNTER_COUNTER_31_0_LEN  32u

#define CVA_QCI_METER_DROP_COUNTER_COUNTER_63_32_LSP 0u
#define CVA_QCI_METER_DROP_COUNTER_COUNTER_63_32_LEN 32u
#define CVA_QCI_METER_DROP_COUNTER_COUNTER_31_0_LSP  0u
#define CVA_QCI_METER_DROP_COUNTER_COUNTER_31_0_LEN  32u

#define CVA_QCI_GATE_FILTER_RESERVED1_LSP                 16u
#define CVA_QCI_GATE_FILTER_RESERVED1_LEN                 16u
#define CVA_QCI_GATE_FILTER_BASETIME_SECOND_MSB_47_32_LSP 0u
#define CVA_QCI_GATE_FILTER_BASETIME_SECOND_MSB_47_32_LEN 16u
#define CVA_QCI_GATE_FILTER_BASETIME_SECOND_LSB_31_0_LSP  0u
#define CVA_QCI_GATE_FILTER_BASETIME_SECOND_LSB_31_0_LEN  32u
#define CVA_QCI_GATE_FILTER_BASETIME_NANOSECOND_LSP       0u
#define CVA_QCI_GATE_FILTER_BASETIME_NANOSECOND_LEN       32u

#define CVA_QCI_CONTROL_LIST_INTERVAL_OCT_MAX_LSP         0u
#define CVA_QCI_CONTROL_LIST_INTERVAL_OCT_MAX_LEN         32u
#define CVA_QCI_CONTROL_LIST_TIMER_INTERVAL_LSP           0u
#define CVA_QCI_CONTROL_LIST_TIMER_INTERVAL_LEN           32u
#define CVA_QCI_CONTROL_LIST_RESERVED1_LSP                5u
#define CVA_QCI_CONTROL_LIST_RESERVED1_LEN                27u
#define CVA_QCI_CONTROL_LIST_BYPASS_INTERNAL_PRIORITY_LSP 4u
#define CVA_QCI_CONTROL_LIST_BYPASS_INTERNAL_PRIORITY_LEN 1u
#define CVA_QCI_CONTROL_LIST_INTERNAL_PRIORITY_LSP        1u
#define CVA_QCI_CONTROL_LIST_INTERNAL_PRIORITY_LEN        3u
#define CVA_QCI_CONTROL_LIST_GATE_STATE_LSP               0u
#define CVA_QCI_CONTROL_LIST_GATE_STATE_LEN               1u

#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY1_LSP  0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY1_LEN  32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY2_LSP  0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY2_LEN  32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY3_LSP  0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY3_LEN  32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY4_LSP  0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY4_LEN  32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY5_LSP  0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY5_LEN  32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY6_LSP  0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY6_LEN  32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY7_LSP  0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY7_LEN  32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY8_LSP  0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY8_LEN  32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY9_LSP  0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY9_LEN  32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY10_LSP 0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY10_LEN 32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY11_LSP 0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY11_LEN 32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY12_LSP 0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY12_LEN 32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY13_LSP 0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY13_LEN 32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY14_LSP 0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY14_LEN 32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY15_LSP 0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY15_LEN 32u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY16_LSP 0u
#define CVA_STATEFUL_LOOK_UP_TABLE_EMPTY16_LEN 32u

#define CVA_STATEFUL_BCAM_EMPTY1_LSP  0u
#define CVA_STATEFUL_BCAM_EMPTY1_LEN  32u
#define CVA_STATEFUL_BCAM_EMPTY2_LSP  0u
#define CVA_STATEFUL_BCAM_EMPTY2_LEN  32u
#define CVA_STATEFUL_BCAM_EMPTY3_LSP  0u
#define CVA_STATEFUL_BCAM_EMPTY3_LEN  32u
#define CVA_STATEFUL_BCAM_EMPTY4_LSP  0u
#define CVA_STATEFUL_BCAM_EMPTY4_LEN  32u
#define CVA_STATEFUL_BCAM_EMPTY5_LSP  0u
#define CVA_STATEFUL_BCAM_EMPTY5_LEN  32u
#define CVA_STATEFUL_BCAM_EMPTY6_LSP  0u
#define CVA_STATEFUL_BCAM_EMPTY6_LEN  32u
#define CVA_STATEFUL_BCAM_EMPTY7_LSP  0u
#define CVA_STATEFUL_BCAM_EMPTY7_LEN  32u
#define CVA_STATEFUL_BCAM_EMPTY8_LSP  0u
#define CVA_STATEFUL_BCAM_EMPTY8_LEN  32u
#define CVA_STATEFUL_BCAM_EMPTY9_LSP  0u
#define CVA_STATEFUL_BCAM_EMPTY9_LEN  32u
#define CVA_STATEFUL_BCAM_EMPTY10_LSP 0u
#define CVA_STATEFUL_BCAM_EMPTY10_LEN 32u

#define CVA_STATEFUL_BCAM_SUB_EMPTY1_LSP 0u
#define CVA_STATEFUL_BCAM_SUB_EMPTY1_LEN 32u
#define CVA_STATEFUL_BCAM_SUB_EMPTY2_LSP 0u
#define CVA_STATEFUL_BCAM_SUB_EMPTY2_LEN 32u
#define CVA_STATEFUL_BCAM_SUB_EMPTY3_LSP 0u
#define CVA_STATEFUL_BCAM_SUB_EMPTY3_LEN 32u
#define CVA_STATEFUL_BCAM_SUB_EMPTY4_LSP 0u
#define CVA_STATEFUL_BCAM_SUB_EMPTY4_LEN 32u
#define CVA_STATEFUL_BCAM_SUB_EMPTY5_LSP 0u
#define CVA_STATEFUL_BCAM_SUB_EMPTY5_LEN 32u
#define CVA_STATEFUL_BCAM_SUB_EMPTY6_LSP 0u
#define CVA_STATEFUL_BCAM_SUB_EMPTY6_LEN 32u

#define CVA_ACL_OVER_RATE_CNT_COUNTER_LSP   0u
#define CVA_ACL_OVER_RATE_CNT_COUNTER_LEN   32u
#define CVA_ACL_OVER_RATE_CNT_ENABLE_LSP    31u
#define CVA_ACL_OVER_RATE_CNT_ENABLE_LEN    1u
#define CVA_ACL_OVER_RATE_CNT_RESERVED1_LSP 30u
#define CVA_ACL_OVER_RATE_CNT_RESERVED1_LEN 1u
#define CVA_ACL_OVER_RATE_CNT_CNTMODE_LSP   0u
#define CVA_ACL_OVER_RATE_CNT_CNTMODE_LEN   1u

#define CVA_ACL_ABNORMAL_TIMES_MITIGATION_THRESHOLD_LSP 16u
#define CVA_ACL_ABNORMAL_TIMES_MITIGATION_THRESHOLD_LEN 16u
#define CVA_ACL_ABNORMAL_TIMES_COUNTER_LSP              0u
#define CVA_ACL_ABNORMAL_TIMES_COUNTER_LEN              16u
#define CVA_ACL_ABNORMAL_TIMES_RESERVED1_LSP            1u
#define CVA_ACL_ABNORMAL_TIMES_RESERVED1_LEN            31u
#define CVA_ACL_ABNORMAL_TIMES_ENABLE_ABNORMAL_LSP      0u
#define CVA_ACL_ABNORMAL_TIMES_ENABLE_ABNORMAL_LEN      1u

#define CVA_HEADER_DUMP_OFFSET_FIELD29_LSP  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD29_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD28_LSP  0u
#define CVA_HEADER_DUMP_OFFSET_FIELD28_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD27_LSP  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD27_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD26_LSP  0u
#define CVA_HEADER_DUMP_OFFSET_FIELD26_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD25_LSP  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD25_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD24_LSP  0u
#define CVA_HEADER_DUMP_OFFSET_FIELD24_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD23_LSP  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD23_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD22_LSP  0u
#define CVA_HEADER_DUMP_OFFSET_FIELD22_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD21_LSP  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD21_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD20_LSP  0u
#define CVA_HEADER_DUMP_OFFSET_FIELD20_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD19_LSP  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD19_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD18_LSP  0u
#define CVA_HEADER_DUMP_OFFSET_FIELD18_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD17_LSP  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD17_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD16_LSP  0u
#define CVA_HEADER_DUMP_OFFSET_FIELD16_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD15_LSP  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD15_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD14_LSP  0u
#define CVA_HEADER_DUMP_OFFSET_FIELD14_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD13_LSP  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD13_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD12_LSP  0u
#define CVA_HEADER_DUMP_OFFSET_FIELD12_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD11_LSP  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD11_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD10_LSP  0u
#define CVA_HEADER_DUMP_OFFSET_FIELD10_LEN  16u
#define CVA_HEADER_DUMP_OFFSET_FIELD9_LSP   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD9_LEN   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD8_LSP   0u
#define CVA_HEADER_DUMP_OFFSET_FIELD8_LEN   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD7_LSP   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD7_LEN   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD6_LSP   0u
#define CVA_HEADER_DUMP_OFFSET_FIELD6_LEN   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD5_LSP   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD5_LEN   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD4_LSP   0u
#define CVA_HEADER_DUMP_OFFSET_FIELD4_LEN   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD3_LSP   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD3_LEN   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD2_LSP   0u
#define CVA_HEADER_DUMP_OFFSET_FIELD2_LEN   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD1_LSP   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD1_LEN   16u
#define CVA_HEADER_DUMP_OFFSET_FIELD0_LSP   0u
#define CVA_HEADER_DUMP_OFFSET_FIELD0_LEN   16u
#define CVA_HEADER_DUMP_RESERVED1_LSP       16u
#define CVA_HEADER_DUMP_RESERVED1_LEN       16u
#define CVA_HEADER_DUMP_ETHERTYPE_LSP       0u
#define CVA_HEADER_DUMP_ETHERTYPE_LEN       16u
#define CVA_HEADER_DUMP_ITAG_VID_LSP        20u
#define CVA_HEADER_DUMP_ITAG_VID_LEN        12u
#define CVA_HEADER_DUMP_ITAG_CFI_LSP        19u
#define CVA_HEADER_DUMP_ITAG_CFI_LEN        1u
#define CVA_HEADER_DUMP_ITAG_PCP_LSP        16u
#define CVA_HEADER_DUMP_ITAG_PCP_LEN        3u
#define CVA_HEADER_DUMP_RESERVED2_LSP       1u
#define CVA_HEADER_DUMP_RESERVED2_LEN       15u
#define CVA_HEADER_DUMP_ITAG_EXIST_LSP      0u
#define CVA_HEADER_DUMP_ITAG_EXIST_LEN      1u
#define CVA_HEADER_DUMP_OTAG_VID_LSP        20u
#define CVA_HEADER_DUMP_OTAG_VID_LEN        12u
#define CVA_HEADER_DUMP_OTAG_CFI_LSP        19u
#define CVA_HEADER_DUMP_OTAG_CFI_LEN        1u
#define CVA_HEADER_DUMP_OTAG_PCP_LSP        16u
#define CVA_HEADER_DUMP_OTAG_PCP_LEN        3u
#define CVA_HEADER_DUMP_RESERVED3_LSP       1u
#define CVA_HEADER_DUMP_RESERVED3_LEN       15u
#define CVA_HEADER_DUMP_OTAG_EXIST_LSP      0u
#define CVA_HEADER_DUMP_OTAG_EXIST_LEN      1u
#define CVA_HEADER_DUMP_RESERVED4_LSP       16u
#define CVA_HEADER_DUMP_RESERVED4_LEN       16u
#define CVA_HEADER_DUMP_SA_47_32_LSP        0u
#define CVA_HEADER_DUMP_SA_47_32_LEN        16u
#define CVA_HEADER_DUMP_SA_31_0_LSP         0u
#define CVA_HEADER_DUMP_SA_31_0_LEN         32u
#define CVA_HEADER_DUMP_RESERVED5_LSP       0u
#define CVA_HEADER_DUMP_RESERVED5_LEN       32u
#define CVA_HEADER_DUMP_RESERVED6_LSP       16u
#define CVA_HEADER_DUMP_RESERVED6_LEN       16u
#define CVA_HEADER_DUMP_DA_47_32_LSP        0u
#define CVA_HEADER_DUMP_DA_47_32_LEN        16u
#define CVA_HEADER_DUMP_DA_31_0_LSP         0u
#define CVA_HEADER_DUMP_DA_31_0_LEN         32u
#define CVA_HEADER_DUMP_RESERVED7_LSP       26u
#define CVA_HEADER_DUMP_RESERVED7_LEN       6u
#define CVA_HEADER_DUMP_EACLIDX_LSP         16u
#define CVA_HEADER_DUMP_EACLIDX_LEN         10u
#define CVA_HEADER_DUMP_RESERVED8_LSP       10u
#define CVA_HEADER_DUMP_RESERVED8_LEN       6u
#define CVA_HEADER_DUMP_IACLIDX_LSP         0u
#define CVA_HEADER_DUMP_IACLIDX_LEN         10u
#define CVA_HEADER_DUMP_RESERVED9_LSP       16u
#define CVA_HEADER_DUMP_RESERVED9_LEN       16u
#define CVA_HEADER_DUMP_TIMESTAMP_47_32_LSP 0u
#define CVA_HEADER_DUMP_TIMESTAMP_47_32_LEN 16u
#define CVA_HEADER_DUMP_TIMESTAMP_31_0_LSP  0u
#define CVA_HEADER_DUMP_TIMESTAMP_31_0_LEN  32u
#define CVA_HEADER_DUMP_RESERVED10_LSP      4u
#define CVA_HEADER_DUMP_RESERVED10_LEN      28u
#define CVA_HEADER_DUMP_SPHY_LSP            0u
#define CVA_HEADER_DUMP_SPHY_LEN            4u

#define CVA_TIMESTAMP_DISCARD_RESERVED1_LSP    1u
#define CVA_TIMESTAMP_DISCARD_RESERVED1_LEN    31u
#define CVA_TIMESTAMP_DISCARD_GUARD_OF_LSP     0u
#define CVA_TIMESTAMP_DISCARD_GUARD_OF_LEN     1u
#define CVA_TIMESTAMP_DISCARD_RESERVED2_LSP    0u
#define CVA_TIMESTAMP_DISCARD_RESERVED2_LEN    32u
#define CVA_TIMESTAMP_DISCARD_GUARD_END_LSP    0u
#define CVA_TIMESTAMP_DISCARD_GUARD_END_LEN    32u
#define CVA_TIMESTAMP_DISCARD_RESERVED3_LSP    1u
#define CVA_TIMESTAMP_DISCARD_RESERVED3_LEN    31u
#define CVA_TIMESTAMP_DISCARD_MONITOR_OF_LSP   0u
#define CVA_TIMESTAMP_DISCARD_MONITOR_OF_LEN   1u
#define CVA_TIMESTAMP_DISCARD_MONITOR_END_LSP  0u
#define CVA_TIMESTAMP_DISCARD_MONITOR_END_LEN  32u
#define CVA_TIMESTAMP_DISCARD_GUARD_TIME_LSP   0u
#define CVA_TIMESTAMP_DISCARD_GUARD_TIME_LEN   32u
#define CVA_TIMESTAMP_DISCARD_MONITOR_TIME_LSP 0u
#define CVA_TIMESTAMP_DISCARD_MONITOR_TIME_LEN 32u
#define CVA_TIMESTAMP_DISCARD_RESERVED4_LSP    20u
#define CVA_TIMESTAMP_DISCARD_RESERVED4_LEN    12u
#define CVA_TIMESTAMP_DISCARD_THRESHOLD_LSP    16u
#define CVA_TIMESTAMP_DISCARD_THRESHOLD_LEN    4u
#define CVA_TIMESTAMP_DISCARD_RESERVED5_LSP    6u
#define CVA_TIMESTAMP_DISCARD_RESERVED5_LEN    10u
#define CVA_TIMESTAMP_DISCARD_GUARD_RUN_LSP    5u
#define CVA_TIMESTAMP_DISCARD_GUARD_RUN_LEN    1u
#define CVA_TIMESTAMP_DISCARD_MONITOR_RUN_LSP  4u
#define CVA_TIMESTAMP_DISCARD_MONITOR_RUN_LEN  1u
#define CVA_TIMESTAMP_DISCARD_RESERVED6_LSP    1u
#define CVA_TIMESTAMP_DISCARD_RESERVED6_LEN    3u
#define CVA_TIMESTAMP_DISCARD_ENABLE_LSP       0u
#define CVA_TIMESTAMP_DISCARD_ENABLE_LEN       1u

#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_479_448_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_479_448_LEN 32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_447_416_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_447_416_LEN 32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_415_384_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_415_384_LEN 32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_383_352_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_383_352_LEN 32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_351_320_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_351_320_LEN 32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_319_288_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_319_288_LEN 32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_287_256_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_287_256_LEN 32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_255_224_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_255_224_LEN 32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_223_192_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_223_192_LEN 32u
#define CVA_HOST_GROUP_TABLE_RESERVED1_LSP             0u
#define CVA_HOST_GROUP_TABLE_RESERVED1_LEN             32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_191_160_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_191_160_LEN 32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_159_128_LSP 0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_159_128_LEN 32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_127_96_LSP  0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_127_96_LEN  32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_95_64_LSP   0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_95_64_LEN   32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_63_32_LSP   0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_63_32_LEN   32u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_31_0_LSP    0u
#define CVA_HOST_GROUP_TABLE_HOST_GRP_WDAT_31_0_LEN    32u

#define CVA_QCI_STREAM_FILTER_BYPASS_MAX_SDU_LSP    31u
#define CVA_QCI_STREAM_FILTER_BYPASS_MAX_SDU_LEN    1u
#define CVA_QCI_STREAM_FILTER_MAX_SDU_LSP           16u
#define CVA_QCI_STREAM_FILTER_MAX_SDU_LEN           15u
#define CVA_QCI_STREAM_FILTER_BYPASS_FLOW_METER_LSP 15u
#define CVA_QCI_STREAM_FILTER_BYPASS_FLOW_METER_LEN 1u
#define CVA_QCI_STREAM_FILTER_FLOW_METER_ID_LSP     8u
#define CVA_QCI_STREAM_FILTER_FLOW_METER_ID_LEN     7u
#define CVA_QCI_STREAM_FILTER_STREAM_GATE_ID_LSP    0u
#define CVA_QCI_STREAM_FILTER_STREAM_GATE_ID_LEN    8u
typedef enum
{
    CVA_VLAN = 0,
    CVA_RESERVED,
    CVA_L2_TABLE,
    CVA_LUT_BCAM,
    CVA_ACTION_TABLE,
    CVA_ACL_COUNTER,
    CVA_POLICER,
    CVA_PIE_TABLE,
    CVA_GROUP,
    CVA_QBV_GATE_CONTROL_LIST_TABLE,
    CVA_QBV_SERIAL_GATE_OPEN_TIME_TABLE = 10,
    CVA_STREAM_IDENTIFICATION_TABLE,
    CVA_CB_LOOK_UP_TABLE,
    CVA_CB_SEQUENCY_RECOVERY_TABLE,
    CVA_CB_HISTORY_TABLE,
    CVA_RH_TABLE,
    CVA_OIL_TABLE,
    CVA_EGIF_TABLE,
    CVA_INGIF_TABLE,
    CVA_HOST_ROUTE_TABLE,
    CVA_NETWORK_ROUTE_TABLE = 20,
    CVA_MULTICAST_COL_TABLE,
    CVA_NEXT_HOP_TABLE,
    CVA_QCI_HIT_COUNTER,
    CVA_QCI_GATE_PASS_COUNTER,
    CVA_QCI_GATE_DROP_COUNTER,
    CVA_QCI_SDU_PASS_COUNTER,
    CVA_QCI_SDU_DROP_COUNTER,
    CVA_QCI_METER_DROP_COUNTER,
    CVA_QCI_GATE_FILTER,
    CVA_QCI_CONTROL_LIST = 30,
    CVA_STATEFUL_LOOK_UP_TABLE,
    CVA_STATEFUL_BCAM,
    CVA_STATEFUL_BCAM_SUB,
    CVA_ACL_OVER_RATE_CNT,
    CVA_ACL_ABNORMAL_TIMES,
    CVA_HEADER_DUMP,
    CVA_TIMESTAMP_DISCARD,
    CVA_HOST_GROUP_TABLE,
    CVA_QCI_STREAM_FILTER,

    CVA_TABLE_LIST_END = 40
} cva_table_list_t;

typedef struct
{
    uint16 lsp; /* LSP of the field */
    uint16 len; /* field length */
} cva_tableField_t;

typedef struct
{
    uint32            type;        /* access table type */
    uint32            size;        /* table size */
    uint32            datareg_num; /* total data registers */
    uint32            field_num;   /* total field numbers */
    cva_tableField_t *fields;      /* table fields */
} cva_table_t;

#ifdef RTK_INTERNAL_DEV
extern RtkApiRet cva_table_read_internal(uint32 unit, cva_table_list_t table, uint32 addr, uint32 *data);
extern RtkApiRet cva_table_write_internal(uint32 unit, cva_table_list_t table, uint32 addr, const uint32 *data);
#else
extern RtkApiRet cva_table_read(uint32 unit, cva_table_list_t table, uint32 addr, uint32 *data);
extern RtkApiRet cva_table_write(uint32 unit, cva_table_list_t table, uint32 addr, const uint32 *data);
#endif /* RTK_INTERNAL_DEV */
extern RtkApiRet         cva_table_burst_read(uint32 unit, cva_table_list_t table, uint32 addr, uint32 *data, uint32 entryNum);
extern const cva_table_t cva_table_list[];

#endif /* __RTL906X_TABLE_STRUCT_H__ */