/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_LIST_FILE_SERDES_WRAP_SDS_H_
#define DVA_RTKAS_REG_LIST_FILE_SERDES_WRAP_SDS_H_

#ifdef DVA_FILE_SERDES_WRAP_SDS
/* File: serdes_wrap_sds */
#define DVA_PCS_CTL_REG_0                                      0x4A560000u
#define DVA_PCS_CTL_REG_0_FIELDNUM                             6u
#define DVA_PCS_CTL_REG_0_DEFAULTVAL                           0x0u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_PCS_CTL                  0x4AD60000u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM         6u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL       0x0u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_PCS_CTL                  0x4AD60800u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM         6u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL       0x0u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_PCS_CTL                  0x4AD61000u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM         6u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL       0x0u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_PCS_CTL                  0x4AD61800u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM         6u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL       0x0u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_PCS_CTL                  0x4AD62000u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM         6u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL       0x0u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_PCS_CTL                  0x4AD62800u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM         6u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL       0x0u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_PCS_CTL                  0x4AD63000u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM         6u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL       0x0u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_PCS_CTL                  0x4AD63800u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM         6u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL       0x0u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_PCS_CTL                  0x4AD64000u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM         6u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL       0x0u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_PCS_CTL                  0x4AD64800u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM         6u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL       0x0u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_PCS_CTL                 0x4AD65000u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM        6u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL      0x0u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_PCS_CTL                 0x4AD65800u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM        6u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL      0x0u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_PCS_CTL                 0x4AD66000u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM        6u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL      0x0u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_PCS_CTL                 0x4AD66800u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM        6u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL      0x0u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_PCS_CTL                 0x4AD67000u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM        6u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL      0x0u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_PCS_CTL                 0x4AD67800u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_PCS_CTL_FIELDNUM        6u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_PCS_CTL_DEFAULTVAL      0x0u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_PCS_DATA                 0x4AD60004u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM        2u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL      0x0u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_PCS_DATA                 0x4AD60804u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM        2u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL      0x0u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_PCS_DATA                 0x4AD61004u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM        2u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL      0x0u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_PCS_DATA                 0x4AD61804u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM        2u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL      0x0u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_PCS_DATA                 0x4AD62004u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM        2u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL      0x0u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_PCS_DATA                 0x4AD62804u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM        2u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL      0x0u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_PCS_DATA                 0x4AD63004u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM        2u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL      0x0u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_PCS_DATA                 0x4AD63804u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM        2u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL      0x0u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_PCS_DATA                 0x4AD64004u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM        2u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL      0x0u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_PCS_DATA                 0x4AD64804u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM        2u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL      0x0u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_PCS_DATA                0x4AD65004u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM       2u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL     0x0u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_PCS_DATA                0x4AD65804u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM       2u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL     0x0u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_PCS_DATA                0x4AD66004u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM       2u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL     0x0u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_PCS_DATA                0x4AD66804u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM       2u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL     0x0u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_PCS_DATA                0x4AD67004u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM       2u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL     0x0u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_PCS_DATA                0x4AD67804u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_PCS_DATA_FIELDNUM       2u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_PCS_DATA_DEFAULTVAL     0x0u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_DPHY_CTL                 0x4AD60008u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM        6u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL      0x0u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_DPHY_CTL                 0x4AD60808u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM        6u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL      0x0u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_DPHY_CTL                 0x4AD61008u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM        6u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL      0x0u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_DPHY_CTL                 0x4AD61808u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM        6u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL      0x0u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_DPHY_CTL                 0x4AD62008u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM        6u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL      0x0u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_DPHY_CTL                 0x4AD62808u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM        6u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL      0x0u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_DPHY_CTL                 0x4AD63008u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM        6u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL      0x0u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_DPHY_CTL                 0x4AD63808u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM        6u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL      0x0u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_DPHY_CTL                 0x4AD64008u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM        6u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL      0x0u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_DPHY_CTL                 0x4AD64808u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM        6u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL      0x0u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_DPHY_CTL                0x4AD65008u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM       6u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL     0x0u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_DPHY_CTL                0x4AD65808u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM       6u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL     0x0u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_DPHY_CTL                0x4AD66008u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM       6u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL     0x0u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_DPHY_CTL                0x4AD66808u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM       6u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL     0x0u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_DPHY_CTL                0x4AD67008u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM       6u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL     0x0u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_DPHY_CTL                0x4AD67808u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_DPHY_CTL_FIELDNUM       6u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_DPHY_CTL_DEFAULTVAL     0x0u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_DPHY_DATA                0x4AD6000Cu
#define DVA_PORT0_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM       2u
#define DVA_PORT0_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL     0x0u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_DPHY_DATA                0x4AD6080Cu
#define DVA_PORT1_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM       2u
#define DVA_PORT1_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL     0x0u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_DPHY_DATA                0x4AD6100Cu
#define DVA_PORT2_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM       2u
#define DVA_PORT2_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL     0x0u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_DPHY_DATA                0x4AD6180Cu
#define DVA_PORT3_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM       2u
#define DVA_PORT3_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL     0x0u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_DPHY_DATA                0x4AD6200Cu
#define DVA_PORT4_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM       2u
#define DVA_PORT4_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL     0x0u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_DPHY_DATA                0x4AD6280Cu
#define DVA_PORT5_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM       2u
#define DVA_PORT5_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL     0x0u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_DPHY_DATA                0x4AD6300Cu
#define DVA_PORT6_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM       2u
#define DVA_PORT6_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL     0x0u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_DPHY_DATA                0x4AD6380Cu
#define DVA_PORT7_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM       2u
#define DVA_PORT7_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL     0x0u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_DPHY_DATA                0x4AD6400Cu
#define DVA_PORT8_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM       2u
#define DVA_PORT8_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL     0x0u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_DPHY_DATA                0x4AD6480Cu
#define DVA_PORT9_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM       2u
#define DVA_PORT9_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL     0x0u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_DPHY_DATA               0x4AD6500Cu
#define DVA_PORT10_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM      2u
#define DVA_PORT10_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL    0x0u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_DPHY_DATA               0x4AD6580Cu
#define DVA_PORT11_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM      2u
#define DVA_PORT11_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL    0x0u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_DPHY_DATA               0x4AD6600Cu
#define DVA_PORT12_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM      2u
#define DVA_PORT12_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL    0x0u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_DPHY_DATA               0x4AD6680Cu
#define DVA_PORT13_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM      2u
#define DVA_PORT13_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL    0x0u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_DPHY_DATA               0x4AD6700Cu
#define DVA_PORT14_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM      2u
#define DVA_PORT14_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL    0x0u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_DPHY_DATA               0x4AD6780Cu
#define DVA_PORT15_INDIRECT_ACCESS_SDS_DPHY_DATA_FIELDNUM      2u
#define DVA_PORT15_INDIRECT_ACCESS_SDS_DPHY_DATA_DEFAULTVAL    0x0u
#define DVA_PORT0_SDS_CTRL_REG_0                               0x4AD60010u
#define DVA_PORT0_SDS_CTRL_REG_0_FIELDNUM                      19u
#define DVA_PORT0_SDS_CTRL_REG_0_DEFAULTVAL                    0x27FEu
#define DVA_PORT1_SDS_CTRL_REG_0                               0x4AD60810u
#define DVA_PORT1_SDS_CTRL_REG_0_FIELDNUM                      19u
#define DVA_PORT1_SDS_CTRL_REG_0_DEFAULTVAL                    0x27FEu
#define DVA_PORT2_SDS_CTRL_REG_0                               0x4AD61010u
#define DVA_PORT2_SDS_CTRL_REG_0_FIELDNUM                      19u
#define DVA_PORT2_SDS_CTRL_REG_0_DEFAULTVAL                    0x27FEu
#define DVA_PORT3_SDS_CTRL_REG_0                               0x4AD61810u
#define DVA_PORT3_SDS_CTRL_REG_0_FIELDNUM                      19u
#define DVA_PORT3_SDS_CTRL_REG_0_DEFAULTVAL                    0x27FEu
#define DVA_PORT4_SDS_CTRL_REG_0                               0x4AD62010u
#define DVA_PORT4_SDS_CTRL_REG_0_FIELDNUM                      19u
#define DVA_PORT4_SDS_CTRL_REG_0_DEFAULTVAL                    0x27FEu
#define DVA_PORT5_SDS_CTRL_REG_0                               0x4AD62810u
#define DVA_PORT5_SDS_CTRL_REG_0_FIELDNUM                      19u
#define DVA_PORT5_SDS_CTRL_REG_0_DEFAULTVAL                    0x27FEu
#define DVA_PORT6_SDS_CTRL_REG_0                               0x4AD63010u
#define DVA_PORT6_SDS_CTRL_REG_0_FIELDNUM                      19u
#define DVA_PORT6_SDS_CTRL_REG_0_DEFAULTVAL                    0x27FEu
#define DVA_PORT7_SDS_CTRL_REG_0                               0x4AD63810u
#define DVA_PORT7_SDS_CTRL_REG_0_FIELDNUM                      19u
#define DVA_PORT7_SDS_CTRL_REG_0_DEFAULTVAL                    0x27FEu
#define DVA_PORT8_SDS_CTRL_REG_0                               0x4AD64010u
#define DVA_PORT8_SDS_CTRL_REG_0_FIELDNUM                      19u
#define DVA_PORT8_SDS_CTRL_REG_0_DEFAULTVAL                    0x27FEu
#define DVA_PORT9_SDS_CTRL_REG_0                               0x4AD64810u
#define DVA_PORT9_SDS_CTRL_REG_0_FIELDNUM                      19u
#define DVA_PORT9_SDS_CTRL_REG_0_DEFAULTVAL                    0x27FEu
#define DVA_PORT10_SDS_CTRL_REG_0                              0x4AD65010u
#define DVA_PORT10_SDS_CTRL_REG_0_FIELDNUM                     19u
#define DVA_PORT10_SDS_CTRL_REG_0_DEFAULTVAL                   0x27FEu
#define DVA_PORT11_SDS_CTRL_REG_0                              0x4AD65810u
#define DVA_PORT11_SDS_CTRL_REG_0_FIELDNUM                     19u
#define DVA_PORT11_SDS_CTRL_REG_0_DEFAULTVAL                   0x27FEu
#define DVA_PORT12_SDS_CTRL_REG_0                              0x4AD66010u
#define DVA_PORT12_SDS_CTRL_REG_0_FIELDNUM                     19u
#define DVA_PORT12_SDS_CTRL_REG_0_DEFAULTVAL                   0x27FEu
#define DVA_PORT13_SDS_CTRL_REG_0                              0x4AD66810u
#define DVA_PORT13_SDS_CTRL_REG_0_FIELDNUM                     19u
#define DVA_PORT13_SDS_CTRL_REG_0_DEFAULTVAL                   0x27FEu
#define DVA_PORT14_SDS_CTRL_REG_0                              0x4AD67010u
#define DVA_PORT14_SDS_CTRL_REG_0_FIELDNUM                     19u
#define DVA_PORT14_SDS_CTRL_REG_0_DEFAULTVAL                   0x27FEu
#define DVA_PORT15_SDS_CTRL_REG_0                              0x4AD67810u
#define DVA_PORT15_SDS_CTRL_REG_0_FIELDNUM                     19u
#define DVA_PORT15_SDS_CTRL_REG_0_DEFAULTVAL                   0x27FEu
#define DVA_PORT0_SDS_CTRL_REG_1                               0x4AD60014u
#define DVA_PORT0_SDS_CTRL_REG_1_FIELDNUM                      4u
#define DVA_PORT0_SDS_CTRL_REG_1_DEFAULTVAL                    0x0u
#define DVA_PORT1_SDS_CTRL_REG_1                               0x4AD60814u
#define DVA_PORT1_SDS_CTRL_REG_1_FIELDNUM                      4u
#define DVA_PORT1_SDS_CTRL_REG_1_DEFAULTVAL                    0x0u
#define DVA_PORT2_SDS_CTRL_REG_1                               0x4AD61014u
#define DVA_PORT2_SDS_CTRL_REG_1_FIELDNUM                      4u
#define DVA_PORT2_SDS_CTRL_REG_1_DEFAULTVAL                    0x0u
#define DVA_PORT3_SDS_CTRL_REG_1                               0x4AD61814u
#define DVA_PORT3_SDS_CTRL_REG_1_FIELDNUM                      4u
#define DVA_PORT3_SDS_CTRL_REG_1_DEFAULTVAL                    0x0u
#define DVA_PORT4_SDS_CTRL_REG_1                               0x4AD62014u
#define DVA_PORT4_SDS_CTRL_REG_1_FIELDNUM                      4u
#define DVA_PORT4_SDS_CTRL_REG_1_DEFAULTVAL                    0x0u
#define DVA_PORT5_SDS_CTRL_REG_1                               0x4AD62814u
#define DVA_PORT5_SDS_CTRL_REG_1_FIELDNUM                      4u
#define DVA_PORT5_SDS_CTRL_REG_1_DEFAULTVAL                    0x0u
#define DVA_PORT6_SDS_CTRL_REG_1                               0x4AD63014u
#define DVA_PORT6_SDS_CTRL_REG_1_FIELDNUM                      4u
#define DVA_PORT6_SDS_CTRL_REG_1_DEFAULTVAL                    0x0u
#define DVA_PORT7_SDS_CTRL_REG_1                               0x4AD63814u
#define DVA_PORT7_SDS_CTRL_REG_1_FIELDNUM                      4u
#define DVA_PORT7_SDS_CTRL_REG_1_DEFAULTVAL                    0x0u
#define DVA_PORT8_SDS_CTRL_REG_1                               0x4AD64014u
#define DVA_PORT8_SDS_CTRL_REG_1_FIELDNUM                      4u
#define DVA_PORT8_SDS_CTRL_REG_1_DEFAULTVAL                    0x0u
#define DVA_PORT9_SDS_CTRL_REG_1                               0x4AD64814u
#define DVA_PORT9_SDS_CTRL_REG_1_FIELDNUM                      4u
#define DVA_PORT9_SDS_CTRL_REG_1_DEFAULTVAL                    0x0u
#define DVA_PORT10_SDS_CTRL_REG_1                              0x4AD65014u
#define DVA_PORT10_SDS_CTRL_REG_1_FIELDNUM                     4u
#define DVA_PORT10_SDS_CTRL_REG_1_DEFAULTVAL                   0x0u
#define DVA_PORT11_SDS_CTRL_REG_1                              0x4AD65814u
#define DVA_PORT11_SDS_CTRL_REG_1_FIELDNUM                     4u
#define DVA_PORT11_SDS_CTRL_REG_1_DEFAULTVAL                   0x0u
#define DVA_PORT12_SDS_CTRL_REG_1                              0x4AD66014u
#define DVA_PORT12_SDS_CTRL_REG_1_FIELDNUM                     4u
#define DVA_PORT12_SDS_CTRL_REG_1_DEFAULTVAL                   0x0u
#define DVA_PORT13_SDS_CTRL_REG_1                              0x4AD66814u
#define DVA_PORT13_SDS_CTRL_REG_1_FIELDNUM                     4u
#define DVA_PORT13_SDS_CTRL_REG_1_DEFAULTVAL                   0x0u
#define DVA_PORT14_SDS_CTRL_REG_1                              0x4AD67014u
#define DVA_PORT14_SDS_CTRL_REG_1_FIELDNUM                     4u
#define DVA_PORT14_SDS_CTRL_REG_1_DEFAULTVAL                   0x0u
#define DVA_PORT15_SDS_CTRL_REG_1                              0x4AD67814u
#define DVA_PORT15_SDS_CTRL_REG_1_FIELDNUM                     4u
#define DVA_PORT15_SDS_CTRL_REG_1_DEFAULTVAL                   0x0u
#define DVA_PORT0_SDS_CTRL_REG_2                               0x4AD60018u
#define DVA_PORT0_SDS_CTRL_REG_2_FIELDNUM                      4u
#define DVA_PORT0_SDS_CTRL_REG_2_DEFAULTVAL                    0x0u
#define DVA_PORT1_SDS_CTRL_REG_2                               0x4AD60818u
#define DVA_PORT1_SDS_CTRL_REG_2_FIELDNUM                      4u
#define DVA_PORT1_SDS_CTRL_REG_2_DEFAULTVAL                    0x0u
#define DVA_PORT2_SDS_CTRL_REG_2                               0x4AD61018u
#define DVA_PORT2_SDS_CTRL_REG_2_FIELDNUM                      4u
#define DVA_PORT2_SDS_CTRL_REG_2_DEFAULTVAL                    0x0u
#define DVA_PORT3_SDS_CTRL_REG_2                               0x4AD61818u
#define DVA_PORT3_SDS_CTRL_REG_2_FIELDNUM                      4u
#define DVA_PORT3_SDS_CTRL_REG_2_DEFAULTVAL                    0x0u
#define DVA_PORT4_SDS_CTRL_REG_2                               0x4AD62018u
#define DVA_PORT4_SDS_CTRL_REG_2_FIELDNUM                      4u
#define DVA_PORT4_SDS_CTRL_REG_2_DEFAULTVAL                    0x0u
#define DVA_PORT5_SDS_CTRL_REG_2                               0x4AD62818u
#define DVA_PORT5_SDS_CTRL_REG_2_FIELDNUM                      4u
#define DVA_PORT5_SDS_CTRL_REG_2_DEFAULTVAL                    0x0u
#define DVA_PORT6_SDS_CTRL_REG_2                               0x4AD63018u
#define DVA_PORT6_SDS_CTRL_REG_2_FIELDNUM                      4u
#define DVA_PORT6_SDS_CTRL_REG_2_DEFAULTVAL                    0x0u
#define DVA_PORT7_SDS_CTRL_REG_2                               0x4AD63818u
#define DVA_PORT7_SDS_CTRL_REG_2_FIELDNUM                      4u
#define DVA_PORT7_SDS_CTRL_REG_2_DEFAULTVAL                    0x0u
#define DVA_PORT8_SDS_CTRL_REG_2                               0x4AD64018u
#define DVA_PORT8_SDS_CTRL_REG_2_FIELDNUM                      4u
#define DVA_PORT8_SDS_CTRL_REG_2_DEFAULTVAL                    0x0u
#define DVA_PORT9_SDS_CTRL_REG_2                               0x4AD64818u
#define DVA_PORT9_SDS_CTRL_REG_2_FIELDNUM                      4u
#define DVA_PORT9_SDS_CTRL_REG_2_DEFAULTVAL                    0x0u
#define DVA_PORT10_SDS_CTRL_REG_2                              0x4AD65018u
#define DVA_PORT10_SDS_CTRL_REG_2_FIELDNUM                     4u
#define DVA_PORT10_SDS_CTRL_REG_2_DEFAULTVAL                   0x0u
#define DVA_PORT11_SDS_CTRL_REG_2                              0x4AD65818u
#define DVA_PORT11_SDS_CTRL_REG_2_FIELDNUM                     4u
#define DVA_PORT11_SDS_CTRL_REG_2_DEFAULTVAL                   0x0u
#define DVA_PORT12_SDS_CTRL_REG_2                              0x4AD66018u
#define DVA_PORT12_SDS_CTRL_REG_2_FIELDNUM                     4u
#define DVA_PORT12_SDS_CTRL_REG_2_DEFAULTVAL                   0x0u
#define DVA_PORT13_SDS_CTRL_REG_2                              0x4AD66818u
#define DVA_PORT13_SDS_CTRL_REG_2_FIELDNUM                     4u
#define DVA_PORT13_SDS_CTRL_REG_2_DEFAULTVAL                   0x0u
#define DVA_PORT14_SDS_CTRL_REG_2                              0x4AD67018u
#define DVA_PORT14_SDS_CTRL_REG_2_FIELDNUM                     4u
#define DVA_PORT14_SDS_CTRL_REG_2_DEFAULTVAL                   0x0u
#define DVA_PORT15_SDS_CTRL_REG_2                              0x4AD67818u
#define DVA_PORT15_SDS_CTRL_REG_2_FIELDNUM                     4u
#define DVA_PORT15_SDS_CTRL_REG_2_DEFAULTVAL                   0x0u
#define DVA_PORT0_SDS_CTRL_REG_3                               0x4AD6001Cu
#define DVA_PORT0_SDS_CTRL_REG_3_FIELDNUM                      8u
#define DVA_PORT0_SDS_CTRL_REG_3_DEFAULTVAL                    0x0u
#define DVA_PORT1_SDS_CTRL_REG_3                               0x4AD6081Cu
#define DVA_PORT1_SDS_CTRL_REG_3_FIELDNUM                      8u
#define DVA_PORT1_SDS_CTRL_REG_3_DEFAULTVAL                    0x0u
#define DVA_PORT2_SDS_CTRL_REG_3                               0x4AD6101Cu
#define DVA_PORT2_SDS_CTRL_REG_3_FIELDNUM                      8u
#define DVA_PORT2_SDS_CTRL_REG_3_DEFAULTVAL                    0x0u
#define DVA_PORT3_SDS_CTRL_REG_3                               0x4AD6181Cu
#define DVA_PORT3_SDS_CTRL_REG_3_FIELDNUM                      8u
#define DVA_PORT3_SDS_CTRL_REG_3_DEFAULTVAL                    0x0u
#define DVA_PORT4_SDS_CTRL_REG_3                               0x4AD6201Cu
#define DVA_PORT4_SDS_CTRL_REG_3_FIELDNUM                      8u
#define DVA_PORT4_SDS_CTRL_REG_3_DEFAULTVAL                    0x0u
#define DVA_PORT5_SDS_CTRL_REG_3                               0x4AD6281Cu
#define DVA_PORT5_SDS_CTRL_REG_3_FIELDNUM                      8u
#define DVA_PORT5_SDS_CTRL_REG_3_DEFAULTVAL                    0x0u
#define DVA_PORT6_SDS_CTRL_REG_3                               0x4AD6301Cu
#define DVA_PORT6_SDS_CTRL_REG_3_FIELDNUM                      8u
#define DVA_PORT6_SDS_CTRL_REG_3_DEFAULTVAL                    0x0u
#define DVA_PORT7_SDS_CTRL_REG_3                               0x4AD6381Cu
#define DVA_PORT7_SDS_CTRL_REG_3_FIELDNUM                      8u
#define DVA_PORT7_SDS_CTRL_REG_3_DEFAULTVAL                    0x0u
#define DVA_PORT8_SDS_CTRL_REG_3                               0x4AD6401Cu
#define DVA_PORT8_SDS_CTRL_REG_3_FIELDNUM                      8u
#define DVA_PORT8_SDS_CTRL_REG_3_DEFAULTVAL                    0x0u
#define DVA_PORT9_SDS_CTRL_REG_3                               0x4AD6481Cu
#define DVA_PORT9_SDS_CTRL_REG_3_FIELDNUM                      8u
#define DVA_PORT9_SDS_CTRL_REG_3_DEFAULTVAL                    0x0u
#define DVA_PORT10_SDS_CTRL_REG_3                              0x4AD6501Cu
#define DVA_PORT10_SDS_CTRL_REG_3_FIELDNUM                     8u
#define DVA_PORT10_SDS_CTRL_REG_3_DEFAULTVAL                   0x0u
#define DVA_PORT11_SDS_CTRL_REG_3                              0x4AD6581Cu
#define DVA_PORT11_SDS_CTRL_REG_3_FIELDNUM                     8u
#define DVA_PORT11_SDS_CTRL_REG_3_DEFAULTVAL                   0x0u
#define DVA_PORT12_SDS_CTRL_REG_3                              0x4AD6601Cu
#define DVA_PORT12_SDS_CTRL_REG_3_FIELDNUM                     8u
#define DVA_PORT12_SDS_CTRL_REG_3_DEFAULTVAL                   0x0u
#define DVA_PORT13_SDS_CTRL_REG_3                              0x4AD6681Cu
#define DVA_PORT13_SDS_CTRL_REG_3_FIELDNUM                     8u
#define DVA_PORT13_SDS_CTRL_REG_3_DEFAULTVAL                   0x0u
#define DVA_PORT14_SDS_CTRL_REG_3                              0x4AD6701Cu
#define DVA_PORT14_SDS_CTRL_REG_3_FIELDNUM                     8u
#define DVA_PORT14_SDS_CTRL_REG_3_DEFAULTVAL                   0x0u
#define DVA_PORT15_SDS_CTRL_REG_3                              0x4AD6781Cu
#define DVA_PORT15_SDS_CTRL_REG_3_FIELDNUM                     8u
#define DVA_PORT15_SDS_CTRL_REG_3_DEFAULTVAL                   0x0u
#define DVA_PORT0_SDS_CTRL_REG_4                               0x4AD60020u
#define DVA_PORT0_SDS_CTRL_REG_4_FIELDNUM                      4u
#define DVA_PORT0_SDS_CTRL_REG_4_DEFAULTVAL                    0x0u
#define DVA_PORT1_SDS_CTRL_REG_4                               0x4AD60820u
#define DVA_PORT1_SDS_CTRL_REG_4_FIELDNUM                      4u
#define DVA_PORT1_SDS_CTRL_REG_4_DEFAULTVAL                    0x0u
#define DVA_PORT2_SDS_CTRL_REG_4                               0x4AD61020u
#define DVA_PORT2_SDS_CTRL_REG_4_FIELDNUM                      4u
#define DVA_PORT2_SDS_CTRL_REG_4_DEFAULTVAL                    0x0u
#define DVA_PORT3_SDS_CTRL_REG_4                               0x4AD61820u
#define DVA_PORT3_SDS_CTRL_REG_4_FIELDNUM                      4u
#define DVA_PORT3_SDS_CTRL_REG_4_DEFAULTVAL                    0x0u
#define DVA_PORT4_SDS_CTRL_REG_4                               0x4AD62020u
#define DVA_PORT4_SDS_CTRL_REG_4_FIELDNUM                      4u
#define DVA_PORT4_SDS_CTRL_REG_4_DEFAULTVAL                    0x0u
#define DVA_PORT5_SDS_CTRL_REG_4                               0x4AD62820u
#define DVA_PORT5_SDS_CTRL_REG_4_FIELDNUM                      4u
#define DVA_PORT5_SDS_CTRL_REG_4_DEFAULTVAL                    0x0u
#define DVA_PORT6_SDS_CTRL_REG_4                               0x4AD63020u
#define DVA_PORT6_SDS_CTRL_REG_4_FIELDNUM                      4u
#define DVA_PORT6_SDS_CTRL_REG_4_DEFAULTVAL                    0x0u
#define DVA_PORT7_SDS_CTRL_REG_4                               0x4AD63820u
#define DVA_PORT7_SDS_CTRL_REG_4_FIELDNUM                      4u
#define DVA_PORT7_SDS_CTRL_REG_4_DEFAULTVAL                    0x0u
#define DVA_PORT8_SDS_CTRL_REG_4                               0x4AD64020u
#define DVA_PORT8_SDS_CTRL_REG_4_FIELDNUM                      4u
#define DVA_PORT8_SDS_CTRL_REG_4_DEFAULTVAL                    0x0u
#define DVA_PORT9_SDS_CTRL_REG_4                               0x4AD64820u
#define DVA_PORT9_SDS_CTRL_REG_4_FIELDNUM                      4u
#define DVA_PORT9_SDS_CTRL_REG_4_DEFAULTVAL                    0x0u
#define DVA_PORT10_SDS_CTRL_REG_4                              0x4AD65020u
#define DVA_PORT10_SDS_CTRL_REG_4_FIELDNUM                     4u
#define DVA_PORT10_SDS_CTRL_REG_4_DEFAULTVAL                   0x0u
#define DVA_PORT11_SDS_CTRL_REG_4                              0x4AD65820u
#define DVA_PORT11_SDS_CTRL_REG_4_FIELDNUM                     4u
#define DVA_PORT11_SDS_CTRL_REG_4_DEFAULTVAL                   0x0u
#define DVA_PORT12_SDS_CTRL_REG_4                              0x4AD66020u
#define DVA_PORT12_SDS_CTRL_REG_4_FIELDNUM                     4u
#define DVA_PORT12_SDS_CTRL_REG_4_DEFAULTVAL                   0x0u
#define DVA_PORT13_SDS_CTRL_REG_4                              0x4AD66820u
#define DVA_PORT13_SDS_CTRL_REG_4_FIELDNUM                     4u
#define DVA_PORT13_SDS_CTRL_REG_4_DEFAULTVAL                   0x0u
#define DVA_PORT14_SDS_CTRL_REG_4                              0x4AD67020u
#define DVA_PORT14_SDS_CTRL_REG_4_FIELDNUM                     4u
#define DVA_PORT14_SDS_CTRL_REG_4_DEFAULTVAL                   0x0u
#define DVA_PORT15_SDS_CTRL_REG_4                              0x4AD67820u
#define DVA_PORT15_SDS_CTRL_REG_4_FIELDNUM                     4u
#define DVA_PORT15_SDS_CTRL_REG_4_DEFAULTVAL                   0x0u
#define DVA_PORT0_SDS_STATUS_REG_0                             0x4AD60024u
#define DVA_PORT0_SDS_STATUS_REG_0_FIELDNUM                    15u
#define DVA_PORT0_SDS_STATUS_REG_0_DEFAULTVAL                  0x0u
#define DVA_PORT1_SDS_STATUS_REG_0                             0x4AD60824u
#define DVA_PORT1_SDS_STATUS_REG_0_FIELDNUM                    15u
#define DVA_PORT1_SDS_STATUS_REG_0_DEFAULTVAL                  0x0u
#define DVA_PORT2_SDS_STATUS_REG_0                             0x4AD61024u
#define DVA_PORT2_SDS_STATUS_REG_0_FIELDNUM                    15u
#define DVA_PORT2_SDS_STATUS_REG_0_DEFAULTVAL                  0x0u
#define DVA_PORT3_SDS_STATUS_REG_0                             0x4AD61824u
#define DVA_PORT3_SDS_STATUS_REG_0_FIELDNUM                    15u
#define DVA_PORT3_SDS_STATUS_REG_0_DEFAULTVAL                  0x0u
#define DVA_PORT4_SDS_STATUS_REG_0                             0x4AD62024u
#define DVA_PORT4_SDS_STATUS_REG_0_FIELDNUM                    15u
#define DVA_PORT4_SDS_STATUS_REG_0_DEFAULTVAL                  0x0u
#define DVA_PORT5_SDS_STATUS_REG_0                             0x4AD62824u
#define DVA_PORT5_SDS_STATUS_REG_0_FIELDNUM                    15u
#define DVA_PORT5_SDS_STATUS_REG_0_DEFAULTVAL                  0x0u
#define DVA_PORT6_SDS_STATUS_REG_0                             0x4AD63024u
#define DVA_PORT6_SDS_STATUS_REG_0_FIELDNUM                    15u
#define DVA_PORT6_SDS_STATUS_REG_0_DEFAULTVAL                  0x0u
#define DVA_PORT7_SDS_STATUS_REG_0                             0x4AD63824u
#define DVA_PORT7_SDS_STATUS_REG_0_FIELDNUM                    15u
#define DVA_PORT7_SDS_STATUS_REG_0_DEFAULTVAL                  0x0u
#define DVA_PORT8_SDS_STATUS_REG_0                             0x4AD64024u
#define DVA_PORT8_SDS_STATUS_REG_0_FIELDNUM                    15u
#define DVA_PORT8_SDS_STATUS_REG_0_DEFAULTVAL                  0x0u
#define DVA_PORT9_SDS_STATUS_REG_0                             0x4AD64824u
#define DVA_PORT9_SDS_STATUS_REG_0_FIELDNUM                    15u
#define DVA_PORT9_SDS_STATUS_REG_0_DEFAULTVAL                  0x0u
#define DVA_PORT10_SDS_STATUS_REG_0                            0x4AD65024u
#define DVA_PORT10_SDS_STATUS_REG_0_FIELDNUM                   15u
#define DVA_PORT10_SDS_STATUS_REG_0_DEFAULTVAL                 0x0u
#define DVA_PORT11_SDS_STATUS_REG_0                            0x4AD65824u
#define DVA_PORT11_SDS_STATUS_REG_0_FIELDNUM                   15u
#define DVA_PORT11_SDS_STATUS_REG_0_DEFAULTVAL                 0x0u
#define DVA_PORT12_SDS_STATUS_REG_0                            0x4AD66024u
#define DVA_PORT12_SDS_STATUS_REG_0_FIELDNUM                   15u
#define DVA_PORT12_SDS_STATUS_REG_0_DEFAULTVAL                 0x0u
#define DVA_PORT13_SDS_STATUS_REG_0                            0x4AD66824u
#define DVA_PORT13_SDS_STATUS_REG_0_FIELDNUM                   15u
#define DVA_PORT13_SDS_STATUS_REG_0_DEFAULTVAL                 0x0u
#define DVA_PORT14_SDS_STATUS_REG_0                            0x4AD67024u
#define DVA_PORT14_SDS_STATUS_REG_0_FIELDNUM                   15u
#define DVA_PORT14_SDS_STATUS_REG_0_DEFAULTVAL                 0x0u
#define DVA_PORT15_SDS_STATUS_REG_0                            0x4AD67824u
#define DVA_PORT15_SDS_STATUS_REG_0_FIELDNUM                   15u
#define DVA_PORT15_SDS_STATUS_REG_0_DEFAULTVAL                 0x0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS             0x4AD60028u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM    2u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL  0x0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS             0x4AD60828u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM    2u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL  0x0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS             0x4AD61028u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM    2u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL  0x0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS             0x4AD61828u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM    2u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL  0x0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS             0x4AD62028u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM    2u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL  0x0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS             0x4AD62828u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM    2u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL  0x0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS             0x4AD63028u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM    2u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL  0x0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS             0x4AD63828u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM    2u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL  0x0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS             0x4AD64028u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM    2u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL  0x0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS             0x4AD64828u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM    2u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL  0x0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS            0x4AD65028u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM   2u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL 0x0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS            0x4AD65828u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM   2u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL 0x0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS            0x4AD66028u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM   2u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL 0x0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS            0x4AD66828u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM   2u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL 0x0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS            0x4AD67028u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM   2u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL 0x0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS            0x4AD67828u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_FIELDNUM   2u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_SERDES_WRAP_SDS_DEFAULTVAL 0x0u
#define DVA_PORT0_SDS_CTRL_REG_5                               0x4AD6002Cu
#define DVA_PORT0_SDS_CTRL_REG_5_FIELDNUM                      10u
#define DVA_PORT0_SDS_CTRL_REG_5_DEFAULTVAL                    0x0u
#define DVA_PORT1_SDS_CTRL_REG_5                               0x4AD6082Cu
#define DVA_PORT1_SDS_CTRL_REG_5_FIELDNUM                      10u
#define DVA_PORT1_SDS_CTRL_REG_5_DEFAULTVAL                    0x0u
#define DVA_PORT2_SDS_CTRL_REG_5                               0x4AD6102Cu
#define DVA_PORT2_SDS_CTRL_REG_5_FIELDNUM                      10u
#define DVA_PORT2_SDS_CTRL_REG_5_DEFAULTVAL                    0x0u
#define DVA_PORT3_SDS_CTRL_REG_5                               0x4AD6182Cu
#define DVA_PORT3_SDS_CTRL_REG_5_FIELDNUM                      10u
#define DVA_PORT3_SDS_CTRL_REG_5_DEFAULTVAL                    0x0u
#define DVA_PORT4_SDS_CTRL_REG_5                               0x4AD6202Cu
#define DVA_PORT4_SDS_CTRL_REG_5_FIELDNUM                      10u
#define DVA_PORT4_SDS_CTRL_REG_5_DEFAULTVAL                    0x0u
#define DVA_PORT5_SDS_CTRL_REG_5                               0x4AD6282Cu
#define DVA_PORT5_SDS_CTRL_REG_5_FIELDNUM                      10u
#define DVA_PORT5_SDS_CTRL_REG_5_DEFAULTVAL                    0x0u
#define DVA_PORT6_SDS_CTRL_REG_5                               0x4AD6302Cu
#define DVA_PORT6_SDS_CTRL_REG_5_FIELDNUM                      10u
#define DVA_PORT6_SDS_CTRL_REG_5_DEFAULTVAL                    0x0u
#define DVA_PORT7_SDS_CTRL_REG_5                               0x4AD6382Cu
#define DVA_PORT7_SDS_CTRL_REG_5_FIELDNUM                      10u
#define DVA_PORT7_SDS_CTRL_REG_5_DEFAULTVAL                    0x0u
#define DVA_PORT8_SDS_CTRL_REG_5                               0x4AD6402Cu
#define DVA_PORT8_SDS_CTRL_REG_5_FIELDNUM                      10u
#define DVA_PORT8_SDS_CTRL_REG_5_DEFAULTVAL                    0x0u
#define DVA_PORT9_SDS_CTRL_REG_5                               0x4AD6482Cu
#define DVA_PORT9_SDS_CTRL_REG_5_FIELDNUM                      10u
#define DVA_PORT9_SDS_CTRL_REG_5_DEFAULTVAL                    0x0u
#define DVA_PORT10_SDS_CTRL_REG_5                              0x4AD6502Cu
#define DVA_PORT10_SDS_CTRL_REG_5_FIELDNUM                     10u
#define DVA_PORT10_SDS_CTRL_REG_5_DEFAULTVAL                   0x0u
#define DVA_PORT11_SDS_CTRL_REG_5                              0x4AD6582Cu
#define DVA_PORT11_SDS_CTRL_REG_5_FIELDNUM                     10u
#define DVA_PORT11_SDS_CTRL_REG_5_DEFAULTVAL                   0x0u
#define DVA_PORT12_SDS_CTRL_REG_5                              0x4AD6602Cu
#define DVA_PORT12_SDS_CTRL_REG_5_FIELDNUM                     10u
#define DVA_PORT12_SDS_CTRL_REG_5_DEFAULTVAL                   0x0u
#define DVA_PORT13_SDS_CTRL_REG_5                              0x4AD6682Cu
#define DVA_PORT13_SDS_CTRL_REG_5_FIELDNUM                     10u
#define DVA_PORT13_SDS_CTRL_REG_5_DEFAULTVAL                   0x0u
#define DVA_PORT14_SDS_CTRL_REG_5                              0x4AD6702Cu
#define DVA_PORT14_SDS_CTRL_REG_5_FIELDNUM                     10u
#define DVA_PORT14_SDS_CTRL_REG_5_DEFAULTVAL                   0x0u
#define DVA_PORT15_SDS_CTRL_REG_5                              0x4AD6782Cu
#define DVA_PORT15_SDS_CTRL_REG_5_FIELDNUM                     10u
#define DVA_PORT15_SDS_CTRL_REG_5_DEFAULTVAL                   0x0u
#endif
#endif /* DVA_RTKAS_REG_LIST_FILE_SERDES_WRAP_SDS_H_ */