/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_LIST_FILE_PORT_ISOLATION_H_
#define DVA_RTKAS_REG_LIST_FILE_PORT_ISOLATION_H_

#ifdef DVA_FILE_PORT_ISOLATION
/* File: Port Isolation */
#define DVA_CPU_PORT_SELF_FILTERING_CONTROL                   0x4A780000u
#define DVA_CPU_PORT_SELF_FILTERING_CONTROL_FIELDNUM          17u
#define DVA_CPU_PORT_SELF_FILTERING_CONTROL_DEFAULTVAL        0xFFFFu
#define DVA_PORT0_PORT_ISOLATION_CONTROL                      0x4AF80000u
#define DVA_PORT0_PORT_ISOLATION_CONTROL_FIELDNUM             2u
#define DVA_PORT0_PORT_ISOLATION_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT1_PORT_ISOLATION_CONTROL                      0x4AF80800u
#define DVA_PORT1_PORT_ISOLATION_CONTROL_FIELDNUM             2u
#define DVA_PORT1_PORT_ISOLATION_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT2_PORT_ISOLATION_CONTROL                      0x4AF81000u
#define DVA_PORT2_PORT_ISOLATION_CONTROL_FIELDNUM             2u
#define DVA_PORT2_PORT_ISOLATION_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT3_PORT_ISOLATION_CONTROL                      0x4AF81800u
#define DVA_PORT3_PORT_ISOLATION_CONTROL_FIELDNUM             2u
#define DVA_PORT3_PORT_ISOLATION_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT4_PORT_ISOLATION_CONTROL                      0x4AF82000u
#define DVA_PORT4_PORT_ISOLATION_CONTROL_FIELDNUM             2u
#define DVA_PORT4_PORT_ISOLATION_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT5_PORT_ISOLATION_CONTROL                      0x4AF82800u
#define DVA_PORT5_PORT_ISOLATION_CONTROL_FIELDNUM             2u
#define DVA_PORT5_PORT_ISOLATION_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT6_PORT_ISOLATION_CONTROL                      0x4AF83000u
#define DVA_PORT6_PORT_ISOLATION_CONTROL_FIELDNUM             2u
#define DVA_PORT6_PORT_ISOLATION_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT7_PORT_ISOLATION_CONTROL                      0x4AF83800u
#define DVA_PORT7_PORT_ISOLATION_CONTROL_FIELDNUM             2u
#define DVA_PORT7_PORT_ISOLATION_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT8_PORT_ISOLATION_CONTROL                      0x4AF84000u
#define DVA_PORT8_PORT_ISOLATION_CONTROL_FIELDNUM             2u
#define DVA_PORT8_PORT_ISOLATION_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT9_PORT_ISOLATION_CONTROL                      0x4AF84800u
#define DVA_PORT9_PORT_ISOLATION_CONTROL_FIELDNUM             2u
#define DVA_PORT9_PORT_ISOLATION_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT10_PORT_ISOLATION_CONTROL                     0x4AF85000u
#define DVA_PORT10_PORT_ISOLATION_CONTROL_FIELDNUM            2u
#define DVA_PORT10_PORT_ISOLATION_CONTROL_DEFAULTVAL          0x0u
#define DVA_PORT11_PORT_ISOLATION_CONTROL                     0x4AF85800u
#define DVA_PORT11_PORT_ISOLATION_CONTROL_FIELDNUM            2u
#define DVA_PORT11_PORT_ISOLATION_CONTROL_DEFAULTVAL          0x0u
#define DVA_PORT12_PORT_ISOLATION_CONTROL                     0x4AF86000u
#define DVA_PORT12_PORT_ISOLATION_CONTROL_FIELDNUM            2u
#define DVA_PORT12_PORT_ISOLATION_CONTROL_DEFAULTVAL          0x0u
#define DVA_PORT13_PORT_ISOLATION_CONTROL                     0x4AF86800u
#define DVA_PORT13_PORT_ISOLATION_CONTROL_FIELDNUM            2u
#define DVA_PORT13_PORT_ISOLATION_CONTROL_DEFAULTVAL          0x0u
#define DVA_PORT14_PORT_ISOLATION_CONTROL                     0x4AF87000u
#define DVA_PORT14_PORT_ISOLATION_CONTROL_FIELDNUM            2u
#define DVA_PORT14_PORT_ISOLATION_CONTROL_DEFAULTVAL          0x0u
#define DVA_PORT15_PORT_ISOLATION_CONTROL                     0x4AF87800u
#define DVA_PORT15_PORT_ISOLATION_CONTROL_FIELDNUM            2u
#define DVA_PORT15_PORT_ISOLATION_CONTROL_DEFAULTVAL          0x0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_ISOLATION             0x4AF80004u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM    2u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL  0x0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_ISOLATION             0x4AF80804u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM    2u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL  0x0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_ISOLATION             0x4AF81004u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM    2u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL  0x0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_ISOLATION             0x4AF81804u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM    2u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL  0x0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_ISOLATION             0x4AF82004u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM    2u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL  0x0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_ISOLATION             0x4AF82804u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM    2u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL  0x0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_ISOLATION             0x4AF83004u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM    2u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL  0x0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_ISOLATION             0x4AF83804u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM    2u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL  0x0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_ISOLATION             0x4AF84004u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM    2u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL  0x0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_ISOLATION             0x4AF84804u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM    2u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL  0x0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_ISOLATION            0x4AF85004u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM   2u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL 0x0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_ISOLATION            0x4AF85804u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM   2u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL 0x0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_ISOLATION            0x4AF86004u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM   2u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL 0x0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_ISOLATION            0x4AF86804u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM   2u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL 0x0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_ISOLATION            0x4AF87004u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM   2u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL 0x0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_ISOLATION            0x4AF87804u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_ISOLATION_FIELDNUM   2u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_ISOLATION_DEFAULTVAL 0x0u
#endif
#endif /* DVA_RTKAS_REG_LIST_FILE_PORT_ISOLATION_H_ */