/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_LIST_FILE_PRIORITY_EXTRACTION_H_
#define DVA_RTKAS_REG_LIST_FILE_PRIORITY_EXTRACTION_H_

#ifdef DVA_FILE_PRIORITY_EXTRACTION
/* File: DVA_VLAN Priority Extraction */
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL0                        0x4A4A0000u
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL0_FIELDNUM               9u
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL0_DEFAULTVAL             0xFAC681u
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL1                        0x4A4A0004u
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL1_FIELDNUM               9u
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL1_DEFAULTVAL             0xFAC681u
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL2                        0x4A4A0008u
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL2_FIELDNUM               9u
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL2_DEFAULTVAL             0xFAC681u
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL3                        0x4A4A000Cu
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL3_FIELDNUM               9u
#define DVA_INNER_TAG_PRIORITY_MAP_CONTROL3_DEFAULTVAL             0xFAC681u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL0                        0x4A4A0010u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL0_FIELDNUM               9u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL0_DEFAULTVAL             0xFAC681u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL1                        0x4A4A0014u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL1_FIELDNUM               9u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL1_DEFAULTVAL             0xFAC681u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL2                        0x4A4A0018u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL2_FIELDNUM               9u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL2_DEFAULTVAL             0xFAC681u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL3                        0x4A4A001Cu
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL3_FIELDNUM               9u
#define DVA_OUTER_TAG_PRIORITY_MAP_CONTROL3_DEFAULTVAL             0xFAC681u
#define DVA_DSCP_PRIORITY_MAP_CONTROL0                             0x4A4A0020u
#define DVA_DSCP_PRIORITY_MAP_CONTROL0_FIELDNUM                    16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL0_DEFAULTVAL                  0x0u
#define DVA_DSCP_PRIORITY_MAP_CONTROL1                             0x4A4A0024u
#define DVA_DSCP_PRIORITY_MAP_CONTROL1_FIELDNUM                    16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL1_DEFAULTVAL                  0x11110000u
#define DVA_DSCP_PRIORITY_MAP_CONTROL2                             0x4A4A0028u
#define DVA_DSCP_PRIORITY_MAP_CONTROL2_FIELDNUM                    16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL2_DEFAULTVAL                  0x22222211u
#define DVA_DSCP_PRIORITY_MAP_CONTROL3                             0x4A4A002Cu
#define DVA_DSCP_PRIORITY_MAP_CONTROL3_FIELDNUM                    16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL3_DEFAULTVAL                  0x44333333u
#define DVA_DSCP_PRIORITY_MAP_CONTROL4                             0x4A4A0030u
#define DVA_DSCP_PRIORITY_MAP_CONTROL4_FIELDNUM                    16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL4_DEFAULTVAL                  0x55554444u
#define DVA_DSCP_PRIORITY_MAP_CONTROL5                             0x4A4A0034u
#define DVA_DSCP_PRIORITY_MAP_CONTROL5_FIELDNUM                    16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL5_DEFAULTVAL                  0x55555555u
#define DVA_DSCP_PRIORITY_MAP_CONTROL6                             0x4A4A0038u
#define DVA_DSCP_PRIORITY_MAP_CONTROL6_FIELDNUM                    16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL6_DEFAULTVAL                  0x66666666u
#define DVA_DSCP_PRIORITY_MAP_CONTROL7                             0x4A4A003Cu
#define DVA_DSCP_PRIORITY_MAP_CONTROL7_FIELDNUM                    16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL7_DEFAULTVAL                  0x77776666u
#define DVA_DSCP_PRIORITY_MAP_CONTROL8                             0x4A4A0040u
#define DVA_DSCP_PRIORITY_MAP_CONTROL8_FIELDNUM                    16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL8_DEFAULTVAL                  0x0u
#define DVA_DSCP_PRIORITY_MAP_CONTROL9                             0x4A4A0044u
#define DVA_DSCP_PRIORITY_MAP_CONTROL9_FIELDNUM                    16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL9_DEFAULTVAL                  0x11110000u
#define DVA_DSCP_PRIORITY_MAP_CONTROL10                            0x4A4A0048u
#define DVA_DSCP_PRIORITY_MAP_CONTROL10_FIELDNUM                   16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL10_DEFAULTVAL                 0x22222211u
#define DVA_DSCP_PRIORITY_MAP_CONTROL11                            0x4A4A004Cu
#define DVA_DSCP_PRIORITY_MAP_CONTROL11_FIELDNUM                   16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL11_DEFAULTVAL                 0x44333333u
#define DVA_DSCP_PRIORITY_MAP_CONTROL12                            0x4A4A0050u
#define DVA_DSCP_PRIORITY_MAP_CONTROL12_FIELDNUM                   16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL12_DEFAULTVAL                 0x55554444u
#define DVA_DSCP_PRIORITY_MAP_CONTROL13                            0x4A4A0054u
#define DVA_DSCP_PRIORITY_MAP_CONTROL13_FIELDNUM                   16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL13_DEFAULTVAL                 0x55555555u
#define DVA_DSCP_PRIORITY_MAP_CONTROL14                            0x4A4A0058u
#define DVA_DSCP_PRIORITY_MAP_CONTROL14_FIELDNUM                   16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL14_DEFAULTVAL                 0x66666666u
#define DVA_DSCP_PRIORITY_MAP_CONTROL15                            0x4A4A005Cu
#define DVA_DSCP_PRIORITY_MAP_CONTROL15_FIELDNUM                   16u
#define DVA_DSCP_PRIORITY_MAP_CONTROL15_DEFAULTVAL                 0x77776666u
#define DVA_PRIORITY_ARBITRATION_CONTROL0                          0x4A4A0060u
#define DVA_PRIORITY_ARBITRATION_CONTROL0_FIELDNUM                 6u
#define DVA_PRIORITY_ARBITRATION_CONTROL0_DEFAULTVAL               0x0u
#define DVA_PRIORITY_ARBITRATION_CONTROL1                          0x4A4A0064u
#define DVA_PRIORITY_ARBITRATION_CONTROL1_FIELDNUM                 6u
#define DVA_PRIORITY_ARBITRATION_CONTROL1_DEFAULTVAL               0x7FFFu
#define DVA_CPU_PRIORITY_CONTROL                                   0x4A4A0068u
#define DVA_CPU_PRIORITY_CONTROL_FIELDNUM                          2u
#define DVA_CPU_PRIORITY_CONTROL_DEFAULTVAL                        0x0u
#define DVA_PORT0_PRIORITY_CONTROL                                 0x4ACA0000u
#define DVA_PORT0_PRIORITY_CONTROL_FIELDNUM                        6u
#define DVA_PORT0_PRIORITY_CONTROL_DEFAULTVAL                      0x20u
#define DVA_PORT1_PRIORITY_CONTROL                                 0x4ACA0800u
#define DVA_PORT1_PRIORITY_CONTROL_FIELDNUM                        6u
#define DVA_PORT1_PRIORITY_CONTROL_DEFAULTVAL                      0x20u
#define DVA_PORT2_PRIORITY_CONTROL                                 0x4ACA1000u
#define DVA_PORT2_PRIORITY_CONTROL_FIELDNUM                        6u
#define DVA_PORT2_PRIORITY_CONTROL_DEFAULTVAL                      0x20u
#define DVA_PORT3_PRIORITY_CONTROL                                 0x4ACA1800u
#define DVA_PORT3_PRIORITY_CONTROL_FIELDNUM                        6u
#define DVA_PORT3_PRIORITY_CONTROL_DEFAULTVAL                      0x20u
#define DVA_PORT4_PRIORITY_CONTROL                                 0x4ACA2000u
#define DVA_PORT4_PRIORITY_CONTROL_FIELDNUM                        6u
#define DVA_PORT4_PRIORITY_CONTROL_DEFAULTVAL                      0x20u
#define DVA_PORT5_PRIORITY_CONTROL                                 0x4ACA2800u
#define DVA_PORT5_PRIORITY_CONTROL_FIELDNUM                        6u
#define DVA_PORT5_PRIORITY_CONTROL_DEFAULTVAL                      0x20u
#define DVA_PORT6_PRIORITY_CONTROL                                 0x4ACA3000u
#define DVA_PORT6_PRIORITY_CONTROL_FIELDNUM                        6u
#define DVA_PORT6_PRIORITY_CONTROL_DEFAULTVAL                      0x20u
#define DVA_PORT7_PRIORITY_CONTROL                                 0x4ACA3800u
#define DVA_PORT7_PRIORITY_CONTROL_FIELDNUM                        6u
#define DVA_PORT7_PRIORITY_CONTROL_DEFAULTVAL                      0x20u
#define DVA_PORT8_PRIORITY_CONTROL                                 0x4ACA4000u
#define DVA_PORT8_PRIORITY_CONTROL_FIELDNUM                        6u
#define DVA_PORT8_PRIORITY_CONTROL_DEFAULTVAL                      0x20u
#define DVA_PORT9_PRIORITY_CONTROL                                 0x4ACA4800u
#define DVA_PORT9_PRIORITY_CONTROL_FIELDNUM                        6u
#define DVA_PORT9_PRIORITY_CONTROL_DEFAULTVAL                      0x20u
#define DVA_PORT10_PRIORITY_CONTROL                                0x4ACA5000u
#define DVA_PORT10_PRIORITY_CONTROL_FIELDNUM                       6u
#define DVA_PORT10_PRIORITY_CONTROL_DEFAULTVAL                     0x20u
#define DVA_PORT11_PRIORITY_CONTROL                                0x4ACA5800u
#define DVA_PORT11_PRIORITY_CONTROL_FIELDNUM                       6u
#define DVA_PORT11_PRIORITY_CONTROL_DEFAULTVAL                     0x20u
#define DVA_PORT12_PRIORITY_CONTROL                                0x4ACA6000u
#define DVA_PORT12_PRIORITY_CONTROL_FIELDNUM                       6u
#define DVA_PORT12_PRIORITY_CONTROL_DEFAULTVAL                     0x20u
#define DVA_PORT13_PRIORITY_CONTROL                                0x4ACA6800u
#define DVA_PORT13_PRIORITY_CONTROL_FIELDNUM                       6u
#define DVA_PORT13_PRIORITY_CONTROL_DEFAULTVAL                     0x20u
#define DVA_PORT14_PRIORITY_CONTROL                                0x4ACA7000u
#define DVA_PORT14_PRIORITY_CONTROL_FIELDNUM                       6u
#define DVA_PORT14_PRIORITY_CONTROL_DEFAULTVAL                     0x20u
#define DVA_PORT15_PRIORITY_CONTROL                                0x4ACA7800u
#define DVA_PORT15_PRIORITY_CONTROL_FIELDNUM                       6u
#define DVA_PORT15_PRIORITY_CONTROL_DEFAULTVAL                     0x20u
#define DVA_PORT0_RX_PRIORITY_COPY_CONTROL                         0x4ACA0004u
#define DVA_PORT0_RX_PRIORITY_COPY_CONTROL_FIELDNUM                3u
#define DVA_PORT0_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL              0x0u
#define DVA_PORT1_RX_PRIORITY_COPY_CONTROL                         0x4ACA0804u
#define DVA_PORT1_RX_PRIORITY_COPY_CONTROL_FIELDNUM                3u
#define DVA_PORT1_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL              0x0u
#define DVA_PORT2_RX_PRIORITY_COPY_CONTROL                         0x4ACA1004u
#define DVA_PORT2_RX_PRIORITY_COPY_CONTROL_FIELDNUM                3u
#define DVA_PORT2_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL              0x0u
#define DVA_PORT3_RX_PRIORITY_COPY_CONTROL                         0x4ACA1804u
#define DVA_PORT3_RX_PRIORITY_COPY_CONTROL_FIELDNUM                3u
#define DVA_PORT3_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL              0x0u
#define DVA_PORT4_RX_PRIORITY_COPY_CONTROL                         0x4ACA2004u
#define DVA_PORT4_RX_PRIORITY_COPY_CONTROL_FIELDNUM                3u
#define DVA_PORT4_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL              0x0u
#define DVA_PORT5_RX_PRIORITY_COPY_CONTROL                         0x4ACA2804u
#define DVA_PORT5_RX_PRIORITY_COPY_CONTROL_FIELDNUM                3u
#define DVA_PORT5_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL              0x0u
#define DVA_PORT6_RX_PRIORITY_COPY_CONTROL                         0x4ACA3004u
#define DVA_PORT6_RX_PRIORITY_COPY_CONTROL_FIELDNUM                3u
#define DVA_PORT6_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL              0x0u
#define DVA_PORT7_RX_PRIORITY_COPY_CONTROL                         0x4ACA3804u
#define DVA_PORT7_RX_PRIORITY_COPY_CONTROL_FIELDNUM                3u
#define DVA_PORT7_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL              0x0u
#define DVA_PORT8_RX_PRIORITY_COPY_CONTROL                         0x4ACA4004u
#define DVA_PORT8_RX_PRIORITY_COPY_CONTROL_FIELDNUM                3u
#define DVA_PORT8_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL              0x0u
#define DVA_PORT9_RX_PRIORITY_COPY_CONTROL                         0x4ACA4804u
#define DVA_PORT9_RX_PRIORITY_COPY_CONTROL_FIELDNUM                3u
#define DVA_PORT9_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL              0x0u
#define DVA_PORT10_RX_PRIORITY_COPY_CONTROL                        0x4ACA5004u
#define DVA_PORT10_RX_PRIORITY_COPY_CONTROL_FIELDNUM               3u
#define DVA_PORT10_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL             0x0u
#define DVA_PORT11_RX_PRIORITY_COPY_CONTROL                        0x4ACA5804u
#define DVA_PORT11_RX_PRIORITY_COPY_CONTROL_FIELDNUM               3u
#define DVA_PORT11_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL             0x0u
#define DVA_PORT12_RX_PRIORITY_COPY_CONTROL                        0x4ACA6004u
#define DVA_PORT12_RX_PRIORITY_COPY_CONTROL_FIELDNUM               3u
#define DVA_PORT12_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL             0x0u
#define DVA_PORT13_RX_PRIORITY_COPY_CONTROL                        0x4ACA6804u
#define DVA_PORT13_RX_PRIORITY_COPY_CONTROL_FIELDNUM               3u
#define DVA_PORT13_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL             0x0u
#define DVA_PORT14_RX_PRIORITY_COPY_CONTROL                        0x4ACA7004u
#define DVA_PORT14_RX_PRIORITY_COPY_CONTROL_FIELDNUM               3u
#define DVA_PORT14_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL             0x0u
#define DVA_PORT15_RX_PRIORITY_COPY_CONTROL                        0x4ACA7804u
#define DVA_PORT15_RX_PRIORITY_COPY_CONTROL_FIELDNUM               3u
#define DVA_PORT15_RX_PRIORITY_COPY_CONTROL_DEFAULTVAL             0x0u
#define DVA_PORT0_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL              0x4ACA0008u
#define DVA_PORT0_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM     9u
#define DVA_PORT0_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL   0xFAC688u
#define DVA_PORT1_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL              0x4ACA0808u
#define DVA_PORT1_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM     9u
#define DVA_PORT1_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL   0xFAC688u
#define DVA_PORT2_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL              0x4ACA1008u
#define DVA_PORT2_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM     9u
#define DVA_PORT2_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL   0xFAC688u
#define DVA_PORT3_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL              0x4ACA1808u
#define DVA_PORT3_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM     9u
#define DVA_PORT3_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL   0xFAC688u
#define DVA_PORT4_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL              0x4ACA2008u
#define DVA_PORT4_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM     9u
#define DVA_PORT4_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL   0xFAC688u
#define DVA_PORT5_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL              0x4ACA2808u
#define DVA_PORT5_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM     9u
#define DVA_PORT5_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL   0xFAC688u
#define DVA_PORT6_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL              0x4ACA3008u
#define DVA_PORT6_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM     9u
#define DVA_PORT6_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL   0xFAC688u
#define DVA_PORT7_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL              0x4ACA3808u
#define DVA_PORT7_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM     9u
#define DVA_PORT7_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL   0xFAC688u
#define DVA_PORT8_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL              0x4ACA4008u
#define DVA_PORT8_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM     9u
#define DVA_PORT8_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL   0xFAC688u
#define DVA_PORT9_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL              0x4ACA4808u
#define DVA_PORT9_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM     9u
#define DVA_PORT9_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL   0xFAC688u
#define DVA_PORT10_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL             0x4ACA5008u
#define DVA_PORT10_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM    9u
#define DVA_PORT10_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL  0xFAC688u
#define DVA_PORT11_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL             0x4ACA5808u
#define DVA_PORT11_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM    9u
#define DVA_PORT11_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL  0xFAC688u
#define DVA_PORT12_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL             0x4ACA6008u
#define DVA_PORT12_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM    9u
#define DVA_PORT12_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL  0xFAC688u
#define DVA_PORT13_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL             0x4ACA6808u
#define DVA_PORT13_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM    9u
#define DVA_PORT13_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL  0xFAC688u
#define DVA_PORT14_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL             0x4ACA7008u
#define DVA_PORT14_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM    9u
#define DVA_PORT14_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL  0xFAC688u
#define DVA_PORT15_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL             0x4ACA7808u
#define DVA_PORT15_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_FIELDNUM    9u
#define DVA_PORT15_PRIORITY_MAP_TO_QUEUENUMBER_CONTROL_DEFAULTVAL  0xFAC688u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION             0x4ACA000Cu
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM    2u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL  0x0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION             0x4ACA080Cu
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM    2u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL  0x0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION             0x4ACA100Cu
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM    2u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL  0x0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION             0x4ACA180Cu
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM    2u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL  0x0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION             0x4ACA200Cu
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM    2u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL  0x0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION             0x4ACA280Cu
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM    2u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL  0x0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION             0x4ACA300Cu
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM    2u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL  0x0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION             0x4ACA380Cu
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM    2u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL  0x0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION             0x4ACA400Cu
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM    2u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL  0x0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION             0x4ACA480Cu
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM    2u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL  0x0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION            0x4ACA500Cu
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM   2u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL 0x0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION            0x4ACA580Cu
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM   2u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL 0x0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION            0x4ACA600Cu
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM   2u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL 0x0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION            0x4ACA680Cu
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM   2u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL 0x0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION            0x4ACA700Cu
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM   2u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL 0x0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION            0x4ACA780Cu
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_FIELDNUM   2u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PRIORITY_EXTRACTION_DEFAULTVAL 0x0u
#endif
#endif /* DVA_RTKAS_REG_LIST_FILE_PRIORITY_EXTRACTION_H_ */