/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_LIST_FILE_VLAN_DECISION_H_
#define DVA_RTKAS_REG_LIST_FILE_VLAN_DECISION_H_

#ifdef DVA_FILE_VLAN_DECISION
/* File: DVA_VLAN Decision */
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC90000u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC90800u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC91000u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC91800u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC92000u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC92800u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC93000u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC93800u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC94000u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC94800u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC95000u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC95800u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC96000u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC96800u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC97000u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC97800u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL                       0x4AC90004u
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL                       0x4AC90804u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL                       0x4AC91004u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL                       0x4AC91804u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL                       0x4AC92004u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL                       0x4AC92804u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL                       0x4AC93004u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL                       0x4AC93804u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL                       0x4AC94004u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL                       0x4AC94804u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL                      0x4AC95004u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL                      0x4AC95804u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL                      0x4AC96004u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL                      0x4AC96804u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL                      0x4AC97004u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL                      0x4AC97804u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DVA_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC90008u
#define DVA_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DVA_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DVA_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC90808u
#define DVA_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DVA_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DVA_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC91008u
#define DVA_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DVA_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DVA_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC91808u
#define DVA_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DVA_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DVA_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC92008u
#define DVA_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DVA_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DVA_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC92808u
#define DVA_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DVA_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DVA_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC93008u
#define DVA_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DVA_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DVA_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC93808u
#define DVA_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DVA_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DVA_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC94008u
#define DVA_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DVA_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DVA_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC94808u
#define DVA_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DVA_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DVA_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC95008u
#define DVA_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DVA_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DVA_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC95808u
#define DVA_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DVA_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DVA_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC96008u
#define DVA_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DVA_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DVA_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC96808u
#define DVA_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DVA_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DVA_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC97008u
#define DVA_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DVA_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DVA_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC97808u
#define DVA_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DVA_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_VLAN_DECISION                0x4AC9000Cu
#define DVA_PORT0_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM       2u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL     0x0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_VLAN_DECISION                0x4AC9080Cu
#define DVA_PORT1_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM       2u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL     0x0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_VLAN_DECISION                0x4AC9100Cu
#define DVA_PORT2_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM       2u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL     0x0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_VLAN_DECISION                0x4AC9180Cu
#define DVA_PORT3_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM       2u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL     0x0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_VLAN_DECISION                0x4AC9200Cu
#define DVA_PORT4_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM       2u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL     0x0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_VLAN_DECISION                0x4AC9280Cu
#define DVA_PORT5_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM       2u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL     0x0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_VLAN_DECISION                0x4AC9300Cu
#define DVA_PORT6_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM       2u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL     0x0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_VLAN_DECISION                0x4AC9380Cu
#define DVA_PORT7_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM       2u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL     0x0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_VLAN_DECISION                0x4AC9400Cu
#define DVA_PORT8_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM       2u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL     0x0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_VLAN_DECISION                0x4AC9480Cu
#define DVA_PORT9_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM       2u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL     0x0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_VLAN_DECISION               0x4AC9500Cu
#define DVA_PORT10_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM      2u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL    0x0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_VLAN_DECISION               0x4AC9580Cu
#define DVA_PORT11_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM      2u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL    0x0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_VLAN_DECISION               0x4AC9600Cu
#define DVA_PORT12_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM      2u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL    0x0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_VLAN_DECISION               0x4AC9680Cu
#define DVA_PORT13_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM      2u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL    0x0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_VLAN_DECISION               0x4AC9700Cu
#define DVA_PORT14_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM      2u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL    0x0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_VLAN_DECISION               0x4AC9780Cu
#define DVA_PORT15_FUSA_PG_LOCK_DMY_VLAN_DECISION_FIELDNUM      2u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_VLAN_DECISION_DEFAULTVAL    0x0u
#endif
#endif /* DVA_RTKAS_REG_LIST_FILE_VLAN_DECISION_H_ */