/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_PORT_ISOLATION_H_
#define DV1_RTKAS_REG_FIELD_FILE_PORT_ISOLATION_H_

#ifdef DV1_FILE_PORT_ISOLATION
/* File: Port Isolation */
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU1631SELFFLT_RESERVED_LSP  16u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU1631SELFFLT_RESERVED_LEN  16u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU1631SELFFLT_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU15SELFFLT_LSP             15u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU15SELFFLT_LEN             1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU15SELFFLT_TYPE            DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU14SELFFLT_LSP             14u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU14SELFFLT_LEN             1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU14SELFFLT_TYPE            DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU13SELFFLT_LSP             13u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU13SELFFLT_LEN             1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU13SELFFLT_TYPE            DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU12SELFFLT_LSP             12u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU12SELFFLT_LEN             1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU12SELFFLT_TYPE            DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU11SELFFLT_LSP             11u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU11SELFFLT_LEN             1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU11SELFFLT_TYPE            DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU10SELFFLT_LSP             10u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU10SELFFLT_LEN             1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU10SELFFLT_TYPE            DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU9SELFFLT_LSP              9u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU9SELFFLT_LEN              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU9SELFFLT_TYPE             DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU8SELFFLT_LSP              8u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU8SELFFLT_LEN              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU8SELFFLT_TYPE             DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU7SELFFLT_LSP              7u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU7SELFFLT_LEN              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU7SELFFLT_TYPE             DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU6SELFFLT_LSP              6u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU6SELFFLT_LEN              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU6SELFFLT_TYPE             DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU5SELFFLT_LSP              5u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU5SELFFLT_LEN              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU5SELFFLT_TYPE             DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU4SELFFLT_LSP              4u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU4SELFFLT_LEN              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU4SELFFLT_TYPE             DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU3SELFFLT_LSP              3u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU3SELFFLT_LEN              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU3SELFFLT_TYPE             DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU2SELFFLT_LSP              2u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU2SELFFLT_LEN              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU2SELFFLT_TYPE             DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU1SELFFLT_LSP              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU1SELFFLT_LEN              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU1SELFFLT_TYPE             DV1_FIELD_TYPE_RW
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU0SELFFLT_LSP              0u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU0SELFFLT_LEN              1u
#define DV1_CPU_PORT_SELF_FILTERING_CONTROL_CPU0SELFFLT_TYPE             DV1_FIELD_TYPE_RW

#define DV1_PORT0_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT0_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT0_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT0_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT0_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT0_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT1_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT1_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT1_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT1_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT1_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT1_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT2_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT2_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT2_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT2_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT2_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT2_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT3_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT3_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT3_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT3_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT3_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT3_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT4_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT4_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT4_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT4_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT4_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT4_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT5_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT5_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT5_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT5_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT5_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT5_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT6_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT6_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT6_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT6_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT6_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT6_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT7_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT7_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT7_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT7_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT7_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT7_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT8_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT8_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT8_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT8_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT8_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT8_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT9_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT9_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT9_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT9_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT9_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT9_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT10_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT10_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT10_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT10_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT10_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT10_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT11_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT11_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT11_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT11_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT11_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT11_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT12_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT12_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT12_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT12_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT12_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT12_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT13_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT13_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT13_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT13_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT13_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT13_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT14_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT14_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT14_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT14_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT14_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT14_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#define DV1_PORT15_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LSP  16u
#define DV1_PORT15_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_LEN  16u
#define DV1_PORT15_PORT_ISOLATION_CONTROL_TISO1631_RESERVED_TYPE DV1_FIELD_TYPE_RO
#define DV1_PORT15_PORT_ISOLATION_CONTROL_TISO_LSP               0u
#define DV1_PORT15_PORT_ISOLATION_CONTROL_TISO_LEN               16u
#define DV1_PORT15_PORT_ISOLATION_CONTROL_TISO_TYPE              DV1_FIELD_TYPE_RW

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_PORT_ISOLATION_H_ */