/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_RESET_H_
#define DV1_RTKAS_REG_FIELD_FILE_RESET_H_

#ifdef DV1_FILE_RESET
/* File: Reset */
#define DV1_RESET_GLOBAL_CONTROL0_FLASH_CTRL_RST_LSP  4u
#define DV1_RESET_GLOBAL_CONTROL0_FLASH_CTRL_RST_LEN  1u
#define DV1_RESET_GLOBAL_CONTROL0_FLASH_CTRL_RST_TYPE DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL0_CPU_MEM_RST_LSP     3u
#define DV1_RESET_GLOBAL_CONTROL0_CPU_MEM_RST_LEN     1u
#define DV1_RESET_GLOBAL_CONTROL0_CPU_MEM_RST_TYPE    DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL0_SWITCH_RST_LSP      2u
#define DV1_RESET_GLOBAL_CONTROL0_SWITCH_RST_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL0_SWITCH_RST_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL0_NIC_RST_LSP         1u
#define DV1_RESET_GLOBAL_CONTROL0_NIC_RST_LEN         1u
#define DV1_RESET_GLOBAL_CONTROL0_NIC_RST_TYPE        DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL0_SW_RST_LSP          0u
#define DV1_RESET_GLOBAL_CONTROL0_SW_RST_LEN          1u
#define DV1_RESET_GLOBAL_CONTROL0_SW_RST_TYPE         DV1_FIELD_TYPE_RWS

#define DV1_RESET_GLOBAL_CONTROL1_HW_RST_LSP  0u
#define DV1_RESET_GLOBAL_CONTROL1_HW_RST_LEN  1u
#define DV1_RESET_GLOBAL_CONTROL1_HW_RST_TYPE DV1_FIELD_TYPE_RWS

#define DV1_RESET_GLOBAL_CONTROL2_SG3_REG_RST_PS_LSP     31u
#define DV1_RESET_GLOBAL_CONTROL2_SG3_REG_RST_PS_LEN     1u
#define DV1_RESET_GLOBAL_CONTROL2_SG3_REG_RST_PS_TYPE    DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_SG2_REG_RST_PS_LSP     30u
#define DV1_RESET_GLOBAL_CONTROL2_SG2_REG_RST_PS_LEN     1u
#define DV1_RESET_GLOBAL_CONTROL2_SG2_REG_RST_PS_TYPE    DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_SG3_RST_PS_LSP         29u
#define DV1_RESET_GLOBAL_CONTROL2_SG3_RST_PS_LEN         1u
#define DV1_RESET_GLOBAL_CONTROL2_SG3_RST_PS_TYPE        DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_SG2_RST_PS_LSP         28u
#define DV1_RESET_GLOBAL_CONTROL2_SG2_RST_PS_LEN         1u
#define DV1_RESET_GLOBAL_CONTROL2_SG2_RST_PS_TYPE        DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_USXG1_REG_RST_PS_LSP   27u
#define DV1_RESET_GLOBAL_CONTROL2_USXG1_REG_RST_PS_LEN   1u
#define DV1_RESET_GLOBAL_CONTROL2_USXG1_REG_RST_PS_TYPE  DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_USXG0_REG_RST_PS_LSP   26u
#define DV1_RESET_GLOBAL_CONTROL2_USXG0_REG_RST_PS_LEN   1u
#define DV1_RESET_GLOBAL_CONTROL2_USXG0_REG_RST_PS_TYPE  DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_USXG1_CORE_RST_PS_LSP  25u
#define DV1_RESET_GLOBAL_CONTROL2_USXG1_CORE_RST_PS_LEN  1u
#define DV1_RESET_GLOBAL_CONTROL2_USXG1_CORE_RST_PS_TYPE DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_USXG0_CORE_RST_PS_LSP  24u
#define DV1_RESET_GLOBAL_CONTROL2_USXG0_CORE_RST_PS_LEN  1u
#define DV1_RESET_GLOBAL_CONTROL2_USXG0_CORE_RST_PS_TYPE DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1000PHY1_RST_PS_LSP   23u
#define DV1_RESET_GLOBAL_CONTROL2_T1000PHY1_RST_PS_LEN   1u
#define DV1_RESET_GLOBAL_CONTROL2_T1000PHY1_RST_PS_TYPE  DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1000PHY0_RST_PS_LSP   22u
#define DV1_RESET_GLOBAL_CONTROL2_T1000PHY0_RST_PS_LEN   1u
#define DV1_RESET_GLOBAL_CONTROL2_T1000PHY0_RST_PS_TYPE  DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_SG1_REG_RST_PS_LSP     21u
#define DV1_RESET_GLOBAL_CONTROL2_SG1_REG_RST_PS_LEN     1u
#define DV1_RESET_GLOBAL_CONTROL2_SG1_REG_RST_PS_TYPE    DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_SG0_REG_RST_PS_LSP     20u
#define DV1_RESET_GLOBAL_CONTROL2_SG0_REG_RST_PS_LEN     1u
#define DV1_RESET_GLOBAL_CONTROL2_SG0_REG_RST_PS_TYPE    DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_SG1_RST_PS_LSP         19u
#define DV1_RESET_GLOBAL_CONTROL2_SG1_RST_PS_LEN         1u
#define DV1_RESET_GLOBAL_CONTROL2_SG1_RST_PS_TYPE        DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_SG0_RST_PS_LSP         18u
#define DV1_RESET_GLOBAL_CONTROL2_SG0_RST_PS_LEN         1u
#define DV1_RESET_GLOBAL_CONTROL2_SG0_RST_PS_TYPE        DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY9_RST_PS_LSP      17u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY9_RST_PS_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY9_RST_PS_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY8_RST_PS_LSP      16u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY8_RST_PS_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY8_RST_PS_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY7_RST_PS_LSP      15u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY7_RST_PS_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY7_RST_PS_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY6_RST_PS_LSP      14u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY6_RST_PS_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY6_RST_PS_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY5_RST_PS_LSP      13u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY5_RST_PS_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY5_RST_PS_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY4_RST_PS_LSP      12u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY4_RST_PS_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY4_RST_PS_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY3_RST_PS_LSP      11u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY3_RST_PS_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY3_RST_PS_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY2_RST_PS_LSP      10u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY2_RST_PS_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY2_RST_PS_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY1_RST_PS_LSP      9u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY1_RST_PS_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY1_RST_PS_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY0_RST_PS_LSP      8u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY0_RST_PS_LEN      1u
#define DV1_RESET_GLOBAL_CONTROL2_T1PHY0_RST_PS_TYPE     DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_SG4_REG_RST_PS_LSP     4u
#define DV1_RESET_GLOBAL_CONTROL2_SG4_REG_RST_PS_LEN     1u
#define DV1_RESET_GLOBAL_CONTROL2_SG4_REG_RST_PS_TYPE    DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_SG4_RST_PS_LSP         3u
#define DV1_RESET_GLOBAL_CONTROL2_SG4_RST_PS_LEN         1u
#define DV1_RESET_GLOBAL_CONTROL2_SG4_RST_PS_TYPE        DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_USXG2_REG_RST_PS_LSP   2u
#define DV1_RESET_GLOBAL_CONTROL2_USXG2_REG_RST_PS_LEN   1u
#define DV1_RESET_GLOBAL_CONTROL2_USXG2_REG_RST_PS_TYPE  DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_USXG2_CORE_RST_PS_LSP  1u
#define DV1_RESET_GLOBAL_CONTROL2_USXG2_CORE_RST_PS_LEN  1u
#define DV1_RESET_GLOBAL_CONTROL2_USXG2_CORE_RST_PS_TYPE DV1_FIELD_TYPE_RWS
#define DV1_RESET_GLOBAL_CONTROL2_FE_RST_PS_LSP          0u
#define DV1_RESET_GLOBAL_CONTROL2_FE_RST_PS_LEN          1u
#define DV1_RESET_GLOBAL_CONTROL2_FE_RST_PS_TYPE         DV1_FIELD_TYPE_RWS

#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P7_RTPGE_LSP  20u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P7_RTPGE_LEN  1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P7_RTPGE_TYPE DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P6_RTPGE_LSP  19u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P6_RTPGE_LEN  1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P6_RTPGE_TYPE DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P10_LSP       18u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P10_LEN       1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P10_TYPE      DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P9_LSP        17u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P9_LEN        1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P9_TYPE       DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P7_LSP        16u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P7_LEN        1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P7_TYPE       DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P6_LSP        15u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P6_LEN        1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P6_TYPE       DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P5_LSP        14u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P5_LEN        1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P5_TYPE       DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P4_LSP        13u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P4_LEN        1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P4_TYPE       DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P3_LSP        12u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P3_LEN        1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P3_TYPE       DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P2_LSP        11u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P2_LEN        1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P2_TYPE       DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P1_LSP        10u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P1_LEN        1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P1_TYPE       DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P0_LSP        9u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P0_LEN        1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_P0_TYPE       DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_LSP           8u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_LEN           1u
#define DV1_RESET_GLOBAL_STATUS_OP_FSM_PHYRSTB_TYPE          DV1_FIELD_TYPE_RO
#define DV1_RESET_GLOBAL_STATUS_RST_STA_LSP                  0u
#define DV1_RESET_GLOBAL_STATUS_RST_STA_LEN                  1u
#define DV1_RESET_GLOBAL_STATUS_RST_STA_TYPE                 DV1_FIELD_TYPE_RW

#define DV1_RESET_DMY_LINK_STA_RL_LSP         24u
#define DV1_RESET_DMY_LINK_STA_RL_LEN         8u
#define DV1_RESET_DMY_LINK_STA_RL_TYPE        DV1_FIELD_TYPE_RO
#define DV1_RESET_DMY_RESET_DMY_REG_23_0_LSP  0u
#define DV1_RESET_DMY_RESET_DMY_REG_23_0_LEN  24u
#define DV1_RESET_DMY_RESET_DMY_REG_23_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_RESET_DMY2_LINK_STA_RL_ALL_LSP  0u
#define DV1_RESET_DMY2_LINK_STA_RL_ALL_LEN  15u
#define DV1_RESET_DMY2_LINK_STA_RL_ALL_TYPE DV1_FIELD_TYPE_RO

#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG3_REG_RST_INT_LSP     31u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG3_REG_RST_INT_LEN     1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG3_REG_RST_INT_TYPE    DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG2_REG_RST_INT_LSP     30u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG2_REG_RST_INT_LEN     1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG2_REG_RST_INT_TYPE    DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG3_RST_INT_LSP         29u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG3_RST_INT_LEN         1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG3_RST_INT_TYPE        DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG2_RST_INT_LSP         28u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG2_RST_INT_LEN         1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG2_RST_INT_TYPE        DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG1_REG_RST_INT_LSP   27u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG1_REG_RST_INT_LEN   1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG1_REG_RST_INT_TYPE  DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG0_REG_RST_INT_LSP   26u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG0_REG_RST_INT_LEN   1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG0_REG_RST_INT_TYPE  DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG1_CORE_RST_INT_LSP  25u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG1_CORE_RST_INT_LEN  1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG1_CORE_RST_INT_TYPE DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG0_CORE_RST_INT_LSP  24u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG0_CORE_RST_INT_LEN  1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG0_CORE_RST_INT_TYPE DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG1_REG_RST_INT_LSP     23u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG1_REG_RST_INT_LEN     1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG1_REG_RST_INT_TYPE    DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG0_REG_RST_INT_LSP     22u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG0_REG_RST_INT_LEN     1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG0_REG_RST_INT_TYPE    DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG1_RST_INT_LSP         21u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG1_RST_INT_LEN         1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG1_RST_INT_TYPE        DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG0_RST_INT_LSP         20u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG0_RST_INT_LEN         1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG0_RST_INT_TYPE        DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1000PHY1_RST_INT_LSP   19u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1000PHY1_RST_INT_LEN   1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1000PHY1_RST_INT_TYPE  DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1000PHY0_RST_INT_LSP   18u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1000PHY0_RST_INT_LEN   1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1000PHY0_RST_INT_TYPE  DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY9_RST_INT_LSP      17u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY9_RST_INT_LEN      1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY9_RST_INT_TYPE     DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY8_RST_INT_LSP      16u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY8_RST_INT_LEN      1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY8_RST_INT_TYPE     DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY7_RST_INT_LSP      15u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY7_RST_INT_LEN      1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY7_RST_INT_TYPE     DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY6_RST_INT_LSP      14u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY6_RST_INT_LEN      1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY6_RST_INT_TYPE     DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY5_RST_INT_LSP      13u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY5_RST_INT_LEN      1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY5_RST_INT_TYPE     DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY4_RST_INT_LSP      12u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY4_RST_INT_LEN      1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY4_RST_INT_TYPE     DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY3_RST_INT_LSP      11u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY3_RST_INT_LEN      1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY3_RST_INT_TYPE     DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY2_RST_INT_LSP      10u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY2_RST_INT_LEN      1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY2_RST_INT_TYPE     DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY1_RST_INT_LSP      9u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY1_RST_INT_LEN      1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY1_RST_INT_TYPE     DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY0_RST_INT_LSP      8u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY0_RST_INT_LEN      1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_T1PHY0_RST_INT_TYPE     DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG4_REG_RST_INT_LSP     4u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG4_REG_RST_INT_LEN     1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG4_REG_RST_INT_TYPE    DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG4_RST_INT_LSP         3u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG4_RST_INT_LEN         1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_SG4_RST_INT_TYPE        DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG2_REG_RST_INT_LSP   2u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG2_REG_RST_INT_LEN   1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG2_REG_RST_INT_TYPE  DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG2_CORE_RST_INT_LSP  1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG2_CORE_RST_INT_LEN  1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_USXG2_CORE_RST_INT_TYPE DV1_FIELD_TYPE_RW1C
#define DV1_PAST_GLOBAL_CONTROL_STATUS_FE_RST_INT_LSP          0u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_FE_RST_INT_LEN          1u
#define DV1_PAST_GLOBAL_CONTROL_STATUS_FE_RST_INT_TYPE         DV1_FIELD_TYPE_RW1C

#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG3_REG_RST_STS_LSP     31u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG3_REG_RST_STS_LEN     1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG3_REG_RST_STS_TYPE    DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG2_REG_RST_STS_LSP     30u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG2_REG_RST_STS_LEN     1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG2_REG_RST_STS_TYPE    DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG3_RST_STS_LSP         29u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG3_RST_STS_LEN         1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG3_RST_STS_TYPE        DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG2_RST_STS_LSP         28u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG2_RST_STS_LEN         1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG2_RST_STS_TYPE        DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG1_REG_RST_STS_LSP   27u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG1_REG_RST_STS_LEN   1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG1_REG_RST_STS_TYPE  DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG0_REG_RST_STS_LSP   26u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG0_REG_RST_STS_LEN   1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG0_REG_RST_STS_TYPE  DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG1_CORE_RST_STS_LSP  25u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG1_CORE_RST_STS_LEN  1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG1_CORE_RST_STS_TYPE DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG0_CORE_RST_STS_LSP  24u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG0_CORE_RST_STS_LEN  1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG0_CORE_RST_STS_TYPE DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG1_REG_RST_STS_LSP     23u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG1_REG_RST_STS_LEN     1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG1_REG_RST_STS_TYPE    DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG0_REG_RST_STS_LSP     22u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG0_REG_RST_STS_LEN     1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG0_REG_RST_STS_TYPE    DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG1_RST_STS_LSP         21u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG1_RST_STS_LEN         1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG1_RST_STS_TYPE        DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG0_RST_STS_LSP         20u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG0_RST_STS_LEN         1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG0_RST_STS_TYPE        DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1000PHY1_RST_STS_LSP   19u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1000PHY1_RST_STS_LEN   1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1000PHY1_RST_STS_TYPE  DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1000PHY0_RST_STS_LSP   18u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1000PHY0_RST_STS_LEN   1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1000PHY0_RST_STS_TYPE  DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY9_RST_STS_LSP      17u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY9_RST_STS_LEN      1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY9_RST_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY8_RST_STS_LSP      16u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY8_RST_STS_LEN      1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY8_RST_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY7_RST_STS_LSP      15u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY7_RST_STS_LEN      1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY7_RST_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY6_RST_STS_LSP      14u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY6_RST_STS_LEN      1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY6_RST_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY5_RST_STS_LSP      13u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY5_RST_STS_LEN      1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY5_RST_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY4_RST_STS_LSP      12u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY4_RST_STS_LEN      1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY4_RST_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY3_RST_STS_LSP      11u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY3_RST_STS_LEN      1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY3_RST_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY2_RST_STS_LSP      10u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY2_RST_STS_LEN      1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY2_RST_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY1_RST_STS_LSP      9u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY1_RST_STS_LEN      1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY1_RST_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY0_RST_STS_LSP      8u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY0_RST_STS_LEN      1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_T1PHY0_RST_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG4_REG_RST_STS_LSP     4u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG4_REG_RST_STS_LEN     1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG4_REG_RST_STS_TYPE    DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG4_RST_STS_LSP         3u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG4_RST_STS_LEN         1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_SG4_RST_STS_TYPE        DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG2_REG_RST_STS_LSP   2u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG2_REG_RST_STS_LEN   1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG2_REG_RST_STS_TYPE  DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG2_CORE_RST_STS_LSP  1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG2_CORE_RST_STS_LEN  1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_USXG2_CORE_RST_STS_TYPE DV1_FIELD_TYPE_RO
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_FE_RST_STS_LSP          0u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_FE_RST_STS_LEN          1u
#define DV1_CURRENT_GLOBAL_CONTROL_STATUS_FE_RST_STS_TYPE         DV1_FIELD_TYPE_RO

#define DV1_PER_PORT_RESET_CONTROL_PER_PORT_RESET_LSP  0u
#define DV1_PER_PORT_RESET_CONTROL_PER_PORT_RESET_LEN  16u
#define DV1_PER_PORT_RESET_CONTROL_PER_PORT_RESET_TYPE DV1_FIELD_TYPE_RW

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_RESET_H_ */