/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_ROUTING_H_
#define DV1_RTKAS_REG_FIELD_FILE_ROUTING_H_

#ifdef DV1_FILE_ROUTING
/* File: Routing */
#define DV1_L3_IPUC_ROUTE_CTRL_DISB_ACT_LSP       17u
#define DV1_L3_IPUC_ROUTE_CTRL_DISB_ACT_LEN       2u
#define DV1_L3_IPUC_ROUTE_CTRL_DISB_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_NON_IP_ACT_LSP     16u
#define DV1_L3_IPUC_ROUTE_CTRL_NON_IP_ACT_LEN     1u
#define DV1_L3_IPUC_ROUTE_CTRL_NON_IP_ACT_TYPE    DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_URPF_BASE_SEL_LSP  15u
#define DV1_L3_IPUC_ROUTE_CTRL_URPF_BASE_SEL_LEN  1u
#define DV1_L3_IPUC_ROUTE_CTRL_URPF_BASE_SEL_TYPE DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_LU_MIS_ACT_LSP     13u
#define DV1_L3_IPUC_ROUTE_CTRL_LU_MIS_ACT_LEN     2u
#define DV1_L3_IPUC_ROUTE_CTRL_LU_MIS_ACT_TYPE    DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_TTL_FAIL_ACT_LSP   12u
#define DV1_L3_IPUC_ROUTE_CTRL_TTL_FAIL_ACT_LEN   1u
#define DV1_L3_IPUC_ROUTE_CTRL_TTL_FAIL_ACT_TYPE  DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_MTU_FAIL_ACT_LSP   11u
#define DV1_L3_IPUC_ROUTE_CTRL_MTU_FAIL_ACT_LEN   1u
#define DV1_L3_IPUC_ROUTE_CTRL_MTU_FAIL_ACT_TYPE  DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_HDR_OPT_ACT_LSP    8u
#define DV1_L3_IPUC_ROUTE_CTRL_HDR_OPT_ACT_LEN    3u
#define DV1_L3_IPUC_ROUTE_CTRL_HDR_OPT_ACT_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_DMAC_MC_ACT_LSP    7u
#define DV1_L3_IPUC_ROUTE_CTRL_DMAC_MC_ACT_LEN    1u
#define DV1_L3_IPUC_ROUTE_CTRL_DMAC_MC_ACT_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_DMAC_BC_ACT_LSP    6u
#define DV1_L3_IPUC_ROUTE_CTRL_DMAC_BC_ACT_LEN    1u
#define DV1_L3_IPUC_ROUTE_CTRL_DMAC_BC_ACT_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_ZERO_SIP_ACT_LSP   5u
#define DV1_L3_IPUC_ROUTE_CTRL_ZERO_SIP_ACT_LEN   1u
#define DV1_L3_IPUC_ROUTE_CTRL_ZERO_SIP_ACT_TYPE  DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_BAD_DIP_ACT_LSP    4u
#define DV1_L3_IPUC_ROUTE_CTRL_BAD_DIP_ACT_LEN    1u
#define DV1_L3_IPUC_ROUTE_CTRL_BAD_DIP_ACT_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_BAD_SIP_ACT_LSP    3u
#define DV1_L3_IPUC_ROUTE_CTRL_BAD_SIP_ACT_LEN    1u
#define DV1_L3_IPUC_ROUTE_CTRL_BAD_SIP_ACT_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_HDR_ERR_ACT_LSP    1u
#define DV1_L3_IPUC_ROUTE_CTRL_HDR_ERR_ACT_LEN    2u
#define DV1_L3_IPUC_ROUTE_CTRL_HDR_ERR_ACT_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_IPUC_ROUTE_CTRL_GLB_EN_LSP         0u
#define DV1_L3_IPUC_ROUTE_CTRL_GLB_EN_LEN         1u
#define DV1_L3_IPUC_ROUTE_CTRL_GLB_EN_TYPE        DV1_FIELD_TYPE_RW

#define DV1_L3_IP6UC_ROUTE_CTRL_DISB_ACT_LSP           22u
#define DV1_L3_IP6UC_ROUTE_CTRL_DISB_ACT_LEN           2u
#define DV1_L3_IP6UC_ROUTE_CTRL_DISB_ACT_TYPE          DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_LU_MIS_ACT_LSP         20u
#define DV1_L3_IP6UC_ROUTE_CTRL_LU_MIS_ACT_LEN         2u
#define DV1_L3_IP6UC_ROUTE_CTRL_LU_MIS_ACT_TYPE        DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_NON_IP_ACT_LSP         19u
#define DV1_L3_IP6UC_ROUTE_CTRL_NON_IP_ACT_LEN         1u
#define DV1_L3_IP6UC_ROUTE_CTRL_NON_IP_ACT_TYPE        DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_URPF_BASE_SEL_LSP      18u
#define DV1_L3_IP6UC_ROUTE_CTRL_URPF_BASE_SEL_LEN      1u
#define DV1_L3_IP6UC_ROUTE_CTRL_URPF_BASE_SEL_TYPE     DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_HL_FAIL_ACT_LSP        17u
#define DV1_L3_IP6UC_ROUTE_CTRL_HL_FAIL_ACT_LEN        1u
#define DV1_L3_IP6UC_ROUTE_CTRL_HL_FAIL_ACT_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_MTU_FAIL_ACT_LSP       16u
#define DV1_L3_IP6UC_ROUTE_CTRL_MTU_FAIL_ACT_LEN       1u
#define DV1_L3_IP6UC_ROUTE_CTRL_MTU_FAIL_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_HDR_ROUTE_ACT_LSP      13u
#define DV1_L3_IP6UC_ROUTE_CTRL_HDR_ROUTE_ACT_LEN      3u
#define DV1_L3_IP6UC_ROUTE_CTRL_HDR_ROUTE_ACT_TYPE     DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_HBH_ERR_ACT_LSP        10u
#define DV1_L3_IP6UC_ROUTE_CTRL_HBH_ERR_ACT_LEN        3u
#define DV1_L3_IP6UC_ROUTE_CTRL_HBH_ERR_ACT_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_HBH_ACT_LSP            7u
#define DV1_L3_IP6UC_ROUTE_CTRL_HBH_ACT_LEN            3u
#define DV1_L3_IP6UC_ROUTE_CTRL_HBH_ACT_TYPE           DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_DMAC_MISMATCH_ACT_LSP  6u
#define DV1_L3_IP6UC_ROUTE_CTRL_DMAC_MISMATCH_ACT_LEN  1u
#define DV1_L3_IP6UC_ROUTE_CTRL_DMAC_MISMATCH_ACT_TYPE DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_ZERO_SIP_ACT_LSP       5u
#define DV1_L3_IP6UC_ROUTE_CTRL_ZERO_SIP_ACT_LEN       1u
#define DV1_L3_IP6UC_ROUTE_CTRL_ZERO_SIP_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_BAD_DIP_ACT_LSP        4u
#define DV1_L3_IP6UC_ROUTE_CTRL_BAD_DIP_ACT_LEN        1u
#define DV1_L3_IP6UC_ROUTE_CTRL_BAD_DIP_ACT_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_BAD_SIP_ACT_LSP        3u
#define DV1_L3_IP6UC_ROUTE_CTRL_BAD_SIP_ACT_LEN        1u
#define DV1_L3_IP6UC_ROUTE_CTRL_BAD_SIP_ACT_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_HDR_ERR_ACT_LSP        1u
#define DV1_L3_IP6UC_ROUTE_CTRL_HDR_ERR_ACT_LEN        2u
#define DV1_L3_IP6UC_ROUTE_CTRL_HDR_ERR_ACT_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_IP6UC_ROUTE_CTRL_GLB_EN_LSP             0u
#define DV1_L3_IP6UC_ROUTE_CTRL_GLB_EN_LEN             1u
#define DV1_L3_IP6UC_ROUTE_CTRL_GLB_EN_TYPE            DV1_FIELD_TYPE_RW

#define DV1_L3_IPMC_ROUTE_CTRL_DAHIT_ACT_LSP          15u
#define DV1_L3_IPMC_ROUTE_CTRL_DAHIT_ACT_LEN          1u
#define DV1_L3_IPMC_ROUTE_CTRL_DAHIT_ACT_TYPE         DV1_FIELD_TYPE_RW
#define DV1_L3_IPMC_ROUTE_CTRL_LU_MIS_ACT_LSP         14u
#define DV1_L3_IPMC_ROUTE_CTRL_LU_MIS_ACT_LEN         1u
#define DV1_L3_IPMC_ROUTE_CTRL_LU_MIS_ACT_TYPE        DV1_FIELD_TYPE_RW
#define DV1_L3_IPMC_ROUTE_CTRL_TTL_FAIL_ACT_LSP       13u
#define DV1_L3_IPMC_ROUTE_CTRL_TTL_FAIL_ACT_LEN       1u
#define DV1_L3_IPMC_ROUTE_CTRL_TTL_FAIL_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_IPMC_ROUTE_CTRL_MTU_FAIL_ACT_LSP       12u
#define DV1_L3_IPMC_ROUTE_CTRL_MTU_FAIL_ACT_LEN       1u
#define DV1_L3_IPMC_ROUTE_CTRL_MTU_FAIL_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_IPMC_ROUTE_CTRL_HDR_OPT_ACT_LSP        9u
#define DV1_L3_IPMC_ROUTE_CTRL_HDR_OPT_ACT_LEN        3u
#define DV1_L3_IPMC_ROUTE_CTRL_HDR_OPT_ACT_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_IPMC_ROUTE_CTRL_DMAC_MISMATCH_ACT_LSP  7u
#define DV1_L3_IPMC_ROUTE_CTRL_DMAC_MISMATCH_ACT_LEN  2u
#define DV1_L3_IPMC_ROUTE_CTRL_DMAC_MISMATCH_ACT_TYPE DV1_FIELD_TYPE_RW
#define DV1_L3_IPMC_ROUTE_CTRL_ZERO_SIP_ACT_LSP       5u
#define DV1_L3_IPMC_ROUTE_CTRL_ZERO_SIP_ACT_LEN       2u
#define DV1_L3_IPMC_ROUTE_CTRL_ZERO_SIP_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_IPMC_ROUTE_CTRL_BAD_SIP_ACT_LSP        3u
#define DV1_L3_IPMC_ROUTE_CTRL_BAD_SIP_ACT_LEN        2u
#define DV1_L3_IPMC_ROUTE_CTRL_BAD_SIP_ACT_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_IPMC_ROUTE_CTRL_IP_HDR_ERR_ACT_LSP     1u
#define DV1_L3_IPMC_ROUTE_CTRL_IP_HDR_ERR_ACT_LEN     2u
#define DV1_L3_IPMC_ROUTE_CTRL_IP_HDR_ERR_ACT_TYPE    DV1_FIELD_TYPE_RW
#define DV1_L3_IPMC_ROUTE_CTRL_GLB_EN_LSP             0u
#define DV1_L3_IPMC_ROUTE_CTRL_GLB_EN_LEN             1u
#define DV1_L3_IPMC_ROUTE_CTRL_GLB_EN_TYPE            DV1_FIELD_TYPE_RW

#define DV1_L3_IP6MC_ROUTE_CTRL_DAHIT_ACT_LSP          21u
#define DV1_L3_IP6MC_ROUTE_CTRL_DAHIT_ACT_LEN          1u
#define DV1_L3_IP6MC_ROUTE_CTRL_DAHIT_ACT_TYPE         DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_LU_MIS_ACT_LSP         20u
#define DV1_L3_IP6MC_ROUTE_CTRL_LU_MIS_ACT_LEN         1u
#define DV1_L3_IP6MC_ROUTE_CTRL_LU_MIS_ACT_TYPE        DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_HL_FAIL_ACT_LSP        19u
#define DV1_L3_IP6MC_ROUTE_CTRL_HL_FAIL_ACT_LEN        1u
#define DV1_L3_IP6MC_ROUTE_CTRL_HL_FAIL_ACT_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_MTU_FAIL_ACT_LSP       18u
#define DV1_L3_IP6MC_ROUTE_CTRL_MTU_FAIL_ACT_LEN       1u
#define DV1_L3_IP6MC_ROUTE_CTRL_MTU_FAIL_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_HDR_ROUTE_ACT_LSP      15u
#define DV1_L3_IP6MC_ROUTE_CTRL_HDR_ROUTE_ACT_LEN      3u
#define DV1_L3_IP6MC_ROUTE_CTRL_HDR_ROUTE_ACT_TYPE     DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_HBH_ERR_ACT_LSP        12u
#define DV1_L3_IP6MC_ROUTE_CTRL_HBH_ERR_ACT_LEN        3u
#define DV1_L3_IP6MC_ROUTE_CTRL_HBH_ERR_ACT_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_HBH_ACT_LSP            9u
#define DV1_L3_IP6MC_ROUTE_CTRL_HBH_ACT_LEN            3u
#define DV1_L3_IP6MC_ROUTE_CTRL_HBH_ACT_TYPE           DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_DMAC_MISMATCH_ACT_LSP  7u
#define DV1_L3_IP6MC_ROUTE_CTRL_DMAC_MISMATCH_ACT_LEN  2u
#define DV1_L3_IP6MC_ROUTE_CTRL_DMAC_MISMATCH_ACT_TYPE DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_ZERO_SIP_ACT_LSP       5u
#define DV1_L3_IP6MC_ROUTE_CTRL_ZERO_SIP_ACT_LEN       2u
#define DV1_L3_IP6MC_ROUTE_CTRL_ZERO_SIP_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_BAD_SIP_ACT_LSP        3u
#define DV1_L3_IP6MC_ROUTE_CTRL_BAD_SIP_ACT_LEN        2u
#define DV1_L3_IP6MC_ROUTE_CTRL_BAD_SIP_ACT_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_IP6_HDR_ERR_ACT_LSP    1u
#define DV1_L3_IP6MC_ROUTE_CTRL_IP6_HDR_ERR_ACT_LEN    2u
#define DV1_L3_IP6MC_ROUTE_CTRL_IP6_HDR_ERR_ACT_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_IP6MC_ROUTE_CTRL_GLB_EN_LSP             0u
#define DV1_L3_IP6MC_ROUTE_CTRL_GLB_EN_LEN             1u
#define DV1_L3_IP6MC_ROUTE_CTRL_GLB_EN_TYPE            DV1_FIELD_TYPE_RW

#define DV1_L3_HOST_TBL_CTRL_UC_TBL1_ALG_LSP  1u
#define DV1_L3_HOST_TBL_CTRL_UC_TBL1_ALG_LEN  1u
#define DV1_L3_HOST_TBL_CTRL_UC_TBL1_ALG_TYPE DV1_FIELD_TYPE_RW
#define DV1_L3_HOST_TBL_CTRL_UC_TBL0_ALG_LSP  0u
#define DV1_L3_HOST_TBL_CTRL_UC_TBL0_ALG_LEN  1u
#define DV1_L3_HOST_TBL_CTRL_UC_TBL0_ALG_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_PORT_IP_ROUTE_CTRL_URPF_CHK_EN_LSP  0u
#define DV1_L3_PORT_IP_ROUTE_CTRL_URPF_CHK_EN_LEN  1u
#define DV1_L3_PORT_IP_ROUTE_CTRL_URPF_CHK_EN_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_PORT_IP6_ROUTE_CTRL_URPF_CHK_EN_LSP  0u
#define DV1_L3_PORT_IP6_ROUTE_CTRL_URPF_CHK_EN_LEN  1u
#define DV1_L3_PORT_IP6_ROUTE_CTRL_URPF_CHK_EN_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TRAP_CPU_DPM_TRAP_CPU_DPM_LSP  0u
#define DV1_L3_TRAP_CPU_DPM_TRAP_CPU_DPM_LEN  16u
#define DV1_L3_TRAP_CPU_DPM_TRAP_CPU_DPM_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_COPY_CPU_DPM_COPY_CPU_DPM_LSP  0u
#define DV1_L3_COPY_CPU_DPM_COPY_CPU_DPM_LEN  16u
#define DV1_L3_COPY_CPU_DPM_COPY_CPU_DPM_TYPE DV1_FIELD_TYPE_RW

#define DV1_ROUTING_RSV_0_ROUTING_RSV_0_LSP  0u
#define DV1_ROUTING_RSV_0_ROUTING_RSV_0_LEN  32u
#define DV1_ROUTING_RSV_0_ROUTING_RSV_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_ROUTING_RSV_1_ROUTING_RSV_1_LSP  0u
#define DV1_ROUTING_RSV_1_ROUTING_RSV_1_LEN  32u
#define DV1_ROUTING_RSV_1_ROUTING_RSV_1_TYPE DV1_FIELD_TYPE_RO

#define DV1_ROUTING_RSV_2_ROUTING_RSV_2_LSP  0u
#define DV1_ROUTING_RSV_2_ROUTING_RSV_2_LEN  32u
#define DV1_ROUTING_RSV_2_ROUTING_RSV_2_TYPE DV1_FIELD_TYPE_RO

#define DV1_ROUTING_RSV_3_ROUTING_RSV_3_LSP  0u
#define DV1_ROUTING_RSV_3_ROUTING_RSV_3_LEN  32u
#define DV1_ROUTING_RSV_3_ROUTING_RSV_3_TYPE DV1_FIELD_TYPE_RO

#define DV1_ROUTING_RSV_4_ROUTING_RSV_4_LSP  0u
#define DV1_ROUTING_RSV_4_ROUTING_RSV_4_LEN  32u
#define DV1_ROUTING_RSV_4_ROUTING_RSV_4_TYPE DV1_FIELD_TYPE_RO

#define DV1_ROUTING_RSV_5_ROUTING_RSV_5_LSP  0u
#define DV1_ROUTING_RSV_5_ROUTING_RSV_5_LEN  32u
#define DV1_ROUTING_RSV_5_ROUTING_RSV_5_TYPE DV1_FIELD_TYPE_RO

#define DV1_ROUTING_RSV_6_ROUTING_RSV_6_LSP  0u
#define DV1_ROUTING_RSV_6_ROUTING_RSV_6_LEN  32u
#define DV1_ROUTING_RSV_6_ROUTING_RSV_6_TYPE DV1_FIELD_TYPE_RO

#define DV1_ROUTING_RSV_7_ROUTING_RSV_7_LSP  0u
#define DV1_ROUTING_RSV_7_ROUTING_RSV_7_LEN  32u
#define DV1_ROUTING_RSV_7_ROUTING_RSV_7_TYPE DV1_FIELD_TYPE_RO

#define DV1_L3_GLOBAL_CONTROL0_RANGE_CHECK_EN_LSP  3u
#define DV1_L3_GLOBAL_CONTROL0_RANGE_CHECK_EN_LEN  1u
#define DV1_L3_GLOBAL_CONTROL0_RANGE_CHECK_EN_TYPE DV1_FIELD_TYPE_RW
#define DV1_L3_GLOBAL_CONTROL0_ANYKEY_EN_LSP       2u
#define DV1_L3_GLOBAL_CONTROL0_ANYKEY_EN_LEN       1u
#define DV1_L3_GLOBAL_CONTROL0_ANYKEY_EN_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_GLOBAL_CONTROL0_ACL_UC_TTLDEC_LSP   1u
#define DV1_L3_GLOBAL_CONTROL0_ACL_UC_TTLDEC_LEN   1u
#define DV1_L3_GLOBAL_CONTROL0_ACL_UC_TTLDEC_TYPE  DV1_FIELD_TYPE_RW
#define DV1_L3_GLOBAL_CONTROL0_ROUTE_DPM_SEL_LSP   0u
#define DV1_L3_GLOBAL_CONTROL0_ROUTE_DPM_SEL_LEN   1u
#define DV1_L3_GLOBAL_CONTROL0_ROUTE_DPM_SEL_TYPE  DV1_FIELD_TYPE_RW

#define DV1_L3_STATUS_MC_MISS_LSP            9u
#define DV1_L3_STATUS_MC_MISS_LEN            1u
#define DV1_L3_STATUS_MC_MISS_TYPE           DV1_FIELD_TYPE_RO
#define DV1_L3_STATUS_COLTBL_MC_2ND_HIT_LSP  8u
#define DV1_L3_STATUS_COLTBL_MC_2ND_HIT_LEN  1u
#define DV1_L3_STATUS_COLTBL_MC_2ND_HIT_TYPE DV1_FIELD_TYPE_RO
#define DV1_L3_STATUS_HOSTBL_MC_2ND_HIT_LSP  7u
#define DV1_L3_STATUS_HOSTBL_MC_2ND_HIT_LEN  1u
#define DV1_L3_STATUS_HOSTBL_MC_2ND_HIT_TYPE DV1_FIELD_TYPE_RO
#define DV1_L3_STATUS_COLTBL_MC_1ST_HIT_LSP  6u
#define DV1_L3_STATUS_COLTBL_MC_1ST_HIT_LEN  1u
#define DV1_L3_STATUS_COLTBL_MC_1ST_HIT_TYPE DV1_FIELD_TYPE_RO
#define DV1_L3_STATUS_HOSTBL_MC_1ST_HIT_LSP  5u
#define DV1_L3_STATUS_HOSTBL_MC_1ST_HIT_LEN  1u
#define DV1_L3_STATUS_HOSTBL_MC_1ST_HIT_TYPE DV1_FIELD_TYPE_RO
#define DV1_L3_STATUS_UC_MISS_LSP            4u
#define DV1_L3_STATUS_UC_MISS_LEN            1u
#define DV1_L3_STATUS_UC_MISS_TYPE           DV1_FIELD_TYPE_RO
#define DV1_L3_STATUS_NETBL_UC_HIT_LSP       3u
#define DV1_L3_STATUS_NETBL_UC_HIT_LEN       1u
#define DV1_L3_STATUS_NETBL_UC_HIT_TYPE      DV1_FIELD_TYPE_RO
#define DV1_L3_STATUS_HOSTBL_UC_HIT_LSP      2u
#define DV1_L3_STATUS_HOSTBL_UC_HIT_LEN      1u
#define DV1_L3_STATUS_HOSTBL_UC_HIT_TYPE     DV1_FIELD_TYPE_RO
#define DV1_L3_STATUS_IGRIF_HIT_LSP          1u
#define DV1_L3_STATUS_IGRIF_HIT_LEN          1u
#define DV1_L3_STATUS_IGRIF_HIT_TYPE         DV1_FIELD_TYPE_RO
#define DV1_L3_STATUS_IGRIF_MISS_LSP         0u
#define DV1_L3_STATUS_IGRIF_MISS_LEN         1u
#define DV1_L3_STATUS_IGRIF_MISS_TYPE        DV1_FIELD_TYPE_RO

#define DV1_L3_UCAST_PACKET_CNT0_ROUTE_UCPKT_CNT_0_LSP  0u
#define DV1_L3_UCAST_PACKET_CNT0_ROUTE_UCPKT_CNT_0_LEN  32u
#define DV1_L3_UCAST_PACKET_CNT0_ROUTE_UCPKT_CNT_0_TYPE DV1_FIELD_TYPE_RWS

#define DV1_L3_UCAST_PACKET_CNT1_ROUTE_UCPKT_CNT_1_LSP  0u
#define DV1_L3_UCAST_PACKET_CNT1_ROUTE_UCPKT_CNT_1_LEN  32u
#define DV1_L3_UCAST_PACKET_CNT1_ROUTE_UCPKT_CNT_1_TYPE DV1_FIELD_TYPE_RWS

#define DV1_L3_MBCAST_PACKET_CNT0_ROUTE_MBCPKT_CNT_0_LSP  0u
#define DV1_L3_MBCAST_PACKET_CNT0_ROUTE_MBCPKT_CNT_0_LEN  32u
#define DV1_L3_MBCAST_PACKET_CNT0_ROUTE_MBCPKT_CNT_0_TYPE DV1_FIELD_TYPE_RWS

#define DV1_L3_MBCAST_PACKET_CNT1_ROUTE_MBCPKT_CNT_1_LSP  0u
#define DV1_L3_MBCAST_PACKET_CNT1_ROUTE_MBCPKT_CNT_1_LEN  32u
#define DV1_L3_MBCAST_PACKET_CNT1_ROUTE_MBCPKT_CNT_1_TYPE DV1_FIELD_TYPE_RWS

#define DV1_L3_ALL_BYTE_CNT0_ROUTE_ALLBYTE_CNT_0_LSP  0u
#define DV1_L3_ALL_BYTE_CNT0_ROUTE_ALLBYTE_CNT_0_LEN  32u
#define DV1_L3_ALL_BYTE_CNT0_ROUTE_ALLBYTE_CNT_0_TYPE DV1_FIELD_TYPE_RWS

#define DV1_L3_ALL_BYTE_CNT1_ROUTE_ALLBYTE_CNT_1_LSP  0u
#define DV1_L3_ALL_BYTE_CNT1_ROUTE_ALLBYTE_CNT_1_LEN  32u
#define DV1_L3_ALL_BYTE_CNT1_ROUTE_ALLBYTE_CNT_1_TYPE DV1_FIELD_TYPE_RWS

#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_HOST_GROUP_TBL_LSP  8u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_HOST_GROUP_TBL_LEN  1u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_HOST_GROUP_TBL_TYPE DV1_FIELD_TYPE_RW1C
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_EGRIF_TBL_LSP       7u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_EGRIF_TBL_LEN       1u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_EGRIF_TBL_TYPE      DV1_FIELD_TYPE_RW1C
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_OIL_TBL_LSP         6u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_OIL_TBL_LEN         1u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_OIL_TBL_TYPE        DV1_FIELD_TYPE_RW1C
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_NH_TBL_LSP          5u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_NH_TBL_LEN          1u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_NH_TBL_TYPE         DV1_FIELD_TYPE_RW1C
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_RH_TBL_LSP          4u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_RH_TBL_LEN          1u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_RH_TBL_TYPE         DV1_FIELD_TYPE_RW1C
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_MCCOL_TBL_LSP       3u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_MCCOL_TBL_LEN       1u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_MCCOL_TBL_TYPE      DV1_FIELD_TYPE_RW1C
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_NET_TBL_LSP         2u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_NET_TBL_LEN         1u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_NET_TBL_TYPE        DV1_FIELD_TYPE_RW1C
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_HOST_TBL_LSP        1u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_HOST_TBL_LEN        1u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_HOST_TBL_TYPE       DV1_FIELD_TYPE_RW1C
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_IGRIF_TBL_LSP       0u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_IGRIF_TBL_LEN       1u
#define DV1_L3_TABLE_CLEAR_CTRL_CLEAR_IGRIF_TBL_TYPE      DV1_FIELD_TYPE_RW1C

#define DV1_L3_TABLE_SEARCH_CONTROL0_PORT_FMT_LSP           3u
#define DV1_L3_TABLE_SEARCH_CONTROL0_PORT_FMT_LEN           1u
#define DV1_L3_TABLE_SEARCH_CONTROL0_PORT_FMT_TYPE          DV1_FIELD_TYPE_RW
#define DV1_L3_TABLE_SEARCH_CONTROL0_TYPE_LSP               1u
#define DV1_L3_TABLE_SEARCH_CONTROL0_TYPE_LEN               2u
#define DV1_L3_TABLE_SEARCH_CONTROL0_TYPE_TYPE              DV1_FIELD_TYPE_RW
#define DV1_L3_TABLE_SEARCH_CONTROL0_L3_SEARCH_TRIGGER_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL0_L3_SEARCH_TRIGGER_LEN  1u
#define DV1_L3_TABLE_SEARCH_CONTROL0_L3_SEARCH_TRIGGER_TYPE DV1_FIELD_TYPE_RW1C

#define DV1_L3_TABLE_SEARCH_CONTROL1_SOURCE_IPV6_ADDR_0_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL1_SOURCE_IPV6_ADDR_0_LEN  32u
#define DV1_L3_TABLE_SEARCH_CONTROL1_SOURCE_IPV6_ADDR_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TABLE_SEARCH_CONTROL2_SOURCE_IPV6_ADDR_1_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL2_SOURCE_IPV6_ADDR_1_LEN  32u
#define DV1_L3_TABLE_SEARCH_CONTROL2_SOURCE_IPV6_ADDR_1_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TABLE_SEARCH_CONTROL3_SOURCE_IPV6_ADDR_2_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL3_SOURCE_IPV6_ADDR_2_LEN  32u
#define DV1_L3_TABLE_SEARCH_CONTROL3_SOURCE_IPV6_ADDR_2_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TABLE_SEARCH_CONTROL4_SOURCE_IPV6_ADDR_3_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL4_SOURCE_IPV6_ADDR_3_LEN  32u
#define DV1_L3_TABLE_SEARCH_CONTROL4_SOURCE_IPV6_ADDR_3_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TABLE_SEARCH_CONTROL5_DEST_IPV6_ADDR_0_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL5_DEST_IPV6_ADDR_0_LEN  32u
#define DV1_L3_TABLE_SEARCH_CONTROL5_DEST_IPV6_ADDR_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TABLE_SEARCH_CONTROL6_DEST_IPV6_ADDR_1_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL6_DEST_IPV6_ADDR_1_LEN  32u
#define DV1_L3_TABLE_SEARCH_CONTROL6_DEST_IPV6_ADDR_1_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TABLE_SEARCH_CONTROL7_DEST_IPV6_ADDR_2_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL7_DEST_IPV6_ADDR_2_LEN  32u
#define DV1_L3_TABLE_SEARCH_CONTROL7_DEST_IPV6_ADDR_2_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TABLE_SEARCH_CONTROL8_DEST_IPV6_ADDR_3_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL8_DEST_IPV6_ADDR_3_LEN  32u
#define DV1_L3_TABLE_SEARCH_CONTROL8_DEST_IPV6_ADDR_3_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TABLE_SEARCH_CONTROL9_DPORT_LSP  16u
#define DV1_L3_TABLE_SEARCH_CONTROL9_DPORT_LEN  16u
#define DV1_L3_TABLE_SEARCH_CONTROL9_DPORT_TYPE DV1_FIELD_TYPE_RW
#define DV1_L3_TABLE_SEARCH_CONTROL9_SPORT_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL9_SPORT_LEN  16u
#define DV1_L3_TABLE_SEARCH_CONTROL9_SPORT_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TABLE_SEARCH_CONTROL10_VID_LSP  0u
#define DV1_L3_TABLE_SEARCH_CONTROL10_VID_LEN  12u
#define DV1_L3_TABLE_SEARCH_CONTROL10_VID_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TABLE_SEARCH_STATUS0_HASH_IDX_BTM_LSP  10u
#define DV1_L3_TABLE_SEARCH_STATUS0_HASH_IDX_BTM_LEN  9u
#define DV1_L3_TABLE_SEARCH_STATUS0_HASH_IDX_BTM_TYPE DV1_FIELD_TYPE_RO
#define DV1_L3_TABLE_SEARCH_STATUS0_HASH_IDX_TOP_LSP  1u
#define DV1_L3_TABLE_SEARCH_STATUS0_HASH_IDX_TOP_LEN  9u
#define DV1_L3_TABLE_SEARCH_STATUS0_HASH_IDX_TOP_TYPE DV1_FIELD_TYPE_RO
#define DV1_L3_TABLE_SEARCH_STATUS0_FOUND_LSP         0u
#define DV1_L3_TABLE_SEARCH_STATUS0_FOUND_LEN         1u
#define DV1_L3_TABLE_SEARCH_STATUS0_FOUND_TYPE        DV1_FIELD_TYPE_RO

#define DV1_L3_TABLE_SEARCH_STATUS1_VALID_MASK_BTM_LSP  12u
#define DV1_L3_TABLE_SEARCH_STATUS1_VALID_MASK_BTM_LEN  12u
#define DV1_L3_TABLE_SEARCH_STATUS1_VALID_MASK_BTM_TYPE DV1_FIELD_TYPE_RO
#define DV1_L3_TABLE_SEARCH_STATUS1_VALID_MASK_TOP_LSP  0u
#define DV1_L3_TABLE_SEARCH_STATUS1_VALID_MASK_TOP_LEN  12u
#define DV1_L3_TABLE_SEARCH_STATUS1_VALID_MASK_TOP_TYPE DV1_FIELD_TYPE_RO

#define DV1_L3_TCAM_ERROR_NETBL_ERR_IDX_LSP  7u
#define DV1_L3_TCAM_ERROR_NETBL_ERR_IDX_LEN  9u
#define DV1_L3_TCAM_ERROR_NETBL_ERR_IDX_TYPE DV1_FIELD_TYPE_RO
#define DV1_L3_TCAM_ERROR_IGRIF_ERR_IDX_LSP  0u
#define DV1_L3_TCAM_ERROR_IGRIF_ERR_IDX_LEN  7u
#define DV1_L3_TCAM_ERROR_IGRIF_ERR_IDX_TYPE DV1_FIELD_TYPE_RO

#define DV1_L3NH_L2DA_CONTROL_L3NH_AGEOUT_ACT_LSP         2u
#define DV1_L3NH_L2DA_CONTROL_L3NH_AGEOUT_ACT_LEN         2u
#define DV1_L3NH_L2DA_CONTROL_L3NH_AGEOUT_ACT_TYPE        DV1_FIELD_TYPE_RW
#define DV1_L3NH_L2DA_CONTROL_L3NH_AGEOUT_ACT_EN_LSP      1u
#define DV1_L3NH_L2DA_CONTROL_L3NH_AGEOUT_ACT_EN_LEN      1u
#define DV1_L3NH_L2DA_CONTROL_L3NH_AGEOUT_ACT_EN_TYPE     DV1_FIELD_TYPE_RW
#define DV1_L3NH_L2DA_CONTROL_L2MC_DA_MISS_BYPASS_EN_LSP  0u
#define DV1_L3NH_L2DA_CONTROL_L2MC_DA_MISS_BYPASS_EN_LEN  1u
#define DV1_L3NH_L2DA_CONTROL_L2MC_DA_MISS_BYPASS_EN_TYPE DV1_FIELD_TYPE_RW

#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DIP_LKUP_CHK_QOSEN_LSP  31u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DIP_LKUP_CHK_QOSEN_LEN  1u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DIP_LKUP_CHK_QOSEN_TYPE DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DIP_LKUP_CHK_PRI_LSP    28u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DIP_LKUP_CHK_PRI_LEN    3u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DIP_LKUP_CHK_PRI_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_URPF_CHK_QOSEN_LSP      27u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_URPF_CHK_QOSEN_LEN      1u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_URPF_CHK_QOSEN_TYPE     DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_URPF_CHK_PRI_LSP        24u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_URPF_CHK_PRI_LEN        3u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_URPF_CHK_PRI_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDREXT_CHK_QOSEN_LSP    23u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDREXT_CHK_QOSEN_LEN    1u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDREXT_CHK_QOSEN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDREXT_CHK_PRI_LSP      20u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDREXT_CHK_PRI_LEN      3u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDREXT_CHK_PRI_TYPE     DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DMAC_CHK_QOSEN_LSP      19u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DMAC_CHK_QOSEN_LEN      1u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DMAC_CHK_QOSEN_TYPE     DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DMAC_CHK_PRI_LSP        16u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DMAC_CHK_PRI_LEN        3u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_DMAC_CHK_PRI_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_IP_CHK_QOSEN_LSP        15u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_IP_CHK_QOSEN_LEN        1u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_IP_CHK_QOSEN_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_IP_CHK_PRI_LSP          12u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_IP_CHK_PRI_LEN          3u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_IP_CHK_PRI_TYPE         DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDR_CHK_QOSEN_LSP       11u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDR_CHK_QOSEN_LEN       1u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDR_CHK_QOSEN_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDR_CHK_PRI_LSP         8u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDR_CHK_PRI_LEN         3u
#define DV1_L3_TRAP_QOS0_ROUTE_UCAST_HDR_CHK_PRI_TYPE        DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_IP_CHK_QOSEN_LSP              7u
#define DV1_L3_TRAP_QOS0_ROUTE_IP_CHK_QOSEN_LEN              1u
#define DV1_L3_TRAP_QOS0_ROUTE_IP_CHK_QOSEN_TYPE             DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_IP_CHK_PRI_LSP                4u
#define DV1_L3_TRAP_QOS0_ROUTE_IP_CHK_PRI_LEN                3u
#define DV1_L3_TRAP_QOS0_ROUTE_IP_CHK_PRI_TYPE               DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_MAC_CHK_QOSEN_LSP             3u
#define DV1_L3_TRAP_QOS0_ROUTE_MAC_CHK_QOSEN_LEN             1u
#define DV1_L3_TRAP_QOS0_ROUTE_MAC_CHK_QOSEN_TYPE            DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS0_ROUTE_MAC_CHK_PRI_LSP               0u
#define DV1_L3_TRAP_QOS0_ROUTE_MAC_CHK_PRI_LEN               3u
#define DV1_L3_TRAP_QOS0_ROUTE_MAC_CHK_PRI_TYPE              DV1_FIELD_TYPE_RW

#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_LKMISS_QOSEN_LSP      27u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_LKMISS_QOSEN_LEN      1u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_LKMISS_QOSEN_TYPE     DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_LKMISS_PRI_LSP        24u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_LKMISS_PRI_LEN        3u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_LKMISS_PRI_TYPE       DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDREXT_CHK_QOSEN_LSP  23u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDREXT_CHK_QOSEN_LEN  1u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDREXT_CHK_QOSEN_TYPE DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDREXT_CHK_PRI_LSP    20u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDREXT_CHK_PRI_LEN    3u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDREXT_CHK_PRI_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_DMAC_CHK_QOSEN_LSP    19u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_DMAC_CHK_QOSEN_LEN    1u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_DMAC_CHK_QOSEN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_DMAC_CHK_PRI_LSP      16u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_DMAC_CHK_PRI_LEN      3u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_DMAC_CHK_PRI_TYPE     DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_SIP_CHK_QOSEN_LSP     15u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_SIP_CHK_QOSEN_LEN     1u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_SIP_CHK_QOSEN_TYPE    DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_SIP_CHK_PRI_LSP       12u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_SIP_CHK_PRI_LEN       3u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_SIP_CHK_PRI_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDR_CHK_QOSEN_LSP     11u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDR_CHK_QOSEN_LEN     1u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDR_CHK_QOSEN_TYPE    DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDR_CHK_PRI_LSP       8u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDR_CHK_PRI_LEN       3u
#define DV1_L3_TRAP_QOS1_ROUTE_MCAST_HDR_CHK_PRI_TYPE      DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_L3_OPTION_QOSEN_LSP         7u
#define DV1_L3_TRAP_QOS1_ROUTE_L3_OPTION_QOSEN_LEN         1u
#define DV1_L3_TRAP_QOS1_ROUTE_L3_OPTION_QOSEN_TYPE        DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_L3_OPTION_PRI_LSP           4u
#define DV1_L3_TRAP_QOS1_ROUTE_L3_OPTION_PRI_LEN           3u
#define DV1_L3_TRAP_QOS1_ROUTE_L3_OPTION_PRI_TYPE          DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_UCAST_TTL_CHK_QOSEN_LSP     3u
#define DV1_L3_TRAP_QOS1_ROUTE_UCAST_TTL_CHK_QOSEN_LEN     1u
#define DV1_L3_TRAP_QOS1_ROUTE_UCAST_TTL_CHK_QOSEN_TYPE    DV1_FIELD_TYPE_RW
#define DV1_L3_TRAP_QOS1_ROUTE_UCAST_TTL_CHK_PRI_LSP       0u
#define DV1_L3_TRAP_QOS1_ROUTE_UCAST_TTL_CHK_PRI_LEN       3u
#define DV1_L3_TRAP_QOS1_ROUTE_UCAST_TTL_CHK_PRI_TYPE      DV1_FIELD_TYPE_RW

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_ROUTING_H_ */