/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_LIST_FILE_SERDES_WTG_TOP_T1_H_
#define DV1_RTKAS_REG_LIST_FILE_SERDES_WTG_TOP_T1_H_

#ifdef DV1_FILE_SERDES_WTG_TOP_T1
/* File: serdes_wtg_top_t1 */
#define DV1_CFG_NCTL_REG_0                                  0x4A570000u
#define DV1_CFG_NCTL_REG_0_FIELDNUM                         19u
#define DV1_CFG_NCTL_REG_0_DEFAULTVAL                       0x0u
#define DV1_CFG_NCTL_REG_1                                  0x4A570004u
#define DV1_CFG_NCTL_REG_1_FIELDNUM                         3u
#define DV1_CFG_NCTL_REG_1_DEFAULTVAL                       0x0u
#define DV1_CFG_NCTL_REG_2                                  0x4A570008u
#define DV1_CFG_NCTL_REG_2_FIELDNUM                         3u
#define DV1_CFG_NCTL_REG_2_DEFAULTVAL                       0x0u
#define DV1_CFG_NCTL_REG_3                                  0x4A57000Cu
#define DV1_CFG_NCTL_REG_3_FIELDNUM                         2u
#define DV1_CFG_NCTL_REG_3_DEFAULTVAL                       0x0u
#define DV1_CFG_NCTL_REG_4                                  0x4A570010u
#define DV1_CFG_NCTL_REG_4_FIELDNUM                         2u
#define DV1_CFG_NCTL_REG_4_DEFAULTVAL                       0x0u
#define DV1_CFG_NCTL_REG_5                                  0x4A570014u
#define DV1_CFG_NCTL_REG_5_FIELDNUM                         2u
#define DV1_CFG_NCTL_REG_5_DEFAULTVAL                       0x0u
#define DV1_CFG_NCTL_REG_6                                  0x4A570018u
#define DV1_CFG_NCTL_REG_6_FIELDNUM                         2u
#define DV1_CFG_NCTL_REG_6_DEFAULTVAL                       0x0u
#define DV1_CFG_NCTL_REG_7                                  0x4A57001Cu
#define DV1_CFG_NCTL_REG_7_FIELDNUM                         4u
#define DV1_CFG_NCTL_REG_7_DEFAULTVAL                       0x0u
#define DV1_CFG_NCTL_REG_8                                  0x4A570020u
#define DV1_CFG_NCTL_REG_8_FIELDNUM                         4u
#define DV1_CFG_NCTL_REG_8_DEFAULTVAL                       0x0u
#define DV1_CFG_NCTL_REG_9                                  0x4A570024u
#define DV1_CFG_NCTL_REG_9_FIELDNUM                         4u
#define DV1_CFG_NCTL_REG_9_DEFAULTVAL                       0x0u
#define DV1_CFG_NCTL_REG_10                                 0x4A570028u
#define DV1_CFG_NCTL_REG_10_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_10_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_11                                 0x4A57002Cu
#define DV1_CFG_NCTL_REG_11_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_11_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_12                                 0x4A570030u
#define DV1_CFG_NCTL_REG_12_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_12_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_13                                 0x4A570034u
#define DV1_CFG_NCTL_REG_13_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_13_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_14                                 0x4A570038u
#define DV1_CFG_NCTL_REG_14_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_14_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_15                                 0x4A57003Cu
#define DV1_CFG_NCTL_REG_15_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_15_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_16                                 0x4A570040u
#define DV1_CFG_NCTL_REG_16_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_16_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_17                                 0x4A570044u
#define DV1_CFG_NCTL_REG_17_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_17_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_18                                 0x4A570048u
#define DV1_CFG_NCTL_REG_18_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_18_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_19                                 0x4A57004Cu
#define DV1_CFG_NCTL_REG_19_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_19_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_20                                 0x4A570050u
#define DV1_CFG_NCTL_REG_20_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_20_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_21                                 0x4A570054u
#define DV1_CFG_NCTL_REG_21_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_21_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_22                                 0x4A570058u
#define DV1_CFG_NCTL_REG_22_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_22_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_23                                 0x4A57005Cu
#define DV1_CFG_NCTL_REG_23_FIELDNUM                        7u
#define DV1_CFG_NCTL_REG_23_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_24                                 0x4A570060u
#define DV1_CFG_NCTL_REG_24_FIELDNUM                        3u
#define DV1_CFG_NCTL_REG_24_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_25                                 0x4A570064u
#define DV1_CFG_NCTL_REG_25_FIELDNUM                        19u
#define DV1_CFG_NCTL_REG_25_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_26                                 0x4A570068u
#define DV1_CFG_NCTL_REG_26_FIELDNUM                        3u
#define DV1_CFG_NCTL_REG_26_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_27                                 0x4A57006Cu
#define DV1_CFG_NCTL_REG_27_FIELDNUM                        3u
#define DV1_CFG_NCTL_REG_27_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_28                                 0x4A570070u
#define DV1_CFG_NCTL_REG_28_FIELDNUM                        2u
#define DV1_CFG_NCTL_REG_28_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_29                                 0x4A570074u
#define DV1_CFG_NCTL_REG_29_FIELDNUM                        2u
#define DV1_CFG_NCTL_REG_29_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_30                                 0x4A570078u
#define DV1_CFG_NCTL_REG_30_FIELDNUM                        2u
#define DV1_CFG_NCTL_REG_30_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_31                                 0x4A57007Cu
#define DV1_CFG_NCTL_REG_31_FIELDNUM                        2u
#define DV1_CFG_NCTL_REG_31_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_32                                 0x4A570080u
#define DV1_CFG_NCTL_REG_32_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_32_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_33                                 0x4A570084u
#define DV1_CFG_NCTL_REG_33_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_33_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_34                                 0x4A570088u
#define DV1_CFG_NCTL_REG_34_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_34_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_35                                 0x4A57008Cu
#define DV1_CFG_NCTL_REG_35_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_35_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_36                                 0x4A570090u
#define DV1_CFG_NCTL_REG_36_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_36_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_37                                 0x4A570094u
#define DV1_CFG_NCTL_REG_37_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_37_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_38                                 0x4A570098u
#define DV1_CFG_NCTL_REG_38_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_38_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_39                                 0x4A57009Cu
#define DV1_CFG_NCTL_REG_39_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_39_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_40                                 0x4A5700A0u
#define DV1_CFG_NCTL_REG_40_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_40_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_41                                 0x4A5700A4u
#define DV1_CFG_NCTL_REG_41_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_41_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_42                                 0x4A5700A8u
#define DV1_CFG_NCTL_REG_42_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_42_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_43                                 0x4A5700ACu
#define DV1_CFG_NCTL_REG_43_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_43_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_44                                 0x4A5700B0u
#define DV1_CFG_NCTL_REG_44_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_44_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_45                                 0x4A5700B4u
#define DV1_CFG_NCTL_REG_45_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_45_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_46                                 0x4A5700B8u
#define DV1_CFG_NCTL_REG_46_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_46_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_47                                 0x4A5700BCu
#define DV1_CFG_NCTL_REG_47_FIELDNUM                        4u
#define DV1_CFG_NCTL_REG_47_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_48                                 0x4A5700C0u
#define DV1_CFG_NCTL_REG_48_FIELDNUM                        7u
#define DV1_CFG_NCTL_REG_48_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_49                                 0x4A5700C4u
#define DV1_CFG_NCTL_REG_49_FIELDNUM                        3u
#define DV1_CFG_NCTL_REG_49_DEFAULTVAL                      0x0u
#define DV1_CFG_NCTL_REG_50                                 0x4A5700C8u
#define DV1_CFG_NCTL_REG_50_FIELDNUM                        7u
#define DV1_CFG_NCTL_REG_50_DEFAULTVAL                      0x2008020u
#define DV1_CFG_NCTL_REG_51                                 0x4A5700CCu
#define DV1_CFG_NCTL_REG_51_FIELDNUM                        3u
#define DV1_CFG_NCTL_REG_51_DEFAULTVAL                      0x20u
#define DV1_DPHY_CTRL_REG_0                                 0x4A5700D0u
#define DV1_DPHY_CTRL_REG_0_FIELDNUM                        9u
#define DV1_DPHY_CTRL_REG_0_DEFAULTVAL                      0x0u
#define DV1_VBGA_TOP_REG                                    0x4A5700D4u
#define DV1_VBGA_TOP_REG_FIELDNUM                           5u
#define DV1_VBGA_TOP_REG_DEFAULTVAL                         0x0u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_PCS_CTL               0x4AD70000u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM      6u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL    0x0u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_PCS_CTL               0x4AD70800u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM      6u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL    0x0u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_PCS_CTL               0x4AD71000u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM      6u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL    0x0u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_PCS_CTL               0x4AD71800u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM      6u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL    0x0u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_PCS_CTL               0x4AD72000u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM      6u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL    0x0u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_PCS_CTL               0x4AD72800u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM      6u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL    0x0u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_PCS_CTL               0x4AD73000u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM      6u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL    0x0u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_PCS_CTL               0x4AD73800u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM      6u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL    0x0u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_PCS_CTL               0x4AD74000u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM      6u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL    0x0u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_PCS_CTL               0x4AD74800u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM      6u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL    0x0u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_PCS_CTL              0x4AD75000u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM     6u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL   0x0u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_PCS_CTL              0x4AD75800u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM     6u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL   0x0u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_PCS_CTL              0x4AD76000u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM     6u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL   0x0u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_PCS_CTL              0x4AD76800u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM     6u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL   0x0u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_PCS_CTL              0x4AD77000u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM     6u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL   0x0u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_PCS_CTL              0x4AD77800u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_PCS_CTL_FIELDNUM     6u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_PCS_CTL_DEFAULTVAL   0x0u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_PCS_DATA              0x4AD70004u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM     2u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL   0x0u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_PCS_DATA              0x4AD70804u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM     2u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL   0x0u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_PCS_DATA              0x4AD71004u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM     2u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL   0x0u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_PCS_DATA              0x4AD71804u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM     2u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL   0x0u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_PCS_DATA              0x4AD72004u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM     2u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL   0x0u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_PCS_DATA              0x4AD72804u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM     2u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL   0x0u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_PCS_DATA              0x4AD73004u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM     2u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL   0x0u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_PCS_DATA              0x4AD73804u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM     2u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL   0x0u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_PCS_DATA              0x4AD74004u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM     2u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL   0x0u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_PCS_DATA              0x4AD74804u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM     2u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL   0x0u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_PCS_DATA             0x4AD75004u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM    2u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL  0x0u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_PCS_DATA             0x4AD75804u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM    2u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL  0x0u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_PCS_DATA             0x4AD76004u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM    2u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL  0x0u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_PCS_DATA             0x4AD76804u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM    2u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL  0x0u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_PCS_DATA             0x4AD77004u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM    2u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL  0x0u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_PCS_DATA             0x4AD77804u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_PCS_DATA_FIELDNUM    2u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_PCS_DATA_DEFAULTVAL  0x0u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_DPHY_CTL              0x4AD70008u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM     6u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL   0x0u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_DPHY_CTL              0x4AD70808u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM     6u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL   0x0u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_DPHY_CTL              0x4AD71008u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM     6u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL   0x0u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_DPHY_CTL              0x4AD71808u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM     6u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL   0x0u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_DPHY_CTL              0x4AD72008u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM     6u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL   0x0u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_DPHY_CTL              0x4AD72808u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM     6u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL   0x0u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_DPHY_CTL              0x4AD73008u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM     6u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL   0x0u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_DPHY_CTL              0x4AD73808u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM     6u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL   0x0u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_DPHY_CTL              0x4AD74008u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM     6u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL   0x0u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_DPHY_CTL              0x4AD74808u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM     6u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL   0x0u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_DPHY_CTL             0x4AD75008u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM    6u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL  0x0u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_DPHY_CTL             0x4AD75808u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM    6u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL  0x0u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_DPHY_CTL             0x4AD76008u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM    6u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL  0x0u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_DPHY_CTL             0x4AD76808u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM    6u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL  0x0u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_DPHY_CTL             0x4AD77008u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM    6u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL  0x0u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_DPHY_CTL             0x4AD77808u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_DPHY_CTL_FIELDNUM    6u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_DPHY_CTL_DEFAULTVAL  0x0u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_DPHY_DATA             0x4AD7000Cu
#define DV1_PORT0_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM    2u
#define DV1_PORT0_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL  0x0u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_DPHY_DATA             0x4AD7080Cu
#define DV1_PORT1_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM    2u
#define DV1_PORT1_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL  0x0u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_DPHY_DATA             0x4AD7100Cu
#define DV1_PORT2_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM    2u
#define DV1_PORT2_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL  0x0u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_DPHY_DATA             0x4AD7180Cu
#define DV1_PORT3_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM    2u
#define DV1_PORT3_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL  0x0u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_DPHY_DATA             0x4AD7200Cu
#define DV1_PORT4_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM    2u
#define DV1_PORT4_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL  0x0u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_DPHY_DATA             0x4AD7280Cu
#define DV1_PORT5_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM    2u
#define DV1_PORT5_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL  0x0u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_DPHY_DATA             0x4AD7300Cu
#define DV1_PORT6_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM    2u
#define DV1_PORT6_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL  0x0u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_DPHY_DATA             0x4AD7380Cu
#define DV1_PORT7_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM    2u
#define DV1_PORT7_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL  0x0u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_DPHY_DATA             0x4AD7400Cu
#define DV1_PORT8_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM    2u
#define DV1_PORT8_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL  0x0u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_DPHY_DATA             0x4AD7480Cu
#define DV1_PORT9_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM    2u
#define DV1_PORT9_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL  0x0u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_DPHY_DATA            0x4AD7500Cu
#define DV1_PORT10_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM   2u
#define DV1_PORT10_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL 0x0u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_DPHY_DATA            0x4AD7580Cu
#define DV1_PORT11_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM   2u
#define DV1_PORT11_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL 0x0u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_DPHY_DATA            0x4AD7600Cu
#define DV1_PORT12_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM   2u
#define DV1_PORT12_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL 0x0u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_DPHY_DATA            0x4AD7680Cu
#define DV1_PORT13_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM   2u
#define DV1_PORT13_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL 0x0u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_DPHY_DATA            0x4AD7700Cu
#define DV1_PORT14_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM   2u
#define DV1_PORT14_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL 0x0u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_DPHY_DATA            0x4AD7780Cu
#define DV1_PORT15_INDIRECT_ACCESS_WTG_DPHY_DATA_FIELDNUM   2u
#define DV1_PORT15_INDIRECT_ACCESS_WTG_DPHY_DATA_DEFAULTVAL 0x0u
#define DV1_PORT0_WTG_CTRL_REG_0                            0x4AD70010u
#define DV1_PORT0_WTG_CTRL_REG_0_FIELDNUM                   8u
#define DV1_PORT0_WTG_CTRL_REG_0_DEFAULTVAL                 0xC07Fu
#define DV1_PORT1_WTG_CTRL_REG_0                            0x4AD70810u
#define DV1_PORT1_WTG_CTRL_REG_0_FIELDNUM                   8u
#define DV1_PORT1_WTG_CTRL_REG_0_DEFAULTVAL                 0xC07Fu
#define DV1_PORT2_WTG_CTRL_REG_0                            0x4AD71010u
#define DV1_PORT2_WTG_CTRL_REG_0_FIELDNUM                   8u
#define DV1_PORT2_WTG_CTRL_REG_0_DEFAULTVAL                 0xC07Fu
#define DV1_PORT3_WTG_CTRL_REG_0                            0x4AD71810u
#define DV1_PORT3_WTG_CTRL_REG_0_FIELDNUM                   8u
#define DV1_PORT3_WTG_CTRL_REG_0_DEFAULTVAL                 0xC07Fu
#define DV1_PORT4_WTG_CTRL_REG_0                            0x4AD72010u
#define DV1_PORT4_WTG_CTRL_REG_0_FIELDNUM                   8u
#define DV1_PORT4_WTG_CTRL_REG_0_DEFAULTVAL                 0xC07Fu
#define DV1_PORT5_WTG_CTRL_REG_0                            0x4AD72810u
#define DV1_PORT5_WTG_CTRL_REG_0_FIELDNUM                   8u
#define DV1_PORT5_WTG_CTRL_REG_0_DEFAULTVAL                 0xC07Fu
#define DV1_PORT6_WTG_CTRL_REG_0                            0x4AD73010u
#define DV1_PORT6_WTG_CTRL_REG_0_FIELDNUM                   8u
#define DV1_PORT6_WTG_CTRL_REG_0_DEFAULTVAL                 0xC07Fu
#define DV1_PORT7_WTG_CTRL_REG_0                            0x4AD73810u
#define DV1_PORT7_WTG_CTRL_REG_0_FIELDNUM                   8u
#define DV1_PORT7_WTG_CTRL_REG_0_DEFAULTVAL                 0xC07Fu
#define DV1_PORT8_WTG_CTRL_REG_0                            0x4AD74010u
#define DV1_PORT8_WTG_CTRL_REG_0_FIELDNUM                   8u
#define DV1_PORT8_WTG_CTRL_REG_0_DEFAULTVAL                 0xC07Fu
#define DV1_PORT9_WTG_CTRL_REG_0                            0x4AD74810u
#define DV1_PORT9_WTG_CTRL_REG_0_FIELDNUM                   8u
#define DV1_PORT9_WTG_CTRL_REG_0_DEFAULTVAL                 0xC07Fu
#define DV1_PORT10_WTG_CTRL_REG_0                           0x4AD75010u
#define DV1_PORT10_WTG_CTRL_REG_0_FIELDNUM                  8u
#define DV1_PORT10_WTG_CTRL_REG_0_DEFAULTVAL                0xC07Fu
#define DV1_PORT11_WTG_CTRL_REG_0                           0x4AD75810u
#define DV1_PORT11_WTG_CTRL_REG_0_FIELDNUM                  8u
#define DV1_PORT11_WTG_CTRL_REG_0_DEFAULTVAL                0xC07Fu
#define DV1_PORT12_WTG_CTRL_REG_0                           0x4AD76010u
#define DV1_PORT12_WTG_CTRL_REG_0_FIELDNUM                  8u
#define DV1_PORT12_WTG_CTRL_REG_0_DEFAULTVAL                0xC07Fu
#define DV1_PORT13_WTG_CTRL_REG_0                           0x4AD76810u
#define DV1_PORT13_WTG_CTRL_REG_0_FIELDNUM                  8u
#define DV1_PORT13_WTG_CTRL_REG_0_DEFAULTVAL                0xC07Fu
#define DV1_PORT14_WTG_CTRL_REG_0                           0x4AD77010u
#define DV1_PORT14_WTG_CTRL_REG_0_FIELDNUM                  8u
#define DV1_PORT14_WTG_CTRL_REG_0_DEFAULTVAL                0xC07Fu
#define DV1_PORT15_WTG_CTRL_REG_0                           0x4AD77810u
#define DV1_PORT15_WTG_CTRL_REG_0_FIELDNUM                  8u
#define DV1_PORT15_WTG_CTRL_REG_0_DEFAULTVAL                0xC07Fu
#define DV1_PORT0_WTG_CTRL_REG_1                            0x4AD70014u
#define DV1_PORT0_WTG_CTRL_REG_1_FIELDNUM                   2u
#define DV1_PORT0_WTG_CTRL_REG_1_DEFAULTVAL                 0x1002u
#define DV1_PORT1_WTG_CTRL_REG_1                            0x4AD70814u
#define DV1_PORT1_WTG_CTRL_REG_1_FIELDNUM                   2u
#define DV1_PORT1_WTG_CTRL_REG_1_DEFAULTVAL                 0x1002u
#define DV1_PORT2_WTG_CTRL_REG_1                            0x4AD71014u
#define DV1_PORT2_WTG_CTRL_REG_1_FIELDNUM                   2u
#define DV1_PORT2_WTG_CTRL_REG_1_DEFAULTVAL                 0x1002u
#define DV1_PORT3_WTG_CTRL_REG_1                            0x4AD71814u
#define DV1_PORT3_WTG_CTRL_REG_1_FIELDNUM                   2u
#define DV1_PORT3_WTG_CTRL_REG_1_DEFAULTVAL                 0x1002u
#define DV1_PORT4_WTG_CTRL_REG_1                            0x4AD72014u
#define DV1_PORT4_WTG_CTRL_REG_1_FIELDNUM                   2u
#define DV1_PORT4_WTG_CTRL_REG_1_DEFAULTVAL                 0x1002u
#define DV1_PORT5_WTG_CTRL_REG_1                            0x4AD72814u
#define DV1_PORT5_WTG_CTRL_REG_1_FIELDNUM                   2u
#define DV1_PORT5_WTG_CTRL_REG_1_DEFAULTVAL                 0x1002u
#define DV1_PORT6_WTG_CTRL_REG_1                            0x4AD73014u
#define DV1_PORT6_WTG_CTRL_REG_1_FIELDNUM                   2u
#define DV1_PORT6_WTG_CTRL_REG_1_DEFAULTVAL                 0x1002u
#define DV1_PORT7_WTG_CTRL_REG_1                            0x4AD73814u
#define DV1_PORT7_WTG_CTRL_REG_1_FIELDNUM                   2u
#define DV1_PORT7_WTG_CTRL_REG_1_DEFAULTVAL                 0x1002u
#define DV1_PORT8_WTG_CTRL_REG_1                            0x4AD74014u
#define DV1_PORT8_WTG_CTRL_REG_1_FIELDNUM                   2u
#define DV1_PORT8_WTG_CTRL_REG_1_DEFAULTVAL                 0x1002u
#define DV1_PORT9_WTG_CTRL_REG_1                            0x4AD74814u
#define DV1_PORT9_WTG_CTRL_REG_1_FIELDNUM                   2u
#define DV1_PORT9_WTG_CTRL_REG_1_DEFAULTVAL                 0x1002u
#define DV1_PORT10_WTG_CTRL_REG_1                           0x4AD75014u
#define DV1_PORT10_WTG_CTRL_REG_1_FIELDNUM                  2u
#define DV1_PORT10_WTG_CTRL_REG_1_DEFAULTVAL                0x1002u
#define DV1_PORT11_WTG_CTRL_REG_1                           0x4AD75814u
#define DV1_PORT11_WTG_CTRL_REG_1_FIELDNUM                  2u
#define DV1_PORT11_WTG_CTRL_REG_1_DEFAULTVAL                0x1002u
#define DV1_PORT12_WTG_CTRL_REG_1                           0x4AD76014u
#define DV1_PORT12_WTG_CTRL_REG_1_FIELDNUM                  2u
#define DV1_PORT12_WTG_CTRL_REG_1_DEFAULTVAL                0x1002u
#define DV1_PORT13_WTG_CTRL_REG_1                           0x4AD76814u
#define DV1_PORT13_WTG_CTRL_REG_1_FIELDNUM                  2u
#define DV1_PORT13_WTG_CTRL_REG_1_DEFAULTVAL                0x1002u
#define DV1_PORT14_WTG_CTRL_REG_1                           0x4AD77014u
#define DV1_PORT14_WTG_CTRL_REG_1_FIELDNUM                  2u
#define DV1_PORT14_WTG_CTRL_REG_1_DEFAULTVAL                0x1002u
#define DV1_PORT15_WTG_CTRL_REG_1                           0x4AD77814u
#define DV1_PORT15_WTG_CTRL_REG_1_FIELDNUM                  2u
#define DV1_PORT15_WTG_CTRL_REG_1_DEFAULTVAL                0x1002u
#define DV1_PORT0_WTG_STATUS_REG_0                          0x4AD70018u
#define DV1_PORT0_WTG_STATUS_REG_0_FIELDNUM                 6u
#define DV1_PORT0_WTG_STATUS_REG_0_DEFAULTVAL               0x0u
#define DV1_PORT1_WTG_STATUS_REG_0                          0x4AD70818u
#define DV1_PORT1_WTG_STATUS_REG_0_FIELDNUM                 6u
#define DV1_PORT1_WTG_STATUS_REG_0_DEFAULTVAL               0x0u
#define DV1_PORT2_WTG_STATUS_REG_0                          0x4AD71018u
#define DV1_PORT2_WTG_STATUS_REG_0_FIELDNUM                 6u
#define DV1_PORT2_WTG_STATUS_REG_0_DEFAULTVAL               0x0u
#define DV1_PORT3_WTG_STATUS_REG_0                          0x4AD71818u
#define DV1_PORT3_WTG_STATUS_REG_0_FIELDNUM                 6u
#define DV1_PORT3_WTG_STATUS_REG_0_DEFAULTVAL               0x0u
#define DV1_PORT4_WTG_STATUS_REG_0                          0x4AD72018u
#define DV1_PORT4_WTG_STATUS_REG_0_FIELDNUM                 6u
#define DV1_PORT4_WTG_STATUS_REG_0_DEFAULTVAL               0x0u
#define DV1_PORT5_WTG_STATUS_REG_0                          0x4AD72818u
#define DV1_PORT5_WTG_STATUS_REG_0_FIELDNUM                 6u
#define DV1_PORT5_WTG_STATUS_REG_0_DEFAULTVAL               0x0u
#define DV1_PORT6_WTG_STATUS_REG_0                          0x4AD73018u
#define DV1_PORT6_WTG_STATUS_REG_0_FIELDNUM                 6u
#define DV1_PORT6_WTG_STATUS_REG_0_DEFAULTVAL               0x0u
#define DV1_PORT7_WTG_STATUS_REG_0                          0x4AD73818u
#define DV1_PORT7_WTG_STATUS_REG_0_FIELDNUM                 6u
#define DV1_PORT7_WTG_STATUS_REG_0_DEFAULTVAL               0x0u
#define DV1_PORT8_WTG_STATUS_REG_0                          0x4AD74018u
#define DV1_PORT8_WTG_STATUS_REG_0_FIELDNUM                 6u
#define DV1_PORT8_WTG_STATUS_REG_0_DEFAULTVAL               0x0u
#define DV1_PORT9_WTG_STATUS_REG_0                          0x4AD74818u
#define DV1_PORT9_WTG_STATUS_REG_0_FIELDNUM                 6u
#define DV1_PORT9_WTG_STATUS_REG_0_DEFAULTVAL               0x0u
#define DV1_PORT10_WTG_STATUS_REG_0                         0x4AD75018u
#define DV1_PORT10_WTG_STATUS_REG_0_FIELDNUM                6u
#define DV1_PORT10_WTG_STATUS_REG_0_DEFAULTVAL              0x0u
#define DV1_PORT11_WTG_STATUS_REG_0                         0x4AD75818u
#define DV1_PORT11_WTG_STATUS_REG_0_FIELDNUM                6u
#define DV1_PORT11_WTG_STATUS_REG_0_DEFAULTVAL              0x0u
#define DV1_PORT12_WTG_STATUS_REG_0                         0x4AD76018u
#define DV1_PORT12_WTG_STATUS_REG_0_FIELDNUM                6u
#define DV1_PORT12_WTG_STATUS_REG_0_DEFAULTVAL              0x0u
#define DV1_PORT13_WTG_STATUS_REG_0                         0x4AD76818u
#define DV1_PORT13_WTG_STATUS_REG_0_FIELDNUM                6u
#define DV1_PORT13_WTG_STATUS_REG_0_DEFAULTVAL              0x0u
#define DV1_PORT14_WTG_STATUS_REG_0                         0x4AD77018u
#define DV1_PORT14_WTG_STATUS_REG_0_FIELDNUM                6u
#define DV1_PORT14_WTG_STATUS_REG_0_DEFAULTVAL              0x0u
#define DV1_PORT15_WTG_STATUS_REG_0                         0x4AD77818u
#define DV1_PORT15_WTG_STATUS_REG_0_FIELDNUM                6u
#define DV1_PORT15_WTG_STATUS_REG_0_DEFAULTVAL              0x0u
#define DV1_PORT0_PCS_CTRL_REG_0                            0x4AD7001Cu
#define DV1_PORT0_PCS_CTRL_REG_0_FIELDNUM                   15u
#define DV1_PORT0_PCS_CTRL_REG_0_DEFAULTVAL                 0x0u
#define DV1_PORT1_PCS_CTRL_REG_0                            0x4AD7081Cu
#define DV1_PORT1_PCS_CTRL_REG_0_FIELDNUM                   15u
#define DV1_PORT1_PCS_CTRL_REG_0_DEFAULTVAL                 0x0u
#define DV1_PORT2_PCS_CTRL_REG_0                            0x4AD7101Cu
#define DV1_PORT2_PCS_CTRL_REG_0_FIELDNUM                   15u
#define DV1_PORT2_PCS_CTRL_REG_0_DEFAULTVAL                 0x0u
#define DV1_PORT3_PCS_CTRL_REG_0                            0x4AD7181Cu
#define DV1_PORT3_PCS_CTRL_REG_0_FIELDNUM                   15u
#define DV1_PORT3_PCS_CTRL_REG_0_DEFAULTVAL                 0x0u
#define DV1_PORT4_PCS_CTRL_REG_0                            0x4AD7201Cu
#define DV1_PORT4_PCS_CTRL_REG_0_FIELDNUM                   15u
#define DV1_PORT4_PCS_CTRL_REG_0_DEFAULTVAL                 0x0u
#define DV1_PORT5_PCS_CTRL_REG_0                            0x4AD7281Cu
#define DV1_PORT5_PCS_CTRL_REG_0_FIELDNUM                   15u
#define DV1_PORT5_PCS_CTRL_REG_0_DEFAULTVAL                 0x0u
#define DV1_PORT6_PCS_CTRL_REG_0                            0x4AD7301Cu
#define DV1_PORT6_PCS_CTRL_REG_0_FIELDNUM                   15u
#define DV1_PORT6_PCS_CTRL_REG_0_DEFAULTVAL                 0x0u
#define DV1_PORT7_PCS_CTRL_REG_0                            0x4AD7381Cu
#define DV1_PORT7_PCS_CTRL_REG_0_FIELDNUM                   15u
#define DV1_PORT7_PCS_CTRL_REG_0_DEFAULTVAL                 0x0u
#define DV1_PORT8_PCS_CTRL_REG_0                            0x4AD7401Cu
#define DV1_PORT8_PCS_CTRL_REG_0_FIELDNUM                   15u
#define DV1_PORT8_PCS_CTRL_REG_0_DEFAULTVAL                 0x0u
#define DV1_PORT9_PCS_CTRL_REG_0                            0x4AD7481Cu
#define DV1_PORT9_PCS_CTRL_REG_0_FIELDNUM                   15u
#define DV1_PORT9_PCS_CTRL_REG_0_DEFAULTVAL                 0x0u
#define DV1_PORT10_PCS_CTRL_REG_0                           0x4AD7501Cu
#define DV1_PORT10_PCS_CTRL_REG_0_FIELDNUM                  15u
#define DV1_PORT10_PCS_CTRL_REG_0_DEFAULTVAL                0x0u
#define DV1_PORT11_PCS_CTRL_REG_0                           0x4AD7581Cu
#define DV1_PORT11_PCS_CTRL_REG_0_FIELDNUM                  15u
#define DV1_PORT11_PCS_CTRL_REG_0_DEFAULTVAL                0x0u
#define DV1_PORT12_PCS_CTRL_REG_0                           0x4AD7601Cu
#define DV1_PORT12_PCS_CTRL_REG_0_FIELDNUM                  15u
#define DV1_PORT12_PCS_CTRL_REG_0_DEFAULTVAL                0x0u
#define DV1_PORT13_PCS_CTRL_REG_0                           0x4AD7681Cu
#define DV1_PORT13_PCS_CTRL_REG_0_FIELDNUM                  15u
#define DV1_PORT13_PCS_CTRL_REG_0_DEFAULTVAL                0x0u
#define DV1_PORT14_PCS_CTRL_REG_0                           0x4AD7701Cu
#define DV1_PORT14_PCS_CTRL_REG_0_FIELDNUM                  15u
#define DV1_PORT14_PCS_CTRL_REG_0_DEFAULTVAL                0x0u
#define DV1_PORT15_PCS_CTRL_REG_0                           0x4AD7781Cu
#define DV1_PORT15_PCS_CTRL_REG_0_FIELDNUM                  15u
#define DV1_PORT15_PCS_CTRL_REG_0_DEFAULTVAL                0x0u
#define DV1_PORT0_PCS_CTRL_REG_1                            0x4AD70020u
#define DV1_PORT0_PCS_CTRL_REG_1_FIELDNUM                   3u
#define DV1_PORT0_PCS_CTRL_REG_1_DEFAULTVAL                 0x0u
#define DV1_PORT1_PCS_CTRL_REG_1                            0x4AD70820u
#define DV1_PORT1_PCS_CTRL_REG_1_FIELDNUM                   3u
#define DV1_PORT1_PCS_CTRL_REG_1_DEFAULTVAL                 0x0u
#define DV1_PORT2_PCS_CTRL_REG_1                            0x4AD71020u
#define DV1_PORT2_PCS_CTRL_REG_1_FIELDNUM                   3u
#define DV1_PORT2_PCS_CTRL_REG_1_DEFAULTVAL                 0x0u
#define DV1_PORT3_PCS_CTRL_REG_1                            0x4AD71820u
#define DV1_PORT3_PCS_CTRL_REG_1_FIELDNUM                   3u
#define DV1_PORT3_PCS_CTRL_REG_1_DEFAULTVAL                 0x0u
#define DV1_PORT4_PCS_CTRL_REG_1                            0x4AD72020u
#define DV1_PORT4_PCS_CTRL_REG_1_FIELDNUM                   3u
#define DV1_PORT4_PCS_CTRL_REG_1_DEFAULTVAL                 0x0u
#define DV1_PORT5_PCS_CTRL_REG_1                            0x4AD72820u
#define DV1_PORT5_PCS_CTRL_REG_1_FIELDNUM                   3u
#define DV1_PORT5_PCS_CTRL_REG_1_DEFAULTVAL                 0x0u
#define DV1_PORT6_PCS_CTRL_REG_1                            0x4AD73020u
#define DV1_PORT6_PCS_CTRL_REG_1_FIELDNUM                   3u
#define DV1_PORT6_PCS_CTRL_REG_1_DEFAULTVAL                 0x0u
#define DV1_PORT7_PCS_CTRL_REG_1                            0x4AD73820u
#define DV1_PORT7_PCS_CTRL_REG_1_FIELDNUM                   3u
#define DV1_PORT7_PCS_CTRL_REG_1_DEFAULTVAL                 0x0u
#define DV1_PORT8_PCS_CTRL_REG_1                            0x4AD74020u
#define DV1_PORT8_PCS_CTRL_REG_1_FIELDNUM                   3u
#define DV1_PORT8_PCS_CTRL_REG_1_DEFAULTVAL                 0x0u
#define DV1_PORT9_PCS_CTRL_REG_1                            0x4AD74820u
#define DV1_PORT9_PCS_CTRL_REG_1_FIELDNUM                   3u
#define DV1_PORT9_PCS_CTRL_REG_1_DEFAULTVAL                 0x0u
#define DV1_PORT10_PCS_CTRL_REG_1                           0x4AD75020u
#define DV1_PORT10_PCS_CTRL_REG_1_FIELDNUM                  3u
#define DV1_PORT10_PCS_CTRL_REG_1_DEFAULTVAL                0x0u
#define DV1_PORT11_PCS_CTRL_REG_1                           0x4AD75820u
#define DV1_PORT11_PCS_CTRL_REG_1_FIELDNUM                  3u
#define DV1_PORT11_PCS_CTRL_REG_1_DEFAULTVAL                0x0u
#define DV1_PORT12_PCS_CTRL_REG_1                           0x4AD76020u
#define DV1_PORT12_PCS_CTRL_REG_1_FIELDNUM                  3u
#define DV1_PORT12_PCS_CTRL_REG_1_DEFAULTVAL                0x0u
#define DV1_PORT13_PCS_CTRL_REG_1                           0x4AD76820u
#define DV1_PORT13_PCS_CTRL_REG_1_FIELDNUM                  3u
#define DV1_PORT13_PCS_CTRL_REG_1_DEFAULTVAL                0x0u
#define DV1_PORT14_PCS_CTRL_REG_1                           0x4AD77020u
#define DV1_PORT14_PCS_CTRL_REG_1_FIELDNUM                  3u
#define DV1_PORT14_PCS_CTRL_REG_1_DEFAULTVAL                0x0u
#define DV1_PORT15_PCS_CTRL_REG_1                           0x4AD77820u
#define DV1_PORT15_PCS_CTRL_REG_1_FIELDNUM                  3u
#define DV1_PORT15_PCS_CTRL_REG_1_DEFAULTVAL                0x0u
#define DV1_PORT0_PCS_CTRL_REG_2                            0x4AD70024u
#define DV1_PORT0_PCS_CTRL_REG_2_FIELDNUM                   3u
#define DV1_PORT0_PCS_CTRL_REG_2_DEFAULTVAL                 0x0u
#define DV1_PORT1_PCS_CTRL_REG_2                            0x4AD70824u
#define DV1_PORT1_PCS_CTRL_REG_2_FIELDNUM                   3u
#define DV1_PORT1_PCS_CTRL_REG_2_DEFAULTVAL                 0x0u
#define DV1_PORT2_PCS_CTRL_REG_2                            0x4AD71024u
#define DV1_PORT2_PCS_CTRL_REG_2_FIELDNUM                   3u
#define DV1_PORT2_PCS_CTRL_REG_2_DEFAULTVAL                 0x0u
#define DV1_PORT3_PCS_CTRL_REG_2                            0x4AD71824u
#define DV1_PORT3_PCS_CTRL_REG_2_FIELDNUM                   3u
#define DV1_PORT3_PCS_CTRL_REG_2_DEFAULTVAL                 0x0u
#define DV1_PORT4_PCS_CTRL_REG_2                            0x4AD72024u
#define DV1_PORT4_PCS_CTRL_REG_2_FIELDNUM                   3u
#define DV1_PORT4_PCS_CTRL_REG_2_DEFAULTVAL                 0x0u
#define DV1_PORT5_PCS_CTRL_REG_2                            0x4AD72824u
#define DV1_PORT5_PCS_CTRL_REG_2_FIELDNUM                   3u
#define DV1_PORT5_PCS_CTRL_REG_2_DEFAULTVAL                 0x0u
#define DV1_PORT6_PCS_CTRL_REG_2                            0x4AD73024u
#define DV1_PORT6_PCS_CTRL_REG_2_FIELDNUM                   3u
#define DV1_PORT6_PCS_CTRL_REG_2_DEFAULTVAL                 0x0u
#define DV1_PORT7_PCS_CTRL_REG_2                            0x4AD73824u
#define DV1_PORT7_PCS_CTRL_REG_2_FIELDNUM                   3u
#define DV1_PORT7_PCS_CTRL_REG_2_DEFAULTVAL                 0x0u
#define DV1_PORT8_PCS_CTRL_REG_2                            0x4AD74024u
#define DV1_PORT8_PCS_CTRL_REG_2_FIELDNUM                   3u
#define DV1_PORT8_PCS_CTRL_REG_2_DEFAULTVAL                 0x0u
#define DV1_PORT9_PCS_CTRL_REG_2                            0x4AD74824u
#define DV1_PORT9_PCS_CTRL_REG_2_FIELDNUM                   3u
#define DV1_PORT9_PCS_CTRL_REG_2_DEFAULTVAL                 0x0u
#define DV1_PORT10_PCS_CTRL_REG_2                           0x4AD75024u
#define DV1_PORT10_PCS_CTRL_REG_2_FIELDNUM                  3u
#define DV1_PORT10_PCS_CTRL_REG_2_DEFAULTVAL                0x0u
#define DV1_PORT11_PCS_CTRL_REG_2                           0x4AD75824u
#define DV1_PORT11_PCS_CTRL_REG_2_FIELDNUM                  3u
#define DV1_PORT11_PCS_CTRL_REG_2_DEFAULTVAL                0x0u
#define DV1_PORT12_PCS_CTRL_REG_2                           0x4AD76024u
#define DV1_PORT12_PCS_CTRL_REG_2_FIELDNUM                  3u
#define DV1_PORT12_PCS_CTRL_REG_2_DEFAULTVAL                0x0u
#define DV1_PORT13_PCS_CTRL_REG_2                           0x4AD76824u
#define DV1_PORT13_PCS_CTRL_REG_2_FIELDNUM                  3u
#define DV1_PORT13_PCS_CTRL_REG_2_DEFAULTVAL                0x0u
#define DV1_PORT14_PCS_CTRL_REG_2                           0x4AD77024u
#define DV1_PORT14_PCS_CTRL_REG_2_FIELDNUM                  3u
#define DV1_PORT14_PCS_CTRL_REG_2_DEFAULTVAL                0x0u
#define DV1_PORT15_PCS_CTRL_REG_2                           0x4AD77824u
#define DV1_PORT15_PCS_CTRL_REG_2_FIELDNUM                  3u
#define DV1_PORT15_PCS_CTRL_REG_2_DEFAULTVAL                0x0u
#define DV1_PORT0_PCS_CTRL_REG_3                            0x4AD70028u
#define DV1_PORT0_PCS_CTRL_REG_3_FIELDNUM                   12u
#define DV1_PORT0_PCS_CTRL_REG_3_DEFAULTVAL                 0x0u
#define DV1_PORT1_PCS_CTRL_REG_3                            0x4AD70828u
#define DV1_PORT1_PCS_CTRL_REG_3_FIELDNUM                   12u
#define DV1_PORT1_PCS_CTRL_REG_3_DEFAULTVAL                 0x0u
#define DV1_PORT2_PCS_CTRL_REG_3                            0x4AD71028u
#define DV1_PORT2_PCS_CTRL_REG_3_FIELDNUM                   12u
#define DV1_PORT2_PCS_CTRL_REG_3_DEFAULTVAL                 0x0u
#define DV1_PORT3_PCS_CTRL_REG_3                            0x4AD71828u
#define DV1_PORT3_PCS_CTRL_REG_3_FIELDNUM                   12u
#define DV1_PORT3_PCS_CTRL_REG_3_DEFAULTVAL                 0x0u
#define DV1_PORT4_PCS_CTRL_REG_3                            0x4AD72028u
#define DV1_PORT4_PCS_CTRL_REG_3_FIELDNUM                   12u
#define DV1_PORT4_PCS_CTRL_REG_3_DEFAULTVAL                 0x0u
#define DV1_PORT5_PCS_CTRL_REG_3                            0x4AD72828u
#define DV1_PORT5_PCS_CTRL_REG_3_FIELDNUM                   12u
#define DV1_PORT5_PCS_CTRL_REG_3_DEFAULTVAL                 0x0u
#define DV1_PORT6_PCS_CTRL_REG_3                            0x4AD73028u
#define DV1_PORT6_PCS_CTRL_REG_3_FIELDNUM                   12u
#define DV1_PORT6_PCS_CTRL_REG_3_DEFAULTVAL                 0x0u
#define DV1_PORT7_PCS_CTRL_REG_3                            0x4AD73828u
#define DV1_PORT7_PCS_CTRL_REG_3_FIELDNUM                   12u
#define DV1_PORT7_PCS_CTRL_REG_3_DEFAULTVAL                 0x0u
#define DV1_PORT8_PCS_CTRL_REG_3                            0x4AD74028u
#define DV1_PORT8_PCS_CTRL_REG_3_FIELDNUM                   12u
#define DV1_PORT8_PCS_CTRL_REG_3_DEFAULTVAL                 0x0u
#define DV1_PORT9_PCS_CTRL_REG_3                            0x4AD74828u
#define DV1_PORT9_PCS_CTRL_REG_3_FIELDNUM                   12u
#define DV1_PORT9_PCS_CTRL_REG_3_DEFAULTVAL                 0x0u
#define DV1_PORT10_PCS_CTRL_REG_3                           0x4AD75028u
#define DV1_PORT10_PCS_CTRL_REG_3_FIELDNUM                  12u
#define DV1_PORT10_PCS_CTRL_REG_3_DEFAULTVAL                0x0u
#define DV1_PORT11_PCS_CTRL_REG_3                           0x4AD75828u
#define DV1_PORT11_PCS_CTRL_REG_3_FIELDNUM                  12u
#define DV1_PORT11_PCS_CTRL_REG_3_DEFAULTVAL                0x0u
#define DV1_PORT12_PCS_CTRL_REG_3                           0x4AD76028u
#define DV1_PORT12_PCS_CTRL_REG_3_FIELDNUM                  12u
#define DV1_PORT12_PCS_CTRL_REG_3_DEFAULTVAL                0x0u
#define DV1_PORT13_PCS_CTRL_REG_3                           0x4AD76828u
#define DV1_PORT13_PCS_CTRL_REG_3_FIELDNUM                  12u
#define DV1_PORT13_PCS_CTRL_REG_3_DEFAULTVAL                0x0u
#define DV1_PORT14_PCS_CTRL_REG_3                           0x4AD77028u
#define DV1_PORT14_PCS_CTRL_REG_3_FIELDNUM                  12u
#define DV1_PORT14_PCS_CTRL_REG_3_DEFAULTVAL                0x0u
#define DV1_PORT15_PCS_CTRL_REG_3                           0x4AD77828u
#define DV1_PORT15_PCS_CTRL_REG_3_FIELDNUM                  12u
#define DV1_PORT15_PCS_CTRL_REG_3_DEFAULTVAL                0x0u
#endif
#endif /* DV1_RTKAS_REG_LIST_FILE_SERDES_WTG_TOP_T1_H_ */