/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_LIST_FILE_VLAN_DECISION_H_
#define DV1_RTKAS_REG_LIST_FILE_VLAN_DECISION_H_

#ifdef DV1_FILE_VLAN_DECISION
/* File: DV1_VLAN Decision */
#define DV1_PORT0_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC90000u
#define DV1_PORT0_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DV1_PORT0_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DV1_PORT1_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC90800u
#define DV1_PORT1_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DV1_PORT1_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DV1_PORT2_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC91000u
#define DV1_PORT2_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DV1_PORT2_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DV1_PORT3_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC91800u
#define DV1_PORT3_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DV1_PORT3_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DV1_PORT4_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC92000u
#define DV1_PORT4_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DV1_PORT4_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DV1_PORT5_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC92800u
#define DV1_PORT5_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DV1_PORT5_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DV1_PORT6_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC93000u
#define DV1_PORT6_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DV1_PORT6_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DV1_PORT7_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC93800u
#define DV1_PORT7_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DV1_PORT7_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DV1_PORT8_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC94000u
#define DV1_PORT8_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DV1_PORT8_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DV1_PORT9_ACCEPT_FRAME_TYPE_CONTROL                     0x4AC94800u
#define DV1_PORT9_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM            6u
#define DV1_PORT9_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL          0x1Fu
#define DV1_PORT10_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC95000u
#define DV1_PORT10_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DV1_PORT10_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DV1_PORT11_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC95800u
#define DV1_PORT11_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DV1_PORT11_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DV1_PORT12_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC96000u
#define DV1_PORT12_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DV1_PORT12_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DV1_PORT13_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC96800u
#define DV1_PORT13_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DV1_PORT13_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DV1_PORT14_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC97000u
#define DV1_PORT14_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DV1_PORT14_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DV1_PORT15_ACCEPT_FRAME_TYPE_CONTROL                    0x4AC97800u
#define DV1_PORT15_ACCEPT_FRAME_TYPE_CONTROL_FIELDNUM           6u
#define DV1_PORT15_ACCEPT_FRAME_TYPE_CONTROL_DEFAULTVAL         0x1Fu
#define DV1_PORT0_IGNORE_VLAN_TAG_CONTROL                       0x4AC90004u
#define DV1_PORT0_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DV1_PORT0_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DV1_PORT1_IGNORE_VLAN_TAG_CONTROL                       0x4AC90804u
#define DV1_PORT1_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DV1_PORT1_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DV1_PORT2_IGNORE_VLAN_TAG_CONTROL                       0x4AC91004u
#define DV1_PORT2_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DV1_PORT2_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DV1_PORT3_IGNORE_VLAN_TAG_CONTROL                       0x4AC91804u
#define DV1_PORT3_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DV1_PORT3_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DV1_PORT4_IGNORE_VLAN_TAG_CONTROL                       0x4AC92004u
#define DV1_PORT4_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DV1_PORT4_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DV1_PORT5_IGNORE_VLAN_TAG_CONTROL                       0x4AC92804u
#define DV1_PORT5_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DV1_PORT5_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DV1_PORT6_IGNORE_VLAN_TAG_CONTROL                       0x4AC93004u
#define DV1_PORT6_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DV1_PORT6_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DV1_PORT7_IGNORE_VLAN_TAG_CONTROL                       0x4AC93804u
#define DV1_PORT7_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DV1_PORT7_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DV1_PORT8_IGNORE_VLAN_TAG_CONTROL                       0x4AC94004u
#define DV1_PORT8_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DV1_PORT8_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DV1_PORT9_IGNORE_VLAN_TAG_CONTROL                       0x4AC94804u
#define DV1_PORT9_IGNORE_VLAN_TAG_CONTROL_FIELDNUM              5u
#define DV1_PORT9_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL            0x0u
#define DV1_PORT10_IGNORE_VLAN_TAG_CONTROL                      0x4AC95004u
#define DV1_PORT10_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DV1_PORT10_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DV1_PORT11_IGNORE_VLAN_TAG_CONTROL                      0x4AC95804u
#define DV1_PORT11_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DV1_PORT11_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DV1_PORT12_IGNORE_VLAN_TAG_CONTROL                      0x4AC96004u
#define DV1_PORT12_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DV1_PORT12_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DV1_PORT13_IGNORE_VLAN_TAG_CONTROL                      0x4AC96804u
#define DV1_PORT13_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DV1_PORT13_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DV1_PORT14_IGNORE_VLAN_TAG_CONTROL                      0x4AC97004u
#define DV1_PORT14_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DV1_PORT14_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DV1_PORT15_IGNORE_VLAN_TAG_CONTROL                      0x4AC97804u
#define DV1_PORT15_IGNORE_VLAN_TAG_CONTROL_FIELDNUM             5u
#define DV1_PORT15_IGNORE_VLAN_TAG_CONTROL_DEFAULTVAL           0x0u
#define DV1_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC90008u
#define DV1_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DV1_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DV1_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC90808u
#define DV1_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DV1_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DV1_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC91008u
#define DV1_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DV1_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DV1_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC91808u
#define DV1_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DV1_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DV1_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC92008u
#define DV1_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DV1_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DV1_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC92808u
#define DV1_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DV1_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DV1_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC93008u
#define DV1_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DV1_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DV1_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC93808u
#define DV1_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DV1_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DV1_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC94008u
#define DV1_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DV1_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DV1_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL             0x4AC94808u
#define DV1_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM    3u
#define DV1_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL  0x0u
#define DV1_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC95008u
#define DV1_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DV1_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DV1_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC95808u
#define DV1_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DV1_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DV1_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC96008u
#define DV1_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DV1_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DV1_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC96808u
#define DV1_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DV1_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DV1_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC97008u
#define DV1_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DV1_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#define DV1_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL            0x4AC97808u
#define DV1_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL_FIELDNUM   3u
#define DV1_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL_DEFAULTVAL 0x0u
#endif
#endif /* DV1_RTKAS_REG_LIST_FILE_VLAN_DECISION_H_ */