/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_LIST_FILE_L2_ENTRY_NUM_CONSTRAIN_H_
#define DV1_RTKAS_REG_LIST_FILE_L2_ENTRY_NUM_CONSTRAIN_H_

#ifdef DV1_FILE_L2_ENTRY_NUM_CONSTRAIN
/* File: L2 Entry Number Constrain */
#define DV1_MAC_ADDRESS_NUMBER_CONSTRAIN_CONTROL             0x4A750000u
#define DV1_MAC_ADDRESS_NUMBER_CONSTRAIN_CONTROL_FIELDNUM    2u
#define DV1_MAC_ADDRESS_NUMBER_CONSTRAIN_CONTROL_DEFAULTVAL  0x8000u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD0_0              0x4A750004u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD0_0_FIELDNUM     1u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD0_0_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD0_1              0x4A750008u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD0_1_FIELDNUM     5u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD0_1_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD1_0              0x4A75000Cu
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD1_0_FIELDNUM     1u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD1_0_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD1_1              0x4A750010u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD1_1_FIELDNUM     5u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD1_1_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD2_0              0x4A750014u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD2_0_FIELDNUM     1u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD2_0_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD2_1              0x4A750018u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD2_1_FIELDNUM     5u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD2_1_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD3_0              0x4A75001Cu
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD3_0_FIELDNUM     1u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD3_0_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD3_1              0x4A750020u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD3_1_FIELDNUM     4u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD3_1_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD4_0              0x4A750024u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD4_0_FIELDNUM     1u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD4_0_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD4_1              0x4A750028u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD4_1_FIELDNUM     4u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD4_1_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD5_0              0x4A75002Cu
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD5_0_FIELDNUM     1u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD5_0_DEFAULTVAL   0x0u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD5_1              0x4A750030u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD5_1_FIELDNUM     4u
#define DV1_LEGAL_SOURCE_ADDRESS_MOVE_RECORD5_1_DEFAULTVAL   0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD0_0            0x4A750034u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD0_0_FIELDNUM   1u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD0_0_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD0_1            0x4A750038u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD0_1_FIELDNUM   5u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD0_1_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD1_0            0x4A75003Cu
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD1_0_FIELDNUM   1u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD1_0_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD1_1            0x4A750040u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD1_1_FIELDNUM   5u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD1_1_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD2_0            0x4A750044u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD2_0_FIELDNUM   1u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD2_0_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD2_1            0x4A750048u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD2_1_FIELDNUM   5u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD2_1_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD3_0            0x4A75004Cu
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD3_0_FIELDNUM   1u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD3_0_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD3_1            0x4A750050u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD3_1_FIELDNUM   4u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD3_1_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD4_0            0x4A750054u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD4_0_FIELDNUM   1u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD4_0_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD4_1            0x4A750058u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD4_1_FIELDNUM   4u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD4_1_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD5_0            0x4A75005Cu
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD5_0_FIELDNUM   1u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD5_0_DEFAULTVAL 0x0u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD5_1            0x4A750060u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD5_1_FIELDNUM   4u
#define DV1_ILLEGAL_SOURCE_ADDRESS_MOVE_RECORD5_1_DEFAULTVAL 0x0u
#define DV1_LUT_VALID_SA_MASK_BIT                            0x4A750064u
#define DV1_LUT_VALID_SA_MASK_BIT_FIELDNUM                   2u
#define DV1_LUT_VALID_SA_MASK_BIT_DEFAULTVAL                 0xFFFFu
#define DV1_LUT_VALID_SA_MASK_BIT_CONTROL0                   0x4A750068u
#define DV1_LUT_VALID_SA_MASK_BIT_CONTROL0_FIELDNUM          2u
#define DV1_LUT_VALID_SA_MASK_BIT_CONTROL0_DEFAULTVAL        0xFFFFu
#define DV1_LUT_VALID_SA_MASK_BIT_CONTROL1                   0x4A75006Cu
#define DV1_LUT_VALID_SA_MASK_BIT_CONTROL1_FIELDNUM          2u
#define DV1_LUT_VALID_SA_MASK_BIT_CONTROL1_DEFAULTVAL        0xFFFFu
#define DV1_INVALID_SA_TRAP_CPU_CONTROL                      0x4A750070u
#define DV1_INVALID_SA_TRAP_CPU_CONTROL_FIELDNUM             2u
#define DV1_INVALID_SA_TRAP_CPU_CONTROL_DEFAULTVAL           0x7FFFu
#define DV1_INVALID_SA_TRAP_CPU_MASK                         0x4A750074u
#define DV1_INVALID_SA_TRAP_CPU_MASK_FIELDNUM                2u
#define DV1_INVALID_SA_TRAP_CPU_MASK_DEFAULTVAL              0x8000u
#define DV1_PORT0_SOURCE_MAC_MOVE_CONTROL                    0x4AF50000u
#define DV1_PORT0_SOURCE_MAC_MOVE_CONTROL_FIELDNUM           5u
#define DV1_PORT0_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL         0x0u
#define DV1_PORT1_SOURCE_MAC_MOVE_CONTROL                    0x4AF50800u
#define DV1_PORT1_SOURCE_MAC_MOVE_CONTROL_FIELDNUM           5u
#define DV1_PORT1_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL         0x0u
#define DV1_PORT2_SOURCE_MAC_MOVE_CONTROL                    0x4AF51000u
#define DV1_PORT2_SOURCE_MAC_MOVE_CONTROL_FIELDNUM           5u
#define DV1_PORT2_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL         0x0u
#define DV1_PORT3_SOURCE_MAC_MOVE_CONTROL                    0x4AF51800u
#define DV1_PORT3_SOURCE_MAC_MOVE_CONTROL_FIELDNUM           5u
#define DV1_PORT3_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL         0x0u
#define DV1_PORT4_SOURCE_MAC_MOVE_CONTROL                    0x4AF52000u
#define DV1_PORT4_SOURCE_MAC_MOVE_CONTROL_FIELDNUM           5u
#define DV1_PORT4_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL         0x0u
#define DV1_PORT5_SOURCE_MAC_MOVE_CONTROL                    0x4AF52800u
#define DV1_PORT5_SOURCE_MAC_MOVE_CONTROL_FIELDNUM           5u
#define DV1_PORT5_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL         0x0u
#define DV1_PORT6_SOURCE_MAC_MOVE_CONTROL                    0x4AF53000u
#define DV1_PORT6_SOURCE_MAC_MOVE_CONTROL_FIELDNUM           5u
#define DV1_PORT6_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL         0x0u
#define DV1_PORT7_SOURCE_MAC_MOVE_CONTROL                    0x4AF53800u
#define DV1_PORT7_SOURCE_MAC_MOVE_CONTROL_FIELDNUM           5u
#define DV1_PORT7_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL         0x0u
#define DV1_PORT8_SOURCE_MAC_MOVE_CONTROL                    0x4AF54000u
#define DV1_PORT8_SOURCE_MAC_MOVE_CONTROL_FIELDNUM           5u
#define DV1_PORT8_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL         0x0u
#define DV1_PORT9_SOURCE_MAC_MOVE_CONTROL                    0x4AF54800u
#define DV1_PORT9_SOURCE_MAC_MOVE_CONTROL_FIELDNUM           5u
#define DV1_PORT9_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL         0x0u
#define DV1_PORT10_SOURCE_MAC_MOVE_CONTROL                   0x4AF55000u
#define DV1_PORT10_SOURCE_MAC_MOVE_CONTROL_FIELDNUM          5u
#define DV1_PORT10_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL        0x0u
#define DV1_PORT11_SOURCE_MAC_MOVE_CONTROL                   0x4AF55800u
#define DV1_PORT11_SOURCE_MAC_MOVE_CONTROL_FIELDNUM          5u
#define DV1_PORT11_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL        0x0u
#define DV1_PORT12_SOURCE_MAC_MOVE_CONTROL                   0x4AF56000u
#define DV1_PORT12_SOURCE_MAC_MOVE_CONTROL_FIELDNUM          5u
#define DV1_PORT12_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL        0x0u
#define DV1_PORT13_SOURCE_MAC_MOVE_CONTROL                   0x4AF56800u
#define DV1_PORT13_SOURCE_MAC_MOVE_CONTROL_FIELDNUM          5u
#define DV1_PORT13_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL        0x0u
#define DV1_PORT14_SOURCE_MAC_MOVE_CONTROL                   0x4AF57000u
#define DV1_PORT14_SOURCE_MAC_MOVE_CONTROL_FIELDNUM          5u
#define DV1_PORT14_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL        0x0u
#define DV1_PORT15_SOURCE_MAC_MOVE_CONTROL                   0x4AF57800u
#define DV1_PORT15_SOURCE_MAC_MOVE_CONTROL_FIELDNUM          5u
#define DV1_PORT15_SOURCE_MAC_MOVE_CONTROL_DEFAULTVAL        0x0u
#define DV1_PORT0_SOURCE_MAC_MOVE_PORTMASK                   0x4AF50004u
#define DV1_PORT0_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM          2u
#define DV1_PORT0_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL        0xFFFFu
#define DV1_PORT1_SOURCE_MAC_MOVE_PORTMASK                   0x4AF50804u
#define DV1_PORT1_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM          2u
#define DV1_PORT1_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL        0xFFFFu
#define DV1_PORT2_SOURCE_MAC_MOVE_PORTMASK                   0x4AF51004u
#define DV1_PORT2_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM          2u
#define DV1_PORT2_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL        0xFFFFu
#define DV1_PORT3_SOURCE_MAC_MOVE_PORTMASK                   0x4AF51804u
#define DV1_PORT3_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM          2u
#define DV1_PORT3_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL        0xFFFFu
#define DV1_PORT4_SOURCE_MAC_MOVE_PORTMASK                   0x4AF52004u
#define DV1_PORT4_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM          2u
#define DV1_PORT4_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL        0xFFFFu
#define DV1_PORT5_SOURCE_MAC_MOVE_PORTMASK                   0x4AF52804u
#define DV1_PORT5_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM          2u
#define DV1_PORT5_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL        0xFFFFu
#define DV1_PORT6_SOURCE_MAC_MOVE_PORTMASK                   0x4AF53004u
#define DV1_PORT6_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM          2u
#define DV1_PORT6_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL        0xFFFFu
#define DV1_PORT7_SOURCE_MAC_MOVE_PORTMASK                   0x4AF53804u
#define DV1_PORT7_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM          2u
#define DV1_PORT7_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL        0xFFFFu
#define DV1_PORT8_SOURCE_MAC_MOVE_PORTMASK                   0x4AF54004u
#define DV1_PORT8_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM          2u
#define DV1_PORT8_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL        0xFFFFu
#define DV1_PORT9_SOURCE_MAC_MOVE_PORTMASK                   0x4AF54804u
#define DV1_PORT9_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM          2u
#define DV1_PORT9_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL        0xFFFFu
#define DV1_PORT10_SOURCE_MAC_MOVE_PORTMASK                  0x4AF55004u
#define DV1_PORT10_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM         2u
#define DV1_PORT10_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL       0xFFFFu
#define DV1_PORT11_SOURCE_MAC_MOVE_PORTMASK                  0x4AF55804u
#define DV1_PORT11_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM         2u
#define DV1_PORT11_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL       0xFFFFu
#define DV1_PORT12_SOURCE_MAC_MOVE_PORTMASK                  0x4AF56004u
#define DV1_PORT12_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM         2u
#define DV1_PORT12_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL       0xFFFFu
#define DV1_PORT13_SOURCE_MAC_MOVE_PORTMASK                  0x4AF56804u
#define DV1_PORT13_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM         2u
#define DV1_PORT13_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL       0xFFFFu
#define DV1_PORT14_SOURCE_MAC_MOVE_PORTMASK                  0x4AF57004u
#define DV1_PORT14_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM         2u
#define DV1_PORT14_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL       0xFFFFu
#define DV1_PORT15_SOURCE_MAC_MOVE_PORTMASK                  0x4AF57804u
#define DV1_PORT15_SOURCE_MAC_MOVE_PORTMASK_FIELDNUM         2u
#define DV1_PORT15_SOURCE_MAC_MOVE_PORTMASK_DEFAULTVAL       0xFFFFu
#define DV1_PORT0_MAC_LIMIT_CONTROL                          0x4AF50008u
#define DV1_PORT0_MAC_LIMIT_CONTROL_FIELDNUM                 5u
#define DV1_PORT0_MAC_LIMIT_CONTROL_DEFAULTVAL               0x0u
#define DV1_PORT1_MAC_LIMIT_CONTROL                          0x4AF50808u
#define DV1_PORT1_MAC_LIMIT_CONTROL_FIELDNUM                 5u
#define DV1_PORT1_MAC_LIMIT_CONTROL_DEFAULTVAL               0x0u
#define DV1_PORT2_MAC_LIMIT_CONTROL                          0x4AF51008u
#define DV1_PORT2_MAC_LIMIT_CONTROL_FIELDNUM                 5u
#define DV1_PORT2_MAC_LIMIT_CONTROL_DEFAULTVAL               0x0u
#define DV1_PORT3_MAC_LIMIT_CONTROL                          0x4AF51808u
#define DV1_PORT3_MAC_LIMIT_CONTROL_FIELDNUM                 5u
#define DV1_PORT3_MAC_LIMIT_CONTROL_DEFAULTVAL               0x0u
#define DV1_PORT4_MAC_LIMIT_CONTROL                          0x4AF52008u
#define DV1_PORT4_MAC_LIMIT_CONTROL_FIELDNUM                 5u
#define DV1_PORT4_MAC_LIMIT_CONTROL_DEFAULTVAL               0x0u
#define DV1_PORT5_MAC_LIMIT_CONTROL                          0x4AF52808u
#define DV1_PORT5_MAC_LIMIT_CONTROL_FIELDNUM                 5u
#define DV1_PORT5_MAC_LIMIT_CONTROL_DEFAULTVAL               0x0u
#define DV1_PORT6_MAC_LIMIT_CONTROL                          0x4AF53008u
#define DV1_PORT6_MAC_LIMIT_CONTROL_FIELDNUM                 5u
#define DV1_PORT6_MAC_LIMIT_CONTROL_DEFAULTVAL               0x0u
#define DV1_PORT7_MAC_LIMIT_CONTROL                          0x4AF53808u
#define DV1_PORT7_MAC_LIMIT_CONTROL_FIELDNUM                 5u
#define DV1_PORT7_MAC_LIMIT_CONTROL_DEFAULTVAL               0x0u
#define DV1_PORT8_MAC_LIMIT_CONTROL                          0x4AF54008u
#define DV1_PORT8_MAC_LIMIT_CONTROL_FIELDNUM                 5u
#define DV1_PORT8_MAC_LIMIT_CONTROL_DEFAULTVAL               0x0u
#define DV1_PORT9_MAC_LIMIT_CONTROL                          0x4AF54808u
#define DV1_PORT9_MAC_LIMIT_CONTROL_FIELDNUM                 5u
#define DV1_PORT9_MAC_LIMIT_CONTROL_DEFAULTVAL               0x0u
#define DV1_PORT10_MAC_LIMIT_CONTROL                         0x4AF55008u
#define DV1_PORT10_MAC_LIMIT_CONTROL_FIELDNUM                5u
#define DV1_PORT10_MAC_LIMIT_CONTROL_DEFAULTVAL              0x0u
#define DV1_PORT11_MAC_LIMIT_CONTROL                         0x4AF55808u
#define DV1_PORT11_MAC_LIMIT_CONTROL_FIELDNUM                5u
#define DV1_PORT11_MAC_LIMIT_CONTROL_DEFAULTVAL              0x0u
#define DV1_PORT12_MAC_LIMIT_CONTROL                         0x4AF56008u
#define DV1_PORT12_MAC_LIMIT_CONTROL_FIELDNUM                5u
#define DV1_PORT12_MAC_LIMIT_CONTROL_DEFAULTVAL              0x0u
#define DV1_PORT13_MAC_LIMIT_CONTROL                         0x4AF56808u
#define DV1_PORT13_MAC_LIMIT_CONTROL_FIELDNUM                5u
#define DV1_PORT13_MAC_LIMIT_CONTROL_DEFAULTVAL              0x0u
#define DV1_PORT14_MAC_LIMIT_CONTROL                         0x4AF57008u
#define DV1_PORT14_MAC_LIMIT_CONTROL_FIELDNUM                5u
#define DV1_PORT14_MAC_LIMIT_CONTROL_DEFAULTVAL              0x0u
#define DV1_PORT15_MAC_LIMIT_CONTROL                         0x4AF57808u
#define DV1_PORT15_MAC_LIMIT_CONTROL_FIELDNUM                5u
#define DV1_PORT15_MAC_LIMIT_CONTROL_DEFAULTVAL              0x0u
#endif
#endif /* DV1_RTKAS_REG_LIST_FILE_L2_ENTRY_NUM_CONSTRAIN_H_ */