/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_LIST_FILE_CPU_DOMAIN_H_
#define DV1_RTKAS_REG_LIST_FILE_CPU_DOMAIN_H_

#ifdef DV1_FILE_CPU_DOMAIN
/* File: CPU Domain */
#define DV1_INTERNAL_CPU_RESET                                   0x42010000u
#define DV1_INTERNAL_CPU_RESET_FIELDNUM                          5u
#define DV1_INTERNAL_CPU_RESET_DEFAULTVAL                        0x8u
#define DV1_CPU_BOOT                                             0x42010004u
#define DV1_CPU_BOOT_FIELDNUM                                    3u
#define DV1_CPU_BOOT_DEFAULTVAL                                  0x0u
#define DV1_INTERNAL_CPU_TRACE_PORT_0                            0x42010008u
#define DV1_INTERNAL_CPU_TRACE_PORT_0_FIELDNUM                   1u
#define DV1_INTERNAL_CPU_TRACE_PORT_0_DEFAULTVAL                 0x0u
#define DV1_INTERNAL_CPU_TRACE_PORT_1                            0x4201000Cu
#define DV1_INTERNAL_CPU_TRACE_PORT_1_FIELDNUM                   2u
#define DV1_INTERNAL_CPU_TRACE_PORT_1_DEFAULTVAL                 0x0u
#define DV1_INTERNAL_CPU_TRACE_PORT_2                            0x42010010u
#define DV1_INTERNAL_CPU_TRACE_PORT_2_FIELDNUM                   1u
#define DV1_INTERNAL_CPU_TRACE_PORT_2_DEFAULTVAL                 0x0u
#define DV1_INTERNAL_CPU_TRACE_PORT_3                            0x42010014u
#define DV1_INTERNAL_CPU_TRACE_PORT_3_FIELDNUM                   2u
#define DV1_INTERNAL_CPU_TRACE_PORT_3_DEFAULTVAL                 0x0u
#define DV1_INTERNAL_CPU_TRACE_PORT_4                            0x42010018u
#define DV1_INTERNAL_CPU_TRACE_PORT_4_FIELDNUM                   1u
#define DV1_INTERNAL_CPU_TRACE_PORT_4_DEFAULTVAL                 0x0u
#define DV1_SPIC_STATUS_DEBUG                                    0x4201001Cu
#define DV1_SPIC_STATUS_DEBUG_FIELDNUM                           7u
#define DV1_SPIC_STATUS_DEBUG_DEFAULTVAL                         0x0u
#define DV1_SPIC_FIFO_TX_DEBUG                                   0x42010020u
#define DV1_SPIC_FIFO_TX_DEBUG_FIELDNUM                          8u
#define DV1_SPIC_FIFO_TX_DEBUG_DEFAULTVAL                        0x0u
#define DV1_PLATFORM_INFO                                        0x42010024u
#define DV1_PLATFORM_INFO_FIELDNUM                               2u
#define DV1_PLATFORM_INFO_DEFAULTVAL                             0x0u
#define DV1_CPU_DOMAIN_RSV_0                                     0x42010028u
#define DV1_CPU_DOMAIN_RSV_0_FIELDNUM                            1u
#define DV1_CPU_DOMAIN_RSV_0_DEFAULTVAL                          0x0u
#define DV1_FAST_INTERRUPT_POL                                   0x4201002Cu
#define DV1_FAST_INTERRUPT_POL_FIELDNUM                          2u
#define DV1_FAST_INTERRUPT_POL_DEFAULTVAL                        0x0u
#define DV1_SPIC_DELAYCHAIN_SELECT                               0x42010030u
#define DV1_SPIC_DELAYCHAIN_SELECT_FIELDNUM                      6u
#define DV1_SPIC_DELAYCHAIN_SELECT_DEFAULTVAL                    0x0u
#define DV1_CR5_ECC_PRE_WRITE_STATUS0                            0x42010034u
#define DV1_CR5_ECC_PRE_WRITE_STATUS0_FIELDNUM                   17u
#define DV1_CR5_ECC_PRE_WRITE_STATUS0_DEFAULTVAL                 0x0u
#define DV1_CR5_ECC_PRE_WRITE_ALL_STATUS1                        0x42010038u
#define DV1_CR5_ECC_PRE_WRITE_ALL_STATUS1_FIELDNUM               18u
#define DV1_CR5_ECC_PRE_WRITE_ALL_STATUS1_DEFAULTVAL             0x0u
#define DV1_CR5_ECC0                                             0x4201003Cu
#define DV1_CR5_ECC0_FIELDNUM                                    1u
#define DV1_CR5_ECC0_DEFAULTVAL                                  0x0u
#define DV1_CR5_ECC1                                             0x42010040u
#define DV1_CR5_ECC1_FIELDNUM                                    1u
#define DV1_CR5_ECC1_DEFAULTVAL                                  0x0u
#define DV1_CR5_SRAM_MODE0                                       0x42010044u
#define DV1_CR5_SRAM_MODE0_FIELDNUM                              2u
#define DV1_CR5_SRAM_MODE0_DEFAULTVAL                            0x15u
#define DV1_CR5_SRAM_MODE1                                       0x42010048u
#define DV1_CR5_SRAM_MODE1_FIELDNUM                              2u
#define DV1_CR5_SRAM_MODE1_DEFAULTVAL                            0x0u
#define DV1_CR5_SRAM_MODE2                                       0x4201004Cu
#define DV1_CR5_SRAM_MODE2_FIELDNUM                              2u
#define DV1_CR5_SRAM_MODE2_DEFAULTVAL                            0x0u
#define DV1_CR5_SRAM_MODE3                                       0x42010050u
#define DV1_CR5_SRAM_MODE3_FIELDNUM                              2u
#define DV1_CR5_SRAM_MODE3_DEFAULTVAL                            0x0u
#define DV1_CR5_SRAM_MODE4                                       0x42010054u
#define DV1_CR5_SRAM_MODE4_FIELDNUM                              2u
#define DV1_CR5_SRAM_MODE4_DEFAULTVAL                            0x0u
#define DV1_CR5_SRAM_MODE5                                       0x42010058u
#define DV1_CR5_SRAM_MODE5_FIELDNUM                              2u
#define DV1_CR5_SRAM_MODE5_DEFAULTVAL                            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CPU_0                      0x4201005Cu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CPU_0_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CPU_0_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CPU_1                      0x42010060u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CPU_1_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CPU_1_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_0                      0x42010064u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_0_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_0_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_1                      0x42010068u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_1_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_1_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_2                      0x4201006Cu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_2_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_2_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_3                      0x42010070u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_3_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_3_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_4                      0x42010074u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_4_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_4_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_5                      0x42010078u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_5_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_5_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_6                      0x4201007Cu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_6_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_6_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_7                      0x42010080u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_7_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_7_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_8                      0x42010084u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_8_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_8_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_9                      0x42010088u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_9_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_9_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_10                     0x4201008Cu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_10_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_10_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_11                     0x42010090u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_11_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_11_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_12                     0x42010094u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_12_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_12_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_13                     0x42010098u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_13_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_13_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_14                     0x4201009Cu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_14_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_14_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_15                     0x420100A0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_15_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_15_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_0                       0x420100A4u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_0_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_0_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_1                       0x420100A8u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_1_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_1_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_2                       0x420100ACu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_2_FIELDNUM              1u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_2_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_3                       0x420100B0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_3_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_3_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_4                       0x420100B4u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_4_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_4_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_5                       0x420100B8u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_5_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_5_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_6                       0x420100BCu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_6_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_6_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_7                       0x420100C0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_7_FIELDNUM              1u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_7_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_8                       0x420100C4u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_8_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_8_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_9                       0x420100C8u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_9_FIELDNUM              1u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_9_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_10                      0x420100CCu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_10_FIELDNUM             1u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_10_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_11                      0x420100D0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_11_FIELDNUM             1u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_11_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_12                      0x420100D4u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_12_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_12_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_13                      0x420100D8u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_13_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_13_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_0                     0x420100DCu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_0_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_0_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_1                     0x420100E0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_1_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_1_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_2                     0x420100E4u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_2_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_2_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_3                     0x420100E8u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_3_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_3_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_4                     0x420100ECu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_4_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_4_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_5                     0x420100F0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_5_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_5_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_6                     0x420100F4u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_6_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_6_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_7                     0x420100F8u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_7_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_7_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_8                     0x420100FCu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_8_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_8_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_9                     0x42010100u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_9_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_9_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_10                    0x42010104u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_10_FIELDNUM           2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_10_DEFAULTVAL         0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_11                    0x42010108u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_11_FIELDNUM           2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_11_DEFAULTVAL         0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_12                    0x4201010Cu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_12_FIELDNUM           2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_12_DEFAULTVAL         0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_13                    0x42010110u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_13_FIELDNUM           2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_PCIE_13_DEFAULTVAL         0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CPU_0                        0x42010114u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CPU_0_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CPU_0_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CPU_1                        0x42010118u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CPU_1_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CPU_1_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_0                        0x4201011Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_0_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_0_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_1                        0x42010120u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_1_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_1_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_2                        0x42010124u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_2_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_2_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_3                        0x42010128u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_3_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_3_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_4                        0x4201012Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_4_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_4_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_5                        0x42010130u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_5_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_5_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_6                        0x42010134u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_6_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_6_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_7                        0x42010138u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_7_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_7_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_8                        0x4201013Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_8_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_8_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_9                        0x42010140u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_9_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_9_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_10                       0x42010144u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_10_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_10_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_11                       0x42010148u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_11_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_11_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_12                       0x4201014Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_12_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_12_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_13                       0x42010150u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_13_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_13_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_14                       0x42010154u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_14_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_14_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_15                       0x42010158u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_15_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_15_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_0                         0x4201015Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_0_FIELDNUM                2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_0_DEFAULTVAL              0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_1                         0x42010160u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_1_FIELDNUM                2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_1_DEFAULTVAL              0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_2                         0x42010164u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_2_FIELDNUM                1u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_2_DEFAULTVAL              0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_3                         0x42010168u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_3_FIELDNUM                2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_3_DEFAULTVAL              0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_4                         0x4201016Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_4_FIELDNUM                2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_4_DEFAULTVAL              0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_5                         0x42010170u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_5_FIELDNUM                2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_5_DEFAULTVAL              0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_6                         0x42010174u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_6_FIELDNUM                2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_6_DEFAULTVAL              0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_7                         0x42010178u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_7_FIELDNUM                1u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_7_DEFAULTVAL              0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_8                         0x4201017Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_8_FIELDNUM                2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_8_DEFAULTVAL              0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_9                         0x42010180u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_9_FIELDNUM                1u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_9_DEFAULTVAL              0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_10                        0x42010184u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_10_FIELDNUM               1u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_10_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_11                        0x42010188u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_11_FIELDNUM               1u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_11_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_12                        0x4201018Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_12_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_12_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_13                        0x42010190u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_13_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_13_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_0                       0x42010194u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_0_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_0_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_1                       0x42010198u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_1_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_1_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_2                       0x4201019Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_2_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_2_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_3                       0x420101A0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_3_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_3_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_4                       0x420101A4u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_4_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_4_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_5                       0x420101A8u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_5_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_5_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_6                       0x420101ACu
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_6_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_6_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_7                       0x420101B0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_7_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_7_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_8                       0x420101B4u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_8_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_8_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_9                       0x420101B8u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_9_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_9_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_10                      0x420101BCu
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_10_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_10_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_11                      0x420101C0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_11_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_11_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_12                      0x420101C4u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_12_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_12_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_13                      0x420101C8u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_13_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_PCIE_13_DEFAULTVAL           0x0u
#define DV1_TIMESTAMP_CONVERTER                                  0x420101CCu
#define DV1_TIMESTAMP_CONVERTER_FIELDNUM                         5u
#define DV1_TIMESTAMP_CONVERTER_DEFAULTVAL                       0x6u
#define DV1_TIMESTAMP_NS_IN                                      0x420101D0u
#define DV1_TIMESTAMP_NS_IN_FIELDNUM                             1u
#define DV1_TIMESTAMP_NS_IN_DEFAULTVAL                           0x0u
#define DV1_TIMESTAMP_S0_IN                                      0x420101D4u
#define DV1_TIMESTAMP_S0_IN_FIELDNUM                             1u
#define DV1_TIMESTAMP_S0_IN_DEFAULTVAL                           0x0u
#define DV1_TIMESTAMP_S1_IN                                      0x420101D8u
#define DV1_TIMESTAMP_S1_IN_FIELDNUM                             2u
#define DV1_TIMESTAMP_S1_IN_DEFAULTVAL                           0x0u
#define DV1_TIMESTAMP_NS_OUT                                     0x420101DCu
#define DV1_TIMESTAMP_NS_OUT_FIELDNUM                            1u
#define DV1_TIMESTAMP_NS_OUT_DEFAULTVAL                          0x0u
#define DV1_TIMESTAMP_S0_OUT                                     0x420101E0u
#define DV1_TIMESTAMP_S0_OUT_FIELDNUM                            1u
#define DV1_TIMESTAMP_S0_OUT_DEFAULTVAL                          0x0u
#define DV1_TIMESTAMP_S1_OUT                                     0x420101E4u
#define DV1_TIMESTAMP_S1_OUT_FIELDNUM                            2u
#define DV1_TIMESTAMP_S1_OUT_DEFAULTVAL                          0x0u
#define DV1_SCALED_NS0_IN                                        0x420101E8u
#define DV1_SCALED_NS0_IN_FIELDNUM                               1u
#define DV1_SCALED_NS0_IN_DEFAULTVAL                             0x0u
#define DV1_SCALED_NS1_IN                                        0x420101ECu
#define DV1_SCALED_NS1_IN_FIELDNUM                               1u
#define DV1_SCALED_NS1_IN_DEFAULTVAL                             0x0u
#define DV1_SCALED_NS2_IN                                        0x420101F0u
#define DV1_SCALED_NS2_IN_FIELDNUM                               1u
#define DV1_SCALED_NS2_IN_DEFAULTVAL                             0x0u
#define DV1_SCALED_NS0_OUT                                       0x420101F4u
#define DV1_SCALED_NS0_OUT_FIELDNUM                              1u
#define DV1_SCALED_NS0_OUT_DEFAULTVAL                            0x0u
#define DV1_SCALED_NS1_OUT                                       0x420101F8u
#define DV1_SCALED_NS1_OUT_FIELDNUM                              1u
#define DV1_SCALED_NS1_OUT_DEFAULTVAL                            0x0u
#define DV1_SCALED_NS2_OUT                                       0x420101FCu
#define DV1_SCALED_NS2_OUT_FIELDNUM                              1u
#define DV1_SCALED_NS2_OUT_DEFAULTVAL                            0x0u
#define DV1_AUGEND_MINUEND_0                                     0x42010200u
#define DV1_AUGEND_MINUEND_0_FIELDNUM                            1u
#define DV1_AUGEND_MINUEND_0_DEFAULTVAL                          0x0u
#define DV1_AUGEND_MINUEND_1                                     0x42010204u
#define DV1_AUGEND_MINUEND_1_FIELDNUM                            1u
#define DV1_AUGEND_MINUEND_1_DEFAULTVAL                          0x0u
#define DV1_AUGEND_MINUEND_2                                     0x42010208u
#define DV1_AUGEND_MINUEND_2_FIELDNUM                            1u
#define DV1_AUGEND_MINUEND_2_DEFAULTVAL                          0x0u
#define DV1_ADDEND_SUBTRAHEND_0                                  0x4201020Cu
#define DV1_ADDEND_SUBTRAHEND_0_FIELDNUM                         1u
#define DV1_ADDEND_SUBTRAHEND_0_DEFAULTVAL                       0x0u
#define DV1_ADDEND_SUBTRAHEND_1                                  0x42010210u
#define DV1_ADDEND_SUBTRAHEND_1_FIELDNUM                         1u
#define DV1_ADDEND_SUBTRAHEND_1_DEFAULTVAL                       0x0u
#define DV1_ADDEND_SUBTRAHEND_2                                  0x42010214u
#define DV1_ADDEND_SUBTRAHEND_2_FIELDNUM                         1u
#define DV1_ADDEND_SUBTRAHEND_2_DEFAULTVAL                       0x0u
#define DV1_ADDER_OUT0                                           0x42010218u
#define DV1_ADDER_OUT0_FIELDNUM                                  1u
#define DV1_ADDER_OUT0_DEFAULTVAL                                0x0u
#define DV1_ADDER_OUT1                                           0x4201021Cu
#define DV1_ADDER_OUT1_FIELDNUM                                  1u
#define DV1_ADDER_OUT1_DEFAULTVAL                                0x0u
#define DV1_ADDER_OUT2                                           0x42010220u
#define DV1_ADDER_OUT2_FIELDNUM                                  1u
#define DV1_ADDER_OUT2_DEFAULTVAL                                0x0u
#define DV1_SCALE_NS_CONTROL                                     0x42010224u
#define DV1_SCALE_NS_CONTROL_FIELDNUM                            5u
#define DV1_SCALE_NS_CONTROL_DEFAULTVAL                          0x8u
#define DV1_MULTIPLICAND_0                                       0x42010228u
#define DV1_MULTIPLICAND_0_FIELDNUM                              1u
#define DV1_MULTIPLICAND_0_DEFAULTVAL                            0x0u
#define DV1_MULTIPLICAND_1                                       0x4201022Cu
#define DV1_MULTIPLICAND_1_FIELDNUM                              1u
#define DV1_MULTIPLICAND_1_DEFAULTVAL                            0x0u
#define DV1_MULTIPLIER_0                                         0x42010230u
#define DV1_MULTIPLIER_0_FIELDNUM                                1u
#define DV1_MULTIPLIER_0_DEFAULTVAL                              0x0u
#define DV1_MULTIPLIER_1                                         0x42010234u
#define DV1_MULTIPLIER_1_FIELDNUM                                1u
#define DV1_MULTIPLIER_1_DEFAULTVAL                              0x0u
#define DV1_MUL_OUT_0                                            0x42010238u
#define DV1_MUL_OUT_0_FIELDNUM                                   1u
#define DV1_MUL_OUT_0_DEFAULTVAL                                 0x0u
#define DV1_MUL_OUT_1                                            0x4201023Cu
#define DV1_MUL_OUT_1_FIELDNUM                                   1u
#define DV1_MUL_OUT_1_DEFAULTVAL                                 0x0u
#define DV1_MUL_OUT_2                                            0x42010240u
#define DV1_MUL_OUT_2_FIELDNUM                                   1u
#define DV1_MUL_OUT_2_DEFAULTVAL                                 0x0u
#define DV1_MUL_OUT_3                                            0x42010244u
#define DV1_MUL_OUT_3_FIELDNUM                                   1u
#define DV1_MUL_OUT_3_DEFAULTVAL                                 0x0u
#define DV1_MULTIPLIER_CONTROL                                   0x42010248u
#define DV1_MULTIPLIER_CONTROL_FIELDNUM                          5u
#define DV1_MULTIPLIER_CONTROL_DEFAULTVAL                        0x8u
#define DV1_NUMERATOR_0                                          0x4201024Cu
#define DV1_NUMERATOR_0_FIELDNUM                                 1u
#define DV1_NUMERATOR_0_DEFAULTVAL                               0x0u
#define DV1_NUMERATOR_1                                          0x42010250u
#define DV1_NUMERATOR_1_FIELDNUM                                 1u
#define DV1_NUMERATOR_1_DEFAULTVAL                               0x0u
#define DV1_DENOMINATOR_0                                        0x42010254u
#define DV1_DENOMINATOR_0_FIELDNUM                               1u
#define DV1_DENOMINATOR_0_DEFAULTVAL                             0x0u
#define DV1_DENOMINATOR_1                                        0x42010258u
#define DV1_DENOMINATOR_1_FIELDNUM                               1u
#define DV1_DENOMINATOR_1_DEFAULTVAL                             0x0u
#define DV1_DIV_OUT_0                                            0x4201025Cu
#define DV1_DIV_OUT_0_FIELDNUM                                   1u
#define DV1_DIV_OUT_0_DEFAULTVAL                                 0x0u
#define DV1_DIV_OUT_1                                            0x42010260u
#define DV1_DIV_OUT_1_FIELDNUM                                   1u
#define DV1_DIV_OUT_1_DEFAULTVAL                                 0x0u
#define DV1_DIVIDER_CONTROL                                      0x42010264u
#define DV1_DIVIDER_CONTROL_FIELDNUM                             5u
#define DV1_DIVIDER_CONTROL_DEFAULTVAL                           0x18u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_14                        0x42010268u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_14_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_14_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_15                        0x4201026Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_15_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_15_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_16                        0x42010270u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_16_FIELDNUM               1u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_16_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_17                        0x42010274u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_17_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_17_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_18                        0x42010278u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_18_FIELDNUM               1u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_18_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_19                        0x4201027Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_19_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_19_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_14                      0x42010280u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_14_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_14_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_15                      0x42010284u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_15_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_15_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_16                      0x42010288u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_16_FIELDNUM             1u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_16_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_17                      0x4201028Cu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_17_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_17_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_18                      0x42010290u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_18_FIELDNUM             1u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_18_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_19                      0x42010294u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_19_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_19_DEFAULTVAL           0x0u
#define DV1_CPU_SLEEP                                            0x42010298u
#define DV1_CPU_SLEEP_FIELDNUM                                   2u
#define DV1_CPU_SLEEP_DEFAULTVAL                                 0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_20                        0x4201029Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_20_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_20_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_20                      0x420102A0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_20_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_20_DEFAULTVAL           0x0u
#define DV1_CR5_SRAM_MODE6                                       0x420102A4u
#define DV1_CR5_SRAM_MODE6_FIELDNUM                              2u
#define DV1_CR5_SRAM_MODE6_DEFAULTVAL                            0x0u
#define DV1_CPU_ECC_PRE_WRITE_STATUS0                            0x420102A8u
#define DV1_CPU_ECC_PRE_WRITE_STATUS0_FIELDNUM                   2u
#define DV1_CPU_ECC_PRE_WRITE_STATUS0_DEFAULTVAL                 0x0u
#define DV1_CPU_ECC_PRE_WRITE_ALL_STATUS1                        0x420102ACu
#define DV1_CPU_ECC_PRE_WRITE_ALL_STATUS1_FIELDNUM               3u
#define DV1_CPU_ECC_PRE_WRITE_ALL_STATUS1_DEFAULTVAL             0x0u
#define DV1_CPU_ECC0                                             0x420102B0u
#define DV1_CPU_ECC0_FIELDNUM                                    2u
#define DV1_CPU_ECC0_DEFAULTVAL                                  0x0u
#define DV1_CR5_ECC2                                             0x420102B4u
#define DV1_CR5_ECC2_FIELDNUM                                    1u
#define DV1_CR5_ECC2_DEFAULTVAL                                  0x0u
#define DV1_CR5_ECC3                                             0x420102B8u
#define DV1_CR5_ECC3_FIELDNUM                                    1u
#define DV1_CR5_ECC3_DEFAULTVAL                                  0x0u
#define DV1_CR5_ECC4                                             0x420102BCu
#define DV1_CR5_ECC4_FIELDNUM                                    1u
#define DV1_CR5_ECC4_DEFAULTVAL                                  0x0u
#define DV1_CR5_ECC5                                             0x420102C0u
#define DV1_CR5_ECC5_FIELDNUM                                    2u
#define DV1_CR5_ECC5_DEFAULTVAL                                  0x0u
#define DV1_CPU_SRAM_MODE0                                       0x420102C4u
#define DV1_CPU_SRAM_MODE0_FIELDNUM                              2u
#define DV1_CPU_SRAM_MODE0_DEFAULTVAL                            0x15u
#define DV1_CPU_SRAM_MODE1                                       0x420102C8u
#define DV1_CPU_SRAM_MODE1_FIELDNUM                              2u
#define DV1_CPU_SRAM_MODE1_DEFAULTVAL                            0x0u
#define DV1_CPU_SRAM_MODE2                                       0x420102CCu
#define DV1_CPU_SRAM_MODE2_FIELDNUM                              2u
#define DV1_CPU_SRAM_MODE2_DEFAULTVAL                            0x0u
#define DV1_SPIC_FIFO_RX_DEBUG                                   0x420102D0u
#define DV1_SPIC_FIFO_RX_DEBUG_FIELDNUM                          7u
#define DV1_SPIC_FIFO_RX_DEBUG_DEFAULTVAL                        0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_17                       0x420102D4u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_17_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_17_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_18                       0x420102D8u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_18_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_18_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_19                       0x420102DCu
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_19_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_19_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_20                       0x420102E0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_20_FIELDNUM              2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CR5_20_DEFAULTVAL            0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_17                     0x420102E4u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_17_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_17_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_18                     0x420102E8u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_18_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_18_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_19                     0x420102ECu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_19_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_19_DEFAULTVAL          0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_20                     0x420102F0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_20_FIELDNUM            2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CR5_20_DEFAULTVAL          0x0u
#define DV1_CR5_SRAM_MODE7                                       0x420102F4u
#define DV1_CR5_SRAM_MODE7_FIELDNUM                              2u
#define DV1_CR5_SRAM_MODE7_DEFAULTVAL                            0x0u
#define DV1_CPU_CTRL_REG                                         0x420102F8u
#define DV1_CPU_CTRL_REG_FIELDNUM                                20u
#define DV1_CPU_CTRL_REG_DEFAULTVAL                              0x3FFFu
#define DV1_CPU_CTRL_REG_1                                       0x420102FCu
#define DV1_CPU_CTRL_REG_1_FIELDNUM                              1u
#define DV1_CPU_CTRL_REG_1_DEFAULTVAL                            0x0u
#define DV1_CPU_CTRL_REG_2                                       0x42010300u
#define DV1_CPU_CTRL_REG_2_FIELDNUM                              1u
#define DV1_CPU_CTRL_REG_2_DEFAULTVAL                            0x0u
#define DV1_CPU_CTRL_REG_3                                       0x42010304u
#define DV1_CPU_CTRL_REG_3_FIELDNUM                              2u
#define DV1_CPU_CTRL_REG_3_DEFAULTVAL                            0x1u
#define DV1_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT            0x42010308u
#define DV1_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_FIELDNUM   6u
#define DV1_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_DEFAULTVAL 0x0u
#define DV1_CR5_SRAM_MODE8                                       0x4201030Cu
#define DV1_CR5_SRAM_MODE8_FIELDNUM                              2u
#define DV1_CR5_SRAM_MODE8_DEFAULTVAL                            0x0u
#define DV1_CR5_SRAM_MODE9                                       0x42010310u
#define DV1_CR5_SRAM_MODE9_FIELDNUM                              2u
#define DV1_CR5_SRAM_MODE9_DEFAULTVAL                            0x0u
#define DV1_CR5_SRAM_MODE10                                      0x42010314u
#define DV1_CR5_SRAM_MODE10_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE10_DEFAULTVAL                           0x0u
#define DV1_CR5_SRAM_MODE11                                      0x42010318u
#define DV1_CR5_SRAM_MODE11_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE11_DEFAULTVAL                           0x0u
#define DV1_CR5_SRAM_MODE12                                      0x4201031Cu
#define DV1_CR5_SRAM_MODE12_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE12_DEFAULTVAL                           0x0u
#define DV1_CR5_SRAM_MODE13                                      0x42010320u
#define DV1_CR5_SRAM_MODE13_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE13_DEFAULTVAL                           0x0u
#define DV1_CR5_SRAM_MODE14                                      0x42010324u
#define DV1_CR5_SRAM_MODE14_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE14_DEFAULTVAL                           0x15u
#define DV1_CR5_SRAM_MODE15                                      0x42010328u
#define DV1_CR5_SRAM_MODE15_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE15_DEFAULTVAL                           0x15u
#define DV1_CR5_SRAM_MODE16                                      0x4201032Cu
#define DV1_CR5_SRAM_MODE16_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE16_DEFAULTVAL                           0x15u
#define DV1_CR5_SRAM_MODE17                                      0x42010330u
#define DV1_CR5_SRAM_MODE17_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE17_DEFAULTVAL                           0x15u
#define DV1_CR5_SRAM_MODE18                                      0x42010334u
#define DV1_CR5_SRAM_MODE18_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE18_DEFAULTVAL                           0x15u
#define DV1_CR5_SRAM_MODE19                                      0x42010338u
#define DV1_CR5_SRAM_MODE19_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE19_DEFAULTVAL                           0x15u
#define DV1_CR5_SRAM_MODE20                                      0x4201033Cu
#define DV1_CR5_SRAM_MODE20_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE20_DEFAULTVAL                           0x15u
#define DV1_CR5_SRAM_MODE21                                      0x42010340u
#define DV1_CR5_SRAM_MODE21_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE21_DEFAULTVAL                           0x15u
#define DV1_CR5_SRAM_MODE22                                      0x42010344u
#define DV1_CR5_SRAM_MODE22_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE22_DEFAULTVAL                           0x0u
#define DV1_CR5_SRAM_MODE23                                      0x42010348u
#define DV1_CR5_SRAM_MODE23_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE23_DEFAULTVAL                           0x0u
#define DV1_CR5_SRAM_MODE24                                      0x4201034Cu
#define DV1_CR5_SRAM_MODE24_FIELDNUM                             2u
#define DV1_CR5_SRAM_MODE24_DEFAULTVAL                           0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CPU_2                        0x42010350u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CPU_2_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_CPU_2_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CPU_2                      0x42010354u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CPU_2_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_CPU_2_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_21                      0x42010358u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_21_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_21_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_22                      0x4201035Cu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_22_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_22_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_23                      0x42010360u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_23_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_23_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_24                      0x42010364u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_24_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_24_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_25                      0x42010368u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_25_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_25_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_26                      0x4201036Cu
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_26_FIELDNUM             2u
#define DV1_SRAM_ECC_INTERRUPT_STATUS_SW_26_DEFAULTVAL           0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_21                        0x42010370u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_21_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_21_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_22                        0x42010374u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_22_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_22_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_23                        0x42010378u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_23_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_23_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_24                        0x4201037Cu
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_24_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_24_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_25                        0x42010380u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_25_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_25_DEFAULTVAL             0x0u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_26                        0x42010384u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_26_FIELDNUM               2u
#define DV1_SRAM_ECC_INTERRUPT_MASK_SW_26_DEFAULTVAL             0x0u
#endif
#endif /* DV1_RTKAS_REG_LIST_FILE_CPU_DOMAIN_H_ */