/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_LIST_FILE_EEE_H_
#define DV1_RTKAS_REG_LIST_FILE_EEE_H_

#ifdef DV1_FILE_EEE
/* File: EEE MAC Control */
#define DV1_GLOBAL_EEE_MAC_CONTROL0                             0x4A7B0000u
#define DV1_GLOBAL_EEE_MAC_CONTROL0_FIELDNUM                    2u
#define DV1_GLOBAL_EEE_MAC_CONTROL0_DEFAULTVAL                  0x1u
#define DV1_GLOBAL_EEE_MAC_CONTROL1                             0x4A7B0004u
#define DV1_GLOBAL_EEE_MAC_CONTROL1_FIELDNUM                    4u
#define DV1_GLOBAL_EEE_MAC_CONTROL1_DEFAULTVAL                  0x2405C80Au
#define DV1_GLOBAL_EEE_MAC_CONTROL2                             0x4A7B0008u
#define DV1_GLOBAL_EEE_MAC_CONTROL2_FIELDNUM                    3u
#define DV1_GLOBAL_EEE_MAC_CONTROL2_DEFAULTVAL                  0x20u
#define DV1_GLOBAL_EEE_MAC_CONTROL3                             0x4A7B000Cu
#define DV1_GLOBAL_EEE_MAC_CONTROL3_FIELDNUM                    4u
#define DV1_GLOBAL_EEE_MAC_CONTROL3_DEFAULTVAL                  0x14051402u
#define DV1_GLOBAL_EEE_MAC_CONTROL4                             0x4A7B0010u
#define DV1_GLOBAL_EEE_MAC_CONTROL4_FIELDNUM                    3u
#define DV1_GLOBAL_EEE_MAC_CONTROL4_DEFAULTVAL                  0x20u
#define DV1_HEAC_NWAY_FRAME_BITS_DEFINITION                     0x4A7B0014u
#define DV1_HEAC_NWAY_FRAME_BITS_DEFINITION_FIELDNUM            3u
#define DV1_HEAC_NWAY_FRAME_BITS_DEFINITION_DEFAULTVAL          0x30000u
#define DV1_EEE_DMY0                                            0x4A7B0018u
#define DV1_EEE_DMY0_FIELDNUM                                   1u
#define DV1_EEE_DMY0_DEFAULTVAL                                 0x0u
#define DV1_EEE_DMY1                                            0x4A7B001Cu
#define DV1_EEE_DMY1_FIELDNUM                                   1u
#define DV1_EEE_DMY1_DEFAULTVAL                                 0x1u
#define DV1_EEE_DMY2                                            0x4A7B0020u
#define DV1_EEE_DMY2_FIELDNUM                                   1u
#define DV1_EEE_DMY2_DEFAULTVAL                                 0x0u
#define DV1_EEE_DMY3                                            0x4A7B0024u
#define DV1_EEE_DMY3_FIELDNUM                                   1u
#define DV1_EEE_DMY3_DEFAULTVAL                                 0x0u
#define DV1_PORT0_HEAC_EEE_AUTO_NEGOTIATION                     0x4AFB0000u
#define DV1_PORT0_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM            6u
#define DV1_PORT0_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL          0x18u
#define DV1_PORT1_HEAC_EEE_AUTO_NEGOTIATION                     0x4AFB0800u
#define DV1_PORT1_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM            6u
#define DV1_PORT1_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL          0x18u
#define DV1_PORT2_HEAC_EEE_AUTO_NEGOTIATION                     0x4AFB1000u
#define DV1_PORT2_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM            6u
#define DV1_PORT2_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL          0x18u
#define DV1_PORT3_HEAC_EEE_AUTO_NEGOTIATION                     0x4AFB1800u
#define DV1_PORT3_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM            6u
#define DV1_PORT3_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL          0x18u
#define DV1_PORT4_HEAC_EEE_AUTO_NEGOTIATION                     0x4AFB2000u
#define DV1_PORT4_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM            6u
#define DV1_PORT4_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL          0x18u
#define DV1_PORT5_HEAC_EEE_AUTO_NEGOTIATION                     0x4AFB2800u
#define DV1_PORT5_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM            6u
#define DV1_PORT5_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL          0x18u
#define DV1_PORT6_HEAC_EEE_AUTO_NEGOTIATION                     0x4AFB3000u
#define DV1_PORT6_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM            6u
#define DV1_PORT6_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL          0x18u
#define DV1_PORT7_HEAC_EEE_AUTO_NEGOTIATION                     0x4AFB3800u
#define DV1_PORT7_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM            6u
#define DV1_PORT7_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL          0x18u
#define DV1_PORT8_HEAC_EEE_AUTO_NEGOTIATION                     0x4AFB4000u
#define DV1_PORT8_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM            6u
#define DV1_PORT8_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL          0x18u
#define DV1_PORT9_HEAC_EEE_AUTO_NEGOTIATION                     0x4AFB4800u
#define DV1_PORT9_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM            6u
#define DV1_PORT9_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL          0x18u
#define DV1_PORT10_HEAC_EEE_AUTO_NEGOTIATION                    0x4AFB5000u
#define DV1_PORT10_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM           6u
#define DV1_PORT10_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL         0x18u
#define DV1_PORT11_HEAC_EEE_AUTO_NEGOTIATION                    0x4AFB5800u
#define DV1_PORT11_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM           6u
#define DV1_PORT11_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL         0x18u
#define DV1_PORT12_HEAC_EEE_AUTO_NEGOTIATION                    0x4AFB6000u
#define DV1_PORT12_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM           6u
#define DV1_PORT12_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL         0x18u
#define DV1_PORT13_HEAC_EEE_AUTO_NEGOTIATION                    0x4AFB6800u
#define DV1_PORT13_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM           6u
#define DV1_PORT13_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL         0x18u
#define DV1_PORT14_HEAC_EEE_AUTO_NEGOTIATION                    0x4AFB7000u
#define DV1_PORT14_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM           6u
#define DV1_PORT14_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL         0x18u
#define DV1_PORT15_HEAC_EEE_AUTO_NEGOTIATION                    0x4AFB7800u
#define DV1_PORT15_HEAC_EEE_AUTO_NEGOTIATION_FIELDNUM           6u
#define DV1_PORT15_HEAC_EEE_AUTO_NEGOTIATION_DEFAULTVAL         0x18u
#define DV1_PORT0_HEAC_FLOWCONTROL_LP_ADVERTISEMENT             0x4AFB0004u
#define DV1_PORT0_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM    3u
#define DV1_PORT0_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL  0x0u
#define DV1_PORT1_HEAC_FLOWCONTROL_LP_ADVERTISEMENT             0x4AFB0804u
#define DV1_PORT1_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM    3u
#define DV1_PORT1_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL  0x0u
#define DV1_PORT2_HEAC_FLOWCONTROL_LP_ADVERTISEMENT             0x4AFB1004u
#define DV1_PORT2_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM    3u
#define DV1_PORT2_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL  0x0u
#define DV1_PORT3_HEAC_FLOWCONTROL_LP_ADVERTISEMENT             0x4AFB1804u
#define DV1_PORT3_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM    3u
#define DV1_PORT3_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL  0x0u
#define DV1_PORT4_HEAC_FLOWCONTROL_LP_ADVERTISEMENT             0x4AFB2004u
#define DV1_PORT4_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM    3u
#define DV1_PORT4_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL  0x0u
#define DV1_PORT5_HEAC_FLOWCONTROL_LP_ADVERTISEMENT             0x4AFB2804u
#define DV1_PORT5_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM    3u
#define DV1_PORT5_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL  0x0u
#define DV1_PORT6_HEAC_FLOWCONTROL_LP_ADVERTISEMENT             0x4AFB3004u
#define DV1_PORT6_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM    3u
#define DV1_PORT6_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL  0x0u
#define DV1_PORT7_HEAC_FLOWCONTROL_LP_ADVERTISEMENT             0x4AFB3804u
#define DV1_PORT7_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM    3u
#define DV1_PORT7_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL  0x0u
#define DV1_PORT8_HEAC_FLOWCONTROL_LP_ADVERTISEMENT             0x4AFB4004u
#define DV1_PORT8_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM    3u
#define DV1_PORT8_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL  0x0u
#define DV1_PORT9_HEAC_FLOWCONTROL_LP_ADVERTISEMENT             0x4AFB4804u
#define DV1_PORT9_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM    3u
#define DV1_PORT9_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL  0x0u
#define DV1_PORT10_HEAC_FLOWCONTROL_LP_ADVERTISEMENT            0x4AFB5004u
#define DV1_PORT10_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM   3u
#define DV1_PORT10_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL 0x0u
#define DV1_PORT11_HEAC_FLOWCONTROL_LP_ADVERTISEMENT            0x4AFB5804u
#define DV1_PORT11_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM   3u
#define DV1_PORT11_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL 0x0u
#define DV1_PORT12_HEAC_FLOWCONTROL_LP_ADVERTISEMENT            0x4AFB6004u
#define DV1_PORT12_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM   3u
#define DV1_PORT12_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL 0x0u
#define DV1_PORT13_HEAC_FLOWCONTROL_LP_ADVERTISEMENT            0x4AFB6804u
#define DV1_PORT13_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM   3u
#define DV1_PORT13_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL 0x0u
#define DV1_PORT14_HEAC_FLOWCONTROL_LP_ADVERTISEMENT            0x4AFB7004u
#define DV1_PORT14_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM   3u
#define DV1_PORT14_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL 0x0u
#define DV1_PORT15_HEAC_FLOWCONTROL_LP_ADVERTISEMENT            0x4AFB7804u
#define DV1_PORT15_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_FIELDNUM   3u
#define DV1_PORT15_HEAC_FLOWCONTROL_LP_ADVERTISEMENT_DEFAULTVAL 0x0u
#define DV1_PORT0_HEAC_EEE_LP_ADVERTISEMENT                     0x4AFB0008u
#define DV1_PORT0_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM            2u
#define DV1_PORT0_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL          0x0u
#define DV1_PORT1_HEAC_EEE_LP_ADVERTISEMENT                     0x4AFB0808u
#define DV1_PORT1_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM            2u
#define DV1_PORT1_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL          0x0u
#define DV1_PORT2_HEAC_EEE_LP_ADVERTISEMENT                     0x4AFB1008u
#define DV1_PORT2_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM            2u
#define DV1_PORT2_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL          0x0u
#define DV1_PORT3_HEAC_EEE_LP_ADVERTISEMENT                     0x4AFB1808u
#define DV1_PORT3_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM            2u
#define DV1_PORT3_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL          0x0u
#define DV1_PORT4_HEAC_EEE_LP_ADVERTISEMENT                     0x4AFB2008u
#define DV1_PORT4_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM            2u
#define DV1_PORT4_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL          0x0u
#define DV1_PORT5_HEAC_EEE_LP_ADVERTISEMENT                     0x4AFB2808u
#define DV1_PORT5_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM            2u
#define DV1_PORT5_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL          0x0u
#define DV1_PORT6_HEAC_EEE_LP_ADVERTISEMENT                     0x4AFB3008u
#define DV1_PORT6_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM            2u
#define DV1_PORT6_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL          0x0u
#define DV1_PORT7_HEAC_EEE_LP_ADVERTISEMENT                     0x4AFB3808u
#define DV1_PORT7_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM            2u
#define DV1_PORT7_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL          0x0u
#define DV1_PORT8_HEAC_EEE_LP_ADVERTISEMENT                     0x4AFB4008u
#define DV1_PORT8_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM            2u
#define DV1_PORT8_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL          0x0u
#define DV1_PORT9_HEAC_EEE_LP_ADVERTISEMENT                     0x4AFB4808u
#define DV1_PORT9_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM            2u
#define DV1_PORT9_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL          0x0u
#define DV1_PORT10_HEAC_EEE_LP_ADVERTISEMENT                    0x4AFB5008u
#define DV1_PORT10_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM           2u
#define DV1_PORT10_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL         0x0u
#define DV1_PORT11_HEAC_EEE_LP_ADVERTISEMENT                    0x4AFB5808u
#define DV1_PORT11_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM           2u
#define DV1_PORT11_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL         0x0u
#define DV1_PORT12_HEAC_EEE_LP_ADVERTISEMENT                    0x4AFB6008u
#define DV1_PORT12_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM           2u
#define DV1_PORT12_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL         0x0u
#define DV1_PORT13_HEAC_EEE_LP_ADVERTISEMENT                    0x4AFB6808u
#define DV1_PORT13_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM           2u
#define DV1_PORT13_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL         0x0u
#define DV1_PORT14_HEAC_EEE_LP_ADVERTISEMENT                    0x4AFB7008u
#define DV1_PORT14_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM           2u
#define DV1_PORT14_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL         0x0u
#define DV1_PORT15_HEAC_EEE_LP_ADVERTISEMENT                    0x4AFB7808u
#define DV1_PORT15_HEAC_EEE_LP_ADVERTISEMENT_FIELDNUM           2u
#define DV1_PORT15_HEAC_EEE_LP_ADVERTISEMENT_DEFAULTVAL         0x0u
#define DV1_PORT0_EEE_MAC_CONTROL                               0x4AFB000Cu
#define DV1_PORT0_EEE_MAC_CONTROL_FIELDNUM                      11u
#define DV1_PORT0_EEE_MAC_CONTROL_DEFAULTVAL                    0x6A3000u
#define DV1_PORT1_EEE_MAC_CONTROL                               0x4AFB080Cu
#define DV1_PORT1_EEE_MAC_CONTROL_FIELDNUM                      11u
#define DV1_PORT1_EEE_MAC_CONTROL_DEFAULTVAL                    0x6A3000u
#define DV1_PORT2_EEE_MAC_CONTROL                               0x4AFB100Cu
#define DV1_PORT2_EEE_MAC_CONTROL_FIELDNUM                      11u
#define DV1_PORT2_EEE_MAC_CONTROL_DEFAULTVAL                    0x6A3000u
#define DV1_PORT3_EEE_MAC_CONTROL                               0x4AFB180Cu
#define DV1_PORT3_EEE_MAC_CONTROL_FIELDNUM                      11u
#define DV1_PORT3_EEE_MAC_CONTROL_DEFAULTVAL                    0x6A3000u
#define DV1_PORT4_EEE_MAC_CONTROL                               0x4AFB200Cu
#define DV1_PORT4_EEE_MAC_CONTROL_FIELDNUM                      11u
#define DV1_PORT4_EEE_MAC_CONTROL_DEFAULTVAL                    0x6A3000u
#define DV1_PORT5_EEE_MAC_CONTROL                               0x4AFB280Cu
#define DV1_PORT5_EEE_MAC_CONTROL_FIELDNUM                      11u
#define DV1_PORT5_EEE_MAC_CONTROL_DEFAULTVAL                    0x6A3000u
#define DV1_PORT6_EEE_MAC_CONTROL                               0x4AFB300Cu
#define DV1_PORT6_EEE_MAC_CONTROL_FIELDNUM                      11u
#define DV1_PORT6_EEE_MAC_CONTROL_DEFAULTVAL                    0x6A3000u
#define DV1_PORT7_EEE_MAC_CONTROL                               0x4AFB380Cu
#define DV1_PORT7_EEE_MAC_CONTROL_FIELDNUM                      11u
#define DV1_PORT7_EEE_MAC_CONTROL_DEFAULTVAL                    0x6A3000u
#define DV1_PORT8_EEE_MAC_CONTROL                               0x4AFB400Cu
#define DV1_PORT8_EEE_MAC_CONTROL_FIELDNUM                      11u
#define DV1_PORT8_EEE_MAC_CONTROL_DEFAULTVAL                    0x6A3000u
#define DV1_PORT9_EEE_MAC_CONTROL                               0x4AFB480Cu
#define DV1_PORT9_EEE_MAC_CONTROL_FIELDNUM                      11u
#define DV1_PORT9_EEE_MAC_CONTROL_DEFAULTVAL                    0x6A3000u
#define DV1_PORT10_EEE_MAC_CONTROL                              0x4AFB500Cu
#define DV1_PORT10_EEE_MAC_CONTROL_FIELDNUM                     11u
#define DV1_PORT10_EEE_MAC_CONTROL_DEFAULTVAL                   0x6A3000u
#define DV1_PORT11_EEE_MAC_CONTROL                              0x4AFB580Cu
#define DV1_PORT11_EEE_MAC_CONTROL_FIELDNUM                     11u
#define DV1_PORT11_EEE_MAC_CONTROL_DEFAULTVAL                   0x6A3000u
#define DV1_PORT12_EEE_MAC_CONTROL                              0x4AFB600Cu
#define DV1_PORT12_EEE_MAC_CONTROL_FIELDNUM                     11u
#define DV1_PORT12_EEE_MAC_CONTROL_DEFAULTVAL                   0x6A3000u
#define DV1_PORT13_EEE_MAC_CONTROL                              0x4AFB680Cu
#define DV1_PORT13_EEE_MAC_CONTROL_FIELDNUM                     11u
#define DV1_PORT13_EEE_MAC_CONTROL_DEFAULTVAL                   0x6A3000u
#define DV1_PORT14_EEE_MAC_CONTROL                              0x4AFB700Cu
#define DV1_PORT14_EEE_MAC_CONTROL_FIELDNUM                     11u
#define DV1_PORT14_EEE_MAC_CONTROL_DEFAULTVAL                   0x6A3000u
#define DV1_PORT15_EEE_MAC_CONTROL                              0x4AFB780Cu
#define DV1_PORT15_EEE_MAC_CONTROL_FIELDNUM                     11u
#define DV1_PORT15_EEE_MAC_CONTROL_DEFAULTVAL                   0x6A3000u
#define DV1_PORT0_LPI_INDICATION_COUNTER0                       0x4AFB0010u
#define DV1_PORT0_LPI_INDICATION_COUNTER0_FIELDNUM              2u
#define DV1_PORT0_LPI_INDICATION_COUNTER0_DEFAULTVAL            0x0u
#define DV1_PORT1_LPI_INDICATION_COUNTER0                       0x4AFB0810u
#define DV1_PORT1_LPI_INDICATION_COUNTER0_FIELDNUM              2u
#define DV1_PORT1_LPI_INDICATION_COUNTER0_DEFAULTVAL            0x0u
#define DV1_PORT2_LPI_INDICATION_COUNTER0                       0x4AFB1010u
#define DV1_PORT2_LPI_INDICATION_COUNTER0_FIELDNUM              2u
#define DV1_PORT2_LPI_INDICATION_COUNTER0_DEFAULTVAL            0x0u
#define DV1_PORT3_LPI_INDICATION_COUNTER0                       0x4AFB1810u
#define DV1_PORT3_LPI_INDICATION_COUNTER0_FIELDNUM              2u
#define DV1_PORT3_LPI_INDICATION_COUNTER0_DEFAULTVAL            0x0u
#define DV1_PORT4_LPI_INDICATION_COUNTER0                       0x4AFB2010u
#define DV1_PORT4_LPI_INDICATION_COUNTER0_FIELDNUM              2u
#define DV1_PORT4_LPI_INDICATION_COUNTER0_DEFAULTVAL            0x0u
#define DV1_PORT5_LPI_INDICATION_COUNTER0                       0x4AFB2810u
#define DV1_PORT5_LPI_INDICATION_COUNTER0_FIELDNUM              2u
#define DV1_PORT5_LPI_INDICATION_COUNTER0_DEFAULTVAL            0x0u
#define DV1_PORT6_LPI_INDICATION_COUNTER0                       0x4AFB3010u
#define DV1_PORT6_LPI_INDICATION_COUNTER0_FIELDNUM              2u
#define DV1_PORT6_LPI_INDICATION_COUNTER0_DEFAULTVAL            0x0u
#define DV1_PORT7_LPI_INDICATION_COUNTER0                       0x4AFB3810u
#define DV1_PORT7_LPI_INDICATION_COUNTER0_FIELDNUM              2u
#define DV1_PORT7_LPI_INDICATION_COUNTER0_DEFAULTVAL            0x0u
#define DV1_PORT8_LPI_INDICATION_COUNTER0                       0x4AFB4010u
#define DV1_PORT8_LPI_INDICATION_COUNTER0_FIELDNUM              2u
#define DV1_PORT8_LPI_INDICATION_COUNTER0_DEFAULTVAL            0x0u
#define DV1_PORT9_LPI_INDICATION_COUNTER0                       0x4AFB4810u
#define DV1_PORT9_LPI_INDICATION_COUNTER0_FIELDNUM              2u
#define DV1_PORT9_LPI_INDICATION_COUNTER0_DEFAULTVAL            0x0u
#define DV1_PORT10_LPI_INDICATION_COUNTER0                      0x4AFB5010u
#define DV1_PORT10_LPI_INDICATION_COUNTER0_FIELDNUM             2u
#define DV1_PORT10_LPI_INDICATION_COUNTER0_DEFAULTVAL           0x0u
#define DV1_PORT11_LPI_INDICATION_COUNTER0                      0x4AFB5810u
#define DV1_PORT11_LPI_INDICATION_COUNTER0_FIELDNUM             2u
#define DV1_PORT11_LPI_INDICATION_COUNTER0_DEFAULTVAL           0x0u
#define DV1_PORT12_LPI_INDICATION_COUNTER0                      0x4AFB6010u
#define DV1_PORT12_LPI_INDICATION_COUNTER0_FIELDNUM             2u
#define DV1_PORT12_LPI_INDICATION_COUNTER0_DEFAULTVAL           0x0u
#define DV1_PORT13_LPI_INDICATION_COUNTER0                      0x4AFB6810u
#define DV1_PORT13_LPI_INDICATION_COUNTER0_FIELDNUM             2u
#define DV1_PORT13_LPI_INDICATION_COUNTER0_DEFAULTVAL           0x0u
#define DV1_PORT14_LPI_INDICATION_COUNTER0                      0x4AFB7010u
#define DV1_PORT14_LPI_INDICATION_COUNTER0_FIELDNUM             2u
#define DV1_PORT14_LPI_INDICATION_COUNTER0_DEFAULTVAL           0x0u
#define DV1_PORT15_LPI_INDICATION_COUNTER0                      0x4AFB7810u
#define DV1_PORT15_LPI_INDICATION_COUNTER0_FIELDNUM             2u
#define DV1_PORT15_LPI_INDICATION_COUNTER0_DEFAULTVAL           0x0u
#define DV1_PORT0_LPI_INDICATION_COUNTER1                       0x4AFB0014u
#define DV1_PORT0_LPI_INDICATION_COUNTER1_FIELDNUM              2u
#define DV1_PORT0_LPI_INDICATION_COUNTER1_DEFAULTVAL            0x0u
#define DV1_PORT1_LPI_INDICATION_COUNTER1                       0x4AFB0814u
#define DV1_PORT1_LPI_INDICATION_COUNTER1_FIELDNUM              2u
#define DV1_PORT1_LPI_INDICATION_COUNTER1_DEFAULTVAL            0x0u
#define DV1_PORT2_LPI_INDICATION_COUNTER1                       0x4AFB1014u
#define DV1_PORT2_LPI_INDICATION_COUNTER1_FIELDNUM              2u
#define DV1_PORT2_LPI_INDICATION_COUNTER1_DEFAULTVAL            0x0u
#define DV1_PORT3_LPI_INDICATION_COUNTER1                       0x4AFB1814u
#define DV1_PORT3_LPI_INDICATION_COUNTER1_FIELDNUM              2u
#define DV1_PORT3_LPI_INDICATION_COUNTER1_DEFAULTVAL            0x0u
#define DV1_PORT4_LPI_INDICATION_COUNTER1                       0x4AFB2014u
#define DV1_PORT4_LPI_INDICATION_COUNTER1_FIELDNUM              2u
#define DV1_PORT4_LPI_INDICATION_COUNTER1_DEFAULTVAL            0x0u
#define DV1_PORT5_LPI_INDICATION_COUNTER1                       0x4AFB2814u
#define DV1_PORT5_LPI_INDICATION_COUNTER1_FIELDNUM              2u
#define DV1_PORT5_LPI_INDICATION_COUNTER1_DEFAULTVAL            0x0u
#define DV1_PORT6_LPI_INDICATION_COUNTER1                       0x4AFB3014u
#define DV1_PORT6_LPI_INDICATION_COUNTER1_FIELDNUM              2u
#define DV1_PORT6_LPI_INDICATION_COUNTER1_DEFAULTVAL            0x0u
#define DV1_PORT7_LPI_INDICATION_COUNTER1                       0x4AFB3814u
#define DV1_PORT7_LPI_INDICATION_COUNTER1_FIELDNUM              2u
#define DV1_PORT7_LPI_INDICATION_COUNTER1_DEFAULTVAL            0x0u
#define DV1_PORT8_LPI_INDICATION_COUNTER1                       0x4AFB4014u
#define DV1_PORT8_LPI_INDICATION_COUNTER1_FIELDNUM              2u
#define DV1_PORT8_LPI_INDICATION_COUNTER1_DEFAULTVAL            0x0u
#define DV1_PORT9_LPI_INDICATION_COUNTER1                       0x4AFB4814u
#define DV1_PORT9_LPI_INDICATION_COUNTER1_FIELDNUM              2u
#define DV1_PORT9_LPI_INDICATION_COUNTER1_DEFAULTVAL            0x0u
#define DV1_PORT10_LPI_INDICATION_COUNTER1                      0x4AFB5014u
#define DV1_PORT10_LPI_INDICATION_COUNTER1_FIELDNUM             2u
#define DV1_PORT10_LPI_INDICATION_COUNTER1_DEFAULTVAL           0x0u
#define DV1_PORT11_LPI_INDICATION_COUNTER1                      0x4AFB5814u
#define DV1_PORT11_LPI_INDICATION_COUNTER1_FIELDNUM             2u
#define DV1_PORT11_LPI_INDICATION_COUNTER1_DEFAULTVAL           0x0u
#define DV1_PORT12_LPI_INDICATION_COUNTER1                      0x4AFB6014u
#define DV1_PORT12_LPI_INDICATION_COUNTER1_FIELDNUM             2u
#define DV1_PORT12_LPI_INDICATION_COUNTER1_DEFAULTVAL           0x0u
#define DV1_PORT13_LPI_INDICATION_COUNTER1                      0x4AFB6814u
#define DV1_PORT13_LPI_INDICATION_COUNTER1_FIELDNUM             2u
#define DV1_PORT13_LPI_INDICATION_COUNTER1_DEFAULTVAL           0x0u
#define DV1_PORT14_LPI_INDICATION_COUNTER1                      0x4AFB7014u
#define DV1_PORT14_LPI_INDICATION_COUNTER1_FIELDNUM             2u
#define DV1_PORT14_LPI_INDICATION_COUNTER1_DEFAULTVAL           0x0u
#define DV1_PORT15_LPI_INDICATION_COUNTER1                      0x4AFB7814u
#define DV1_PORT15_LPI_INDICATION_COUNTER1_FIELDNUM             2u
#define DV1_PORT15_LPI_INDICATION_COUNTER1_DEFAULTVAL           0x0u
#define DV1_PORT0_LPI_INDICATION_COUNTER2                       0x4AFB0018u
#define DV1_PORT0_LPI_INDICATION_COUNTER2_FIELDNUM              2u
#define DV1_PORT0_LPI_INDICATION_COUNTER2_DEFAULTVAL            0x0u
#define DV1_PORT1_LPI_INDICATION_COUNTER2                       0x4AFB0818u
#define DV1_PORT1_LPI_INDICATION_COUNTER2_FIELDNUM              2u
#define DV1_PORT1_LPI_INDICATION_COUNTER2_DEFAULTVAL            0x0u
#define DV1_PORT2_LPI_INDICATION_COUNTER2                       0x4AFB1018u
#define DV1_PORT2_LPI_INDICATION_COUNTER2_FIELDNUM              2u
#define DV1_PORT2_LPI_INDICATION_COUNTER2_DEFAULTVAL            0x0u
#define DV1_PORT3_LPI_INDICATION_COUNTER2                       0x4AFB1818u
#define DV1_PORT3_LPI_INDICATION_COUNTER2_FIELDNUM              2u
#define DV1_PORT3_LPI_INDICATION_COUNTER2_DEFAULTVAL            0x0u
#define DV1_PORT4_LPI_INDICATION_COUNTER2                       0x4AFB2018u
#define DV1_PORT4_LPI_INDICATION_COUNTER2_FIELDNUM              2u
#define DV1_PORT4_LPI_INDICATION_COUNTER2_DEFAULTVAL            0x0u
#define DV1_PORT5_LPI_INDICATION_COUNTER2                       0x4AFB2818u
#define DV1_PORT5_LPI_INDICATION_COUNTER2_FIELDNUM              2u
#define DV1_PORT5_LPI_INDICATION_COUNTER2_DEFAULTVAL            0x0u
#define DV1_PORT6_LPI_INDICATION_COUNTER2                       0x4AFB3018u
#define DV1_PORT6_LPI_INDICATION_COUNTER2_FIELDNUM              2u
#define DV1_PORT6_LPI_INDICATION_COUNTER2_DEFAULTVAL            0x0u
#define DV1_PORT7_LPI_INDICATION_COUNTER2                       0x4AFB3818u
#define DV1_PORT7_LPI_INDICATION_COUNTER2_FIELDNUM              2u
#define DV1_PORT7_LPI_INDICATION_COUNTER2_DEFAULTVAL            0x0u
#define DV1_PORT8_LPI_INDICATION_COUNTER2                       0x4AFB4018u
#define DV1_PORT8_LPI_INDICATION_COUNTER2_FIELDNUM              2u
#define DV1_PORT8_LPI_INDICATION_COUNTER2_DEFAULTVAL            0x0u
#define DV1_PORT9_LPI_INDICATION_COUNTER2                       0x4AFB4818u
#define DV1_PORT9_LPI_INDICATION_COUNTER2_FIELDNUM              2u
#define DV1_PORT9_LPI_INDICATION_COUNTER2_DEFAULTVAL            0x0u
#define DV1_PORT10_LPI_INDICATION_COUNTER2                      0x4AFB5018u
#define DV1_PORT10_LPI_INDICATION_COUNTER2_FIELDNUM             2u
#define DV1_PORT10_LPI_INDICATION_COUNTER2_DEFAULTVAL           0x0u
#define DV1_PORT11_LPI_INDICATION_COUNTER2                      0x4AFB5818u
#define DV1_PORT11_LPI_INDICATION_COUNTER2_FIELDNUM             2u
#define DV1_PORT11_LPI_INDICATION_COUNTER2_DEFAULTVAL           0x0u
#define DV1_PORT12_LPI_INDICATION_COUNTER2                      0x4AFB6018u
#define DV1_PORT12_LPI_INDICATION_COUNTER2_FIELDNUM             2u
#define DV1_PORT12_LPI_INDICATION_COUNTER2_DEFAULTVAL           0x0u
#define DV1_PORT13_LPI_INDICATION_COUNTER2                      0x4AFB6818u
#define DV1_PORT13_LPI_INDICATION_COUNTER2_FIELDNUM             2u
#define DV1_PORT13_LPI_INDICATION_COUNTER2_DEFAULTVAL           0x0u
#define DV1_PORT14_LPI_INDICATION_COUNTER2                      0x4AFB7018u
#define DV1_PORT14_LPI_INDICATION_COUNTER2_FIELDNUM             2u
#define DV1_PORT14_LPI_INDICATION_COUNTER2_DEFAULTVAL           0x0u
#define DV1_PORT15_LPI_INDICATION_COUNTER2                      0x4AFB7818u
#define DV1_PORT15_LPI_INDICATION_COUNTER2_FIELDNUM             2u
#define DV1_PORT15_LPI_INDICATION_COUNTER2_DEFAULTVAL           0x0u
#define DV1_PORT0_LINK_DOWN_CONTROL                             0x4AFB001Cu
#define DV1_PORT0_LINK_DOWN_CONTROL_FIELDNUM                    3u
#define DV1_PORT0_LINK_DOWN_CONTROL_DEFAULTVAL                  0x0u
#define DV1_PORT1_LINK_DOWN_CONTROL                             0x4AFB081Cu
#define DV1_PORT1_LINK_DOWN_CONTROL_FIELDNUM                    3u
#define DV1_PORT1_LINK_DOWN_CONTROL_DEFAULTVAL                  0x0u
#define DV1_PORT2_LINK_DOWN_CONTROL                             0x4AFB101Cu
#define DV1_PORT2_LINK_DOWN_CONTROL_FIELDNUM                    3u
#define DV1_PORT2_LINK_DOWN_CONTROL_DEFAULTVAL                  0x0u
#define DV1_PORT3_LINK_DOWN_CONTROL                             0x4AFB181Cu
#define DV1_PORT3_LINK_DOWN_CONTROL_FIELDNUM                    3u
#define DV1_PORT3_LINK_DOWN_CONTROL_DEFAULTVAL                  0x0u
#define DV1_PORT4_LINK_DOWN_CONTROL                             0x4AFB201Cu
#define DV1_PORT4_LINK_DOWN_CONTROL_FIELDNUM                    3u
#define DV1_PORT4_LINK_DOWN_CONTROL_DEFAULTVAL                  0x0u
#define DV1_PORT5_LINK_DOWN_CONTROL                             0x4AFB281Cu
#define DV1_PORT5_LINK_DOWN_CONTROL_FIELDNUM                    3u
#define DV1_PORT5_LINK_DOWN_CONTROL_DEFAULTVAL                  0x0u
#define DV1_PORT6_LINK_DOWN_CONTROL                             0x4AFB301Cu
#define DV1_PORT6_LINK_DOWN_CONTROL_FIELDNUM                    3u
#define DV1_PORT6_LINK_DOWN_CONTROL_DEFAULTVAL                  0x0u
#define DV1_PORT7_LINK_DOWN_CONTROL                             0x4AFB381Cu
#define DV1_PORT7_LINK_DOWN_CONTROL_FIELDNUM                    3u
#define DV1_PORT7_LINK_DOWN_CONTROL_DEFAULTVAL                  0x0u
#define DV1_PORT8_LINK_DOWN_CONTROL                             0x4AFB401Cu
#define DV1_PORT8_LINK_DOWN_CONTROL_FIELDNUM                    3u
#define DV1_PORT8_LINK_DOWN_CONTROL_DEFAULTVAL                  0x0u
#define DV1_PORT9_LINK_DOWN_CONTROL                             0x4AFB481Cu
#define DV1_PORT9_LINK_DOWN_CONTROL_FIELDNUM                    3u
#define DV1_PORT9_LINK_DOWN_CONTROL_DEFAULTVAL                  0x0u
#define DV1_PORT10_LINK_DOWN_CONTROL                            0x4AFB501Cu
#define DV1_PORT10_LINK_DOWN_CONTROL_FIELDNUM                   3u
#define DV1_PORT10_LINK_DOWN_CONTROL_DEFAULTVAL                 0x0u
#define DV1_PORT11_LINK_DOWN_CONTROL                            0x4AFB581Cu
#define DV1_PORT11_LINK_DOWN_CONTROL_FIELDNUM                   3u
#define DV1_PORT11_LINK_DOWN_CONTROL_DEFAULTVAL                 0x0u
#define DV1_PORT12_LINK_DOWN_CONTROL                            0x4AFB601Cu
#define DV1_PORT12_LINK_DOWN_CONTROL_FIELDNUM                   3u
#define DV1_PORT12_LINK_DOWN_CONTROL_DEFAULTVAL                 0x0u
#define DV1_PORT13_LINK_DOWN_CONTROL                            0x4AFB681Cu
#define DV1_PORT13_LINK_DOWN_CONTROL_FIELDNUM                   3u
#define DV1_PORT13_LINK_DOWN_CONTROL_DEFAULTVAL                 0x0u
#define DV1_PORT14_LINK_DOWN_CONTROL                            0x4AFB701Cu
#define DV1_PORT14_LINK_DOWN_CONTROL_FIELDNUM                   3u
#define DV1_PORT14_LINK_DOWN_CONTROL_DEFAULTVAL                 0x0u
#define DV1_PORT15_LINK_DOWN_CONTROL                            0x4AFB781Cu
#define DV1_PORT15_LINK_DOWN_CONTROL_FIELDNUM                   3u
#define DV1_PORT15_LINK_DOWN_CONTROL_DEFAULTVAL                 0x0u
#define DV1_PORT0_EEE_PORT_DMY0                                 0x4AFB0020u
#define DV1_PORT0_EEE_PORT_DMY0_FIELDNUM                        1u
#define DV1_PORT0_EEE_PORT_DMY0_DEFAULTVAL                      0x0u
#define DV1_PORT1_EEE_PORT_DMY0                                 0x4AFB0820u
#define DV1_PORT1_EEE_PORT_DMY0_FIELDNUM                        1u
#define DV1_PORT1_EEE_PORT_DMY0_DEFAULTVAL                      0x0u
#define DV1_PORT2_EEE_PORT_DMY0                                 0x4AFB1020u
#define DV1_PORT2_EEE_PORT_DMY0_FIELDNUM                        1u
#define DV1_PORT2_EEE_PORT_DMY0_DEFAULTVAL                      0x0u
#define DV1_PORT3_EEE_PORT_DMY0                                 0x4AFB1820u
#define DV1_PORT3_EEE_PORT_DMY0_FIELDNUM                        1u
#define DV1_PORT3_EEE_PORT_DMY0_DEFAULTVAL                      0x0u
#define DV1_PORT4_EEE_PORT_DMY0                                 0x4AFB2020u
#define DV1_PORT4_EEE_PORT_DMY0_FIELDNUM                        1u
#define DV1_PORT4_EEE_PORT_DMY0_DEFAULTVAL                      0x0u
#define DV1_PORT5_EEE_PORT_DMY0                                 0x4AFB2820u
#define DV1_PORT5_EEE_PORT_DMY0_FIELDNUM                        1u
#define DV1_PORT5_EEE_PORT_DMY0_DEFAULTVAL                      0x0u
#define DV1_PORT6_EEE_PORT_DMY0                                 0x4AFB3020u
#define DV1_PORT6_EEE_PORT_DMY0_FIELDNUM                        1u
#define DV1_PORT6_EEE_PORT_DMY0_DEFAULTVAL                      0x0u
#define DV1_PORT7_EEE_PORT_DMY0                                 0x4AFB3820u
#define DV1_PORT7_EEE_PORT_DMY0_FIELDNUM                        1u
#define DV1_PORT7_EEE_PORT_DMY0_DEFAULTVAL                      0x0u
#define DV1_PORT8_EEE_PORT_DMY0                                 0x4AFB4020u
#define DV1_PORT8_EEE_PORT_DMY0_FIELDNUM                        1u
#define DV1_PORT8_EEE_PORT_DMY0_DEFAULTVAL                      0x0u
#define DV1_PORT9_EEE_PORT_DMY0                                 0x4AFB4820u
#define DV1_PORT9_EEE_PORT_DMY0_FIELDNUM                        1u
#define DV1_PORT9_EEE_PORT_DMY0_DEFAULTVAL                      0x0u
#define DV1_PORT10_EEE_PORT_DMY0                                0x4AFB5020u
#define DV1_PORT10_EEE_PORT_DMY0_FIELDNUM                       1u
#define DV1_PORT10_EEE_PORT_DMY0_DEFAULTVAL                     0x0u
#define DV1_PORT11_EEE_PORT_DMY0                                0x4AFB5820u
#define DV1_PORT11_EEE_PORT_DMY0_FIELDNUM                       1u
#define DV1_PORT11_EEE_PORT_DMY0_DEFAULTVAL                     0x0u
#define DV1_PORT12_EEE_PORT_DMY0                                0x4AFB6020u
#define DV1_PORT12_EEE_PORT_DMY0_FIELDNUM                       1u
#define DV1_PORT12_EEE_PORT_DMY0_DEFAULTVAL                     0x0u
#define DV1_PORT13_EEE_PORT_DMY0                                0x4AFB6820u
#define DV1_PORT13_EEE_PORT_DMY0_FIELDNUM                       1u
#define DV1_PORT13_EEE_PORT_DMY0_DEFAULTVAL                     0x0u
#define DV1_PORT14_EEE_PORT_DMY0                                0x4AFB7020u
#define DV1_PORT14_EEE_PORT_DMY0_FIELDNUM                       1u
#define DV1_PORT14_EEE_PORT_DMY0_DEFAULTVAL                     0x0u
#define DV1_PORT15_EEE_PORT_DMY0                                0x4AFB7820u
#define DV1_PORT15_EEE_PORT_DMY0_FIELDNUM                       1u
#define DV1_PORT15_EEE_PORT_DMY0_DEFAULTVAL                     0x0u
#define DV1_PORT0_EEE_PORT_DMY1                                 0x4AFB0024u
#define DV1_PORT0_EEE_PORT_DMY1_FIELDNUM                        1u
#define DV1_PORT0_EEE_PORT_DMY1_DEFAULTVAL                      0x0u
#define DV1_PORT1_EEE_PORT_DMY1                                 0x4AFB0824u
#define DV1_PORT1_EEE_PORT_DMY1_FIELDNUM                        1u
#define DV1_PORT1_EEE_PORT_DMY1_DEFAULTVAL                      0x0u
#define DV1_PORT2_EEE_PORT_DMY1                                 0x4AFB1024u
#define DV1_PORT2_EEE_PORT_DMY1_FIELDNUM                        1u
#define DV1_PORT2_EEE_PORT_DMY1_DEFAULTVAL                      0x0u
#define DV1_PORT3_EEE_PORT_DMY1                                 0x4AFB1824u
#define DV1_PORT3_EEE_PORT_DMY1_FIELDNUM                        1u
#define DV1_PORT3_EEE_PORT_DMY1_DEFAULTVAL                      0x0u
#define DV1_PORT4_EEE_PORT_DMY1                                 0x4AFB2024u
#define DV1_PORT4_EEE_PORT_DMY1_FIELDNUM                        1u
#define DV1_PORT4_EEE_PORT_DMY1_DEFAULTVAL                      0x0u
#define DV1_PORT5_EEE_PORT_DMY1                                 0x4AFB2824u
#define DV1_PORT5_EEE_PORT_DMY1_FIELDNUM                        1u
#define DV1_PORT5_EEE_PORT_DMY1_DEFAULTVAL                      0x0u
#define DV1_PORT6_EEE_PORT_DMY1                                 0x4AFB3024u
#define DV1_PORT6_EEE_PORT_DMY1_FIELDNUM                        1u
#define DV1_PORT6_EEE_PORT_DMY1_DEFAULTVAL                      0x0u
#define DV1_PORT7_EEE_PORT_DMY1                                 0x4AFB3824u
#define DV1_PORT7_EEE_PORT_DMY1_FIELDNUM                        1u
#define DV1_PORT7_EEE_PORT_DMY1_DEFAULTVAL                      0x0u
#define DV1_PORT8_EEE_PORT_DMY1                                 0x4AFB4024u
#define DV1_PORT8_EEE_PORT_DMY1_FIELDNUM                        1u
#define DV1_PORT8_EEE_PORT_DMY1_DEFAULTVAL                      0x0u
#define DV1_PORT9_EEE_PORT_DMY1                                 0x4AFB4824u
#define DV1_PORT9_EEE_PORT_DMY1_FIELDNUM                        1u
#define DV1_PORT9_EEE_PORT_DMY1_DEFAULTVAL                      0x0u
#define DV1_PORT10_EEE_PORT_DMY1                                0x4AFB5024u
#define DV1_PORT10_EEE_PORT_DMY1_FIELDNUM                       1u
#define DV1_PORT10_EEE_PORT_DMY1_DEFAULTVAL                     0x0u
#define DV1_PORT11_EEE_PORT_DMY1                                0x4AFB5824u
#define DV1_PORT11_EEE_PORT_DMY1_FIELDNUM                       1u
#define DV1_PORT11_EEE_PORT_DMY1_DEFAULTVAL                     0x0u
#define DV1_PORT12_EEE_PORT_DMY1                                0x4AFB6024u
#define DV1_PORT12_EEE_PORT_DMY1_FIELDNUM                       1u
#define DV1_PORT12_EEE_PORT_DMY1_DEFAULTVAL                     0x0u
#define DV1_PORT13_EEE_PORT_DMY1                                0x4AFB6824u
#define DV1_PORT13_EEE_PORT_DMY1_FIELDNUM                       1u
#define DV1_PORT13_EEE_PORT_DMY1_DEFAULTVAL                     0x0u
#define DV1_PORT14_EEE_PORT_DMY1                                0x4AFB7024u
#define DV1_PORT14_EEE_PORT_DMY1_FIELDNUM                       1u
#define DV1_PORT14_EEE_PORT_DMY1_DEFAULTVAL                     0x0u
#define DV1_PORT15_EEE_PORT_DMY1                                0x4AFB7824u
#define DV1_PORT15_EEE_PORT_DMY1_FIELDNUM                       1u
#define DV1_PORT15_EEE_PORT_DMY1_DEFAULTVAL                     0x0u
#define DV1_PORT0_EEE_PORT_DMY2                                 0x4AFB0028u
#define DV1_PORT0_EEE_PORT_DMY2_FIELDNUM                        1u
#define DV1_PORT0_EEE_PORT_DMY2_DEFAULTVAL                      0x0u
#define DV1_PORT1_EEE_PORT_DMY2                                 0x4AFB0828u
#define DV1_PORT1_EEE_PORT_DMY2_FIELDNUM                        1u
#define DV1_PORT1_EEE_PORT_DMY2_DEFAULTVAL                      0x0u
#define DV1_PORT2_EEE_PORT_DMY2                                 0x4AFB1028u
#define DV1_PORT2_EEE_PORT_DMY2_FIELDNUM                        1u
#define DV1_PORT2_EEE_PORT_DMY2_DEFAULTVAL                      0x0u
#define DV1_PORT3_EEE_PORT_DMY2                                 0x4AFB1828u
#define DV1_PORT3_EEE_PORT_DMY2_FIELDNUM                        1u
#define DV1_PORT3_EEE_PORT_DMY2_DEFAULTVAL                      0x0u
#define DV1_PORT4_EEE_PORT_DMY2                                 0x4AFB2028u
#define DV1_PORT4_EEE_PORT_DMY2_FIELDNUM                        1u
#define DV1_PORT4_EEE_PORT_DMY2_DEFAULTVAL                      0x0u
#define DV1_PORT5_EEE_PORT_DMY2                                 0x4AFB2828u
#define DV1_PORT5_EEE_PORT_DMY2_FIELDNUM                        1u
#define DV1_PORT5_EEE_PORT_DMY2_DEFAULTVAL                      0x0u
#define DV1_PORT6_EEE_PORT_DMY2                                 0x4AFB3028u
#define DV1_PORT6_EEE_PORT_DMY2_FIELDNUM                        1u
#define DV1_PORT6_EEE_PORT_DMY2_DEFAULTVAL                      0x0u
#define DV1_PORT7_EEE_PORT_DMY2                                 0x4AFB3828u
#define DV1_PORT7_EEE_PORT_DMY2_FIELDNUM                        1u
#define DV1_PORT7_EEE_PORT_DMY2_DEFAULTVAL                      0x0u
#define DV1_PORT8_EEE_PORT_DMY2                                 0x4AFB4028u
#define DV1_PORT8_EEE_PORT_DMY2_FIELDNUM                        1u
#define DV1_PORT8_EEE_PORT_DMY2_DEFAULTVAL                      0x0u
#define DV1_PORT9_EEE_PORT_DMY2                                 0x4AFB4828u
#define DV1_PORT9_EEE_PORT_DMY2_FIELDNUM                        1u
#define DV1_PORT9_EEE_PORT_DMY2_DEFAULTVAL                      0x0u
#define DV1_PORT10_EEE_PORT_DMY2                                0x4AFB5028u
#define DV1_PORT10_EEE_PORT_DMY2_FIELDNUM                       1u
#define DV1_PORT10_EEE_PORT_DMY2_DEFAULTVAL                     0x0u
#define DV1_PORT11_EEE_PORT_DMY2                                0x4AFB5828u
#define DV1_PORT11_EEE_PORT_DMY2_FIELDNUM                       1u
#define DV1_PORT11_EEE_PORT_DMY2_DEFAULTVAL                     0x0u
#define DV1_PORT12_EEE_PORT_DMY2                                0x4AFB6028u
#define DV1_PORT12_EEE_PORT_DMY2_FIELDNUM                       1u
#define DV1_PORT12_EEE_PORT_DMY2_DEFAULTVAL                     0x0u
#define DV1_PORT13_EEE_PORT_DMY2                                0x4AFB6828u
#define DV1_PORT13_EEE_PORT_DMY2_FIELDNUM                       1u
#define DV1_PORT13_EEE_PORT_DMY2_DEFAULTVAL                     0x0u
#define DV1_PORT14_EEE_PORT_DMY2                                0x4AFB7028u
#define DV1_PORT14_EEE_PORT_DMY2_FIELDNUM                       1u
#define DV1_PORT14_EEE_PORT_DMY2_DEFAULTVAL                     0x0u
#define DV1_PORT15_EEE_PORT_DMY2                                0x4AFB7828u
#define DV1_PORT15_EEE_PORT_DMY2_FIELDNUM                       1u
#define DV1_PORT15_EEE_PORT_DMY2_DEFAULTVAL                     0x0u
#define DV1_PORT0_EEE_PORT_DMY3                                 0x4AFB002Cu
#define DV1_PORT0_EEE_PORT_DMY3_FIELDNUM                        1u
#define DV1_PORT0_EEE_PORT_DMY3_DEFAULTVAL                      0x0u
#define DV1_PORT1_EEE_PORT_DMY3                                 0x4AFB082Cu
#define DV1_PORT1_EEE_PORT_DMY3_FIELDNUM                        1u
#define DV1_PORT1_EEE_PORT_DMY3_DEFAULTVAL                      0x0u
#define DV1_PORT2_EEE_PORT_DMY3                                 0x4AFB102Cu
#define DV1_PORT2_EEE_PORT_DMY3_FIELDNUM                        1u
#define DV1_PORT2_EEE_PORT_DMY3_DEFAULTVAL                      0x0u
#define DV1_PORT3_EEE_PORT_DMY3                                 0x4AFB182Cu
#define DV1_PORT3_EEE_PORT_DMY3_FIELDNUM                        1u
#define DV1_PORT3_EEE_PORT_DMY3_DEFAULTVAL                      0x0u
#define DV1_PORT4_EEE_PORT_DMY3                                 0x4AFB202Cu
#define DV1_PORT4_EEE_PORT_DMY3_FIELDNUM                        1u
#define DV1_PORT4_EEE_PORT_DMY3_DEFAULTVAL                      0x0u
#define DV1_PORT5_EEE_PORT_DMY3                                 0x4AFB282Cu
#define DV1_PORT5_EEE_PORT_DMY3_FIELDNUM                        1u
#define DV1_PORT5_EEE_PORT_DMY3_DEFAULTVAL                      0x0u
#define DV1_PORT6_EEE_PORT_DMY3                                 0x4AFB302Cu
#define DV1_PORT6_EEE_PORT_DMY3_FIELDNUM                        1u
#define DV1_PORT6_EEE_PORT_DMY3_DEFAULTVAL                      0x0u
#define DV1_PORT7_EEE_PORT_DMY3                                 0x4AFB382Cu
#define DV1_PORT7_EEE_PORT_DMY3_FIELDNUM                        1u
#define DV1_PORT7_EEE_PORT_DMY3_DEFAULTVAL                      0x0u
#define DV1_PORT8_EEE_PORT_DMY3                                 0x4AFB402Cu
#define DV1_PORT8_EEE_PORT_DMY3_FIELDNUM                        1u
#define DV1_PORT8_EEE_PORT_DMY3_DEFAULTVAL                      0x0u
#define DV1_PORT9_EEE_PORT_DMY3                                 0x4AFB482Cu
#define DV1_PORT9_EEE_PORT_DMY3_FIELDNUM                        1u
#define DV1_PORT9_EEE_PORT_DMY3_DEFAULTVAL                      0x0u
#define DV1_PORT10_EEE_PORT_DMY3                                0x4AFB502Cu
#define DV1_PORT10_EEE_PORT_DMY3_FIELDNUM                       1u
#define DV1_PORT10_EEE_PORT_DMY3_DEFAULTVAL                     0x0u
#define DV1_PORT11_EEE_PORT_DMY3                                0x4AFB582Cu
#define DV1_PORT11_EEE_PORT_DMY3_FIELDNUM                       1u
#define DV1_PORT11_EEE_PORT_DMY3_DEFAULTVAL                     0x0u
#define DV1_PORT12_EEE_PORT_DMY3                                0x4AFB602Cu
#define DV1_PORT12_EEE_PORT_DMY3_FIELDNUM                       1u
#define DV1_PORT12_EEE_PORT_DMY3_DEFAULTVAL                     0x0u
#define DV1_PORT13_EEE_PORT_DMY3                                0x4AFB682Cu
#define DV1_PORT13_EEE_PORT_DMY3_FIELDNUM                       1u
#define DV1_PORT13_EEE_PORT_DMY3_DEFAULTVAL                     0x0u
#define DV1_PORT14_EEE_PORT_DMY3                                0x4AFB702Cu
#define DV1_PORT14_EEE_PORT_DMY3_FIELDNUM                       1u
#define DV1_PORT14_EEE_PORT_DMY3_DEFAULTVAL                     0x0u
#define DV1_PORT15_EEE_PORT_DMY3                                0x4AFB782Cu
#define DV1_PORT15_EEE_PORT_DMY3_FIELDNUM                       1u
#define DV1_PORT15_EEE_PORT_DMY3_DEFAULTVAL                     0x0u
#define DV1_PORT0_EEE_LP_C_AND_S_FIELD_VALUE                    0x4AFB0030u
#define DV1_PORT0_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM           3u
#define DV1_PORT0_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL         0x0u
#define DV1_PORT1_EEE_LP_C_AND_S_FIELD_VALUE                    0x4AFB0830u
#define DV1_PORT1_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM           3u
#define DV1_PORT1_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL         0x0u
#define DV1_PORT2_EEE_LP_C_AND_S_FIELD_VALUE                    0x4AFB1030u
#define DV1_PORT2_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM           3u
#define DV1_PORT2_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL         0x0u
#define DV1_PORT3_EEE_LP_C_AND_S_FIELD_VALUE                    0x4AFB1830u
#define DV1_PORT3_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM           3u
#define DV1_PORT3_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL         0x0u
#define DV1_PORT4_EEE_LP_C_AND_S_FIELD_VALUE                    0x4AFB2030u
#define DV1_PORT4_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM           3u
#define DV1_PORT4_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL         0x0u
#define DV1_PORT5_EEE_LP_C_AND_S_FIELD_VALUE                    0x4AFB2830u
#define DV1_PORT5_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM           3u
#define DV1_PORT5_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL         0x0u
#define DV1_PORT6_EEE_LP_C_AND_S_FIELD_VALUE                    0x4AFB3030u
#define DV1_PORT6_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM           3u
#define DV1_PORT6_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL         0x0u
#define DV1_PORT7_EEE_LP_C_AND_S_FIELD_VALUE                    0x4AFB3830u
#define DV1_PORT7_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM           3u
#define DV1_PORT7_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL         0x0u
#define DV1_PORT8_EEE_LP_C_AND_S_FIELD_VALUE                    0x4AFB4030u
#define DV1_PORT8_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM           3u
#define DV1_PORT8_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL         0x0u
#define DV1_PORT9_EEE_LP_C_AND_S_FIELD_VALUE                    0x4AFB4830u
#define DV1_PORT9_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM           3u
#define DV1_PORT9_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL         0x0u
#define DV1_PORT10_EEE_LP_C_AND_S_FIELD_VALUE                   0x4AFB5030u
#define DV1_PORT10_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM          3u
#define DV1_PORT10_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL        0x0u
#define DV1_PORT11_EEE_LP_C_AND_S_FIELD_VALUE                   0x4AFB5830u
#define DV1_PORT11_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM          3u
#define DV1_PORT11_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL        0x0u
#define DV1_PORT12_EEE_LP_C_AND_S_FIELD_VALUE                   0x4AFB6030u
#define DV1_PORT12_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM          3u
#define DV1_PORT12_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL        0x0u
#define DV1_PORT13_EEE_LP_C_AND_S_FIELD_VALUE                   0x4AFB6830u
#define DV1_PORT13_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM          3u
#define DV1_PORT13_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL        0x0u
#define DV1_PORT14_EEE_LP_C_AND_S_FIELD_VALUE                   0x4AFB7030u
#define DV1_PORT14_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM          3u
#define DV1_PORT14_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL        0x0u
#define DV1_PORT15_EEE_LP_C_AND_S_FIELD_VALUE                   0x4AFB7830u
#define DV1_PORT15_EEE_LP_C_AND_S_FIELD_VALUE_FIELDNUM          3u
#define DV1_PORT15_EEE_LP_C_AND_S_FIELD_VALUE_DEFAULTVAL        0x0u
#endif
#endif /* DV1_RTKAS_REG_LIST_FILE_EEE_H_ */