/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_LED_H_
#define DVA_RTKAS_REG_FIELD_FILE_LED_H_

#ifdef DVA_FILE_LED
/* File: LED */
#define DVA_LED_CONTROL0_LED_MODE_UNLOCK_LSP      30u
#define DVA_LED_CONTROL0_LED_MODE_UNLOCK_LEN      1u
#define DVA_LED_CONTROL0_LED_MODE_UNLOCK_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL0_RG_GPIO_INDIC_T1_LSP     29u
#define DVA_LED_CONTROL0_RG_GPIO_INDIC_T1_LEN     1u
#define DVA_LED_CONTROL0_RG_GPIO_INDIC_T1_TYPE    DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL0_RLDP_INDICATOR_EN_LSP    28u
#define DVA_LED_CONTROL0_RLDP_INDICATOR_EN_LEN    1u
#define DVA_LED_CONTROL0_RLDP_INDICATOR_EN_TYPE   DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL0_RLDP_BLINK_TIME_LSP      27u
#define DVA_LED_CONTROL0_RLDP_BLINK_TIME_LEN      1u
#define DVA_LED_CONTROL0_RLDP_BLINK_TIME_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL0_DIS_PWR_ON_BLINKING_LSP  26u
#define DVA_LED_CONTROL0_DIS_PWR_ON_BLINKING_LEN  1u
#define DVA_LED_CONTROL0_DIS_PWR_ON_BLINKING_TYPE DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_LED_BLINKING_TIME_LSP    25u
#define DVA_LED_CONTROL0_LED_BLINKING_TIME_LEN    1u
#define DVA_LED_CONTROL0_LED_BLINKING_TIME_TYPE   DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL0_RG_GPIO_INDIC_EN_LSP     24u
#define DVA_LED_CONTROL0_RG_GPIO_INDIC_EN_LEN     1u
#define DVA_LED_CONTROL0_RG_GPIO_INDIC_EN_TYPE    DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL0_RG_GPHY_LED1_CFG_LSP     22u
#define DVA_LED_CONTROL0_RG_GPHY_LED1_CFG_LEN     2u
#define DVA_LED_CONTROL0_RG_GPHY_LED1_CFG_TYPE    DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_GPHY_LED0_CFG_LSP     20u
#define DVA_LED_CONTROL0_RG_GPHY_LED0_CFG_LEN     2u
#define DVA_LED_CONTROL0_RG_GPHY_LED0_CFG_TYPE    DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_LED_9_CFG_LSP         18u
#define DVA_LED_CONTROL0_RG_LED_9_CFG_LEN         2u
#define DVA_LED_CONTROL0_RG_LED_9_CFG_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_LED_8_CFG_LSP         16u
#define DVA_LED_CONTROL0_RG_LED_8_CFG_LEN         2u
#define DVA_LED_CONTROL0_RG_LED_8_CFG_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_LED_7_CFG_LSP         14u
#define DVA_LED_CONTROL0_RG_LED_7_CFG_LEN         2u
#define DVA_LED_CONTROL0_RG_LED_7_CFG_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_LED_6_CFG_LSP         12u
#define DVA_LED_CONTROL0_RG_LED_6_CFG_LEN         2u
#define DVA_LED_CONTROL0_RG_LED_6_CFG_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_LED_5_CFG_LSP         10u
#define DVA_LED_CONTROL0_RG_LED_5_CFG_LEN         2u
#define DVA_LED_CONTROL0_RG_LED_5_CFG_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_LED_4_CFG_LSP         8u
#define DVA_LED_CONTROL0_RG_LED_4_CFG_LEN         2u
#define DVA_LED_CONTROL0_RG_LED_4_CFG_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_LED_3_CFG_LSP         6u
#define DVA_LED_CONTROL0_RG_LED_3_CFG_LEN         2u
#define DVA_LED_CONTROL0_RG_LED_3_CFG_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_LED_2_CFG_LSP         4u
#define DVA_LED_CONTROL0_RG_LED_2_CFG_LEN         2u
#define DVA_LED_CONTROL0_RG_LED_2_CFG_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_LED_1_CFG_LSP         2u
#define DVA_LED_CONTROL0_RG_LED_1_CFG_LEN         2u
#define DVA_LED_CONTROL0_RG_LED_1_CFG_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_LED_CONTROL0_RG_LED_0_CFG_LSP         0u
#define DVA_LED_CONTROL0_RG_LED_0_CFG_LEN         2u
#define DVA_LED_CONTROL0_RG_LED_0_CFG_TYPE        DVA_FIELD_TYPE_RWS

#define DVA_LED_CONTROL1_RG_GPHY_LED1_CTRL_LSP  11u
#define DVA_LED_CONTROL1_RG_GPHY_LED1_CTRL_LEN  1u
#define DVA_LED_CONTROL1_RG_GPHY_LED1_CTRL_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_GPHY_LED0_CTRL_LSP  10u
#define DVA_LED_CONTROL1_RG_GPHY_LED0_CTRL_LEN  1u
#define DVA_LED_CONTROL1_RG_GPHY_LED0_CTRL_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_LED_9_CTRL_LSP      9u
#define DVA_LED_CONTROL1_RG_LED_9_CTRL_LEN      1u
#define DVA_LED_CONTROL1_RG_LED_9_CTRL_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_LED_8_CTRL_LSP      8u
#define DVA_LED_CONTROL1_RG_LED_8_CTRL_LEN      1u
#define DVA_LED_CONTROL1_RG_LED_8_CTRL_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_LED_7_CTRL_LSP      7u
#define DVA_LED_CONTROL1_RG_LED_7_CTRL_LEN      1u
#define DVA_LED_CONTROL1_RG_LED_7_CTRL_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_LED_6_CTRL_LSP      6u
#define DVA_LED_CONTROL1_RG_LED_6_CTRL_LEN      1u
#define DVA_LED_CONTROL1_RG_LED_6_CTRL_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_LED_5_CTRL_LSP      5u
#define DVA_LED_CONTROL1_RG_LED_5_CTRL_LEN      1u
#define DVA_LED_CONTROL1_RG_LED_5_CTRL_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_LED_4_CTRL_LSP      4u
#define DVA_LED_CONTROL1_RG_LED_4_CTRL_LEN      1u
#define DVA_LED_CONTROL1_RG_LED_4_CTRL_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_LED_3_CTRL_LSP      3u
#define DVA_LED_CONTROL1_RG_LED_3_CTRL_LEN      1u
#define DVA_LED_CONTROL1_RG_LED_3_CTRL_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_LED_2_CTRL_LSP      2u
#define DVA_LED_CONTROL1_RG_LED_2_CTRL_LEN      1u
#define DVA_LED_CONTROL1_RG_LED_2_CTRL_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_LED_1_CTRL_LSP      1u
#define DVA_LED_CONTROL1_RG_LED_1_CTRL_LEN      1u
#define DVA_LED_CONTROL1_RG_LED_1_CTRL_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_CONTROL1_RG_LED_0_CTRL_LSP      0u
#define DVA_LED_CONTROL1_RG_LED_0_CTRL_LEN      1u
#define DVA_LED_CONTROL1_RG_LED_0_CTRL_TYPE     DVA_FIELD_TYPE_RW

#define DVA_LED_STATUS_CONTROL0_RG_LED_7_STA_LSP  28u
#define DVA_LED_STATUS_CONTROL0_RG_LED_7_STA_LEN  4u
#define DVA_LED_STATUS_CONTROL0_RG_LED_7_STA_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_STATUS_CONTROL0_RG_LED_6_STA_LSP  24u
#define DVA_LED_STATUS_CONTROL0_RG_LED_6_STA_LEN  4u
#define DVA_LED_STATUS_CONTROL0_RG_LED_6_STA_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_STATUS_CONTROL0_RG_LED_5_STA_LSP  20u
#define DVA_LED_STATUS_CONTROL0_RG_LED_5_STA_LEN  4u
#define DVA_LED_STATUS_CONTROL0_RG_LED_5_STA_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_STATUS_CONTROL0_RG_LED_4_STA_LSP  16u
#define DVA_LED_STATUS_CONTROL0_RG_LED_4_STA_LEN  4u
#define DVA_LED_STATUS_CONTROL0_RG_LED_4_STA_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_STATUS_CONTROL0_RG_LED_3_STA_LSP  12u
#define DVA_LED_STATUS_CONTROL0_RG_LED_3_STA_LEN  4u
#define DVA_LED_STATUS_CONTROL0_RG_LED_3_STA_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_STATUS_CONTROL0_RG_LED_2_STA_LSP  8u
#define DVA_LED_STATUS_CONTROL0_RG_LED_2_STA_LEN  4u
#define DVA_LED_STATUS_CONTROL0_RG_LED_2_STA_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_STATUS_CONTROL0_RG_LED_1_STA_LSP  4u
#define DVA_LED_STATUS_CONTROL0_RG_LED_1_STA_LEN  4u
#define DVA_LED_STATUS_CONTROL0_RG_LED_1_STA_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_STATUS_CONTROL0_RG_LED_0_STA_LSP  0u
#define DVA_LED_STATUS_CONTROL0_RG_LED_0_STA_LEN  4u
#define DVA_LED_STATUS_CONTROL0_RG_LED_0_STA_TYPE DVA_FIELD_TYPE_RW

#define DVA_LED_STATUS_CONTROL1_RG_GPHY_LED1_STA_LSP  12u
#define DVA_LED_STATUS_CONTROL1_RG_GPHY_LED1_STA_LEN  4u
#define DVA_LED_STATUS_CONTROL1_RG_GPHY_LED1_STA_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_STATUS_CONTROL1_RG_GPHY_LED0_STA_LSP  8u
#define DVA_LED_STATUS_CONTROL1_RG_GPHY_LED0_STA_LEN  4u
#define DVA_LED_STATUS_CONTROL1_RG_GPHY_LED0_STA_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_STATUS_CONTROL1_RG_LED_9_STA_LSP      4u
#define DVA_LED_STATUS_CONTROL1_RG_LED_9_STA_LEN      4u
#define DVA_LED_STATUS_CONTROL1_RG_LED_9_STA_TYPE     DVA_FIELD_TYPE_RW
#define DVA_LED_STATUS_CONTROL1_RG_LED_8_STA_LSP      0u
#define DVA_LED_STATUS_CONTROL1_RG_LED_8_STA_LEN      4u
#define DVA_LED_STATUS_CONTROL1_RG_LED_8_STA_TYPE     DVA_FIELD_TYPE_RW

#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC5_CFG_LSP  10u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC5_CFG_LEN  2u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC5_CFG_TYPE DVA_FIELD_TYPE_RWS
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC4_CFG_LSP  8u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC4_CFG_LEN  2u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC4_CFG_TYPE DVA_FIELD_TYPE_RWS
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC3_CFG_LSP  6u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC3_CFG_LEN  2u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC3_CFG_TYPE DVA_FIELD_TYPE_RWS
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC2_CFG_LSP  4u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC2_CFG_LEN  2u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC2_CFG_TYPE DVA_FIELD_TYPE_RWS
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC1_CFG_LSP  2u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC1_CFG_LEN  2u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC1_CFG_TYPE DVA_FIELD_TYPE_RWS
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC0_CFG_LSP  0u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC0_CFG_LEN  2u
#define DVA_LED_INDICATOR_CONTROL0_RG_LED_INDIC0_CFG_TYPE DVA_FIELD_TYPE_RWS

#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC5_CTRL_LSP  5u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC5_CTRL_LEN  1u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC5_CTRL_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC4_CTRL_LSP  4u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC4_CTRL_LEN  1u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC4_CTRL_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC3_CTRL_LSP  3u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC3_CTRL_LEN  1u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC3_CTRL_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC2_CTRL_LSP  2u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC2_CTRL_LEN  1u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC2_CTRL_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC1_CTRL_LSP  1u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC1_CTRL_LEN  1u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC1_CTRL_TYPE DVA_FIELD_TYPE_RW
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC0_CTRL_LSP  0u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC0_CTRL_LEN  1u
#define DVA_LED_INDICATOR_CONTROL1_RG_LED_INDIC0_CTRL_TYPE DVA_FIELD_TYPE_RW

#define DVA_LED_INDICATOR_CONTROL2_RG_LED_INDIC0_MASK_LSP  0u
#define DVA_LED_INDICATOR_CONTROL2_RG_LED_INDIC0_MASK_LEN  16u
#define DVA_LED_INDICATOR_CONTROL2_RG_LED_INDIC0_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LED_INDICATOR_CONTROL3_RG_LED_INDIC1_MASK_LSP  0u
#define DVA_LED_INDICATOR_CONTROL3_RG_LED_INDIC1_MASK_LEN  16u
#define DVA_LED_INDICATOR_CONTROL3_RG_LED_INDIC1_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LED_INDICATOR_CONTROL4_RG_LED_INDIC2_MASK_LSP  0u
#define DVA_LED_INDICATOR_CONTROL4_RG_LED_INDIC2_MASK_LEN  16u
#define DVA_LED_INDICATOR_CONTROL4_RG_LED_INDIC2_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LED_INDICATOR_CONTROL5_RG_LED_INDIC3_MASK_LSP  0u
#define DVA_LED_INDICATOR_CONTROL5_RG_LED_INDIC3_MASK_LEN  16u
#define DVA_LED_INDICATOR_CONTROL5_RG_LED_INDIC3_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LED_INDICATOR_CONTROL6_RG_LED_INDIC4_MASK_LSP  0u
#define DVA_LED_INDICATOR_CONTROL6_RG_LED_INDIC4_MASK_LEN  16u
#define DVA_LED_INDICATOR_CONTROL6_RG_LED_INDIC4_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LED_INDICATOR_CONTROL7_RG_LED_INDIC5_MASK_LSP  0u
#define DVA_LED_INDICATOR_CONTROL7_RG_LED_INDIC5_MASK_LEN  16u
#define DVA_LED_INDICATOR_CONTROL7_RG_LED_INDIC5_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_FUSA_PG_LOCK_DMY_LED_FUSA_PG_LOCK_DMY_LED_LSP  0u
#define DVA_FUSA_PG_LOCK_DMY_LED_FUSA_PG_LOCK_DMY_LED_LEN  1u
#define DVA_FUSA_PG_LOCK_DMY_LED_FUSA_PG_LOCK_DMY_LED_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_LED_H_ */