/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_AFE_MISC_H_
#define DVA_RTKAS_REG_FIELD_FILE_AFE_MISC_H_

#ifdef DVA_FILE_AFE_MISC
/* File: I2C */
#define DVA_AFE_CENTER_REG_0_REG_CEN0_L_LSP  0u
#define DVA_AFE_CENTER_REG_0_REG_CEN0_L_LEN  16u
#define DVA_AFE_CENTER_REG_0_REG_CEN0_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_CENTER_REG_1_REG_CEN1_L_LSP  0u
#define DVA_AFE_CENTER_REG_1_REG_CEN1_L_LEN  16u
#define DVA_AFE_CENTER_REG_1_REG_CEN1_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_CENTER_REG_2_REG_CEN2_L_LSP  0u
#define DVA_AFE_CENTER_REG_2_REG_CEN2_L_LEN  16u
#define DVA_AFE_CENTER_REG_2_RTT_L_LSP       3u
#define DVA_AFE_CENTER_REG_2_RTT_L_LEN       5u
#define DVA_AFE_CENTER_REG_2_REG_CEN2_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_0_REG0_L_LSP  0u
#define DVA_AFE_REG_0_REG0_L_LEN  16u
#define DVA_AFE_REG_0_REG0_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_1_REG1_L_LSP        0u
#define DVA_AFE_REG_1_REG1_L_LEN        16u
#define DVA_AFE_REG_1_REGEN_CK66M_L_LSP 15u
#define DVA_AFE_REG_1_REGEN_CK66M_L_LEN 1u
#define DVA_AFE_REG_1_REG1_L_TYPE       DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_2_REG2_L_LSP  0u
#define DVA_AFE_REG_2_REG2_L_LEN  16u
#define DVA_AFE_REG_2_REG2_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_3_REG3_L_LSP  0u
#define DVA_AFE_REG_3_REG3_L_LEN  16u
#define DVA_AFE_REG_3_REG3_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_4_REG4_L_LSP  0u
#define DVA_AFE_REG_4_REG4_L_LEN  16u
#define DVA_AFE_REG_4_REG4_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_5_REG5_L_LSP          0u
#define DVA_AFE_REG_5_REG5_L_LEN          16u
#define DVA_AFE_REG_5_H750M_L125M_SEL_LSP 0u
#define DVA_AFE_REG_5_H750M_L125M_SEL_LEN 6u
#define DVA_AFE_REG_5_HCKR_LCKT_SEL_LSP   6u
#define DVA_AFE_REG_5_HCKR_LCKT_SEL_LEN   6u
#define DVA_AFE_REG_5_CKTEST_PI_SEL_L_LSP 12u
#define DVA_AFE_REG_5_CKTEST_PI_SEL_L_LEN 2u
#define DVA_AFE_REG_5_REG5_L_TYPE         DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_6_REG6_L_LSP            0u
#define DVA_AFE_REG_6_REG6_L_LEN            16u
#define DVA_AFE_REG_6_REG_EN_JTTEST_OUT_LSP 8u
#define DVA_AFE_REG_6_REG_EN_JTTEST_OUT_LEN 5u
#define DVA_AFE_REG_6_REG6_L_TYPE           DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_7_REG7_L_LSP         0u
#define DVA_AFE_REG_7_REG7_L_LEN         16u
#define DVA_AFE_REG_7_REG_CKTEST_SEL_LSP 0u
#define DVA_AFE_REG_7_REG_CKTEST_SEL_LEN 1u
#define DVA_AFE_REG_7_REG7_L_TYPE        DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_8_REG8_L_LSP  0u
#define DVA_AFE_REG_8_REG8_L_LEN  16u
#define DVA_AFE_REG_8_REG8_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_9_REG9_L_LSP            0u
#define DVA_AFE_REG_9_REG9_L_LEN            16u
#define DVA_AFE_REG_9_REG_CK66MSEL_LSP      1u
#define DVA_AFE_REG_9_REG_CK66MSEL_LEN      2u
#define DVA_AFE_REG_9_REG_EN_TEST_OUT_L_LSP 12u
#define DVA_AFE_REG_9_REG_EN_TEST_OUT_L_LEN 1u
#define DVA_AFE_REG_9_REG9_L_TYPE           DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_10_REG10_L_LSP  0u
#define DVA_AFE_REG_10_REG10_L_LEN  16u
#define DVA_AFE_REG_10_REG10_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_11_REG11_L_LSP       0u
#define DVA_AFE_REG_11_REG11_L_LEN       16u
#define DVA_AFE_REG_11_REG_CKR_SEL_L_LSP 0u
#define DVA_AFE_REG_11_REG_CKR_SEL_L_LEN 8u
#define DVA_AFE_REG_11_REG11_L_TYPE      DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_12_REG12_L_LSP  0u
#define DVA_AFE_REG_12_REG12_L_LEN  16u
#define DVA_AFE_REG_12_REG12_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_13_REG13_L_LSP  0u
#define DVA_AFE_REG_13_REG13_L_LEN  16u
#define DVA_AFE_REG_13_REG13_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_14_REG14_L_LSP  0u
#define DVA_AFE_REG_14_REG14_L_LEN  16u
#define DVA_AFE_REG_14_REG14_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_15_REG15_L_LSP  0u
#define DVA_AFE_REG_15_REG15_L_LEN  16u
#define DVA_AFE_REG_15_REG15_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_16_REG16_L_LSP  0u
#define DVA_AFE_REG_16_REG16_L_LEN  16u
#define DVA_AFE_REG_16_REG16_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_17_REG17_L_LSP  0u
#define DVA_AFE_REG_17_REG17_L_LEN  16u
#define DVA_AFE_REG_17_REG17_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_18_REG18_L_LSP     0u
#define DVA_AFE_REG_18_REG18_L_LEN     16u
#define DVA_AFE_REG_18_POW_CKSEL_L_LSP 7u
#define DVA_AFE_REG_18_POW_CKSEL_L_LEN 6u
#define DVA_AFE_REG_18_REG18_L_TYPE    DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_19_REG19_L_LSP  0u
#define DVA_AFE_REG_19_REG19_L_LEN  16u
#define DVA_AFE_REG_19_REG19_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_20_REG20_L_LSP  0u
#define DVA_AFE_REG_20_REG20_L_LEN  16u
#define DVA_AFE_REG_20_REG20_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_21_REG21_L_LSP  0u
#define DVA_AFE_REG_21_REG21_L_LEN  16u
#define DVA_AFE_REG_21_REG21_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_22_REG22_L_LSP  0u
#define DVA_AFE_REG_22_REG22_L_LEN  16u
#define DVA_AFE_REG_22_REG22_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_23_REG23_L_LSP  0u
#define DVA_AFE_REG_23_REG23_L_LEN  16u
#define DVA_AFE_REG_23_REG23_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_24_REG24_L_LSP  0u
#define DVA_AFE_REG_24_REG24_L_LEN  16u
#define DVA_AFE_REG_24_REG24_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_25_REG25_L_LSP  0u
#define DVA_AFE_REG_25_REG25_L_LEN  16u
#define DVA_AFE_REG_25_REG25_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_26_REG26_L_LSP  0u
#define DVA_AFE_REG_26_REG26_L_LEN  16u
#define DVA_AFE_REG_26_REG26_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_27_REG27_L_LSP  0u
#define DVA_AFE_REG_27_REG27_L_LEN  16u
#define DVA_AFE_REG_27_REG27_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_28_REG28_L_LSP  0u
#define DVA_AFE_REG_28_REG28_L_LEN  16u
#define DVA_AFE_REG_28_REG28_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_29_REG29_L_LSP  0u
#define DVA_AFE_REG_29_REG29_L_LEN  16u
#define DVA_AFE_REG_29_REG29_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_30_REG30_L_LSP       0u
#define DVA_AFE_REG_30_REG30_L_LEN       16u
#define DVA_AFE_REG_30_JETTEST_OUT_L_LSP 15u
#define DVA_AFE_REG_30_JETTEST_OUT_L_LEN 1u
#define DVA_AFE_REG_30_REG30_L_TYPE      DVA_FIELD_TYPE_RW

#define DVA_AFE_REG_31_REG31_L_LSP  0u
#define DVA_AFE_REG_31_REG31_L_LEN  16u
#define DVA_AFE_REG_31_REG31_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG0_PLLSCPU_REG0_PLLSCPU_L_LSP  0u
#define DVA_AFE_REG0_PLLSCPU_REG0_PLLSCPU_L_LEN  16u
#define DVA_AFE_REG0_PLLSCPU_REG0_PLLSCPU_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_REG1_PLLSCPU_REG1_PLLSCPU_L_LSP  0u
#define DVA_AFE_REG1_PLLSCPU_REG1_PLLSCPU_L_LEN  16u
#define DVA_AFE_REG1_PLLSCPU_REG1_PLLSCPU_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_EN_DCO_EN_DCO_L_LSP  0u
#define DVA_AFE_EN_DCO_EN_DCO_L_LEN  1u
#define DVA_AFE_EN_DCO_EN_DCO_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_EN_GDAC_IBX_CEN_EN_GDAC_IBX_CEN_L_LSP  0u
#define DVA_AFE_EN_GDAC_IBX_CEN_EN_GDAC_IBX_CEN_L_LEN  1u
#define DVA_AFE_EN_GDAC_IBX_CEN_EN_GDAC_IBX_CEN_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_LVLDO_FE_POW_LVLDO_FE_L_LSP  0u
#define DVA_AFE_LVLDO_FE_POW_LVLDO_FE_L_LEN  1u
#define DVA_AFE_LVLDO_FE_POW_LVLDO_FE_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_POW_FE_POW_FE_L_LSP  0u
#define DVA_AFE_POW_FE_POW_FE_L_LEN  1u
#define DVA_AFE_POW_FE_POW_FE_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLLSCPU_SPD_DOWN_REG_PLLSCPU_SPD_DOWN_L_LSP  0u
#define DVA_PLLSCPU_SPD_DOWN_REG_PLLSCPU_SPD_DOWN_L_LEN  2u
#define DVA_PLLSCPU_SPD_DOWN_REG_PLLSCPU_SPD_DOWN_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_AFE_R_CALI_R_CALI_EN_LSP  0u
#define DVA_AFE_R_CALI_R_CALI_EN_LEN  1u
#define DVA_AFE_R_CALI_R_CALI_EN_TYPE DVA_FIELD_TYPE_RO

#define DVA_PLL_PARAM_0_T_FASTON_LDO_RDY_LSP  0u
#define DVA_PLL_PARAM_0_T_FASTON_LDO_RDY_LEN  16u
#define DVA_PLL_PARAM_0_T_FASTON_LDO_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_1_T_FASTON_LDO_HIGH_LSP  0u
#define DVA_PLL_PARAM_1_T_FASTON_LDO_HIGH_LEN  16u
#define DVA_PLL_PARAM_1_T_FASTON_LDO_HIGH_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_2_T_RSTB_PLL_RDY_LSP  0u
#define DVA_PLL_PARAM_2_T_RSTB_PLL_RDY_LEN  16u
#define DVA_PLL_PARAM_2_T_RSTB_PLL_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_3_T_FASTLOCK_CCO_RDY_LSP  0u
#define DVA_PLL_PARAM_3_T_FASTLOCK_CCO_RDY_LEN  16u
#define DVA_PLL_PARAM_3_T_FASTLOCK_CCO_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_4_T_FASTLOCK_CCO_HIGH_LSP  0u
#define DVA_PLL_PARAM_4_T_FASTLOCK_CCO_HIGH_LEN  16u
#define DVA_PLL_PARAM_4_T_FASTLOCK_CCO_HIGH_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_5_T_ICP_SW_RDY_LSP  0u
#define DVA_PLL_PARAM_5_T_ICP_SW_RDY_LEN  16u
#define DVA_PLL_PARAM_5_T_ICP_SW_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_6_T_VC_FORCE_RDY_LSP  0u
#define DVA_PLL_PARAM_6_T_VC_FORCE_RDY_LEN  16u
#define DVA_PLL_PARAM_6_T_VC_FORCE_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_7_T_VC_FORCE_HIGH_LSP  0u
#define DVA_PLL_PARAM_7_T_VC_FORCE_HIGH_LEN  16u
#define DVA_PLL_PARAM_7_T_VC_FORCE_HIGH_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_8_T_RSTB_DLL_RDY_LSP  0u
#define DVA_PLL_PARAM_8_T_RSTB_DLL_RDY_LEN  16u
#define DVA_PLL_PARAM_8_T_RSTB_DLL_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_9_T_START_DUTY_CONSTRAINT_RDY_LSP  0u
#define DVA_PLL_PARAM_9_T_START_DUTY_CONSTRAINT_RDY_LEN  16u
#define DVA_PLL_PARAM_9_T_START_DUTY_CONSTRAINT_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_10_T_POW_PI_RDY_LSP  0u
#define DVA_PLL_PARAM_10_T_POW_PI_RDY_LEN  16u
#define DVA_PLL_PARAM_10_T_POW_PI_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_11_T_PI_OUT_EN_RDY_LSP  0u
#define DVA_PLL_PARAM_11_T_PI_OUT_EN_RDY_LEN  16u
#define DVA_PLL_PARAM_11_T_PI_OUT_EN_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_12_T_RSTB_SSCPS_RDY_LSP  0u
#define DVA_PLL_PARAM_12_T_RSTB_SSCPS_RDY_LEN  16u
#define DVA_PLL_PARAM_12_T_RSTB_SSCPS_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_PARAM_13_T_ANARSTB_RDY_LSP  0u
#define DVA_PLL_PARAM_13_T_ANARSTB_RDY_LEN  16u
#define DVA_PLL_PARAM_13_T_ANARSTB_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_0_REG_POW_MCK_L_LSP  0u
#define DVA_REG_CONTROL_PLL_0_REG_POW_MCK_L_LEN  1u
#define DVA_REG_CONTROL_PLL_0_REG_POW_MCK_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_1_REG_FASTON_LDO_LSP  0u
#define DVA_REG_CONTROL_PLL_1_REG_FASTON_LDO_LEN  1u
#define DVA_REG_CONTROL_PLL_1_REG_FASTON_LDO_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_2_REG_RSTB_PLL_LSP  0u
#define DVA_REG_CONTROL_PLL_2_REG_RSTB_PLL_LEN  1u
#define DVA_REG_CONTROL_PLL_2_REG_RSTB_PLL_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_3_REG_FASTLOCK_CCO_LSP  0u
#define DVA_REG_CONTROL_PLL_3_REG_FASTLOCK_CCO_LEN  1u
#define DVA_REG_CONTROL_PLL_3_REG_FASTLOCK_CCO_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_4_REG_ICP_SW_LSP  0u
#define DVA_REG_CONTROL_PLL_4_REG_ICP_SW_LEN  1u
#define DVA_REG_CONTROL_PLL_4_REG_ICP_SW_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_5_REG_VC_FORCE_LSP  0u
#define DVA_REG_CONTROL_PLL_5_REG_VC_FORCE_LEN  1u
#define DVA_REG_CONTROL_PLL_5_REG_VC_FORCE_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_6_REG_RSTB_DLL_LSP  0u
#define DVA_REG_CONTROL_PLL_6_REG_RSTB_DLL_LEN  1u
#define DVA_REG_CONTROL_PLL_6_REG_RSTB_DLL_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_7_REG_START_DUTY_CONSTRAINT_LSP  0u
#define DVA_REG_CONTROL_PLL_7_REG_START_DUTY_CONSTRAINT_LEN  1u
#define DVA_REG_CONTROL_PLL_7_REG_START_DUTY_CONSTRAINT_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_8_REG_POW_PI_LSP  0u
#define DVA_REG_CONTROL_PLL_8_REG_POW_PI_LEN  6u
#define DVA_REG_CONTROL_PLL_8_REG_POW_PI_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_9_REG_PI_OUT_EN_LSP  0u
#define DVA_REG_CONTROL_PLL_9_REG_PI_OUT_EN_LEN  2u
#define DVA_REG_CONTROL_PLL_9_REG_PI_OUT_EN_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_10_REG_RSTB_SSCPS_LSP  0u
#define DVA_REG_CONTROL_PLL_10_REG_RSTB_SSCPS_LEN  1u
#define DVA_REG_CONTROL_PLL_10_REG_RSTB_SSCPS_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_11_REG_ANARSTB_RX_L_LSP  0u
#define DVA_REG_CONTROL_PLL_11_REG_ANARSTB_RX_L_LEN  10u
#define DVA_REG_CONTROL_PLL_11_REG_ANARSTB_RX_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_12_REG_ANARSTB_PTP_L_LSP  0u
#define DVA_REG_CONTROL_PLL_12_REG_ANARSTB_PTP_L_LEN  10u
#define DVA_REG_CONTROL_PLL_12_REG_ANARSTB_PTP_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_13_REG_ANARSTB_SYS_L_LSP  0u
#define DVA_REG_CONTROL_PLL_13_REG_ANARSTB_SYS_L_LEN  10u
#define DVA_REG_CONTROL_PLL_13_REG_ANARSTB_SYS_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_14_REG_ANARSTB_RMII_L_LSP  0u
#define DVA_REG_CONTROL_PLL_14_REG_ANARSTB_RMII_L_LEN  3u
#define DVA_REG_CONTROL_PLL_14_REG_ANARSTB_RMII_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_15_REG_TRIG_LSP  0u
#define DVA_REG_CONTROL_PLL_15_REG_TRIG_LEN  1u
#define DVA_REG_CONTROL_PLL_15_REG_TRIG_TYPE DVA_FIELD_TYPE_RW

#define DVA_REG_CONTROL_PLL_16_SW_FULL_CTRL_LSP  0u
#define DVA_REG_CONTROL_PLL_16_SW_FULL_CTRL_LEN  1u
#define DVA_REG_CONTROL_PLL_16_SW_FULL_CTRL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PLL_CPU_DIVN_PLL_CPU_DIVN_L_LSP  0u
#define DVA_PLL_CPU_DIVN_PLL_CPU_DIVN_L_LEN  5u
#define DVA_PLL_CPU_DIVN_PLL_CPU_DIVN_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_REF_CKUPS_REF_CKUPS_L_LSP  0u
#define DVA_REF_CKUPS_REF_CKUPS_L_LEN  5u
#define DVA_REF_CKUPS_REF_CKUPS_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_PLL_ON_TRIG_CPU_PLL_POWER_ON_TRIG_LSP  0u
#define DVA_CPU_PLL_ON_TRIG_CPU_PLL_POWER_ON_TRIG_LEN  1u
#define DVA_CPU_PLL_ON_TRIG_CPU_PLL_POWER_ON_TRIG_TYPE DVA_FIELD_TYPE_RWS

#define DVA_CPU_PLL_OFF_TRIG_CPU_PLL_POWER_OFF_TRIG_LSP  0u
#define DVA_CPU_PLL_OFF_TRIG_CPU_PLL_POWER_OFF_TRIG_LEN  1u
#define DVA_CPU_PLL_OFF_TRIG_CPU_PLL_POWER_OFF_TRIG_TYPE DVA_FIELD_TYPE_RWS

#define DVA_CPU_PLL_STATUS_CPU_PLL_STATUS_LSP  0u
#define DVA_CPU_PLL_STATUS_CPU_PLL_STATUS_LEN  1u
#define DVA_CPU_PLL_STATUS_CPU_PLL_STATUS_TYPE DVA_FIELD_TYPE_RO

#define DVA_CPU_PLL_PARAM_0_T_CPU_PLL_LDO_RDY_LSP  0u
#define DVA_CPU_PLL_PARAM_0_T_CPU_PLL_LDO_RDY_LEN  21u
#define DVA_CPU_PLL_PARAM_0_T_CPU_PLL_LDO_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_PLL_PARAM_1_T_RSTB_CPU_PLL_RDY_LSP  0u
#define DVA_CPU_PLL_PARAM_1_T_RSTB_CPU_PLL_RDY_LEN  21u
#define DVA_CPU_PLL_PARAM_1_T_RSTB_CPU_PLL_RDY_TYPE DVA_FIELD_TYPE_RW

#define DVA_FUSA_PG_LOCK_DMY_AFE_MISC_FUSA_PG_LOCK_DMY_AFE_MISC_LSP  0u
#define DVA_FUSA_PG_LOCK_DMY_AFE_MISC_FUSA_PG_LOCK_DMY_AFE_MISC_LEN  1u
#define DVA_FUSA_PG_LOCK_DMY_AFE_MISC_FUSA_PG_LOCK_DMY_AFE_MISC_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_AFE_MISC_H_ */