/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_CPU_DOMAIN_H_
#define DVA_RTKAS_REG_FIELD_FILE_CPU_DOMAIN_H_

#ifdef DVA_FILE_CPU_DOMAIN
/* File: CPU Domain */
#define DVA_INTERNAL_CPU_RESET_WAIT_CPU_ECC_PRE_WRITE_DONE_LSP  3u
#define DVA_INTERNAL_CPU_RESET_WAIT_CPU_ECC_PRE_WRITE_DONE_LEN  1u
#define DVA_INTERNAL_CPU_RESET_WAIT_CPU_ECC_PRE_WRITE_DONE_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_RESET_RST_DAP_CPU_LSP                  2u
#define DVA_INTERNAL_CPU_RESET_RST_DAP_CPU_LEN                  1u
#define DVA_INTERNAL_CPU_RESET_RST_DAP_CPU_TYPE                 DVA_FIELD_TYPE_RWS
#define DVA_INTERNAL_CPU_RESET_RST_DBG_CPU_LSP                  1u
#define DVA_INTERNAL_CPU_RESET_RST_DBG_CPU_LEN                  1u
#define DVA_INTERNAL_CPU_RESET_RST_DBG_CPU_TYPE                 DVA_FIELD_TYPE_RWS
#define DVA_INTERNAL_CPU_RESET_RST_CPU_LSP                      0u
#define DVA_INTERNAL_CPU_RESET_RST_CPU_LEN                      1u
#define DVA_INTERNAL_CPU_RESET_RST_CPU_TYPE                     DVA_FIELD_TYPE_RWS

#define DVA_CPU_BOOT_BOOT_STATUS_LSP   1u
#define DVA_CPU_BOOT_BOOT_STATUS_LEN   1u
#define DVA_CPU_BOOT_BOOT_STATUS_TYPE  DVA_FIELD_TYPE_RW
#define DVA_CPU_BOOT_SPIC_ROM_SEL_LSP  0u
#define DVA_CPU_BOOT_SPIC_ROM_SEL_LEN  1u
#define DVA_CPU_BOOT_SPIC_ROM_SEL_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_TRACE_PORT_0_TRACE_I0_IVADDR_LSP  0u
#define DVA_INTERNAL_CPU_TRACE_PORT_0_TRACE_I0_IVADDR_LEN  32u
#define DVA_INTERNAL_CPU_TRACE_PORT_0_TRACE_I0_IVADDR_TYPE DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_TRACE_PORT_1_TRACE_I0_RETIRE_LSP  0u
#define DVA_INTERNAL_CPU_TRACE_PORT_1_TRACE_I0_RETIRE_LEN  1u
#define DVA_INTERNAL_CPU_TRACE_PORT_1_TRACE_I0_RETIRE_TYPE DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_TRACE_PORT_2_TRACE_I1_IVADDR_LSP  0u
#define DVA_INTERNAL_CPU_TRACE_PORT_2_TRACE_I1_IVADDR_LEN  32u
#define DVA_INTERNAL_CPU_TRACE_PORT_2_TRACE_I1_IVADDR_TYPE DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_TRACE_PORT_3_TRACE_I1_RETIRE_LSP  0u
#define DVA_INTERNAL_CPU_TRACE_PORT_3_TRACE_I1_RETIRE_LEN  1u
#define DVA_INTERNAL_CPU_TRACE_PORT_3_TRACE_I1_RETIRE_TYPE DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_TRACE_PORT_4_TRACE_PC_LSP  0u
#define DVA_INTERNAL_CPU_TRACE_PORT_4_TRACE_PC_LEN  32u
#define DVA_INTERNAL_CPU_TRACE_PORT_4_TRACE_PC_TYPE DVA_FIELD_TYPE_RO

#define DVA_SPIC_STATUS_DEBUG_SPIC_BUSY_R_LSP      14u
#define DVA_SPIC_STATUS_DEBUG_SPIC_BUSY_R_LEN      1u
#define DVA_SPIC_STATUS_DEBUG_SPIC_BUSY_R_TYPE     DVA_FIELD_TYPE_RO
#define DVA_SPIC_STATUS_DEBUG_SPIC_PGM_RST_ST_LSP  11u
#define DVA_SPIC_STATUS_DEBUG_SPIC_PGM_RST_ST_LEN  3u
#define DVA_SPIC_STATUS_DEBUG_SPIC_PGM_RST_ST_TYPE DVA_FIELD_TYPE_RO
#define DVA_SPIC_STATUS_DEBUG_SPI_SH_STATE_R_LSP   8u
#define DVA_SPIC_STATUS_DEBUG_SPI_SH_STATE_R_LEN   3u
#define DVA_SPIC_STATUS_DEBUG_SPI_SH_STATE_R_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SPIC_STATUS_DEBUG_SPI_AT_STATE_R_LSP   4u
#define DVA_SPIC_STATUS_DEBUG_SPI_AT_STATE_R_LEN   4u
#define DVA_SPIC_STATUS_DEBUG_SPI_AT_STATE_R_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SPIC_STATUS_DEBUG_SPI_OC_STATE_R_LSP   1u
#define DVA_SPIC_STATUS_DEBUG_SPI_OC_STATE_R_LEN   3u
#define DVA_SPIC_STATUS_DEBUG_SPI_OC_STATE_R_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SPIC_STATUS_DEBUG_SPI_SER_ENABLE_LSP   0u
#define DVA_SPIC_STATUS_DEBUG_SPI_SER_ENABLE_LEN   1u
#define DVA_SPIC_STATUS_DEBUG_SPI_SER_ENABLE_TYPE  DVA_FIELD_TYPE_RO

#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_BOOT_FINISH_LSP        20u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_BOOT_FINISH_LEN        1u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_BOOT_FINISH_TYPE       DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_POP_LSP        19u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_POP_LEN        1u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_POP_TYPE       DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_OUT_VALID_LSP  18u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_OUT_VALID_LEN  1u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_OUT_VALID_TYPE DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_IN_VALID_LSP   17u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_IN_VALID_LEN   1u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_IN_VALID_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_PUSH_LSP       16u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_PUSH_LEN       1u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_PUSH_TYPE      DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_OUT_DATA_LSP   8u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_OUT_DATA_LEN   8u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_OUT_DATA_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_IN_DATA_LSP    0u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_IN_DATA_LEN    8u
#define DVA_SPIC_FIFO_TX_DEBUG_SPIC_TX_FIFO_IN_DATA_TYPE   DVA_FIELD_TYPE_RO

#define DVA_PLATFORM_INFO_RXI300_FATAL_LSP  0u
#define DVA_PLATFORM_INFO_RXI300_FATAL_LEN  1u
#define DVA_PLATFORM_INFO_RXI300_FATAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_CPU_DOMAIN_RSV_0_CPU_DOMAIN_RSV_0_LSP  0u
#define DVA_CPU_DOMAIN_RSV_0_CPU_DOMAIN_RSV_0_LEN  32u
#define DVA_CPU_DOMAIN_RSV_0_CPU_DOMAIN_RSV_0_TYPE DVA_FIELD_TYPE_RO

#define DVA_FAST_INTERRUPT_POL_FIQINT_N_POL_LSP  0u
#define DVA_FAST_INTERRUPT_POL_FIQINT_N_POL_LEN  4u
#define DVA_FAST_INTERRUPT_POL_FIQINT_N_POL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT3_DLY_SEL_LSP  17u
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT3_DLY_SEL_LEN  4u
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT3_DLY_SEL_TYPE DVA_FIELD_TYPE_RW
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT2_DLY_SEL_LSP  13u
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT2_DLY_SEL_LEN  4u
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT2_DLY_SEL_TYPE DVA_FIELD_TYPE_RW
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT1_DLY_SEL_LSP  9u
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT1_DLY_SEL_LEN  4u
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT1_DLY_SEL_TYPE DVA_FIELD_TYPE_RW
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT0_DLY_SEL_LSP  5u
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT0_DLY_SEL_LEN  4u
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_DAT0_DLY_SEL_TYPE DVA_FIELD_TYPE_RW
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_CLK_DLY_SEL_LSP   0u
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_CLK_DLY_SEL_LEN   5u
#define DVA_SPIC_DELAYCHAIN_SELECT_SPIC_CLK_DLY_SEL_TYPE  DVA_FIELD_TYPE_RW

#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_ECCTAG_0_LSP      15u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_ECCTAG_0_LEN      1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_ECCTAG_0_TYPE     DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_ECCDATA_0_LSP     14u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_ECCDATA_0_LEN     1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_ECCDATA_0_TYPE    DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_DPRAM_ECC_0_LSP  13u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_DPRAM_ECC_0_LEN  1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_DPRAM_ECC_0_TYPE DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_DPRAM_0_LSP      12u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_DPRAM_0_LEN      1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_DPRAM_0_TYPE     DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_PHT_DATA_0_LSP       11u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_PHT_DATA_0_LEN       1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_PHT_DATA_0_TYPE      DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_IC_DATA_0_LSP        10u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_IC_DATA_0_LEN        1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_IC_DATA_0_TYPE       DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_IC_TAG_0_LSP         9u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_IC_TAG_0_LEN         1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_IC_TAG_0_TYPE        DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_IC_LRU_0_LSP         8u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_IC_LRU_0_LEN         1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_IC_LRU_0_TYPE        DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_TAG_0_LSP         7u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_TAG_0_LEN         1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_TAG_0_TYPE        DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_DATA_0_LSP        6u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_DATA_0_LEN        1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DC_DATA_0_TYPE       DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_BTB_TAG_0_LSP        5u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_BTB_TAG_0_LEN        1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_BTB_TAG_0_TYPE       DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_BTB_DATA_0_LSP       4u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_BTB_DATA_0_LEN       1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_BTB_DATA_0_TYPE      DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_OC_RAM_ECC_0_LSP     3u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_OC_RAM_ECC_0_LEN     1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_OC_RAM_ECC_0_TYPE    DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_OC_RAM_0_LSP         2u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_OC_RAM_0_LEN         1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_OC_RAM_0_TYPE        DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DATA_SRAM_ECC_0_LSP  1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DATA_SRAM_ECC_0_LEN  1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DATA_SRAM_ECC_0_TYPE DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DATA_SRAM_0_LSP      0u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DATA_SRAM_0_LEN      1u
#define DVA_CR5_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_DATA_SRAM_0_TYPE     DVA_FIELD_TYPE_RO

#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_DONE_CR5_LSP                 31u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_DONE_CR5_LEN                 1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_DONE_CR5_TYPE                DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_OC_RAM_ECC_LSP     15u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_OC_RAM_ECC_LEN     1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_OC_RAM_ECC_TYPE    DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_NIC_DPRAM_ECC_LSP  14u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_NIC_DPRAM_ECC_LEN  1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_NIC_DPRAM_ECC_TYPE DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_ECCTAG_LSP      13u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_ECCTAG_LEN      1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_ECCTAG_TYPE     DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_ECCDATA_LSP     12u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_ECCDATA_LEN     1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_ECCDATA_TYPE    DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DATA_SRAM_ECC_LSP  11u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DATA_SRAM_ECC_LEN  1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DATA_SRAM_ECC_TYPE DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_NIC_DPRAM_LSP      10u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_NIC_DPRAM_LEN      1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_NIC_DPRAM_TYPE     DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_PHT_DATA_LSP       9u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_PHT_DATA_LEN       1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_PHT_DATA_TYPE      DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_IC_DATA_LSP        8u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_IC_DATA_LEN        1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_IC_DATA_TYPE       DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_IC_TAG_LSP         7u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_IC_TAG_LEN         1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_IC_TAG_TYPE        DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_IC_LRU_LSP         6u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_IC_LRU_LEN         1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_IC_LRU_TYPE        DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_TAG_LSP         5u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_TAG_LEN         1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_TAG_TYPE        DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_DATA_LSP        4u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_DATA_LEN        1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DC_DATA_TYPE       DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_BTB_TAG_LSP        3u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_BTB_TAG_LEN        1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_BTB_TAG_TYPE       DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_BTB_DATA_LSP       2u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_BTB_DATA_LEN       1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_BTB_DATA_TYPE      DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_OC_RAM_LSP         1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_OC_RAM_LEN         1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_OC_RAM_TYPE        DVA_FIELD_TYPE_RO
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DATA_SRAM_LSP      0u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DATA_SRAM_LEN      1u
#define DVA_CR5_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_DATA_SRAM_TYPE     DVA_FIELD_TYPE_RO

#define DVA_CR5_ECC0_MEM_ECC_MSG_CR5_0_LSP  0u
#define DVA_CR5_ECC0_MEM_ECC_MSG_CR5_0_LEN  32u
#define DVA_CR5_ECC0_MEM_ECC_MSG_CR5_0_TYPE DVA_FIELD_TYPE_RO

#define DVA_CR5_ECC1_MEM_ECC_MSG_CR5_1_LSP  0u
#define DVA_CR5_ECC1_MEM_ECC_MSG_CR5_1_LEN  32u
#define DVA_CR5_ECC1_MEM_ECC_MSG_CR5_1_TYPE DVA_FIELD_TYPE_RO

#define DVA_CR5_SRAM_MODE0_MEMORY_MODE_CTRL_R52_SRAM_ATCM_LSP  0u
#define DVA_CR5_SRAM_MODE0_MEMORY_MODE_CTRL_R52_SRAM_ATCM_LEN  7u
#define DVA_CR5_SRAM_MODE0_MEMORY_MODE_CTRL_R52_SRAM_ATCM_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE1_MEMORY_MODE_CTRL_R52_SRAM_BTCM_LSP  0u
#define DVA_CR5_SRAM_MODE1_MEMORY_MODE_CTRL_R52_SRAM_BTCM_LEN  10u
#define DVA_CR5_SRAM_MODE1_MEMORY_MODE_CTRL_R52_SRAM_BTCM_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE2_MEMORY_MODE_CTRL_R52_SRAM_CTCM_LSP  0u
#define DVA_CR5_SRAM_MODE2_MEMORY_MODE_CTRL_R52_SRAM_CTCM_LEN  10u
#define DVA_CR5_SRAM_MODE2_MEMORY_MODE_CTRL_R52_SRAM_CTCM_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE3_MEMORY_MODE_CTRL_R52_SRAM_DC_DATA_LSP  0u
#define DVA_CR5_SRAM_MODE3_MEMORY_MODE_CTRL_R52_SRAM_DC_DATA_LEN  10u
#define DVA_CR5_SRAM_MODE3_MEMORY_MODE_CTRL_R52_SRAM_DC_DATA_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE4_MEMORY_MODE_CTRL_R52_SRAM_IC_DATA_LSP  0u
#define DVA_CR5_SRAM_MODE4_MEMORY_MODE_CTRL_R52_SRAM_IC_DATA_LEN  10u
#define DVA_CR5_SRAM_MODE4_MEMORY_MODE_CTRL_R52_SRAM_IC_DATA_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE5_MEMORY_MODE_CTRL_DC_TAG_LSP  0u
#define DVA_CR5_SRAM_MODE5_MEMORY_MODE_CTRL_DC_TAG_LEN  10u
#define DVA_CR5_SRAM_MODE5_MEMORY_MODE_CTRL_DC_TAG_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_0_SECBOOT_IROM_FIFO_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_0_SECBOOT_IROM_FIFO_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_0_SECBOOT_IROM_FIFO_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_1_RSA_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_1_RSA_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_1_RSA_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_0_IMEM0_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_0_IMEM0_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_0_IMEM0_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_1_DMEM1_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_1_DMEM1_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_1_DMEM1_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_2_DMEM0_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_2_DMEM0_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_2_DMEM0_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_3_L2MEM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_3_L2MEM_ECC_ISR_LEN  8u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_3_L2MEM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_4_IMEM1_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_4_IMEM1_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_4_IMEM1_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_5_OC_ROM_1_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_5_OC_ROM_1_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_5_OC_ROM_1_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_6_OC_ROM_2_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_6_OC_ROM_2_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_6_OC_ROM_2_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_7_OC_ROM_3_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_7_OC_ROM_3_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_7_OC_ROM_3_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_8_BTB_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_8_BTB_ECC_ISR_LEN  8u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_8_BTB_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_9_BTB_TAG_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_9_BTB_TAG_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_9_BTB_TAG_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_10_DC_DATA_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_10_DC_DATA_ECC_ISR_LEN  8u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_10_DC_DATA_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_8_NIC_DPRAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_8_NIC_DPRAM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_8_NIC_DPRAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_27_ATSQ_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_27_ATSQ_ECC_ISR_LEN  26u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_27_ATSQ_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_3_LALU_IMEM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_3_LALU_IMEM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_3_LALU_IMEM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_4_LALU_MMEM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_4_LALU_MMEM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_4_LALU_MMEM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_28_DPC_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_28_DPC_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_28_DPC_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_0_PMI_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_0_PMI_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_0_PMI_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_1_TXQ_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_1_TXQ_ECC_ISR_LEN  26u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_1_TXQ_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_2_PB_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_2_PB_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_2_PB_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_3_HT_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_3_HT_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_3_HT_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_4_RH_SRAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_4_RH_SRAM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_4_RH_SRAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_5_OIL_SRAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_5_OIL_SRAM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_5_OIL_SRAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_6_IF_SRAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_6_IF_SRAM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_6_IF_SRAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_7_QBV_CTRL_ECC_ISR_0_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_7_QBV_CTRL_ECC_ISR_0_LEN  32u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_7_QBV_CTRL_ECC_ISR_0_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_8_QBV_CTRL_ECC_ISR_1_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_8_QBV_CTRL_ECC_ISR_1_LEN  20u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_8_QBV_CTRL_ECC_ISR_1_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_9_QBV_SGOT_ECC_ISR_0_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_9_QBV_SGOT_ECC_ISR_0_LEN  32u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_9_QBV_SGOT_ECC_ISR_0_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_10_QBV_SGOT_ECC_ISR_1_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_10_QBV_SGOT_ECC_ISR_1_LEN  20u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_10_QBV_SGOT_ECC_ISR_1_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_5_LALU_TMEM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_5_LALU_TMEM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_5_LALU_TMEM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_6_TLS_RAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_6_TLS_RAM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_6_TLS_RAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_7_SEC_SRAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_7_SEC_SRAM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_7_SEC_SRAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_0_RAM1P_RBUF_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_0_RAM1P_RBUF_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_0_RAM1P_RBUF_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_1_RAM1P_SOT_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_1_RAM1P_SOT_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_1_RAM1P_SOT_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_2_RAM2P_P_HDR_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_2_RAM2P_P_HDR_ECC_ISR_LEN  4u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_2_RAM2P_P_HDR_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_3_RAM2P_P_DATA_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_3_RAM2P_P_DATA_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_3_RAM2P_P_DATA_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_4_FTR_ROM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_4_FTR_ROM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_4_FTR_ROM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_5_IROM_FIFO_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_5_IROM_FIFO_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_5_IROM_FIFO_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_6_DROM_FIFO_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_6_DROM_FIFO_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_6_DROM_FIFO_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_7_RAM1P_LINKLIST_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_7_RAM1P_LINKLIST_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_7_RAM1P_LINKLIST_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_8_RAM1P_FIFO_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_8_RAM1P_FIFO_ECC_ISR_LEN  4u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_8_RAM1P_FIFO_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_9_ISRAM_FIFO_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_9_ISRAM_FIFO_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_9_ISRAM_FIFO_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_10_RX_REG_FIFO_1P_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_10_RX_REG_FIFO_1P_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_10_RX_REG_FIFO_1P_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_11_ADM_TWOPRF_RX_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_11_ADM_TWOPRF_RX_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_11_ADM_TWOPRF_RX_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_12_ADM_TWOPRF_TX_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_12_ADM_TWOPRF_TX_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_12_ADM_TWOPRF_TX_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_13_DESC_FIFO_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_13_DESC_FIFO_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_PCIE_13_DESC_FIFO_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_0_SECBOOT_IROM_FIFO_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_0_SECBOOT_IROM_FIFO_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_0_SECBOOT_IROM_FIFO_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_1_RSA_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_1_RSA_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_1_RSA_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_0_IMEM0_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_0_IMEM0_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_0_IMEM0_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_1_DMEM1_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_1_DMEM1_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_1_DMEM1_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_2_DMEM0_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_2_DMEM0_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_2_DMEM0_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_3_L2MEM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_3_L2MEM_ECC_IMR_LEN  8u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_3_L2MEM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_4_IMEM1_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_4_IMEM1_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_4_IMEM1_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_5_OC_ROM_1_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_5_OC_ROM_1_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_5_OC_ROM_1_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_6_OC_ROM_2_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_6_OC_ROM_2_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_6_OC_ROM_2_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_7_OC_ROM_3_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_7_OC_ROM_3_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_7_OC_ROM_3_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_8_BTB_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_8_BTB_ECC_IMR_LEN  8u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_8_BTB_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_9_BTB_TAG_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_9_BTB_TAG_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_9_BTB_TAG_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_10_DC_DATA_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_10_DC_DATA_ECC_IMR_LEN  8u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_10_DC_DATA_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_8_NIC_DPRAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_8_NIC_DPRAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_8_NIC_DPRAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_27_ATSQ_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_27_ATSQ_ECC_IMR_LEN  26u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_27_ATSQ_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_3_LALU_IMEM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_3_LALU_IMEM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_3_LALU_IMEM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_4_LALU_MMEM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_4_LALU_MMEM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_4_LALU_MMEM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_28_DPC_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_28_DPC_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_28_DPC_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_0_PMI_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_0_PMI_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_0_PMI_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_1_TXQ_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_1_TXQ_ECC_IMR_LEN  26u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_1_TXQ_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_2_PB_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_2_PB_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_2_PB_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_3_HT_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_3_HT_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_3_HT_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_4_RH_SRAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_4_RH_SRAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_4_RH_SRAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_5_OIL_SRAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_5_OIL_SRAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_5_OIL_SRAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_6_IF_SRAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_6_IF_SRAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_6_IF_SRAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_7_QBV_CTRL_ECC_IMR_0_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_7_QBV_CTRL_ECC_IMR_0_LEN  32u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_7_QBV_CTRL_ECC_IMR_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_8_QBV_CTRL_ECC_IMR_1_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_8_QBV_CTRL_ECC_IMR_1_LEN  20u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_8_QBV_CTRL_ECC_IMR_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_9_QBV_SGOT_ECC_IMR_0_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_9_QBV_SGOT_ECC_IMR_0_LEN  32u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_9_QBV_SGOT_ECC_IMR_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_10_QBV_SGOT_ECC_IMR_1_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_10_QBV_SGOT_ECC_IMR_1_LEN  20u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_10_QBV_SGOT_ECC_IMR_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_5_LALU_TMEM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_5_LALU_TMEM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_5_LALU_TMEM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_6_TLS_RAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_6_TLS_RAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_6_TLS_RAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_7_SEC_SRAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_7_SEC_SRAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_7_SEC_SRAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_0_RAM1P_RBUF_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_0_RAM1P_RBUF_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_0_RAM1P_RBUF_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_1_RAM1P_SOT_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_1_RAM1P_SOT_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_1_RAM1P_SOT_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_2_RAM2P_P_HDR_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_2_RAM2P_P_HDR_ECC_IMR_LEN  4u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_2_RAM2P_P_HDR_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_3_RAM2P_P_DATA_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_3_RAM2P_P_DATA_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_3_RAM2P_P_DATA_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_4_FTR_ROM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_4_FTR_ROM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_4_FTR_ROM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_5_IROM_FIFO_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_5_IROM_FIFO_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_5_IROM_FIFO_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_6_DROM_FIFO_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_6_DROM_FIFO_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_6_DROM_FIFO_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_7_RAM1P_LINKLIST_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_7_RAM1P_LINKLIST_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_7_RAM1P_LINKLIST_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_8_RAM1P_FIFO_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_8_RAM1P_FIFO_ECC_IMR_LEN  4u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_8_RAM1P_FIFO_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_9_ISRAM_FIFO_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_9_ISRAM_FIFO_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_9_ISRAM_FIFO_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_10_RX_REG_FIFO_1P_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_10_RX_REG_FIFO_1P_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_10_RX_REG_FIFO_1P_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_11_ADM_TWOPRF_RX_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_11_ADM_TWOPRF_RX_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_11_ADM_TWOPRF_RX_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_12_ADM_TWOPRF_TX_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_12_ADM_TWOPRF_TX_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_12_ADM_TWOPRF_TX_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_13_DESC_FIFO_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_13_DESC_FIFO_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_PCIE_13_DESC_FIFO_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_TIMESTAMP_CONVERTER_TRANSFORM_TYPE_LSP    8u
#define DVA_TIMESTAMP_CONVERTER_TRANSFORM_TYPE_LEN    3u
#define DVA_TIMESTAMP_CONVERTER_TRANSFORM_TYPE_TYPE   DVA_FIELD_TYPE_RW
#define DVA_TIMESTAMP_CONVERTER_TRANSFORM_STATUS_LSP  1u
#define DVA_TIMESTAMP_CONVERTER_TRANSFORM_STATUS_LEN  3u
#define DVA_TIMESTAMP_CONVERTER_TRANSFORM_STATUS_TYPE DVA_FIELD_TYPE_RO
#define DVA_TIMESTAMP_CONVERTER_TRANSFORM_REQ_LSP     0u
#define DVA_TIMESTAMP_CONVERTER_TRANSFORM_REQ_LEN     1u
#define DVA_TIMESTAMP_CONVERTER_TRANSFORM_REQ_TYPE    DVA_FIELD_TYPE_RWS

#define DVA_TIMESTAMP_NS_IN_TIMESTAMP_NS_IN_LSP  0u
#define DVA_TIMESTAMP_NS_IN_TIMESTAMP_NS_IN_LEN  32u
#define DVA_TIMESTAMP_NS_IN_TIMESTAMP_NS_IN_TYPE DVA_FIELD_TYPE_RW

#define DVA_TIMESTAMP_S0_IN_TIMESTAMP_S0_IN_LSP  0u
#define DVA_TIMESTAMP_S0_IN_TIMESTAMP_S0_IN_LEN  32u
#define DVA_TIMESTAMP_S0_IN_TIMESTAMP_S0_IN_TYPE DVA_FIELD_TYPE_RW

#define DVA_TIMESTAMP_S1_IN_TIMESTAMP_S1_IN_LSP  0u
#define DVA_TIMESTAMP_S1_IN_TIMESTAMP_S1_IN_LEN  16u
#define DVA_TIMESTAMP_S1_IN_TIMESTAMP_S1_IN_TYPE DVA_FIELD_TYPE_RW

#define DVA_TIMESTAMP_NS_OUT_TIMESTAMP_NS_OUT_LSP  0u
#define DVA_TIMESTAMP_NS_OUT_TIMESTAMP_NS_OUT_LEN  32u
#define DVA_TIMESTAMP_NS_OUT_TIMESTAMP_NS_OUT_TYPE DVA_FIELD_TYPE_RO

#define DVA_TIMESTAMP_S0_OUT_TIMESTAMP_S0_OUT_LSP  0u
#define DVA_TIMESTAMP_S0_OUT_TIMESTAMP_S0_OUT_LEN  32u
#define DVA_TIMESTAMP_S0_OUT_TIMESTAMP_S0_OUT_TYPE DVA_FIELD_TYPE_RO

#define DVA_TIMESTAMP_S1_OUT_TIMESTAMP_S1_OUT_LSP  0u
#define DVA_TIMESTAMP_S1_OUT_TIMESTAMP_S1_OUT_LEN  16u
#define DVA_TIMESTAMP_S1_OUT_TIMESTAMP_S1_OUT_TYPE DVA_FIELD_TYPE_RO

#define DVA_SCALED_NS0_IN_SCALED_NS0_IN_LSP  0u
#define DVA_SCALED_NS0_IN_SCALED_NS0_IN_LEN  32u
#define DVA_SCALED_NS0_IN_SCALED_NS0_IN_TYPE DVA_FIELD_TYPE_RW

#define DVA_SCALED_NS1_IN_SCALED_NS1_IN_LSP  0u
#define DVA_SCALED_NS1_IN_SCALED_NS1_IN_LEN  32u
#define DVA_SCALED_NS1_IN_SCALED_NS1_IN_TYPE DVA_FIELD_TYPE_RW

#define DVA_SCALED_NS2_IN_SCALED_NS2_IN_LSP  0u
#define DVA_SCALED_NS2_IN_SCALED_NS2_IN_LEN  32u
#define DVA_SCALED_NS2_IN_SCALED_NS2_IN_TYPE DVA_FIELD_TYPE_RW

#define DVA_SCALED_NS0_OUT_SCALED_NS0_OUT_LSP  0u
#define DVA_SCALED_NS0_OUT_SCALED_NS0_OUT_LEN  32u
#define DVA_SCALED_NS0_OUT_SCALED_NS0_OUT_TYPE DVA_FIELD_TYPE_RO

#define DVA_SCALED_NS1_OUT_SCALED_NS1_OUT_LSP  0u
#define DVA_SCALED_NS1_OUT_SCALED_NS1_OUT_LEN  32u
#define DVA_SCALED_NS1_OUT_SCALED_NS1_OUT_TYPE DVA_FIELD_TYPE_RO

#define DVA_SCALED_NS2_OUT_SCALED_NS2_OUT_LSP  0u
#define DVA_SCALED_NS2_OUT_SCALED_NS2_OUT_LEN  32u
#define DVA_SCALED_NS2_OUT_SCALED_NS2_OUT_TYPE DVA_FIELD_TYPE_RO

#define DVA_AUGEND_MINUEND_0_AUGEND_MINUEND_0_LSP  0u
#define DVA_AUGEND_MINUEND_0_AUGEND_MINUEND_0_LEN  32u
#define DVA_AUGEND_MINUEND_0_AUGEND_MINUEND_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_AUGEND_MINUEND_1_AUGEND_MINUEND_1_LSP  0u
#define DVA_AUGEND_MINUEND_1_AUGEND_MINUEND_1_LEN  32u
#define DVA_AUGEND_MINUEND_1_AUGEND_MINUEND_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_AUGEND_MINUEND_2_AUGEND_MINUEND_2_LSP  0u
#define DVA_AUGEND_MINUEND_2_AUGEND_MINUEND_2_LEN  32u
#define DVA_AUGEND_MINUEND_2_AUGEND_MINUEND_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDEND_SUBTRAHEND_0_ADDEND_SUBTRAHEND_0_LSP  0u
#define DVA_ADDEND_SUBTRAHEND_0_ADDEND_SUBTRAHEND_0_LEN  32u
#define DVA_ADDEND_SUBTRAHEND_0_ADDEND_SUBTRAHEND_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDEND_SUBTRAHEND_1_ADDEND_SUBTRAHEND_1_LSP  0u
#define DVA_ADDEND_SUBTRAHEND_1_ADDEND_SUBTRAHEND_1_LEN  32u
#define DVA_ADDEND_SUBTRAHEND_1_ADDEND_SUBTRAHEND_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDEND_SUBTRAHEND_2_ADDEND_SUBTRAHEND_2_LSP  0u
#define DVA_ADDEND_SUBTRAHEND_2_ADDEND_SUBTRAHEND_2_LEN  32u
#define DVA_ADDEND_SUBTRAHEND_2_ADDEND_SUBTRAHEND_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDER_OUT0_ADDER_OUT0_LSP  0u
#define DVA_ADDER_OUT0_ADDER_OUT0_LEN  32u
#define DVA_ADDER_OUT0_ADDER_OUT0_TYPE DVA_FIELD_TYPE_RO

#define DVA_ADDER_OUT1_ADDER_OUT1_LSP  0u
#define DVA_ADDER_OUT1_ADDER_OUT1_LEN  32u
#define DVA_ADDER_OUT1_ADDER_OUT1_TYPE DVA_FIELD_TYPE_RO

#define DVA_ADDER_OUT2_ADDER_OUT2_LSP  0u
#define DVA_ADDER_OUT2_ADDER_OUT2_LEN  32u
#define DVA_ADDER_OUT2_ADDER_OUT2_TYPE DVA_FIELD_TYPE_RO

#define DVA_SCALE_NS_CONTROL_ERROR_STATS_LSP  4u
#define DVA_SCALE_NS_CONTROL_ERROR_STATS_LEN  1u
#define DVA_SCALE_NS_CONTROL_ERROR_STATS_TYPE DVA_FIELD_TYPE_RO
#define DVA_SCALE_NS_CONTROL_OP_STATUS_LSP    3u
#define DVA_SCALE_NS_CONTROL_OP_STATUS_LEN    1u
#define DVA_SCALE_NS_CONTROL_OP_STATUS_TYPE   DVA_FIELD_TYPE_RO
#define DVA_SCALE_NS_CONTROL_OP_EN_LSP        2u
#define DVA_SCALE_NS_CONTROL_OP_EN_LEN        1u
#define DVA_SCALE_NS_CONTROL_OP_EN_TYPE       DVA_FIELD_TYPE_RWS
#define DVA_SCALE_NS_CONTROL_OP_MODE_LSP      0u
#define DVA_SCALE_NS_CONTROL_OP_MODE_LEN      2u
#define DVA_SCALE_NS_CONTROL_OP_MODE_TYPE     DVA_FIELD_TYPE_RW

#define DVA_MULTIPLICAND_0_MULTIPLICAND_0_LSP  0u
#define DVA_MULTIPLICAND_0_MULTIPLICAND_0_LEN  32u
#define DVA_MULTIPLICAND_0_MULTIPLICAND_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTIPLICAND_1_MULTIPLICAND_1_LSP  0u
#define DVA_MULTIPLICAND_1_MULTIPLICAND_1_LEN  32u
#define DVA_MULTIPLICAND_1_MULTIPLICAND_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTIPLIER_0_MULTIPLIER_0_LSP  0u
#define DVA_MULTIPLIER_0_MULTIPLIER_0_LEN  32u
#define DVA_MULTIPLIER_0_MULTIPLIER_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTIPLIER_1_MULTIPLIER_1_LSP  0u
#define DVA_MULTIPLIER_1_MULTIPLIER_1_LEN  32u
#define DVA_MULTIPLIER_1_MULTIPLIER_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_MUL_OUT_0_MUL_OUT_0_LSP  0u
#define DVA_MUL_OUT_0_MUL_OUT_0_LEN  32u
#define DVA_MUL_OUT_0_MUL_OUT_0_TYPE DVA_FIELD_TYPE_RO

#define DVA_MUL_OUT_1_MUL_OUT_1_LSP  0u
#define DVA_MUL_OUT_1_MUL_OUT_1_LEN  32u
#define DVA_MUL_OUT_1_MUL_OUT_1_TYPE DVA_FIELD_TYPE_RO

#define DVA_MUL_OUT_2_MUL_OUT_2_LSP  0u
#define DVA_MUL_OUT_2_MUL_OUT_2_LEN  32u
#define DVA_MUL_OUT_2_MUL_OUT_2_TYPE DVA_FIELD_TYPE_RO

#define DVA_MUL_OUT_3_MUL_OUT_3_LSP  0u
#define DVA_MUL_OUT_3_MUL_OUT_3_LEN  32u
#define DVA_MUL_OUT_3_MUL_OUT_3_TYPE DVA_FIELD_TYPE_RO

#define DVA_MULTIPLIER_CONTROL_MUL_ERROR_STATS_LSP  4u
#define DVA_MULTIPLIER_CONTROL_MUL_ERROR_STATS_LEN  1u
#define DVA_MULTIPLIER_CONTROL_MUL_ERROR_STATS_TYPE DVA_FIELD_TYPE_RO
#define DVA_MULTIPLIER_CONTROL_MUL_STATUS_LSP       3u
#define DVA_MULTIPLIER_CONTROL_MUL_STATUS_LEN       1u
#define DVA_MULTIPLIER_CONTROL_MUL_STATUS_TYPE      DVA_FIELD_TYPE_RO
#define DVA_MULTIPLIER_CONTROL_MUL_EN_LSP           2u
#define DVA_MULTIPLIER_CONTROL_MUL_EN_LEN           1u
#define DVA_MULTIPLIER_CONTROL_MUL_EN_TYPE          DVA_FIELD_TYPE_RWS
#define DVA_MULTIPLIER_CONTROL_MUL_MODE_LSP         0u
#define DVA_MULTIPLIER_CONTROL_MUL_MODE_LEN         2u
#define DVA_MULTIPLIER_CONTROL_MUL_MODE_TYPE        DVA_FIELD_TYPE_RW

#define DVA_NUMERATOR_0_NUMERATOR_0_LSP  0u
#define DVA_NUMERATOR_0_NUMERATOR_0_LEN  32u
#define DVA_NUMERATOR_0_NUMERATOR_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_NUMERATOR_1_NUMERATOR_1_LSP  0u
#define DVA_NUMERATOR_1_NUMERATOR_1_LEN  32u
#define DVA_NUMERATOR_1_NUMERATOR_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_DENOMINATOR_0_DENOMINATOR_0_LSP  0u
#define DVA_DENOMINATOR_0_DENOMINATOR_0_LEN  32u
#define DVA_DENOMINATOR_0_DENOMINATOR_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_DENOMINATOR_1_DENOMINATOR_1_LSP  0u
#define DVA_DENOMINATOR_1_DENOMINATOR_1_LEN  32u
#define DVA_DENOMINATOR_1_DENOMINATOR_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_DIV_OUT_0_DIV_OUT_0_LSP  0u
#define DVA_DIV_OUT_0_DIV_OUT_0_LEN  32u
#define DVA_DIV_OUT_0_DIV_OUT_0_TYPE DVA_FIELD_TYPE_RO

#define DVA_DIV_OUT_1_DIV_OUT_1_LSP  0u
#define DVA_DIV_OUT_1_DIV_OUT_1_LEN  32u
#define DVA_DIV_OUT_1_DIV_OUT_1_TYPE DVA_FIELD_TYPE_RO

#define DVA_DIVIDER_CONTROL_DIV_ERROR_STATS_LSP  4u
#define DVA_DIVIDER_CONTROL_DIV_ERROR_STATS_LEN  1u
#define DVA_DIVIDER_CONTROL_DIV_ERROR_STATS_TYPE DVA_FIELD_TYPE_RO
#define DVA_DIVIDER_CONTROL_DIV_STATUS_LSP       3u
#define DVA_DIVIDER_CONTROL_DIV_STATUS_LEN       1u
#define DVA_DIVIDER_CONTROL_DIV_STATUS_TYPE      DVA_FIELD_TYPE_RO
#define DVA_DIVIDER_CONTROL_DIV_EN_LSP           2u
#define DVA_DIVIDER_CONTROL_DIV_EN_LEN           1u
#define DVA_DIVIDER_CONTROL_DIV_EN_TYPE          DVA_FIELD_TYPE_RWS
#define DVA_DIVIDER_CONTROL_DIV_MODE_LSP         0u
#define DVA_DIVIDER_CONTROL_DIV_MODE_LEN         2u
#define DVA_DIVIDER_CONTROL_DIV_MODE_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_14_EIP160SE_STAT_RAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_14_EIP160SE_STAT_RAM_ECC_IMR_LEN  12u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_14_EIP160SE_STAT_RAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_15_EIP160SI_STAT_RAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_15_EIP160SI_STAT_RAM_ECC_IMR_LEN  12u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_15_EIP160SI_STAT_RAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_16_EIP160SE_SA_RAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_16_EIP160SE_SA_RAM_ECC_IMR_LEN  12u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_16_EIP160SE_SA_RAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_9_SECBOOT_ISRAM_FIFO_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_9_SECBOOT_ISRAM_FIFO_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_9_SECBOOT_ISRAM_FIFO_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_18_EIP160SI_SA_RAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_18_EIP160SI_SA_RAM_ECC_IMR_LEN  12u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_18_EIP160SI_SA_RAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_14_EIP160SE_STAT_RAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_14_EIP160SE_STAT_RAM_ECC_ISR_LEN  12u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_14_EIP160SE_STAT_RAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_15_EIP160SI_STAT_RAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_15_EIP160SI_STAT_RAM_ECC_ISR_LEN  12u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_15_EIP160SI_STAT_RAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_16_EIP160SE_SA_RAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_16_EIP160SE_SA_RAM_ECC_ISR_LEN  12u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_16_EIP160SE_SA_RAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_9_SECBOOT_ISRAM_FIFO_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_9_SECBOOT_ISRAM_FIFO_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_9_SECBOOT_ISRAM_FIFO_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_18_EIP160SI_SA_RAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_18_EIP160SI_SA_RAM_ECC_ISR_LEN  12u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_18_EIP160SI_SA_RAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_CPU_SLEEP_SL_SLEEPSYS_R_LSP  0u
#define DVA_CPU_SLEEP_SL_SLEEPSYS_R_LEN  1u
#define DVA_CPU_SLEEP_SL_SLEEPSYS_R_TYPE DVA_FIELD_TYPE_RO

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_20_MACSEC_TX_RA_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_20_MACSEC_TX_RA_ECC_IMR_LEN  18u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_20_MACSEC_TX_RA_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_20_MACSEC_TX_RA_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_20_MACSEC_TX_RA_ECC_ISR_LEN  18u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_20_MACSEC_TX_RA_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_CR5_SRAM_MODE6_MEMORY_MODE_CTRL_R52_SRAM_IC_TAG_LSP  0u
#define DVA_CR5_SRAM_MODE6_MEMORY_MODE_CTRL_R52_SRAM_IC_TAG_LEN  10u
#define DVA_CR5_SRAM_MODE6_MEMORY_MODE_CTRL_R52_SRAM_IC_TAG_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_SECBOOT_ISRAM_FIFO_0_LSP  7u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_SECBOOT_ISRAM_FIFO_0_LEN  1u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_SECBOOT_ISRAM_FIFO_0_TYPE DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_MACPHY_SRAM_1_LSP     6u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_MACPHY_SRAM_1_LEN     1u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_MACPHY_SRAM_1_TYPE    DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_MACPHY_SRAM_0_LSP     5u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_MACPHY_SRAM_0_LEN     1u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_NIC_MACPHY_SRAM_0_TYPE    DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_LALU_TMEM_0_LSP           4u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_LALU_TMEM_0_LEN           1u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_LALU_TMEM_0_TYPE          DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_LALU_MMEM_0_LSP           3u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_LALU_MMEM_0_LEN           1u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_LALU_MMEM_0_TYPE          DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_SEC_SRAM_0_LSP            2u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_SEC_SRAM_0_LEN            1u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_SEC_SRAM_0_TYPE           DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_TLS_RAM_0_LSP             1u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_TLS_RAM_0_LEN             1u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_TLS_RAM_0_TYPE            DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_RSA_0_LSP                 0u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_RSA_0_LEN                 1u
#define DVA_CPU_ECC_PRE_WRITE_STATUS0_ECC_PRE_WRITE_EN_ST_RSA_0_TYPE                DVA_FIELD_TYPE_RO

#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_DONE_CPU_LSP                      31u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_DONE_CPU_LEN                      1u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_DONE_CPU_TYPE                     DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_SECBOOT_ISRAM_FIFO_LSP  6u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_SECBOOT_ISRAM_FIFO_LEN  1u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_SECBOOT_ISRAM_FIFO_TYPE DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_NIC_MACPHY_SRAM_LSP     5u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_NIC_MACPHY_SRAM_LEN     1u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_NIC_MACPHY_SRAM_TYPE    DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_LALU_TMEM_LSP           4u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_LALU_TMEM_LEN           1u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_LALU_TMEM_TYPE          DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_LALU_MMEM_LSP           3u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_LALU_MMEM_LEN           1u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_LALU_MMEM_TYPE          DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_SEC_SRAM_LSP            2u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_SEC_SRAM_LEN            1u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_SEC_SRAM_TYPE           DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_TLS_RAM_LSP             1u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_TLS_RAM_LEN             1u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_TLS_RAM_TYPE            DVA_FIELD_TYPE_RO
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_RSA_LSP                 0u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_RSA_LEN                 1u
#define DVA_CPU_ECC_PRE_WRITE_ALL_STATUS1_ECC_PRE_WRITE_EN_ALL_ST_RSA_TYPE                DVA_FIELD_TYPE_RO

#define DVA_CPU_ECC0_MEM_ECC_MSG_CPU_0_LSP  0u
#define DVA_CPU_ECC0_MEM_ECC_MSG_CPU_0_LEN  10u
#define DVA_CPU_ECC0_MEM_ECC_MSG_CPU_0_TYPE DVA_FIELD_TYPE_RO

#define DVA_CR5_ECC2_MEM_ECC_MSG_CR5_2_LSP  0u
#define DVA_CR5_ECC2_MEM_ECC_MSG_CR5_2_LEN  32u
#define DVA_CR5_ECC2_MEM_ECC_MSG_CR5_2_TYPE DVA_FIELD_TYPE_RO

#define DVA_CR5_ECC3_MEM_ECC_MSG_CR5_3_LSP  0u
#define DVA_CR5_ECC3_MEM_ECC_MSG_CR5_3_LEN  32u
#define DVA_CR5_ECC3_MEM_ECC_MSG_CR5_3_TYPE DVA_FIELD_TYPE_RO

#define DVA_CR5_ECC4_MEM_ECC_MSG_CR5_4_LSP  0u
#define DVA_CR5_ECC4_MEM_ECC_MSG_CR5_4_LEN  32u
#define DVA_CR5_ECC4_MEM_ECC_MSG_CR5_4_TYPE DVA_FIELD_TYPE_RO

#define DVA_CR5_ECC5_MEM_ECC_MSG_CR5_5_LSP  0u
#define DVA_CR5_ECC5_MEM_ECC_MSG_CR5_5_LEN  2u
#define DVA_CR5_ECC5_MEM_ECC_MSG_CR5_5_TYPE DVA_FIELD_TYPE_RO

#define DVA_CPU_SRAM_MODE0_MEMORY_MODE_CTRL_SECBOOT_IROM_FIFO_LSP  0u
#define DVA_CPU_SRAM_MODE0_MEMORY_MODE_CTRL_SECBOOT_IROM_FIFO_LEN  7u
#define DVA_CPU_SRAM_MODE0_MEMORY_MODE_CTRL_SECBOOT_IROM_FIFO_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_SRAM_MODE1_MEMORY_MODE_CTRL_RSA_LSP  0u
#define DVA_CPU_SRAM_MODE1_MEMORY_MODE_CTRL_RSA_LEN  9u
#define DVA_CPU_SRAM_MODE1_MEMORY_MODE_CTRL_RSA_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_SRAM_MODE2_MEMORY_MODE_CTRL_NIC_MACPHY_SRAM_LSP  0u
#define DVA_CPU_SRAM_MODE2_MEMORY_MODE_CTRL_NIC_MACPHY_SRAM_LEN  16u
#define DVA_CPU_SRAM_MODE2_MEMORY_MODE_CTRL_NIC_MACPHY_SRAM_TYPE DVA_FIELD_TYPE_RW

#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_POP_LSP        19u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_POP_LEN        1u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_POP_TYPE       DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_OUT_VALID_LSP  18u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_OUT_VALID_LEN  1u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_OUT_VALID_TYPE DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_IN_VALID_LSP   17u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_IN_VALID_LEN   1u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_IN_VALID_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_PUSH_LSP       16u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_PUSH_LEN       1u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_PUSH_TYPE      DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_OUT_DATA_LSP   8u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_OUT_DATA_LEN   8u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_OUT_DATA_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_IN_DATA_LSP    0u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_IN_DATA_LEN    8u
#define DVA_SPIC_FIFO_RX_DEBUG_SPIC_RX_FIFO_IN_DATA_TYPE   DVA_FIELD_TYPE_RO

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_17_OC_ROM_4_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_17_OC_ROM_4_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_17_OC_ROM_4_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_18_OC_ROM_5_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_18_OC_ROM_5_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_18_OC_ROM_5_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_19_SA_RAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_19_SA_RAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_19_SA_RAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_20_OC_ROM_7_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_20_OC_ROM_7_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CR5_20_OC_ROM_7_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_17_OC_ROM_4_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_17_OC_ROM_4_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_17_OC_ROM_4_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_18_OC_ROM_5_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_18_OC_ROM_5_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_18_OC_ROM_5_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_19_OC_ROM_6_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_19_OC_ROM_6_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_19_OC_ROM_6_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_20_OC_ROM_7_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_20_OC_ROM_7_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CR5_20_OC_ROM_7_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_CR5_SRAM_MODE7_MEMORY_MODE_CTRL_R52_SRAM_ATCM_LSP  0u
#define DVA_CR5_SRAM_MODE7_MEMORY_MODE_CTRL_R52_SRAM_ATCM_LEN  10u
#define DVA_CR5_SRAM_MODE7_MEMORY_MODE_CTRL_R52_SRAM_ATCM_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_CTRL_REG_SPNIDEN_LSP          18u
#define DVA_CPU_CTRL_REG_SPNIDEN_LEN          1u
#define DVA_CPU_CTRL_REG_SPNIDEN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_SPIDEN_LSP           17u
#define DVA_CPU_CTRL_REG_SPIDEN_LEN           1u
#define DVA_CPU_CTRL_REG_SPIDEN_TYPE          DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_SPD_UP_LSP           16u
#define DVA_CPU_CTRL_REG_SPD_UP_LEN           1u
#define DVA_CPU_CTRL_REG_SPD_UP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_SEV_IN_LSP           15u
#define DVA_CPU_CTRL_REG_SEV_IN_LEN           1u
#define DVA_CPU_CTRL_REG_SEV_IN_TYPE          DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_RETENTION_MODE_LSP   14u
#define DVA_CPU_CTRL_REG_RETENTION_MODE_LEN   1u
#define DVA_CPU_CTRL_REG_RETENTION_MODE_TYPE  DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_RETENTION_L2MEM_LSP  13u
#define DVA_CPU_CTRL_REG_RETENTION_L2MEM_LEN  1u
#define DVA_CPU_CTRL_REG_RETENTION_L2MEM_TYPE DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_RETENTION_ITCM1_LSP  12u
#define DVA_CPU_CTRL_REG_RETENTION_ITCM1_LEN  1u
#define DVA_CPU_CTRL_REG_RETENTION_ITCM1_TYPE DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_RETENTION_ITCM0_LSP  11u
#define DVA_CPU_CTRL_REG_RETENTION_ITCM0_LEN  1u
#define DVA_CPU_CTRL_REG_RETENTION_ITCM0_TYPE DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_RETENTION_DTCM1_LSP  10u
#define DVA_CPU_CTRL_REG_RETENTION_DTCM1_LEN  1u
#define DVA_CPU_CTRL_REG_RETENTION_DTCM1_TYPE DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_RETENTION_DTCM0_LSP  9u
#define DVA_CPU_CTRL_REG_RETENTION_DTCM0_LEN  1u
#define DVA_CPU_CTRL_REG_RETENTION_DTCM0_TYPE DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_NIDEN_LSP            8u
#define DVA_CPU_CTRL_REG_NIDEN_LEN            1u
#define DVA_CPU_CTRL_REG_NIDEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_INITL2MEN_LSP        7u
#define DVA_CPU_CTRL_REG_INITL2MEN_LEN        1u
#define DVA_CPU_CTRL_REG_INITL2MEN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_INITITCMEN1_LSP      6u
#define DVA_CPU_CTRL_REG_INITITCMEN1_LEN      1u
#define DVA_CPU_CTRL_REG_INITITCMEN1_TYPE     DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_INITITCMEN0_LSP      5u
#define DVA_CPU_CTRL_REG_INITITCMEN0_LEN      1u
#define DVA_CPU_CTRL_REG_INITITCMEN0_TYPE     DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_INITI2DTCM_LSP       4u
#define DVA_CPU_CTRL_REG_INITI2DTCM_LEN       1u
#define DVA_CPU_CTRL_REG_INITI2DTCM_TYPE      DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_INITDTCMEN1_LSP      3u
#define DVA_CPU_CTRL_REG_INITDTCMEN1_LEN      1u
#define DVA_CPU_CTRL_REG_INITDTCMEN1_TYPE     DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_INITDTCMEN0_LSP      2u
#define DVA_CPU_CTRL_REG_INITDTCMEN0_LEN      1u
#define DVA_CPU_CTRL_REG_INITDTCMEN0_TYPE     DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_INITD2ITCM_LSP       1u
#define DVA_CPU_CTRL_REG_INITD2ITCM_LEN       1u
#define DVA_CPU_CTRL_REG_INITD2ITCM_TYPE      DVA_FIELD_TYPE_RW
#define DVA_CPU_CTRL_REG_INITECCEN_LSP        0u
#define DVA_CPU_CTRL_REG_INITECCEN_LEN        1u
#define DVA_CPU_CTRL_REG_INITECCEN_TYPE       DVA_FIELD_TYPE_RW

#define DVA_CPU_CTRL_REG_1_INITVTOR_NS_LSP  0u
#define DVA_CPU_CTRL_REG_1_INITVTOR_NS_LEN  32u
#define DVA_CPU_CTRL_REG_1_INITVTOR_NS_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_CTRL_REG_2_INITVTOR_S_LSP  0u
#define DVA_CPU_CTRL_REG_2_INITVTOR_S_LEN  32u
#define DVA_CPU_CTRL_REG_2_INITVTOR_S_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_CTRL_REG_3_RG_EN_WATCHDOG_IRPT_LSP  0u
#define DVA_CPU_CTRL_REG_3_RG_EN_WATCHDOG_IRPT_LEN  1u
#define DVA_CPU_CTRL_REG_3_RG_EN_WATCHDOG_IRPT_TYPE DVA_FIELD_TYPE_RW

#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_CAL_MODE_LSP          28u
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_CAL_MODE_LEN          1u
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_CAL_MODE_TYPE         DVA_FIELD_TYPE_RW
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT3_INVPAIR_SEL_LSP  21u
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT3_INVPAIR_SEL_LEN  7u
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT3_INVPAIR_SEL_TYPE DVA_FIELD_TYPE_RW
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT2_INVPAIR_SEL_LSP  14u
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT2_INVPAIR_SEL_LEN  7u
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT2_INVPAIR_SEL_TYPE DVA_FIELD_TYPE_RW
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT1_INVPAIR_SEL_LSP  7u
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT1_INVPAIR_SEL_LEN  7u
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT1_INVPAIR_SEL_TYPE DVA_FIELD_TYPE_RW
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT0_INVPAIR_SEL_LSP  0u
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT0_INVPAIR_SEL_LEN  7u
#define DVA_SPIC_DELAYCHAIN_WITH_INVERTER_PAIR_SELECT_SPIC_DAT0_INVPAIR_SEL_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE8_MEMORY_MODE_CTRL_R52_SRAM_FSS_LSP  0u
#define DVA_CR5_SRAM_MODE8_MEMORY_MODE_CTRL_R52_SRAM_FSS_LEN  10u
#define DVA_CR5_SRAM_MODE8_MEMORY_MODE_CTRL_R52_SRAM_FSS_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE9_MEMORY_MODE_CTRL_SECBOOT_ISRAM_FIFO_LSP  0u
#define DVA_CR5_SRAM_MODE9_MEMORY_MODE_CTRL_SECBOOT_ISRAM_FIFO_LEN  10u
#define DVA_CR5_SRAM_MODE9_MEMORY_MODE_CTRL_SECBOOT_ISRAM_FIFO_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE10_MEMORY_MODE_CTRL_NIC_DPRAM_LSP  0u
#define DVA_CR5_SRAM_MODE10_MEMORY_MODE_CTRL_NIC_DPRAM_LEN  16u
#define DVA_CR5_SRAM_MODE10_MEMORY_MODE_CTRL_NIC_DPRAM_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE11_MEMORY_MODE_CTRL_LALU_IMEM_LSP  0u
#define DVA_CR5_SRAM_MODE11_MEMORY_MODE_CTRL_LALU_IMEM_LEN  7u
#define DVA_CR5_SRAM_MODE11_MEMORY_MODE_CTRL_LALU_IMEM_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE12_MEMORY_MODE_CTRL_LALU_MMEM_LSP  0u
#define DVA_CR5_SRAM_MODE12_MEMORY_MODE_CTRL_LALU_MMEM_LEN  11u
#define DVA_CR5_SRAM_MODE12_MEMORY_MODE_CTRL_LALU_MMEM_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE13_MEMORY_MODE_CTRL_LALU_TMEM_LSP  0u
#define DVA_CR5_SRAM_MODE13_MEMORY_MODE_CTRL_LALU_TMEM_LEN  11u
#define DVA_CR5_SRAM_MODE13_MEMORY_MODE_CTRL_LALU_TMEM_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE14_MEMORY_MODE_CTRL_OC_ROM_0_LSP  0u
#define DVA_CR5_SRAM_MODE14_MEMORY_MODE_CTRL_OC_ROM_0_LEN  7u
#define DVA_CR5_SRAM_MODE14_MEMORY_MODE_CTRL_OC_ROM_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE15_MEMORY_MODE_CTRL_OC_ROM_1_LSP  0u
#define DVA_CR5_SRAM_MODE15_MEMORY_MODE_CTRL_OC_ROM_1_LEN  7u
#define DVA_CR5_SRAM_MODE15_MEMORY_MODE_CTRL_OC_ROM_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE16_MEMORY_MODE_CTRL_OC_ROM_2_LSP  0u
#define DVA_CR5_SRAM_MODE16_MEMORY_MODE_CTRL_OC_ROM_2_LEN  7u
#define DVA_CR5_SRAM_MODE16_MEMORY_MODE_CTRL_OC_ROM_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE17_MEMORY_MODE_CTRL_OC_ROM_3_LSP  0u
#define DVA_CR5_SRAM_MODE17_MEMORY_MODE_CTRL_OC_ROM_3_LEN  7u
#define DVA_CR5_SRAM_MODE17_MEMORY_MODE_CTRL_OC_ROM_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE18_MEMORY_MODE_CTRL_OC_ROM_4_LSP  0u
#define DVA_CR5_SRAM_MODE18_MEMORY_MODE_CTRL_OC_ROM_4_LEN  7u
#define DVA_CR5_SRAM_MODE18_MEMORY_MODE_CTRL_OC_ROM_4_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE19_MEMORY_MODE_CTRL_OC_ROM_5_LSP  0u
#define DVA_CR5_SRAM_MODE19_MEMORY_MODE_CTRL_OC_ROM_5_LEN  7u
#define DVA_CR5_SRAM_MODE19_MEMORY_MODE_CTRL_OC_ROM_5_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE20_MEMORY_MODE_CTRL_OC_ROM_6_LSP  0u
#define DVA_CR5_SRAM_MODE20_MEMORY_MODE_CTRL_OC_ROM_6_LEN  7u
#define DVA_CR5_SRAM_MODE20_MEMORY_MODE_CTRL_OC_ROM_6_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE21_MEMORY_MODE_CTRL_OC_ROM_7_LSP  0u
#define DVA_CR5_SRAM_MODE21_MEMORY_MODE_CTRL_OC_ROM_7_LEN  7u
#define DVA_CR5_SRAM_MODE21_MEMORY_MODE_CTRL_OC_ROM_7_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE22_MEMORY_MODE_CTRL_PHT_DATA_LSP  0u
#define DVA_CR5_SRAM_MODE22_MEMORY_MODE_CTRL_PHT_DATA_LEN  7u
#define DVA_CR5_SRAM_MODE22_MEMORY_MODE_CTRL_PHT_DATA_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE23_MEMORY_MODE_CTRL_DATA_SRAM_LSP  0u
#define DVA_CR5_SRAM_MODE23_MEMORY_MODE_CTRL_DATA_SRAM_LEN  7u
#define DVA_CR5_SRAM_MODE23_MEMORY_MODE_CTRL_DATA_SRAM_TYPE DVA_FIELD_TYPE_RW

#define DVA_CR5_SRAM_MODE24_MEMORY_MODE_CTRL_DATA_SRAM_ECC_LSP  0u
#define DVA_CR5_SRAM_MODE24_MEMORY_MODE_CTRL_DATA_SRAM_ECC_LEN  7u
#define DVA_CR5_SRAM_MODE24_MEMORY_MODE_CTRL_DATA_SRAM_ECC_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_2_NIC_MACPHY_SRAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_2_NIC_MACPHY_SRAM_ECC_IMR_LEN  4u
#define DVA_SRAM_ECC_INTERRUPT_MASK_CPU_2_NIC_MACPHY_SRAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_2_NIC_MACPHY_SRAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_2_NIC_MACPHY_SRAM_ECC_ISR_LEN  4u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_CPU_2_NIC_MACPHY_SRAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_21_EIP160SE_10G64_STAT_RAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_21_EIP160SE_10G64_STAT_RAM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_21_EIP160SE_10G64_STAT_RAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_22_EIP160SI_10G64_STAT_RAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_22_EIP160SI_10G64_STAT_RAM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_22_EIP160SI_10G64_STAT_RAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_23_EIP160SE_10G64_SA_RAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_23_EIP160SE_10G64_SA_RAM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_23_EIP160SE_10G64_SA_RAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_24_EIP160SI_10G64_SA_RAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_24_EIP160SI_10G64_SA_RAM_ECC_ISR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_24_EIP160SI_10G64_SA_RAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_25_WTG_SRAM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_25_WTG_SRAM_ECC_ISR_LEN  8u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_25_WTG_SRAM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_26_WTG_ROM_ECC_ISR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_26_WTG_ROM_ECC_ISR_LEN  8u
#define DVA_SRAM_ECC_INTERRUPT_STATUS_SW_26_WTG_ROM_ECC_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_21_EIP160SE_10G64_STAT_RAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_21_EIP160SE_10G64_STAT_RAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_21_EIP160SE_10G64_STAT_RAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_22_EIP160SI_10G64_STAT_RAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_22_EIP160SI_10G64_STAT_RAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_22_EIP160SI_10G64_STAT_RAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_23_EIP160SE_10G64_SA_RAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_23_EIP160SE_10G64_SA_RAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_23_EIP160SE_10G64_SA_RAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_24_EIP160SI_10G64_SA_RAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_24_EIP160SI_10G64_SA_RAM_ECC_IMR_LEN  2u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_24_EIP160SI_10G64_SA_RAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_25_WTG_SRAM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_25_WTG_SRAM_ECC_IMR_LEN  8u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_25_WTG_SRAM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_26_WTG_ROM_ECC_IMR_LSP  0u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_26_WTG_ROM_ECC_IMR_LEN  8u
#define DVA_SRAM_ECC_INTERRUPT_MASK_SW_26_WTG_ROM_ECC_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SPIC_DPHY_CTRL_SPIC_DPHY_RD_DELAY_LSP         4u
#define DVA_SPIC_DPHY_CTRL_SPIC_DPHY_RD_DELAY_LEN         3u
#define DVA_SPIC_DPHY_CTRL_SPIC_DPHY_RD_DELAY_TYPE        DVA_FIELD_TYPE_RW
#define DVA_SPIC_DPHY_CTRL_SPIC_DPHY_RD_DELAY_FACTOR_LSP  2u
#define DVA_SPIC_DPHY_CTRL_SPIC_DPHY_RD_DELAY_FACTOR_LEN  2u
#define DVA_SPIC_DPHY_CTRL_SPIC_DPHY_RD_DELAY_FACTOR_TYPE DVA_FIELD_TYPE_RW
#define DVA_SPIC_DPHY_CTRL_SPIC_DPHY_EN_LSP               0u
#define DVA_SPIC_DPHY_CTRL_SPIC_DPHY_EN_LEN               1u
#define DVA_SPIC_DPHY_CTRL_SPIC_DPHY_EN_TYPE              DVA_FIELD_TYPE_RW

#define DVA_SPIC_INTERRUPT_MASK_SPIC_RXUIS_IMR_LSP  2u
#define DVA_SPIC_INTERRUPT_MASK_SPIC_RXUIS_IMR_LEN  1u
#define DVA_SPIC_INTERRUPT_MASK_SPIC_RXUIS_IMR_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_CPU_DOMAIN_H_ */