/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_LINK_AGGREGATE_H_
#define DVA_RTKAS_REG_FIELD_FILE_LINK_AGGREGATE_H_

#ifdef DVA_FILE_LINK_AGGREGATE
/* File: Link Aggregate */
#define DVA_LAG0_MEMBER_LAG0_PORT_MEMBER_LSP  0u
#define DVA_LAG0_MEMBER_LAG0_PORT_MEMBER_LEN  16u
#define DVA_LAG0_MEMBER_LAG0_PORT_MEMBER_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG0_HASH_SETTING_LAG0_HASH_SHIFT_LSP  8u
#define DVA_LAG0_HASH_SETTING_LAG0_HASH_SHIFT_LEN  16u
#define DVA_LAG0_HASH_SETTING_LAG0_HASH_SHIFT_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG0_HASH_SETTING_LAG0_HASH_MASK_LSP   0u
#define DVA_LAG0_HASH_SETTING_LAG0_HASH_MASK_LEN   8u
#define DVA_LAG0_HASH_SETTING_LAG0_HASH_MASK_TYPE  DVA_FIELD_TYPE_RW

#define DVA_LAG1_MEMBER_LAG1_PORT_MEMBER_LSP  0u
#define DVA_LAG1_MEMBER_LAG1_PORT_MEMBER_LEN  16u
#define DVA_LAG1_MEMBER_LAG1_PORT_MEMBER_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG1_HASH_SETTING_LAG1_HASH_SHIFT_LSP  8u
#define DVA_LAG1_HASH_SETTING_LAG1_HASH_SHIFT_LEN  16u
#define DVA_LAG1_HASH_SETTING_LAG1_HASH_SHIFT_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG1_HASH_SETTING_LAG1_HASH_MASK_LSP   0u
#define DVA_LAG1_HASH_SETTING_LAG1_HASH_MASK_LEN   8u
#define DVA_LAG1_HASH_SETTING_LAG1_HASH_MASK_TYPE  DVA_FIELD_TYPE_RW

#define DVA_LAG2_MEMBER_LAG2_PORT_MEMBER_LSP  0u
#define DVA_LAG2_MEMBER_LAG2_PORT_MEMBER_LEN  16u
#define DVA_LAG2_MEMBER_LAG2_PORT_MEMBER_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG2_HASH_SETTING_LAG2_HASH_SHIFT_LSP  8u
#define DVA_LAG2_HASH_SETTING_LAG2_HASH_SHIFT_LEN  16u
#define DVA_LAG2_HASH_SETTING_LAG2_HASH_SHIFT_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG2_HASH_SETTING_LAG2_HASH_MASK_LSP   0u
#define DVA_LAG2_HASH_SETTING_LAG2_HASH_MASK_LEN   8u
#define DVA_LAG2_HASH_SETTING_LAG2_HASH_MASK_TYPE  DVA_FIELD_TYPE_RW

#define DVA_LAG3_MEMBER_LAG3_PORT_MEMBER_LSP  0u
#define DVA_LAG3_MEMBER_LAG3_PORT_MEMBER_LEN  16u
#define DVA_LAG3_MEMBER_LAG3_PORT_MEMBER_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG3_HASH_SETTING_LAG3_HASH_SHIFT_LSP  8u
#define DVA_LAG3_HASH_SETTING_LAG3_HASH_SHIFT_LEN  16u
#define DVA_LAG3_HASH_SETTING_LAG3_HASH_SHIFT_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG3_HASH_SETTING_LAG3_HASH_MASK_LSP   0u
#define DVA_LAG3_HASH_SETTING_LAG3_HASH_MASK_LEN   8u
#define DVA_LAG3_HASH_SETTING_LAG3_HASH_MASK_TYPE  DVA_FIELD_TYPE_RW

#define DVA_LAG4_MEMBER_LAG4_PORT_MEMBER_LSP  0u
#define DVA_LAG4_MEMBER_LAG4_PORT_MEMBER_LEN  16u
#define DVA_LAG4_MEMBER_LAG4_PORT_MEMBER_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG4_HASH_SETTING_LAG4_HASH_SHIFT_LSP  8u
#define DVA_LAG4_HASH_SETTING_LAG4_HASH_SHIFT_LEN  16u
#define DVA_LAG4_HASH_SETTING_LAG4_HASH_SHIFT_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG4_HASH_SETTING_LAG4_HASH_MASK_LSP   0u
#define DVA_LAG4_HASH_SETTING_LAG4_HASH_MASK_LEN   8u
#define DVA_LAG4_HASH_SETTING_LAG4_HASH_MASK_TYPE  DVA_FIELD_TYPE_RW

#define DVA_LAG5_MEMBER_LAG5_PORT_MEMBER_LSP  0u
#define DVA_LAG5_MEMBER_LAG5_PORT_MEMBER_LEN  16u
#define DVA_LAG5_MEMBER_LAG5_PORT_MEMBER_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG5_HASH_SETTING_LAG5_HASH_SHIFT_LSP  8u
#define DVA_LAG5_HASH_SETTING_LAG5_HASH_SHIFT_LEN  16u
#define DVA_LAG5_HASH_SETTING_LAG5_HASH_SHIFT_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG5_HASH_SETTING_LAG5_HASH_MASK_LSP   0u
#define DVA_LAG5_HASH_SETTING_LAG5_HASH_MASK_LEN   8u
#define DVA_LAG5_HASH_SETTING_LAG5_HASH_MASK_TYPE  DVA_FIELD_TYPE_RW

#define DVA_LAG6_MEMBER_LAG6_PORT_MEMBER_LSP  0u
#define DVA_LAG6_MEMBER_LAG6_PORT_MEMBER_LEN  16u
#define DVA_LAG6_MEMBER_LAG6_PORT_MEMBER_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG6_HASH_SETTING_LAG6_HASH_SHIFT_LSP  8u
#define DVA_LAG6_HASH_SETTING_LAG6_HASH_SHIFT_LEN  16u
#define DVA_LAG6_HASH_SETTING_LAG6_HASH_SHIFT_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG6_HASH_SETTING_LAG6_HASH_MASK_LSP   0u
#define DVA_LAG6_HASH_SETTING_LAG6_HASH_MASK_LEN   8u
#define DVA_LAG6_HASH_SETTING_LAG6_HASH_MASK_TYPE  DVA_FIELD_TYPE_RW

#define DVA_LAG7_MEMBER_LAG7_PORT_MEMBER_LSP  0u
#define DVA_LAG7_MEMBER_LAG7_PORT_MEMBER_LEN  16u
#define DVA_LAG7_MEMBER_LAG7_PORT_MEMBER_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG7_HASH_SETTING_LAG7_HASH_SHIFT_LSP  8u
#define DVA_LAG7_HASH_SETTING_LAG7_HASH_SHIFT_LEN  16u
#define DVA_LAG7_HASH_SETTING_LAG7_HASH_SHIFT_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG7_HASH_SETTING_LAG7_HASH_MASK_LSP   0u
#define DVA_LAG7_HASH_SETTING_LAG7_HASH_MASK_LEN   8u
#define DVA_LAG7_HASH_SETTING_LAG7_HASH_MASK_TYPE  DVA_FIELD_TYPE_RW

#define DVA_LAG0_BALANCE_MODE_SETTING_0_LAG0_BALANCE_MODE_PROTOCOL_LSP   16u
#define DVA_LAG0_BALANCE_MODE_SETTING_0_LAG0_BALANCE_MODE_PROTOCOL_LEN   8u
#define DVA_LAG0_BALANCE_MODE_SETTING_0_LAG0_BALANCE_MODE_PROTOCOL_TYPE  DVA_FIELD_TYPE_RW
#define DVA_LAG0_BALANCE_MODE_SETTING_0_LAG0_BALANCE_MODE_ETHERTYPE_LSP  0u
#define DVA_LAG0_BALANCE_MODE_SETTING_0_LAG0_BALANCE_MODE_ETHERTYPE_LEN  16u
#define DVA_LAG0_BALANCE_MODE_SETTING_0_LAG0_BALANCE_MODE_ETHERTYPE_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG0_BALANCE_MODE_SETTING_1_LAG0_BALANCE_MODE_L4_DPORT_MASK_LSP  16u
#define DVA_LAG0_BALANCE_MODE_SETTING_1_LAG0_BALANCE_MODE_L4_DPORT_MASK_LEN  16u
#define DVA_LAG0_BALANCE_MODE_SETTING_1_LAG0_BALANCE_MODE_L4_DPORT_MASK_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG0_BALANCE_MODE_SETTING_1_LAG0_BALANCE_MODE_L4_DPORT_LSP       0u
#define DVA_LAG0_BALANCE_MODE_SETTING_1_LAG0_BALANCE_MODE_L4_DPORT_LEN       16u
#define DVA_LAG0_BALANCE_MODE_SETTING_1_LAG0_BALANCE_MODE_L4_DPORT_TYPE      DVA_FIELD_TYPE_RW

#define DVA_LAG0_BALANCE_MODE_SETTING_2_LAG0_BALANCE_MODE_MASK_LSP  0u
#define DVA_LAG0_BALANCE_MODE_SETTING_2_LAG0_BALANCE_MODE_MASK_LEN  4u
#define DVA_LAG0_BALANCE_MODE_SETTING_2_LAG0_BALANCE_MODE_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG1_BALANCE_MODE_SETTING_0_LAG1_BALANCE_MODE_PROTOCOL_LSP   16u
#define DVA_LAG1_BALANCE_MODE_SETTING_0_LAG1_BALANCE_MODE_PROTOCOL_LEN   8u
#define DVA_LAG1_BALANCE_MODE_SETTING_0_LAG1_BALANCE_MODE_PROTOCOL_TYPE  DVA_FIELD_TYPE_RW
#define DVA_LAG1_BALANCE_MODE_SETTING_0_LAG1_BALANCE_MODE_ETHERTYPE_LSP  0u
#define DVA_LAG1_BALANCE_MODE_SETTING_0_LAG1_BALANCE_MODE_ETHERTYPE_LEN  16u
#define DVA_LAG1_BALANCE_MODE_SETTING_0_LAG1_BALANCE_MODE_ETHERTYPE_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG1_BALANCE_MODE_SETTING_1_LAG1_BALANCE_MODE_L4_DPORT_MASK_LSP  16u
#define DVA_LAG1_BALANCE_MODE_SETTING_1_LAG1_BALANCE_MODE_L4_DPORT_MASK_LEN  16u
#define DVA_LAG1_BALANCE_MODE_SETTING_1_LAG1_BALANCE_MODE_L4_DPORT_MASK_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG1_BALANCE_MODE_SETTING_1_LAG1_BALANCE_MODE_L4_DPORT_LSP       0u
#define DVA_LAG1_BALANCE_MODE_SETTING_1_LAG1_BALANCE_MODE_L4_DPORT_LEN       16u
#define DVA_LAG1_BALANCE_MODE_SETTING_1_LAG1_BALANCE_MODE_L4_DPORT_TYPE      DVA_FIELD_TYPE_RW

#define DVA_LAG1_BALANCE_MODE_SETTING_2_LAG1_BALANCE_MODE_MASK_LSP  0u
#define DVA_LAG1_BALANCE_MODE_SETTING_2_LAG1_BALANCE_MODE_MASK_LEN  4u
#define DVA_LAG1_BALANCE_MODE_SETTING_2_LAG1_BALANCE_MODE_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG2_BALANCE_MODE_SETTING_0_LAG2_BALANCE_MODE_PROTOCOL_LSP   16u
#define DVA_LAG2_BALANCE_MODE_SETTING_0_LAG2_BALANCE_MODE_PROTOCOL_LEN   8u
#define DVA_LAG2_BALANCE_MODE_SETTING_0_LAG2_BALANCE_MODE_PROTOCOL_TYPE  DVA_FIELD_TYPE_RW
#define DVA_LAG2_BALANCE_MODE_SETTING_0_LAG2_BALANCE_MODE_ETHERTYPE_LSP  0u
#define DVA_LAG2_BALANCE_MODE_SETTING_0_LAG2_BALANCE_MODE_ETHERTYPE_LEN  16u
#define DVA_LAG2_BALANCE_MODE_SETTING_0_LAG2_BALANCE_MODE_ETHERTYPE_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG2_BALANCE_MODE_SETTING_1_LAG2_BALANCE_MODE_L4_DPORT_MASK_LSP  16u
#define DVA_LAG2_BALANCE_MODE_SETTING_1_LAG2_BALANCE_MODE_L4_DPORT_MASK_LEN  16u
#define DVA_LAG2_BALANCE_MODE_SETTING_1_LAG2_BALANCE_MODE_L4_DPORT_MASK_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG2_BALANCE_MODE_SETTING_1_LAG2_BALANCE_MODE_L4_DPORT_LSP       0u
#define DVA_LAG2_BALANCE_MODE_SETTING_1_LAG2_BALANCE_MODE_L4_DPORT_LEN       16u
#define DVA_LAG2_BALANCE_MODE_SETTING_1_LAG2_BALANCE_MODE_L4_DPORT_TYPE      DVA_FIELD_TYPE_RW

#define DVA_LAG2_BALANCE_MODE_SETTING_2_LAG2_BALANCE_MODE_MASK_LSP  0u
#define DVA_LAG2_BALANCE_MODE_SETTING_2_LAG2_BALANCE_MODE_MASK_LEN  4u
#define DVA_LAG2_BALANCE_MODE_SETTING_2_LAG2_BALANCE_MODE_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG3_BALANCE_MODE_SETTING_0_LAG3_BALANCE_MODE_PROTOCOL_LSP   16u
#define DVA_LAG3_BALANCE_MODE_SETTING_0_LAG3_BALANCE_MODE_PROTOCOL_LEN   8u
#define DVA_LAG3_BALANCE_MODE_SETTING_0_LAG3_BALANCE_MODE_PROTOCOL_TYPE  DVA_FIELD_TYPE_RW
#define DVA_LAG3_BALANCE_MODE_SETTING_0_LAG3_BALANCE_MODE_ETHERTYPE_LSP  0u
#define DVA_LAG3_BALANCE_MODE_SETTING_0_LAG3_BALANCE_MODE_ETHERTYPE_LEN  16u
#define DVA_LAG3_BALANCE_MODE_SETTING_0_LAG3_BALANCE_MODE_ETHERTYPE_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG3_BALANCE_MODE_SETTING_1_LAG3_BALANCE_MODE_L4_DPORT_MASK_LSP  16u
#define DVA_LAG3_BALANCE_MODE_SETTING_1_LAG3_BALANCE_MODE_L4_DPORT_MASK_LEN  16u
#define DVA_LAG3_BALANCE_MODE_SETTING_1_LAG3_BALANCE_MODE_L4_DPORT_MASK_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG3_BALANCE_MODE_SETTING_1_LAG3_BALANCE_MODE_L4_DPORT_LSP       0u
#define DVA_LAG3_BALANCE_MODE_SETTING_1_LAG3_BALANCE_MODE_L4_DPORT_LEN       16u
#define DVA_LAG3_BALANCE_MODE_SETTING_1_LAG3_BALANCE_MODE_L4_DPORT_TYPE      DVA_FIELD_TYPE_RW

#define DVA_LAG3_BALANCE_MODE_SETTING_2_LAG3_BALANCE_MODE_MASK_LSP  0u
#define DVA_LAG3_BALANCE_MODE_SETTING_2_LAG3_BALANCE_MODE_MASK_LEN  4u
#define DVA_LAG3_BALANCE_MODE_SETTING_2_LAG3_BALANCE_MODE_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG4_BALANCE_MODE_SETTING_0_LAG4_BALANCE_MODE_PROTOCOL_LSP   16u
#define DVA_LAG4_BALANCE_MODE_SETTING_0_LAG4_BALANCE_MODE_PROTOCOL_LEN   8u
#define DVA_LAG4_BALANCE_MODE_SETTING_0_LAG4_BALANCE_MODE_PROTOCOL_TYPE  DVA_FIELD_TYPE_RW
#define DVA_LAG4_BALANCE_MODE_SETTING_0_LAG4_BALANCE_MODE_ETHERTYPE_LSP  0u
#define DVA_LAG4_BALANCE_MODE_SETTING_0_LAG4_BALANCE_MODE_ETHERTYPE_LEN  16u
#define DVA_LAG4_BALANCE_MODE_SETTING_0_LAG4_BALANCE_MODE_ETHERTYPE_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG4_BALANCE_MODE_SETTING_1_LAG4_BALANCE_MODE_L4_DPORT_MASK_LSP  16u
#define DVA_LAG4_BALANCE_MODE_SETTING_1_LAG4_BALANCE_MODE_L4_DPORT_MASK_LEN  16u
#define DVA_LAG4_BALANCE_MODE_SETTING_1_LAG4_BALANCE_MODE_L4_DPORT_MASK_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG4_BALANCE_MODE_SETTING_1_LAG4_BALANCE_MODE_L4_DPORT_LSP       0u
#define DVA_LAG4_BALANCE_MODE_SETTING_1_LAG4_BALANCE_MODE_L4_DPORT_LEN       16u
#define DVA_LAG4_BALANCE_MODE_SETTING_1_LAG4_BALANCE_MODE_L4_DPORT_TYPE      DVA_FIELD_TYPE_RW

#define DVA_LAG4_BALANCE_MODE_SETTING_2_LAG4_BALANCE_MODE_MASK_LSP  0u
#define DVA_LAG4_BALANCE_MODE_SETTING_2_LAG4_BALANCE_MODE_MASK_LEN  4u
#define DVA_LAG4_BALANCE_MODE_SETTING_2_LAG4_BALANCE_MODE_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG5_BALANCE_MODE_SETTING_0_LAG5_BALANCE_MODE_PROTOCOL_LSP   16u
#define DVA_LAG5_BALANCE_MODE_SETTING_0_LAG5_BALANCE_MODE_PROTOCOL_LEN   8u
#define DVA_LAG5_BALANCE_MODE_SETTING_0_LAG5_BALANCE_MODE_PROTOCOL_TYPE  DVA_FIELD_TYPE_RW
#define DVA_LAG5_BALANCE_MODE_SETTING_0_LAG5_BALANCE_MODE_ETHERTYPE_LSP  0u
#define DVA_LAG5_BALANCE_MODE_SETTING_0_LAG5_BALANCE_MODE_ETHERTYPE_LEN  16u
#define DVA_LAG5_BALANCE_MODE_SETTING_0_LAG5_BALANCE_MODE_ETHERTYPE_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG5_BALANCE_MODE_SETTING_1_LAG5_BALANCE_MODE_L4_DPORT_MASK_LSP  16u
#define DVA_LAG5_BALANCE_MODE_SETTING_1_LAG5_BALANCE_MODE_L4_DPORT_MASK_LEN  16u
#define DVA_LAG5_BALANCE_MODE_SETTING_1_LAG5_BALANCE_MODE_L4_DPORT_MASK_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG5_BALANCE_MODE_SETTING_1_LAG5_BALANCE_MODE_L4_DPORT_LSP       0u
#define DVA_LAG5_BALANCE_MODE_SETTING_1_LAG5_BALANCE_MODE_L4_DPORT_LEN       16u
#define DVA_LAG5_BALANCE_MODE_SETTING_1_LAG5_BALANCE_MODE_L4_DPORT_TYPE      DVA_FIELD_TYPE_RW

#define DVA_LAG5_BALANCE_MODE_SETTING_2_LAG5_BALANCE_MODE_MASK_LSP  0u
#define DVA_LAG5_BALANCE_MODE_SETTING_2_LAG5_BALANCE_MODE_MASK_LEN  4u
#define DVA_LAG5_BALANCE_MODE_SETTING_2_LAG5_BALANCE_MODE_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG6_BALANCE_MODE_SETTING_0_LAG6_BALANCE_MODE_PROTOCOL_LSP   16u
#define DVA_LAG6_BALANCE_MODE_SETTING_0_LAG6_BALANCE_MODE_PROTOCOL_LEN   8u
#define DVA_LAG6_BALANCE_MODE_SETTING_0_LAG6_BALANCE_MODE_PROTOCOL_TYPE  DVA_FIELD_TYPE_RW
#define DVA_LAG6_BALANCE_MODE_SETTING_0_LAG6_BALANCE_MODE_ETHERTYPE_LSP  0u
#define DVA_LAG6_BALANCE_MODE_SETTING_0_LAG6_BALANCE_MODE_ETHERTYPE_LEN  16u
#define DVA_LAG6_BALANCE_MODE_SETTING_0_LAG6_BALANCE_MODE_ETHERTYPE_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG6_BALANCE_MODE_SETTING_1_LAG6_BALANCE_MODE_L4_DPORT_MASK_LSP  16u
#define DVA_LAG6_BALANCE_MODE_SETTING_1_LAG6_BALANCE_MODE_L4_DPORT_MASK_LEN  16u
#define DVA_LAG6_BALANCE_MODE_SETTING_1_LAG6_BALANCE_MODE_L4_DPORT_MASK_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG6_BALANCE_MODE_SETTING_1_LAG6_BALANCE_MODE_L4_DPORT_LSP       0u
#define DVA_LAG6_BALANCE_MODE_SETTING_1_LAG6_BALANCE_MODE_L4_DPORT_LEN       16u
#define DVA_LAG6_BALANCE_MODE_SETTING_1_LAG6_BALANCE_MODE_L4_DPORT_TYPE      DVA_FIELD_TYPE_RW

#define DVA_LAG6_BALANCE_MODE_SETTING_2_LAG6_BALANCE_MODE_MASK_LSP  0u
#define DVA_LAG6_BALANCE_MODE_SETTING_2_LAG6_BALANCE_MODE_MASK_LEN  4u
#define DVA_LAG6_BALANCE_MODE_SETTING_2_LAG6_BALANCE_MODE_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG7_BALANCE_MODE_SETTING_0_LAG7_BALANCE_MODE_PROTOCOL_LSP   16u
#define DVA_LAG7_BALANCE_MODE_SETTING_0_LAG7_BALANCE_MODE_PROTOCOL_LEN   8u
#define DVA_LAG7_BALANCE_MODE_SETTING_0_LAG7_BALANCE_MODE_PROTOCOL_TYPE  DVA_FIELD_TYPE_RW
#define DVA_LAG7_BALANCE_MODE_SETTING_0_LAG7_BALANCE_MODE_ETHERTYPE_LSP  0u
#define DVA_LAG7_BALANCE_MODE_SETTING_0_LAG7_BALANCE_MODE_ETHERTYPE_LEN  16u
#define DVA_LAG7_BALANCE_MODE_SETTING_0_LAG7_BALANCE_MODE_ETHERTYPE_TYPE DVA_FIELD_TYPE_RW

#define DVA_LAG7_BALANCE_MODE_SETTING_1_LAG7_BALANCE_MODE_L4_DPORT_MASK_LSP  16u
#define DVA_LAG7_BALANCE_MODE_SETTING_1_LAG7_BALANCE_MODE_L4_DPORT_MASK_LEN  16u
#define DVA_LAG7_BALANCE_MODE_SETTING_1_LAG7_BALANCE_MODE_L4_DPORT_MASK_TYPE DVA_FIELD_TYPE_RW
#define DVA_LAG7_BALANCE_MODE_SETTING_1_LAG7_BALANCE_MODE_L4_DPORT_LSP       0u
#define DVA_LAG7_BALANCE_MODE_SETTING_1_LAG7_BALANCE_MODE_L4_DPORT_LEN       16u
#define DVA_LAG7_BALANCE_MODE_SETTING_1_LAG7_BALANCE_MODE_L4_DPORT_TYPE      DVA_FIELD_TYPE_RW

#define DVA_LAG7_BALANCE_MODE_SETTING_2_LAG7_BALANCE_MODE_MASK_LSP  0u
#define DVA_LAG7_BALANCE_MODE_SETTING_2_LAG7_BALANCE_MODE_MASK_LEN  4u
#define DVA_LAG7_BALANCE_MODE_SETTING_2_LAG7_BALANCE_MODE_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_LA_ENABLE_SETTING_LA_EN_LSP  0u
#define DVA_LA_ENABLE_SETTING_LA_EN_LEN  16u
#define DVA_LA_ENABLE_SETTING_LA_EN_TYPE DVA_FIELD_TYPE_RW

#define DVA_LA_COLLECTING_SETTING_LA_RX_EN_LSP  0u
#define DVA_LA_COLLECTING_SETTING_LA_RX_EN_LEN  16u
#define DVA_LA_COLLECTING_SETTING_LA_RX_EN_TYPE DVA_FIELD_TYPE_RW

#define DVA_LA_DISTRIBUTING_SETTING_LA_TX_EN_LSP  0u
#define DVA_LA_DISTRIBUTING_SETTING_LA_TX_EN_LEN  16u
#define DVA_LA_DISTRIBUTING_SETTING_LA_TX_EN_TYPE DVA_FIELD_TYPE_RW

#define DVA_LA_TX_CPU_TAG_SETTING_LA_TX_CPU_EN_LSP  0u
#define DVA_LA_TX_CPU_TAG_SETTING_LA_TX_CPU_EN_LEN  16u
#define DVA_LA_TX_CPU_TAG_SETTING_LA_TX_CPU_EN_TYPE DVA_FIELD_TYPE_RW

#define DVA_LA_PACKET_CHECK_SETTING_0_TYPE2_CHECK_EN_LSP  0u
#define DVA_LA_PACKET_CHECK_SETTING_0_TYPE2_CHECK_EN_LEN  16u
#define DVA_LA_PACKET_CHECK_SETTING_0_TYPE2_CHECK_EN_TYPE DVA_FIELD_TYPE_RW

#define DVA_LA_PACKET_CHECK_SETTING_1_SUBTYPE_CHECK_EN_LSP  0u
#define DVA_LA_PACKET_CHECK_SETTING_1_SUBTYPE_CHECK_EN_LEN  16u
#define DVA_LA_PACKET_CHECK_SETTING_1_SUBTYPE_CHECK_EN_TYPE DVA_FIELD_TYPE_RW

#define DVA_FUSA_PG_LOCK_DMY_LINK_AGGREGATE_FUSA_PG_LOCK_DMY_LINK_AGGREGATE_LSP  0u
#define DVA_FUSA_PG_LOCK_DMY_LINK_AGGREGATE_FUSA_PG_LOCK_DMY_LINK_AGGREGATE_LEN  1u
#define DVA_FUSA_PG_LOCK_DMY_LINK_AGGREGATE_FUSA_PG_LOCK_DMY_LINK_AGGREGATE_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_LINK_AGGREGATE_H_ */