/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_CPU_ENGINE_H_
#define DVA_RTKAS_REG_FIELD_FILE_CPU_ENGINE_H_

#ifdef DVA_FILE_CPU_ENGINE
/* File: CPU Engine */
#define DVA_CPU_DMY_0_CPU_DMY_0_LSP  0u
#define DVA_CPU_DMY_0_CPU_DMY_0_LEN  32u
#define DVA_CPU_DMY_0_CPU_DMY_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_DMY_1_CPU_DMY_1_LSP  0u
#define DVA_CPU_DMY_1_CPU_DMY_1_LEN  32u
#define DVA_CPU_DMY_1_CPU_DMY_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_DMY_2_CPU_DMY_2_LSP  0u
#define DVA_CPU_DMY_2_CPU_DMY_2_LEN  32u
#define DVA_CPU_DMY_2_CPU_DMY_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDER_SUBTRACTOR_CONTROL0_AUGEND_LSB_LSP  0u
#define DVA_ADDER_SUBTRACTOR_CONTROL0_AUGEND_LSB_LEN  32u
#define DVA_ADDER_SUBTRACTOR_CONTROL0_AUGEND_LSB_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDER_SUBTRACTOR_CONTROL1_AUGEND_MSB_LSP  0u
#define DVA_ADDER_SUBTRACTOR_CONTROL1_AUGEND_MSB_LEN  8u
#define DVA_ADDER_SUBTRACTOR_CONTROL1_AUGEND_MSB_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDER_SUBTRACTOR_CONTROL2_ADDEND_LSB_LSP  0u
#define DVA_ADDER_SUBTRACTOR_CONTROL2_ADDEND_LSB_LEN  32u
#define DVA_ADDER_SUBTRACTOR_CONTROL2_ADDEND_LSB_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDER_SUBTRACTOR_CONTROL3_ADDEND_MSB_LSP  0u
#define DVA_ADDER_SUBTRACTOR_CONTROL3_ADDEND_MSB_LEN  8u
#define DVA_ADDER_SUBTRACTOR_CONTROL3_ADDEND_MSB_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDER_SUBTRACTOR_CONTROL4_OVERFLOW_LSP     8u
#define DVA_ADDER_SUBTRACTOR_CONTROL4_OVERFLOW_LEN     1u
#define DVA_ADDER_SUBTRACTOR_CONTROL4_OVERFLOW_TYPE    DVA_FIELD_TYPE_RO
#define DVA_ADDER_SUBTRACTOR_CONTROL4_ADD_SUB_SEL_LSP  0u
#define DVA_ADDER_SUBTRACTOR_CONTROL4_ADD_SUB_SEL_LEN  1u
#define DVA_ADDER_SUBTRACTOR_CONTROL4_ADD_SUB_SEL_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDER_SUBTRACTOR_CONTROL5_SUM_LSB_LSP  0u
#define DVA_ADDER_SUBTRACTOR_CONTROL5_SUM_LSB_LEN  32u
#define DVA_ADDER_SUBTRACTOR_CONTROL5_SUM_LSB_TYPE DVA_FIELD_TYPE_RO

#define DVA_ADDER_SUBTRACTOR_CONTROL6_SUM_MSB_LSP  0u
#define DVA_ADDER_SUBTRACTOR_CONTROL6_SUM_MSB_LEN  8u
#define DVA_ADDER_SUBTRACTOR_CONTROL6_SUM_MSB_TYPE DVA_FIELD_TYPE_RO

#define DVA_BACKDOOR_CONTROL0_BACKDOOR_EXECUTE_LSP  31u
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_EXECUTE_LEN  1u
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_EXECUTE_TYPE DVA_FIELD_TYPE_RWS
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_CMD_LSP      30u
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_CMD_LEN      1u
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_CMD_TYPE     DVA_FIELD_TYPE_RW
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_DATA_3_LSP   24u
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_DATA_3_LEN   4u
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_DATA_3_TYPE  DVA_FIELD_TYPE_RWS
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_ADDR_LSP     0u
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_ADDR_LEN     7u
#define DVA_BACKDOOR_CONTROL0_BACKDOOR_ADDR_TYPE    DVA_FIELD_TYPE_RW

#define DVA_BACKDOOR_CONTROL1_BACKDOOR_DATA_0_LSP  0u
#define DVA_BACKDOOR_CONTROL1_BACKDOOR_DATA_0_LEN  32u
#define DVA_BACKDOOR_CONTROL1_BACKDOOR_DATA_0_TYPE DVA_FIELD_TYPE_RWS

#define DVA_BACKDOOR_CONTROL2_BACKDOOR_DATA_1_LSP  0u
#define DVA_BACKDOOR_CONTROL2_BACKDOOR_DATA_1_LEN  32u
#define DVA_BACKDOOR_CONTROL2_BACKDOOR_DATA_1_TYPE DVA_FIELD_TYPE_RWS

#define DVA_BACKDOOR_CONTROL3_BACKDOOR_DATA_2_LSP  0u
#define DVA_BACKDOOR_CONTROL3_BACKDOOR_DATA_2_LEN  32u
#define DVA_BACKDOOR_CONTROL3_BACKDOOR_DATA_2_TYPE DVA_FIELD_TYPE_RWS

#define DVA_BACKDOOR_CONTROL4_QBV_RD_DATA_3_LSP    24u
#define DVA_BACKDOOR_CONTROL4_QBV_RD_DATA_3_LEN    4u
#define DVA_BACKDOOR_CONTROL4_QBV_RD_DATA_3_TYPE   DVA_FIELD_TYPE_RW
#define DVA_BACKDOOR_CONTROL4_QBV_HW_PREFETCH_LSP  16u
#define DVA_BACKDOOR_CONTROL4_QBV_HW_PREFETCH_LEN  1u
#define DVA_BACKDOOR_CONTROL4_QBV_HW_PREFETCH_TYPE DVA_FIELD_TYPE_RWS
#define DVA_BACKDOOR_CONTROL4_TBLMODIFY_LSP        1u
#define DVA_BACKDOOR_CONTROL4_TBLMODIFY_LEN        1u
#define DVA_BACKDOOR_CONTROL4_TBLMODIFY_TYPE       DVA_FIELD_TYPE_RO
#define DVA_BACKDOOR_CONTROL4_TBLACC_RD_RDY_LSP    0u
#define DVA_BACKDOOR_CONTROL4_TBLACC_RD_RDY_LEN    1u
#define DVA_BACKDOOR_CONTROL4_TBLACC_RD_RDY_TYPE   DVA_FIELD_TYPE_RWS

#define DVA_BACKDOOR_CONTROL5_QBV_RD_DATA_0_LSP  0u
#define DVA_BACKDOOR_CONTROL5_QBV_RD_DATA_0_LEN  32u
#define DVA_BACKDOOR_CONTROL5_QBV_RD_DATA_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_BACKDOOR_CONTROL6_QBV_RD_DATA_1_LSP  0u
#define DVA_BACKDOOR_CONTROL6_QBV_RD_DATA_1_LEN  32u
#define DVA_BACKDOOR_CONTROL6_QBV_RD_DATA_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_BACKDOOR_CONTROL7_QBV_RD_DATA_2_LSP  0u
#define DVA_BACKDOOR_CONTROL7_QBV_RD_DATA_2_LEN  32u
#define DVA_BACKDOOR_CONTROL7_QBV_RD_DATA_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_PLATFORM_BIST_ISR_LSP          17u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_PLATFORM_BIST_ISR_LEN          1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_PLATFORM_BIST_ISR_TYPE         DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_MACPHY_1_IRQ_ISR_LSP           16u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_MACPHY_1_IRQ_ISR_LEN           1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_MACPHY_1_IRQ_ISR_TYPE          DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_MACPHY_0_IRQ_ISR_LSP           15u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_MACPHY_0_IRQ_ISR_LEN           1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_MACPHY_0_IRQ_ISR_TYPE          DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_EXT_ISR_LSP             14u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_EXT_ISR_LEN             1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_EXT_ISR_TYPE            DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_MAC_GPO2_ISR_LSP        13u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_MAC_GPO2_ISR_LEN        1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_MAC_GPO2_ISR_TYPE       DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_MAC_GPO1_ISR_LSP        12u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_MAC_GPO1_ISR_LEN        1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_MAC_GPO1_ISR_TYPE       DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_MAC_GPO0_ISR_LSP        11u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_MAC_GPO0_ISR_LEN        1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_MAC_GPO0_ISR_TYPE       DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_GLOB_GPO1_ISR_LSP       10u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_GLOB_GPO1_ISR_LEN       1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_GLOB_GPO1_ISR_TYPE      DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_GLOB_GPO0_ISR_LSP       9u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_GLOB_GPO0_ISR_LEN       1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_GLOB_GPO0_ISR_TYPE      DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_CPU_ISR_LSP             8u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_CPU_ISR_LEN             1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OP_FSM_CPU_ISR_TYPE            DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_PTP_INTR_ISR_LSP               6u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_PTP_INTR_ISR_LEN               1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_PTP_INTR_ISR_TYPE              DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_ECC_TEST_MODE_ISR_LSP          5u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_ECC_TEST_MODE_ISR_LEN          1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_ECC_TEST_MODE_ISR_TYPE         DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_BOCSH_RESET_ISR_LSP            4u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_BOCSH_RESET_ISR_LEN            1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_BOCSH_RESET_ISR_TYPE           DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_MAC_BOOTUP_MBIST_FAIL_ISR_LSP  3u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_MAC_BOOTUP_MBIST_FAIL_ISR_LEN  1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_MAC_BOOTUP_MBIST_FAIL_ISR_TYPE DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OCP_TIMEOUT_ISR_LSP            2u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OCP_TIMEOUT_ISR_LEN            1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_OCP_TIMEOUT_ISR_TYPE           DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_QBV_EXTCPU_READ_ISR_LSP        1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_QBV_EXTCPU_READ_ISR_LEN        1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_QBV_EXTCPU_READ_ISR_TYPE       DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_QBV_CFG_RDY_ISR_LSP            0u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_QBV_CFG_RDY_ISR_LEN            1u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS_QBV_CFG_RDY_ISR_TYPE           DVA_FIELD_TYPE_RW1C

#define DVA_INTERNAL_CPU_INTERRUPT_MASK_PLATFORM_BIST_IMR_LSP          17u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_PLATFORM_BIST_IMR_LEN          1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_PLATFORM_BIST_IMR_TYPE         DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_MACPHY_1_IRQ_IMR_LSP           16u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_MACPHY_1_IRQ_IMR_LEN           1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_MACPHY_1_IRQ_IMR_TYPE          DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_MACPHY_0_IRQ_IMR_LSP           15u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_MACPHY_0_IRQ_IMR_LEN           1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_MACPHY_0_IRQ_IMR_TYPE          DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_EXT_IMR_LSP             14u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_EXT_IMR_LEN             1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_EXT_IMR_TYPE            DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_MAC_GPO2_IMR_LSP        13u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_MAC_GPO2_IMR_LEN        1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_MAC_GPO2_IMR_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_MAC_GPO1_IMR_LSP        12u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_MAC_GPO1_IMR_LEN        1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_MAC_GPO1_IMR_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_MAC_GPO0_IMR_LSP        11u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_MAC_GPO0_IMR_LEN        1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_MAC_GPO0_IMR_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_GLOB_GPO1_IMR_LSP       10u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_GLOB_GPO1_IMR_LEN       1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_GLOB_GPO1_IMR_TYPE      DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_GLOB_GPO0_IMR_LSP       9u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_GLOB_GPO0_IMR_LEN       1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_GLOB_GPO0_IMR_TYPE      DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_CPU_IMR_LSP             8u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_CPU_IMR_LEN             1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OP_FSM_CPU_IMR_TYPE            DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_PTP_INTR_IMR_LSP               6u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_PTP_INTR_IMR_LEN               1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_PTP_INTR_IMR_TYPE              DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_ECC_TEST_MODE_IMR_LSP          5u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_ECC_TEST_MODE_IMR_LEN          1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_ECC_TEST_MODE_IMR_TYPE         DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_BOCSH_RESET_IMR_LSP            4u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_BOCSH_RESET_IMR_LEN            1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_BOCSH_RESET_IMR_TYPE           DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_MAC_BOOTUP_MBIST_FAIL_IMR_LSP  3u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_MAC_BOOTUP_MBIST_FAIL_IMR_LEN  1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_MAC_BOOTUP_MBIST_FAIL_IMR_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OCP_TIMEOUT_IMR_LSP            2u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OCP_TIMEOUT_IMR_LEN            1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_OCP_TIMEOUT_IMR_TYPE           DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_QBV_EXTCPU_READ_IMR_LSP        1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_QBV_EXTCPU_READ_IMR_LEN        1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_QBV_EXTCPU_READ_IMR_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_QBV_CFG_RDY_IMR_LSP            0u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_QBV_CFG_RDY_IMR_LEN            1u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK_QBV_CFG_RDY_IMR_TYPE           DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_VARIABLE_CONTROL_VAR_REG_WR_EN_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE_CONTROL_VAR_REG_WR_EN_LEN  1u
#define DVA_INTERNAL_CPU_VARIABLE_CONTROL_VAR_REG_WR_EN_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_VARIABLE0_VAR_REG_0_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE0_VAR_REG_0_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE0_VAR_REG_0_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE1_VAR_REG_1_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE1_VAR_REG_1_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE1_VAR_REG_1_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE2_VAR_REG_2_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE2_VAR_REG_2_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE2_VAR_REG_2_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE3_VAR_REG_3_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE3_VAR_REG_3_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE3_VAR_REG_3_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE4_VAR_REG_4_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE4_VAR_REG_4_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE4_VAR_REG_4_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE5_VAR_REG_5_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE5_VAR_REG_5_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE5_VAR_REG_5_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE6_VAR_REG_6_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE6_VAR_REG_6_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE6_VAR_REG_6_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE7_VAR_REG_7_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE7_VAR_REG_7_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE7_VAR_REG_7_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE8_VAR_REG_8_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE8_VAR_REG_8_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE8_VAR_REG_8_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE9_VAR_REG_9_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE9_VAR_REG_9_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE9_VAR_REG_9_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE10_VAR_REG_10_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE10_VAR_REG_10_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE10_VAR_REG_10_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE11_VAR_REG_11_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE11_VAR_REG_11_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE11_VAR_REG_11_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE12_VAR_REG_12_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE12_VAR_REG_12_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE12_VAR_REG_12_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE13_VAR_REG_13_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE13_VAR_REG_13_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE13_VAR_REG_13_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE14_VAR_REG_14_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE14_VAR_REG_14_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE14_VAR_REG_14_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE15_VAR_REG_15_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE15_VAR_REG_15_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE15_VAR_REG_15_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE16_VAR_REG_16_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE16_VAR_REG_16_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE16_VAR_REG_16_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE17_VAR_REG_17_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE17_VAR_REG_17_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE17_VAR_REG_17_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE18_VAR_REG_18_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE18_VAR_REG_18_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE18_VAR_REG_18_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_VARIABLE19_VAR_REG_19_LSP  0u
#define DVA_INTERNAL_CPU_VARIABLE19_VAR_REG_19_LEN  32u
#define DVA_INTERNAL_CPU_VARIABLE19_VAR_REG_19_TYPE DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_INTERRUPT_STATUS0_OPFSM_ECC_ISR_LSP        30u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS0_OPFSM_ECC_ISR_LEN        2u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS0_OPFSM_ECC_ISR_TYPE       DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS0_EFUSE_MATCH_ERR_ISR_LSP  16u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS0_EFUSE_MATCH_ERR_ISR_LEN  3u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS0_EFUSE_MATCH_ERR_ISR_TYPE DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS0_TCAM_MATCH_ERR_ISR_LSP   0u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS0_TCAM_MATCH_ERR_ISR_LEN   9u
#define DVA_INTERNAL_CPU_INTERRUPT_STATUS0_TCAM_MATCH_ERR_ISR_TYPE  DVA_FIELD_TYPE_RW1C

#define DVA_INTERNAL_CPU_INTERRUPT_MASK0_OPFSM_ECC_IMR_LSP        30u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK0_OPFSM_ECC_IMR_LEN        2u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK0_OPFSM_ECC_IMR_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK0_EFUSE_MATCH_ERR_IMR_LSP  16u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK0_EFUSE_MATCH_ERR_IMR_LEN  3u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK0_EFUSE_MATCH_ERR_IMR_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_INTERRUPT_MASK0_TCAM_MATCH_ERR_IMR_LSP   0u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK0_TCAM_MATCH_ERR_IMR_LEN   9u
#define DVA_INTERNAL_CPU_INTERRUPT_MASK0_TCAM_MATCH_ERR_IMR_TYPE  DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_POLLING_INTERNAL_POL_LSP  0u
#define DVA_INTERNAL_CPU_POLLING_INTERNAL_POL_LEN  32u
#define DVA_INTERNAL_CPU_POLLING_INTERNAL_POL_TYPE DVA_FIELD_TYPE_RO

#define DVA_POWER_SAVING_CONTROL0_SYSCLK_GATE_EN_LSP    31u
#define DVA_POWER_SAVING_CONTROL0_SYSCLK_GATE_EN_LEN    1u
#define DVA_POWER_SAVING_CONTROL0_SYSCLK_GATE_EN_TYPE   DVA_FIELD_TYPE_RW
#define DVA_POWER_SAVING_CONTROL0_SYSCLK_GATE_MASK_LSP  0u
#define DVA_POWER_SAVING_CONTROL0_SYSCLK_GATE_MASK_LEN  16u
#define DVA_POWER_SAVING_CONTROL0_SYSCLK_GATE_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_POWER_SAVING_CONTROL1_SYSCLK_GATE_MAXDLY_LSP  0u
#define DVA_POWER_SAVING_CONTROL1_SYSCLK_GATE_MAXDLY_LEN  32u
#define DVA_POWER_SAVING_CONTROL1_SYSCLK_GATE_MAXDLY_TYPE DVA_FIELD_TYPE_RW

#define DVA_DESIGN_FOR_MEASTUMENT_ECO_CLK_GATED_CLKRSTINTF_LSP  28u
#define DVA_DESIGN_FOR_MEASTUMENT_ECO_CLK_GATED_CLKRSTINTF_LEN  3u
#define DVA_DESIGN_FOR_MEASTUMENT_ECO_CLK_GATED_CLKRSTINTF_TYPE DVA_FIELD_TYPE_RW
#define DVA_DESIGN_FOR_MEASTUMENT_ECO_CLK_GATED_LSP             8u
#define DVA_DESIGN_FOR_MEASTUMENT_ECO_CLK_GATED_LEN             16u
#define DVA_DESIGN_FOR_MEASTUMENT_ECO_CLK_GATED_TYPE            DVA_FIELD_TYPE_RW
#define DVA_DESIGN_FOR_MEASTUMENT_OP_FSM_PHYRSTB_EN_LSP         2u
#define DVA_DESIGN_FOR_MEASTUMENT_OP_FSM_PHYRSTB_EN_LEN         1u
#define DVA_DESIGN_FOR_MEASTUMENT_OP_FSM_PHYRSTB_EN_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_DESIGN_FOR_MEASTUMENT_OP_FSM_DISB_EN_LSP            1u
#define DVA_DESIGN_FOR_MEASTUMENT_OP_FSM_DISB_EN_LEN            1u
#define DVA_DESIGN_FOR_MEASTUMENT_OP_FSM_DISB_EN_TYPE           DVA_FIELD_TYPE_RWS
#define DVA_DESIGN_FOR_MEASTUMENT_SHDN_AFE_PAD_EN_LSP           0u
#define DVA_DESIGN_FOR_MEASTUMENT_SHDN_AFE_PAD_EN_LEN           1u
#define DVA_DESIGN_FOR_MEASTUMENT_SHDN_AFE_PAD_EN_TYPE          DVA_FIELD_TYPE_RWS

#define DVA_SOFTWARE_INTERRUPT_CPU_SW_EVENT_NUM_2_LSP  24u
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_EVENT_NUM_2_LEN  8u
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_EVENT_NUM_2_TYPE DVA_FIELD_TYPE_RW
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_EVENT_NUM_1_LSP  16u
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_EVENT_NUM_1_LEN  8u
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_EVENT_NUM_1_TYPE DVA_FIELD_TYPE_RW
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_EVENT_NUM_0_LSP  8u
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_EVENT_NUM_0_LEN  8u
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_EVENT_NUM_0_TYPE DVA_FIELD_TYPE_RW
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_INT_LSP          0u
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_INT_LEN          1u
#define DVA_SOFTWARE_INTERRUPT_CPU_SW_INT_TYPE         DVA_FIELD_TYPE_RW

#define DVA_SPI_LOAD_IROM_RESULT_SPI_LOAD_CODE_FAIL_LSP  31u
#define DVA_SPI_LOAD_IROM_RESULT_SPI_LOAD_CODE_FAIL_LEN  1u
#define DVA_SPI_LOAD_IROM_RESULT_SPI_LOAD_CODE_FAIL_TYPE DVA_FIELD_TYPE_RO
#define DVA_SPI_LOAD_IROM_RESULT_SPI_CRC16_LSP           0u
#define DVA_SPI_LOAD_IROM_RESULT_SPI_CRC16_LEN           16u
#define DVA_SPI_LOAD_IROM_RESULT_SPI_CRC16_TYPE          DVA_FIELD_TYPE_RO

#define DVA_CPU_DMY_3_CPU_DMY_3_LSP  0u
#define DVA_CPU_DMY_3_CPU_DMY_3_LEN  32u
#define DVA_CPU_DMY_3_CPU_DMY_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_DMY_4_CPU_DMY_4_LSP  0u
#define DVA_CPU_DMY_4_CPU_DMY_4_LEN  32u
#define DVA_CPU_DMY_4_CPU_DMY_4_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_DMY_5_CPU_DMY_5_LSP  0u
#define DVA_CPU_DMY_5_CPU_DMY_5_LEN  32u
#define DVA_CPU_DMY_5_CPU_DMY_5_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_DMY_6_CPU_DMY_6_LSP  0u
#define DVA_CPU_DMY_6_CPU_DMY_6_LEN  32u
#define DVA_CPU_DMY_6_CPU_DMY_6_TYPE DVA_FIELD_TYPE_RW

#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P3_LSP  24u
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P3_LEN  8u
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P3_TYPE DVA_FIELD_TYPE_RO
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P2_LSP  16u
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P2_LEN  8u
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P2_TYPE DVA_FIELD_TYPE_RO
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P1_LSP  8u
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P1_LEN  8u
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P1_TYPE DVA_FIELD_TYPE_RO
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P0_LSP  0u
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P0_LEN  8u
#define DVA_HW_POWER_ON_STATE0_PWRON_CS_P0_TYPE DVA_FIELD_TYPE_RO

#define DVA_HW_POWER_ON_STATE1_PHY_OK_A_DONE_LSP  31u
#define DVA_HW_POWER_ON_STATE1_PHY_OK_A_DONE_LEN  1u
#define DVA_HW_POWER_ON_STATE1_PHY_OK_A_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_HW_POWER_ON_STATE1_PWRON_CS_P5_LSP    8u
#define DVA_HW_POWER_ON_STATE1_PWRON_CS_P5_LEN    8u
#define DVA_HW_POWER_ON_STATE1_PWRON_CS_P5_TYPE   DVA_FIELD_TYPE_RO
#define DVA_HW_POWER_ON_STATE1_PWRON_CS_P4_LSP    0u
#define DVA_HW_POWER_ON_STATE1_PWRON_CS_P4_LEN    8u
#define DVA_HW_POWER_ON_STATE1_PWRON_CS_P4_TYPE   DVA_FIELD_TYPE_RO

#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P10_LSP  24u
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P10_LEN  8u
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P10_TYPE DVA_FIELD_TYPE_RO
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P9_LSP   16u
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P9_LEN   8u
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P9_TYPE  DVA_FIELD_TYPE_RO
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P7_LSP   8u
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P7_LEN   8u
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P7_TYPE  DVA_FIELD_TYPE_RO
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P6_LSP   0u
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P6_LEN   8u
#define DVA_HW_POWER_ON_STATE2_PWRON_CS_P6_TYPE  DVA_FIELD_TYPE_RO

#define DVA_HW_POWER_ON_STATE3_PWRON_CS_P7_RTPGE_LSP  8u
#define DVA_HW_POWER_ON_STATE3_PWRON_CS_P7_RTPGE_LEN  8u
#define DVA_HW_POWER_ON_STATE3_PWRON_CS_P7_RTPGE_TYPE DVA_FIELD_TYPE_RO
#define DVA_HW_POWER_ON_STATE3_PWRON_CS_P6_RTPGE_LSP  0u
#define DVA_HW_POWER_ON_STATE3_PWRON_CS_P6_RTPGE_LEN  8u
#define DVA_HW_POWER_ON_STATE3_PWRON_CS_P6_RTPGE_TYPE DVA_FIELD_TYPE_RO

#define DVA_TM9_TRACE_PORT_0_TRACE_I0_IVADDR_LSP  0u
#define DVA_TM9_TRACE_PORT_0_TRACE_I0_IVADDR_LEN  32u
#define DVA_TM9_TRACE_PORT_0_TRACE_I0_IVADDR_TYPE DVA_FIELD_TYPE_RO

#define DVA_TM9_TRACE_PORT_1_TRACE_I1_IVADDR_LSP  0u
#define DVA_TM9_TRACE_PORT_1_TRACE_I1_IVADDR_LEN  32u
#define DVA_TM9_TRACE_PORT_1_TRACE_I1_IVADDR_TYPE DVA_FIELD_TYPE_RO

#define DVA_TM9_TRACE_PORT_2_TRACE_PC_LSP  0u
#define DVA_TM9_TRACE_PORT_2_TRACE_PC_LEN  32u
#define DVA_TM9_TRACE_PORT_2_TRACE_PC_TYPE DVA_FIELD_TYPE_RO

#define DVA_MACPHY_INTERRUPT_DETECT_MACPHY_LEVEL_DETECT_LSP  0u
#define DVA_MACPHY_INTERRUPT_DETECT_MACPHY_LEVEL_DETECT_LEN  1u
#define DVA_MACPHY_INTERRUPT_DETECT_MACPHY_LEVEL_DETECT_TYPE DVA_FIELD_TYPE_RW

#define DVA_FUSA_PG_LOCK_DMY_CPU_ENGINE_FUSA_PG_LOCK_DMY_CPU_ENGINE_LSP  0u
#define DVA_FUSA_PG_LOCK_DMY_CPU_ENGINE_FUSA_PG_LOCK_DMY_CPU_ENGINE_LEN  1u
#define DVA_FUSA_PG_LOCK_DMY_CPU_ENGINE_FUSA_PG_LOCK_DMY_CPU_ENGINE_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_CPU_ENGINE_H_ */