/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_KEY_H_
#define DVA_RTKAS_REG_FIELD_FILE_KEY_H_

#ifdef DVA_FILE_KEY
/* File: KEY */
#define DVA_SECURITY_PARA_0_CMAC_DATA_ADDR_LSP  0u
#define DVA_SECURITY_PARA_0_CMAC_DATA_ADDR_LEN  32u
#define DVA_SECURITY_PARA_0_CMAC_DATA_ADDR_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURITY_PARA_1_CMAC_DATA_LEN_LSP  0u
#define DVA_SECURITY_PARA_1_CMAC_DATA_LEN_LEN  32u
#define DVA_SECURITY_PARA_1_CMAC_DATA_LEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURITY_PARA_2_SEC_DMY_0_LSP  0u
#define DVA_SECURITY_PARA_2_SEC_DMY_0_LEN  32u
#define DVA_SECURITY_PARA_2_SEC_DMY_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURITY_PARA_3_SEC_DMY_1_LSP  0u
#define DVA_SECURITY_PARA_3_SEC_DMY_1_LEN  32u
#define DVA_SECURITY_PARA_3_SEC_DMY_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURITY_PARA_4_SEC_DMY_2_LSP  0u
#define DVA_SECURITY_PARA_4_SEC_DMY_2_LEN  32u
#define DVA_SECURITY_PARA_4_SEC_DMY_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURITY_PARA_5_SEC_DMY_3_LSP  0u
#define DVA_SECURITY_PARA_5_SEC_DMY_3_LEN  32u
#define DVA_SECURITY_PARA_5_SEC_DMY_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURITY_PARA_6_SEC_DMY_4_LSP  0u
#define DVA_SECURITY_PARA_6_SEC_DMY_4_LEN  32u
#define DVA_SECURITY_PARA_6_SEC_DMY_4_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURITY_PARA_7_SEC_DMY_5_LSP  0u
#define DVA_SECURITY_PARA_7_SEC_DMY_5_LEN  32u
#define DVA_SECURITY_PARA_7_SEC_DMY_5_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECUREBOOT_MCU_INTR_N_SECUREBOOT_MCU_INTR_N_LSP  0u
#define DVA_SECUREBOOT_MCU_INTR_N_SECUREBOOT_MCU_INTR_N_LEN  15u
#define DVA_SECUREBOOT_MCU_INTR_N_SECUREBOOT_MCU_INTR_N_TYPE DVA_FIELD_TYPE_RW

#define DVA_MCU_INTR_DONE_MCU_ECC_COMPARE_LSP  2u
#define DVA_MCU_INTR_DONE_MCU_ECC_COMPARE_LEN  1u
#define DVA_MCU_INTR_DONE_MCU_ECC_COMPARE_TYPE DVA_FIELD_TYPE_RW
#define DVA_MCU_INTR_DONE_MCU_FAIL_FLAG_LSP    1u
#define DVA_MCU_INTR_DONE_MCU_FAIL_FLAG_LEN    1u
#define DVA_MCU_INTR_DONE_MCU_FAIL_FLAG_TYPE   DVA_FIELD_TYPE_RW
#define DVA_MCU_INTR_DONE_MCU_INTR_DONE_LSP    0u
#define DVA_MCU_INTR_DONE_MCU_INTR_DONE_LEN    1u
#define DVA_MCU_INTR_DONE_MCU_INTR_DONE_TYPE   DVA_FIELD_TYPE_RW

#define DVA_MCU_INTR_CTRL_REG0_MCU_OPCODE_LSP  0u
#define DVA_MCU_INTR_CTRL_REG0_MCU_OPCODE_LEN  16u
#define DVA_MCU_INTR_CTRL_REG0_MCU_OPCODE_TYPE DVA_FIELD_TYPE_RW

#define DVA_DMA_START_ADDR_L_DMA_START_ADDR_L_LSP  0u
#define DVA_DMA_START_ADDR_L_DMA_START_ADDR_L_LEN  16u
#define DVA_DMA_START_ADDR_L_DMA_START_ADDR_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_DMA_START_ADDR_H_DMA_START_ADDR_H_LSP  0u
#define DVA_DMA_START_ADDR_H_DMA_START_ADDR_H_LEN  16u
#define DVA_DMA_START_ADDR_H_DMA_START_ADDR_H_TYPE DVA_FIELD_TYPE_RW

#define DVA_MCU_CONFIG_REG_SCAN_MODE_EN_LSP    7u
#define DVA_MCU_CONFIG_REG_SCAN_MODE_EN_LEN    1u
#define DVA_MCU_CONFIG_REG_SCAN_MODE_EN_TYPE   DVA_FIELD_TYPE_RW
#define DVA_MCU_CONFIG_REG_MCU_CONFIG_REG_LSP  0u
#define DVA_MCU_CONFIG_REG_MCU_CONFIG_REG_LEN  7u
#define DVA_MCU_CONFIG_REG_MCU_CONFIG_REG_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_0_KEY_INDEX_LSP   24u
#define DVA_MACSEC_PARA_0_KEY_INDEX_LEN   8u
#define DVA_MACSEC_PARA_0_KEY_INDEX_TYPE  DVA_FIELD_TYPE_RW
#define DVA_MACSEC_PARA_0_IS_XPN_LSP      3u
#define DVA_MACSEC_PARA_0_IS_XPN_LEN      1u
#define DVA_MACSEC_PARA_0_IS_XPN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_MACSEC_PARA_0_KEY_AN_LSP      1u
#define DVA_MACSEC_PARA_0_KEY_AN_LEN      2u
#define DVA_MACSEC_PARA_0_KEY_AN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_MACSEC_PARA_0_KEY_LENGTH_LSP  0u
#define DVA_MACSEC_PARA_0_KEY_LENGTH_LEN  1u
#define DVA_MACSEC_PARA_0_KEY_LENGTH_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_1_DATA_LEN_LSP  0u
#define DVA_MACSEC_PARA_1_DATA_LEN_LEN  12u
#define DVA_MACSEC_PARA_1_DATA_LEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_2_BUFFER_START_ADDR_L_LSP  0u
#define DVA_MACSEC_PARA_2_BUFFER_START_ADDR_L_LEN  16u
#define DVA_MACSEC_PARA_2_BUFFER_START_ADDR_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_3_BUFFER_START_ADDR_H_LSP  0u
#define DVA_MACSEC_PARA_3_BUFFER_START_ADDR_H_LEN  16u
#define DVA_MACSEC_PARA_3_BUFFER_START_ADDR_H_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_4_MACSEC_SAK_ADDR_L_LSP  0u
#define DVA_MACSEC_PARA_4_MACSEC_SAK_ADDR_L_LEN  12u
#define DVA_MACSEC_PARA_4_MACSEC_SAK_ADDR_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_5_MACSEC_SAK_ADDR_H_LSP  0u
#define DVA_MACSEC_PARA_5_MACSEC_SAK_ADDR_H_LEN  12u
#define DVA_MACSEC_PARA_5_MACSEC_SAK_ADDR_H_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_6_KAY_CONTROL_REGISTER_0_LSP  0u
#define DVA_MACSEC_PARA_6_KAY_CONTROL_REGISTER_0_LEN  32u
#define DVA_MACSEC_PARA_6_KAY_CONTROL_REGISTER_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_7_KAY_CONTROL_REGISTER_1_LSP  0u
#define DVA_MACSEC_PARA_7_KAY_CONTROL_REGISTER_1_LEN  32u
#define DVA_MACSEC_PARA_7_KAY_CONTROL_REGISTER_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_8_KAY_CONTROL_REGISTER_2_LSP  0u
#define DVA_MACSEC_PARA_8_KAY_CONTROL_REGISTER_2_LEN  32u
#define DVA_MACSEC_PARA_8_KAY_CONTROL_REGISTER_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_9_KAY_CONTROL_REGISTER_3_LSP  0u
#define DVA_MACSEC_PARA_9_KAY_CONTROL_REGISTER_3_LEN  32u
#define DVA_MACSEC_PARA_9_KAY_CONTROL_REGISTER_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_10_KAY_CONTROL_REGISTER_4_LSP  0u
#define DVA_MACSEC_PARA_10_KAY_CONTROL_REGISTER_4_LEN  32u
#define DVA_MACSEC_PARA_10_KAY_CONTROL_REGISTER_4_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_11_KAY_CONTROL_REGISTER_5_LSP  0u
#define DVA_MACSEC_PARA_11_KAY_CONTROL_REGISTER_5_LEN  32u
#define DVA_MACSEC_PARA_11_KAY_CONTROL_REGISTER_5_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_12_KAY_CONTROL_REGISTER_6_LSP  0u
#define DVA_MACSEC_PARA_12_KAY_CONTROL_REGISTER_6_LEN  32u
#define DVA_MACSEC_PARA_12_KAY_CONTROL_REGISTER_6_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_13_KAY_CONTROL_REGISTER_7_LSP  0u
#define DVA_MACSEC_PARA_13_KAY_CONTROL_REGISTER_7_LEN  32u
#define DVA_MACSEC_PARA_13_KAY_CONTROL_REGISTER_7_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_14_KAY_CONTROL_REGISTER_8_LSP  0u
#define DVA_MACSEC_PARA_14_KAY_CONTROL_REGISTER_8_LEN  32u
#define DVA_MACSEC_PARA_14_KAY_CONTROL_REGISTER_8_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_15_KAY_CONTROL_REGISTER_9_LSP  0u
#define DVA_MACSEC_PARA_15_KAY_CONTROL_REGISTER_9_LEN  32u
#define DVA_MACSEC_PARA_15_KAY_CONTROL_REGISTER_9_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_16_KAY_CONTROL_REGISTER_10_LSP  0u
#define DVA_MACSEC_PARA_16_KAY_CONTROL_REGISTER_10_LEN  32u
#define DVA_MACSEC_PARA_16_KAY_CONTROL_REGISTER_10_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_17_KAY_CONTROL_REGISTER_11_LSP  0u
#define DVA_MACSEC_PARA_17_KAY_CONTROL_REGISTER_11_LEN  32u
#define DVA_MACSEC_PARA_17_KAY_CONTROL_REGISTER_11_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_18_KAY_CONTROL_REGISTER_12_LSP  0u
#define DVA_MACSEC_PARA_18_KAY_CONTROL_REGISTER_12_LEN  32u
#define DVA_MACSEC_PARA_18_KAY_CONTROL_REGISTER_12_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_19_KAY_CONTROL_REGISTER_13_LSP  0u
#define DVA_MACSEC_PARA_19_KAY_CONTROL_REGISTER_13_LEN  32u
#define DVA_MACSEC_PARA_19_KAY_CONTROL_REGISTER_13_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_20_KAY_CONTROL_REGISTER_14_LSP  0u
#define DVA_MACSEC_PARA_20_KAY_CONTROL_REGISTER_14_LEN  32u
#define DVA_MACSEC_PARA_20_KAY_CONTROL_REGISTER_14_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_21_KAY_CONTROL_REGISTER_15_LSP  0u
#define DVA_MACSEC_PARA_21_KAY_CONTROL_REGISTER_15_LEN  32u
#define DVA_MACSEC_PARA_21_KAY_CONTROL_REGISTER_15_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_22_KAY_CONTROL_REGISTER_16_LSP  0u
#define DVA_MACSEC_PARA_22_KAY_CONTROL_REGISTER_16_LEN  32u
#define DVA_MACSEC_PARA_22_KAY_CONTROL_REGISTER_16_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_23_KAY_CONTROL_REGISTER_17_LSP  0u
#define DVA_MACSEC_PARA_23_KAY_CONTROL_REGISTER_17_LEN  32u
#define DVA_MACSEC_PARA_23_KAY_CONTROL_REGISTER_17_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_24_KAY_CONTROL_REGISTER_18_LSP  0u
#define DVA_MACSEC_PARA_24_KAY_CONTROL_REGISTER_18_LEN  32u
#define DVA_MACSEC_PARA_24_KAY_CONTROL_REGISTER_18_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_25_KAY_CONTROL_REGISTER_19_LSP  0u
#define DVA_MACSEC_PARA_25_KAY_CONTROL_REGISTER_19_LEN  32u
#define DVA_MACSEC_PARA_25_KAY_CONTROL_REGISTER_19_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_26_KAY_CONTROL_REGISTER_20_LSP  0u
#define DVA_MACSEC_PARA_26_KAY_CONTROL_REGISTER_20_LEN  32u
#define DVA_MACSEC_PARA_26_KAY_CONTROL_REGISTER_20_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_27_KAY_CONTROL_REGISTER_21_LSP  0u
#define DVA_MACSEC_PARA_27_KAY_CONTROL_REGISTER_21_LEN  32u
#define DVA_MACSEC_PARA_27_KAY_CONTROL_REGISTER_21_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_28_KAY_CONTROL_REGISTER_22_LSP  0u
#define DVA_MACSEC_PARA_28_KAY_CONTROL_REGISTER_22_LEN  32u
#define DVA_MACSEC_PARA_28_KAY_CONTROL_REGISTER_22_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_29_KAY_CONTROL_REGISTER_23_LSP  0u
#define DVA_MACSEC_PARA_29_KAY_CONTROL_REGISTER_23_LEN  32u
#define DVA_MACSEC_PARA_29_KAY_CONTROL_REGISTER_23_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_30_KAY_CONTROL_REGISTER_24_LSP  0u
#define DVA_MACSEC_PARA_30_KAY_CONTROL_REGISTER_24_LEN  32u
#define DVA_MACSEC_PARA_30_KAY_CONTROL_REGISTER_24_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_31_KAY_CONTROL_REGISTER_25_LSP  0u
#define DVA_MACSEC_PARA_31_KAY_CONTROL_REGISTER_25_LEN  32u
#define DVA_MACSEC_PARA_31_KAY_CONTROL_REGISTER_25_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_32_KAY_CONTROL_REGISTER_26_LSP  0u
#define DVA_MACSEC_PARA_32_KAY_CONTROL_REGISTER_26_LEN  32u
#define DVA_MACSEC_PARA_32_KAY_CONTROL_REGISTER_26_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_33_KAY_CONTROL_REGISTER_27_LSP  0u
#define DVA_MACSEC_PARA_33_KAY_CONTROL_REGISTER_27_LEN  32u
#define DVA_MACSEC_PARA_33_KAY_CONTROL_REGISTER_27_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_34_KAY_CONTROL_REGISTER_28_LSP  0u
#define DVA_MACSEC_PARA_34_KAY_CONTROL_REGISTER_28_LEN  32u
#define DVA_MACSEC_PARA_34_KAY_CONTROL_REGISTER_28_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_35_KAY_CONTROL_REGISTER_29_LSP  0u
#define DVA_MACSEC_PARA_35_KAY_CONTROL_REGISTER_29_LEN  32u
#define DVA_MACSEC_PARA_35_KAY_CONTROL_REGISTER_29_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_36_KAY_CONTROL_REGISTER_30_LSP  0u
#define DVA_MACSEC_PARA_36_KAY_CONTROL_REGISTER_30_LEN  32u
#define DVA_MACSEC_PARA_36_KAY_CONTROL_REGISTER_30_TYPE DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_37_KAY_CONTROL_REGISTER_31_LSP  0u
#define DVA_MACSEC_PARA_37_KAY_CONTROL_REGISTER_31_LEN  32u
#define DVA_MACSEC_PARA_37_KAY_CONTROL_REGISTER_31_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_0_SECURE_AUTH_REGIF_JTAG_SEL_LSP  4u
#define DVA_SECURE_INTF_PARA_0_SECURE_AUTH_REGIF_JTAG_SEL_LEN  1u
#define DVA_SECURE_INTF_PARA_0_SECURE_AUTH_REGIF_JTAG_SEL_TYPE DVA_FIELD_TYPE_RO
#define DVA_SECURE_INTF_PARA_0_OTP_JTAG_IF_AUTH_MODE_LSP       2u
#define DVA_SECURE_INTF_PARA_0_OTP_JTAG_IF_AUTH_MODE_LEN       2u
#define DVA_SECURE_INTF_PARA_0_OTP_JTAG_IF_AUTH_MODE_TYPE      DVA_FIELD_TYPE_RO
#define DVA_SECURE_INTF_PARA_0_OTP_REG_IF_AUTH_MODE_LSP        0u
#define DVA_SECURE_INTF_PARA_0_OTP_REG_IF_AUTH_MODE_LEN        2u
#define DVA_SECURE_INTF_PARA_0_OTP_REG_IF_AUTH_MODE_TYPE       DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_1_SECURE_AUTH_MODE_DATA_IN_0_LSP  0u
#define DVA_SECURE_INTF_PARA_1_SECURE_AUTH_MODE_DATA_IN_0_LEN  32u
#define DVA_SECURE_INTF_PARA_1_SECURE_AUTH_MODE_DATA_IN_0_TYPE DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_2_SECURE_AUTH_MODE_DATA_IN_1_LSP  0u
#define DVA_SECURE_INTF_PARA_2_SECURE_AUTH_MODE_DATA_IN_1_LEN  32u
#define DVA_SECURE_INTF_PARA_2_SECURE_AUTH_MODE_DATA_IN_1_TYPE DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_3_SECURE_AUTH_MODE_DATA_IN_2_LSP  0u
#define DVA_SECURE_INTF_PARA_3_SECURE_AUTH_MODE_DATA_IN_2_LEN  32u
#define DVA_SECURE_INTF_PARA_3_SECURE_AUTH_MODE_DATA_IN_2_TYPE DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_4_SECURE_AUTH_MODE_DATA_IN_3_LSP  0u
#define DVA_SECURE_INTF_PARA_4_SECURE_AUTH_MODE_DATA_IN_3_LEN  32u
#define DVA_SECURE_INTF_PARA_4_SECURE_AUTH_MODE_DATA_IN_3_TYPE DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_5_SECURE_RMA_MODE_DATA_IN_0_LSP  0u
#define DVA_SECURE_INTF_PARA_5_SECURE_RMA_MODE_DATA_IN_0_LEN  32u
#define DVA_SECURE_INTF_PARA_5_SECURE_RMA_MODE_DATA_IN_0_TYPE DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_6_SECURE_RMA_MODE_DATA_IN_1_LSP  0u
#define DVA_SECURE_INTF_PARA_6_SECURE_RMA_MODE_DATA_IN_1_LEN  32u
#define DVA_SECURE_INTF_PARA_6_SECURE_RMA_MODE_DATA_IN_1_TYPE DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_7_SECURE_RMA_MODE_DATA_IN_2_LSP  0u
#define DVA_SECURE_INTF_PARA_7_SECURE_RMA_MODE_DATA_IN_2_LEN  32u
#define DVA_SECURE_INTF_PARA_7_SECURE_RMA_MODE_DATA_IN_2_TYPE DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_8_SECURE_RMA_MODE_DATA_IN_3_LSP  0u
#define DVA_SECURE_INTF_PARA_8_SECURE_RMA_MODE_DATA_IN_3_LEN  32u
#define DVA_SECURE_INTF_PARA_8_SECURE_RMA_MODE_DATA_IN_3_TYPE DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_9_SECURE_AUTH_MODE_DATA_OUT_0_LSP  0u
#define DVA_SECURE_INTF_PARA_9_SECURE_AUTH_MODE_DATA_OUT_0_LEN  32u
#define DVA_SECURE_INTF_PARA_9_SECURE_AUTH_MODE_DATA_OUT_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_10_SECURE_AUTH_MODE_DATA_OUT_1_LSP  0u
#define DVA_SECURE_INTF_PARA_10_SECURE_AUTH_MODE_DATA_OUT_1_LEN  32u
#define DVA_SECURE_INTF_PARA_10_SECURE_AUTH_MODE_DATA_OUT_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_11_SECURE_AUTH_MODE_DATA_OUT_2_LSP  0u
#define DVA_SECURE_INTF_PARA_11_SECURE_AUTH_MODE_DATA_OUT_2_LEN  32u
#define DVA_SECURE_INTF_PARA_11_SECURE_AUTH_MODE_DATA_OUT_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_12_SECURE_AUTH_MODE_DATA_OUT_3_LSP  0u
#define DVA_SECURE_INTF_PARA_12_SECURE_AUTH_MODE_DATA_OUT_3_LEN  32u
#define DVA_SECURE_INTF_PARA_12_SECURE_AUTH_MODE_DATA_OUT_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_13_SECURE_AUTH_COUNTER_LSP      16u
#define DVA_SECURE_INTF_PARA_13_SECURE_AUTH_COUNTER_LEN      16u
#define DVA_SECURE_INTF_PARA_13_SECURE_AUTH_COUNTER_TYPE     DVA_FIELD_TYPE_RO
#define DVA_SECURE_INTF_PARA_13_SECURE_AUTH_MODE_STATUS_LSP  1u
#define DVA_SECURE_INTF_PARA_13_SECURE_AUTH_MODE_STATUS_LEN  1u
#define DVA_SECURE_INTF_PARA_13_SECURE_AUTH_MODE_STATUS_TYPE DVA_FIELD_TYPE_RW
#define DVA_SECURE_INTF_PARA_13_SECURE_AUTH_MODE_DONE_LSP    0u
#define DVA_SECURE_INTF_PARA_13_SECURE_AUTH_MODE_DONE_LEN    1u
#define DVA_SECURE_INTF_PARA_13_SECURE_AUTH_MODE_DONE_TYPE   DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_14_SECURE_RMA_COUNTER_LSP      16u
#define DVA_SECURE_INTF_PARA_14_SECURE_RMA_COUNTER_LEN      16u
#define DVA_SECURE_INTF_PARA_14_SECURE_RMA_COUNTER_TYPE     DVA_FIELD_TYPE_RO
#define DVA_SECURE_INTF_PARA_14_SECURE_RMA_MODE_STATUS_LSP  1u
#define DVA_SECURE_INTF_PARA_14_SECURE_RMA_MODE_STATUS_LEN  1u
#define DVA_SECURE_INTF_PARA_14_SECURE_RMA_MODE_STATUS_TYPE DVA_FIELD_TYPE_RW
#define DVA_SECURE_INTF_PARA_14_SECURE_RMA_MODE_DONE_LSP    0u
#define DVA_SECURE_INTF_PARA_14_SECURE_RMA_MODE_DONE_LEN    1u
#define DVA_SECURE_INTF_PARA_14_SECURE_RMA_MODE_DONE_TYPE   DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_38_SECY_TXRX_MODE_LSP  4u
#define DVA_MACSEC_PARA_38_SECY_TXRX_MODE_LEN  1u
#define DVA_MACSEC_PARA_38_SECY_TXRX_MODE_TYPE DVA_FIELD_TYPE_RW
#define DVA_MACSEC_PARA_38_SECY_INDEX_LSP      0u
#define DVA_MACSEC_PARA_38_SECY_INDEX_LEN      4u
#define DVA_MACSEC_PARA_38_SECY_INDEX_TYPE     DVA_FIELD_TYPE_RW

#define DVA_MACSEC_PARA_39_UNWRAP_KEY_INDEX_LSP  1u
#define DVA_MACSEC_PARA_39_UNWRAP_KEY_INDEX_LEN  4u
#define DVA_MACSEC_PARA_39_UNWRAP_KEY_INDEX_TYPE DVA_FIELD_TYPE_RW
#define DVA_MACSEC_PARA_39_FLASH_CAK_EN_LSP      0u
#define DVA_MACSEC_PARA_39_FLASH_CAK_EN_LEN      1u
#define DVA_MACSEC_PARA_39_FLASH_CAK_EN_TYPE     DVA_FIELD_TYPE_RW

#define DVA_MCU_DBG_REG_01_MCU_DBG_REG_01_LSP  0u
#define DVA_MCU_DBG_REG_01_MCU_DBG_REG_01_LEN  32u
#define DVA_MCU_DBG_REG_01_MCU_DBG_REG_01_TYPE DVA_FIELD_TYPE_RO

#define DVA_MCU_DBG_REG_02_MCU_DBG_REG_02_LSP  0u
#define DVA_MCU_DBG_REG_02_MCU_DBG_REG_02_LEN  32u
#define DVA_MCU_DBG_REG_02_MCU_DBG_REG_02_TYPE DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_15_PCIE0_AUTH_MODE_DATA_IN_0_LSP  0u
#define DVA_SECURE_INTF_PARA_15_PCIE0_AUTH_MODE_DATA_IN_0_LEN  32u
#define DVA_SECURE_INTF_PARA_15_PCIE0_AUTH_MODE_DATA_IN_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_16_PCIE0_AUTH_MODE_DATA_IN_1_LSP  0u
#define DVA_SECURE_INTF_PARA_16_PCIE0_AUTH_MODE_DATA_IN_1_LEN  32u
#define DVA_SECURE_INTF_PARA_16_PCIE0_AUTH_MODE_DATA_IN_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_17_PCIE0_AUTH_MODE_DATA_IN_2_LSP  0u
#define DVA_SECURE_INTF_PARA_17_PCIE0_AUTH_MODE_DATA_IN_2_LEN  32u
#define DVA_SECURE_INTF_PARA_17_PCIE0_AUTH_MODE_DATA_IN_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_18_PCIE0_AUTH_MODE_DATA_IN_3_LSP  0u
#define DVA_SECURE_INTF_PARA_18_PCIE0_AUTH_MODE_DATA_IN_3_LEN  32u
#define DVA_SECURE_INTF_PARA_18_PCIE0_AUTH_MODE_DATA_IN_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_19_PCIE0_RMA_MODE_DATA_IN_0_LSP  0u
#define DVA_SECURE_INTF_PARA_19_PCIE0_RMA_MODE_DATA_IN_0_LEN  32u
#define DVA_SECURE_INTF_PARA_19_PCIE0_RMA_MODE_DATA_IN_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_20_PCIE0_RMA_MODE_DATA_IN_1_LSP  0u
#define DVA_SECURE_INTF_PARA_20_PCIE0_RMA_MODE_DATA_IN_1_LEN  32u
#define DVA_SECURE_INTF_PARA_20_PCIE0_RMA_MODE_DATA_IN_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_21_PCIE0_RMA_MODE_DATA_IN_2_LSP  0u
#define DVA_SECURE_INTF_PARA_21_PCIE0_RMA_MODE_DATA_IN_2_LEN  32u
#define DVA_SECURE_INTF_PARA_21_PCIE0_RMA_MODE_DATA_IN_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_22_PCIE0_RMA_MODE_DATA_IN_3_LSP  0u
#define DVA_SECURE_INTF_PARA_22_PCIE0_RMA_MODE_DATA_IN_3_LEN  32u
#define DVA_SECURE_INTF_PARA_22_PCIE0_RMA_MODE_DATA_IN_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_23_PCIE0_AUTH_MODE_DATA_OUT_0_LSP  0u
#define DVA_SECURE_INTF_PARA_23_PCIE0_AUTH_MODE_DATA_OUT_0_LEN  32u
#define DVA_SECURE_INTF_PARA_23_PCIE0_AUTH_MODE_DATA_OUT_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_24_PCIE0_AUTH_MODE_DATA_OUT_1_LSP  0u
#define DVA_SECURE_INTF_PARA_24_PCIE0_AUTH_MODE_DATA_OUT_1_LEN  32u
#define DVA_SECURE_INTF_PARA_24_PCIE0_AUTH_MODE_DATA_OUT_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_25_PCIE0_AUTH_MODE_DATA_OUT_2_LSP  0u
#define DVA_SECURE_INTF_PARA_25_PCIE0_AUTH_MODE_DATA_OUT_2_LEN  32u
#define DVA_SECURE_INTF_PARA_25_PCIE0_AUTH_MODE_DATA_OUT_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_26_PCIE0_AUTH_MODE_DATA_OUT_3_LSP  0u
#define DVA_SECURE_INTF_PARA_26_PCIE0_AUTH_MODE_DATA_OUT_3_LEN  32u
#define DVA_SECURE_INTF_PARA_26_PCIE0_AUTH_MODE_DATA_OUT_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_COUNTER_LSP              16u
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_COUNTER_LEN              16u
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_COUNTER_TYPE             DVA_FIELD_TYPE_RO
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_MODE_STATUS_LSP          2u
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_MODE_STATUS_LEN          1u
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_MODE_STATUS_TYPE         DVA_FIELD_TYPE_RW
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_MODE_PASSWORD_DONE_LSP   1u
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_MODE_PASSWORD_DONE_LEN   1u
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_MODE_PASSWORD_DONE_TYPE  DVA_FIELD_TYPE_RW
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_MODE_HANDSHAKE_DONE_LSP  0u
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_MODE_HANDSHAKE_DONE_LEN  1u
#define DVA_SECURE_INTF_PARA_27_PCIE0_AUTH_MODE_HANDSHAKE_DONE_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_28_PCIE0_RMA_COUNTER_LSP      16u
#define DVA_SECURE_INTF_PARA_28_PCIE0_RMA_COUNTER_LEN      16u
#define DVA_SECURE_INTF_PARA_28_PCIE0_RMA_COUNTER_TYPE     DVA_FIELD_TYPE_RO
#define DVA_SECURE_INTF_PARA_28_PCIE0_RMA_MODE_STATUS_LSP  1u
#define DVA_SECURE_INTF_PARA_28_PCIE0_RMA_MODE_STATUS_LEN  1u
#define DVA_SECURE_INTF_PARA_28_PCIE0_RMA_MODE_STATUS_TYPE DVA_FIELD_TYPE_RW
#define DVA_SECURE_INTF_PARA_28_PCIE0_RMA_MODE_DONE_LSP    0u
#define DVA_SECURE_INTF_PARA_28_PCIE0_RMA_MODE_DONE_LEN    1u
#define DVA_SECURE_INTF_PARA_28_PCIE0_RMA_MODE_DONE_TYPE   DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_29_PCIE1_AUTH_MODE_DATA_IN_0_LSP  0u
#define DVA_SECURE_INTF_PARA_29_PCIE1_AUTH_MODE_DATA_IN_0_LEN  32u
#define DVA_SECURE_INTF_PARA_29_PCIE1_AUTH_MODE_DATA_IN_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_30_PCIE1_AUTH_MODE_DATA_IN_1_LSP  0u
#define DVA_SECURE_INTF_PARA_30_PCIE1_AUTH_MODE_DATA_IN_1_LEN  32u
#define DVA_SECURE_INTF_PARA_30_PCIE1_AUTH_MODE_DATA_IN_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_31_PCIE1_AUTH_MODE_DATA_IN_2_LSP  0u
#define DVA_SECURE_INTF_PARA_31_PCIE1_AUTH_MODE_DATA_IN_2_LEN  32u
#define DVA_SECURE_INTF_PARA_31_PCIE1_AUTH_MODE_DATA_IN_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_32_PCIE1_AUTH_MODE_DATA_IN_3_LSP  0u
#define DVA_SECURE_INTF_PARA_32_PCIE1_AUTH_MODE_DATA_IN_3_LEN  32u
#define DVA_SECURE_INTF_PARA_32_PCIE1_AUTH_MODE_DATA_IN_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_33_PCIE1_RMA_MODE_DATA_IN_0_LSP  0u
#define DVA_SECURE_INTF_PARA_33_PCIE1_RMA_MODE_DATA_IN_0_LEN  32u
#define DVA_SECURE_INTF_PARA_33_PCIE1_RMA_MODE_DATA_IN_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_34_PCIE1_RMA_MODE_DATA_IN_1_LSP  0u
#define DVA_SECURE_INTF_PARA_34_PCIE1_RMA_MODE_DATA_IN_1_LEN  32u
#define DVA_SECURE_INTF_PARA_34_PCIE1_RMA_MODE_DATA_IN_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_35_PCIE1_RMA_MODE_DATA_IN_2_LSP  0u
#define DVA_SECURE_INTF_PARA_35_PCIE1_RMA_MODE_DATA_IN_2_LEN  32u
#define DVA_SECURE_INTF_PARA_35_PCIE1_RMA_MODE_DATA_IN_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_36_PCIE1_RMA_MODE_DATA_IN_3_LSP  0u
#define DVA_SECURE_INTF_PARA_36_PCIE1_RMA_MODE_DATA_IN_3_LEN  32u
#define DVA_SECURE_INTF_PARA_36_PCIE1_RMA_MODE_DATA_IN_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_37_PCIE1_AUTH_MODE_DATA_OUT_0_LSP  0u
#define DVA_SECURE_INTF_PARA_37_PCIE1_AUTH_MODE_DATA_OUT_0_LEN  32u
#define DVA_SECURE_INTF_PARA_37_PCIE1_AUTH_MODE_DATA_OUT_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_38_PCIE1_AUTH_MODE_DATA_OUT_1_LSP  0u
#define DVA_SECURE_INTF_PARA_38_PCIE1_AUTH_MODE_DATA_OUT_1_LEN  32u
#define DVA_SECURE_INTF_PARA_38_PCIE1_AUTH_MODE_DATA_OUT_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_39_PCIE1_AUTH_MODE_DATA_OUT_2_LSP  0u
#define DVA_SECURE_INTF_PARA_39_PCIE1_AUTH_MODE_DATA_OUT_2_LEN  32u
#define DVA_SECURE_INTF_PARA_39_PCIE1_AUTH_MODE_DATA_OUT_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_40_PCIE1_AUTH_MODE_DATA_OUT_3_LSP  0u
#define DVA_SECURE_INTF_PARA_40_PCIE1_AUTH_MODE_DATA_OUT_3_LEN  32u
#define DVA_SECURE_INTF_PARA_40_PCIE1_AUTH_MODE_DATA_OUT_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_COUNTER_LSP              16u
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_COUNTER_LEN              16u
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_COUNTER_TYPE             DVA_FIELD_TYPE_RO
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_MODE_STATUS_LSP          2u
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_MODE_STATUS_LEN          1u
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_MODE_STATUS_TYPE         DVA_FIELD_TYPE_RW
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_MODE_PASSWORD_DONE_LSP   1u
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_MODE_PASSWORD_DONE_LEN   1u
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_MODE_PASSWORD_DONE_TYPE  DVA_FIELD_TYPE_RW
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_MODE_HANDSHAKE_DONE_LSP  0u
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_MODE_HANDSHAKE_DONE_LEN  1u
#define DVA_SECURE_INTF_PARA_41_PCIE1_AUTH_MODE_HANDSHAKE_DONE_TYPE DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_42_PCIE1_RMA_COUNTER_LSP      16u
#define DVA_SECURE_INTF_PARA_42_PCIE1_RMA_COUNTER_LEN      16u
#define DVA_SECURE_INTF_PARA_42_PCIE1_RMA_COUNTER_TYPE     DVA_FIELD_TYPE_RO
#define DVA_SECURE_INTF_PARA_42_PCIE1_RMA_MODE_STATUS_LSP  1u
#define DVA_SECURE_INTF_PARA_42_PCIE1_RMA_MODE_STATUS_LEN  1u
#define DVA_SECURE_INTF_PARA_42_PCIE1_RMA_MODE_STATUS_TYPE DVA_FIELD_TYPE_RW
#define DVA_SECURE_INTF_PARA_42_PCIE1_RMA_MODE_DONE_LSP    0u
#define DVA_SECURE_INTF_PARA_42_PCIE1_RMA_MODE_DONE_LEN    1u
#define DVA_SECURE_INTF_PARA_42_PCIE1_RMA_MODE_DONE_TYPE   DVA_FIELD_TYPE_RW

#define DVA_SECURE_INTF_PARA_43_OTP_PCIE0_AUTH_MODE_LSP  0u
#define DVA_SECURE_INTF_PARA_43_OTP_PCIE0_AUTH_MODE_LEN  2u
#define DVA_SECURE_INTF_PARA_43_OTP_PCIE0_AUTH_MODE_TYPE DVA_FIELD_TYPE_RO

#define DVA_SECURE_INTF_PARA_44_OTP_PCIE1_AUTH_MODE_LSP  0u
#define DVA_SECURE_INTF_PARA_44_OTP_PCIE1_AUTH_MODE_LEN  2u
#define DVA_SECURE_INTF_PARA_44_OTP_PCIE1_AUTH_MODE_TYPE DVA_FIELD_TYPE_RO

#define DVA_MCU_DBG_REG_03_MCU_DBG_REG_03_LSP  0u
#define DVA_MCU_DBG_REG_03_MCU_DBG_REG_03_LEN  32u
#define DVA_MCU_DBG_REG_03_MCU_DBG_REG_03_TYPE DVA_FIELD_TYPE_RO

#define DVA_MCU_DBG_PG_SEL_MCU_DBG_PG_SEL_LSP  0u
#define DVA_MCU_DBG_PG_SEL_MCU_DBG_PG_SEL_LEN  3u
#define DVA_MCU_DBG_PG_SEL_MCU_DBG_PG_SEL_TYPE DVA_FIELD_TYPE_RW

#define DVA_MCU_PATCH_DATA_MCU_DBG_PATCH_WDATA_LSP  16u
#define DVA_MCU_PATCH_DATA_MCU_DBG_PATCH_WDATA_LEN  16u
#define DVA_MCU_PATCH_DATA_MCU_DBG_PATCH_WDATA_TYPE DVA_FIELD_TYPE_RW
#define DVA_MCU_PATCH_DATA_MCU_DBG_PATCH_RDATA_LSP  0u
#define DVA_MCU_PATCH_DATA_MCU_DBG_PATCH_RDATA_LEN  16u
#define DVA_MCU_PATCH_DATA_MCU_DBG_PATCH_RDATA_TYPE DVA_FIELD_TYPE_RO

#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_ACK_LSP       21u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_ACK_LEN       1u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_ACK_TYPE      DVA_FIELD_TYPE_RO
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_DATA_RDY_LSP  20u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_DATA_RDY_LEN  1u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_DATA_RDY_TYPE DVA_FIELD_TYPE_RO
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_ADDR_RDY_LSP  19u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_ADDR_RDY_LEN  1u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_ADDR_RDY_TYPE DVA_FIELD_TYPE_RO
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_WEN_LSP       18u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_WEN_LEN       1u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_WEN_TYPE      DVA_FIELD_TYPE_RW
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_TRANS_LSP     17u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_TRANS_LEN     1u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_TRANS_TYPE    DVA_FIELD_TYPE_RW
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_REQ_N_LSP     16u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_REQ_N_LEN     1u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_REQ_N_TYPE    DVA_FIELD_TYPE_RW
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_ADDR_LSP      0u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_ADDR_LEN      16u
#define DVA_MCU_PATCH_CTL_MCU_DBG_PATCH_ADDR_TYPE     DVA_FIELD_TYPE_RW

#define DVA_FUSA_PG_LOCK_DMY_KEY_FUSA_PG_LOCK_DMY_KEY_LSP  0u
#define DVA_FUSA_PG_LOCK_DMY_KEY_FUSA_PG_LOCK_DMY_KEY_LEN  1u
#define DVA_FUSA_PG_LOCK_DMY_KEY_FUSA_PG_LOCK_DMY_KEY_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_KEY_H_ */