/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_PORT_BASED_VLAN_H_
#define DVA_RTKAS_REG_FIELD_FILE_PORT_BASED_VLAN_H_

#ifdef DVA_FILE_PORT_BASED_VLAN
/* File: Port_based DVA_VLAN */
#define DVA_VLAN_PORTROLE_CONTROL_PORTROLE_LSP  0u
#define DVA_VLAN_PORTROLE_CONTROL_PORTROLE_LEN  16u
#define DVA_VLAN_PORTROLE_CONTROL_PORTROLE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT0_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT0_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT0_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT0_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT0_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT0_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT0_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT0_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT0_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT0_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT0_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT0_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT1_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT1_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT1_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT1_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT1_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT1_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT1_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT1_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT1_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT1_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT1_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT1_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT2_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT2_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT2_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT2_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT2_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT2_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT2_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT2_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT2_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT2_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT2_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT2_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT3_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT3_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT3_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT3_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT3_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT3_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT3_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT3_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT3_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT3_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT3_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT3_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT4_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT4_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT4_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT4_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT4_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT4_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT4_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT4_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT4_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT4_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT4_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT4_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT5_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT5_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT5_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT5_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT5_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT5_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT5_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT5_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT5_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT5_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT5_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT5_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT6_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT6_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT6_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT6_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT6_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT6_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT6_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT6_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT6_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT6_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT6_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT6_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT7_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT7_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT7_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT7_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT7_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT7_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT7_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT7_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT7_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT7_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT7_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT7_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT8_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT8_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT8_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT8_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT8_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT8_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT8_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT8_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT8_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT8_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT8_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT8_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT9_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT9_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT9_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT9_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT9_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT9_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT9_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT9_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT9_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT9_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT9_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT9_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT10_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT10_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT10_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT10_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT10_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT10_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT10_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT10_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT10_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT10_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT10_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT10_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT11_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT11_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT11_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT11_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT11_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT11_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT11_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT11_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT11_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT11_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT11_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT11_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT12_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT12_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT12_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT12_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT12_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT12_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT12_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT12_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT12_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT12_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT12_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT12_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT13_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT13_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT13_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT13_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT13_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT13_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT13_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT13_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT13_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT13_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT13_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT13_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT14_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT14_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT14_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT14_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT14_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT14_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT14_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT14_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT14_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT14_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT14_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT14_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_VLAN_CONTROL_PIVID_LSP  20u
#define DVA_PORT15_VLAN_CONTROL_PIVID_LEN  12u
#define DVA_PORT15_VLAN_CONTROL_PIVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_VLAN_CONTROL_PIDEI_LSP  19u
#define DVA_PORT15_VLAN_CONTROL_PIDEI_LEN  1u
#define DVA_PORT15_VLAN_CONTROL_PIDEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_VLAN_CONTROL_PIPRI_LSP  16u
#define DVA_PORT15_VLAN_CONTROL_PIPRI_LEN  3u
#define DVA_PORT15_VLAN_CONTROL_PIPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_VLAN_CONTROL_POVID_LSP  4u
#define DVA_PORT15_VLAN_CONTROL_POVID_LEN  12u
#define DVA_PORT15_VLAN_CONTROL_POVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_VLAN_CONTROL_PODEI_LSP  3u
#define DVA_PORT15_VLAN_CONTROL_PODEI_LEN  1u
#define DVA_PORT15_VLAN_CONTROL_PODEI_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_VLAN_CONTROL_POPRI_LSP  0u
#define DVA_PORT15_VLAN_CONTROL_POPRI_LEN  3u
#define DVA_PORT15_VLAN_CONTROL_POPRI_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LSP  0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_LEN  1u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_FUSA_PG_LOCK_DMY_PORT_BASED_VLAN_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_PORT_BASED_VLAN_H_ */