/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_RLDP_H_
#define DVA_RTKAS_REG_FIELD_FILE_RLDP_H_

#ifdef DVA_FILE_RLDP
/* File: RLDP */
#define DVA_RTKPP_RANDOM_NUMBER_CONTROL0_RTKPP_RANDOM_NUMBER31_0_LSP  0u
#define DVA_RTKPP_RANDOM_NUMBER_CONTROL0_RTKPP_RANDOM_NUMBER31_0_LEN  32u
#define DVA_RTKPP_RANDOM_NUMBER_CONTROL0_RTKPP_RANDOM_NUMBER31_0_TYPE DVA_FIELD_TYPE_RO

#define DVA_RTKPP_RANDOM_NUMBER_CONTROL1_RTKPP_SEED15_0_LSP            16u
#define DVA_RTKPP_RANDOM_NUMBER_CONTROL1_RTKPP_SEED15_0_LEN            16u
#define DVA_RTKPP_RANDOM_NUMBER_CONTROL1_RTKPP_SEED15_0_TYPE           DVA_FIELD_TYPE_RWS
#define DVA_RTKPP_RANDOM_NUMBER_CONTROL1_RTKPP_RANDOM_NUMBER47_32_LSP  0u
#define DVA_RTKPP_RANDOM_NUMBER_CONTROL1_RTKPP_RANDOM_NUMBER47_32_LEN  16u
#define DVA_RTKPP_RANDOM_NUMBER_CONTROL1_RTKPP_RANDOM_NUMBER47_32_TYPE DVA_FIELD_TYPE_RO

#define DVA_RTKPP_RANDOM_NUMBER_CONTROL2_RTKPP_SEED47_16_LSP  0u
#define DVA_RTKPP_RANDOM_NUMBER_CONTROL2_RTKPP_SEED47_16_LEN  32u
#define DVA_RTKPP_RANDOM_NUMBER_CONTROL2_RTKPP_SEED47_16_TYPE DVA_FIELD_TYPE_RWS

#define DVA_RLDP_LOOP_STATE_RETRY_CONTROL_RETRY_COUNT_LSP   16u
#define DVA_RLDP_LOOP_STATE_RETRY_CONTROL_RETRY_COUNT_LEN   8u
#define DVA_RLDP_LOOP_STATE_RETRY_CONTROL_RETRY_COUNT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_RLDP_LOOP_STATE_RETRY_CONTROL_RETRY_PERIOD_LSP  0u
#define DVA_RLDP_LOOP_STATE_RETRY_CONTROL_RETRY_PERIOD_LEN  16u
#define DVA_RLDP_LOOP_STATE_RETRY_CONTROL_RETRY_PERIOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_RLDP_CHECK_STATE_RETRY_CONTROL_RETRY_COUNT_LSP   16u
#define DVA_RLDP_CHECK_STATE_RETRY_CONTROL_RETRY_COUNT_LEN   8u
#define DVA_RLDP_CHECK_STATE_RETRY_CONTROL_RETRY_COUNT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_RLDP_CHECK_STATE_RETRY_CONTROL_RETRY_PERIOD_LSP  0u
#define DVA_RLDP_CHECK_STATE_RETRY_CONTROL_RETRY_PERIOD_LEN  16u
#define DVA_RLDP_CHECK_STATE_RETRY_CONTROL_RETRY_PERIOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_RLDP_ENABLE_PORT_MASK_CONTROL_ENABLE_PMSK_LSP  0u
#define DVA_RLDP_ENABLE_PORT_MASK_CONTROL_ENABLE_PMSK_LEN  15u
#define DVA_RLDP_ENABLE_PORT_MASK_CONTROL_ENABLE_PMSK_TYPE DVA_FIELD_TYPE_RW

#define DVA_RLDP_LOOP_PORT_MASK_CONTROL0_RLDP_CHECK_PMSK_LSP  16u
#define DVA_RLDP_LOOP_PORT_MASK_CONTROL0_RLDP_CHECK_PMSK_LEN  15u
#define DVA_RLDP_LOOP_PORT_MASK_CONTROL0_RLDP_CHECK_PMSK_TYPE DVA_FIELD_TYPE_RO
#define DVA_RLDP_LOOP_PORT_MASK_CONTROL0_RLDP_LOOP_PMSK_LSP   0u
#define DVA_RLDP_LOOP_PORT_MASK_CONTROL0_RLDP_LOOP_PMSK_LEN   15u
#define DVA_RLDP_LOOP_PORT_MASK_CONTROL0_RLDP_LOOP_PMSK_TYPE  DVA_FIELD_TYPE_RO

#define DVA_RLDP_LOOP_PORT_MASK_CONTROL1_SAMV_PMSK_LSP      16u
#define DVA_RLDP_LOOP_PORT_MASK_CONTROL1_SAMV_PMSK_LEN      15u
#define DVA_RLDP_LOOP_PORT_MASK_CONTROL1_SAMV_PMSK_TYPE     DVA_FIELD_TYPE_RO
#define DVA_RLDP_LOOP_PORT_MASK_CONTROL1_RLDP_LOOP_IPM_LSP  0u
#define DVA_RLDP_LOOP_PORT_MASK_CONTROL1_RLDP_LOOP_IPM_LEN  15u
#define DVA_RLDP_LOOP_PORT_MASK_CONTROL1_RLDP_LOOP_IPM_TYPE DVA_FIELD_TYPE_RWS

#define DVA_RLDP_GLOBAL_CONTROL_RLDP_AUTOTRIGGER_LSP          21u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_AUTOTRIGGER_LEN          1u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_AUTOTRIGGER_TYPE         DVA_FIELD_TYPE_RW
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_COMP_ID_LSP              20u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_COMP_ID_LEN              1u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_COMP_ID_TYPE             DVA_FIELD_TYPE_RW
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_INTERNAL_CPU_ENABLE_LSP  4u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_INTERNAL_CPU_ENABLE_LEN  16u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_INTERNAL_CPU_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_GEN_RANDOM_LSP           3u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_GEN_RANDOM_LEN           1u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_GEN_RANDOM_TYPE          DVA_FIELD_TYPE_RWS
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_CPUTRIG_LSP              2u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_CPUTRIG_LEN              1u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_CPUTRIG_TYPE             DVA_FIELD_TYPE_RWS
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_VLEAKY_LSP               1u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_VLEAKY_LEN               1u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_VLEAKY_TYPE              DVA_FIELD_TYPE_RW
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_AUTOBLK_LSP              0u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_AUTOBLK_LEN              1u
#define DVA_RLDP_GLOBAL_CONTROL_RLDP_AUTOBLK_TYPE             DVA_FIELD_TYPE_RW

#define DVA_TX_DISABLE_GLOBAL_CONTROL_DISABLETX_14_0_LSP  0u
#define DVA_TX_DISABLE_GLOBAL_CONTROL_DISABLETX_14_0_LEN  15u
#define DVA_TX_DISABLE_GLOBAL_CONTROL_DISABLETX_14_0_TYPE DVA_FIELD_TYPE_RWS

#define DVA_RX_DISABLE_GLOBAL_CONTROL_DISABLERX_14_0_LSP  0u
#define DVA_RX_DISABLE_GLOBAL_CONTROL_DISABLERX_14_0_LEN  15u
#define DVA_RX_DISABLE_GLOBAL_CONTROL_DISABLERX_14_0_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT0_LOOP_PORT_LOOPED_PORT0_LSP  0u
#define DVA_PORT0_LOOP_PORT_LOOPED_PORT0_LEN  4u
#define DVA_PORT0_LOOP_PORT_LOOPED_PORT0_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT1_LOOP_PORT_LOOPED_PORT1_LSP  0u
#define DVA_PORT1_LOOP_PORT_LOOPED_PORT1_LEN  4u
#define DVA_PORT1_LOOP_PORT_LOOPED_PORT1_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT2_LOOP_PORT_LOOPED_PORT2_LSP  0u
#define DVA_PORT2_LOOP_PORT_LOOPED_PORT2_LEN  4u
#define DVA_PORT2_LOOP_PORT_LOOPED_PORT2_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT3_LOOP_PORT_LOOPED_PORT3_LSP  0u
#define DVA_PORT3_LOOP_PORT_LOOPED_PORT3_LEN  4u
#define DVA_PORT3_LOOP_PORT_LOOPED_PORT3_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT4_LOOP_PORT_LOOPED_PORT4_LSP  0u
#define DVA_PORT4_LOOP_PORT_LOOPED_PORT4_LEN  4u
#define DVA_PORT4_LOOP_PORT_LOOPED_PORT4_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT5_LOOP_PORT_LOOPED_PORT5_LSP  0u
#define DVA_PORT5_LOOP_PORT_LOOPED_PORT5_LEN  4u
#define DVA_PORT5_LOOP_PORT_LOOPED_PORT5_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT6_LOOP_PORT_LOOPED_PORT6_LSP  0u
#define DVA_PORT6_LOOP_PORT_LOOPED_PORT6_LEN  4u
#define DVA_PORT6_LOOP_PORT_LOOPED_PORT6_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT7_LOOP_PORT_LOOPED_PORT7_LSP  0u
#define DVA_PORT7_LOOP_PORT_LOOPED_PORT7_LEN  4u
#define DVA_PORT7_LOOP_PORT_LOOPED_PORT7_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT8_LOOP_PORT_LOOPED_PORT8_LSP  0u
#define DVA_PORT8_LOOP_PORT_LOOPED_PORT8_LEN  4u
#define DVA_PORT8_LOOP_PORT_LOOPED_PORT8_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT9_LOOP_PORT_LOOPED_PORT9_LSP  0u
#define DVA_PORT9_LOOP_PORT_LOOPED_PORT9_LEN  4u
#define DVA_PORT9_LOOP_PORT_LOOPED_PORT9_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT10_LOOP_PORT_LOOPED_PORT10_LSP  0u
#define DVA_PORT10_LOOP_PORT_LOOPED_PORT10_LEN  4u
#define DVA_PORT10_LOOP_PORT_LOOPED_PORT10_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT11_LOOP_PORT_LOOPED_PORT11_LSP  0u
#define DVA_PORT11_LOOP_PORT_LOOPED_PORT11_LEN  4u
#define DVA_PORT11_LOOP_PORT_LOOPED_PORT11_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT12_LOOP_PORT_LOOPED_PORT12_LSP  0u
#define DVA_PORT12_LOOP_PORT_LOOPED_PORT12_LEN  4u
#define DVA_PORT12_LOOP_PORT_LOOPED_PORT12_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT13_LOOP_PORT_LOOPED_PORT13_LSP  0u
#define DVA_PORT13_LOOP_PORT_LOOPED_PORT13_LEN  4u
#define DVA_PORT13_LOOP_PORT_LOOPED_PORT13_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT14_LOOP_PORT_LOOPED_PORT14_LSP  0u
#define DVA_PORT14_LOOP_PORT_LOOPED_PORT14_LEN  4u
#define DVA_PORT14_LOOP_PORT_LOOPED_PORT14_TYPE DVA_FIELD_TYPE_RWS

#define DVA_SWITCH_OWN_MAC_CONTROL0_SWMAC47_16_LSP  0u
#define DVA_SWITCH_OWN_MAC_CONTROL0_SWMAC47_16_LEN  32u
#define DVA_SWITCH_OWN_MAC_CONTROL0_SWMAC47_16_TYPE DVA_FIELD_TYPE_RW

#define DVA_SWITCH_OWN_MAC_CONTROL1_DSTSWMACCHK_LSP  17u
#define DVA_SWITCH_OWN_MAC_CONTROL1_DSTSWMACCHK_LEN  2u
#define DVA_SWITCH_OWN_MAC_CONTROL1_DSTSWMACCHK_TYPE DVA_FIELD_TYPE_RW
#define DVA_SWITCH_OWN_MAC_CONTROL1_SWMACVALID_LSP   16u
#define DVA_SWITCH_OWN_MAC_CONTROL1_SWMACVALID_LEN   1u
#define DVA_SWITCH_OWN_MAC_CONTROL1_SWMACVALID_TYPE  DVA_FIELD_TYPE_RW
#define DVA_SWITCH_OWN_MAC_CONTROL1_SWMAC15_0_LSP    0u
#define DVA_SWITCH_OWN_MAC_CONTROL1_SWMAC15_0_LEN    16u
#define DVA_SWITCH_OWN_MAC_CONTROL1_SWMAC15_0_TYPE   DVA_FIELD_TYPE_RW

#define DVA_SWITCH_OWN_MAC_CONTROL2_SWMACCPUMASK_LSP  0u
#define DVA_SWITCH_OWN_MAC_CONTROL2_SWMACCPUMASK_LEN  16u
#define DVA_SWITCH_OWN_MAC_CONTROL2_SWMACCPUMASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_EXTRA_PORT_DEBUG_CONTROL_EXDBGMODE_LSP  1u
#define DVA_EXTRA_PORT_DEBUG_CONTROL_EXDBGMODE_LEN  1u
#define DVA_EXTRA_PORT_DEBUG_CONTROL_EXDBGMODE_TYPE DVA_FIELD_TYPE_RW
#define DVA_EXTRA_PORT_DEBUG_CONTROL_TRIGGER_LSP    0u
#define DVA_EXTRA_PORT_DEBUG_CONTROL_TRIGGER_LEN    1u
#define DVA_EXTRA_PORT_DEBUG_CONTROL_TRIGGER_TYPE   DVA_FIELD_TYPE_RWS

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_PKTLEN_LSP     5u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_PKTLEN_LEN     14u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_PKTLEN_TYPE    DVA_FIELD_TYPE_RW
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_GENEN_LSP      4u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_GENEN_LEN      1u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_GENEN_TYPE     DVA_FIELD_TYPE_RWS
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_INCREN_LSP     3u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_INCREN_LEN     1u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_INCREN_TYPE    DVA_FIELD_TYPE_RW
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_OTAGEXIST_LSP  2u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_OTAGEXIST_LEN  1u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_OTAGEXIST_TYPE DVA_FIELD_TYPE_RW
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_ITAGEXIST_LSP  1u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_ITAGEXIST_LEN  1u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_ITAGEXIST_TYPE DVA_FIELD_TYPE_RW
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_CTAGEXIST_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_CTAGEXIST_LEN  1u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL0_SPG_CTAGEXIST_TYPE DVA_FIELD_TYPE_RW

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL1_SPG_SMAC31_0_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL1_SPG_SMAC31_0_LEN  32u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL1_SPG_SMAC31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL2_SPG_SMAC47_32_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL2_SPG_SMAC47_32_LEN  16u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL2_SPG_SMAC47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL3_SPG_DMAC31_0_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL3_SPG_DMAC31_0_LEN  32u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL3_SPG_DMAC31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL4_SPG_DMAC47_32_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL4_SPG_DMAC47_32_LEN  16u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL4_SPG_DMAC47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL5_SPG_ITAG_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL5_SPG_ITAG_LEN  32u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL5_SPG_ITAG_TYPE DVA_FIELD_TYPE_RW

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL6_SPG_OTAG_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL6_SPG_OTAG_LEN  32u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL6_SPG_OTAG_TYPE DVA_FIELD_TYPE_RW

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL7_SPG_CTAG31_0_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL7_SPG_CTAG31_0_LEN  32u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL7_SPG_CTAG31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL8_SPG_CTAG63_32_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL8_SPG_CTAG63_32_LEN  32u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL8_SPG_CTAG63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL9_SPG_SRCPORT_LSP   18u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL9_SPG_SRCPORT_LEN   5u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL9_SPG_SRCPORT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL9_SPG_PKTNUM_LSP    8u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL9_SPG_PKTNUM_LEN    10u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL9_SPG_PKTNUM_TYPE   DVA_FIELD_TYPE_RW
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL9_SPG_FIRSTOCT_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL9_SPG_FIRSTOCT_LEN  8u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL9_SPG_FIRSTOCT_TYPE DVA_FIELD_TYPE_RW

#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL10_SPG_PAGE_THON_LSP   16u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL10_SPG_PAGE_THON_LEN   12u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL10_SPG_PAGE_THON_TYPE  DVA_FIELD_TYPE_RW
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL10_SPG_PAGE_THOFF_LSP  0u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL10_SPG_PAGE_THOFF_LEN  12u
#define DVA_SIMPLE_PACKET_GENERATOR_CONTROL10_SPG_PAGE_THOFF_TYPE DVA_FIELD_TYPE_RW

#define DVA_FUSA_PG_LOCK_DMY_RLDP_FUSA_PG_LOCK_DMY_RLDP_LSP  0u
#define DVA_FUSA_PG_LOCK_DMY_RLDP_FUSA_PG_LOCK_DMY_RLDP_LEN  1u
#define DVA_FUSA_PG_LOCK_DMY_RLDP_FUSA_PG_LOCK_DMY_RLDP_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_RLDP_H_ */