/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_LIST_FILE_SOURCE_MAC_LEARNING_H_
#define DVA_RTKAS_REG_LIST_FILE_SOURCE_MAC_LEARNING_H_

#ifdef DVA_FILE_SOURCE_MAC_LEARNING
/* File: Source MAC Learning */
#define DVA_SOURCE_MAC_LEARNING_CONTROL0                    0x4A730000u
#define DVA_SOURCE_MAC_LEARNING_CONTROL0_FIELDNUM           10u
#define DVA_SOURCE_MAC_LEARNING_CONTROL0_DEFAULTVAL         0x80056u
#define DVA_SOURCE_MAC_LEARNING_CONTROL1                    0x4A730004u
#define DVA_SOURCE_MAC_LEARNING_CONTROL1_FIELDNUM           2u
#define DVA_SOURCE_MAC_LEARNING_CONTROL1_DEFAULTVAL         0x8000u
#define DVA_ADDRESS_TABLE_FLUSH_CONTROL0                    0x4A730008u
#define DVA_ADDRESS_TABLE_FLUSH_CONTROL0_FIELDNUM           5u
#define DVA_ADDRESS_TABLE_FLUSH_CONTROL0_DEFAULTVAL         0x0u
#define DVA_ADDRESS_TABLE_FLUSH_CONTROL1                    0x4A73000Cu
#define DVA_ADDRESS_TABLE_FLUSH_CONTROL1_FIELDNUM           2u
#define DVA_ADDRESS_TABLE_FLUSH_CONTROL1_DEFAULTVAL         0x0u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL0                   0x4A730010u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL0_FIELDNUM          5u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL0_DEFAULTVAL        0x0u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL1                   0x4A730014u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL1_FIELDNUM          1u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL1_DEFAULTVAL        0x0u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL2                   0x4A730018u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL2_FIELDNUM          6u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL2_DEFAULTVAL        0x0u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL3                   0x4A73001Cu
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL3_FIELDNUM          2u
#define DVA_ADDRESS_TABLE_SEARCH_CONTROL3_DEFAULTVAL        0x0u
#define DVA_ADDRESS_TABLE_SEARCH_RESULT                     0x4A730020u
#define DVA_ADDRESS_TABLE_SEARCH_RESULT_FIELDNUM            3u
#define DVA_ADDRESS_TABLE_SEARCH_RESULT_DEFAULTVAL          0x0u
#define DVA_SA_LEARNING_INTERRUPT_STATUS                    0x4A730024u
#define DVA_SA_LEARNING_INTERRUPT_STATUS_FIELDNUM           3u
#define DVA_SA_LEARNING_INTERRUPT_STATUS_DEFAULTVAL         0x0u
#define DVA_CONFLICT_INT_STATUS0                            0x4A730028u
#define DVA_CONFLICT_INT_STATUS0_FIELDNUM                   3u
#define DVA_CONFLICT_INT_STATUS0_DEFAULTVAL                 0x0u
#define DVA_CONFLICT_INT_STATUS1                            0x4A73002Cu
#define DVA_CONFLICT_INT_STATUS1_FIELDNUM                   2u
#define DVA_CONFLICT_INT_STATUS1_DEFAULTVAL                 0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT0                   0x4A730030u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT0_FIELDNUM          1u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT0_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT1                   0x4A730034u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT1_FIELDNUM          4u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT1_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT2                   0x4A730038u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT2_FIELDNUM          1u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT2_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT3                   0x4A73003Cu
#define DVA_SOURCE_MAC_LEARNING_CONFLICT3_FIELDNUM          4u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT3_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT4                   0x4A730040u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT4_FIELDNUM          1u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT4_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT5                   0x4A730044u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT5_FIELDNUM          4u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT5_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT6                   0x4A730048u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT6_FIELDNUM          1u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT6_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT7                   0x4A73004Cu
#define DVA_SOURCE_MAC_LEARNING_CONFLICT7_FIELDNUM          4u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT7_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT8                   0x4A730050u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT8_FIELDNUM          1u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT8_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT9                   0x4A730054u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT9_FIELDNUM          4u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT9_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT10                  0x4A730058u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT10_FIELDNUM         1u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT10_DEFAULTVAL       0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT11                  0x4A73005Cu
#define DVA_SOURCE_MAC_LEARNING_CONFLICT11_FIELDNUM         4u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT11_DEFAULTVAL       0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT12                  0x4A730060u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT12_FIELDNUM         1u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT12_DEFAULTVAL       0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT13                  0x4A730064u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT13_FIELDNUM         4u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT13_DEFAULTVAL       0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT14                  0x4A730068u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT14_FIELDNUM         1u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT14_DEFAULTVAL       0x0u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT15                  0x4A73006Cu
#define DVA_SOURCE_MAC_LEARNING_CONFLICT15_FIELDNUM         4u
#define DVA_SOURCE_MAC_LEARNING_CONFLICT15_DEFAULTVAL       0x0u
#define DVA_OVERFLOW_INT_STATUS0                            0x4A730070u
#define DVA_OVERFLOW_INT_STATUS0_FIELDNUM                   3u
#define DVA_OVERFLOW_INT_STATUS0_DEFAULTVAL                 0x0u
#define DVA_OVERFLOW_INT_STATUS1                            0x4A730074u
#define DVA_OVERFLOW_INT_STATUS1_FIELDNUM                   2u
#define DVA_OVERFLOW_INT_STATUS1_DEFAULTVAL                 0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW0                   0x4A730078u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW0_FIELDNUM          1u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW0_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW1                   0x4A73007Cu
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW1_FIELDNUM          3u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW1_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW2                   0x4A730080u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW2_FIELDNUM          1u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW2_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW3                   0x4A730084u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW3_FIELDNUM          3u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW3_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW4                   0x4A730088u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW4_FIELDNUM          1u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW4_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW5                   0x4A73008Cu
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW5_FIELDNUM          3u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW5_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW6                   0x4A730090u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW6_FIELDNUM          1u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW6_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW7                   0x4A730094u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW7_FIELDNUM          3u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW7_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW8                   0x4A730098u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW8_FIELDNUM          1u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW8_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW9                   0x4A73009Cu
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW9_FIELDNUM          3u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW9_DEFAULTVAL        0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW10                  0x4A7300A0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW10_FIELDNUM         1u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW10_DEFAULTVAL       0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW11                  0x4A7300A4u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW11_FIELDNUM         3u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW11_DEFAULTVAL       0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW12                  0x4A7300A8u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW12_FIELDNUM         1u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW12_DEFAULTVAL       0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW13                  0x4A7300ACu
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW13_FIELDNUM         3u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW13_DEFAULTVAL       0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW14                  0x4A7300B0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW14_FIELDNUM         1u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW14_DEFAULTVAL       0x0u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW15                  0x4A7300B4u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW15_FIELDNUM         3u
#define DVA_SOURCE_MAC_LEARNING_OVERFLOW15_DEFAULTVAL       0x0u
#define DVA_FUSA_PG_LOCK_DMY_SOURCE_MAC_LEARNING            0x4A7300B8u
#define DVA_FUSA_PG_LOCK_DMY_SOURCE_MAC_LEARNING_FIELDNUM   2u
#define DVA_FUSA_PG_LOCK_DMY_SOURCE_MAC_LEARNING_DEFAULTVAL 0x0u
#endif
#endif /* DVA_RTKAS_REG_LIST_FILE_SOURCE_MAC_LEARNING_H_ */