/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_LIST_FILE_PORT_RELAY_DIS_H_
#define DVA_RTKAS_REG_LIST_FILE_PORT_RELAY_DIS_H_

#ifdef DVA_FILE_PORT_RELAY_DIS
/* File: port_relay_dis */
#define DVA_PORT0_CRCPR_CON                                   0x4AFA0000u
#define DVA_PORT0_CRCPR_CON_FIELDNUM                          2u
#define DVA_PORT0_CRCPR_CON_DEFAULTVAL                        0x0u
#define DVA_PORT1_CRCPR_CON                                   0x4AFA0800u
#define DVA_PORT1_CRCPR_CON_FIELDNUM                          2u
#define DVA_PORT1_CRCPR_CON_DEFAULTVAL                        0x0u
#define DVA_PORT2_CRCPR_CON                                   0x4AFA1000u
#define DVA_PORT2_CRCPR_CON_FIELDNUM                          2u
#define DVA_PORT2_CRCPR_CON_DEFAULTVAL                        0x0u
#define DVA_PORT3_CRCPR_CON                                   0x4AFA1800u
#define DVA_PORT3_CRCPR_CON_FIELDNUM                          2u
#define DVA_PORT3_CRCPR_CON_DEFAULTVAL                        0x0u
#define DVA_PORT4_CRCPR_CON                                   0x4AFA2000u
#define DVA_PORT4_CRCPR_CON_FIELDNUM                          2u
#define DVA_PORT4_CRCPR_CON_DEFAULTVAL                        0x0u
#define DVA_PORT5_CRCPR_CON                                   0x4AFA2800u
#define DVA_PORT5_CRCPR_CON_FIELDNUM                          2u
#define DVA_PORT5_CRCPR_CON_DEFAULTVAL                        0x0u
#define DVA_PORT6_CRCPR_CON                                   0x4AFA3000u
#define DVA_PORT6_CRCPR_CON_FIELDNUM                          2u
#define DVA_PORT6_CRCPR_CON_DEFAULTVAL                        0x0u
#define DVA_PORT7_CRCPR_CON                                   0x4AFA3800u
#define DVA_PORT7_CRCPR_CON_FIELDNUM                          2u
#define DVA_PORT7_CRCPR_CON_DEFAULTVAL                        0x0u
#define DVA_PORT8_CRCPR_CON                                   0x4AFA4000u
#define DVA_PORT8_CRCPR_CON_FIELDNUM                          2u
#define DVA_PORT8_CRCPR_CON_DEFAULTVAL                        0x0u
#define DVA_PORT9_CRCPR_CON                                   0x4AFA4800u
#define DVA_PORT9_CRCPR_CON_FIELDNUM                          2u
#define DVA_PORT9_CRCPR_CON_DEFAULTVAL                        0x0u
#define DVA_PORT10_CRCPR_CON                                  0x4AFA5000u
#define DVA_PORT10_CRCPR_CON_FIELDNUM                         2u
#define DVA_PORT10_CRCPR_CON_DEFAULTVAL                       0x0u
#define DVA_PORT11_CRCPR_CON                                  0x4AFA5800u
#define DVA_PORT11_CRCPR_CON_FIELDNUM                         2u
#define DVA_PORT11_CRCPR_CON_DEFAULTVAL                       0x0u
#define DVA_PORT12_CRCPR_CON                                  0x4AFA6000u
#define DVA_PORT12_CRCPR_CON_FIELDNUM                         2u
#define DVA_PORT12_CRCPR_CON_DEFAULTVAL                       0x0u
#define DVA_PORT13_CRCPR_CON                                  0x4AFA6800u
#define DVA_PORT13_CRCPR_CON_FIELDNUM                         2u
#define DVA_PORT13_CRCPR_CON_DEFAULTVAL                       0x0u
#define DVA_PORT14_CRCPR_CON                                  0x4AFA7000u
#define DVA_PORT14_CRCPR_CON_FIELDNUM                         2u
#define DVA_PORT14_CRCPR_CON_DEFAULTVAL                       0x0u
#define DVA_PORT15_CRCPR_CON                                  0x4AFA7800u
#define DVA_PORT15_CRCPR_CON_FIELDNUM                         2u
#define DVA_PORT15_CRCPR_CON_DEFAULTVAL                       0x0u
#define DVA_PORT0_CRCPR_METER_RELAY_STATUS                    0x4AFA0004u
#define DVA_PORT0_CRCPR_METER_RELAY_STATUS_FIELDNUM           3u
#define DVA_PORT0_CRCPR_METER_RELAY_STATUS_DEFAULTVAL         0x0u
#define DVA_PORT1_CRCPR_METER_RELAY_STATUS                    0x4AFA0804u
#define DVA_PORT1_CRCPR_METER_RELAY_STATUS_FIELDNUM           3u
#define DVA_PORT1_CRCPR_METER_RELAY_STATUS_DEFAULTVAL         0x0u
#define DVA_PORT2_CRCPR_METER_RELAY_STATUS                    0x4AFA1004u
#define DVA_PORT2_CRCPR_METER_RELAY_STATUS_FIELDNUM           3u
#define DVA_PORT2_CRCPR_METER_RELAY_STATUS_DEFAULTVAL         0x0u
#define DVA_PORT3_CRCPR_METER_RELAY_STATUS                    0x4AFA1804u
#define DVA_PORT3_CRCPR_METER_RELAY_STATUS_FIELDNUM           3u
#define DVA_PORT3_CRCPR_METER_RELAY_STATUS_DEFAULTVAL         0x0u
#define DVA_PORT4_CRCPR_METER_RELAY_STATUS                    0x4AFA2004u
#define DVA_PORT4_CRCPR_METER_RELAY_STATUS_FIELDNUM           3u
#define DVA_PORT4_CRCPR_METER_RELAY_STATUS_DEFAULTVAL         0x0u
#define DVA_PORT5_CRCPR_METER_RELAY_STATUS                    0x4AFA2804u
#define DVA_PORT5_CRCPR_METER_RELAY_STATUS_FIELDNUM           3u
#define DVA_PORT5_CRCPR_METER_RELAY_STATUS_DEFAULTVAL         0x0u
#define DVA_PORT6_CRCPR_METER_RELAY_STATUS                    0x4AFA3004u
#define DVA_PORT6_CRCPR_METER_RELAY_STATUS_FIELDNUM           3u
#define DVA_PORT6_CRCPR_METER_RELAY_STATUS_DEFAULTVAL         0x0u
#define DVA_PORT7_CRCPR_METER_RELAY_STATUS                    0x4AFA3804u
#define DVA_PORT7_CRCPR_METER_RELAY_STATUS_FIELDNUM           3u
#define DVA_PORT7_CRCPR_METER_RELAY_STATUS_DEFAULTVAL         0x0u
#define DVA_PORT8_CRCPR_METER_RELAY_STATUS                    0x4AFA4004u
#define DVA_PORT8_CRCPR_METER_RELAY_STATUS_FIELDNUM           3u
#define DVA_PORT8_CRCPR_METER_RELAY_STATUS_DEFAULTVAL         0x0u
#define DVA_PORT9_CRCPR_METER_RELAY_STATUS                    0x4AFA4804u
#define DVA_PORT9_CRCPR_METER_RELAY_STATUS_FIELDNUM           3u
#define DVA_PORT9_CRCPR_METER_RELAY_STATUS_DEFAULTVAL         0x0u
#define DVA_PORT10_CRCPR_METER_RELAY_STATUS                   0x4AFA5004u
#define DVA_PORT10_CRCPR_METER_RELAY_STATUS_FIELDNUM          3u
#define DVA_PORT10_CRCPR_METER_RELAY_STATUS_DEFAULTVAL        0x0u
#define DVA_PORT11_CRCPR_METER_RELAY_STATUS                   0x4AFA5804u
#define DVA_PORT11_CRCPR_METER_RELAY_STATUS_FIELDNUM          3u
#define DVA_PORT11_CRCPR_METER_RELAY_STATUS_DEFAULTVAL        0x0u
#define DVA_PORT12_CRCPR_METER_RELAY_STATUS                   0x4AFA6004u
#define DVA_PORT12_CRCPR_METER_RELAY_STATUS_FIELDNUM          3u
#define DVA_PORT12_CRCPR_METER_RELAY_STATUS_DEFAULTVAL        0x0u
#define DVA_PORT13_CRCPR_METER_RELAY_STATUS                   0x4AFA6804u
#define DVA_PORT13_CRCPR_METER_RELAY_STATUS_FIELDNUM          3u
#define DVA_PORT13_CRCPR_METER_RELAY_STATUS_DEFAULTVAL        0x0u
#define DVA_PORT14_CRCPR_METER_RELAY_STATUS                   0x4AFA7004u
#define DVA_PORT14_CRCPR_METER_RELAY_STATUS_FIELDNUM          3u
#define DVA_PORT14_CRCPR_METER_RELAY_STATUS_DEFAULTVAL        0x0u
#define DVA_PORT15_CRCPR_METER_RELAY_STATUS                   0x4AFA7804u
#define DVA_PORT15_CRCPR_METER_RELAY_STATUS_FIELDNUM          3u
#define DVA_PORT15_CRCPR_METER_RELAY_STATUS_DEFAULTVAL        0x0u
#define DVA_PORT0_CRCPR_IE                                    0x4AFA0008u
#define DVA_PORT0_CRCPR_IE_FIELDNUM                           2u
#define DVA_PORT0_CRCPR_IE_DEFAULTVAL                         0x0u
#define DVA_PORT1_CRCPR_IE                                    0x4AFA0808u
#define DVA_PORT1_CRCPR_IE_FIELDNUM                           2u
#define DVA_PORT1_CRCPR_IE_DEFAULTVAL                         0x0u
#define DVA_PORT2_CRCPR_IE                                    0x4AFA1008u
#define DVA_PORT2_CRCPR_IE_FIELDNUM                           2u
#define DVA_PORT2_CRCPR_IE_DEFAULTVAL                         0x0u
#define DVA_PORT3_CRCPR_IE                                    0x4AFA1808u
#define DVA_PORT3_CRCPR_IE_FIELDNUM                           2u
#define DVA_PORT3_CRCPR_IE_DEFAULTVAL                         0x0u
#define DVA_PORT4_CRCPR_IE                                    0x4AFA2008u
#define DVA_PORT4_CRCPR_IE_FIELDNUM                           2u
#define DVA_PORT4_CRCPR_IE_DEFAULTVAL                         0x0u
#define DVA_PORT5_CRCPR_IE                                    0x4AFA2808u
#define DVA_PORT5_CRCPR_IE_FIELDNUM                           2u
#define DVA_PORT5_CRCPR_IE_DEFAULTVAL                         0x0u
#define DVA_PORT6_CRCPR_IE                                    0x4AFA3008u
#define DVA_PORT6_CRCPR_IE_FIELDNUM                           2u
#define DVA_PORT6_CRCPR_IE_DEFAULTVAL                         0x0u
#define DVA_PORT7_CRCPR_IE                                    0x4AFA3808u
#define DVA_PORT7_CRCPR_IE_FIELDNUM                           2u
#define DVA_PORT7_CRCPR_IE_DEFAULTVAL                         0x0u
#define DVA_PORT8_CRCPR_IE                                    0x4AFA4008u
#define DVA_PORT8_CRCPR_IE_FIELDNUM                           2u
#define DVA_PORT8_CRCPR_IE_DEFAULTVAL                         0x0u
#define DVA_PORT9_CRCPR_IE                                    0x4AFA4808u
#define DVA_PORT9_CRCPR_IE_FIELDNUM                           2u
#define DVA_PORT9_CRCPR_IE_DEFAULTVAL                         0x0u
#define DVA_PORT10_CRCPR_IE                                   0x4AFA5008u
#define DVA_PORT10_CRCPR_IE_FIELDNUM                          2u
#define DVA_PORT10_CRCPR_IE_DEFAULTVAL                        0x0u
#define DVA_PORT11_CRCPR_IE                                   0x4AFA5808u
#define DVA_PORT11_CRCPR_IE_FIELDNUM                          2u
#define DVA_PORT11_CRCPR_IE_DEFAULTVAL                        0x0u
#define DVA_PORT12_CRCPR_IE                                   0x4AFA6008u
#define DVA_PORT12_CRCPR_IE_FIELDNUM                          2u
#define DVA_PORT12_CRCPR_IE_DEFAULTVAL                        0x0u
#define DVA_PORT13_CRCPR_IE                                   0x4AFA6808u
#define DVA_PORT13_CRCPR_IE_FIELDNUM                          2u
#define DVA_PORT13_CRCPR_IE_DEFAULTVAL                        0x0u
#define DVA_PORT14_CRCPR_IE                                   0x4AFA7008u
#define DVA_PORT14_CRCPR_IE_FIELDNUM                          2u
#define DVA_PORT14_CRCPR_IE_DEFAULTVAL                        0x0u
#define DVA_PORT15_CRCPR_IE                                   0x4AFA7808u
#define DVA_PORT15_CRCPR_IE_FIELDNUM                          2u
#define DVA_PORT15_CRCPR_IE_DEFAULTVAL                        0x0u
#define DVA_PORT0_CRCPR_IP                                    0x4AFA000Cu
#define DVA_PORT0_CRCPR_IP_FIELDNUM                           2u
#define DVA_PORT0_CRCPR_IP_DEFAULTVAL                         0x0u
#define DVA_PORT1_CRCPR_IP                                    0x4AFA080Cu
#define DVA_PORT1_CRCPR_IP_FIELDNUM                           2u
#define DVA_PORT1_CRCPR_IP_DEFAULTVAL                         0x0u
#define DVA_PORT2_CRCPR_IP                                    0x4AFA100Cu
#define DVA_PORT2_CRCPR_IP_FIELDNUM                           2u
#define DVA_PORT2_CRCPR_IP_DEFAULTVAL                         0x0u
#define DVA_PORT3_CRCPR_IP                                    0x4AFA180Cu
#define DVA_PORT3_CRCPR_IP_FIELDNUM                           2u
#define DVA_PORT3_CRCPR_IP_DEFAULTVAL                         0x0u
#define DVA_PORT4_CRCPR_IP                                    0x4AFA200Cu
#define DVA_PORT4_CRCPR_IP_FIELDNUM                           2u
#define DVA_PORT4_CRCPR_IP_DEFAULTVAL                         0x0u
#define DVA_PORT5_CRCPR_IP                                    0x4AFA280Cu
#define DVA_PORT5_CRCPR_IP_FIELDNUM                           2u
#define DVA_PORT5_CRCPR_IP_DEFAULTVAL                         0x0u
#define DVA_PORT6_CRCPR_IP                                    0x4AFA300Cu
#define DVA_PORT6_CRCPR_IP_FIELDNUM                           2u
#define DVA_PORT6_CRCPR_IP_DEFAULTVAL                         0x0u
#define DVA_PORT7_CRCPR_IP                                    0x4AFA380Cu
#define DVA_PORT7_CRCPR_IP_FIELDNUM                           2u
#define DVA_PORT7_CRCPR_IP_DEFAULTVAL                         0x0u
#define DVA_PORT8_CRCPR_IP                                    0x4AFA400Cu
#define DVA_PORT8_CRCPR_IP_FIELDNUM                           2u
#define DVA_PORT8_CRCPR_IP_DEFAULTVAL                         0x0u
#define DVA_PORT9_CRCPR_IP                                    0x4AFA480Cu
#define DVA_PORT9_CRCPR_IP_FIELDNUM                           2u
#define DVA_PORT9_CRCPR_IP_DEFAULTVAL                         0x0u
#define DVA_PORT10_CRCPR_IP                                   0x4AFA500Cu
#define DVA_PORT10_CRCPR_IP_FIELDNUM                          2u
#define DVA_PORT10_CRCPR_IP_DEFAULTVAL                        0x0u
#define DVA_PORT11_CRCPR_IP                                   0x4AFA580Cu
#define DVA_PORT11_CRCPR_IP_FIELDNUM                          2u
#define DVA_PORT11_CRCPR_IP_DEFAULTVAL                        0x0u
#define DVA_PORT12_CRCPR_IP                                   0x4AFA600Cu
#define DVA_PORT12_CRCPR_IP_FIELDNUM                          2u
#define DVA_PORT12_CRCPR_IP_DEFAULTVAL                        0x0u
#define DVA_PORT13_CRCPR_IP                                   0x4AFA680Cu
#define DVA_PORT13_CRCPR_IP_FIELDNUM                          2u
#define DVA_PORT13_CRCPR_IP_DEFAULTVAL                        0x0u
#define DVA_PORT14_CRCPR_IP                                   0x4AFA700Cu
#define DVA_PORT14_CRCPR_IP_FIELDNUM                          2u
#define DVA_PORT14_CRCPR_IP_DEFAULTVAL                        0x0u
#define DVA_PORT15_CRCPR_IP                                   0x4AFA780Cu
#define DVA_PORT15_CRCPR_IP_FIELDNUM                          2u
#define DVA_PORT15_CRCPR_IP_DEFAULTVAL                        0x0u
#define DVA_PORT0_CRCPR_METER_INC_WEIGHT                      0x4AFA0010u
#define DVA_PORT0_CRCPR_METER_INC_WEIGHT_FIELDNUM             1u
#define DVA_PORT0_CRCPR_METER_INC_WEIGHT_DEFAULTVAL           0x1000u
#define DVA_PORT1_CRCPR_METER_INC_WEIGHT                      0x4AFA0810u
#define DVA_PORT1_CRCPR_METER_INC_WEIGHT_FIELDNUM             1u
#define DVA_PORT1_CRCPR_METER_INC_WEIGHT_DEFAULTVAL           0x1000u
#define DVA_PORT2_CRCPR_METER_INC_WEIGHT                      0x4AFA1010u
#define DVA_PORT2_CRCPR_METER_INC_WEIGHT_FIELDNUM             1u
#define DVA_PORT2_CRCPR_METER_INC_WEIGHT_DEFAULTVAL           0x1000u
#define DVA_PORT3_CRCPR_METER_INC_WEIGHT                      0x4AFA1810u
#define DVA_PORT3_CRCPR_METER_INC_WEIGHT_FIELDNUM             1u
#define DVA_PORT3_CRCPR_METER_INC_WEIGHT_DEFAULTVAL           0x1000u
#define DVA_PORT4_CRCPR_METER_INC_WEIGHT                      0x4AFA2010u
#define DVA_PORT4_CRCPR_METER_INC_WEIGHT_FIELDNUM             1u
#define DVA_PORT4_CRCPR_METER_INC_WEIGHT_DEFAULTVAL           0x1000u
#define DVA_PORT5_CRCPR_METER_INC_WEIGHT                      0x4AFA2810u
#define DVA_PORT5_CRCPR_METER_INC_WEIGHT_FIELDNUM             1u
#define DVA_PORT5_CRCPR_METER_INC_WEIGHT_DEFAULTVAL           0x1000u
#define DVA_PORT6_CRCPR_METER_INC_WEIGHT                      0x4AFA3010u
#define DVA_PORT6_CRCPR_METER_INC_WEIGHT_FIELDNUM             1u
#define DVA_PORT6_CRCPR_METER_INC_WEIGHT_DEFAULTVAL           0x1000u
#define DVA_PORT7_CRCPR_METER_INC_WEIGHT                      0x4AFA3810u
#define DVA_PORT7_CRCPR_METER_INC_WEIGHT_FIELDNUM             1u
#define DVA_PORT7_CRCPR_METER_INC_WEIGHT_DEFAULTVAL           0x1000u
#define DVA_PORT8_CRCPR_METER_INC_WEIGHT                      0x4AFA4010u
#define DVA_PORT8_CRCPR_METER_INC_WEIGHT_FIELDNUM             1u
#define DVA_PORT8_CRCPR_METER_INC_WEIGHT_DEFAULTVAL           0x1000u
#define DVA_PORT9_CRCPR_METER_INC_WEIGHT                      0x4AFA4810u
#define DVA_PORT9_CRCPR_METER_INC_WEIGHT_FIELDNUM             1u
#define DVA_PORT9_CRCPR_METER_INC_WEIGHT_DEFAULTVAL           0x1000u
#define DVA_PORT10_CRCPR_METER_INC_WEIGHT                     0x4AFA5010u
#define DVA_PORT10_CRCPR_METER_INC_WEIGHT_FIELDNUM            1u
#define DVA_PORT10_CRCPR_METER_INC_WEIGHT_DEFAULTVAL          0x1000u
#define DVA_PORT11_CRCPR_METER_INC_WEIGHT                     0x4AFA5810u
#define DVA_PORT11_CRCPR_METER_INC_WEIGHT_FIELDNUM            1u
#define DVA_PORT11_CRCPR_METER_INC_WEIGHT_DEFAULTVAL          0x1000u
#define DVA_PORT12_CRCPR_METER_INC_WEIGHT                     0x4AFA6010u
#define DVA_PORT12_CRCPR_METER_INC_WEIGHT_FIELDNUM            1u
#define DVA_PORT12_CRCPR_METER_INC_WEIGHT_DEFAULTVAL          0x1000u
#define DVA_PORT13_CRCPR_METER_INC_WEIGHT                     0x4AFA6810u
#define DVA_PORT13_CRCPR_METER_INC_WEIGHT_FIELDNUM            1u
#define DVA_PORT13_CRCPR_METER_INC_WEIGHT_DEFAULTVAL          0x1000u
#define DVA_PORT14_CRCPR_METER_INC_WEIGHT                     0x4AFA7010u
#define DVA_PORT14_CRCPR_METER_INC_WEIGHT_FIELDNUM            1u
#define DVA_PORT14_CRCPR_METER_INC_WEIGHT_DEFAULTVAL          0x1000u
#define DVA_PORT15_CRCPR_METER_INC_WEIGHT                     0x4AFA7810u
#define DVA_PORT15_CRCPR_METER_INC_WEIGHT_FIELDNUM            1u
#define DVA_PORT15_CRCPR_METER_INC_WEIGHT_DEFAULTVAL          0x1000u
#define DVA_PORT0_CRCPR_METER_DEC_WEIGHT                      0x4AFA0014u
#define DVA_PORT0_CRCPR_METER_DEC_WEIGHT_FIELDNUM             1u
#define DVA_PORT0_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL           0x1u
#define DVA_PORT1_CRCPR_METER_DEC_WEIGHT                      0x4AFA0814u
#define DVA_PORT1_CRCPR_METER_DEC_WEIGHT_FIELDNUM             1u
#define DVA_PORT1_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL           0x1u
#define DVA_PORT2_CRCPR_METER_DEC_WEIGHT                      0x4AFA1014u
#define DVA_PORT2_CRCPR_METER_DEC_WEIGHT_FIELDNUM             1u
#define DVA_PORT2_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL           0x1u
#define DVA_PORT3_CRCPR_METER_DEC_WEIGHT                      0x4AFA1814u
#define DVA_PORT3_CRCPR_METER_DEC_WEIGHT_FIELDNUM             1u
#define DVA_PORT3_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL           0x1u
#define DVA_PORT4_CRCPR_METER_DEC_WEIGHT                      0x4AFA2014u
#define DVA_PORT4_CRCPR_METER_DEC_WEIGHT_FIELDNUM             1u
#define DVA_PORT4_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL           0x1u
#define DVA_PORT5_CRCPR_METER_DEC_WEIGHT                      0x4AFA2814u
#define DVA_PORT5_CRCPR_METER_DEC_WEIGHT_FIELDNUM             1u
#define DVA_PORT5_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL           0x1u
#define DVA_PORT6_CRCPR_METER_DEC_WEIGHT                      0x4AFA3014u
#define DVA_PORT6_CRCPR_METER_DEC_WEIGHT_FIELDNUM             1u
#define DVA_PORT6_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL           0x1u
#define DVA_PORT7_CRCPR_METER_DEC_WEIGHT                      0x4AFA3814u
#define DVA_PORT7_CRCPR_METER_DEC_WEIGHT_FIELDNUM             1u
#define DVA_PORT7_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL           0x1u
#define DVA_PORT8_CRCPR_METER_DEC_WEIGHT                      0x4AFA4014u
#define DVA_PORT8_CRCPR_METER_DEC_WEIGHT_FIELDNUM             1u
#define DVA_PORT8_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL           0x1u
#define DVA_PORT9_CRCPR_METER_DEC_WEIGHT                      0x4AFA4814u
#define DVA_PORT9_CRCPR_METER_DEC_WEIGHT_FIELDNUM             1u
#define DVA_PORT9_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL           0x1u
#define DVA_PORT10_CRCPR_METER_DEC_WEIGHT                     0x4AFA5014u
#define DVA_PORT10_CRCPR_METER_DEC_WEIGHT_FIELDNUM            1u
#define DVA_PORT10_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL          0x1u
#define DVA_PORT11_CRCPR_METER_DEC_WEIGHT                     0x4AFA5814u
#define DVA_PORT11_CRCPR_METER_DEC_WEIGHT_FIELDNUM            1u
#define DVA_PORT11_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL          0x1u
#define DVA_PORT12_CRCPR_METER_DEC_WEIGHT                     0x4AFA6014u
#define DVA_PORT12_CRCPR_METER_DEC_WEIGHT_FIELDNUM            1u
#define DVA_PORT12_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL          0x1u
#define DVA_PORT13_CRCPR_METER_DEC_WEIGHT                     0x4AFA6814u
#define DVA_PORT13_CRCPR_METER_DEC_WEIGHT_FIELDNUM            1u
#define DVA_PORT13_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL          0x1u
#define DVA_PORT14_CRCPR_METER_DEC_WEIGHT                     0x4AFA7014u
#define DVA_PORT14_CRCPR_METER_DEC_WEIGHT_FIELDNUM            1u
#define DVA_PORT14_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL          0x1u
#define DVA_PORT15_CRCPR_METER_DEC_WEIGHT                     0x4AFA7814u
#define DVA_PORT15_CRCPR_METER_DEC_WEIGHT_FIELDNUM            1u
#define DVA_PORT15_CRCPR_METER_DEC_WEIGHT_DEFAULTVAL          0x1u
#define DVA_PORT0_CRCPR_METER_RELAYDIS_THOD                   0x4AFA0018u
#define DVA_PORT0_CRCPR_METER_RELAYDIS_THOD_FIELDNUM          1u
#define DVA_PORT0_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL        0x1800u
#define DVA_PORT1_CRCPR_METER_RELAYDIS_THOD                   0x4AFA0818u
#define DVA_PORT1_CRCPR_METER_RELAYDIS_THOD_FIELDNUM          1u
#define DVA_PORT1_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL        0x1800u
#define DVA_PORT2_CRCPR_METER_RELAYDIS_THOD                   0x4AFA1018u
#define DVA_PORT2_CRCPR_METER_RELAYDIS_THOD_FIELDNUM          1u
#define DVA_PORT2_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL        0x1800u
#define DVA_PORT3_CRCPR_METER_RELAYDIS_THOD                   0x4AFA1818u
#define DVA_PORT3_CRCPR_METER_RELAYDIS_THOD_FIELDNUM          1u
#define DVA_PORT3_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL        0x1800u
#define DVA_PORT4_CRCPR_METER_RELAYDIS_THOD                   0x4AFA2018u
#define DVA_PORT4_CRCPR_METER_RELAYDIS_THOD_FIELDNUM          1u
#define DVA_PORT4_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL        0x1800u
#define DVA_PORT5_CRCPR_METER_RELAYDIS_THOD                   0x4AFA2818u
#define DVA_PORT5_CRCPR_METER_RELAYDIS_THOD_FIELDNUM          1u
#define DVA_PORT5_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL        0x1800u
#define DVA_PORT6_CRCPR_METER_RELAYDIS_THOD                   0x4AFA3018u
#define DVA_PORT6_CRCPR_METER_RELAYDIS_THOD_FIELDNUM          1u
#define DVA_PORT6_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL        0x1800u
#define DVA_PORT7_CRCPR_METER_RELAYDIS_THOD                   0x4AFA3818u
#define DVA_PORT7_CRCPR_METER_RELAYDIS_THOD_FIELDNUM          1u
#define DVA_PORT7_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL        0x1800u
#define DVA_PORT8_CRCPR_METER_RELAYDIS_THOD                   0x4AFA4018u
#define DVA_PORT8_CRCPR_METER_RELAYDIS_THOD_FIELDNUM          1u
#define DVA_PORT8_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL        0x1800u
#define DVA_PORT9_CRCPR_METER_RELAYDIS_THOD                   0x4AFA4818u
#define DVA_PORT9_CRCPR_METER_RELAYDIS_THOD_FIELDNUM          1u
#define DVA_PORT9_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL        0x1800u
#define DVA_PORT10_CRCPR_METER_RELAYDIS_THOD                  0x4AFA5018u
#define DVA_PORT10_CRCPR_METER_RELAYDIS_THOD_FIELDNUM         1u
#define DVA_PORT10_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL       0x1800u
#define DVA_PORT11_CRCPR_METER_RELAYDIS_THOD                  0x4AFA5818u
#define DVA_PORT11_CRCPR_METER_RELAYDIS_THOD_FIELDNUM         1u
#define DVA_PORT11_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL       0x1800u
#define DVA_PORT12_CRCPR_METER_RELAYDIS_THOD                  0x4AFA6018u
#define DVA_PORT12_CRCPR_METER_RELAYDIS_THOD_FIELDNUM         1u
#define DVA_PORT12_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL       0x1800u
#define DVA_PORT13_CRCPR_METER_RELAYDIS_THOD                  0x4AFA6818u
#define DVA_PORT13_CRCPR_METER_RELAYDIS_THOD_FIELDNUM         1u
#define DVA_PORT13_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL       0x1800u
#define DVA_PORT14_CRCPR_METER_RELAYDIS_THOD                  0x4AFA7018u
#define DVA_PORT14_CRCPR_METER_RELAYDIS_THOD_FIELDNUM         1u
#define DVA_PORT14_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL       0x1800u
#define DVA_PORT15_CRCPR_METER_RELAYDIS_THOD                  0x4AFA7818u
#define DVA_PORT15_CRCPR_METER_RELAYDIS_THOD_FIELDNUM         1u
#define DVA_PORT15_CRCPR_METER_RELAYDIS_THOD_DEFAULTVAL       0x1800u
#define DVA_PORT0_CRCPR_METER_RELAYALE_THOD                   0x4AFA001Cu
#define DVA_PORT0_CRCPR_METER_RELAYALE_THOD_FIELDNUM          1u
#define DVA_PORT0_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL        0x1400u
#define DVA_PORT1_CRCPR_METER_RELAYALE_THOD                   0x4AFA081Cu
#define DVA_PORT1_CRCPR_METER_RELAYALE_THOD_FIELDNUM          1u
#define DVA_PORT1_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL        0x1400u
#define DVA_PORT2_CRCPR_METER_RELAYALE_THOD                   0x4AFA101Cu
#define DVA_PORT2_CRCPR_METER_RELAYALE_THOD_FIELDNUM          1u
#define DVA_PORT2_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL        0x1400u
#define DVA_PORT3_CRCPR_METER_RELAYALE_THOD                   0x4AFA181Cu
#define DVA_PORT3_CRCPR_METER_RELAYALE_THOD_FIELDNUM          1u
#define DVA_PORT3_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL        0x1400u
#define DVA_PORT4_CRCPR_METER_RELAYALE_THOD                   0x4AFA201Cu
#define DVA_PORT4_CRCPR_METER_RELAYALE_THOD_FIELDNUM          1u
#define DVA_PORT4_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL        0x1400u
#define DVA_PORT5_CRCPR_METER_RELAYALE_THOD                   0x4AFA281Cu
#define DVA_PORT5_CRCPR_METER_RELAYALE_THOD_FIELDNUM          1u
#define DVA_PORT5_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL        0x1400u
#define DVA_PORT6_CRCPR_METER_RELAYALE_THOD                   0x4AFA301Cu
#define DVA_PORT6_CRCPR_METER_RELAYALE_THOD_FIELDNUM          1u
#define DVA_PORT6_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL        0x1400u
#define DVA_PORT7_CRCPR_METER_RELAYALE_THOD                   0x4AFA381Cu
#define DVA_PORT7_CRCPR_METER_RELAYALE_THOD_FIELDNUM          1u
#define DVA_PORT7_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL        0x1400u
#define DVA_PORT8_CRCPR_METER_RELAYALE_THOD                   0x4AFA401Cu
#define DVA_PORT8_CRCPR_METER_RELAYALE_THOD_FIELDNUM          1u
#define DVA_PORT8_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL        0x1400u
#define DVA_PORT9_CRCPR_METER_RELAYALE_THOD                   0x4AFA481Cu
#define DVA_PORT9_CRCPR_METER_RELAYALE_THOD_FIELDNUM          1u
#define DVA_PORT9_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL        0x1400u
#define DVA_PORT10_CRCPR_METER_RELAYALE_THOD                  0x4AFA501Cu
#define DVA_PORT10_CRCPR_METER_RELAYALE_THOD_FIELDNUM         1u
#define DVA_PORT10_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL       0x1400u
#define DVA_PORT11_CRCPR_METER_RELAYALE_THOD                  0x4AFA581Cu
#define DVA_PORT11_CRCPR_METER_RELAYALE_THOD_FIELDNUM         1u
#define DVA_PORT11_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL       0x1400u
#define DVA_PORT12_CRCPR_METER_RELAYALE_THOD                  0x4AFA601Cu
#define DVA_PORT12_CRCPR_METER_RELAYALE_THOD_FIELDNUM         1u
#define DVA_PORT12_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL       0x1400u
#define DVA_PORT13_CRCPR_METER_RELAYALE_THOD                  0x4AFA681Cu
#define DVA_PORT13_CRCPR_METER_RELAYALE_THOD_FIELDNUM         1u
#define DVA_PORT13_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL       0x1400u
#define DVA_PORT14_CRCPR_METER_RELAYALE_THOD                  0x4AFA701Cu
#define DVA_PORT14_CRCPR_METER_RELAYALE_THOD_FIELDNUM         1u
#define DVA_PORT14_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL       0x1400u
#define DVA_PORT15_CRCPR_METER_RELAYALE_THOD                  0x4AFA781Cu
#define DVA_PORT15_CRCPR_METER_RELAYALE_THOD_FIELDNUM         1u
#define DVA_PORT15_CRCPR_METER_RELAYALE_THOD_DEFAULTVAL       0x1400u
#define DVA_PORT0_CRCPR_METER_CNT                             0x4AFA0020u
#define DVA_PORT0_CRCPR_METER_CNT_FIELDNUM                    1u
#define DVA_PORT0_CRCPR_METER_CNT_DEFAULTVAL                  0x0u
#define DVA_PORT1_CRCPR_METER_CNT                             0x4AFA0820u
#define DVA_PORT1_CRCPR_METER_CNT_FIELDNUM                    1u
#define DVA_PORT1_CRCPR_METER_CNT_DEFAULTVAL                  0x0u
#define DVA_PORT2_CRCPR_METER_CNT                             0x4AFA1020u
#define DVA_PORT2_CRCPR_METER_CNT_FIELDNUM                    1u
#define DVA_PORT2_CRCPR_METER_CNT_DEFAULTVAL                  0x0u
#define DVA_PORT3_CRCPR_METER_CNT                             0x4AFA1820u
#define DVA_PORT3_CRCPR_METER_CNT_FIELDNUM                    1u
#define DVA_PORT3_CRCPR_METER_CNT_DEFAULTVAL                  0x0u
#define DVA_PORT4_CRCPR_METER_CNT                             0x4AFA2020u
#define DVA_PORT4_CRCPR_METER_CNT_FIELDNUM                    1u
#define DVA_PORT4_CRCPR_METER_CNT_DEFAULTVAL                  0x0u
#define DVA_PORT5_CRCPR_METER_CNT                             0x4AFA2820u
#define DVA_PORT5_CRCPR_METER_CNT_FIELDNUM                    1u
#define DVA_PORT5_CRCPR_METER_CNT_DEFAULTVAL                  0x0u
#define DVA_PORT6_CRCPR_METER_CNT                             0x4AFA3020u
#define DVA_PORT6_CRCPR_METER_CNT_FIELDNUM                    1u
#define DVA_PORT6_CRCPR_METER_CNT_DEFAULTVAL                  0x0u
#define DVA_PORT7_CRCPR_METER_CNT                             0x4AFA3820u
#define DVA_PORT7_CRCPR_METER_CNT_FIELDNUM                    1u
#define DVA_PORT7_CRCPR_METER_CNT_DEFAULTVAL                  0x0u
#define DVA_PORT8_CRCPR_METER_CNT                             0x4AFA4020u
#define DVA_PORT8_CRCPR_METER_CNT_FIELDNUM                    1u
#define DVA_PORT8_CRCPR_METER_CNT_DEFAULTVAL                  0x0u
#define DVA_PORT9_CRCPR_METER_CNT                             0x4AFA4820u
#define DVA_PORT9_CRCPR_METER_CNT_FIELDNUM                    1u
#define DVA_PORT9_CRCPR_METER_CNT_DEFAULTVAL                  0x0u
#define DVA_PORT10_CRCPR_METER_CNT                            0x4AFA5020u
#define DVA_PORT10_CRCPR_METER_CNT_FIELDNUM                   1u
#define DVA_PORT10_CRCPR_METER_CNT_DEFAULTVAL                 0x0u
#define DVA_PORT11_CRCPR_METER_CNT                            0x4AFA5820u
#define DVA_PORT11_CRCPR_METER_CNT_FIELDNUM                   1u
#define DVA_PORT11_CRCPR_METER_CNT_DEFAULTVAL                 0x0u
#define DVA_PORT12_CRCPR_METER_CNT                            0x4AFA6020u
#define DVA_PORT12_CRCPR_METER_CNT_FIELDNUM                   1u
#define DVA_PORT12_CRCPR_METER_CNT_DEFAULTVAL                 0x0u
#define DVA_PORT13_CRCPR_METER_CNT                            0x4AFA6820u
#define DVA_PORT13_CRCPR_METER_CNT_FIELDNUM                   1u
#define DVA_PORT13_CRCPR_METER_CNT_DEFAULTVAL                 0x0u
#define DVA_PORT14_CRCPR_METER_CNT                            0x4AFA7020u
#define DVA_PORT14_CRCPR_METER_CNT_FIELDNUM                   1u
#define DVA_PORT14_CRCPR_METER_CNT_DEFAULTVAL                 0x0u
#define DVA_PORT15_CRCPR_METER_CNT                            0x4AFA7820u
#define DVA_PORT15_CRCPR_METER_CNT_FIELDNUM                   1u
#define DVA_PORT15_CRCPR_METER_CNT_DEFAULTVAL                 0x0u
#define DVA_PORT0_CRCPR_METER_CYCTIME                         0x4AFA0024u
#define DVA_PORT0_CRCPR_METER_CYCTIME_FIELDNUM                1u
#define DVA_PORT0_CRCPR_METER_CYCTIME_DEFAULTVAL              0x0u
#define DVA_PORT1_CRCPR_METER_CYCTIME                         0x4AFA0824u
#define DVA_PORT1_CRCPR_METER_CYCTIME_FIELDNUM                1u
#define DVA_PORT1_CRCPR_METER_CYCTIME_DEFAULTVAL              0x0u
#define DVA_PORT2_CRCPR_METER_CYCTIME                         0x4AFA1024u
#define DVA_PORT2_CRCPR_METER_CYCTIME_FIELDNUM                1u
#define DVA_PORT2_CRCPR_METER_CYCTIME_DEFAULTVAL              0x0u
#define DVA_PORT3_CRCPR_METER_CYCTIME                         0x4AFA1824u
#define DVA_PORT3_CRCPR_METER_CYCTIME_FIELDNUM                1u
#define DVA_PORT3_CRCPR_METER_CYCTIME_DEFAULTVAL              0x0u
#define DVA_PORT4_CRCPR_METER_CYCTIME                         0x4AFA2024u
#define DVA_PORT4_CRCPR_METER_CYCTIME_FIELDNUM                1u
#define DVA_PORT4_CRCPR_METER_CYCTIME_DEFAULTVAL              0x0u
#define DVA_PORT5_CRCPR_METER_CYCTIME                         0x4AFA2824u
#define DVA_PORT5_CRCPR_METER_CYCTIME_FIELDNUM                1u
#define DVA_PORT5_CRCPR_METER_CYCTIME_DEFAULTVAL              0x0u
#define DVA_PORT6_CRCPR_METER_CYCTIME                         0x4AFA3024u
#define DVA_PORT6_CRCPR_METER_CYCTIME_FIELDNUM                1u
#define DVA_PORT6_CRCPR_METER_CYCTIME_DEFAULTVAL              0x0u
#define DVA_PORT7_CRCPR_METER_CYCTIME                         0x4AFA3824u
#define DVA_PORT7_CRCPR_METER_CYCTIME_FIELDNUM                1u
#define DVA_PORT7_CRCPR_METER_CYCTIME_DEFAULTVAL              0x0u
#define DVA_PORT8_CRCPR_METER_CYCTIME                         0x4AFA4024u
#define DVA_PORT8_CRCPR_METER_CYCTIME_FIELDNUM                1u
#define DVA_PORT8_CRCPR_METER_CYCTIME_DEFAULTVAL              0x0u
#define DVA_PORT9_CRCPR_METER_CYCTIME                         0x4AFA4824u
#define DVA_PORT9_CRCPR_METER_CYCTIME_FIELDNUM                1u
#define DVA_PORT9_CRCPR_METER_CYCTIME_DEFAULTVAL              0x0u
#define DVA_PORT10_CRCPR_METER_CYCTIME                        0x4AFA5024u
#define DVA_PORT10_CRCPR_METER_CYCTIME_FIELDNUM               1u
#define DVA_PORT10_CRCPR_METER_CYCTIME_DEFAULTVAL             0x0u
#define DVA_PORT11_CRCPR_METER_CYCTIME                        0x4AFA5824u
#define DVA_PORT11_CRCPR_METER_CYCTIME_FIELDNUM               1u
#define DVA_PORT11_CRCPR_METER_CYCTIME_DEFAULTVAL             0x0u
#define DVA_PORT12_CRCPR_METER_CYCTIME                        0x4AFA6024u
#define DVA_PORT12_CRCPR_METER_CYCTIME_FIELDNUM               1u
#define DVA_PORT12_CRCPR_METER_CYCTIME_DEFAULTVAL             0x0u
#define DVA_PORT13_CRCPR_METER_CYCTIME                        0x4AFA6824u
#define DVA_PORT13_CRCPR_METER_CYCTIME_FIELDNUM               1u
#define DVA_PORT13_CRCPR_METER_CYCTIME_DEFAULTVAL             0x0u
#define DVA_PORT14_CRCPR_METER_CYCTIME                        0x4AFA7024u
#define DVA_PORT14_CRCPR_METER_CYCTIME_FIELDNUM               1u
#define DVA_PORT14_CRCPR_METER_CYCTIME_DEFAULTVAL             0x0u
#define DVA_PORT15_CRCPR_METER_CYCTIME                        0x4AFA7824u
#define DVA_PORT15_CRCPR_METER_CYCTIME_FIELDNUM               1u
#define DVA_PORT15_CRCPR_METER_CYCTIME_DEFAULTVAL             0x0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS             0x4AFA0028u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM    2u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL  0x0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS             0x4AFA0828u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM    2u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL  0x0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS             0x4AFA1028u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM    2u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL  0x0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS             0x4AFA1828u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM    2u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL  0x0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS             0x4AFA2028u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM    2u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL  0x0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS             0x4AFA2828u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM    2u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL  0x0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS             0x4AFA3028u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM    2u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL  0x0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS             0x4AFA3828u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM    2u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL  0x0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS             0x4AFA4028u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM    2u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL  0x0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS             0x4AFA4828u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM    2u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL  0x0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS            0x4AFA5028u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM   2u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL 0x0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS            0x4AFA5828u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM   2u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL 0x0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS            0x4AFA6028u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM   2u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL 0x0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS            0x4AFA6828u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM   2u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL 0x0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS            0x4AFA7028u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM   2u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL 0x0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS            0x4AFA7828u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FIELDNUM   2u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_DEFAULTVAL 0x0u
#endif
#endif /* DVA_RTKAS_REG_LIST_FILE_PORT_RELAY_DIS_H_ */