/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_LIST_FILE_ALE_TABLE_ACCESS_H_
#define DVA_RTKAS_REG_LIST_FILE_ALE_TABLE_ACCESS_H_

#ifdef DVA_FILE_ALE_TABLE_ACCESS
/* File: Table Access */
#define DVA_ALE_INDIRECT_CONTROL_FOR_INTERNAL_CPU               0x4A400000u
#define DVA_ALE_INDIRECT_CONTROL_FOR_INTERNAL_CPU_FIELDNUM      5u
#define DVA_ALE_INDIRECT_CONTROL_FOR_INTERNAL_CPU_DEFAULTVAL    0x0u
#define DVA_ALE_INDIRECT_DATA0_FOR_INTERNAL_CPU                 0x4A400004u
#define DVA_ALE_INDIRECT_DATA0_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DVA_ALE_INDIRECT_DATA0_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DVA_ALE_INDIRECT_DATA1_FOR_INTERNAL_CPU                 0x4A400008u
#define DVA_ALE_INDIRECT_DATA1_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DVA_ALE_INDIRECT_DATA1_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DVA_ALE_INDIRECT_DATA2_FOR_INTERNAL_CPU                 0x4A40000Cu
#define DVA_ALE_INDIRECT_DATA2_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DVA_ALE_INDIRECT_DATA2_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DVA_ALE_INDIRECT_DATA3_FOR_INTERNAL_CPU                 0x4A400010u
#define DVA_ALE_INDIRECT_DATA3_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DVA_ALE_INDIRECT_DATA3_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DVA_ALE_INDIRECT_DATA4_FOR_INTERNAL_CPU                 0x4A400014u
#define DVA_ALE_INDIRECT_DATA4_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DVA_ALE_INDIRECT_DATA4_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DVA_ALE_INDIRECT_DATA5_FOR_INTERNAL_CPU                 0x4A400018u
#define DVA_ALE_INDIRECT_DATA5_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DVA_ALE_INDIRECT_DATA5_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DVA_ALE_INDIRECT_DATA6_FOR_INTERNAL_CPU                 0x4A40001Cu
#define DVA_ALE_INDIRECT_DATA6_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DVA_ALE_INDIRECT_DATA6_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DVA_ALE_INDIRECT_DATA7_FOR_INTERNAL_CPU                 0x4A400020u
#define DVA_ALE_INDIRECT_DATA7_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DVA_ALE_INDIRECT_DATA7_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DVA_ALE_INDIRECT_DATA8_FOR_INTERNAL_CPU                 0x4A400024u
#define DVA_ALE_INDIRECT_DATA8_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DVA_ALE_INDIRECT_DATA8_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DVA_ALE_INDIRECT_DATA9_FOR_INTERNAL_CPU                 0x4A400028u
#define DVA_ALE_INDIRECT_DATA9_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DVA_ALE_INDIRECT_DATA9_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DVA_ALE_INDIRECT_DATA10_FOR_INTERNAL_CPU                0x4A40002Cu
#define DVA_ALE_INDIRECT_DATA10_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA10_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA11_FOR_INTERNAL_CPU                0x4A400030u
#define DVA_ALE_INDIRECT_DATA11_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA11_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA12_FOR_INTERNAL_CPU                0x4A400034u
#define DVA_ALE_INDIRECT_DATA12_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA12_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA13_FOR_INTERNAL_CPU                0x4A400038u
#define DVA_ALE_INDIRECT_DATA13_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA13_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA14_FOR_INTERNAL_CPU                0x4A40003Cu
#define DVA_ALE_INDIRECT_DATA14_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA14_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA15_FOR_INTERNAL_CPU                0x4A400040u
#define DVA_ALE_INDIRECT_DATA15_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA15_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA16_FOR_INTERNAL_CPU                0x4A400044u
#define DVA_ALE_INDIRECT_DATA16_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA16_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA17_FOR_INTERNAL_CPU                0x4A400048u
#define DVA_ALE_INDIRECT_DATA17_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA17_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA18_FOR_INTERNAL_CPU                0x4A40004Cu
#define DVA_ALE_INDIRECT_DATA18_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA18_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA19_FOR_INTERNAL_CPU                0x4A400050u
#define DVA_ALE_INDIRECT_DATA19_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA19_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA20_FOR_INTERNAL_CPU                0x4A400054u
#define DVA_ALE_INDIRECT_DATA20_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA20_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA21_FOR_INTERNAL_CPU                0x4A400058u
#define DVA_ALE_INDIRECT_DATA21_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA21_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA22_FOR_INTERNAL_CPU                0x4A40005Cu
#define DVA_ALE_INDIRECT_DATA22_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA22_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA23_FOR_INTERNAL_CPU                0x4A400060u
#define DVA_ALE_INDIRECT_DATA23_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA23_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA24_FOR_INTERNAL_CPU                0x4A400064u
#define DVA_ALE_INDIRECT_DATA24_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA24_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA25_FOR_INTERNAL_CPU                0x4A400068u
#define DVA_ALE_INDIRECT_DATA25_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA25_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA26_FOR_INTERNAL_CPU                0x4A40006Cu
#define DVA_ALE_INDIRECT_DATA26_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA26_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA27_FOR_INTERNAL_CPU                0x4A400070u
#define DVA_ALE_INDIRECT_DATA27_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA27_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA28_FOR_INTERNAL_CPU                0x4A400074u
#define DVA_ALE_INDIRECT_DATA28_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA28_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA29_FOR_INTERNAL_CPU                0x4A400078u
#define DVA_ALE_INDIRECT_DATA29_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA29_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA30_FOR_INTERNAL_CPU                0x4A40007Cu
#define DVA_ALE_INDIRECT_DATA30_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA30_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_DATA31_FOR_INTERNAL_CPU                0x4A400080u
#define DVA_ALE_INDIRECT_DATA31_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DVA_ALE_INDIRECT_DATA31_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DVA_ALE_INDIRECT_OCCUPY_STATUS                          0x4A400084u
#define DVA_ALE_INDIRECT_OCCUPY_STATUS_FIELDNUM                 3u
#define DVA_ALE_INDIRECT_OCCUPY_STATUS_DEFAULTVAL               0x0u
#define DVA_ALE_INDIRECT_CONTROL_FOR_EXTERNAL_DEVICE            0x4A400088u
#define DVA_ALE_INDIRECT_CONTROL_FOR_EXTERNAL_DEVICE_FIELDNUM   6u
#define DVA_ALE_INDIRECT_CONTROL_FOR_EXTERNAL_DEVICE_DEFAULTVAL 0x0u
#define DVA_ALE_INDIRECT_DATA0_FOR_EXTERNAL_DEVICE              0x4A40008Cu
#define DVA_ALE_INDIRECT_DATA0_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DVA_ALE_INDIRECT_DATA0_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DVA_ALE_INDIRECT_DATA1_FOR_EXTERNAL_DEVICE              0x4A400090u
#define DVA_ALE_INDIRECT_DATA1_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DVA_ALE_INDIRECT_DATA1_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DVA_ALE_INDIRECT_DATA2_FOR_EXTERNAL_DEVICE              0x4A400094u
#define DVA_ALE_INDIRECT_DATA2_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DVA_ALE_INDIRECT_DATA2_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DVA_ALE_INDIRECT_DATA3_FOR_EXTERNAL_DEVICE              0x4A400098u
#define DVA_ALE_INDIRECT_DATA3_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DVA_ALE_INDIRECT_DATA3_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DVA_ALE_INDIRECT_DATA4_FOR_EXTERNAL_DEVICE              0x4A40009Cu
#define DVA_ALE_INDIRECT_DATA4_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DVA_ALE_INDIRECT_DATA4_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DVA_ALE_INDIRECT_DATA5_FOR_EXTERNAL_DEVICE              0x4A4000A0u
#define DVA_ALE_INDIRECT_DATA5_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DVA_ALE_INDIRECT_DATA5_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DVA_ALE_INDIRECT_DATA6_FOR_EXTERNAL_DEVICE              0x4A4000A4u
#define DVA_ALE_INDIRECT_DATA6_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DVA_ALE_INDIRECT_DATA6_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DVA_ALE_INDIRECT_DATA7_FOR_EXTERNAL_DEVICE              0x4A4000A8u
#define DVA_ALE_INDIRECT_DATA7_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DVA_ALE_INDIRECT_DATA7_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DVA_ALE_INDIRECT_DATA8_FOR_EXTERNAL_DEVICE              0x4A4000ACu
#define DVA_ALE_INDIRECT_DATA8_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DVA_ALE_INDIRECT_DATA8_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DVA_ALE_INDIRECT_DATA9_FOR_EXTERNAL_DEVICE              0x4A4000B0u
#define DVA_ALE_INDIRECT_DATA9_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DVA_ALE_INDIRECT_DATA9_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DVA_ALE_INDIRECT_DATA10_FOR_EXTERNAL_DEVICE             0x4A4000B4u
#define DVA_ALE_INDIRECT_DATA10_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA10_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA11_FOR_EXTERNAL_DEVICE             0x4A4000B8u
#define DVA_ALE_INDIRECT_DATA11_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA11_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA12_FOR_EXTERNAL_DEVICE             0x4A4000BCu
#define DVA_ALE_INDIRECT_DATA12_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA12_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA13_FOR_EXTERNAL_DEVICE             0x4A4000C0u
#define DVA_ALE_INDIRECT_DATA13_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA13_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA14_FOR_EXTERNAL_DEVICE             0x4A4000C4u
#define DVA_ALE_INDIRECT_DATA14_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA14_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA15_FOR_EXTERNAL_DEVICE             0x4A4000C8u
#define DVA_ALE_INDIRECT_DATA15_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA15_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA16_FOR_EXTERNAL_DEVICE             0x4A4000CCu
#define DVA_ALE_INDIRECT_DATA16_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA16_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA17_FOR_EXTERNAL_DEVICE             0x4A4000D0u
#define DVA_ALE_INDIRECT_DATA17_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA17_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA18_FOR_EXTERNAL_DEVICE             0x4A4000D4u
#define DVA_ALE_INDIRECT_DATA18_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA18_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA19_FOR_EXTERNAL_DEVICE             0x4A4000D8u
#define DVA_ALE_INDIRECT_DATA19_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA19_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA20_FOR_EXTERNAL_DEVICE             0x4A4000DCu
#define DVA_ALE_INDIRECT_DATA20_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA20_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA21_FOR_EXTERNAL_DEVICE             0x4A4000E0u
#define DVA_ALE_INDIRECT_DATA21_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA21_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA22_FOR_EXTERNAL_DEVICE             0x4A4000E4u
#define DVA_ALE_INDIRECT_DATA22_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA22_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA23_FOR_EXTERNAL_DEVICE             0x4A4000E8u
#define DVA_ALE_INDIRECT_DATA23_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA23_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA24_FOR_EXTERNAL_DEVICE             0x4A4000ECu
#define DVA_ALE_INDIRECT_DATA24_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA24_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA25_FOR_EXTERNAL_DEVICE             0x4A4000F0u
#define DVA_ALE_INDIRECT_DATA25_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA25_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA26_FOR_EXTERNAL_DEVICE             0x4A4000F4u
#define DVA_ALE_INDIRECT_DATA26_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA26_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA27_FOR_EXTERNAL_DEVICE             0x4A4000F8u
#define DVA_ALE_INDIRECT_DATA27_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA27_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA28_FOR_EXTERNAL_DEVICE             0x4A4000FCu
#define DVA_ALE_INDIRECT_DATA28_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA28_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA29_FOR_EXTERNAL_DEVICE             0x4A400100u
#define DVA_ALE_INDIRECT_DATA29_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA29_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA30_FOR_EXTERNAL_DEVICE             0x4A400104u
#define DVA_ALE_INDIRECT_DATA30_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA30_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_INDIRECT_DATA31_FOR_EXTERNAL_DEVICE             0x4A400108u
#define DVA_ALE_INDIRECT_DATA31_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DVA_ALE_INDIRECT_DATA31_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DVA_ALE_BURST_OPERATION                                 0x4A40010Cu
#define DVA_ALE_BURST_OPERATION_FIELDNUM                        3u
#define DVA_ALE_BURST_OPERATION_DEFAULTVAL                      0x0u
#define DVA_ALE_DMY0                                            0x4A400110u
#define DVA_ALE_DMY0_FIELDNUM                                   1u
#define DVA_ALE_DMY0_DEFAULTVAL                                 0xFu
#define DVA_ALE_DMY1                                            0x4A400114u
#define DVA_ALE_DMY1_FIELDNUM                                   1u
#define DVA_ALE_DMY1_DEFAULTVAL                                 0x0u
#define DVA_ALE_DMY2                                            0x4A400118u
#define DVA_ALE_DMY2_FIELDNUM                                   1u
#define DVA_ALE_DMY2_DEFAULTVAL                                 0x0u
#define DVA_ALE_DMY3                                            0x4A40011Cu
#define DVA_ALE_DMY3_FIELDNUM                                   1u
#define DVA_ALE_DMY3_DEFAULTVAL                                 0x0u
#define DVA_ALE_DMY4                                            0x4A400120u
#define DVA_ALE_DMY4_FIELDNUM                                   1u
#define DVA_ALE_DMY4_DEFAULTVAL                                 0x0u
#define DVA_ALE_DMY5                                            0x4A400124u
#define DVA_ALE_DMY5_FIELDNUM                                   1u
#define DVA_ALE_DMY5_DEFAULTVAL                                 0x0u
#define DVA_ALE_DMY6                                            0x4A400128u
#define DVA_ALE_DMY6_FIELDNUM                                   1u
#define DVA_ALE_DMY6_DEFAULTVAL                                 0x0u
#define DVA_ALE_DMY7                                            0x4A40012Cu
#define DVA_ALE_DMY7_FIELDNUM                                   1u
#define DVA_ALE_DMY7_DEFAULTVAL                                 0x0u
#define DVA_ALE_DMY8                                            0x4A400130u
#define DVA_ALE_DMY8_FIELDNUM                                   1u
#define DVA_ALE_DMY8_DEFAULTVAL                                 0x0u
#define DVA_ALE_DMY9                                            0x4A400134u
#define DVA_ALE_DMY9_FIELDNUM                                   1u
#define DVA_ALE_DMY9_DEFAULTVAL                                 0x0u
#define DVA_DIRECT_ACCESS_EN                                    0x4A400138u
#define DVA_DIRECT_ACCESS_EN_FIELDNUM                           3u
#define DVA_DIRECT_ACCESS_EN_DEFAULTVAL                         0x0u
#define DVA_FUSA_PG_LOCK_DMY_ALE_TABLE_ACCESS                   0x4A40013Cu
#define DVA_FUSA_PG_LOCK_DMY_ALE_TABLE_ACCESS_FIELDNUM          2u
#define DVA_FUSA_PG_LOCK_DMY_ALE_TABLE_ACCESS_DEFAULTVAL        0x0u
#endif
#endif /* DVA_RTKAS_REG_LIST_FILE_ALE_TABLE_ACCESS_H_ */