/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_SAFETY_H_
#define DVA_RTKAS_REG_FIELD_FILE_SAFETY_H_

#ifdef DVA_FILE_SAFETY
/* File: Safety */
#define DVA_AGGREGATED_SAFETY_INTERRUPT_IP_AGGREGATED_SAFETY_INTERRUPT_STATUS_LSP  0u
#define DVA_AGGREGATED_SAFETY_INTERRUPT_IP_AGGREGATED_SAFETY_INTERRUPT_STATUS_LEN  11u
#define DVA_AGGREGATED_SAFETY_INTERRUPT_IP_AGGREGATED_SAFETY_INTERRUPT_STATUS_TYPE DVA_FIELD_TYPE_RO

#define DVA_AGGREGATED_SAFETY_INTERRUPT_IE_AGGREGATED_SAFETY_INTERRUPT_ENABLE_LSP  0u
#define DVA_AGGREGATED_SAFETY_INTERRUPT_IE_AGGREGATED_SAFETY_INTERRUPT_ENABLE_LEN  11u
#define DVA_AGGREGATED_SAFETY_INTERRUPT_IE_AGGREGATED_SAFETY_INTERRUPT_ENABLE_TYPE DVA_FIELD_TYPE_RW

#define DVA_MIB_0_IP_RG_MIB_0_IP_LSP  0u
#define DVA_MIB_0_IP_RG_MIB_0_IP_LEN  27u
#define DVA_MIB_0_IP_RG_MIB_0_IP_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_MIB_0_IE_RG_MIB_0_IE_LSP  0u
#define DVA_MIB_0_IE_RG_MIB_0_IE_LEN  27u
#define DVA_MIB_0_IE_RG_MIB_0_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_MIB_1_IP_RG_MIB_1_IP_LSP  0u
#define DVA_MIB_1_IP_RG_MIB_1_IP_LEN  11u
#define DVA_MIB_1_IP_RG_MIB_1_IP_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_MIB_1_IE_RG_MIB_1_IE_LSP  0u
#define DVA_MIB_1_IE_RG_MIB_1_IE_LEN  11u
#define DVA_MIB_1_IE_RG_MIB_1_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_MIB_2_IP_RG_MIB_2_IP_LSP  0u
#define DVA_MIB_2_IP_RG_MIB_2_IP_LEN  24u
#define DVA_MIB_2_IP_RG_MIB_2_IP_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_MIB_2_IE_RG_MIB_2_IE_LSP  0u
#define DVA_MIB_2_IE_RG_MIB_2_IE_LEN  24u
#define DVA_MIB_2_IE_RG_MIB_2_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_DISB_MON_RX_IP_DISB_MONITOR_RX_INTERRUPT_STATUS_LSP  0u
#define DVA_DISB_MON_RX_IP_DISB_MONITOR_RX_INTERRUPT_STATUS_LEN  16u
#define DVA_DISB_MON_RX_IP_DISB_MONITOR_RX_INTERRUPT_STATUS_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_DISB_MON_RX_IE_DISB_MONITOR_RX_INTERRUPT_ENABLE_LSP  0u
#define DVA_DISB_MON_RX_IE_DISB_MONITOR_RX_INTERRUPT_ENABLE_LEN  16u
#define DVA_DISB_MON_RX_IE_DISB_MONITOR_RX_INTERRUPT_ENABLE_TYPE DVA_FIELD_TYPE_RW

#define DVA_DISB_MON_TX_IP_DISB_MONITOR_TX_INTERRUPT_STATUS_LSP  0u
#define DVA_DISB_MON_TX_IP_DISB_MONITOR_TX_INTERRUPT_STATUS_LEN  16u
#define DVA_DISB_MON_TX_IP_DISB_MONITOR_TX_INTERRUPT_STATUS_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_DISB_MON_TX_IE_DISB_MONITOR_TX_INTERRUPT_ENABLE_LSP  0u
#define DVA_DISB_MON_TX_IE_DISB_MONITOR_TX_INTERRUPT_ENABLE_LEN  16u
#define DVA_DISB_MON_TX_IE_DISB_MONITOR_TX_INTERRUPT_ENABLE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CLK_DET_SLOW_RX_IP_RG_CLK_DET_SLOW_RX_IP_LSP  0u
#define DVA_CLK_DET_SLOW_RX_IP_RG_CLK_DET_SLOW_RX_IP_LEN  16u
#define DVA_CLK_DET_SLOW_RX_IP_RG_CLK_DET_SLOW_RX_IP_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_CLK_DET_SLOW_RX_IE_RG_CLK_DET_SLOW_RX_IE_LSP  0u
#define DVA_CLK_DET_SLOW_RX_IE_RG_CLK_DET_SLOW_RX_IE_LEN  16u
#define DVA_CLK_DET_SLOW_RX_IE_RG_CLK_DET_SLOW_RX_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CLK_DET_FAST_RX_IP_RG_CLK_DET_FAST_RX_IP_LSP  0u
#define DVA_CLK_DET_FAST_RX_IP_RG_CLK_DET_FAST_RX_IP_LEN  16u
#define DVA_CLK_DET_FAST_RX_IP_RG_CLK_DET_FAST_RX_IP_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_CLK_DET_FAST_RX_IE_RG_CLK_DET_FAST_RX_IE_LSP  0u
#define DVA_CLK_DET_FAST_RX_IE_RG_CLK_DET_FAST_RX_IE_LEN  16u
#define DVA_CLK_DET_FAST_RX_IE_RG_CLK_DET_FAST_RX_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CLK_DET_DEAD_RX_IP_RG_CLK_DET_DEAD_RX_IP_LSP  0u
#define DVA_CLK_DET_DEAD_RX_IP_RG_CLK_DET_DEAD_RX_IP_LEN  16u
#define DVA_CLK_DET_DEAD_RX_IP_RG_CLK_DET_DEAD_RX_IP_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_CLK_DET_DEAD_RX_IE_RG_CLK_DET_DEAD_RX_IE_LSP  0u
#define DVA_CLK_DET_DEAD_RX_IE_RG_CLK_DET_DEAD_RX_IE_LEN  16u
#define DVA_CLK_DET_DEAD_RX_IE_RG_CLK_DET_DEAD_RX_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CLK_DET_SLOW_TX_IP_RG_CLK_DET_SLOW_TX_IP_LSP  0u
#define DVA_CLK_DET_SLOW_TX_IP_RG_CLK_DET_SLOW_TX_IP_LEN  16u
#define DVA_CLK_DET_SLOW_TX_IP_RG_CLK_DET_SLOW_TX_IP_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_CLK_DET_SLOW_TX_IE_RG_CLK_DET_SLOW_TX_IE_LSP  0u
#define DVA_CLK_DET_SLOW_TX_IE_RG_CLK_DET_SLOW_TX_IE_LEN  16u
#define DVA_CLK_DET_SLOW_TX_IE_RG_CLK_DET_SLOW_TX_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CLK_DET_FAST_TX_IP_RG_CLK_DET_FAST_TX_IP_LSP  0u
#define DVA_CLK_DET_FAST_TX_IP_RG_CLK_DET_FAST_TX_IP_LEN  16u
#define DVA_CLK_DET_FAST_TX_IP_RG_CLK_DET_FAST_TX_IP_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_CLK_DET_FAST_TX_IE_RG_CLK_DET_FAST_TX_IE_LSP  0u
#define DVA_CLK_DET_FAST_TX_IE_RG_CLK_DET_FAST_TX_IE_LEN  16u
#define DVA_CLK_DET_FAST_TX_IE_RG_CLK_DET_FAST_TX_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CLK_DET_DEAD_TX_IP_RG_CLK_DET_DEAD_TX_IP_LSP  0u
#define DVA_CLK_DET_DEAD_TX_IP_RG_CLK_DET_DEAD_TX_IP_LEN  16u
#define DVA_CLK_DET_DEAD_TX_IP_RG_CLK_DET_DEAD_TX_IP_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_CLK_DET_DEAD_TX_IE_RG_CLK_DET_DEAD_TX_IE_LSP  0u
#define DVA_CLK_DET_DEAD_TX_IE_RG_CLK_DET_DEAD_TX_IE_LEN  16u
#define DVA_CLK_DET_DEAD_TX_IE_RG_CLK_DET_DEAD_TX_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CLK_DET_SYS_IP_RG_CLK_DET_SYS_IP_LSP  0u
#define DVA_CLK_DET_SYS_IP_RG_CLK_DET_SYS_IP_LEN  3u
#define DVA_CLK_DET_SYS_IP_RG_CLK_DET_SYS_IP_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_CLK_DET_SYS_IE_RG_CLK_DET_SYS_IE_LSP  0u
#define DVA_CLK_DET_SYS_IE_RG_CLK_DET_SYS_IE_LEN  3u
#define DVA_CLK_DET_SYS_IE_RG_CLK_DET_SYS_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_TCAM_ERR_IP_RG_TCAM_ERR_IP_LSP  0u
#define DVA_TCAM_ERR_IP_RG_TCAM_ERR_IP_LEN  7u
#define DVA_TCAM_ERR_IP_RG_TCAM_ERR_IP_TYPE DVA_FIELD_TYPE_RO

#define DVA_TCAM_ERR_IE_RG_TCAM_ERR_IE_LSP  0u
#define DVA_TCAM_ERR_IE_RG_TCAM_ERR_IE_LEN  7u
#define DVA_TCAM_ERR_IE_RG_TCAM_ERR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_TCAM_ERR_ACL_IP_RG_TCAM_ERR_ACL_IP_LSP  0u
#define DVA_TCAM_ERR_ACL_IP_RG_TCAM_ERR_ACL_IP_LEN  18u
#define DVA_TCAM_ERR_ACL_IP_RG_TCAM_ERR_ACL_IP_TYPE DVA_FIELD_TYPE_RO

#define DVA_TCAM_ERR_ACL_IE_RG_TCAM_ERR_ACL_IE_LSP  0u
#define DVA_TCAM_ERR_ACL_IE_RG_TCAM_ERR_ACL_IE_LEN  18u
#define DVA_TCAM_ERR_ACL_IE_RG_TCAM_ERR_ACL_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_TCAM_ERR_CB_IP_RG_TCAM_ERR_CB_IP_LSP  0u
#define DVA_TCAM_ERR_CB_IP_RG_TCAM_ERR_CB_IP_LEN  4u
#define DVA_TCAM_ERR_CB_IP_RG_TCAM_ERR_CB_IP_TYPE DVA_FIELD_TYPE_RO

#define DVA_TCAM_ERR_CB_IE_RG_TCAM_ERR_CB_IE_LSP  0u
#define DVA_TCAM_ERR_CB_IE_RG_TCAM_ERR_CB_IE_LEN  4u
#define DVA_TCAM_ERR_CB_IE_RG_TCAM_ERR_CB_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_TCAM_ERR_ROUTE_IP_RG_TCAM_ERR_ROUTE_IP_LSP  0u
#define DVA_TCAM_ERR_ROUTE_IP_RG_TCAM_ERR_ROUTE_IP_LEN  8u
#define DVA_TCAM_ERR_ROUTE_IP_RG_TCAM_ERR_ROUTE_IP_TYPE DVA_FIELD_TYPE_RO

#define DVA_TCAM_ERR_ROUTE_IE_RG_TCAM_ERR_ROUTE_IE_LSP  0u
#define DVA_TCAM_ERR_ROUTE_IE_RG_TCAM_ERR_ROUTE_IE_LEN  8u
#define DVA_TCAM_ERR_ROUTE_IE_RG_TCAM_ERR_ROUTE_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT0_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT1_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT2_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT3_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT4_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT5_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT6_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT7_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT8_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT9_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT10_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT11_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT12_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT13_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT14_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LSP          31u
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_LEN          1u
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_MONITOR_TESTMODE_EN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LSP  3u
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_ACTIVE_TX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LSP  2u
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_LEN  1u
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_ACTIVE_RX_STATUS_TO_MONITOR_TYPE DVA_FIELD_TYPE_RO
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LSP                1u
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_LEN                1u
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_MONITOR_TX_EN_TYPE               DVA_FIELD_TYPE_RW
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LSP                0u
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_LEN                1u
#define DVA_PORT15_DISB_MONITOR_CONTROL_DISB_MONITOR_RX_EN_TYPE               DVA_FIELD_TYPE_RW

#define DVA_PORT0_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LSP  0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_LEN  1u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_SAFETY_FUSA_PG_LOCK_DMY_SAFETY_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_SAFETY_H_ */