/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_INTERRUPT_TOP_H_
#define DVA_RTKAS_REG_FIELD_FILE_INTERRUPT_TOP_H_

#ifdef DVA_FILE_INTERRUPT_TOP
/* File: Interrupt Top */
#define DVA_RG_INTERRUPT_TOP_VERSION_RG_INTERRUPT_TOP_VERSION_LSP  0u
#define DVA_RG_INTERRUPT_TOP_VERSION_RG_INTERRUPT_TOP_VERSION_LEN  32u
#define DVA_RG_INTERRUPT_TOP_VERSION_RG_INTERRUPT_TOP_VERSION_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_NUM_LSP              7u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_NUM_LEN              8u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_NUM_TYPE             DVA_FIELD_TYPE_RW
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IP_LSP           6u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IP_LEN           1u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IP_TYPE          DVA_FIELD_TYPE_RWS
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IE_LSP           5u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IE_LEN           1u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IE_TYPE          DVA_FIELD_TYPE_RW
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_TRIG_LSP             4u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_TRIG_LEN             1u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_TRIG_TYPE            DVA_FIELD_TYPE_RWS
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_SW_INT_PULSE_INTERVAL_LSP           2u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_SW_INT_PULSE_INTERVAL_LEN           2u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_SW_INT_PULSE_INTERVAL_TYPE          DVA_FIELD_TYPE_RW
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_RG_INTERRUPT_TOP_EXT_INTR_MODE_LSP  0u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_RG_INTERRUPT_TOP_EXT_INTR_MODE_LEN  2u
#define DVA_RG_INTERRUPT_TOP_EXT_INTR_MODE_RG_INTERRUPT_TOP_EXT_INTR_MODE_TYPE DVA_FIELD_TYPE_RWS

#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP0_RG_INTERRUPT_TOP_INT_IE_GRP0_LSP  0u
#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP0_RG_INTERRUPT_TOP_INT_IE_GRP0_LEN  32u
#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP0_RG_INTERRUPT_TOP_INT_IE_GRP0_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP1_RG_INTERRUPT_TOP_INT_IE_GRP1_LSP  0u
#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP1_RG_INTERRUPT_TOP_INT_IE_GRP1_LEN  32u
#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP1_RG_INTERRUPT_TOP_INT_IE_GRP1_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP2_RG_INTERRUPT_TOP_INT_IE_GRP2_LSP  0u
#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP2_RG_INTERRUPT_TOP_INT_IE_GRP2_LEN  32u
#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP2_RG_INTERRUPT_TOP_INT_IE_GRP2_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP3_RG_INTERRUPT_TOP_INT_IE_GRP3_LSP  0u
#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP3_RG_INTERRUPT_TOP_INT_IE_GRP3_LEN  32u
#define DVA_RG_INTERRUPT_TOP_INT_IE_GRP3_RG_INTERRUPT_TOP_INT_IE_GRP3_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP0_RG_INTERRUPT_TOP_INT_IP_GRP0_LSP  0u
#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP0_RG_INTERRUPT_TOP_INT_IP_GRP0_LEN  32u
#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP0_RG_INTERRUPT_TOP_INT_IP_GRP0_TYPE DVA_FIELD_TYPE_RO

#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP1_RG_INTERRUPT_TOP_INT_IP_GRP1_LSP  0u
#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP1_RG_INTERRUPT_TOP_INT_IP_GRP1_LEN  32u
#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP1_RG_INTERRUPT_TOP_INT_IP_GRP1_TYPE DVA_FIELD_TYPE_RO

#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP2_RG_INTERRUPT_TOP_INT_IP_GRP2_LSP  0u
#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP2_RG_INTERRUPT_TOP_INT_IP_GRP2_LEN  32u
#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP2_RG_INTERRUPT_TOP_INT_IP_GRP2_TYPE DVA_FIELD_TYPE_RO

#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP3_RG_INTERRUPT_TOP_INT_IP_GRP3_LSP  0u
#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP3_RG_INTERRUPT_TOP_INT_IP_GRP3_LEN  32u
#define DVA_RG_INTERRUPT_TOP_INT_IP_GRP3_RG_INTERRUPT_TOP_INT_IP_GRP3_TYPE DVA_FIELD_TYPE_RO

#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP0_RG_INTERRUPT_TOP_EXT_IE_GRP0_LSP  0u
#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP0_RG_INTERRUPT_TOP_EXT_IE_GRP0_LEN  32u
#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP0_RG_INTERRUPT_TOP_EXT_IE_GRP0_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP1_RG_INTERRUPT_TOP_EXT_IE_GRP1_LSP  0u
#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP1_RG_INTERRUPT_TOP_EXT_IE_GRP1_LEN  32u
#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP1_RG_INTERRUPT_TOP_EXT_IE_GRP1_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP2_RG_INTERRUPT_TOP_EXT_IE_GRP2_LSP  0u
#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP2_RG_INTERRUPT_TOP_EXT_IE_GRP2_LEN  32u
#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP2_RG_INTERRUPT_TOP_EXT_IE_GRP2_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP3_RG_INTERRUPT_TOP_EXT_IE_GRP3_LSP  0u
#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP3_RG_INTERRUPT_TOP_EXT_IE_GRP3_LEN  32u
#define DVA_RG_INTERRUPT_TOP_EXT_IE_GRP3_RG_INTERRUPT_TOP_EXT_IE_GRP3_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP0_RG_INTERRUPT_TOP_EXT_IP_GRP0_LSP  0u
#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP0_RG_INTERRUPT_TOP_EXT_IP_GRP0_LEN  32u
#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP0_RG_INTERRUPT_TOP_EXT_IP_GRP0_TYPE DVA_FIELD_TYPE_RO

#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP1_RG_INTERRUPT_TOP_EXT_IP_GRP1_LSP  0u
#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP1_RG_INTERRUPT_TOP_EXT_IP_GRP1_LEN  32u
#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP1_RG_INTERRUPT_TOP_EXT_IP_GRP1_TYPE DVA_FIELD_TYPE_RO

#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP2_RG_INTERRUPT_TOP_EXT_IP_GRP2_LSP  0u
#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP2_RG_INTERRUPT_TOP_EXT_IP_GRP2_LEN  32u
#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP2_RG_INTERRUPT_TOP_EXT_IP_GRP2_TYPE DVA_FIELD_TYPE_RO

#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP3_RG_INTERRUPT_TOP_EXT_IP_GRP3_LSP  0u
#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP3_RG_INTERRUPT_TOP_EXT_IP_GRP3_LEN  32u
#define DVA_RG_INTERRUPT_TOP_EXT_IP_GRP3_RG_INTERRUPT_TOP_EXT_IP_GRP3_TYPE DVA_FIELD_TYPE_RO

#define DVA_RG_INTERRUPT_TOP_POL_GRP0_RG_INTERRUPT_TOP_POL_GRP0_LSP  0u
#define DVA_RG_INTERRUPT_TOP_POL_GRP0_RG_INTERRUPT_TOP_POL_GRP0_LEN  32u
#define DVA_RG_INTERRUPT_TOP_POL_GRP0_RG_INTERRUPT_TOP_POL_GRP0_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_POL_GRP1_RG_INTERRUPT_TOP_POL_GRP1_LSP  0u
#define DVA_RG_INTERRUPT_TOP_POL_GRP1_RG_INTERRUPT_TOP_POL_GRP1_LEN  32u
#define DVA_RG_INTERRUPT_TOP_POL_GRP1_RG_INTERRUPT_TOP_POL_GRP1_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_POL_GRP2_RG_INTERRUPT_TOP_POL_GRP2_LSP  0u
#define DVA_RG_INTERRUPT_TOP_POL_GRP2_RG_INTERRUPT_TOP_POL_GRP2_LEN  32u
#define DVA_RG_INTERRUPT_TOP_POL_GRP2_RG_INTERRUPT_TOP_POL_GRP2_TYPE DVA_FIELD_TYPE_RW

#define DVA_RG_INTERRUPT_TOP_POL_GRP3_RG_INTERRUPT_TOP_POL_GRP3_LSP  0u
#define DVA_RG_INTERRUPT_TOP_POL_GRP3_RG_INTERRUPT_TOP_POL_GRP3_LEN  32u
#define DVA_RG_INTERRUPT_TOP_POL_GRP3_RG_INTERRUPT_TOP_POL_GRP3_TYPE DVA_FIELD_TYPE_RW

#define DVA_FUSA_PG_LOCK_DMY_INTERRUPT_TOP_FUSA_PG_LOCK_DMY_INTERRUPT_TOP_LSP  0u
#define DVA_FUSA_PG_LOCK_DMY_INTERRUPT_TOP_FUSA_PG_LOCK_DMY_INTERRUPT_TOP_LEN  1u
#define DVA_FUSA_PG_LOCK_DMY_INTERRUPT_TOP_FUSA_PG_LOCK_DMY_INTERRUPT_TOP_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_INTERRUPT_TOP_H_ */