/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_CPU_AUX_SYS_H_
#define DVA_RTKAS_REG_FIELD_FILE_CPU_AUX_SYS_H_

#ifdef DVA_FILE_CPU_AUX_SYS
/* File: cpu_aux_sys */
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_CORERESET0_LSP    21u
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_CORERESET0_LEN    1u
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_CORERESET0_TYPE   DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_CPUPORESET0_LSP   20u
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_CPUPORESET0_LEN   1u
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_CPUPORESET0_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_SYSMEMCRESET_LSP  18u
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_SYSMEMCRESET_LEN  1u
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_SYSMEMCRESET_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_TOPRESET_LSP      16u
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_TOPRESET_LEN      1u
#define DVA_INTERNAL_CPU_RESET_REQUEST_MANUAL_TOPRESET_TYPE     DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_RESET_REQUEST_CORERESET0_LSP           5u
#define DVA_INTERNAL_CPU_RESET_REQUEST_CORERESET0_LEN           1u
#define DVA_INTERNAL_CPU_RESET_REQUEST_CORERESET0_TYPE          DVA_FIELD_TYPE_RWS
#define DVA_INTERNAL_CPU_RESET_REQUEST_CPUPORESET0_LSP          4u
#define DVA_INTERNAL_CPU_RESET_REQUEST_CPUPORESET0_LEN          1u
#define DVA_INTERNAL_CPU_RESET_REQUEST_CPUPORESET0_TYPE         DVA_FIELD_TYPE_RWS
#define DVA_INTERNAL_CPU_RESET_REQUEST_SYSMEMCRESET_LSP         2u
#define DVA_INTERNAL_CPU_RESET_REQUEST_SYSMEMCRESET_LEN         1u
#define DVA_INTERNAL_CPU_RESET_REQUEST_SYSMEMCRESET_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_INTERNAL_CPU_RESET_REQUEST_RESETSOCDBG_LSP          1u
#define DVA_INTERNAL_CPU_RESET_REQUEST_RESETSOCDBG_LEN          1u
#define DVA_INTERNAL_CPU_RESET_REQUEST_RESETSOCDBG_TYPE         DVA_FIELD_TYPE_RWS
#define DVA_INTERNAL_CPU_RESET_REQUEST_TOPRESET_LSP             0u
#define DVA_INTERNAL_CPU_RESET_REQUEST_TOPRESET_LEN             1u
#define DVA_INTERNAL_CPU_RESET_REQUEST_TOPRESET_TYPE            DVA_FIELD_TYPE_RWS

#define DVA_INTERNAL_CPU_GLOBAL_STATUS_CPU_RESET_HS_FSM_LSP   4u
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_CPU_RESET_HS_FSM_LEN   2u
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_CPU_RESET_HS_FSM_TYPE  DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_STATUS_JTAGTOP_LSP     2u
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_STATUS_JTAGTOP_LEN     1u
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_STATUS_JTAGTOP_TYPE    DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_STATUS_JTAGNSW_LSP     1u
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_STATUS_JTAGNSW_LEN     1u
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_STATUS_JTAGNSW_TYPE    DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_SYS_MEM_INIT_DONE_LSP  0u
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_SYS_MEM_INIT_DONE_LEN  1u
#define DVA_INTERNAL_CPU_GLOBAL_STATUS_SYS_MEM_INIT_DONE_TYPE DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_PREFETCH_DIS_LSP              31u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_PREFETCH_DIS_LEN              1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_PREFETCH_DIS_TYPE             DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_TRCCK_EN_LSP                  30u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_TRCCK_EN_LEN                  1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_TRCCK_EN_TYPE                 DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_TRCCK_DIVF_LSP                24u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_TRCCK_DIVF_LEN                6u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_TRCCK_DIVF_TYPE               DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_TSCK_DIVF_LSP                 16u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_TSCK_DIVF_LEN                 6u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_TSCK_DIVF_TYPE                DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_ATCM_REMAP_EN_LSP             11u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_ATCM_REMAP_EN_LEN             1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_ATCM_REMAP_EN_TYPE            DVA_FIELD_TYPE_RWS
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_RESET_WAIT_WFI_LSP            10u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_RESET_WAIT_WFI_LEN            1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_RESET_WAIT_WFI_TYPE           DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_PLL_CLK_DIS_LSP               9u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_PLL_CLK_DIS_LEN               1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_PLL_CLK_DIS_TYPE              DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_EXT_CLK_SEL_LSP               8u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_EXT_CLK_SEL_LEN               1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_EXT_CLK_SEL_TYPE              DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_SYS_MEM_BYPASS_AUTO_INIT_LSP  7u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_SYS_MEM_BYPASS_AUTO_INIT_LEN  1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_SYS_MEM_BYPASS_AUTO_INIT_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_SYS_MEM_ECC_CHK_EN_LSP        6u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_SYS_MEM_ECC_CHK_EN_LEN        1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_SYS_MEM_ECC_CHK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_BTCM_REMAP_EN_LSP             5u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_BTCM_REMAP_EN_LEN             1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_BTCM_REMAP_EN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_NIDEN_LSP                     4u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_NIDEN_LEN                     1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_NIDEN_TYPE                    DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_DBGEN_LSP                     3u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_DBGEN_LEN                     1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_DBGEN_TYPE                    DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_CFGRAMPROTEN_LSP              2u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_CFGRAMPROTEN_LEN              1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_CFGRAMPROTEN_TYPE             DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_CFGMRPEN_LSP                  1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_CFGMRPEN_LEN                  1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_CFGMRPEN_TYPE                 DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_CFGINITREG_LSP                0u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_CFGINITREG_LEN                1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_0_CFGINITREG_TYPE               DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_GLOBAL_CTRL_1_CFGAXISTCMBASEADDR_LSP  24u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_1_CFGAXISTCMBASEADDR_LEN  8u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_1_CFGAXISTCMBASEADDR_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_1_DCLSCOMPIN_GLOBAL_LSP   0u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_1_DCLSCOMPIN_GLOBAL_LEN   4u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_1_DCLSCOMPIN_GLOBAL_TYPE  DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_GLOBAL_CTRL_2_CFGLLPPBASEADDR_LSP  12u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_2_CFGLLPPBASEADDR_LEN  20u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_2_CFGLLPPBASEADDR_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_2_CFGLLPPSIZE_LSP      4u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_2_CFGLLPPSIZE_LEN      4u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_2_CFGLLPPSIZE_TYPE     DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_2_CFGLLPPIMP_LSP       0u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_2_CFGLLPPIMP_LEN       1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_2_CFGLLPPIMP_TYPE      DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHBASEADDR_LSP  27u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHBASEADDR_LEN  5u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHBASEADDR_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHPROTEN_LSP    2u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHPROTEN_LEN    1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHPROTEN_TYPE   DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHPROTIMP_LSP   1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHPROTIMP_LEN   1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHPROTIMP_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHIMP_LSP       0u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHIMP_LEN       1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_3_CFGFLASHIMP_TYPE      DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGPERIPHBASE_LSP   21u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGPERIPHBASE_LEN   11u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGPERIPHBASE_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGCLUSTERUTID_LSP  16u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGCLUSTERUTID_LEN  2u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGCLUSTERUTID_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGMPIDRAFF2_LSP    8u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGMPIDRAFF2_LEN    8u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGMPIDRAFF2_TYPE   DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGMPIDRAFF1_LSP    0u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGMPIDRAFF1_LEN    8u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_4_CFGMPIDRAFF1_TYPE   DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_CFGDBGROMADDR_LSP            12u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_CFGDBGROMADDR_LEN            20u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_CFGDBGROMADDR_TYPE           DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_STATICCFG_TPCTL_LSP          10u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_STATICCFG_TPCTL_LEN          1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_STATICCFG_TPCTL_TYPE         DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_STATICCFG_TPMAXDATASIZE_LSP  4u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_STATICCFG_TPMAXDATASIZE_LEN  5u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_STATICCFG_TPMAXDATASIZE_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_EVENTI_LSP                   3u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_EVENTI_LEN                   1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_EVENTI_TYPE                  DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_PMC_TC_LSP                   2u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_PMC_TC_LEN                   1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_PMC_TC_TYPE                  DVA_FIELD_TYPE_RWS
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_PMC_TEN_LSP                  1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_PMC_TEN_LEN                  1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_PMC_TEN_TYPE                 DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_CFGDBGROMADDRV_LSP           0u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_CFGDBGROMADDRV_LEN           1u
#define DVA_INTERNAL_CPU_GLOBAL_CTRL_5_CFGDBGROMADDRV_TYPE          DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_GLOBAL_ERROR_ISR_DCLSCOMP_ERR_ISR_LSP        31u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_ISR_DCLSCOMP_ERR_ISR_LEN        1u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_ISR_DCLSCOMP_ERR_ISR_TYPE       DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_ISR_DCLSCOMPOUT_GLOBAL_ISR_LSP  16u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_ISR_DCLSCOMPOUT_GLOBAL_ISR_LEN  4u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_ISR_DCLSCOMPOUT_GLOBAL_ISR_TYPE DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_ISR_ERREVENT_GLOBAL_ISR_LSP     0u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_ISR_ERREVENT_GLOBAL_ISR_LEN     5u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_ISR_ERREVENT_GLOBAL_ISR_TYPE    DVA_FIELD_TYPE_RW1C

#define DVA_INTERNAL_CPU_GLOBAL_ERROR_IMR_DCLSCOMP_ERR_IMR_LSP        31u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_IMR_DCLSCOMP_ERR_IMR_LEN        1u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_IMR_DCLSCOMP_ERR_IMR_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_IMR_DCLSCOMPOUT_GLOBAL_IMR_LSP  16u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_IMR_DCLSCOMPOUT_GLOBAL_IMR_LEN  4u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_IMR_DCLSCOMPOUT_GLOBAL_IMR_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_IMR_ERREVENT_GLOBAL_IMR_LSP     0u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_IMR_ERREVENT_GLOBAL_IMR_LEN     5u
#define DVA_INTERNAL_CPU_GLOBAL_ERROR_IMR_ERREVENT_GLOBAL_IMR_TYPE    DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_CORE0_CTRL_0_DCLSCOMPIN_CORE0_LSP     16u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_DCLSCOMPIN_CORE0_LEN     14u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_DCLSCOMPIN_CORE0_TYPE    DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGL1CACHEINVDIS0_LSP    7u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGL1CACHEINVDIS0_LEN    1u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGL1CACHEINVDIS0_TYPE   DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CPUHALT0_LSP             6u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CPUHALT0_LEN             1u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CPUHALT0_TYPE            DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_HNIDEN0_LSP              5u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_HNIDEN0_LEN              1u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_HNIDEN0_TYPE             DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_HIDEN0_LSP               4u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_HIDEN0_LEN               1u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_HIDEN0_TYPE              DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGFLASHEN0_LSP          3u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGFLASHEN0_LEN          1u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGFLASHEN0_TYPE         DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGTCMBOOT0_LSP          2u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGTCMBOOT0_LEN          1u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGTCMBOOT0_TYPE         DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGTHUMBEXCEPTIONS0_LSP  1u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGTHUMBEXCEPTIONS0_LEN  1u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGTHUMBEXCEPTIONS0_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGENDIANESS0_LSP        0u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGENDIANESS0_LEN        1u
#define DVA_INTERNAL_CPU_CORE0_CTRL_0_CFGENDIANESS0_TYPE       DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_CORE0_CTRL_1_CFGVECTABLE0_LSP  5u
#define DVA_INTERNAL_CPU_CORE0_CTRL_1_CFGVECTABLE0_LEN  27u
#define DVA_INTERNAL_CPU_CORE0_CTRL_1_CFGVECTABLE0_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_CORE0_MEMERRMEM_SECMEMERRMEM0_LSP  16u
#define DVA_INTERNAL_CPU_CORE0_MEMERRMEM_SECMEMERRMEM0_LEN  15u
#define DVA_INTERNAL_CPU_CORE0_MEMERRMEM_SECMEMERRMEM0_TYPE DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_CORE0_MEMERRMEM_PRIMEMERRMEM0_LSP  0u
#define DVA_INTERNAL_CPU_CORE0_MEMERRMEM_PRIMEMERRMEM0_LEN  15u
#define DVA_INTERNAL_CPU_CORE0_MEMERRMEM_PRIMEMERRMEM0_TYPE DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_CORE0_PRIMEMERRIDX_PRIMEMERRIDX0_LSP  0u
#define DVA_INTERNAL_CPU_CORE0_PRIMEMERRIDX_PRIMEMERRIDX0_LEN  25u
#define DVA_INTERNAL_CPU_CORE0_PRIMEMERRIDX_PRIMEMERRIDX0_TYPE DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_CORE0_SECMEMERRIDX_SECMEMERRIDX0_LSP  0u
#define DVA_INTERNAL_CPU_CORE0_SECMEMERRIDX_SECMEMERRIDX0_LEN  25u
#define DVA_INTERNAL_CPU_CORE0_SECMEMERRIDX_SECMEMERRIDX0_TYPE DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_CORE0_STATUS_SECMEMERRV0_LSP  3u
#define DVA_INTERNAL_CPU_CORE0_STATUS_SECMEMERRV0_LEN  1u
#define DVA_INTERNAL_CPU_CORE0_STATUS_SECMEMERRV0_TYPE DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_CORE0_STATUS_PRIMEMERRV0_LSP  2u
#define DVA_INTERNAL_CPU_CORE0_STATUS_PRIMEMERRV0_LEN  1u
#define DVA_INTERNAL_CPU_CORE0_STATUS_PRIMEMERRV0_TYPE DVA_FIELD_TYPE_RW1C
#define DVA_INTERNAL_CPU_CORE0_STATUS_STANDBYWFE0_LSP  1u
#define DVA_INTERNAL_CPU_CORE0_STATUS_STANDBYWFE0_LEN  1u
#define DVA_INTERNAL_CPU_CORE0_STATUS_STANDBYWFE0_TYPE DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_CORE0_STATUS_STANDBYWFI0_LSP  0u
#define DVA_INTERNAL_CPU_CORE0_STATUS_STANDBYWFI0_LEN  1u
#define DVA_INTERNAL_CPU_CORE0_STATUS_STANDBYWFI0_TYPE DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_CORE_0_ERROR_ISR_0_ERREVENT_CORE0_ISR_LSP  0u
#define DVA_INTERNAL_CPU_CORE_0_ERROR_ISR_0_ERREVENT_CORE0_ISR_LEN  26u
#define DVA_INTERNAL_CPU_CORE_0_ERROR_ISR_0_ERREVENT_CORE0_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_INTERNAL_CPU_CORE_0_ERROR_IMR_0_ERREVENT_CORE0_IMR_LSP  0u
#define DVA_INTERNAL_CPU_CORE_0_ERROR_IMR_0_ERREVENT_CORE0_IMR_LEN  26u
#define DVA_INTERNAL_CPU_CORE_0_ERROR_IMR_0_ERREVENT_CORE0_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_CORE_0_ERROR_ISR_1_DCLSCOMPOUT_CORE0_ISR_LSP  0u
#define DVA_INTERNAL_CPU_CORE_0_ERROR_ISR_1_DCLSCOMPOUT_CORE0_ISR_LEN  14u
#define DVA_INTERNAL_CPU_CORE_0_ERROR_ISR_1_DCLSCOMPOUT_CORE0_ISR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_INTERNAL_CPU_CORE_0_ERROR_IMR_1_DCLSCOMPOUT_CORE0_IMR_LSP  0u
#define DVA_INTERNAL_CPU_CORE_0_ERROR_IMR_1_DCLSCOMPOUT_CORE0_IMR_LEN  14u
#define DVA_INTERNAL_CPU_CORE_0_ERROR_IMR_1_DCLSCOMPOUT_CORE0_IMR_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_SRAM_CTRL_DONE_LSP  31u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_SRAM_CTRL_DONE_LEN  1u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_SRAM_CTRL_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_SEL_LSP             28u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_SEL_LEN             1u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_SEL_TYPE            DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_RECORDER_EN_LSP     27u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_RECORDER_EN_LEN     1u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_RECORDER_EN_TYPE    DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_FSSCTRL_RST_N_LSP               26u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_FSSCTRL_RST_N_LEN               1u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_FSSCTRL_RST_N_TYPE              DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_EXT_READ_PULSE_LSP  25u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_EXT_READ_PULSE_LEN  1u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_EXT_READ_PULSE_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_EXT_READ_READY_LSP  24u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_EXT_READ_READY_LEN  1u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_EXT_READ_READY_TYPE DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_EXT_READ_DATA_LSP   0u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_EXT_READ_DATA_LEN   20u
#define DVA_INTERNAL_CPU_FSS_RECORDER_CTRL_HPC_FSSCTRL_EXT_READ_DATA_TYPE  DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_FSS0_CTRL_0_FSSREC_FIFO_RRST_N_C0_LSP            30u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_FSSREC_FIFO_RRST_N_C0_LEN            1u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_FSSREC_FIFO_RRST_N_C0_TYPE           DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_FSSREC_RST_N_C0_LSP                  29u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_FSSREC_RST_N_C0_LEN                  1u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_FSSREC_RST_N_C0_TYPE                 DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_FSS_RST_N_C0_LSP                     28u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_FSS_RST_N_C0_LEN                     1u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_FSS_RST_N_C0_TYPE                    DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSSREC_RECORDER_INTERVAL_C0_LSP  20u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSSREC_RECORDER_INTERVAL_C0_LEN  6u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSSREC_RECORDER_INTERVAL_C0_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSSREC_USER_DETECT_C0_LSP        17u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSSREC_USER_DETECT_C0_LEN        1u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSSREC_USER_DETECT_C0_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSSREC_RECORDER_EN_C0_LSP        16u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSSREC_RECORDER_EN_C0_LEN        1u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSSREC_RECORDER_EN_C0_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_CONFIG_CDL0_C0_LSP           8u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_CONFIG_CDL0_C0_LEN           4u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_CONFIG_CDL0_C0_TYPE          DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_FALL_EDGE_SEL_C0_LSP         4u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_FALL_EDGE_SEL_C0_LEN         1u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_FALL_EDGE_SEL_C0_TYPE        DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_PATH_SEL_C0_LSP              2u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_PATH_SEL_C0_LEN              2u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_PATH_SEL_C0_TYPE             DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_CAL_EN_C0_LSP                1u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_CAL_EN_C0_LEN                1u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_CAL_EN_C0_TYPE               DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_SENSOR_EN_C0_LSP             0u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_SENSOR_EN_C0_LEN             1u
#define DVA_INTERNAL_CPU_FSS0_CTRL_0_HPC_FSS_SENSOR_EN_C0_TYPE            DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG2_CDL2_C0_LSP  24u
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG2_CDL2_C0_LEN  5u
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG2_CDL2_C0_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG2_CDL1_C0_LSP  16u
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG2_CDL1_C0_LEN  5u
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG2_CDL1_C0_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG1_CDL2_C0_LSP  8u
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG1_CDL2_C0_LEN  5u
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG1_CDL2_C0_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG1_CDL1_C0_LSP  0u
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG1_CDL1_C0_LEN  5u
#define DVA_INTERNAL_CPU_FSS0_CTRL_1_HPC_FSS_CONFIG1_CDL1_C0_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_CAL_DONE_C0_LSP      31u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_CAL_DONE_C0_LEN      1u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_CAL_DONE_C0_TYPE     DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_CAL_MIN_CDL1_C0_LSP  24u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_CAL_MIN_CDL1_C0_LEN  5u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_CAL_MIN_CDL1_C0_TYPE DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_CAL_CDL0_C0_LSP      16u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_CAL_CDL0_C0_LEN      4u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_CAL_CDL0_C0_TYPE     DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT2_OUT_C0_LSP   6u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT2_OUT_C0_LEN   1u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT2_OUT_C0_TYPE  DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT2_2_C0_LSP     5u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT2_2_C0_LEN     1u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT2_2_C0_TYPE    DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT2_1_C0_LSP     4u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT2_1_C0_LEN     1u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT2_1_C0_TYPE    DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT1_OUT_C0_LSP   2u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT1_OUT_C0_LEN   1u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT1_OUT_C0_TYPE  DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT1_2_C0_LSP     1u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT1_2_C0_LEN     1u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT1_2_C0_TYPE    DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT1_1_C0_LSP     0u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT1_1_C0_LEN     1u
#define DVA_INTERNAL_CPU_FSS0_STATUS_HPC_FSS_DETECT1_1_C0_TYPE    DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_FSS1_CTRL_0_FSSREC_FIFO_RRST_N_C1_LSP            30u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_FSSREC_FIFO_RRST_N_C1_LEN            1u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_FSSREC_FIFO_RRST_N_C1_TYPE           DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_FSSREC_RST_N_C1_LSP                  29u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_FSSREC_RST_N_C1_LEN                  1u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_FSSREC_RST_N_C1_TYPE                 DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_FSS_RST_N_C1_LSP                     28u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_FSS_RST_N_C1_LEN                     1u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_FSS_RST_N_C1_TYPE                    DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSSREC_RECORDER_INTERVAL_C1_LSP  20u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSSREC_RECORDER_INTERVAL_C1_LEN  6u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSSREC_RECORDER_INTERVAL_C1_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSSREC_USER_DETECT_C1_LSP        17u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSSREC_USER_DETECT_C1_LEN        1u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSSREC_USER_DETECT_C1_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSSREC_RECORDER_EN_C1_LSP        16u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSSREC_RECORDER_EN_C1_LEN        1u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSSREC_RECORDER_EN_C1_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_CONFIG_CDL0_C1_LSP           8u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_CONFIG_CDL0_C1_LEN           4u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_CONFIG_CDL0_C1_TYPE          DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_FALL_EDGE_SEL_C1_LSP         4u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_FALL_EDGE_SEL_C1_LEN         1u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_FALL_EDGE_SEL_C1_TYPE        DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_PATH_SEL_C1_LSP              2u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_PATH_SEL_C1_LEN              2u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_PATH_SEL_C1_TYPE             DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_CAL_EN_C1_LSP                1u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_CAL_EN_C1_LEN                1u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_CAL_EN_C1_TYPE               DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_SENSOR_EN_C1_LSP             0u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_SENSOR_EN_C1_LEN             1u
#define DVA_INTERNAL_CPU_FSS1_CTRL_0_HPC_FSS_SENSOR_EN_C1_TYPE            DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG2_CDL2_C1_LSP  24u
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG2_CDL2_C1_LEN  5u
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG2_CDL2_C1_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG2_CDL1_C1_LSP  16u
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG2_CDL1_C1_LEN  5u
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG2_CDL1_C1_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG1_CDL2_C1_LSP  8u
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG1_CDL2_C1_LEN  5u
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG1_CDL2_C1_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG1_CDL1_C1_LSP  0u
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG1_CDL1_C1_LEN  5u
#define DVA_INTERNAL_CPU_FSS1_CTRL_1_HPC_FSS_CONFIG1_CDL1_C1_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_CAL_DONE_C1_LSP      31u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_CAL_DONE_C1_LEN      1u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_CAL_DONE_C1_TYPE     DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_CAL_MIN_CDL1_C1_LSP  24u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_CAL_MIN_CDL1_C1_LEN  5u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_CAL_MIN_CDL1_C1_TYPE DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_CAL_CDL0_C1_LSP      16u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_CAL_CDL0_C1_LEN      4u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_CAL_CDL0_C1_TYPE     DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT2_OUT_C1_LSP   6u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT2_OUT_C1_LEN   1u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT2_OUT_C1_TYPE  DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT2_2_C1_LSP     5u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT2_2_C1_LEN     1u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT2_2_C1_TYPE    DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT2_1_C1_LSP     4u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT2_1_C1_LEN     1u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT2_1_C1_TYPE    DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT1_OUT_C1_LSP   2u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT1_OUT_C1_LEN   1u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT1_OUT_C1_TYPE  DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT1_2_C1_LSP     1u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT1_2_C1_LEN     1u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT1_2_C1_TYPE    DVA_FIELD_TYPE_RO
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT1_1_C1_LSP     0u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT1_1_C1_LEN     1u
#define DVA_INTERNAL_CPU_FSS1_STATUS_HPC_FSS_DETECT1_1_C1_TYPE    DVA_FIELD_TYPE_RO

#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_STOV_LSP        7u
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_STOV_LEN        1u
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_STOV_TYPE       DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_RET1N_RAM_LSP   6u
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_RET1N_RAM_LEN   1u
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_RET1N_RAM_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_EMAS_DDATA_LSP  5u
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_EMAS_DDATA_LEN  1u
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_EMAS_DDATA_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_EMAW_DDATA_LSP  3u
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_EMAW_DDATA_LEN  2u
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_EMAW_DDATA_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_EMA_DDATA_LSP   0u
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_EMA_DDATA_LEN   3u
#define DVA_INTERNAL_CPU_SRAM_MODE_0_HPC_EMA_DDATA_TYPE  DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SRAM_MODE_1_HPC_EMAS_DTAG_LSP  5u
#define DVA_INTERNAL_CPU_SRAM_MODE_1_HPC_EMAS_DTAG_LEN  1u
#define DVA_INTERNAL_CPU_SRAM_MODE_1_HPC_EMAS_DTAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_1_HPC_EMAW_DTAG_LSP  3u
#define DVA_INTERNAL_CPU_SRAM_MODE_1_HPC_EMAW_DTAG_LEN  2u
#define DVA_INTERNAL_CPU_SRAM_MODE_1_HPC_EMAW_DTAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_1_HPC_EMA_DTAG_LSP   0u
#define DVA_INTERNAL_CPU_SRAM_MODE_1_HPC_EMA_DTAG_LEN   3u
#define DVA_INTERNAL_CPU_SRAM_MODE_1_HPC_EMA_DTAG_TYPE  DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SRAM_MODE_2_HPC_EMAS_IDATA_LSP  5u
#define DVA_INTERNAL_CPU_SRAM_MODE_2_HPC_EMAS_IDATA_LEN  1u
#define DVA_INTERNAL_CPU_SRAM_MODE_2_HPC_EMAS_IDATA_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_2_HPC_EMAW_IDATA_LSP  3u
#define DVA_INTERNAL_CPU_SRAM_MODE_2_HPC_EMAW_IDATA_LEN  2u
#define DVA_INTERNAL_CPU_SRAM_MODE_2_HPC_EMAW_IDATA_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_2_HPC_EMA_IDATA_LSP   0u
#define DVA_INTERNAL_CPU_SRAM_MODE_2_HPC_EMA_IDATA_LEN   3u
#define DVA_INTERNAL_CPU_SRAM_MODE_2_HPC_EMA_IDATA_TYPE  DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SRAM_MODE_3_HPC_EMAS_ITAG_LSP  5u
#define DVA_INTERNAL_CPU_SRAM_MODE_3_HPC_EMAS_ITAG_LEN  1u
#define DVA_INTERNAL_CPU_SRAM_MODE_3_HPC_EMAS_ITAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_3_HPC_EMAW_ITAG_LSP  3u
#define DVA_INTERNAL_CPU_SRAM_MODE_3_HPC_EMAW_ITAG_LEN  2u
#define DVA_INTERNAL_CPU_SRAM_MODE_3_HPC_EMAW_ITAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_3_HPC_EMA_ITAG_LSP   0u
#define DVA_INTERNAL_CPU_SRAM_MODE_3_HPC_EMA_ITAG_LEN   3u
#define DVA_INTERNAL_CPU_SRAM_MODE_3_HPC_EMA_ITAG_TYPE  DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SRAM_MODE_4_HPC_EMAS_BTCM_LSP  5u
#define DVA_INTERNAL_CPU_SRAM_MODE_4_HPC_EMAS_BTCM_LEN  1u
#define DVA_INTERNAL_CPU_SRAM_MODE_4_HPC_EMAS_BTCM_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_4_HPC_EMAW_BTCM_LSP  3u
#define DVA_INTERNAL_CPU_SRAM_MODE_4_HPC_EMAW_BTCM_LEN  2u
#define DVA_INTERNAL_CPU_SRAM_MODE_4_HPC_EMAW_BTCM_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_4_HPC_EMA_BTCM_LSP   0u
#define DVA_INTERNAL_CPU_SRAM_MODE_4_HPC_EMA_BTCM_LEN   3u
#define DVA_INTERNAL_CPU_SRAM_MODE_4_HPC_EMA_BTCM_TYPE  DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SRAM_MODE_5_HPC_EMAS_CTCM_LSP  5u
#define DVA_INTERNAL_CPU_SRAM_MODE_5_HPC_EMAS_CTCM_LEN  1u
#define DVA_INTERNAL_CPU_SRAM_MODE_5_HPC_EMAS_CTCM_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_5_HPC_EMAW_CTCM_LSP  3u
#define DVA_INTERNAL_CPU_SRAM_MODE_5_HPC_EMAW_CTCM_LEN  2u
#define DVA_INTERNAL_CPU_SRAM_MODE_5_HPC_EMAW_CTCM_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_5_HPC_EMA_CTCM_LSP   0u
#define DVA_INTERNAL_CPU_SRAM_MODE_5_HPC_EMA_CTCM_LEN   3u
#define DVA_INTERNAL_CPU_SRAM_MODE_5_HPC_EMA_CTCM_TYPE  DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_RET1N_LSP  6u
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_RET1N_LEN  1u
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_RET1N_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_EMAS_LSP   5u
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_EMAS_LEN   1u
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_EMAS_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_EMAW_LSP   3u
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_EMAW_LEN   2u
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_EMAW_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_EMA_LSP    0u
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_EMA_LEN    3u
#define DVA_INTERNAL_CPU_SRAM_MODE_6_HPC_FSS_EMA_TYPE   DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SRAM_MODE_7_HPC_PGEN_ROM_LSP  4u
#define DVA_INTERNAL_CPU_SRAM_MODE_7_HPC_PGEN_ROM_LEN  1u
#define DVA_INTERNAL_CPU_SRAM_MODE_7_HPC_PGEN_ROM_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_7_HPC_KEN_ATCM_LSP  3u
#define DVA_INTERNAL_CPU_SRAM_MODE_7_HPC_KEN_ATCM_LEN  1u
#define DVA_INTERNAL_CPU_SRAM_MODE_7_HPC_KEN_ATCM_TYPE DVA_FIELD_TYPE_RW
#define DVA_INTERNAL_CPU_SRAM_MODE_7_HPC_EMA_ATCM_LSP  0u
#define DVA_INTERNAL_CPU_SRAM_MODE_7_HPC_EMA_ATCM_LEN  3u
#define DVA_INTERNAL_CPU_SRAM_MODE_7_HPC_EMA_ATCM_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SRAM_MODE_8_MEMORY_MODE_CTRL_SYS_MEM_0_LSP  0u
#define DVA_INTERNAL_CPU_SRAM_MODE_8_MEMORY_MODE_CTRL_SYS_MEM_0_LEN  8u
#define DVA_INTERNAL_CPU_SRAM_MODE_8_MEMORY_MODE_CTRL_SYS_MEM_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_PLATFORM_DEBUG_CTRL_DBG_CTRL_LSP  0u
#define DVA_INTERNAL_CPU_PLATFORM_DEBUG_CTRL_DBG_CTRL_LEN  8u
#define DVA_INTERNAL_CPU_PLATFORM_DEBUG_CTRL_DBG_CTRL_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SPARE_0_SPARE_REG0_LSP  0u
#define DVA_INTERNAL_CPU_SPARE_0_SPARE_REG0_LEN  32u
#define DVA_INTERNAL_CPU_SPARE_0_SPARE_REG0_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SPARE_1_SPARE_REG1_LSP  0u
#define DVA_INTERNAL_CPU_SPARE_1_SPARE_REG1_LEN  32u
#define DVA_INTERNAL_CPU_SPARE_1_SPARE_REG1_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SPARE_2_SPARE_REG2_LSP  0u
#define DVA_INTERNAL_CPU_SPARE_2_SPARE_REG2_LEN  32u
#define DVA_INTERNAL_CPU_SPARE_2_SPARE_REG2_TYPE DVA_FIELD_TYPE_RW

#define DVA_INTERNAL_CPU_SPARE_3_SPARE_REG3_LSP  0u
#define DVA_INTERNAL_CPU_SPARE_3_SPARE_REG3_LEN  32u
#define DVA_INTERNAL_CPU_SPARE_3_SPARE_REG3_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_CPU_AUX_SYS_H_ */