/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_I2C_H_
#define DVA_RTKAS_REG_FIELD_FILE_I2C_H_

#ifdef DVA_FILE_I2C
/* File: I2C */
#define DVA_EXTERNAL_ACCESS_CONTROL_I2C_MODE_LSP             5u
#define DVA_EXTERNAL_ACCESS_CONTROL_I2C_MODE_LEN             1u
#define DVA_EXTERNAL_ACCESS_CONTROL_I2C_MODE_TYPE            DVA_FIELD_TYPE_RW
#define DVA_EXTERNAL_ACCESS_CONTROL_I2C_DEVICE_ADDR_2_0_LSP  2u
#define DVA_EXTERNAL_ACCESS_CONTROL_I2C_DEVICE_ADDR_2_0_LEN  3u
#define DVA_EXTERNAL_ACCESS_CONTROL_I2C_DEVICE_ADDR_2_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_I2C_EXTERNAL_ACCESS_STATUS_I2C_DATALEN_LSP  0u
#define DVA_I2C_EXTERNAL_ACCESS_STATUS_I2C_DATALEN_LEN  22u
#define DVA_I2C_EXTERNAL_ACCESS_STATUS_I2C_DATALEN_TYPE DVA_FIELD_TYPE_RO

#define DVA_I2C_EXTERNAL_ACCESS_ADDRESS_I2C_EAAR_LSP  0u
#define DVA_I2C_EXTERNAL_ACCESS_ADDRESS_I2C_EAAR_LEN  24u
#define DVA_I2C_EXTERNAL_ACCESS_ADDRESS_I2C_EAAR_TYPE DVA_FIELD_TYPE_RO

#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_MAX_PAGE_BYTES_LSP     17u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_MAX_PAGE_BYTES_LEN     1u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_MAX_PAGE_BYTES_TYPE    DVA_FIELD_TYPE_RO
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_FASTEND_LSP            16u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_FASTEND_LEN            1u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_FASTEND_TYPE           DVA_FIELD_TYPE_RO
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_CPUCODE_EXIST_LSP             15u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_CPUCODE_EXIST_LEN             1u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_CPUCODE_EXIST_TYPE            DVA_FIELD_TYPE_RO
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_AUTOLOAD_CONFIGURE_EXIST_LSP  14u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_AUTOLOAD_CONFIGURE_EXIST_LEN  1u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_AUTOLOAD_CONFIGURE_EXIST_TYPE DVA_FIELD_TYPE_RO
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_EEPROM_RANGE_2_0_LSP      10u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_EEPROM_RANGE_2_0_LEN      3u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_EEPROM_RANGE_2_0_TYPE     DVA_FIELD_TYPE_RO
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_SCK_FREQ_LSP              8u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_SCK_FREQ_LEN              2u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_SCK_FREQ_TYPE             DVA_FIELD_TYPE_RW
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_VALID_LSP              0u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_VALID_LEN              8u
#define DVA_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_VALID_TYPE             DVA_FIELD_TYPE_RW

#define DVA_EEPROM_CODE_SIZE_ADDR_CODEEA_LSP  0u
#define DVA_EEPROM_CODE_SIZE_ADDR_CODEEA_LEN  16u
#define DVA_EEPROM_CODE_SIZE_ADDR_CODEEA_TYPE DVA_FIELD_TYPE_RO

#define DVA_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_END_POS_LSP    16u
#define DVA_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_END_POS_LEN    16u
#define DVA_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_END_POS_TYPE   DVA_FIELD_TYPE_RW
#define DVA_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_START_POS_LSP  0u
#define DVA_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_START_POS_LEN  16u
#define DVA_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_START_POS_TYPE DVA_FIELD_TYPE_RW

#define DVA_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_END_POS_LSP    16u
#define DVA_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_END_POS_LEN    16u
#define DVA_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_END_POS_TYPE   DVA_FIELD_TYPE_RW
#define DVA_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_START_POS_LSP  0u
#define DVA_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_START_POS_LEN  16u
#define DVA_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_START_POS_TYPE DVA_FIELD_TYPE_RW

#define DVA_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_END_POS_LSP    16u
#define DVA_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_END_POS_LEN    16u
#define DVA_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_END_POS_TYPE   DVA_FIELD_TYPE_RW
#define DVA_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_START_POS_LSP  0u
#define DVA_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_START_POS_LEN  16u
#define DVA_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_START_POS_TYPE DVA_FIELD_TYPE_RW

#define DVA_EEPROM_STATUS_EEPROM_VALID_FAIL_LSP     4u
#define DVA_EEPROM_STATUS_EEPROM_VALID_FAIL_LEN     1u
#define DVA_EEPROM_STATUS_EEPROM_VALID_FAIL_TYPE    DVA_FIELD_TYPE_RO
#define DVA_EEPROM_STATUS_SEL_EEPROM_ADDR_SIZE_LSP  3u
#define DVA_EEPROM_STATUS_SEL_EEPROM_ADDR_SIZE_LEN  1u
#define DVA_EEPROM_STATUS_SEL_EEPROM_ADDR_SIZE_TYPE DVA_FIELD_TYPE_RO
#define DVA_EEPROM_STATUS_EEPROM_COMPLETE_LSP       2u
#define DVA_EEPROM_STATUS_EEPROM_COMPLETE_LEN       1u
#define DVA_EEPROM_STATUS_EEPROM_COMPLETE_TYPE      DVA_FIELD_TYPE_RO
#define DVA_EEPROM_STATUS_NOEEPROM_LSP              1u
#define DVA_EEPROM_STATUS_NOEEPROM_LEN              1u
#define DVA_EEPROM_STATUS_NOEEPROM_TYPE             DVA_FIELD_TYPE_RO

#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_EXEC_CPU_LSP        31u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_EXEC_CPU_LEN        1u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_EXEC_CPU_TYPE       DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ACCMD_CPU_LSP       30u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ACCMD_CPU_LEN       1u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ACCMD_CPU_TYPE      DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATATYPE_CPU_LSP    29u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATATYPE_CPU_LEN    1u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATATYPE_CPU_TYPE   DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATALENGTH_CPU_LSP  24u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATALENGTH_CPU_LEN  5u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATALENGTH_CPU_TYPE DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DEVADDR_CPU_LSP     18u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DEVADDR_CPU_LEN     3u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DEVADDR_CPU_TYPE    DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_SUCCESS_CPU_LSP     17u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_SUCCESS_CPU_LEN     1u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_SUCCESS_CPU_TYPE    DVA_FIELD_TYPE_RW1C
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_RETRY_CPU_LSP       16u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_RETRY_CPU_LEN       1u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_RETRY_CPU_TYPE      DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_HIGH_CPU_LSP   8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_HIGH_CPU_LEN   8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_HIGH_CPU_TYPE  DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_LOW_CPU_LSP    0u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_LOW_CPU_LEN    8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_LOW_CPU_TYPE   DVA_FIELD_TYPE_RWS

#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA3_LSP  24u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA3_LEN  8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA3_TYPE DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA2_LSP  16u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA2_LEN  8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA2_TYPE DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA1_LSP  8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA1_LEN  8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA1_TYPE DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA0_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA0_LEN  8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA0_TYPE DVA_FIELD_TYPE_RWS

#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA7_LSP  24u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA7_LEN  8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA7_TYPE DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA6_LSP  16u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA6_LEN  8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA6_TYPE DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA5_LSP  8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA5_LEN  8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA5_TYPE DVA_FIELD_TYPE_RWS
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA4_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA4_LEN  8u
#define DVA_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA4_TYPE DVA_FIELD_TYPE_RWS

#define DVA_I2C_8051_CPU_OCCUPY_STATUS_I2C_8051_OCCUPY_LSP  1u
#define DVA_I2C_8051_CPU_OCCUPY_STATUS_I2C_8051_OCCUPY_LEN  1u
#define DVA_I2C_8051_CPU_OCCUPY_STATUS_I2C_8051_OCCUPY_TYPE DVA_FIELD_TYPE_RWS
#define DVA_I2C_8051_CPU_OCCUPY_STATUS_I2C_CPU_OCCUPY_LSP   0u
#define DVA_I2C_8051_CPU_OCCUPY_STATUS_I2C_CPU_OCCUPY_LEN   1u
#define DVA_I2C_8051_CPU_OCCUPY_STATUS_I2C_CPU_OCCUPY_TYPE  DVA_FIELD_TYPE_RWS

#define DVA_I2C_DMY0_I2C_DMY_REG_0_LSP  0u
#define DVA_I2C_DMY0_I2C_DMY_REG_0_LEN  32u
#define DVA_I2C_DMY0_I2C_DMY_REG_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_REGACC_CHANNEL_CONTROL_PHYAD0_RD_EN_LSP  2u
#define DVA_REGACC_CHANNEL_CONTROL_PHYAD0_RD_EN_LEN  1u
#define DVA_REGACC_CHANNEL_CONTROL_PHYAD0_RD_EN_TYPE DVA_FIELD_TYPE_RW
#define DVA_REGACC_CHANNEL_CONTROL_SEL_PREM_LSP      0u
#define DVA_REGACC_CHANNEL_CONTROL_SEL_PREM_LEN      2u
#define DVA_REGACC_CHANNEL_CONTROL_SEL_PREM_TYPE     DVA_FIELD_TYPE_RW

#define DVA_I2C_DMY1_I2C_DMY_REG_1_LSP  0u
#define DVA_I2C_DMY1_I2C_DMY_REG_1_LEN  32u
#define DVA_I2C_DMY1_I2C_DMY_REG_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_MDC_MDIO_MASTER_CONTROL0_SEL_SMI_FREQ_LSP  9u
#define DVA_MDC_MDIO_MASTER_CONTROL0_SEL_SMI_FREQ_LEN  5u
#define DVA_MDC_MDIO_MASTER_CONTROL0_SEL_SMI_FREQ_TYPE DVA_FIELD_TYPE_RW
#define DVA_MDC_MDIO_MASTER_CONTROL0_SMI_TIMEOUT_LSP   8u
#define DVA_MDC_MDIO_MASTER_CONTROL0_SMI_TIMEOUT_LEN   1u
#define DVA_MDC_MDIO_MASTER_CONTROL0_SMI_TIMEOUT_TYPE  DVA_FIELD_TYPE_RS
#define DVA_MDC_MDIO_MASTER_CONTROL0_SEL_PREM_LSP      2u
#define DVA_MDC_MDIO_MASTER_CONTROL0_SEL_PREM_LEN      2u
#define DVA_MDC_MDIO_MASTER_CONTROL0_SEL_PREM_TYPE     DVA_FIELD_TYPE_RW

#define DVA_MDC_MDIO_MASTER_CONTROL1_PHYADDR_4_0_LSP  0u
#define DVA_MDC_MDIO_MASTER_CONTROL1_PHYADDR_4_0_LEN  5u
#define DVA_MDC_MDIO_MASTER_CONTROL1_PHYADDR_4_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_DATA_15_0_LSP    16u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_DATA_15_0_LEN    16u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_DATA_15_0_TYPE   DVA_FIELD_TYPE_RWS
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_REG_4_0_LSP      8u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_REG_4_0_LEN      5u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_REG_4_0_TYPE     DVA_FIELD_TYPE_RW
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PAGE_4_0_LSP     3u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PAGE_4_0_LEN     5u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PAGE_4_0_TYPE    DVA_FIELD_TYPE_RW
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PHY_REG_TYP_LSP  2u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PHY_REG_TYP_LEN  1u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PHY_REG_TYP_TYPE DVA_FIELD_TYPE_RW
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_RWOP_LSP         1u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_RWOP_LEN         1u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_RWOP_TYPE        DVA_FIELD_TYPE_RW
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_CDM_LSP          0u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_CDM_LEN          1u
#define DVA_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_CDM_TYPE         DVA_FIELD_TYPE_RWS

#define DVA_SPI_SLAVE_CONTROL_SPI_BURST_ENABLE_LSP  5u
#define DVA_SPI_SLAVE_CONTROL_SPI_BURST_ENABLE_LEN  1u
#define DVA_SPI_SLAVE_CONTROL_SPI_BURST_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_SPI_SLAVE_CONTROL_SPI_DMY_CYCLE_LSP     0u
#define DVA_SPI_SLAVE_CONTROL_SPI_DMY_CYCLE_LEN     5u
#define DVA_SPI_SLAVE_CONTROL_SPI_DMY_CYCLE_TYPE    DVA_FIELD_TYPE_RW

#define DVA_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_TX_GEN_DATA_SEL_LSP  16u
#define DVA_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_TX_GEN_DATA_SEL_LEN  1u
#define DVA_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_TX_GEN_DATA_SEL_TYPE DVA_FIELD_TYPE_RW
#define DVA_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_WR_OP_LSP     8u
#define DVA_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_WR_OP_LEN     8u
#define DVA_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_WR_OP_TYPE    DVA_FIELD_TYPE_RW
#define DVA_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_RD_OP_LSP     0u
#define DVA_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_RD_OP_LEN     8u
#define DVA_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_RD_OP_TYPE    DVA_FIELD_TYPE_RW

#define DVA_SPI_SLAVE_CHECKSUM_INTERRUPT_STATUS_SLV_CHKSUM_FAIL_INT_STS_LSP  0u
#define DVA_SPI_SLAVE_CHECKSUM_INTERRUPT_STATUS_SLV_CHKSUM_FAIL_INT_STS_LEN  1u
#define DVA_SPI_SLAVE_CHECKSUM_INTERRUPT_STATUS_SLV_CHKSUM_FAIL_INT_STS_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_SPI_SLAVE_CHECKSUM_INTERRUPT_CONTROL_SLV_CHKSUM_FAIL_INT_EN_LSP  0u
#define DVA_SPI_SLAVE_CHECKSUM_INTERRUPT_CONTROL_SLV_CHKSUM_FAIL_INT_EN_LEN  1u
#define DVA_SPI_SLAVE_CHECKSUM_INTERRUPT_CONTROL_SLV_CHKSUM_FAIL_INT_EN_TYPE DVA_FIELD_TYPE_RW

#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_APB_RD_SLOW_EXTRA_LSP      5u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_APB_RD_SLOW_EXTRA_LEN      1u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_APB_RD_SLOW_EXTRA_TYPE     DVA_FIELD_TYPE_RW
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_APB_WR_SLOW_EXTRA_LSP      4u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_APB_WR_SLOW_EXTRA_LEN      1u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_APB_WR_SLOW_EXTRA_TYPE     DVA_FIELD_TYPE_RW
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_SPI_FORCE_SLV_CEB_LSP      3u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_SPI_FORCE_SLV_CEB_LEN      1u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_SPI_FORCE_SLV_CEB_TYPE     DVA_FIELD_TYPE_RW
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_I2C_FORCE_SLV_CEB_LSP      2u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_I2C_FORCE_SLV_CEB_LEN      1u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_I2C_FORCE_SLV_CEB_TYPE     DVA_FIELD_TYPE_RW
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_SLV_CHKSUM_CRC_METHOD_LSP  1u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_SLV_CHKSUM_CRC_METHOD_LEN  1u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_SLV_CHKSUM_CRC_METHOD_TYPE DVA_FIELD_TYPE_RW
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_SLV_CHKSUM_MODE_LSP        0u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_SLV_CHKSUM_MODE_LEN        1u
#define DVA_SLAVE_INTERFACE_CHECKSUM_CONTROL_CFG_SLV_CHKSUM_MODE_TYPE       DVA_FIELD_TYPE_RW

#define DVA_REGACC_CHANNEL_FSM_I2C_SM_NS_LSP  6u
#define DVA_REGACC_CHANNEL_FSM_I2C_SM_NS_LEN  6u
#define DVA_REGACC_CHANNEL_FSM_I2C_SM_NS_TYPE DVA_FIELD_TYPE_RO
#define DVA_REGACC_CHANNEL_FSM_I2C_SM_CS_LSP  0u
#define DVA_REGACC_CHANNEL_FSM_I2C_SM_CS_LEN  6u
#define DVA_REGACC_CHANNEL_FSM_I2C_SM_CS_TYPE DVA_FIELD_TYPE_RO

#define DVA_PSEUDO_REG_PAGE_NUMBER_PSEUDO_PG_NUM_LSP  0u
#define DVA_PSEUDO_REG_PAGE_NUMBER_PSEUDO_PG_NUM_LEN  8u
#define DVA_PSEUDO_REG_PAGE_NUMBER_PSEUDO_PG_NUM_TYPE DVA_FIELD_TYPE_RO

#define DVA_PSEUDO_REG_CMD_PSEUDO_CMD_REG_LSP  0u
#define DVA_PSEUDO_REG_CMD_PSEUDO_CMD_REG_LEN  32u
#define DVA_PSEUDO_REG_CMD_PSEUDO_CMD_REG_TYPE DVA_FIELD_TYPE_RO

#define DVA_PSEUDO_REG_DAT_PSEUDO_DAT_REG_LSP  0u
#define DVA_PSEUDO_REG_DAT_PSEUDO_DAT_REG_LEN  32u
#define DVA_PSEUDO_REG_DAT_PSEUDO_DAT_REG_TYPE DVA_FIELD_TYPE_RO

#define DVA_PSEUDO_REG_AUTH_CTRL_PSEUDO_AUTH_CTRL_LSP  0u
#define DVA_PSEUDO_REG_AUTH_CTRL_PSEUDO_AUTH_CTRL_LEN  32u
#define DVA_PSEUDO_REG_AUTH_CTRL_PSEUDO_AUTH_CTRL_TYPE DVA_FIELD_TYPE_RO

#define DVA_FUSA_PG_LOCK_DMY_I2C_FUSA_PG_LOCK_DMY_I2C_LSP  0u
#define DVA_FUSA_PG_LOCK_DMY_I2C_FUSA_PG_LOCK_DMY_I2C_LEN  1u
#define DVA_FUSA_PG_LOCK_DMY_I2C_FUSA_PG_LOCK_DMY_I2C_TYPE DVA_FIELD_TYPE_RW

#define DVA_I2C_FSM_CONTROL_I2C_FSM_TIMEOUT_ENABLE_LSP     31u
#define DVA_I2C_FSM_CONTROL_I2C_FSM_TIMEOUT_ENABLE_LEN     1u
#define DVA_I2C_FSM_CONTROL_I2C_FSM_TIMEOUT_ENABLE_TYPE    DVA_FIELD_TYPE_RW
#define DVA_I2C_FSM_CONTROL_I2C_FSM_TIMEOUT_AUTO_IDLE_LSP  30u
#define DVA_I2C_FSM_CONTROL_I2C_FSM_TIMEOUT_AUTO_IDLE_LEN  1u
#define DVA_I2C_FSM_CONTROL_I2C_FSM_TIMEOUT_AUTO_IDLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_I2C_FSM_CONTROL_I2C_FSM_JUMP_IDLE_LSP          29u
#define DVA_I2C_FSM_CONTROL_I2C_FSM_JUMP_IDLE_LEN          1u
#define DVA_I2C_FSM_CONTROL_I2C_FSM_JUMP_IDLE_TYPE         DVA_FIELD_TYPE_RWS
#define DVA_I2C_FSM_CONTROL_I2C_FSM_TIMEOUT_THRESHOLD_LSP  0u
#define DVA_I2C_FSM_CONTROL_I2C_FSM_TIMEOUT_THRESHOLD_LEN  28u
#define DVA_I2C_FSM_CONTROL_I2C_FSM_TIMEOUT_THRESHOLD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PSEUDO_REG_ERROR_STATUS_PSEUDO_ERROR_STATUS_LSP  0u
#define DVA_PSEUDO_REG_ERROR_STATUS_PSEUDO_ERROR_STATUS_LEN  16u
#define DVA_PSEUDO_REG_ERROR_STATUS_PSEUDO_ERROR_STATUS_TYPE DVA_FIELD_TYPE_RO

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_I2C_H_ */