/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_MAILBOX_H_
#define DVA_RTKAS_REG_FIELD_FILE_MAILBOX_H_

#ifdef DVA_FILE_MAILBOX
/* File: mailbox */
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_0_OPCODE_CPU_INDIR_CH0_OPCODE_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_0_OPCODE_CPU_INDIR_CH0_OPCODE_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_0_OPCODE_CPU_INDIR_CH0_OPCODE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_0_ADDRESS_CPU_INDIR_CH0_ADDRESS_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_0_ADDRESS_CPU_INDIR_CH0_ADDRESS_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_0_ADDRESS_CPU_INDIR_CH0_ADDRESS_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_0_DATA_CPU_INDIR_CH0_DATA_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_0_DATA_CPU_INDIR_CH0_DATA_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_0_DATA_CPU_INDIR_CH0_DATA_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_1_OPCODE_CPU_INDIR_CH1_OPCODE_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_1_OPCODE_CPU_INDIR_CH1_OPCODE_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_1_OPCODE_CPU_INDIR_CH1_OPCODE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_1_ADDRESS_CPU_INDIR_CH1_ADDRESS_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_1_ADDRESS_CPU_INDIR_CH1_ADDRESS_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_1_ADDRESS_CPU_INDIR_CH1_ADDRESS_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_1_DATA_CPU_INDIR_CH1_DATA_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_1_DATA_CPU_INDIR_CH1_DATA_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_1_DATA_CPU_INDIR_CH1_DATA_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_2_OPCODE_CPU_INDIR_CH2_OPCODE_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_2_OPCODE_CPU_INDIR_CH2_OPCODE_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_2_OPCODE_CPU_INDIR_CH2_OPCODE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_2_PARAMETER_1_CPU_INDIR_CH2_PARAMETER_1_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_2_PARAMETER_1_CPU_INDIR_CH2_PARAMETER_1_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_2_PARAMETER_1_CPU_INDIR_CH2_PARAMETER_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_2_PARAMETER_2_CPU_INDIR_CH2_PARAMETER_2_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_2_PARAMETER_2_CPU_INDIR_CH2_PARAMETER_2_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_2_PARAMETER_2_CPU_INDIR_CH2_PARAMETER_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_3_OPCODE_CPU_INDIR_CH3_OPCODE_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_3_OPCODE_CPU_INDIR_CH3_OPCODE_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_3_OPCODE_CPU_INDIR_CH3_OPCODE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_3_PARAMETER_1_CPU_INDIR_CH3_PARAMETER_1_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_3_PARAMETER_1_CPU_INDIR_CH3_PARAMETER_1_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_3_PARAMETER_1_CPU_INDIR_CH3_PARAMETER_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_3_PARAMETER_2_CPU_INDIR_CH3_PARAMETER_2_LSP  0u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_3_PARAMETER_2_CPU_INDIR_CH3_PARAMETER_2_LEN  32u
#define DVA_CPU_INDIRECT_ACCESS_CHANNEL_3_PARAMETER_2_CPU_INDIR_CH3_PARAMETER_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_COMMAND_IN_FLASHLESS_MODE_OPCODE_CPU_CMD_FLASHLESS_OPCODE_LSP  0u
#define DVA_CPU_COMMAND_IN_FLASHLESS_MODE_OPCODE_CPU_CMD_FLASHLESS_OPCODE_LEN  32u
#define DVA_CPU_COMMAND_IN_FLASHLESS_MODE_OPCODE_CPU_CMD_FLASHLESS_OPCODE_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_COMMAND_IN_FLASHLESS_MODE_PARAMETER_1_CPU_CMD_FLASHLESS_PARAMETER_1_LSP  0u
#define DVA_CPU_COMMAND_IN_FLASHLESS_MODE_PARAMETER_1_CPU_CMD_FLASHLESS_PARAMETER_1_LEN  32u
#define DVA_CPU_COMMAND_IN_FLASHLESS_MODE_PARAMETER_1_CPU_CMD_FLASHLESS_PARAMETER_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_CPU_COMMAND_IN_FLASHLESS_MODE_PARAMETER_2_CPU_CMD_FLASHLESS_PARAMETER_2_LSP  0u
#define DVA_CPU_COMMAND_IN_FLASHLESS_MODE_PARAMETER_2_CPU_CMD_FLASHLESS_PARAMETER_2_LEN  32u
#define DVA_CPU_COMMAND_IN_FLASHLESS_MODE_PARAMETER_2_CPU_CMD_FLASHLESS_PARAMETER_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_DMY_REG_EXT_CHK_1_SAFETY_DMY_REG_ACCESS_1_LSP  0u
#define DVA_DMY_REG_EXT_CHK_1_SAFETY_DMY_REG_ACCESS_1_LEN  8u
#define DVA_DMY_REG_EXT_CHK_1_SAFETY_DMY_REG_ACCESS_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_DMY_REG_EXT_CHK_2_SAFETY_DMY_REG_ACCESS_2_LSP  0u
#define DVA_DMY_REG_EXT_CHK_2_SAFETY_DMY_REG_ACCESS_2_LEN  8u
#define DVA_DMY_REG_EXT_CHK_2_SAFETY_DMY_REG_ACCESS_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_DMY_REG_EXT_CHK_3_SAFETY_DMY_REG_ACCESS_3_LSP  0u
#define DVA_DMY_REG_EXT_CHK_3_SAFETY_DMY_REG_ACCESS_3_LEN  8u
#define DVA_DMY_REG_EXT_CHK_3_SAFETY_DMY_REG_ACCESS_3_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_MAILBOX_H_ */