/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_PORT_RELAY_DIS_H_
#define DVA_RTKAS_REG_FIELD_FILE_PORT_RELAY_DIS_H_

#ifdef DVA_FILE_PORT_RELAY_DIS
/* File: port_relay_dis */
#define DVA_PORT0_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT0_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT0_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT1_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT1_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT2_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT2_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT3_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT3_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT4_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT4_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT5_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT5_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT6_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT6_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT7_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT7_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT8_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT8_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT9_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT9_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT10_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT10_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT11_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT11_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT12_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT12_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT13_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT13_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT14_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT14_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_CRCPR_CON_CRCPR_CON_LSP  0u
#define DVA_PORT15_CRCPR_CON_CRCPR_CON_LEN  2u
#define DVA_PORT15_CRCPR_CON_CRCPR_CON_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT0_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT0_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT0_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT0_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT0_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT1_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT1_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT1_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT1_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT1_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT1_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT2_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT2_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT2_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT2_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT2_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT2_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT3_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT3_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT3_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT3_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT3_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT3_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT4_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT4_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT4_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT4_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT4_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT4_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT5_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT5_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT5_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT5_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT5_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT5_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT6_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT6_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT6_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT6_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT6_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT6_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT7_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT7_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT7_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT7_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT7_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT7_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT8_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT8_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT8_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT8_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT8_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT8_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT9_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT9_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT9_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT9_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT9_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT9_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT10_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT10_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT10_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT10_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT10_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT10_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT11_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT11_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT11_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT11_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT11_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT11_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT12_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT12_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT12_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT12_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT12_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT12_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT13_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT13_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT13_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT13_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT13_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT13_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT14_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT14_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT14_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT14_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT14_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT14_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT15_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LSP         1u
#define DVA_PORT15_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_LEN         1u
#define DVA_PORT15_CRCPR_METER_RELAY_STATUS_CRCPR_METER_CLEAR_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_PORT15_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LSP  0u
#define DVA_PORT15_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_LEN  1u
#define DVA_PORT15_CRCPR_METER_RELAY_STATUS_CRCPR_METER_RELAY_STATUS_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT0_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT0_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT0_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT1_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT1_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT2_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT2_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT3_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT3_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT4_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT4_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT5_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT5_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT6_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT6_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT7_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT7_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT8_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT8_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT9_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT9_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT10_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT10_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT11_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT11_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT12_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT12_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT13_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT13_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT14_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT14_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_CRCPR_IE_CRCPR_IE_LSP  0u
#define DVA_PORT15_CRCPR_IE_CRCPR_IE_LEN  3u
#define DVA_PORT15_CRCPR_IE_CRCPR_IE_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT0_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT0_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT1_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT1_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT1_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT2_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT2_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT2_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT3_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT3_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT3_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT4_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT4_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT4_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT5_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT5_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT5_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT6_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT6_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT6_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT7_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT7_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT7_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT8_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT8_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT8_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT9_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT9_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT9_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT10_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT10_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT10_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT11_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT11_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT11_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT12_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT12_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT12_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT13_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT13_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT13_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT14_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT14_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT14_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT15_CRCPR_IP_CRCPR_IP_LSP  0u
#define DVA_PORT15_CRCPR_IP_CRCPR_IP_LEN  3u
#define DVA_PORT15_CRCPR_IP_CRCPR_IP_TYPE DVA_FIELD_TYPE_RWS

#define DVA_PORT0_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT0_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT0_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT1_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT1_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT2_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT2_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT3_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT3_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT4_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT4_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT5_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT5_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT6_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT6_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT7_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT7_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT8_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT8_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT9_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT9_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT10_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT10_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT11_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT11_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT12_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT12_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT13_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT13_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT14_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT14_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LSP  0u
#define DVA_PORT15_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_LEN  32u
#define DVA_PORT15_CRCPR_METER_INC_WEIGHT_CRCPR_METER_INC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT0_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT0_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT1_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT1_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT2_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT2_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT3_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT3_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT4_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT4_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT5_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT5_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT6_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT6_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT7_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT7_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT8_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT8_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT9_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT9_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT10_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT10_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT11_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT11_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT12_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT12_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT13_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT13_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT14_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT14_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LSP  0u
#define DVA_PORT15_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_LEN  32u
#define DVA_PORT15_CRCPR_METER_DEC_WEIGHT_CRCPR_METER_DEC_WEIGHT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT0_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT0_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT1_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT1_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT2_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT2_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT3_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT3_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT4_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT4_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT5_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT5_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT6_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT6_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT7_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT7_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT8_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT8_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT9_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT9_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT10_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT10_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT11_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT11_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT12_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT12_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT13_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT13_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT14_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT14_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LSP  0u
#define DVA_PORT15_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_LEN  32u
#define DVA_PORT15_CRCPR_METER_RELAYDIS_THOD_CRCPR_METER_RELAYDIS_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT0_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT0_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT1_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT1_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT2_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT2_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT3_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT3_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT4_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT4_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT5_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT5_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT6_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT6_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT7_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT7_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT8_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT8_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT9_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT9_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT10_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT10_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT11_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT11_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT12_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT12_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT13_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT13_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT14_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT14_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LSP  0u
#define DVA_PORT15_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_LEN  32u
#define DVA_PORT15_CRCPR_METER_RELAYALE_THOD_CRCPR_METER_RELAYEN_THOD_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT0_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT0_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT1_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT1_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT1_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT2_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT2_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT2_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT3_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT3_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT3_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT4_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT4_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT4_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT5_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT5_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT5_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT6_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT6_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT6_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT7_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT7_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT7_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT8_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT8_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT8_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT9_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT9_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT9_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT10_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT10_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT10_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT11_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT11_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT11_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT12_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT12_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT12_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT13_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT13_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT13_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT14_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT14_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT14_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT15_CRCPR_METER_CNT_CRCPR_METER_CNT_LSP  0u
#define DVA_PORT15_CRCPR_METER_CNT_CRCPR_METER_CNT_LEN  32u
#define DVA_PORT15_CRCPR_METER_CNT_CRCPR_METER_CNT_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT0_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT0_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT0_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT1_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT1_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT2_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT2_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT3_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT3_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT4_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT4_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT5_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT5_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT6_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT6_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT7_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT7_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT8_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT8_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT9_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT9_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT10_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT10_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT11_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT11_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT12_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT12_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT13_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT13_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT14_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT14_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LSP  0u
#define DVA_PORT15_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_LEN  32u
#define DVA_PORT15_CRCPR_METER_CYCTIME_CRCPR_METER_CYCTIME_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LSP  0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_LEN  1u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_FUSA_PG_LOCK_DMY_PORT_RELAY_DIS_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_PORT_RELAY_DIS_H_ */