/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_MIRRORING_H_
#define DVA_RTKAS_REG_FIELD_FILE_MIRRORING_H_

#ifdef DVA_FILE_MIRRORING
/* File: Mirroring */
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_SPMDPMOP_LSP   6u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_SPMDPMOP_LEN   1u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_SPMDPMOP_TYPE  DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_CROSSVLAN_LSP  5u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_CROSSVLAN_LEN  1u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_CROSSVLAN_TYPE DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MUA_LSP        4u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MUA_LEN        1u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MUA_TYPE       DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MMA_LSP        3u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MMA_LEN        1u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MMA_TYPE       DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MBA_LSP        2u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MBA_LEN        1u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MBA_TYPE       DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MBPKT_LSP      1u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MBPKT_LEN      1u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MBPKT_TYPE     DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MGPKT_LSP      0u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MGPKT_LEN      1u
#define DVA_TRAFFIC_MIRROR0_CONTROL0_MIR0_MGPKT_TYPE     DVA_FIELD_TYPE_RW

#define DVA_TRAFFIC_MIRROR0_CONTROL1_MIR0_MORG_LSP           6u
#define DVA_TRAFFIC_MIRROR0_CONTROL1_MIR0_MORG_LEN           1u
#define DVA_TRAFFIC_MIRROR0_CONTROL1_MIR0_MORG_TYPE          DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR0_CONTROL1_MIR0_FLOWBASEDONLY_LSP  5u
#define DVA_TRAFFIC_MIRROR0_CONTROL1_MIR0_FLOWBASEDONLY_LEN  1u
#define DVA_TRAFFIC_MIRROR0_CONTROL1_MIR0_FLOWBASEDONLY_TYPE DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR0_CONTROL1_MIR0_DP_LSP             0u
#define DVA_TRAFFIC_MIRROR0_CONTROL1_MIR0_DP_LEN             4u
#define DVA_TRAFFIC_MIRROR0_CONTROL1_MIR0_DP_TYPE            DVA_FIELD_TYPE_RW

#define DVA_TRAFFIC_MIRROR0_CONTROL3_MIR0_SPM1_RESERVED_LSP  16u
#define DVA_TRAFFIC_MIRROR0_CONTROL3_MIR0_SPM1_RESERVED_LEN  16u
#define DVA_TRAFFIC_MIRROR0_CONTROL3_MIR0_SPM1_RESERVED_TYPE DVA_FIELD_TYPE_RO
#define DVA_TRAFFIC_MIRROR0_CONTROL3_MIR0_SPM_LSP            0u
#define DVA_TRAFFIC_MIRROR0_CONTROL3_MIR0_SPM_LEN            16u
#define DVA_TRAFFIC_MIRROR0_CONTROL3_MIR0_SPM_TYPE           DVA_FIELD_TYPE_RW

#define DVA_TRAFFIC_MIRROR0_CONTROL4_MIR0_DPM1_RESERVED_LSP  16u
#define DVA_TRAFFIC_MIRROR0_CONTROL4_MIR0_DPM1_RESERVED_LEN  16u
#define DVA_TRAFFIC_MIRROR0_CONTROL4_MIR0_DPM1_RESERVED_TYPE DVA_FIELD_TYPE_RO
#define DVA_TRAFFIC_MIRROR0_CONTROL4_MIR0_DPM_LSP            0u
#define DVA_TRAFFIC_MIRROR0_CONTROL4_MIR0_DPM_LEN            16u
#define DVA_TRAFFIC_MIRROR0_CONTROL4_MIR0_DPM_TYPE           DVA_FIELD_TYPE_RW

#define DVA_MIRROR0_PORT_EGRESS_FILTER_CONTROL_MIR0_MIREGFILTER_LSP  0u
#define DVA_MIRROR0_PORT_EGRESS_FILTER_CONTROL_MIR0_MIREGFILTER_LEN  1u
#define DVA_MIRROR0_PORT_EGRESS_FILTER_CONTROL_MIR0_MIREGFILTER_TYPE DVA_FIELD_TYPE_RW

#define DVA_TRAFFIC_MIRROR0_SAMPLE_CONTROL_MIR0_SAMPLE_RATE_LSP  16u
#define DVA_TRAFFIC_MIRROR0_SAMPLE_CONTROL_MIR0_SAMPLE_RATE_LEN  16u
#define DVA_TRAFFIC_MIRROR0_SAMPLE_CONTROL_MIR0_SAMPLE_RATE_TYPE DVA_FIELD_TYPE_RWS
#define DVA_TRAFFIC_MIRROR0_SAMPLE_CONTROL_MIR0_PKTCNT_LSP       0u
#define DVA_TRAFFIC_MIRROR0_SAMPLE_CONTROL_MIR0_PKTCNT_LEN       16u
#define DVA_TRAFFIC_MIRROR0_SAMPLE_CONTROL_MIR0_PKTCNT_TYPE      DVA_FIELD_TYPE_RO

#define DVA_TRAFFIC_MIRROR0_SAMPLE_STATISTIC_MIR0_TOTAL_SAMPLE_LSP  0u
#define DVA_TRAFFIC_MIRROR0_SAMPLE_STATISTIC_MIR0_TOTAL_SAMPLE_LEN  32u
#define DVA_TRAFFIC_MIRROR0_SAMPLE_STATISTIC_MIR0_TOTAL_SAMPLE_TYPE DVA_FIELD_TYPE_RO

#define DVA_REMOTE_MIRROR0_TX0_MIR0_RSPAN_TX_TAG_ACT_LSP  0u
#define DVA_REMOTE_MIRROR0_TX0_MIR0_RSPAN_TX_TAG_ACT_LEN  2u
#define DVA_REMOTE_MIRROR0_TX0_MIR0_RSPAN_TX_TAG_ACT_TYPE DVA_FIELD_TYPE_RW

#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_TPID_LSP  16u
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_TPID_LEN  16u
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_TPID_TYPE DVA_FIELD_TYPE_RW
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_PRI_LSP   13u
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_PRI_LEN   3u
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_PRI_TYPE  DVA_FIELD_TYPE_RW
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_CFI_LSP   12u
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_CFI_LEN   1u
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_CFI_TYPE  DVA_FIELD_TYPE_RW
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_VID_LSP   0u
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_VID_LEN   12u
#define DVA_REMOTE_MIRROR0_TX1_MIR0_RSPAN_TX_TAG_VID_TYPE  DVA_FIELD_TYPE_RW

#define DVA_REMOTE_MIRROR0_RX_MIR0_RSPAN_RX_TAG_VID_LSP  4u
#define DVA_REMOTE_MIRROR0_RX_MIR0_RSPAN_RX_TAG_VID_LEN  12u
#define DVA_REMOTE_MIRROR0_RX_MIR0_RSPAN_RX_TAG_VID_TYPE DVA_FIELD_TYPE_RW
#define DVA_REMOTE_MIRROR0_RX_MIR0_RSPAN_RX_TAG_CHK_LSP  0u
#define DVA_REMOTE_MIRROR0_RX_MIR0_RSPAN_RX_TAG_CHK_LEN  1u
#define DVA_REMOTE_MIRROR0_RX_MIR0_RSPAN_RX_TAG_CHK_TYPE DVA_FIELD_TYPE_RW

#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_SPMDPMOP_LSP   6u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_SPMDPMOP_LEN   1u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_SPMDPMOP_TYPE  DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_CROSSVLAN_LSP  5u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_CROSSVLAN_LEN  1u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_CROSSVLAN_TYPE DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MUA_LSP        4u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MUA_LEN        1u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MUA_TYPE       DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MMA_LSP        3u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MMA_LEN        1u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MMA_TYPE       DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MBA_LSP        2u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MBA_LEN        1u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MBA_TYPE       DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MBPKT_LSP      1u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MBPKT_LEN      1u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MBPKT_TYPE     DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MGPKT_LSP      0u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MGPKT_LEN      1u
#define DVA_TRAFFIC_MIRROR1_CONTROL0_MIR1_MGPKT_TYPE     DVA_FIELD_TYPE_RW

#define DVA_TRAFFIC_MIRROR1_CONTROL1_MIR1_MORG_LSP           6u
#define DVA_TRAFFIC_MIRROR1_CONTROL1_MIR1_MORG_LEN           1u
#define DVA_TRAFFIC_MIRROR1_CONTROL1_MIR1_MORG_TYPE          DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR1_CONTROL1_MIR1_FLOWBASEDONLY_LSP  5u
#define DVA_TRAFFIC_MIRROR1_CONTROL1_MIR1_FLOWBASEDONLY_LEN  1u
#define DVA_TRAFFIC_MIRROR1_CONTROL1_MIR1_FLOWBASEDONLY_TYPE DVA_FIELD_TYPE_RW
#define DVA_TRAFFIC_MIRROR1_CONTROL1_MIR1_DP_LSP             0u
#define DVA_TRAFFIC_MIRROR1_CONTROL1_MIR1_DP_LEN             4u
#define DVA_TRAFFIC_MIRROR1_CONTROL1_MIR1_DP_TYPE            DVA_FIELD_TYPE_RW

#define DVA_TRAFFIC_MIRROR1_CONTROL3_MIR1_SPM1_RESERVED_LSP  16u
#define DVA_TRAFFIC_MIRROR1_CONTROL3_MIR1_SPM1_RESERVED_LEN  16u
#define DVA_TRAFFIC_MIRROR1_CONTROL3_MIR1_SPM1_RESERVED_TYPE DVA_FIELD_TYPE_RO
#define DVA_TRAFFIC_MIRROR1_CONTROL3_MIR1_SPM_LSP            0u
#define DVA_TRAFFIC_MIRROR1_CONTROL3_MIR1_SPM_LEN            16u
#define DVA_TRAFFIC_MIRROR1_CONTROL3_MIR1_SPM_TYPE           DVA_FIELD_TYPE_RW

#define DVA_TRAFFIC_MIRROR1_CONTROL4_MIR1_DPM1_RESERVED_LSP  16u
#define DVA_TRAFFIC_MIRROR1_CONTROL4_MIR1_DPM1_RESERVED_LEN  16u
#define DVA_TRAFFIC_MIRROR1_CONTROL4_MIR1_DPM1_RESERVED_TYPE DVA_FIELD_TYPE_RO
#define DVA_TRAFFIC_MIRROR1_CONTROL4_MIR1_DPM_LSP            0u
#define DVA_TRAFFIC_MIRROR1_CONTROL4_MIR1_DPM_LEN            16u
#define DVA_TRAFFIC_MIRROR1_CONTROL4_MIR1_DPM_TYPE           DVA_FIELD_TYPE_RW

#define DVA_MIRROR1_PORT_EGRESS_FILTER_CONTROL_MIR1_MIREGFILTER_LSP  0u
#define DVA_MIRROR1_PORT_EGRESS_FILTER_CONTROL_MIR1_MIREGFILTER_LEN  1u
#define DVA_MIRROR1_PORT_EGRESS_FILTER_CONTROL_MIR1_MIREGFILTER_TYPE DVA_FIELD_TYPE_RW

#define DVA_TRAFFIC_MIRROR1_SAMPLE_CONTROL_MIR1_SAMPLE_RATE_LSP  16u
#define DVA_TRAFFIC_MIRROR1_SAMPLE_CONTROL_MIR1_SAMPLE_RATE_LEN  16u
#define DVA_TRAFFIC_MIRROR1_SAMPLE_CONTROL_MIR1_SAMPLE_RATE_TYPE DVA_FIELD_TYPE_RWS
#define DVA_TRAFFIC_MIRROR1_SAMPLE_CONTROL_MIR1_PKTCNT_LSP       0u
#define DVA_TRAFFIC_MIRROR1_SAMPLE_CONTROL_MIR1_PKTCNT_LEN       16u
#define DVA_TRAFFIC_MIRROR1_SAMPLE_CONTROL_MIR1_PKTCNT_TYPE      DVA_FIELD_TYPE_RO

#define DVA_TRAFFIC_MIRROR1_SAMPLE_STATISTIC_MIR1_TOTAL_SAMPLE_LSP  0u
#define DVA_TRAFFIC_MIRROR1_SAMPLE_STATISTIC_MIR1_TOTAL_SAMPLE_LEN  32u
#define DVA_TRAFFIC_MIRROR1_SAMPLE_STATISTIC_MIR1_TOTAL_SAMPLE_TYPE DVA_FIELD_TYPE_RO

#define DVA_REMOTE_MIRROR1_TX0_MIR1_RSPAN_TX_TAG_ACT_LSP  0u
#define DVA_REMOTE_MIRROR1_TX0_MIR1_RSPAN_TX_TAG_ACT_LEN  2u
#define DVA_REMOTE_MIRROR1_TX0_MIR1_RSPAN_TX_TAG_ACT_TYPE DVA_FIELD_TYPE_RW

#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_TPID_LSP  16u
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_TPID_LEN  16u
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_TPID_TYPE DVA_FIELD_TYPE_RW
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_PRI_LSP   13u
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_PRI_LEN   3u
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_PRI_TYPE  DVA_FIELD_TYPE_RW
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_CFI_LSP   12u
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_CFI_LEN   1u
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_CFI_TYPE  DVA_FIELD_TYPE_RW
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_VID_LSP   0u
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_VID_LEN   12u
#define DVA_REMOTE_MIRROR1_TX1_MIR1_RSPAN_TX_TAG_VID_TYPE  DVA_FIELD_TYPE_RW

#define DVA_REMOTE_MIRROR1_RX_MIR1_RSPAN_RX_TAG_VID_LSP  4u
#define DVA_REMOTE_MIRROR1_RX_MIR1_RSPAN_RX_TAG_VID_LEN  12u
#define DVA_REMOTE_MIRROR1_RX_MIR1_RSPAN_RX_TAG_VID_TYPE DVA_FIELD_TYPE_RW
#define DVA_REMOTE_MIRROR1_RX_MIR1_RSPAN_RX_TAG_CHK_LSP  0u
#define DVA_REMOTE_MIRROR1_RX_MIR1_RSPAN_RX_TAG_CHK_LEN  1u
#define DVA_REMOTE_MIRROR1_RX_MIR1_RSPAN_RX_TAG_CHK_TYPE DVA_FIELD_TYPE_RW

#define DVA_FUSA_PG_LOCK_DMY_MIRRORING_FUSA_PG_LOCK_DMY_MIRRORING_LSP  0u
#define DVA_FUSA_PG_LOCK_DMY_MIRRORING_FUSA_PG_LOCK_DMY_MIRRORING_LEN  1u
#define DVA_FUSA_PG_LOCK_DMY_MIRRORING_FUSA_PG_LOCK_DMY_MIRRORING_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_MIRRORING_H_ */