/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_REMARKING_H_
#define DVA_RTKAS_REG_FIELD_FILE_REMARKING_H_

#ifdef DVA_FILE_REMARKING
/* File: Remarking */
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI7_LSP  31u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI7_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI7_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI7_LSP   28u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI7_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI7_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI6_LSP  27u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI6_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI6_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI6_LSP   24u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI6_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI6_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI5_LSP  23u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI5_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI5_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI5_LSP   20u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI5_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI5_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI4_LSP  19u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI4_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI4_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI4_LSP   16u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI4_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI4_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI3_LSP  15u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI3_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI3_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI3_LSP   12u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI3_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI3_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI2_LSP  11u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI2_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI2_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI2_LSP   8u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI2_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI2_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI1_LSP  7u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI1_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI1_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI1_LSP   4u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI1_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI1_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI0_LSP  3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI0_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_IDEITOPRI0_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI0_LSP   0u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI0_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL0_PRITOPRI0_TYPE  DVA_FIELD_TYPE_RW

#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI7_LSP  31u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI7_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI7_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI7_LSP   28u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI7_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI7_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI6_LSP  27u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI6_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI6_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI6_LSP   24u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI6_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI6_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI5_LSP  23u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI5_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI5_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI5_LSP   20u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI5_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI5_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI4_LSP  19u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI4_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI4_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI4_LSP   16u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI4_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI4_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI3_LSP  15u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI3_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI3_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI3_LSP   12u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI3_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI3_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI2_LSP  11u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI2_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI2_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI2_LSP   8u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI2_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI2_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI1_LSP  7u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI1_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI1_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI1_LSP   4u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI1_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI1_TYPE  DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI0_LSP  3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI0_LEN  1u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_IDEITOPRI0_TYPE DVA_FIELD_TYPE_RW
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI0_LSP   0u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI0_LEN   3u
#define DVA_INNER_TAG_PRIORITY_REMARKING_TABLE_CONTROL1_PRITOPRI0_TYPE  DVA_FIELD_TYPE_RW

#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI7_LSP  31u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI7_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI7_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI7_LSP   28u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI7_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI7_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI6_LSP  27u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI6_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI6_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI6_LSP   24u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI6_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI6_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI5_LSP  23u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI5_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI5_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI5_LSP   20u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI5_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI5_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI4_LSP  19u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI4_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI4_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI4_LSP   16u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI4_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI4_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI3_LSP  15u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI3_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI3_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI3_LSP   12u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI3_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI3_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI2_LSP  11u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI2_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI2_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI2_LSP   8u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI2_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI2_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI1_LSP  7u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI1_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI1_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI1_LSP   4u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI1_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI1_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI0_LSP  3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI0_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_ODEITOPRI0_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI0_LSP   0u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI0_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL0_PRITOPRI0_TYPE  DVA_FIELD_TYPE_RW

#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI7_LSP  31u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI7_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI7_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI7_LSP   28u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI7_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI7_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI6_LSP  27u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI6_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI6_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI6_LSP   24u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI6_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI6_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI5_LSP  23u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI5_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI5_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI5_LSP   20u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI5_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI5_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI4_LSP  19u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI4_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI4_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI4_LSP   16u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI4_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI4_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI3_LSP  15u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI3_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI3_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI3_LSP   12u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI3_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI3_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI2_LSP  11u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI2_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI2_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI2_LSP   8u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI2_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI2_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI1_LSP  7u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI1_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI1_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI1_LSP   4u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI1_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI1_TYPE  DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI0_LSP  3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI0_LEN  1u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_ODEITOPRI0_TYPE DVA_FIELD_TYPE_RW
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI0_LSP   0u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI0_LEN   3u
#define DVA_OUTER_TAG_PRIORITY_AND_DEI_REMARKING_TABLE_CONTROL1_PRITOPRI0_TYPE  DVA_FIELD_TYPE_RW

#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI4_LSP  24u
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI4_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI4_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI3_LSP  18u
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI3_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI3_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI2_LSP  12u
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI2_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI2_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI1_LSP  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI1_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI1_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI0_LSP  0u
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI0_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL0_DSCPTOPRI0_TYPE DVA_FIELD_TYPE_RW

#define DVA_DSCP_REMARKING_TABLE_CONTROL1_DSCPTOPRI7_LSP  12u
#define DVA_DSCP_REMARKING_TABLE_CONTROL1_DSCPTOPRI7_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL1_DSCPTOPRI7_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL1_DSCPTOPRI6_LSP  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL1_DSCPTOPRI6_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL1_DSCPTOPRI6_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL1_DSCPTOPRI5_LSP  0u
#define DVA_DSCP_REMARKING_TABLE_CONTROL1_DSCPTOPRI5_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL1_DSCPTOPRI5_TYPE DVA_FIELD_TYPE_RW

#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI4_LSP  24u
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI4_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI4_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI3_LSP  18u
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI3_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI3_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI2_LSP  12u
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI2_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI2_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI1_LSP  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI1_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI1_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI0_LSP  0u
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI0_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL2_DSCPTOPRI0_TYPE DVA_FIELD_TYPE_RW

#define DVA_DSCP_REMARKING_TABLE_CONTROL3_DSCPTOPRI7_LSP  12u
#define DVA_DSCP_REMARKING_TABLE_CONTROL3_DSCPTOPRI7_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL3_DSCPTOPRI7_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL3_DSCPTOPRI6_LSP  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL3_DSCPTOPRI6_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL3_DSCPTOPRI6_TYPE DVA_FIELD_TYPE_RW
#define DVA_DSCP_REMARKING_TABLE_CONTROL3_DSCPTOPRI5_LSP  0u
#define DVA_DSCP_REMARKING_TABLE_CONTROL3_DSCPTOPRI5_LEN  6u
#define DVA_DSCP_REMARKING_TABLE_CONTROL3_DSCPTOPRI5_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT0_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT1_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT2_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT3_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT4_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT5_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT6_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT7_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT8_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT9_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT10_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT11_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT12_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT13_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT14_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_DSCPRMK_LSP        5u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_DSCPRMK_LEN        1u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_DSCPRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LSP  4u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_LEN  1u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_DSCPRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_OPRIRMK_LSP        3u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_OPRIRMK_LEN        1u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_OPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LSP  2u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_LEN  1u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_OPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_IPRIRMK_LSP        1u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_IPRIRMK_LEN        1u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_IPRIRMK_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LSP  0u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_LEN  1u
#define DVA_PORT15_PRIORITY_REMARKING_CONTROL_IPRIRMKTBLIDX_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LSP  0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_LEN  1u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_REMARKING_FUSA_PG_LOCK_DMY_REMARKING_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_REMARKING_H_ */