/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_VLAN_DECISION_H_
#define DVA_RTKAS_REG_FIELD_FILE_VLAN_DECISION_H_

#ifdef DVA_FILE_VLAN_DECISION
/* File: DVA_VLAN Decision */
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT0_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT1_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT2_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT3_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT4_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT5_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT6_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT7_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT8_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT9_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT10_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT11_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT12_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT13_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT14_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LSP  4u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_LEN  1u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTDOUBLETAG_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LSP       3u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_LEN       1u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTITAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LSP      2u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_LEN      1u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTIUTAG_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LSP       1u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_LEN       1u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTOTAG_TYPE      DVA_FIELD_TYPE_RW
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LSP      0u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_LEN      1u
#define DVA_PORT15_ACCEPT_FRAME_TYPE_CONTROL_ACPTOUTAG_TYPE     DVA_FIELD_TYPE_RW

#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT0_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT1_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT2_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT3_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT4_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT5_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT6_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT7_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT8_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT9_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT10_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT11_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT12_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT13_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT14_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LSP    3u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_LEN    1u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_KEEPOTAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LSP    2u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_LEN    1u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_KEEPITAGVID_TYPE   DVA_FIELD_TYPE_RW
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LSP  1u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_LEN  1u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_IGNOREOTAGVID_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LSP  0u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_LEN  1u
#define DVA_PORT15_IGNORE_VLAN_TAG_CONTROL_IGNOREITAGVID_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT0_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT1_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT2_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT3_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT4_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT5_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT6_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT7_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT8_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT9_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT10_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT11_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT12_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT13_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT14_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LSP  1u
#define DVA_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_LEN  1u
#define DVA_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL_INGRESSVLANRETAGGINGENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LSP   0u
#define DVA_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_LEN   1u
#define DVA_PORT15_PROPERTY_BASED_VLAN_RETAG_CONTROL_EGRESSVLANRETAGGINGENABLE_TYPE  DVA_FIELD_TYPE_RW

#define DVA_PORT0_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LSP  0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_LEN  1u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_VLAN_DECISION_FUSA_PG_LOCK_DMY_VLAN_DECISION_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_VLAN_DECISION_H_ */