/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_WOL_H_
#define DVA_RTKAS_REG_FIELD_FILE_WOL_H_

#ifdef DVA_FILE_WOL
/* File: WOL */
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT14_LSP  19u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT14_LEN  1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT14_TYPE DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT13_LSP  18u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT13_LEN  1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT13_TYPE DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT12_LSP  17u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT12_LEN  1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT12_TYPE DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT11_LSP  16u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT11_LEN  1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT11_TYPE DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT10_LSP  15u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT10_LEN  1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT10_TYPE DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT9_LSP   14u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT9_LEN   1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT9_TYPE  DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT8_LSP   13u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT8_LEN   1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT8_TYPE  DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT7_LSP   12u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT7_LEN   1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT7_TYPE  DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT6_LSP   11u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT6_LEN   1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT6_TYPE  DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT5_LSP   10u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT5_LEN   1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT5_TYPE  DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT4_LSP   9u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT4_LEN   1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT4_TYPE  DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT3_LSP   8u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT3_LEN   1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT3_TYPE  DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT2_LSP   7u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT2_LEN   1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT2_TYPE  DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT1_LSP   6u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT1_LEN   1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT1_TYPE  DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT0_LSP   5u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT0_LEN   1u
#define DVA_WOL_GLOBAL_CONTROL_WOLDETPORT0_TYPE  DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_LUEN_LSP          4u
#define DVA_WOL_GLOBAL_CONTROL_LUEN_LEN          1u
#define DVA_WOL_GLOBAL_CONTROL_LUEN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_GLOBAL_CONTROL_WSAM1_LSP         3u
#define DVA_WOL_GLOBAL_CONTROL_WSAM1_LEN         1u
#define DVA_WOL_GLOBAL_CONTROL_WSAM1_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_WOL_GLOBAL_CONTROL_WSAM0_LSP         2u
#define DVA_WOL_GLOBAL_CONTROL_WSAM0_LEN         1u
#define DVA_WOL_GLOBAL_CONTROL_WSAM0_TYPE        DVA_FIELD_TYPE_RWS
#define DVA_WOL_GLOBAL_CONTROL_WI_FLAG_LSP       1u
#define DVA_WOL_GLOBAL_CONTROL_WI_FLAG_LEN       1u
#define DVA_WOL_GLOBAL_CONTROL_WI_FLAG_TYPE      DVA_FIELD_TYPE_RW1C

#define DVA_WOL_CONTROL_WAKEUP_CPUEN14_LSP         30u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN14_LEN         1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN14_TYPE        DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN13_LSP         29u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN13_LEN         1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN13_TYPE        DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN12_LSP         28u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN12_LEN         1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN12_TYPE        DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN11_LSP         27u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN11_LEN         1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN11_TYPE        DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN10_LSP         26u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN10_LEN         1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN10_TYPE        DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN9_LSP          25u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN9_LEN          1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN9_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN8_LSP          24u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN8_LEN          1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN8_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN7_LSP          23u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN7_LEN          1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN7_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN6_LSP          22u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN6_LEN          1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN6_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN5_LSP          21u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN5_LEN          1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN5_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN4_LSP          20u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN4_LEN          1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN4_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN3_LSP          19u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN3_LEN          1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN3_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN2_LSP          18u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN2_LEN          1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN2_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN1_LSP          17u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN1_LEN          1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN1_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_WAKEUP_CPUEN0_LSP          16u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN0_LEN          1u
#define DVA_WOL_CONTROL_WAKEUP_CPUEN0_TYPE         DVA_FIELD_TYPE_RW
#define DVA_WOL_CONTROL_SW_WOL_PULSE_INTERVAL_LSP  9u
#define DVA_WOL_CONTROL_SW_WOL_PULSE_INTERVAL_LEN  2u
#define DVA_WOL_CONTROL_SW_WOL_PULSE_INTERVAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT0_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT0_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT0_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT0_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT0_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT0_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT0_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT0_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT0_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT0_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT0_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT0_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT0_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT0_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT0_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT0_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT1_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT1_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT1_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT1_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT1_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT1_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT1_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT1_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT1_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT1_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT1_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT1_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT1_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT1_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT1_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT1_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT1_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT2_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT2_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT2_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT2_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT2_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT2_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT2_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT2_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT2_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT2_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT2_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT2_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT2_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT2_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT2_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT2_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT2_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT3_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT3_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT3_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT3_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT3_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT3_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT3_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT3_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT3_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT3_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT3_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT3_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT3_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT3_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT3_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT3_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT3_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT4_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT4_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT4_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT4_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT4_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT4_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT4_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT4_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT4_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT4_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT4_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT4_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT4_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT4_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT4_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT4_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT4_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT5_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT5_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT5_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT5_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT5_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT5_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT5_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT5_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT5_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT5_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT5_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT5_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT5_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT5_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT5_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT5_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT5_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT6_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT6_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT6_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT6_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT6_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT6_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT6_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT6_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT6_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT6_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT6_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT6_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT6_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT6_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT6_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT6_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT6_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT7_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT7_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT7_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT7_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT7_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT7_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT7_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT7_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT7_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT7_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT7_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT7_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT7_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT7_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT7_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT7_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT7_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT8_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT8_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT8_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT8_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT8_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT8_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT8_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT8_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT8_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT8_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT8_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT8_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT8_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT8_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT8_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT8_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT8_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT9_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT9_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT9_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT9_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT9_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT9_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT9_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT9_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT9_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT9_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT9_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT9_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT9_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT9_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT9_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT9_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT9_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT10_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT10_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT10_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT10_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT10_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT10_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT10_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT10_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT10_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT10_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT10_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT10_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT10_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT10_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT10_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT10_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT10_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT11_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT11_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT11_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT11_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT11_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT11_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT11_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT11_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT11_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT11_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT11_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT11_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT11_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT11_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT11_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT11_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT11_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT12_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT12_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT12_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT12_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT12_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT12_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT12_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT12_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT12_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT12_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT12_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT12_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT12_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT12_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT12_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT12_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT12_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT13_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT13_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT13_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT13_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT13_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT13_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT13_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT13_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT13_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT13_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT13_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT13_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT13_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT13_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT13_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT13_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT13_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT14_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT14_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT14_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT14_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT14_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT14_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT14_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT14_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT14_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT14_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT14_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT14_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT14_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT14_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT14_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT14_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT14_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT15_WOL_CTRL_WAKEUP_CPUPKTEN_LSP  5u
#define DVA_PORT15_WOL_CTRL_WAKEUP_CPUPKTEN_LEN  1u
#define DVA_PORT15_WOL_CTRL_WAKEUP_CPUPKTEN_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_WOL_CTRL_FWD_MP_LSP           4u
#define DVA_PORT15_WOL_CTRL_FWD_MP_LEN           1u
#define DVA_PORT15_WOL_CTRL_FWD_MP_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT15_WOL_CTRL_FWD_WF_LSP           3u
#define DVA_PORT15_WOL_CTRL_FWD_WF_LEN           1u
#define DVA_PORT15_WOL_CTRL_FWD_WF_TYPE          DVA_FIELD_TYPE_RW
#define DVA_PORT15_WOL_CTRL_WOLEN_LSP            2u
#define DVA_PORT15_WOL_CTRL_WOLEN_LEN            1u
#define DVA_PORT15_WOL_CTRL_WOLEN_TYPE           DVA_FIELD_TYPE_RW
#define DVA_PORT15_WOL_CTRL_MPEN_LSP             1u
#define DVA_PORT15_WOL_CTRL_MPEN_LEN             1u
#define DVA_PORT15_WOL_CTRL_MPEN_TYPE            DVA_FIELD_TYPE_RW
#define DVA_PORT15_WOL_CTRL_WFEN_LSP             0u
#define DVA_PORT15_WOL_CTRL_WFEN_LEN             1u
#define DVA_PORT15_WOL_CTRL_WFEN_TYPE            DVA_FIELD_TYPE_RW

#define DVA_PORT0_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT0_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT0_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT0_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT0_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT0_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT0_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT0_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT0_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT1_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT1_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT1_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT1_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT1_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT1_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT1_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT1_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT2_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT2_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT2_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT2_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT2_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT2_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT2_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT2_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT3_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT3_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT3_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT3_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT3_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT3_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT3_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT3_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT4_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT4_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT4_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT4_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT4_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT4_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT4_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT4_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT5_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT5_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT5_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT5_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT5_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT5_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT5_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT5_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT6_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT6_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT6_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT6_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT6_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT6_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT6_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT6_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT7_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT7_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT7_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT7_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT7_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT7_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT7_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT7_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT8_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT8_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT8_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT8_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT8_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT8_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT8_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT8_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT9_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT9_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT9_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT9_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT9_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT9_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT9_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT9_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT10_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT10_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT10_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT10_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT10_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT10_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT10_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT10_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT11_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT11_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT11_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT11_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT11_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT11_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT11_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT11_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT12_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT12_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT12_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT12_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT12_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT12_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT12_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT12_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT13_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT13_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT13_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT13_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT13_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT13_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT13_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT13_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT14_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT14_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT14_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT14_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT14_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT14_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT14_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT14_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_WPF_CRC_MATCH0_HSBCRC1_LSP  24u
#define DVA_PORT15_WPF_CRC_MATCH0_HSBCRC1_LEN  8u
#define DVA_PORT15_WPF_CRC_MATCH0_HSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_WPF_CRC_MATCH0_LSBCRC1_LSP  16u
#define DVA_PORT15_WPF_CRC_MATCH0_LSBCRC1_LEN  8u
#define DVA_PORT15_WPF_CRC_MATCH0_LSBCRC1_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_WPF_CRC_MATCH0_HSBCRC0_LSP  8u
#define DVA_PORT15_WPF_CRC_MATCH0_HSBCRC0_LEN  8u
#define DVA_PORT15_WPF_CRC_MATCH0_HSBCRC0_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_WPF_CRC_MATCH0_LSBCRC0_LSP  0u
#define DVA_PORT15_WPF_CRC_MATCH0_LSBCRC0_LEN  8u
#define DVA_PORT15_WPF_CRC_MATCH0_LSBCRC0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT0_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT0_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT1_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT1_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT2_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT2_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT3_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT3_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT4_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT4_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT5_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT5_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT6_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT6_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT7_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT7_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT8_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT8_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT9_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT9_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT10_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT10_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT11_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT11_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT12_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT12_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT13_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT13_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT14_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT14_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LSP  0u
#define DVA_PORT15_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_LEN  32u
#define DVA_PORT15_WAKEUP_FRAME_MASK0_0_WAKEUPMASK0_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT0_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT0_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT1_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT1_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT2_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT2_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT3_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT3_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT4_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT4_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT5_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT5_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT6_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT6_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT7_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT7_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT8_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT8_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT9_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT9_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT10_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT10_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT11_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT11_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT12_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT12_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT13_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT13_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT14_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT14_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LSP  0u
#define DVA_PORT15_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_LEN  32u
#define DVA_PORT15_WAKEUP_FRAME_MASK0_1_WAKEUPMASK0_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT0_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT0_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT1_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT1_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT2_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT2_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT3_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT3_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT4_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT4_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT5_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT5_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT6_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT6_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT7_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT7_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT8_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT8_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT9_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT9_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT10_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT10_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT11_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT11_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT12_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT12_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT13_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT13_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT14_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT14_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LSP  0u
#define DVA_PORT15_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_LEN  32u
#define DVA_PORT15_WAKEUP_FRAME_MASK0_2_WAKEUPMASK0_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT0_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT0_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT1_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT1_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT2_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT2_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT3_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT3_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT4_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT4_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT5_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT5_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT6_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT6_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT7_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT7_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT8_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT8_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT9_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT9_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT10_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT10_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT11_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT11_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT12_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT12_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT13_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT13_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT14_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT14_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LSP  0u
#define DVA_PORT15_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_LEN  32u
#define DVA_PORT15_WAKEUP_FRAME_MASK0_3_WAKEUPMASK0_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT0_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT0_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT1_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT1_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT2_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT2_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT3_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT3_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT4_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT4_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT5_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT5_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT6_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT6_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT7_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT7_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT8_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT8_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT9_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT9_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT10_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT10_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT11_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT11_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT12_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT12_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT13_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT13_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT14_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT14_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LSP  0u
#define DVA_PORT15_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_LEN  32u
#define DVA_PORT15_WAKEUP_FRAME_MASK1_0_WAKEUPMASK1_127_96_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT0_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT0_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT1_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT1_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT2_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT2_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT3_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT3_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT4_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT4_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT5_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT5_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT6_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT6_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT7_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT7_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT8_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT8_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT9_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT9_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT10_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT10_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT11_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT11_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT12_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT12_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT13_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT13_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT14_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT14_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LSP  0u
#define DVA_PORT15_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_LEN  32u
#define DVA_PORT15_WAKEUP_FRAME_MASK1_1_WAKEUPMASK1_95_64_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT0_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT0_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT1_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT1_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT2_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT2_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT3_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT3_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT4_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT4_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT5_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT5_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT6_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT6_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT7_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT7_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT8_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT8_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT9_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT9_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT10_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT10_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT11_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT11_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT12_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT12_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT13_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT13_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT14_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT14_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LSP  0u
#define DVA_PORT15_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_LEN  32u
#define DVA_PORT15_WAKEUP_FRAME_MASK1_2_WAKEUPMASK1_63_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT0_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT0_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT1_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT1_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT2_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT2_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT3_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT3_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT4_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT4_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT5_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT5_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT6_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT6_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT7_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT7_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT8_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT8_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT9_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT9_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT10_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT10_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT11_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT11_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT12_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT12_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT13_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT13_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT14_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT14_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LSP  0u
#define DVA_PORT15_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_LEN  32u
#define DVA_PORT15_WAKEUP_FRAME_MASK1_3_WAKEUPMASK1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT0_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT0_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT1_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT1_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT2_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT2_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT3_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT3_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT4_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT4_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT5_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT5_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT6_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT6_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT7_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT7_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT8_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT8_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT9_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT9_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT10_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT10_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT11_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT11_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT12_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT12_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT13_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT13_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT14_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT14_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_LSB_NODE_ID_1_NODEID1_31_0_LSP  0u
#define DVA_PORT15_LSB_NODE_ID_1_NODEID1_31_0_LEN  32u
#define DVA_PORT15_LSB_NODE_ID_1_NODEID1_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT0_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT0_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT0_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT0_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT0_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT1_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT1_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT1_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT1_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT1_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT2_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT2_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT2_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT2_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT2_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT3_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT3_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT3_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT3_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT3_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT4_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT4_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT4_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT4_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT4_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT5_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT5_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT5_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT5_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT5_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT6_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT6_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT6_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT6_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT6_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT7_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT7_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT7_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT7_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT7_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT8_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT8_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT8_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT8_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT8_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT9_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT9_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT9_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT9_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT9_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT10_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT10_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT10_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT10_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT10_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT11_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT11_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT11_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT11_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT11_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT12_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT12_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT12_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT12_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT12_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT13_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT13_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT13_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT13_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT13_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT14_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT14_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT14_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT14_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT14_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_HSB_NODE_ID_1_NODEID1EN_LSP      16u
#define DVA_PORT15_HSB_NODE_ID_1_NODEID1EN_LEN      1u
#define DVA_PORT15_HSB_NODE_ID_1_NODEID1EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT15_HSB_NODE_ID_1_NODEID1_47_32_LSP  0u
#define DVA_PORT15_HSB_NODE_ID_1_NODEID1_47_32_LEN  16u
#define DVA_PORT15_HSB_NODE_ID_1_NODEID1_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT0_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT0_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT1_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT1_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT2_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT2_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT3_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT3_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT4_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT4_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT5_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT5_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT6_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT6_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT7_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT7_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT8_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT8_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT9_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT9_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT10_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT10_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT11_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT11_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT12_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT12_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT13_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT13_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT14_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT14_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_LSB_NODE_ID_2_NODEID2_31_0_LSP  0u
#define DVA_PORT15_LSB_NODE_ID_2_NODEID2_31_0_LEN  32u
#define DVA_PORT15_LSB_NODE_ID_2_NODEID2_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT0_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT0_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT0_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT0_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT0_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT1_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT1_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT1_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT1_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT1_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT2_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT2_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT2_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT2_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT2_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT3_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT3_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT3_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT3_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT3_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT4_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT4_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT4_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT4_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT4_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT5_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT5_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT5_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT5_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT5_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT6_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT6_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT6_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT6_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT6_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT7_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT7_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT7_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT7_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT7_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT8_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT8_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT8_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT8_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT8_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT9_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT9_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT9_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT9_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT9_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT10_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT10_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT10_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT10_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT10_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT11_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT11_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT11_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT11_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT11_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT12_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT12_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT12_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT12_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT12_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT13_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT13_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT13_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT13_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT13_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT14_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT14_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT14_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT14_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT14_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_HSB_NODE_ID_2_NODEID2EN_LSP      16u
#define DVA_PORT15_HSB_NODE_ID_2_NODEID2EN_LEN      1u
#define DVA_PORT15_HSB_NODE_ID_2_NODEID2EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT15_HSB_NODE_ID_2_NODEID2_47_32_LSP  0u
#define DVA_PORT15_HSB_NODE_ID_2_NODEID2_47_32_LEN  16u
#define DVA_PORT15_HSB_NODE_ID_2_NODEID2_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT0_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT0_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT1_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT1_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT2_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT2_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT3_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT3_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT4_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT4_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT5_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT5_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT6_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT6_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT7_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT7_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT8_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT8_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT9_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT9_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT10_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT10_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT11_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT11_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT12_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT12_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT13_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT13_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT14_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT14_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_LSB_NODE_ID_3_NODEID3_31_0_LSP  0u
#define DVA_PORT15_LSB_NODE_ID_3_NODEID3_31_0_LEN  32u
#define DVA_PORT15_LSB_NODE_ID_3_NODEID3_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT0_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT0_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT0_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT0_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT0_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT1_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT1_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT1_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT1_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT1_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT2_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT2_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT2_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT2_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT2_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT3_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT3_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT3_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT3_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT3_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT4_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT4_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT4_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT4_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT4_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT5_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT5_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT5_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT5_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT5_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT6_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT6_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT6_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT6_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT6_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT7_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT7_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT7_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT7_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT7_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT8_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT8_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT8_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT8_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT8_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT9_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT9_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT9_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT9_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT9_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT10_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT10_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT10_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT10_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT10_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT11_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT11_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT11_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT11_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT11_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT12_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT12_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT12_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT12_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT12_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT13_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT13_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT13_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT13_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT13_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT14_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT14_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT14_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT14_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT14_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_HSB_NODE_ID_3_NODEID3EN_LSP      16u
#define DVA_PORT15_HSB_NODE_ID_3_NODEID3EN_LEN      1u
#define DVA_PORT15_HSB_NODE_ID_3_NODEID3EN_TYPE     DVA_FIELD_TYPE_RW
#define DVA_PORT15_HSB_NODE_ID_3_NODEID3_47_32_LSP  0u
#define DVA_PORT15_HSB_NODE_ID_3_NODEID3_47_32_LEN  16u
#define DVA_PORT15_HSB_NODE_ID_3_NODEID3_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LSP  0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_LEN  1u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_WOL_FUSA_PG_LOCK_DMY_WOL_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_WOL_H_ */