/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_UART_H_
#define DVA_RTKAS_REG_FIELD_FILE_UART_H_

#ifdef DVA_FILE_UART
/* File: UART */
#define DVA_DAT0_UART_DATA_DAT0_UART_DATA_LSP  0u
#define DVA_DAT0_UART_DATA_DAT0_UART_DATA_LEN  8u
#define DVA_DAT0_UART_DATA_DAT0_UART_DATA_TYPE DVA_FIELD_TYPE_RW

#define DVA_DAT0_UART_IER_DAT0_CHAR_TIMEOUT_IE_LSP  4u
#define DVA_DAT0_UART_IER_DAT0_CHAR_TIMEOUT_IE_LEN  1u
#define DVA_DAT0_UART_IER_DAT0_CHAR_TIMEOUT_IE_TYPE DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_IER_DAT0_MDM_STS_IE_LSP       3u
#define DVA_DAT0_UART_IER_DAT0_MDM_STS_IE_LEN       1u
#define DVA_DAT0_UART_IER_DAT0_MDM_STS_IE_TYPE      DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_IER_DAT0_RX_LINESTS_IE_LSP    2u
#define DVA_DAT0_UART_IER_DAT0_RX_LINESTS_IE_LEN    1u
#define DVA_DAT0_UART_IER_DAT0_RX_LINESTS_IE_TYPE   DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_IER_DAT0_THR_EMPTY_IE_LSP     1u
#define DVA_DAT0_UART_IER_DAT0_THR_EMPTY_IE_LEN     1u
#define DVA_DAT0_UART_IER_DAT0_THR_EMPTY_IE_TYPE    DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_IER_DAT0_DATA_RDY_IE_LSP      0u
#define DVA_DAT0_UART_IER_DAT0_DATA_RDY_IE_LEN      1u
#define DVA_DAT0_UART_IER_DAT0_DATA_RDY_IE_TYPE     DVA_FIELD_TYPE_RW

#define DVA_DAT0_UART_FCR_DAT0_RXFIFO_TRGLVL_LSP  6u
#define DVA_DAT0_UART_FCR_DAT0_RXFIFO_TRGLVL_LEN  2u
#define DVA_DAT0_UART_FCR_DAT0_RXFIFO_TRGLVL_TYPE DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_FCR_DAT0_EN_AUTO_CTS_LSP    5u
#define DVA_DAT0_UART_FCR_DAT0_EN_AUTO_CTS_LEN    1u
#define DVA_DAT0_UART_FCR_DAT0_EN_AUTO_CTS_TYPE   DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_FCR_DAT0_EN_AUTO_RTS_LSP    4u
#define DVA_DAT0_UART_FCR_DAT0_EN_AUTO_RTS_LEN    1u
#define DVA_DAT0_UART_FCR_DAT0_EN_AUTO_RTS_TYPE   DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_FCR_DAT0_DMA_MODE_LSP       3u
#define DVA_DAT0_UART_FCR_DAT0_DMA_MODE_LEN       1u
#define DVA_DAT0_UART_FCR_DAT0_DMA_MODE_TYPE      DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_FCR_DAT0_TXFIFO_RST_LSP     2u
#define DVA_DAT0_UART_FCR_DAT0_TXFIFO_RST_LEN     1u
#define DVA_DAT0_UART_FCR_DAT0_TXFIFO_RST_TYPE    DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_FCR_DAT0_RXFIFO_RST_LSP     1u
#define DVA_DAT0_UART_FCR_DAT0_RXFIFO_RST_LEN     1u
#define DVA_DAT0_UART_FCR_DAT0_RXFIFO_RST_TYPE    DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_FCR_DAT0_FIFO_EN_LSP        0u
#define DVA_DAT0_UART_FCR_DAT0_FIFO_EN_LEN        1u
#define DVA_DAT0_UART_FCR_DAT0_FIFO_EN_TYPE       DVA_FIELD_TYPE_RW

#define DVA_DAT0_UART_LCR_DAT0_DLAB_LSP          7u
#define DVA_DAT0_UART_LCR_DAT0_DLAB_LEN          1u
#define DVA_DAT0_UART_LCR_DAT0_DLAB_TYPE         DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_LCR_DAT0_SET_BREAK_LSP     6u
#define DVA_DAT0_UART_LCR_DAT0_SET_BREAK_LEN     1u
#define DVA_DAT0_UART_LCR_DAT0_SET_BREAK_TYPE    DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_LCR_DAT0_FORCE_PARITY_LSP  5u
#define DVA_DAT0_UART_LCR_DAT0_FORCE_PARITY_LEN  1u
#define DVA_DAT0_UART_LCR_DAT0_FORCE_PARITY_TYPE DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_LCR_DAT0_EVEN_PARITY_LSP   4u
#define DVA_DAT0_UART_LCR_DAT0_EVEN_PARITY_LEN   1u
#define DVA_DAT0_UART_LCR_DAT0_EVEN_PARITY_TYPE  DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_LCR_DAT0_PARITY_EN_LSP     3u
#define DVA_DAT0_UART_LCR_DAT0_PARITY_EN_LEN     1u
#define DVA_DAT0_UART_LCR_DAT0_PARITY_EN_TYPE    DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_LCR_DAT0_STOP_BIT_LSP      2u
#define DVA_DAT0_UART_LCR_DAT0_STOP_BIT_LEN      1u
#define DVA_DAT0_UART_LCR_DAT0_STOP_BIT_TYPE     DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_LCR_DAT0_WORD_LEN_LSP      0u
#define DVA_DAT0_UART_LCR_DAT0_WORD_LEN_LEN      2u
#define DVA_DAT0_UART_LCR_DAT0_WORD_LEN_TYPE     DVA_FIELD_TYPE_RW

#define DVA_DAT0_UART_MCR_DAT0_LOOP_BACK_LSP  4u
#define DVA_DAT0_UART_MCR_DAT0_LOOP_BACK_LEN  1u
#define DVA_DAT0_UART_MCR_DAT0_LOOP_BACK_TYPE DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_MCR_DAT0_OUT_2_LSP      3u
#define DVA_DAT0_UART_MCR_DAT0_OUT_2_LEN      1u
#define DVA_DAT0_UART_MCR_DAT0_OUT_2_TYPE     DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_MCR_DAT0_OUT_1_LSP      2u
#define DVA_DAT0_UART_MCR_DAT0_OUT_1_LEN      1u
#define DVA_DAT0_UART_MCR_DAT0_OUT_1_TYPE     DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_MCR_DAT0_RTS_LSP        1u
#define DVA_DAT0_UART_MCR_DAT0_RTS_LEN        1u
#define DVA_DAT0_UART_MCR_DAT0_RTS_TYPE       DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_MCR_DAT0_DTR_LSP        0u
#define DVA_DAT0_UART_MCR_DAT0_DTR_LEN        1u
#define DVA_DAT0_UART_MCR_DAT0_DTR_TYPE       DVA_FIELD_TYPE_RW

#define DVA_DAT0_UART_LSR_DAT0_FIFODATA_ERR_LSP  7u
#define DVA_DAT0_UART_LSR_DAT0_FIFODATA_ERR_LEN  1u
#define DVA_DAT0_UART_LSR_DAT0_FIFODATA_ERR_TYPE DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_LSR_DAT0_TX_EMPTY_LSP      6u
#define DVA_DAT0_UART_LSR_DAT0_TX_EMPTY_LEN      1u
#define DVA_DAT0_UART_LSR_DAT0_TX_EMPTY_TYPE     DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_LSR_DAT0_THR_EMPTY_LSP     5u
#define DVA_DAT0_UART_LSR_DAT0_THR_EMPTY_LEN     1u
#define DVA_DAT0_UART_LSR_DAT0_THR_EMPTY_TYPE    DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_LSR_DAT0_BREAK_INT_LSP     4u
#define DVA_DAT0_UART_LSR_DAT0_BREAK_INT_LEN     1u
#define DVA_DAT0_UART_LSR_DAT0_BREAK_INT_TYPE    DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_LSR_DAT0_FRAMING_ERR_LSP   3u
#define DVA_DAT0_UART_LSR_DAT0_FRAMING_ERR_LEN   1u
#define DVA_DAT0_UART_LSR_DAT0_FRAMING_ERR_TYPE  DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_LSR_DAT0_PARITY_ERR_LSP    2u
#define DVA_DAT0_UART_LSR_DAT0_PARITY_ERR_LEN    1u
#define DVA_DAT0_UART_LSR_DAT0_PARITY_ERR_TYPE   DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_LSR_DAT0_OVERRUN_ERR_LSP   1u
#define DVA_DAT0_UART_LSR_DAT0_OVERRUN_ERR_LEN   1u
#define DVA_DAT0_UART_LSR_DAT0_OVERRUN_ERR_TYPE  DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_LSR_DAT0_DATA_RDY_LSP      0u
#define DVA_DAT0_UART_LSR_DAT0_DATA_RDY_LEN      1u
#define DVA_DAT0_UART_LSR_DAT0_DATA_RDY_TYPE     DVA_FIELD_TYPE_RO

#define DVA_DAT0_UART_MSR_DAT0_CD_LSP            7u
#define DVA_DAT0_UART_MSR_DAT0_CD_LEN            1u
#define DVA_DAT0_UART_MSR_DAT0_CD_TYPE           DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_MSR_DAT0_RI_LSP            6u
#define DVA_DAT0_UART_MSR_DAT0_RI_LEN            1u
#define DVA_DAT0_UART_MSR_DAT0_RI_TYPE           DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_MSR_DAT0_DSR_LSP           5u
#define DVA_DAT0_UART_MSR_DAT0_DSR_LEN           1u
#define DVA_DAT0_UART_MSR_DAT0_DSR_TYPE          DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_MSR_DAT0_CTS_LSP           4u
#define DVA_DAT0_UART_MSR_DAT0_CTS_LEN           1u
#define DVA_DAT0_UART_MSR_DAT0_CTS_TYPE          DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_MSR_DAT0_DELTA_CD_LSP      3u
#define DVA_DAT0_UART_MSR_DAT0_DELTA_CD_LEN      1u
#define DVA_DAT0_UART_MSR_DAT0_DELTA_CD_TYPE     DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_MSR_DAT0_TRAILEDGE_RI_LSP  2u
#define DVA_DAT0_UART_MSR_DAT0_TRAILEDGE_RI_LEN  1u
#define DVA_DAT0_UART_MSR_DAT0_TRAILEDGE_RI_TYPE DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_MSR_DAT0_DELTA_DSR_LSP     1u
#define DVA_DAT0_UART_MSR_DAT0_DELTA_DSR_LEN     1u
#define DVA_DAT0_UART_MSR_DAT0_DELTA_DSR_TYPE    DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_MSR_DAT0_DELTA_CTS_LSP     0u
#define DVA_DAT0_UART_MSR_DAT0_DELTA_CTS_LEN     1u
#define DVA_DAT0_UART_MSR_DAT0_DELTA_CTS_TYPE    DVA_FIELD_TYPE_RO

#define DVA_DAT0_UART_SPR_DAT0_BRDC_DIV_LSP  0u
#define DVA_DAT0_UART_SPR_DAT0_BRDC_DIV_LEN  16u
#define DVA_DAT0_UART_SPR_DAT0_BRDC_DIV_TYPE DVA_FIELD_TYPE_RW

#define DVA_DAT0_UART_RTHR_DAT0_RTHR_H_LSP  4u
#define DVA_DAT0_UART_RTHR_DAT0_RTHR_H_LEN  4u
#define DVA_DAT0_UART_RTHR_DAT0_RTHR_H_TYPE DVA_FIELD_TYPE_RW
#define DVA_DAT0_UART_RTHR_DAT0_RTHR_L_LSP  0u
#define DVA_DAT0_UART_RTHR_DAT0_RTHR_L_LEN  4u
#define DVA_DAT0_UART_RTHR_DAT0_RTHR_L_TYPE DVA_FIELD_TYPE_RW

#define DVA_DAT0_UART_ISR_DAT0_FIFOS_ENABLED_LSP  6u
#define DVA_DAT0_UART_ISR_DAT0_FIFOS_ENABLED_LEN  2u
#define DVA_DAT0_UART_ISR_DAT0_FIFOS_ENABLED_TYPE DVA_FIELD_TYPE_RO
#define DVA_DAT0_UART_ISR_DAT0_INT_IDCODE_LSP     0u
#define DVA_DAT0_UART_ISR_DAT0_INT_IDCODE_LEN     4u
#define DVA_DAT0_UART_ISR_DAT0_INT_IDCODE_TYPE    DVA_FIELD_TYPE_RO

#define DVA_FUSA_PG_LOCK_DMY_UART_FUSA_PG_LOCK_DMY_UART_LSP  0u
#define DVA_FUSA_PG_LOCK_DMY_UART_FUSA_PG_LOCK_DMY_UART_LEN  1u
#define DVA_FUSA_PG_LOCK_DMY_UART_FUSA_PG_LOCK_DMY_UART_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_UART_H_ */