/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_ADDR_TABLE_LOOKUP_H_
#define DVA_RTKAS_REG_FIELD_FILE_ADDR_TABLE_LOOKUP_H_

#ifdef DVA_FILE_ADDR_TABLE_LOOKUP
/* File: Address Table Lookup */
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_LMPRI_LSP      29u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_LMPRI_LEN      3u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_LMPRI_TYPE     DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_DFLMPRI_LSP    28u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_DFLMPRI_LEN    1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_DFLMPRI_TYPE   DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_DFIPMCPRI_LSP  8u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_DFIPMCPRI_LEN  1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_DFIPMCPRI_TYPE DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_IPMCPRI_LSP    5u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_IPMCPRI_LEN    3u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_IPMCPRI_TYPE   DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_L2MCIPMC_LSP   3u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_L2MCIPMC_LEN   2u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_L2MCIPMC_TYPE  DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_L2UCIPMC_LSP   1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_L2UCIPMC_LEN   2u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_L2UCIPMC_TYPE  DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_IPMC_LSP       0u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_IPMC_LEN       1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL0_IPMC_TYPE      DVA_FIELD_TYPE_RW

#define DVA_ADDRESS_TABLE_LOOKUP_IPMC_CPUMASK_IPMCCPUMSK_LSP  0u
#define DVA_ADDRESS_TABLE_LOOKUP_IPMC_CPUMASK_IPMCCPUMSK_LEN  16u
#define DVA_ADDRESS_TABLE_LOOKUP_IPMC_CPUMASK_IPMCCPUMSK_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_INVALID_SA_DETECT_EN_LSP  5u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_INVALID_SA_DETECT_EN_LEN  1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_INVALID_SA_DETECT_EN_TYPE DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_BCAM_EN_LSP               4u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_BCAM_EN_LEN               1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_BCAM_EN_TYPE              DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_GRPVLEAKY_LSP             3u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_GRPVLEAKY_LEN             1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_GRPVLEAKY_TYPE            DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_GROUPTABLEEN_LSP          2u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_GROUPTABLEEN_LEN          1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_GROUPTABLEEN_TYPE         DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_STATICVLKY_LSP            1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_STATICVLKY_LEN            1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_STATICVLKY_TYPE           DVA_FIELD_TYPE_RW
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_HASHALG_LSP               0u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_HASHALG_LEN               1u
#define DVA_ADDRESS_TABLE_LOOKUP_CONTROL1_HASHALG_TYPE              DVA_FIELD_TYPE_RW

#define DVA_SOURCE_MAC_LEARNING_ENABLE_CONTROL_SRCLEARNEN_LSP  0u
#define DVA_SOURCE_MAC_LEARNING_ENABLE_CONTROL_SRCLEARNEN_LEN  16u
#define DVA_SOURCE_MAC_LEARNING_ENABLE_CONTROL_SRCLEARNEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDRESS_TABLE_LOOKUP_MISS_CONTROL1_LKMISSCPUMSK_LSP  0u
#define DVA_ADDRESS_TABLE_LOOKUP_MISS_CONTROL1_LKMISSCPUMSK_LEN  16u
#define DVA_ADDRESS_TABLE_LOOKUP_MISS_CONTROL1_LKMISSCPUMSK_TYPE DVA_FIELD_TYPE_RW

#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL0_PRIORITY_0_FLOODING_PORT_MASK_LSP  0u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL0_PRIORITY_0_FLOODING_PORT_MASK_LEN  16u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL0_PRIORITY_0_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL1_PRIORITY_1_FLOODING_PORT_MASK_LSP  0u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL1_PRIORITY_1_FLOODING_PORT_MASK_LEN  16u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL1_PRIORITY_1_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL2_PRIORITY_2_FLOODING_PORT_MASK_LSP  0u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL2_PRIORITY_2_FLOODING_PORT_MASK_LEN  16u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL2_PRIORITY_2_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL3_PRIORITY_3_FLOODING_PORT_MASK_LSP  0u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL3_PRIORITY_3_FLOODING_PORT_MASK_LEN  16u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL3_PRIORITY_3_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL4_PRIORITY_4_FLOODING_PORT_MASK_LSP  0u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL4_PRIORITY_4_FLOODING_PORT_MASK_LEN  16u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL4_PRIORITY_4_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL5_PRIORITY_5_FLOODING_PORT_MASK_LSP  0u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL5_PRIORITY_5_FLOODING_PORT_MASK_LEN  16u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL5_PRIORITY_5_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL6_PRIORITY_6_FLOODING_PORT_MASK_LSP  0u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL6_PRIORITY_6_FLOODING_PORT_MASK_LEN  16u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL6_PRIORITY_6_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL7_PRIORITY_7_FLOODING_PORT_MASK_LSP  0u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL7_PRIORITY_7_FLOODING_PORT_MASK_LEN  16u
#define DVA_UNICAST_MISS_FLOOD_PROCESS_CONTROL7_PRIORITY_7_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL0_PRIORITY_0_FLOODING_PORT_MASK_LSP  0u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL0_PRIORITY_0_FLOODING_PORT_MASK_LEN  16u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL0_PRIORITY_0_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL1_PRIORITY_1_FLOODING_PORT_MASK_LSP  0u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL1_PRIORITY_1_FLOODING_PORT_MASK_LEN  16u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL1_PRIORITY_1_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL2_PRIORITY_2_FLOODING_PORT_MASK_LSP  0u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL2_PRIORITY_2_FLOODING_PORT_MASK_LEN  16u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL2_PRIORITY_2_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL3_PRIORITY_3_FLOODING_PORT_MASK_LSP  0u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL3_PRIORITY_3_FLOODING_PORT_MASK_LEN  16u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL3_PRIORITY_3_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL4_PRIORITY_4_FLOODING_PORT_MASK_LSP  0u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL4_PRIORITY_4_FLOODING_PORT_MASK_LEN  16u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL4_PRIORITY_4_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL5_PRIORITY_5_FLOODING_PORT_MASK_LSP  0u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL5_PRIORITY_5_FLOODING_PORT_MASK_LEN  16u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL5_PRIORITY_5_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL6_PRIORITY_6_FLOODING_PORT_MASK_LSP  0u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL6_PRIORITY_6_FLOODING_PORT_MASK_LEN  16u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL6_PRIORITY_6_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL7_PRIORITY_7_FLOODING_PORT_MASK_LSP  0u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL7_PRIORITY_7_FLOODING_PORT_MASK_LEN  16u
#define DVA_MULTICAST_MISS_FLOOD_PROCESS_CONTROL7_PRIORITY_7_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL0_PRIORITY_0_FLOODING_PORT_MASK_LSP  0u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL0_PRIORITY_0_FLOODING_PORT_MASK_LEN  16u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL0_PRIORITY_0_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL1_PRIORITY_1_FLOODING_PORT_MASK_LSP  0u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL1_PRIORITY_1_FLOODING_PORT_MASK_LEN  16u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL1_PRIORITY_1_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL2_PRIORITY_2_FLOODING_PORT_MASK_LSP  0u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL2_PRIORITY_2_FLOODING_PORT_MASK_LEN  16u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL2_PRIORITY_2_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL3_PRIORITY_3_FLOODING_PORT_MASK_LSP  0u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL3_PRIORITY_3_FLOODING_PORT_MASK_LEN  16u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL3_PRIORITY_3_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL4_PRIORITY_4_FLOODING_PORT_MASK_LSP  0u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL4_PRIORITY_4_FLOODING_PORT_MASK_LEN  16u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL4_PRIORITY_4_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL5_PRIORITY_5_FLOODING_PORT_MASK_LSP  0u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL5_PRIORITY_5_FLOODING_PORT_MASK_LEN  16u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL5_PRIORITY_5_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL6_PRIORITY_6_FLOODING_PORT_MASK_LSP  0u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL6_PRIORITY_6_FLOODING_PORT_MASK_LEN  16u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL6_PRIORITY_6_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL7_PRIORITY_7_FLOODING_PORT_MASK_LSP  0u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL7_PRIORITY_7_FLOODING_PORT_MASK_LEN  16u
#define DVA_BROADCAST_MISS_FLOOD_PROCESS_CONTROL7_PRIORITY_7_FLOODING_PORT_MASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDRESS_TABLE_MULTICAST_CONTROL0_RTPORTMASK_LSP  0u
#define DVA_ADDRESS_TABLE_MULTICAST_CONTROL0_RTPORTMASK_LEN  16u
#define DVA_ADDRESS_TABLE_MULTICAST_CONTROL0_RTPORTMASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_ADDRESS_TABLE_MULTICAST_CONTROL1_MULDISPORTMASK_LSP  0u
#define DVA_ADDRESS_TABLE_MULTICAST_CONTROL1_MULDISPORTMASK_LEN  16u
#define DVA_ADDRESS_TABLE_MULTICAST_CONTROL1_MULDISPORTMASK_TYPE DVA_FIELD_TYPE_RW

#define DVA_HASH_OVERFLOW_INTERRUPT_STATUS_OVERFLOW_THRESHOLD_LSP  0u
#define DVA_HASH_OVERFLOW_INTERRUPT_STATUS_OVERFLOW_THRESHOLD_LEN  8u
#define DVA_HASH_OVERFLOW_INTERRUPT_STATUS_OVERFLOW_THRESHOLD_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF7_BRD_EN_LSP  23u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF7_BRD_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF7_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF6_BRD_EN_LSP  22u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF6_BRD_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF6_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF5_BRD_EN_LSP  21u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF5_BRD_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF5_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF4_BRD_EN_LSP  20u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF4_BRD_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF4_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF3_BRD_EN_LSP  19u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF3_BRD_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF3_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF2_BRD_EN_LSP  18u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF2_BRD_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF2_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF1_BRD_EN_LSP  17u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF1_BRD_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF1_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_PF_BRD_EN_LSP   16u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_PF_BRD_EN_LEN   1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_PF_BRD_EN_TYPE  DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF7_MAR_EN_LSP  15u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF7_MAR_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF7_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF6_MAR_EN_LSP  14u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF6_MAR_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF6_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF5_MAR_EN_LSP  13u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF5_MAR_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF5_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF4_MAR_EN_LSP  12u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF4_MAR_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF4_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF3_MAR_EN_LSP  11u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF3_MAR_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF3_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF2_MAR_EN_LSP  10u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF2_MAR_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF2_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF1_MAR_EN_LSP  9u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF1_MAR_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF1_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_PF_MAR_EN_LSP   8u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_PF_MAR_EN_LEN   1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_PF_MAR_EN_TYPE  DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF7_LBK_EN_LSP  7u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF7_LBK_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF7_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF6_LBK_EN_LSP  6u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF6_LBK_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF6_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF5_LBK_EN_LSP  5u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF5_LBK_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF5_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF4_LBK_EN_LSP  4u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF4_LBK_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF4_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF3_LBK_EN_LSP  3u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF3_LBK_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF3_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF2_LBK_EN_LSP  2u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF2_LBK_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF2_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF1_LBK_EN_LSP  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF1_LBK_EN_LEN  1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_VF1_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_PF_LBK_EN_LSP   0u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_PF_LBK_EN_LEN   1u
#define DVA_P9_PCIE_LOOPBACK_CONTROL_P9_PF_LBK_EN_TYPE  DVA_FIELD_TYPE_RWS

#define DVA_P9_PCIE_LOOPBACK_PF_MACID0_P9_PFMACID_31_0_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_PF_MACID0_P9_PFMACID_31_0_LEN  32u
#define DVA_P9_PCIE_LOOPBACK_PF_MACID0_P9_PFMACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_PF_MACID1_P9_PFMACID_47_32_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_PF_MACID1_P9_PFMACID_47_32_LEN  16u
#define DVA_P9_PCIE_LOOPBACK_PF_MACID1_P9_PFMACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF1_MACID0_P9_VF1MACID_31_0_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF1_MACID0_P9_VF1MACID_31_0_LEN  32u
#define DVA_P9_PCIE_LOOPBACK_VF1_MACID0_P9_VF1MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF1_MACID1_P9_VF1MACID_47_32_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF1_MACID1_P9_VF1MACID_47_32_LEN  16u
#define DVA_P9_PCIE_LOOPBACK_VF1_MACID1_P9_VF1MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF2_MACID0_P9_VF2MACID_31_0_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF2_MACID0_P9_VF2MACID_31_0_LEN  32u
#define DVA_P9_PCIE_LOOPBACK_VF2_MACID0_P9_VF2MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF2_MACID1_P9_VF2MACID_47_32_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF2_MACID1_P9_VF2MACID_47_32_LEN  16u
#define DVA_P9_PCIE_LOOPBACK_VF2_MACID1_P9_VF2MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF3_MACID0_P9_VF3MACID_31_0_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF3_MACID0_P9_VF3MACID_31_0_LEN  32u
#define DVA_P9_PCIE_LOOPBACK_VF3_MACID0_P9_VF3MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF3_MACID1_P9_VF3MACID_47_32_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF3_MACID1_P9_VF3MACID_47_32_LEN  16u
#define DVA_P9_PCIE_LOOPBACK_VF3_MACID1_P9_VF3MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF4_MACID0_P9_VF4MACID_31_0_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF4_MACID0_P9_VF4MACID_31_0_LEN  32u
#define DVA_P9_PCIE_LOOPBACK_VF4_MACID0_P9_VF4MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF4_MACID1_P9_VF4MACID_47_32_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF4_MACID1_P9_VF4MACID_47_32_LEN  16u
#define DVA_P9_PCIE_LOOPBACK_VF4_MACID1_P9_VF4MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF5_MACID0_P9_VF5MACID_31_0_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF5_MACID0_P9_VF5MACID_31_0_LEN  32u
#define DVA_P9_PCIE_LOOPBACK_VF5_MACID0_P9_VF5MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF5_MACID1_P9_VF5MACID_47_32_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF5_MACID1_P9_VF5MACID_47_32_LEN  16u
#define DVA_P9_PCIE_LOOPBACK_VF5_MACID1_P9_VF5MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF6_MACID0_P9_VF6MACID_31_0_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF6_MACID0_P9_VF6MACID_31_0_LEN  32u
#define DVA_P9_PCIE_LOOPBACK_VF6_MACID0_P9_VF6MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF6_MACID1_P9_VF6MACID_47_32_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF6_MACID1_P9_VF6MACID_47_32_LEN  16u
#define DVA_P9_PCIE_LOOPBACK_VF6_MACID1_P9_VF6MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF7_MACID0_P9_VF7MACID_31_0_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF7_MACID0_P9_VF7MACID_31_0_LEN  32u
#define DVA_P9_PCIE_LOOPBACK_VF7_MACID0_P9_VF7MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P9_PCIE_LOOPBACK_VF7_MACID1_P9_VF7MACID_47_32_LSP  0u
#define DVA_P9_PCIE_LOOPBACK_VF7_MACID1_P9_VF7MACID_47_32_LEN  16u
#define DVA_P9_PCIE_LOOPBACK_VF7_MACID1_P9_VF7MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF7_BRD_EN_LSP  23u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF7_BRD_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF7_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF6_BRD_EN_LSP  22u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF6_BRD_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF6_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF5_BRD_EN_LSP  21u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF5_BRD_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF5_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF4_BRD_EN_LSP  20u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF4_BRD_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF4_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF3_BRD_EN_LSP  19u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF3_BRD_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF3_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF2_BRD_EN_LSP  18u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF2_BRD_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF2_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF1_BRD_EN_LSP  17u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF1_BRD_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF1_BRD_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_PF_BRD_EN_LSP   16u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_PF_BRD_EN_LEN   1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_PF_BRD_EN_TYPE  DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF7_MAR_EN_LSP  15u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF7_MAR_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF7_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF6_MAR_EN_LSP  14u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF6_MAR_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF6_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF5_MAR_EN_LSP  13u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF5_MAR_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF5_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF4_MAR_EN_LSP  12u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF4_MAR_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF4_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF3_MAR_EN_LSP  11u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF3_MAR_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF3_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF2_MAR_EN_LSP  10u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF2_MAR_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF2_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF1_MAR_EN_LSP  9u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF1_MAR_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF1_MAR_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_PF_MAR_EN_LSP   8u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_PF_MAR_EN_LEN   1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_PF_MAR_EN_TYPE  DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF7_LBK_EN_LSP  7u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF7_LBK_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF7_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF6_LBK_EN_LSP  6u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF6_LBK_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF6_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF5_LBK_EN_LSP  5u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF5_LBK_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF5_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF4_LBK_EN_LSP  4u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF4_LBK_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF4_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF3_LBK_EN_LSP  3u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF3_LBK_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF3_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF2_LBK_EN_LSP  2u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF2_LBK_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF2_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF1_LBK_EN_LSP  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF1_LBK_EN_LEN  1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_VF1_LBK_EN_TYPE DVA_FIELD_TYPE_RWS
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_PF_LBK_EN_LSP   0u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_PF_LBK_EN_LEN   1u
#define DVA_P11_PCIE_LOOPBACK_CONTROL_P11_PF_LBK_EN_TYPE  DVA_FIELD_TYPE_RWS

#define DVA_P11_PCIE_LOOPBACK_PF_MACID0_P11_PFMACID_31_0_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_PF_MACID0_P11_PFMACID_31_0_LEN  32u
#define DVA_P11_PCIE_LOOPBACK_PF_MACID0_P11_PFMACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_PF_MACID1_P11_PFMACID_47_32_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_PF_MACID1_P11_PFMACID_47_32_LEN  16u
#define DVA_P11_PCIE_LOOPBACK_PF_MACID1_P11_PFMACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF1_MACID0_P11_VF1MACID_31_0_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF1_MACID0_P11_VF1MACID_31_0_LEN  32u
#define DVA_P11_PCIE_LOOPBACK_VF1_MACID0_P11_VF1MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF1_MACID1_P11_VF1MACID_47_32_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF1_MACID1_P11_VF1MACID_47_32_LEN  16u
#define DVA_P11_PCIE_LOOPBACK_VF1_MACID1_P11_VF1MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF2_MACID0_P11_VF2MACID_31_0_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF2_MACID0_P11_VF2MACID_31_0_LEN  32u
#define DVA_P11_PCIE_LOOPBACK_VF2_MACID0_P11_VF2MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF2_MACID1_P11_VF2MACID_47_32_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF2_MACID1_P11_VF2MACID_47_32_LEN  16u
#define DVA_P11_PCIE_LOOPBACK_VF2_MACID1_P11_VF2MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF3_MACID0_P11_VF3MACID_31_0_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF3_MACID0_P11_VF3MACID_31_0_LEN  32u
#define DVA_P11_PCIE_LOOPBACK_VF3_MACID0_P11_VF3MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF3_MACID1_P11_VF3MACID_47_32_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF3_MACID1_P11_VF3MACID_47_32_LEN  16u
#define DVA_P11_PCIE_LOOPBACK_VF3_MACID1_P11_VF3MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF4_MACID0_P11_VF4MACID_31_0_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF4_MACID0_P11_VF4MACID_31_0_LEN  32u
#define DVA_P11_PCIE_LOOPBACK_VF4_MACID0_P11_VF4MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF4_MACID1_P11_VF4MACID_47_32_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF4_MACID1_P11_VF4MACID_47_32_LEN  16u
#define DVA_P11_PCIE_LOOPBACK_VF4_MACID1_P11_VF4MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF5_MACID0_P11_VF5MACID_31_0_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF5_MACID0_P11_VF5MACID_31_0_LEN  32u
#define DVA_P11_PCIE_LOOPBACK_VF5_MACID0_P11_VF5MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF5_MACID1_P11_VF5MACID_47_32_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF5_MACID1_P11_VF5MACID_47_32_LEN  16u
#define DVA_P11_PCIE_LOOPBACK_VF5_MACID1_P11_VF5MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF6_MACID0_P11_VF6MACID_31_0_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF6_MACID0_P11_VF6MACID_31_0_LEN  32u
#define DVA_P11_PCIE_LOOPBACK_VF6_MACID0_P11_VF6MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF6_MACID1_P11_VF6MACID_47_32_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF6_MACID1_P11_VF6MACID_47_32_LEN  16u
#define DVA_P11_PCIE_LOOPBACK_VF6_MACID1_P11_VF6MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF7_MACID0_P11_VF7MACID_31_0_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF7_MACID0_P11_VF7MACID_31_0_LEN  32u
#define DVA_P11_PCIE_LOOPBACK_VF7_MACID0_P11_VF7MACID_31_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_P11_PCIE_LOOPBACK_VF7_MACID1_P11_VF7MACID_47_32_LSP  0u
#define DVA_P11_PCIE_LOOPBACK_VF7_MACID1_P11_VF7MACID_47_32_LEN  16u
#define DVA_P11_PCIE_LOOPBACK_VF7_MACID1_P11_VF7MACID_47_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT0_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT0_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT1_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT1_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT2_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT2_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT3_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT3_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT4_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT4_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT5_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT5_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT6_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT6_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT7_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT7_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT8_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT8_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT9_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT9_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT10_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT10_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT11_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT11_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT12_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT12_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT13_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT13_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT14_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT14_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_SOURCE_PORT_FILTER_SPFT_LSP  0u
#define DVA_PORT15_SOURCE_PORT_FILTER_SPFT_LEN  1u
#define DVA_PORT15_SOURCE_PORT_FILTER_SPFT_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT0_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT1_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT2_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT3_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT4_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT5_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT6_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT7_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT8_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT9_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT10_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT11_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT12_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT13_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT14_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LSP  12u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_LEN  3u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_MISSOP_FPM_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LSP          10u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_LEN          2u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L3MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LSP          8u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_LEN          2u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2BMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LSP          6u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_LEN          2u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2MMISSOP_TYPE         DVA_FIELD_TYPE_RW
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LSP        4u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_LEN        2u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V4MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LSP        2u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_LEN        2u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_V6MCSLKMSOP_TYPE       DVA_FIELD_TYPE_RW
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LSP          0u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_LEN          2u
#define DVA_PORT15_ADDRESS_TABLE_LOOKUP_MISS_CONTROL_L2UMISSOP_TYPE         DVA_FIELD_TYPE_RW

#define DVA_PORT0_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LSP  0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_LEN  1u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_FUSA_PG_LOCK_DMY_ADDR_TABLE_LOOKUP_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_ADDR_TABLE_LOOKUP_H_ */