/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DVA_RTKAS_REG_FIELD_FILE_ACL_H_
#define DVA_RTKAS_REG_FIELD_FILE_ACL_H_

#ifdef DVA_FILE_ACL
/* File: ACL */
#define DVA_POLICER_TABLE_CONTROL_INCLPREIFG_LSP  0u
#define DVA_POLICER_TABLE_CONTROL_INCLPREIFG_LEN  1u
#define DVA_POLICER_TABLE_CONTROL_INCLPREIFG_TYPE DVA_FIELD_TYPE_RW

#define DVA_CRC_ERROR_FRAME_LOOKUP_CONTROL_CFIPIELK_LSP     1u
#define DVA_CRC_ERROR_FRAME_LOOKUP_CONTROL_CFIPIELK_LEN     1u
#define DVA_CRC_ERROR_FRAME_LOOKUP_CONTROL_CFIPIELK_TYPE    DVA_FIELD_TYPE_RW
#define DVA_CRC_ERROR_FRAME_LOOKUP_CONTROL_CRCERRPIELK_LSP  0u
#define DVA_CRC_ERROR_FRAME_LOOKUP_CONTROL_CRCERRPIELK_LEN  1u
#define DVA_CRC_ERROR_FRAME_LOOKUP_CONTROL_CRCERRPIELK_TYPE DVA_FIELD_TYPE_RW

#define DVA_IACL_LOOKUP_MISS_COUNTER_0_IACL_CNT_LSB_LSP  0u
#define DVA_IACL_LOOKUP_MISS_COUNTER_0_IACL_CNT_LSB_LEN  32u
#define DVA_IACL_LOOKUP_MISS_COUNTER_0_IACL_CNT_LSB_TYPE DVA_FIELD_TYPE_RWS

#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_LU_MISSTAB_EN_LSP  19u
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_LU_MISSTAB_EN_LEN  1u
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_LU_MISSTAB_EN_TYPE DVA_FIELD_TYPE_RW
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_MODE_LSP       18u
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_MODE_LEN       1u
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_MODE_TYPE      DVA_FIELD_TYPE_RW
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_WR_LSP         17u
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_WR_LEN         1u
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_WR_TYPE        DVA_FIELD_TYPE_RW1C
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_RD_LSP         16u
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_RD_LEN         1u
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_RD_TYPE        DVA_FIELD_TYPE_RW1C
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_MSB_LSP        0u
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_MSB_LEN        16u
#define DVA_IACL_LOOKUP_MISS_COUNTER_1_IACL_CNT_MSB_TYPE       DVA_FIELD_TYPE_RWS

#define DVA_IACL_ABNORMAL_TIME_SLOT_CONTROL_IACL_TIME_SLOT_ENABLE_LSP     31u
#define DVA_IACL_ABNORMAL_TIME_SLOT_CONTROL_IACL_TIME_SLOT_ENABLE_LEN     1u
#define DVA_IACL_ABNORMAL_TIME_SLOT_CONTROL_IACL_TIME_SLOT_ENABLE_TYPE    DVA_FIELD_TYPE_RW
#define DVA_IACL_ABNORMAL_TIME_SLOT_CONTROL_IACL_TIME_SLOT_CLEAR_LSP      30u
#define DVA_IACL_ABNORMAL_TIME_SLOT_CONTROL_IACL_TIME_SLOT_CLEAR_LEN      1u
#define DVA_IACL_ABNORMAL_TIME_SLOT_CONTROL_IACL_TIME_SLOT_CLEAR_TYPE     DVA_FIELD_TYPE_RW
#define DVA_IACL_ABNORMAL_TIME_SLOT_CONTROL_IACL_TIME_SLOT_THRESHOLD_LSP  0u
#define DVA_IACL_ABNORMAL_TIME_SLOT_CONTROL_IACL_TIME_SLOT_THRESHOLD_LEN  20u
#define DVA_IACL_ABNORMAL_TIME_SLOT_CONTROL_IACL_TIME_SLOT_THRESHOLD_TYPE DVA_FIELD_TYPE_RW

#define DVA_IACL_ABNORMAL_DETECTION_CONTROL_IACL_ABNORMAL_DPM_LSP  0u
#define DVA_IACL_ABNORMAL_DETECTION_CONTROL_IACL_ABNORMAL_DPM_LEN  16u
#define DVA_IACL_ABNORMAL_DETECTION_CONTROL_IACL_ABNORMAL_DPM_TYPE DVA_FIELD_TYPE_RW

#define DVA_EACL_LOOKUP_MISS_COUNTER_0_EACL_CNT_LSB_LSP  0u
#define DVA_EACL_LOOKUP_MISS_COUNTER_0_EACL_CNT_LSB_LEN  32u
#define DVA_EACL_LOOKUP_MISS_COUNTER_0_EACL_CNT_LSB_TYPE DVA_FIELD_TYPE_RWS

#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_LU_MISSTAB_EN_LSP  19u
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_LU_MISSTAB_EN_LEN  1u
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_LU_MISSTAB_EN_TYPE DVA_FIELD_TYPE_RW
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_MODE_LSP       18u
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_MODE_LEN       1u
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_MODE_TYPE      DVA_FIELD_TYPE_RW
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_WR_LSP         17u
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_WR_LEN         1u
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_WR_TYPE        DVA_FIELD_TYPE_RW1C
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_RD_LSP         16u
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_RD_LEN         1u
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_RD_TYPE        DVA_FIELD_TYPE_RW1C
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_MSB_LSP        0u
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_MSB_LEN        16u
#define DVA_EACL_LOOKUP_MISS_COUNTER_1_EACL_CNT_MSB_TYPE       DVA_FIELD_TYPE_RWS

#define DVA_EACL_ABNORMAL_TIME_SLOT_CONTROL_EACL_TIME_SLOT_ENABLE_LSP     31u
#define DVA_EACL_ABNORMAL_TIME_SLOT_CONTROL_EACL_TIME_SLOT_ENABLE_LEN     1u
#define DVA_EACL_ABNORMAL_TIME_SLOT_CONTROL_EACL_TIME_SLOT_ENABLE_TYPE    DVA_FIELD_TYPE_RW
#define DVA_EACL_ABNORMAL_TIME_SLOT_CONTROL_EACL_TIME_SLOT_CLEAR_LSP      30u
#define DVA_EACL_ABNORMAL_TIME_SLOT_CONTROL_EACL_TIME_SLOT_CLEAR_LEN      1u
#define DVA_EACL_ABNORMAL_TIME_SLOT_CONTROL_EACL_TIME_SLOT_CLEAR_TYPE     DVA_FIELD_TYPE_RW
#define DVA_EACL_ABNORMAL_TIME_SLOT_CONTROL_EACL_TIME_SLOT_THRESHOLD_LSP  0u
#define DVA_EACL_ABNORMAL_TIME_SLOT_CONTROL_EACL_TIME_SLOT_THRESHOLD_LEN  20u
#define DVA_EACL_ABNORMAL_TIME_SLOT_CONTROL_EACL_TIME_SLOT_THRESHOLD_TYPE DVA_FIELD_TYPE_RW

#define DVA_EACL_ABNORMAL_DETECTION_CONTROL_EACL_ABNORMAL_DPM_LSP  0u
#define DVA_EACL_ABNORMAL_DETECTION_CONTROL_EACL_ABNORMAL_DPM_LEN  16u
#define DVA_EACL_ABNORMAL_DETECTION_CONTROL_EACL_ABNORMAL_DPM_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_N_CPU_SELF_FILTER_CONTROL_CPUSELFITER_EACL_SEL_LSP  0u
#define DVA_ACL_N_CPU_SELF_FILTER_CONTROL_CPUSELFITER_EACL_SEL_LEN  1u
#define DVA_ACL_N_CPU_SELF_FILTER_CONTROL_CPUSELFITER_EACL_SEL_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL0_CPTOCPUMSK_0_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL0_CPTOCPUMSK_0_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL0_CPTOCPUMSK_0_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL1_CPTOCPUMSK_1_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL1_CPTOCPUMSK_1_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL1_CPTOCPUMSK_1_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL2_CPTOCPUMSK_2_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL2_CPTOCPUMSK_2_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL2_CPTOCPUMSK_2_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL3_CPTOCPUMSK_3_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL3_CPTOCPUMSK_3_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL3_CPTOCPUMSK_3_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL4_CPTOCPUMSK_4_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL4_CPTOCPUMSK_4_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL4_CPTOCPUMSK_4_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL5_CPTOCPUMSK_5_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL5_CPTOCPUMSK_5_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL5_CPTOCPUMSK_5_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL6_CPTOCPUMSK_6_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL6_CPTOCPUMSK_6_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL6_CPTOCPUMSK_6_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL7_CPTOCPUMSK_7_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL7_CPTOCPUMSK_7_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL7_CPTOCPUMSK_7_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL8_CPTOCPUMSK_8_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL8_CPTOCPUMSK_8_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL8_CPTOCPUMSK_8_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL9_CPTOCPUMSK_9_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL9_CPTOCPUMSK_9_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL9_CPTOCPUMSK_9_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL10_CPTOCPUMSK_10_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL10_CPTOCPUMSK_10_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL10_CPTOCPUMSK_10_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL11_CPTOCPUMSK_11_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL11_CPTOCPUMSK_11_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL11_CPTOCPUMSK_11_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL12_CPTOCPUMSK_12_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL12_CPTOCPUMSK_12_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL12_CPTOCPUMSK_12_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL13_CPTOCPUMSK_13_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL13_CPTOCPUMSK_13_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL13_CPTOCPUMSK_13_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL14_CPTOCPUMSK_14_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL14_CPTOCPUMSK_14_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL14_CPTOCPUMSK_14_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL15_CPTOCPUMSK_15_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL15_CPTOCPUMSK_15_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL15_CPTOCPUMSK_15_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL16_CPTOCPUMSK_16_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL16_CPTOCPUMSK_16_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL16_CPTOCPUMSK_16_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL17_CPTOCPUMSK_17_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL17_CPTOCPUMSK_17_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL17_CPTOCPUMSK_17_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL18_CPTOCPUMSK_18_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL18_CPTOCPUMSK_18_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL18_CPTOCPUMSK_18_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL19_CPTOCPUMSK_19_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL19_CPTOCPUMSK_19_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL19_CPTOCPUMSK_19_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL20_CPTOCPUMSK_20_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL20_CPTOCPUMSK_20_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL20_CPTOCPUMSK_20_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL21_CPTOCPUMSK_21_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL21_CPTOCPUMSK_21_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL21_CPTOCPUMSK_21_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL22_CPTOCPUMSK_22_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL22_CPTOCPUMSK_22_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL22_CPTOCPUMSK_22_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL23_CPTOCPUMSK_23_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL23_CPTOCPUMSK_23_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL23_CPTOCPUMSK_23_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL24_CPTOCPUMSK_24_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL24_CPTOCPUMSK_24_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL24_CPTOCPUMSK_24_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL25_CPTOCPUMSK_25_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL25_CPTOCPUMSK_25_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL25_CPTOCPUMSK_25_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL26_CPTOCPUMSK_26_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL26_CPTOCPUMSK_26_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL26_CPTOCPUMSK_26_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL27_CPTOCPUMSK_27_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL27_CPTOCPUMSK_27_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL27_CPTOCPUMSK_27_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL28_CPTOCPUMSK_28_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL28_CPTOCPUMSK_28_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL28_CPTOCPUMSK_28_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL29_CPTOCPUMSK_29_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL29_CPTOCPUMSK_29_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL29_CPTOCPUMSK_29_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL30_CPTOCPUMSK_30_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL30_CPTOCPUMSK_30_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL30_CPTOCPUMSK_30_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL31_CPTOCPUMSK_31_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL31_CPTOCPUMSK_31_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL31_CPTOCPUMSK_31_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL32_CPTOCPUMSK_32_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL32_CPTOCPUMSK_32_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL32_CPTOCPUMSK_32_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL33_CPTOCPUMSK_33_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL33_CPTOCPUMSK_33_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL33_CPTOCPUMSK_33_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL34_CPTOCPUMSK_34_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL34_CPTOCPUMSK_34_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL34_CPTOCPUMSK_34_TYPE DVA_FIELD_TYPE_RW

#define DVA_ACL_COPYTOCPU_CONTROL35_CPTOCPUMSK_35_LSP  0u
#define DVA_ACL_COPYTOCPU_CONTROL35_CPTOCPUMSK_35_LEN  16u
#define DVA_ACL_COPYTOCPU_CONTROL35_CPTOCPUMSK_35_TYPE DVA_FIELD_TYPE_RW

#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL15SELFFLT_LSP  15u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL15SELFFLT_LEN  1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL15SELFFLT_TYPE DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL14SELFFLT_LSP  14u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL14SELFFLT_LEN  1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL14SELFFLT_TYPE DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL13SELFFLT_LSP  13u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL13SELFFLT_LEN  1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL13SELFFLT_TYPE DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL12SELFFLT_LSP  12u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL12SELFFLT_LEN  1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL12SELFFLT_TYPE DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL11SELFFLT_LSP  11u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL11SELFFLT_LEN  1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL11SELFFLT_TYPE DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL10SELFFLT_LSP  10u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL10SELFFLT_LEN  1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL10SELFFLT_TYPE DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL9SELFFLT_LSP   9u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL9SELFFLT_LEN   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL9SELFFLT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL8SELFFLT_LSP   8u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL8SELFFLT_LEN   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL8SELFFLT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL7SELFFLT_LSP   7u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL7SELFFLT_LEN   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL7SELFFLT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL6SELFFLT_LSP   6u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL6SELFFLT_LEN   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL6SELFFLT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL5SELFFLT_LSP   5u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL5SELFFLT_LEN   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL5SELFFLT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL4SELFFLT_LSP   4u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL4SELFFLT_LEN   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL4SELFFLT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL3SELFFLT_LSP   3u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL3SELFFLT_LEN   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL3SELFFLT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL2SELFFLT_LSP   2u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL2SELFFLT_LEN   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL2SELFFLT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL1SELFFLT_LSP   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL1SELFFLT_LEN   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL1SELFFLT_TYPE  DVA_FIELD_TYPE_RW
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL0SELFFLT_LSP   0u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL0SELFFLT_LEN   1u
#define DVA_EACL_PORT_SELF_FILTERING_CONTROL_EACL0SELFFLT_TYPE  DVA_FIELD_TYPE_RW

#define DVA_ALE_COUNTER0_ALE_COUNTER_ENABLE_LSP  1u
#define DVA_ALE_COUNTER0_ALE_COUNTER_ENABLE_LEN  1u
#define DVA_ALE_COUNTER0_ALE_COUNTER_ENABLE_TYPE DVA_FIELD_TYPE_RW
#define DVA_ALE_COUNTER0_ALE_COUNTER_SET_LSP     0u
#define DVA_ALE_COUNTER0_ALE_COUNTER_SET_LEN     1u
#define DVA_ALE_COUNTER0_ALE_COUNTER_SET_TYPE    DVA_FIELD_TYPE_RW1C

#define DVA_ALE_COUNTER1_ALE_COUNTER_WRITE_DATA_LSP  0u
#define DVA_ALE_COUNTER1_ALE_COUNTER_WRITE_DATA_LEN  32u
#define DVA_ALE_COUNTER1_ALE_COUNTER_WRITE_DATA_TYPE DVA_FIELD_TYPE_RW

#define DVA_ALE_COUNTER2_ALE_COUNTER_WRITE_DATA_LSP  0u
#define DVA_ALE_COUNTER2_ALE_COUNTER_WRITE_DATA_LEN  16u
#define DVA_ALE_COUNTER2_ALE_COUNTER_WRITE_DATA_TYPE DVA_FIELD_TYPE_RW

#define DVA_ALE_COUNTER3_ALE_COUNTER_READ_DATA_LSP  0u
#define DVA_ALE_COUNTER3_ALE_COUNTER_READ_DATA_LEN  32u
#define DVA_ALE_COUNTER3_ALE_COUNTER_READ_DATA_TYPE DVA_FIELD_TYPE_RO

#define DVA_ALE_COUNTER4_ALE_COUNTER_READ_DATA_LSP  0u
#define DVA_ALE_COUNTER4_ALE_COUNTER_READ_DATA_LEN  16u
#define DVA_ALE_COUNTER4_ALE_COUNTER_READ_DATA_TYPE DVA_FIELD_TYPE_RO

#define DVA_ALE_HEADER_DUMP0_ALE_HEADER_DUMP_LOCK_LSP   1u
#define DVA_ALE_HEADER_DUMP0_ALE_HEADER_DUMP_LOCK_LEN   1u
#define DVA_ALE_HEADER_DUMP0_ALE_HEADER_DUMP_LOCK_TYPE  DVA_FIELD_TYPE_RW
#define DVA_ALE_HEADER_DUMP0_ALE_HEADER_DUMP_CLEAR_LSP  0u
#define DVA_ALE_HEADER_DUMP0_ALE_HEADER_DUMP_CLEAR_LEN  1u
#define DVA_ALE_HEADER_DUMP0_ALE_HEADER_DUMP_CLEAR_TYPE DVA_FIELD_TYPE_RW1C

#define DVA_ACL_FRAME_LENGTH0_EACL_FRAMELEN_SEL_LSP  1u
#define DVA_ACL_FRAME_LENGTH0_EACL_FRAMELEN_SEL_LEN  1u
#define DVA_ACL_FRAME_LENGTH0_EACL_FRAMELEN_SEL_TYPE DVA_FIELD_TYPE_RW
#define DVA_ACL_FRAME_LENGTH0_IACL_FRAMELEN_SEL_LSP  0u
#define DVA_ACL_FRAME_LENGTH0_IACL_FRAMELEN_SEL_LEN  1u
#define DVA_ACL_FRAME_LENGTH0_IACL_FRAMELEN_SEL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_RG_TCAM128X96_0_0_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_0_0_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_0_0_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_0_0_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_CRC_CURRENT_RG_TCAM128X96_0_0_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_CRC_CURRENT_RG_TCAM128X96_0_0_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_0_0_CTRL_CRC_CURRENT_RG_TCAM128X96_0_0_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_RG_TCAM128X96_0_1_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_0_1_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_0_1_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_0_1_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_CRC_CURRENT_RG_TCAM128X96_0_1_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_CRC_CURRENT_RG_TCAM128X96_0_1_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_0_1_CTRL_CRC_CURRENT_RG_TCAM128X96_0_1_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_RG_TCAM128X96_1_0_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_1_0_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_1_0_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_1_0_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_CRC_CURRENT_RG_TCAM128X96_1_0_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_CRC_CURRENT_RG_TCAM128X96_1_0_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_1_0_CTRL_CRC_CURRENT_RG_TCAM128X96_1_0_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_RG_TCAM128X96_1_1_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_1_1_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_1_1_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_1_1_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_CRC_CURRENT_RG_TCAM128X96_1_1_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_CRC_CURRENT_RG_TCAM128X96_1_1_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_1_1_CTRL_CRC_CURRENT_RG_TCAM128X96_1_1_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_RG_TCAM128X96_2_0_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_2_0_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_2_0_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_2_0_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_CRC_CURRENT_RG_TCAM128X96_2_0_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_CRC_CURRENT_RG_TCAM128X96_2_0_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_2_0_CTRL_CRC_CURRENT_RG_TCAM128X96_2_0_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_RG_TCAM128X96_2_1_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_2_1_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_2_1_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_2_1_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_CRC_CURRENT_RG_TCAM128X96_2_1_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_CRC_CURRENT_RG_TCAM128X96_2_1_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_2_1_CTRL_CRC_CURRENT_RG_TCAM128X96_2_1_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_RG_TCAM128X96_3_0_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_3_0_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_3_0_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_3_0_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_CRC_CURRENT_RG_TCAM128X96_3_0_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_CRC_CURRENT_RG_TCAM128X96_3_0_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_3_0_CTRL_CRC_CURRENT_RG_TCAM128X96_3_0_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_RG_TCAM128X96_3_1_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_3_1_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_3_1_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_3_1_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_CRC_CURRENT_RG_TCAM128X96_3_1_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_CRC_CURRENT_RG_TCAM128X96_3_1_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_3_1_CTRL_CRC_CURRENT_RG_TCAM128X96_3_1_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_RG_TCAM128X96_4_0_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_4_0_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_4_0_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_4_0_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_CRC_CURRENT_RG_TCAM128X96_4_0_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_CRC_CURRENT_RG_TCAM128X96_4_0_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_4_0_CTRL_CRC_CURRENT_RG_TCAM128X96_4_0_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_RG_TCAM128X96_4_1_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_4_1_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_4_1_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_4_1_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_CRC_CURRENT_RG_TCAM128X96_4_1_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_CRC_CURRENT_RG_TCAM128X96_4_1_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_4_1_CTRL_CRC_CURRENT_RG_TCAM128X96_4_1_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_RG_TCAM128X96_5_0_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_5_0_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_5_0_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_5_0_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_CRC_CURRENT_RG_TCAM128X96_5_0_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_CRC_CURRENT_RG_TCAM128X96_5_0_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_5_0_CTRL_CRC_CURRENT_RG_TCAM128X96_5_0_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_RG_TCAM128X96_5_1_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_5_1_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_5_1_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_5_1_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_CRC_CURRENT_RG_TCAM128X96_5_1_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_CRC_CURRENT_RG_TCAM128X96_5_1_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_5_1_CTRL_CRC_CURRENT_RG_TCAM128X96_5_1_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_RG_TCAM128X96_6_0_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_6_0_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_6_0_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_6_0_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_CRC_CURRENT_RG_TCAM128X96_6_0_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_CRC_CURRENT_RG_TCAM128X96_6_0_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_6_0_CTRL_CRC_CURRENT_RG_TCAM128X96_6_0_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_RG_TCAM128X96_6_1_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_6_1_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_6_1_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_6_1_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_CRC_CURRENT_RG_TCAM128X96_6_1_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_CRC_CURRENT_RG_TCAM128X96_6_1_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_6_1_CTRL_CRC_CURRENT_RG_TCAM128X96_6_1_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_RG_TCAM128X96_7_0_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_7_0_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_7_0_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_CRC_GOLDEN_RG_TCAM128X96_7_0_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_CRC_CURRENT_RG_TCAM128X96_7_0_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_CRC_CURRENT_RG_TCAM128X96_7_0_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_7_0_CTRL_CRC_CURRENT_RG_TCAM128X96_7_0_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_RG_TCAM128X96_7_1_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_7_1_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_7_1_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_CRC_GOLDEN_RG_TCAM128X96_7_1_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_CRC_CURRENT_RG_TCAM128X96_7_1_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_CRC_CURRENT_RG_TCAM128X96_7_1_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_128X96_7_1_CTRL_CRC_CURRENT_RG_TCAM128X96_7_1_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_RG_TCAM64X96_8_0_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_CRC_GOLDEN_RG_TCAM64X96_8_0_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_CRC_GOLDEN_RG_TCAM64X96_8_0_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_CRC_GOLDEN_RG_TCAM64X96_8_0_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_CRC_CURRENT_RG_TCAM64X96_8_0_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_CRC_CURRENT_RG_TCAM64X96_8_0_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_64X96_8_0_CTRL_CRC_CURRENT_RG_TCAM64X96_8_0_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_FIRST_RUN_DONE_LSP  5u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_FIRST_RUN_DONE_LEN  1u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_FIRST_RUN_DONE_TYPE DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_CLR_IRPT_LSP        4u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_CLR_IRPT_LEN        1u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_CLR_IRPT_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_CRC_FAIL_IRPT_LSP   3u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_CRC_FAIL_IRPT_LEN   1u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_CRC_FAIL_IRPT_TYPE  DVA_FIELD_TYPE_RO
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_CHECK_EN_LSP        2u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_CHECK_EN_LEN        1u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_CHECK_EN_TYPE       DVA_FIELD_TYPE_RW
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_PER_SEL_LSP         0u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_PER_SEL_LEN         2u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_RG_TCAM64X96_8_1_ACL_PER_SEL_TYPE        DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_CRC_GOLDEN_RG_TCAM64X96_8_1_ACL_GOLDEN_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_CRC_GOLDEN_RG_TCAM64X96_8_1_ACL_GOLDEN_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_CRC_GOLDEN_RG_TCAM64X96_8_1_ACL_GOLDEN_CRC_VAL_TYPE DVA_FIELD_TYPE_RW

#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_CRC_CURRENT_RG_TCAM64X96_8_1_ACL_CURR_CRC_VAL_LSP  0u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_CRC_CURRENT_RG_TCAM64X96_8_1_ACL_CURR_CRC_VAL_LEN  32u
#define DVA_SAFETY_TCAM_64X96_8_1_CTRL_CRC_CURRENT_RG_TCAM64X96_8_1_ACL_CURR_CRC_VAL_TYPE DVA_FIELD_TYPE_RO

#define DVA_PORT0_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT0_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT0_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT0_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT0_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT0_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT1_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT1_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT1_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT1_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT1_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT2_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT2_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT2_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT2_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT2_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT3_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT3_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT3_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT3_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT3_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT4_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT4_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT4_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT4_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT4_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT5_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT5_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT5_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT5_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT5_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT6_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT6_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT6_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT6_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT6_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT7_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT7_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT7_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT7_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT7_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT8_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT8_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT8_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT8_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT8_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT9_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT9_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT9_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT9_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT9_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT10_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT10_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT10_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT10_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT10_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT11_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT11_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT11_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT11_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT11_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT12_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT12_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT12_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT12_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT12_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT13_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT13_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT13_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT13_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT13_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT14_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT14_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT14_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT14_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT14_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_IACL_LOOKUP_CONTROL_IACL_DEFACT_LSP     1u
#define DVA_PORT15_IACL_LOOKUP_CONTROL_IACL_DEFACT_LEN     1u
#define DVA_PORT15_IACL_LOOKUP_CONTROL_IACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT15_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LSP  0u
#define DVA_PORT15_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_LEN  1u
#define DVA_PORT15_IACL_LOOKUP_CONTROL_IACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT0_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT0_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT0_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT0_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT0_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT1_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT1_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT1_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT1_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT1_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT2_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT2_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT2_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT2_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT2_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT3_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT3_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT3_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT3_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT3_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT4_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT4_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT4_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT4_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT4_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT5_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT5_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT5_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT5_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT5_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT6_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT6_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT6_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT6_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT6_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT7_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT7_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT7_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT7_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT7_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT8_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT8_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT8_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT8_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT8_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT9_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT9_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT9_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT9_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT9_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT10_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT10_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT10_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT10_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT10_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT11_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT11_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT11_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT11_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT11_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT12_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT12_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT12_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT12_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT12_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT13_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT13_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT13_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT13_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT13_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT14_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT14_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT14_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT14_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT14_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_EACL_LOOKUP_CONTROL_EACL_DEFACT_LSP     1u
#define DVA_PORT15_EACL_LOOKUP_CONTROL_EACL_DEFACT_LEN     1u
#define DVA_PORT15_EACL_LOOKUP_CONTROL_EACL_DEFACT_TYPE    DVA_FIELD_TYPE_RW
#define DVA_PORT15_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LSP  0u
#define DVA_PORT15_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_LEN  1u
#define DVA_PORT15_EACL_LOOKUP_CONTROL_EACL_INACLLUEN_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT0_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT0_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT1_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT1_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT2_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT2_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT3_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT3_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT4_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT4_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT5_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT5_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT6_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT6_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT7_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT7_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT8_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT8_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT9_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT9_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT10_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT10_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT11_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT11_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT12_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT12_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT13_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT13_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT14_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT14_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#define DVA_PORT15_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LSP  0u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_LEN  1u
#define DVA_PORT15_FUSA_PG_LOCK_DMY_ACL_FUSA_PG_LOCK_DMY_ACL_TYPE DVA_FIELD_TYPE_RW

#endif
#endif /* DVA_RTKAS_REG_FIELD_FILE_ACL_H_ */