/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_CPU_EFUSE_H_
#define DV1_RTKAS_REG_FIELD_FILE_CPU_EFUSE_H_

#ifdef DV1_FILE_CPU_EFUSE
/* File: EFUSE */
#define DV1_EFUSE_COMMAND_EFUSE_REG_RD_LSP     31u
#define DV1_EFUSE_COMMAND_EFUSE_REG_RD_LEN     1u
#define DV1_EFUSE_COMMAND_EFUSE_REG_RD_TYPE    DV1_FIELD_TYPE_RWS
#define DV1_EFUSE_COMMAND_EFUSE_REG_WR_LSP     30u
#define DV1_EFUSE_COMMAND_EFUSE_REG_WR_LEN     1u
#define DV1_EFUSE_COMMAND_EFUSE_REG_WR_TYPE    DV1_FIELD_TYPE_RWS
#define DV1_EFUSE_COMMAND_REG03_LSP            27u
#define DV1_EFUSE_COMMAND_REG03_LEN            3u
#define DV1_EFUSE_COMMAND_REG03_TYPE           DV1_FIELD_TYPE_RWS
#define DV1_EFUSE_COMMAND_EFUSE_PORTC_SEL_LSP  26u
#define DV1_EFUSE_COMMAND_EFUSE_PORTC_SEL_LEN  1u
#define DV1_EFUSE_COMMAND_EFUSE_PORTC_SEL_TYPE DV1_FIELD_TYPE_RW
#define DV1_EFUSE_COMMAND_EFUSE_PORTB_SEL_LSP  25u
#define DV1_EFUSE_COMMAND_EFUSE_PORTB_SEL_LEN  1u
#define DV1_EFUSE_COMMAND_EFUSE_PORTB_SEL_TYPE DV1_FIELD_TYPE_RW
#define DV1_EFUSE_COMMAND_EFUSE_PORTA_SEL_LSP  24u
#define DV1_EFUSE_COMMAND_EFUSE_PORTA_SEL_LEN  1u
#define DV1_EFUSE_COMMAND_EFUSE_PORTA_SEL_TYPE DV1_FIELD_TYPE_RW
#define DV1_EFUSE_COMMAND_REG02_LSP            22u
#define DV1_EFUSE_COMMAND_REG02_LEN            2u
#define DV1_EFUSE_COMMAND_REG02_TYPE           DV1_FIELD_TYPE_RW
#define DV1_EFUSE_COMMAND_EFUSE_WORD_ADDR_LSP  16u
#define DV1_EFUSE_COMMAND_EFUSE_WORD_ADDR_LEN  6u
#define DV1_EFUSE_COMMAND_EFUSE_WORD_ADDR_TYPE DV1_FIELD_TYPE_RW
#define DV1_EFUSE_COMMAND_EFUSE_DATA_LSP       0u
#define DV1_EFUSE_COMMAND_EFUSE_DATA_LEN       16u
#define DV1_EFUSE_COMMAND_EFUSE_DATA_TYPE      DV1_FIELD_TYPE_RWS

#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_ACCEN_LSP   15u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_ACCEN_LEN   1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_ACCEN_TYPE  DV1_FIELD_TYPE_RW
#define DV1_EFUSE_DIRECT_PG_REG05_LSP                9u
#define DV1_EFUSE_DIRECT_PG_REG05_LEN                6u
#define DV1_EFUSE_DIRECT_PG_REG05_TYPE               DV1_FIELD_TYPE_RW
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A9_LSP      8u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A9_LEN      1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A9_TYPE     DV1_FIELD_TYPE_RW
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A8_LSP      7u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A8_LEN      1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A8_TYPE     DV1_FIELD_TYPE_RW
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A7_LSP      6u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A7_LEN      1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A7_TYPE     DV1_FIELD_TYPE_RW
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A0_LSP      5u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A0_LEN      1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_A0_TYPE     DV1_FIELD_TYPE_RW
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_PGENB_LSP   4u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_PGENB_LEN   1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_PGENB_TYPE  DV1_FIELD_TYPE_RW
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_STROBE_LSP  3u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_STROBE_LEN  1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_STROBE_TYPE DV1_FIELD_TYPE_RW
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_CSB_LSP     2u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_CSB_LEN     1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_CSB_TYPE    DV1_FIELD_TYPE_RW
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_PS_LSP      1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_PS_LEN      1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_PS_TYPE     DV1_FIELD_TYPE_RW
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_PD_LSP      0u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_PD_LEN      1u
#define DV1_EFUSE_DIRECT_PG_EFUSE_DIRECT_PD_TYPE     DV1_FIELD_TYPE_RW

#define DV1_EFUSE_DMY_0_EFUSE_DMY_0_LSP  0u
#define DV1_EFUSE_DMY_0_EFUSE_DMY_0_LEN  32u
#define DV1_EFUSE_DMY_0_EFUSE_DMY_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_EFUSE_DMY_1_EFUSE_DMY_1_LSP  0u
#define DV1_EFUSE_DMY_1_EFUSE_DMY_1_LEN  32u
#define DV1_EFUSE_DMY_1_EFUSE_DMY_1_TYPE DV1_FIELD_TYPE_RO

#define DV1_EFUSE_CONFIG0_EFUSE_THPPG_LSP     30u
#define DV1_EFUSE_CONFIG0_EFUSE_THPPG_LEN     2u
#define DV1_EFUSE_CONFIG0_EFUSE_THPPG_TYPE    DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_THPA_LSP      28u
#define DV1_EFUSE_CONFIG0_EFUSE_THPA_LEN      2u
#define DV1_EFUSE_CONFIG0_EFUSE_THPA_TYPE     DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TPGM_LSP      26u
#define DV1_EFUSE_CONFIG0_EFUSE_TPGM_LEN      2u
#define DV1_EFUSE_CONFIG0_EFUSE_TPGM_TYPE     DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPPG_LSP    24u
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPPG_LEN    2u
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPPG_TYPE   DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPA_LSP     22u
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPA_LEN     2u
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPA_TYPE    DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPCS_LSP    20u
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPCS_LEN    2u
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPCS_TYPE   DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPPSCS_LSP  18u
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPPSCS_LEN  2u
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPPSCS_TYPE DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPPDPS_LSP  16u
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPPDPS_LEN  2u
#define DV1_EFUSE_CONFIG0_EFUSE_TSUPPDPS_TYPE DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_THRCS_LSP     14u
#define DV1_EFUSE_CONFIG0_EFUSE_THRCS_LEN     2u
#define DV1_EFUSE_CONFIG0_EFUSE_THRCS_TYPE    DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_THRPD_LSP     12u
#define DV1_EFUSE_CONFIG0_EFUSE_THRPD_LEN     2u
#define DV1_EFUSE_CONFIG0_EFUSE_THRPD_TYPE    DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_THRA_LSP      10u
#define DV1_EFUSE_CONFIG0_EFUSE_THRA_LEN      2u
#define DV1_EFUSE_CONFIG0_EFUSE_THRA_TYPE     DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TSO_LSP       8u
#define DV1_EFUSE_CONFIG0_EFUSE_TSO_LEN       2u
#define DV1_EFUSE_CONFIG0_EFUSE_TSO_TYPE      DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TRD_LSP       6u
#define DV1_EFUSE_CONFIG0_EFUSE_TRD_LEN       2u
#define DV1_EFUSE_CONFIG0_EFUSE_TRD_TYPE      DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TSURA_LSP     4u
#define DV1_EFUSE_CONFIG0_EFUSE_TSURA_LEN     2u
#define DV1_EFUSE_CONFIG0_EFUSE_TSURA_TYPE    DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TSURPDCS_LSP  2u
#define DV1_EFUSE_CONFIG0_EFUSE_TSURPDCS_LEN  2u
#define DV1_EFUSE_CONFIG0_EFUSE_TSURPDCS_TYPE DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG0_EFUSE_TSURCS_LSP    0u
#define DV1_EFUSE_CONFIG0_EFUSE_TSURCS_LEN    2u
#define DV1_EFUSE_CONFIG0_EFUSE_TSURCS_TYPE   DV1_FIELD_TYPE_RW

#define DV1_EFUSE_CONFIG1_REG14_LSP          6u
#define DV1_EFUSE_CONFIG1_REG14_LEN          2u
#define DV1_EFUSE_CONFIG1_REG14_TYPE         DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG1_EFUSE_THPPS_LSP    4u
#define DV1_EFUSE_CONFIG1_EFUSE_THPPS_LEN    2u
#define DV1_EFUSE_CONFIG1_EFUSE_THPPS_TYPE   DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG1_EFUSE_THPPDPS_LSP  2u
#define DV1_EFUSE_CONFIG1_EFUSE_THPPDPS_LEN  2u
#define DV1_EFUSE_CONFIG1_EFUSE_THPPDPS_TYPE DV1_FIELD_TYPE_RW
#define DV1_EFUSE_CONFIG1_EFUSE_THPCS_LSP    0u
#define DV1_EFUSE_CONFIG1_EFUSE_THPCS_LEN    2u
#define DV1_EFUSE_CONFIG1_EFUSE_THPCS_TYPE   DV1_FIELD_TYPE_RW

#define DV1_EFUSE_DMY_2_EFUSE_DMY_2_LSP  0u
#define DV1_EFUSE_DMY_2_EFUSE_DMY_2_LEN  32u
#define DV1_EFUSE_DMY_2_EFUSE_DMY_2_TYPE DV1_FIELD_TYPE_RO

#define DV1_EFUSE_DMY_3_EFUSE_DMY_3_LSP  0u
#define DV1_EFUSE_DMY_3_EFUSE_DMY_3_LEN  32u
#define DV1_EFUSE_DMY_3_EFUSE_DMY_3_TYPE DV1_FIELD_TYPE_RO

#define DV1_DIS_EFUSE_PG_DIS_EFUSE_PG_LSP  0u
#define DV1_DIS_EFUSE_PG_DIS_EFUSE_PG_LEN  1u
#define DV1_DIS_EFUSE_PG_DIS_EFUSE_PG_TYPE DV1_FIELD_TYPE_RW

#define DV1_OTP_TRIGGER_OTP_START_ADDR_LSP  16u
#define DV1_OTP_TRIGGER_OTP_START_ADDR_LEN  12u
#define DV1_OTP_TRIGGER_OTP_START_ADDR_TYPE DV1_FIELD_TYPE_RWS
#define DV1_OTP_TRIGGER_OTP_MODE_LSP        11u
#define DV1_OTP_TRIGGER_OTP_MODE_LEN        5u
#define DV1_OTP_TRIGGER_OTP_MODE_TYPE       DV1_FIELD_TYPE_RW
#define DV1_OTP_TRIGGER_OTP_OP_START_LSP    10u
#define DV1_OTP_TRIGGER_OTP_OP_START_LEN    1u
#define DV1_OTP_TRIGGER_OTP_OP_START_TYPE   DV1_FIELD_TYPE_RWS

#define DV1_OTP_DATA_REG_OTP_DATA_LSP  0u
#define DV1_OTP_DATA_REG_OTP_DATA_LEN  32u
#define DV1_OTP_DATA_REG_OTP_DATA_TYPE DV1_FIELD_TYPE_RW

#define DV1_OTP_CTRL_REG_OTP_READ_THEN_WAIT_EN_LSP  9u
#define DV1_OTP_CTRL_REG_OTP_READ_THEN_WAIT_EN_LEN  1u
#define DV1_OTP_CTRL_REG_OTP_READ_THEN_WAIT_EN_TYPE DV1_FIELD_TYPE_RW
#define DV1_OTP_CTRL_REG_OTP_READ_ALL_ADDR_EN_LSP   6u
#define DV1_OTP_CTRL_REG_OTP_READ_ALL_ADDR_EN_LEN   1u
#define DV1_OTP_CTRL_REG_OTP_READ_ALL_ADDR_EN_TYPE  DV1_FIELD_TYPE_RW
#define DV1_OTP_CTRL_REG_OTP_AUTO_CLR_STATUS_LSP    4u
#define DV1_OTP_CTRL_REG_OTP_AUTO_CLR_STATUS_LEN    1u
#define DV1_OTP_CTRL_REG_OTP_AUTO_CLR_STATUS_TYPE   DV1_FIELD_TYPE_RW
#define DV1_OTP_CTRL_REG_OTP_TEST_ARRAY_EN_LSP      3u
#define DV1_OTP_CTRL_REG_OTP_TEST_ARRAY_EN_LEN      1u
#define DV1_OTP_CTRL_REG_OTP_TEST_ARRAY_EN_TYPE     DV1_FIELD_TYPE_RW
#define DV1_OTP_CTRL_REG_OTP_DS_EN_LSP              2u
#define DV1_OTP_CTRL_REG_OTP_DS_EN_LEN              1u
#define DV1_OTP_CTRL_REG_OTP_DS_EN_TYPE             DV1_FIELD_TYPE_RW
#define DV1_OTP_CTRL_REG_OTP_TEST_ROW_COL_SEL_LSP   1u
#define DV1_OTP_CTRL_REG_OTP_TEST_ROW_COL_SEL_LEN   1u
#define DV1_OTP_CTRL_REG_OTP_TEST_ROW_COL_SEL_TYPE  DV1_FIELD_TYPE_RW
#define DV1_OTP_CTRL_REG_OTP_SOFT_RST_LSP           0u
#define DV1_OTP_CTRL_REG_OTP_SOFT_RST_LEN           1u
#define DV1_OTP_CTRL_REG_OTP_SOFT_RST_TYPE          DV1_FIELD_TYPE_RW

#define DV1_OTP_TIMING_CTRL_REG_0_OTP_TTAS_LSP  16u
#define DV1_OTP_TIMING_CTRL_REG_0_OTP_TTAS_LEN  10u
#define DV1_OTP_TIMING_CTRL_REG_0_OTP_TTAS_TYPE DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_0_OTP_TSAS_LSP  6u
#define DV1_OTP_TIMING_CTRL_REG_0_OTP_TSAS_LEN  6u
#define DV1_OTP_TIMING_CTRL_REG_0_OTP_TSAS_TYPE DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_0_OTP_TVDS_LSP  0u
#define DV1_OTP_TIMING_CTRL_REG_0_OTP_TVDS_LEN  5u
#define DV1_OTP_TIMING_CTRL_REG_0_OTP_TVDS_TYPE DV1_FIELD_TYPE_RW

#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TPWI_LSP  25u
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TPWI_LEN  5u
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TPWI_TYPE DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TPW_LSP   16u
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TPW_LEN   8u
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TPW_TYPE  DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TPPS_LSP  9u
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TPPS_LEN  7u
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TPPS_TYPE DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TCS_LSP   0u
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TCS_LEN   8u
#define DV1_OTP_TIMING_CTRL_REG_1_OTP_TCS_TYPE  DV1_FIELD_TYPE_RW

#define DV1_OTP_TIMING_CTRL_REG_2_OTP_PDOUT_MISMATCH_INT_EN_LSP       27u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_PDOUT_MISMATCH_INT_EN_LEN       1u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_PDOUT_MISMATCH_INT_EN_TYPE      DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_PGM_LOCK_REGION_INT_EN_LSP      23u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_PGM_LOCK_REGION_INT_EN_LEN      1u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_PGM_LOCK_REGION_INT_EN_TYPE     DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_RPCK_GOOD_INT_EN_LSP            22u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_RPCK_GOOD_INT_EN_LEN            1u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_RPCK_GOOD_INT_EN_TYPE           DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_RPCK_NG_INT_EN_LSP              21u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_RPCK_NG_INT_EN_LEN              1u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_RPCK_NG_INT_EN_TYPE             DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_RPCK_OK_INT_EN_LSP              20u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_RPCK_OK_INT_EN_LEN              1u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_RPCK_OK_INT_EN_TYPE             DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_INIT_RD_KILLCHIP_INT_EN_LSP     19u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_INIT_RD_KILLCHIP_INT_EN_LEN     1u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_INIT_RD_KILLCHIP_INT_EN_TYPE    DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_INIT_RD_CMP_HIGH_NG_INT_EN_LSP  18u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_INIT_RD_CMP_HIGH_NG_INT_EN_LEN  1u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_INIT_RD_CMP_HIGH_NG_INT_EN_TYPE DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_ABNORMAL_REPAIR_INT_EN_LSP      17u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_ABNORMAL_REPAIR_INT_EN_LEN      1u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_ABNORMAL_REPAIR_INT_EN_TYPE     DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_OP_DONE_INT_EN_LSP              16u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_OP_DONE_INT_EN_LEN              1u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_OP_DONE_INT_EN_TYPE             DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_TPPH_LSP                        0u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_TPPH_LEN                        11u
#define DV1_OTP_TIMING_CTRL_REG_2_OTP_TPPH_TYPE                       DV1_FIELD_TYPE_RW

#define DV1_OTP_INT_STS_REG_OTP_PDOUT_MISMATCH_INT_MASK_LSP       27u
#define DV1_OTP_INT_STS_REG_OTP_PDOUT_MISMATCH_INT_MASK_LEN       1u
#define DV1_OTP_INT_STS_REG_OTP_PDOUT_MISMATCH_INT_MASK_TYPE      DV1_FIELD_TYPE_RW
#define DV1_OTP_INT_STS_REG_OTP_PGM_LOCK_REGION_INT_MASK_LSP      23u
#define DV1_OTP_INT_STS_REG_OTP_PGM_LOCK_REGION_INT_MASK_LEN      1u
#define DV1_OTP_INT_STS_REG_OTP_PGM_LOCK_REGION_INT_MASK_TYPE     DV1_FIELD_TYPE_RW
#define DV1_OTP_INT_STS_REG_OTP_RPCK_GOOD_INT_MASK_LSP            22u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_GOOD_INT_MASK_LEN            1u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_GOOD_INT_MASK_TYPE           DV1_FIELD_TYPE_RW
#define DV1_OTP_INT_STS_REG_OTP_RPCK_NG_INT_MASK_LSP              21u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_NG_INT_MASK_LEN              1u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_NG_INT_MASK_TYPE             DV1_FIELD_TYPE_RW
#define DV1_OTP_INT_STS_REG_OTP_RPCK_OK_INT_MASK_LSP              20u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_OK_INT_MASK_LEN              1u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_OK_INT_MASK_TYPE             DV1_FIELD_TYPE_RW
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_KILLCHIP_INT_MASK_LSP     19u
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_KILLCHIP_INT_MASK_LEN     1u
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_KILLCHIP_INT_MASK_TYPE    DV1_FIELD_TYPE_RW
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_CMP_HIGH_NG_INT_MASK_LSP  18u
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_CMP_HIGH_NG_INT_MASK_LEN  1u
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_CMP_HIGH_NG_INT_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_OTP_INT_STS_REG_OTP_ABNORMAL_REPAIR_INT_MASK_LSP      17u
#define DV1_OTP_INT_STS_REG_OTP_ABNORMAL_REPAIR_INT_MASK_LEN      1u
#define DV1_OTP_INT_STS_REG_OTP_ABNORMAL_REPAIR_INT_MASK_TYPE     DV1_FIELD_TYPE_RW
#define DV1_OTP_INT_STS_REG_OTP_OP_DONE_INT_MASK_LSP              16u
#define DV1_OTP_INT_STS_REG_OTP_OP_DONE_INT_MASK_LEN              1u
#define DV1_OTP_INT_STS_REG_OTP_OP_DONE_INT_MASK_TYPE             DV1_FIELD_TYPE_RW
#define DV1_OTP_INT_STS_REG_OTP_PDOUT_MISMATCH_INT_LSP            11u
#define DV1_OTP_INT_STS_REG_OTP_PDOUT_MISMATCH_INT_LEN            1u
#define DV1_OTP_INT_STS_REG_OTP_PDOUT_MISMATCH_INT_TYPE           DV1_FIELD_TYPE_RW1C
#define DV1_OTP_INT_STS_REG_OTP_PGM_LOCK_REGION_INT_LSP           7u
#define DV1_OTP_INT_STS_REG_OTP_PGM_LOCK_REGION_INT_LEN           1u
#define DV1_OTP_INT_STS_REG_OTP_PGM_LOCK_REGION_INT_TYPE          DV1_FIELD_TYPE_RW1C
#define DV1_OTP_INT_STS_REG_OTP_RPCK_GOOD_INT_LSP                 6u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_GOOD_INT_LEN                 1u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_GOOD_INT_TYPE                DV1_FIELD_TYPE_RW1C
#define DV1_OTP_INT_STS_REG_OTP_RPCK_NG_INT_LSP                   5u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_NG_INT_LEN                   1u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_NG_INT_TYPE                  DV1_FIELD_TYPE_RW1C
#define DV1_OTP_INT_STS_REG_OTP_RPCK_OK_INT_LSP                   4u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_OK_INT_LEN                   1u
#define DV1_OTP_INT_STS_REG_OTP_RPCK_OK_INT_TYPE                  DV1_FIELD_TYPE_RW1C
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_KILLCHIP_INT_LSP          3u
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_KILLCHIP_INT_LEN          1u
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_KILLCHIP_INT_TYPE         DV1_FIELD_TYPE_RW1C
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_CMP_HIGH_NG_INT_LSP       2u
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_CMP_HIGH_NG_INT_LEN       1u
#define DV1_OTP_INT_STS_REG_OTP_INIT_RD_CMP_HIGH_NG_INT_TYPE      DV1_FIELD_TYPE_RW1C
#define DV1_OTP_INT_STS_REG_OTP_ABNORMAL_REPAIR_INT_LSP           1u
#define DV1_OTP_INT_STS_REG_OTP_ABNORMAL_REPAIR_INT_LEN           1u
#define DV1_OTP_INT_STS_REG_OTP_ABNORMAL_REPAIR_INT_TYPE          DV1_FIELD_TYPE_RW1C
#define DV1_OTP_INT_STS_REG_OTP_OP_DONE_INT_LSP                   0u
#define DV1_OTP_INT_STS_REG_OTP_OP_DONE_INT_LEN                   1u
#define DV1_OTP_INT_STS_REG_OTP_OP_DONE_INT_TYPE                  DV1_FIELD_TYPE_RW1C

#define DV1_OTP_FSM_STATE_OTP_INIT_RD_NG_CNT_LSP  16u
#define DV1_OTP_FSM_STATE_OTP_INIT_RD_NG_CNT_LEN  13u
#define DV1_OTP_FSM_STATE_OTP_INIT_RD_NG_CNT_TYPE DV1_FIELD_TYPE_RO
#define DV1_OTP_FSM_STATE_OTP_READY_LSP           15u
#define DV1_OTP_FSM_STATE_OTP_READY_LEN           1u
#define DV1_OTP_FSM_STATE_OTP_READY_TYPE          DV1_FIELD_TYPE_RO
#define DV1_OTP_FSM_STATE_OTP_IF_FSM_LSP          4u
#define DV1_OTP_FSM_STATE_OTP_IF_FSM_LEN          5u
#define DV1_OTP_FSM_STATE_OTP_IF_FSM_TYPE         DV1_FIELD_TYPE_RO
#define DV1_OTP_FSM_STATE_OTP_MAIN_FSM_LSP        0u
#define DV1_OTP_FSM_STATE_OTP_MAIN_FSM_LEN        4u
#define DV1_OTP_FSM_STATE_OTP_MAIN_FSM_TYPE       DV1_FIELD_TYPE_RO

#define DV1_OTP_INIT_RD_NG_ADR_REG_OTP_INIT_RD_NG_ADR1_LSP  16u
#define DV1_OTP_INIT_RD_NG_ADR_REG_OTP_INIT_RD_NG_ADR1_LEN  12u
#define DV1_OTP_INIT_RD_NG_ADR_REG_OTP_INIT_RD_NG_ADR1_TYPE DV1_FIELD_TYPE_RO
#define DV1_OTP_INIT_RD_NG_ADR_REG_OTP_INIT_RD_NG_ADR0_LSP  0u
#define DV1_OTP_INIT_RD_NG_ADR_REG_OTP_INIT_RD_NG_ADR0_LEN  12u
#define DV1_OTP_INIT_RD_NG_ADR_REG_OTP_INIT_RD_NG_ADR0_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_SW_DIRECT_REG_SW_DIRECT_RESERVED_LSP  0u
#define DV1_OTP_SW_DIRECT_REG_SW_DIRECT_RESERVED_LEN  1u
#define DV1_OTP_SW_DIRECT_REG_SW_DIRECT_RESERVED_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_TIMING_CTRL_REG_3_OTP_PCLK_H_CYCLE_LSP  28u
#define DV1_OTP_TIMING_CTRL_REG_3_OTP_PCLK_H_CYCLE_LEN  3u
#define DV1_OTP_TIMING_CTRL_REG_3_OTP_PCLK_H_CYCLE_TYPE DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_3_OTP_READ_DELAY_LSP    24u
#define DV1_OTP_TIMING_CTRL_REG_3_OTP_READ_DELAY_LEN    3u
#define DV1_OTP_TIMING_CTRL_REG_3_OTP_READ_DELAY_TYPE   DV1_FIELD_TYPE_RW
#define DV1_OTP_TIMING_CTRL_REG_3_OTP_TPPR_LSP          16u
#define DV1_OTP_TIMING_CTRL_REG_3_OTP_TPPR_LEN          7u
#define DV1_OTP_TIMING_CTRL_REG_3_OTP_TPPR_TYPE         DV1_FIELD_TYPE_RW

#define DV1_OTP_INT_STATUS_READ_OTP_PDOUT_MISMATCH_INT_STS_LSP       11u
#define DV1_OTP_INT_STATUS_READ_OTP_PDOUT_MISMATCH_INT_STS_LEN       1u
#define DV1_OTP_INT_STATUS_READ_OTP_PDOUT_MISMATCH_INT_STS_TYPE      DV1_FIELD_TYPE_RO
#define DV1_OTP_INT_STATUS_READ_OTP_PGM_LOCK_REGION_INT_STS_LSP      7u
#define DV1_OTP_INT_STATUS_READ_OTP_PGM_LOCK_REGION_INT_STS_LEN      1u
#define DV1_OTP_INT_STATUS_READ_OTP_PGM_LOCK_REGION_INT_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_OTP_INT_STATUS_READ_OTP_RPCK_GOOD_INT_STS_LSP            6u
#define DV1_OTP_INT_STATUS_READ_OTP_RPCK_GOOD_INT_STS_LEN            1u
#define DV1_OTP_INT_STATUS_READ_OTP_RPCK_GOOD_INT_STS_TYPE           DV1_FIELD_TYPE_RO
#define DV1_OTP_INT_STATUS_READ_OTP_RPCK_NG_INT_STS_LSP              5u
#define DV1_OTP_INT_STATUS_READ_OTP_RPCK_NG_INT_STS_LEN              1u
#define DV1_OTP_INT_STATUS_READ_OTP_RPCK_NG_INT_STS_TYPE             DV1_FIELD_TYPE_RO
#define DV1_OTP_INT_STATUS_READ_OTP_RPCK_OK_INT_STS_LSP              4u
#define DV1_OTP_INT_STATUS_READ_OTP_RPCK_OK_INT_STS_LEN              1u
#define DV1_OTP_INT_STATUS_READ_OTP_RPCK_OK_INT_STS_TYPE             DV1_FIELD_TYPE_RO
#define DV1_OTP_INT_STATUS_READ_OTP_INIT_RD_KILLCHIP_INT_STS_LSP     3u
#define DV1_OTP_INT_STATUS_READ_OTP_INIT_RD_KILLCHIP_INT_STS_LEN     1u
#define DV1_OTP_INT_STATUS_READ_OTP_INIT_RD_KILLCHIP_INT_STS_TYPE    DV1_FIELD_TYPE_RO
#define DV1_OTP_INT_STATUS_READ_OTP_INIT_RD_CMP_HIGH_NG_INT_STS_LSP  2u
#define DV1_OTP_INT_STATUS_READ_OTP_INIT_RD_CMP_HIGH_NG_INT_STS_LEN  1u
#define DV1_OTP_INT_STATUS_READ_OTP_INIT_RD_CMP_HIGH_NG_INT_STS_TYPE DV1_FIELD_TYPE_RO
#define DV1_OTP_INT_STATUS_READ_OTP_ABNORMAL_REPAIR_INT_STS_LSP      1u
#define DV1_OTP_INT_STATUS_READ_OTP_ABNORMAL_REPAIR_INT_STS_LEN      1u
#define DV1_OTP_INT_STATUS_READ_OTP_ABNORMAL_REPAIR_INT_STS_TYPE     DV1_FIELD_TYPE_RO
#define DV1_OTP_INT_STATUS_READ_OTP_OP_DONE_INT_STS_LSP              0u
#define DV1_OTP_INT_STATUS_READ_OTP_OP_DONE_INT_STS_LEN              1u
#define DV1_OTP_INT_STATUS_READ_OTP_OP_DONE_INT_STS_TYPE             DV1_FIELD_TYPE_RO

#define DV1_OTP_READ_DATA_REG_0_OTP_READ_DATA_0_LSP  0u
#define DV1_OTP_READ_DATA_REG_0_OTP_READ_DATA_0_LEN  32u
#define DV1_OTP_READ_DATA_REG_0_OTP_READ_DATA_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_READ_DATA_REG_1_OTP_READ_DATA_1_LSP  0u
#define DV1_OTP_READ_DATA_REG_1_OTP_READ_DATA_1_LEN  32u
#define DV1_OTP_READ_DATA_REG_1_OTP_READ_DATA_1_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_READ_DATA_REG_2_OTP_READ_DATA_2_LSP  0u
#define DV1_OTP_READ_DATA_REG_2_OTP_READ_DATA_2_LEN  32u
#define DV1_OTP_READ_DATA_REG_2_OTP_READ_DATA_2_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_CTL_2_OTP_FPGA_SOFT_RST_LSP  0u
#define DV1_OTP_CTL_2_OTP_FPGA_SOFT_RST_LEN  1u
#define DV1_OTP_CTL_2_OTP_FPGA_SOFT_RST_TYPE DV1_FIELD_TYPE_RW

#define DV1_OTP_LOCK_BIT_REGION_01_LOCKBIT_0X2A0_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_01_LOCKBIT_0X2A0_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_01_LOCKBIT_0X2A0_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_02_LOCKBIT_0X2A1_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_02_LOCKBIT_0X2A1_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_02_LOCKBIT_0X2A1_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_03_LOCKBIT_0X2A2_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_03_LOCKBIT_0X2A2_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_03_LOCKBIT_0X2A2_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_04_LOCKBIT_0X2A3_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_04_LOCKBIT_0X2A3_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_04_LOCKBIT_0X2A3_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_05_LOCKBIT_0X2A4_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_05_LOCKBIT_0X2A4_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_05_LOCKBIT_0X2A4_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_06_LOCKBIT_0X2A8_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_06_LOCKBIT_0X2A8_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_06_LOCKBIT_0X2A8_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_07_LOCKBIT_0X2A9_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_07_LOCKBIT_0X2A9_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_07_LOCKBIT_0X2A9_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_08_LOCKBIT_0X2AA_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_08_LOCKBIT_0X2AA_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_08_LOCKBIT_0X2AA_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_09_LOCKBIT_0X2AB_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_09_LOCKBIT_0X2AB_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_09_LOCKBIT_0X2AB_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_10_LOCKBIT_0X2AD_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_10_LOCKBIT_0X2AD_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_10_LOCKBIT_0X2AD_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_11_LOCKBIT_0X2AE_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_11_LOCKBIT_0X2AE_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_11_LOCKBIT_0X2AE_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_12_LOCKBIT_0X2B0_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_12_LOCKBIT_0X2B0_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_12_LOCKBIT_0X2B0_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_13_LOCKBIT_0X2B4_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_13_LOCKBIT_0X2B4_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_13_LOCKBIT_0X2B4_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_14_LOCKBIT_0X2B5_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_14_LOCKBIT_0X2B5_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_14_LOCKBIT_0X2B5_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_LOCK_BIT_REGION_15_LOCKBIT_0X2B6_LSP  0u
#define DV1_OTP_LOCK_BIT_REGION_15_LOCKBIT_0X2B6_LEN  32u
#define DV1_OTP_LOCK_BIT_REGION_15_LOCKBIT_0X2B6_TYPE DV1_FIELD_TYPE_RO

#define DV1_OTP_DUMMY_REG_00_OTP_DUMMY_REG_LSP  0u
#define DV1_OTP_DUMMY_REG_00_OTP_DUMMY_REG_LEN  32u
#define DV1_OTP_DUMMY_REG_00_OTP_DUMMY_REG_TYPE DV1_FIELD_TYPE_RW

#define DV1_OTP_FAULT_INJECTION_00_RG_OTP_FAULT_INJECTION_EN_LSP  0u
#define DV1_OTP_FAULT_INJECTION_00_RG_OTP_FAULT_INJECTION_EN_LEN  1u
#define DV1_OTP_FAULT_INJECTION_00_RG_OTP_FAULT_INJECTION_EN_TYPE DV1_FIELD_TYPE_RW

#define DV1_OTP_FAULT_INJECTION_01_RG_OTP_FAULT_INJECTION_DATA0_LSP  0u
#define DV1_OTP_FAULT_INJECTION_01_RG_OTP_FAULT_INJECTION_DATA0_LEN  32u
#define DV1_OTP_FAULT_INJECTION_01_RG_OTP_FAULT_INJECTION_DATA0_TYPE DV1_FIELD_TYPE_RW

#define DV1_OTP_FAULT_INJECTION_02_RG_OTP_FAULT_INJECTION_DATA1_LSP  0u
#define DV1_OTP_FAULT_INJECTION_02_RG_OTP_FAULT_INJECTION_DATA1_LEN  32u
#define DV1_OTP_FAULT_INJECTION_02_RG_OTP_FAULT_INJECTION_DATA1_TYPE DV1_FIELD_TYPE_RW

#define DV1_OTP_FAULT_INJECTION_03_RG_OTP_FAULT_INJECTION_DATA2_LSP  0u
#define DV1_OTP_FAULT_INJECTION_03_RG_OTP_FAULT_INJECTION_DATA2_LEN  32u
#define DV1_OTP_FAULT_INJECTION_03_RG_OTP_FAULT_INJECTION_DATA2_TYPE DV1_FIELD_TYPE_RW

#define DV1_OTP_INDIRECT_OCCUPY_STATUS_REG_RG_OTP_INDIRECT_OCCUPY_STATUS_LSP  0u
#define DV1_OTP_INDIRECT_OCCUPY_STATUS_REG_RG_OTP_INDIRECT_OCCUPY_STATUS_LEN  32u
#define DV1_OTP_INDIRECT_OCCUPY_STATUS_REG_RG_OTP_INDIRECT_OCCUPY_STATUS_TYPE DV1_FIELD_TYPE_RW

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_CPU_EFUSE_H_ */