/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_CPU_VARIABLE_H_
#define DV1_RTKAS_REG_FIELD_FILE_CPU_VARIABLE_H_

#ifdef DV1_FILE_CPU_VARIABLE
/* File: CPU Variable */
#define DV1_INTERNAL_CPU_VARIABLE20_VAR_REG_20_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE20_VAR_REG_20_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE20_VAR_REG_20_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE21_VAR_REG_21_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE21_VAR_REG_21_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE21_VAR_REG_21_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE22_VAR_REG_22_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE22_VAR_REG_22_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE22_VAR_REG_22_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE23_VAR_REG_23_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE23_VAR_REG_23_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE23_VAR_REG_23_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE24_VAR_REG_24_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE24_VAR_REG_24_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE24_VAR_REG_24_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE25_VAR_REG_25_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE25_VAR_REG_25_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE25_VAR_REG_25_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE26_VAR_REG_26_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE26_VAR_REG_26_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE26_VAR_REG_26_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE27_VAR_REG_27_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE27_VAR_REG_27_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE27_VAR_REG_27_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE28_VAR_REG_28_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE28_VAR_REG_28_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE28_VAR_REG_28_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE29_VAR_REG_29_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE29_VAR_REG_29_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE29_VAR_REG_29_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE30_VAR_REG_30_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE30_VAR_REG_30_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE30_VAR_REG_30_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE31_VAR_REG_31_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE31_VAR_REG_31_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE31_VAR_REG_31_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE32_VAR_REG_32_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE32_VAR_REG_32_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE32_VAR_REG_32_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE33_VAR_REG_33_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE33_VAR_REG_33_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE33_VAR_REG_33_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE34_VAR_REG_34_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE34_VAR_REG_34_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE34_VAR_REG_34_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE35_VAR_REG_35_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE35_VAR_REG_35_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE35_VAR_REG_35_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE36_VAR_REG_36_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE36_VAR_REG_36_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE36_VAR_REG_36_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE37_VAR_REG_37_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE37_VAR_REG_37_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE37_VAR_REG_37_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE38_VAR_REG_38_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE38_VAR_REG_38_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE38_VAR_REG_38_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE39_VAR_REG_39_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE39_VAR_REG_39_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE39_VAR_REG_39_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE40_VAR_REG_40_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE40_VAR_REG_40_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE40_VAR_REG_40_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE41_VAR_REG_41_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE41_VAR_REG_41_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE41_VAR_REG_41_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE42_VAR_REG_42_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE42_VAR_REG_42_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE42_VAR_REG_42_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE43_VAR_REG_43_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE43_VAR_REG_43_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE43_VAR_REG_43_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE44_VAR_REG_44_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE44_VAR_REG_44_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE44_VAR_REG_44_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE45_VAR_REG_45_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE45_VAR_REG_45_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE45_VAR_REG_45_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE46_VAR_REG_46_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE46_VAR_REG_46_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE46_VAR_REG_46_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE47_VAR_REG_47_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE47_VAR_REG_47_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE47_VAR_REG_47_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE48_VAR_REG_48_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE48_VAR_REG_48_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE48_VAR_REG_48_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE49_VAR_REG_49_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE49_VAR_REG_49_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE49_VAR_REG_49_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE50_VAR_REG_50_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE50_VAR_REG_50_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE50_VAR_REG_50_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE51_VAR_REG_51_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE51_VAR_REG_51_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE51_VAR_REG_51_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE52_VAR_REG_52_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE52_VAR_REG_52_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE52_VAR_REG_52_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE53_VAR_REG_53_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE53_VAR_REG_53_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE53_VAR_REG_53_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE54_VAR_REG_54_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE54_VAR_REG_54_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE54_VAR_REG_54_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE55_VAR_REG_55_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE55_VAR_REG_55_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE55_VAR_REG_55_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE56_VAR_REG_56_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE56_VAR_REG_56_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE56_VAR_REG_56_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE57_VAR_REG_57_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE57_VAR_REG_57_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE57_VAR_REG_57_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE58_VAR_REG_58_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE58_VAR_REG_58_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE58_VAR_REG_58_TYPE DV1_FIELD_TYPE_RWS

#define DV1_INTERNAL_CPU_VARIABLE59_VAR_REG_59_LSP  0u
#define DV1_INTERNAL_CPU_VARIABLE59_VAR_REG_59_LEN  32u
#define DV1_INTERNAL_CPU_VARIABLE59_VAR_REG_59_TYPE DV1_FIELD_TYPE_RWS

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_CPU_VARIABLE_H_ */