/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_PORT_BASED_VLAN_H_
#define DV1_RTKAS_REG_FIELD_FILE_PORT_BASED_VLAN_H_

#ifdef DV1_FILE_PORT_BASED_VLAN
/* File: Port_based DV1_VLAN */
#define DV1_VLAN_PORTROLE_CONTROL_PORTROLE_LSP  0u
#define DV1_VLAN_PORTROLE_CONTROL_PORTROLE_LEN  16u
#define DV1_VLAN_PORTROLE_CONTROL_PORTROLE_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT0_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT0_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT0_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT0_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT0_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT0_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT0_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT0_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT0_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT0_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT0_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT0_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT0_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT0_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT0_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT0_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT0_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT0_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT1_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT1_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT1_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT1_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT1_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT1_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT1_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT1_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT1_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT1_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT1_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT1_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT1_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT1_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT1_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT1_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT1_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT1_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT2_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT2_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT2_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT2_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT2_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT2_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT2_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT2_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT2_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT2_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT2_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT2_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT2_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT2_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT2_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT2_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT2_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT2_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT3_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT3_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT3_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT3_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT3_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT3_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT3_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT3_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT3_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT3_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT3_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT3_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT3_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT3_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT3_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT3_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT3_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT3_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT4_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT4_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT4_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT4_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT4_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT4_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT4_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT4_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT4_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT4_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT4_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT4_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT4_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT4_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT4_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT4_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT4_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT4_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT5_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT5_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT5_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT5_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT5_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT5_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT5_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT5_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT5_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT5_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT5_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT5_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT5_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT5_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT5_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT5_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT5_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT5_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT6_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT6_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT6_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT6_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT6_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT6_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT6_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT6_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT6_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT6_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT6_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT6_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT6_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT6_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT6_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT6_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT6_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT6_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT7_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT7_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT7_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT7_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT7_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT7_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT7_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT7_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT7_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT7_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT7_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT7_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT7_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT7_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT7_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT7_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT7_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT7_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT8_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT8_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT8_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT8_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT8_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT8_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT8_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT8_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT8_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT8_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT8_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT8_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT8_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT8_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT8_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT8_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT8_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT8_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT9_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT9_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT9_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT9_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT9_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT9_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT9_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT9_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT9_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT9_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT9_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT9_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT9_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT9_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT9_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT9_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT9_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT9_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT10_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT10_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT10_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT10_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT10_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT10_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT10_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT10_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT10_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT10_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT10_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT10_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT10_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT10_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT10_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT10_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT10_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT10_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT11_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT11_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT11_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT11_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT11_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT11_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT11_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT11_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT11_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT11_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT11_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT11_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT11_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT11_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT11_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT11_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT11_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT11_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT12_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT12_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT12_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT12_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT12_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT12_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT12_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT12_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT12_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT12_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT12_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT12_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT12_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT12_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT12_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT12_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT12_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT12_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT13_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT13_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT13_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT13_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT13_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT13_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT13_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT13_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT13_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT13_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT13_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT13_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT13_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT13_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT13_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT13_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT13_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT13_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT14_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT14_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT14_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT14_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT14_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT14_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT14_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT14_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT14_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT14_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT14_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT14_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT14_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT14_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT14_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT14_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT14_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT14_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#define DV1_PORT15_VLAN_CONTROL_PIVID_LSP  20u
#define DV1_PORT15_VLAN_CONTROL_PIVID_LEN  12u
#define DV1_PORT15_VLAN_CONTROL_PIVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT15_VLAN_CONTROL_PIDEI_LSP  19u
#define DV1_PORT15_VLAN_CONTROL_PIDEI_LEN  1u
#define DV1_PORT15_VLAN_CONTROL_PIDEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT15_VLAN_CONTROL_PIPRI_LSP  16u
#define DV1_PORT15_VLAN_CONTROL_PIPRI_LEN  3u
#define DV1_PORT15_VLAN_CONTROL_PIPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT15_VLAN_CONTROL_POVID_LSP  4u
#define DV1_PORT15_VLAN_CONTROL_POVID_LEN  12u
#define DV1_PORT15_VLAN_CONTROL_POVID_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT15_VLAN_CONTROL_PODEI_LSP  3u
#define DV1_PORT15_VLAN_CONTROL_PODEI_LEN  1u
#define DV1_PORT15_VLAN_CONTROL_PODEI_TYPE DV1_FIELD_TYPE_RW
#define DV1_PORT15_VLAN_CONTROL_POPRI_LSP  0u
#define DV1_PORT15_VLAN_CONTROL_POPRI_LEN  3u
#define DV1_PORT15_VLAN_CONTROL_POPRI_TYPE DV1_FIELD_TYPE_RW

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_PORT_BASED_VLAN_H_ */