/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_SAFETY_H_
#define DV1_RTKAS_REG_FIELD_FILE_SAFETY_H_

#ifdef DV1_FILE_SAFETY
/* File: Safety */
#define DV1_SAFE_IRPT_IP_SPF_0_SAFE_IRPT_IP_SPF_0_LSP  0u
#define DV1_SAFE_IRPT_IP_SPF_0_SAFE_IRPT_IP_SPF_0_LEN  21u
#define DV1_SAFE_IRPT_IP_SPF_0_SAFE_IRPT_IP_SPF_0_TYPE DV1_FIELD_TYPE_RW1C

#define DV1_SAFE_IRPT_IP_LF_0_SAFE_IRPT_IP_LF_0_LSP  0u
#define DV1_SAFE_IRPT_IP_LF_0_SAFE_IRPT_IP_LF_0_LEN  21u
#define DV1_SAFE_IRPT_IP_LF_0_SAFE_IRPT_IP_LF_0_TYPE DV1_FIELD_TYPE_RW1C

#define DV1_SAFE_IRPT_IE_SPF_0_SAFE_IRPT_IE_SPF_0_LSP  0u
#define DV1_SAFE_IRPT_IE_SPF_0_SAFE_IRPT_IE_SPF_0_LEN  21u
#define DV1_SAFE_IRPT_IE_SPF_0_SAFE_IRPT_IE_SPF_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_SAFE_IRPT_IE_LF_0_SAFE_IRPT_IE_LF_0_LSP  0u
#define DV1_SAFE_IRPT_IE_LF_0_SAFE_IRPT_IE_LF_0_LEN  21u
#define DV1_SAFE_IRPT_IE_LF_0_SAFE_IRPT_IE_LF_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_DISB_SAFETY_REG_0_DISB_SAFETY_FLAG_LSP    31u
#define DV1_DISB_SAFETY_REG_0_DISB_SAFETY_FLAG_LEN    1u
#define DV1_DISB_SAFETY_REG_0_DISB_SAFETY_FLAG_TYPE   DV1_FIELD_TYPE_RO
#define DV1_DISB_SAFETY_REG_0_DISB_SAFETY_TD_SEL_LSP  1u
#define DV1_DISB_SAFETY_REG_0_DISB_SAFETY_TD_SEL_LEN  3u
#define DV1_DISB_SAFETY_REG_0_DISB_SAFETY_TD_SEL_TYPE DV1_FIELD_TYPE_RW
#define DV1_DISB_SAFETY_REG_0_DISB_SAFETY_EN_LSP      0u
#define DV1_DISB_SAFETY_REG_0_DISB_SAFETY_EN_LEN      1u
#define DV1_DISB_SAFETY_REG_0_DISB_SAFETY_EN_TYPE     DV1_FIELD_TYPE_RW

#define DV1_DISB_SAFETY_REG_1_DISB_SAFETY_LOG_LSP  0u
#define DV1_DISB_SAFETY_REG_1_DISB_SAFETY_LOG_LEN  32u
#define DV1_DISB_SAFETY_REG_1_DISB_SAFETY_LOG_TYPE DV1_FIELD_TYPE_RO

#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_CMP_CNT_LSP         16u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_CMP_CNT_LEN         16u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_CMP_CNT_TYPE        DV1_FIELD_TYPE_RW
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TIMEOUT_TARGET_LSP  8u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TIMEOUT_TARGET_LEN  8u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TIMEOUT_TARGET_TYPE DV1_FIELD_TYPE_RW
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TARGET_PORT_LSP     4u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TARGET_PORT_LEN     4u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TARGET_PORT_TYPE    DV1_FIELD_TYPE_RW
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TIME_UNIT_LSP       2u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TIME_UNIT_LEN       2u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TIME_UNIT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TASK_DONE_LSP       1u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TASK_DONE_LEN       1u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TASK_DONE_TYPE      DV1_FIELD_TYPE_RO
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TASK_EN_LSP         0u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TASK_EN_LEN         1u
#define DV1_MAC_TXRX_SAFETY_REG_TX_SAFETY_MAC_TX_TASK_EN_TYPE        DV1_FIELD_TYPE_RW

#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_CMP_CNT_LSP         16u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_CMP_CNT_LEN         16u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_CMP_CNT_TYPE        DV1_FIELD_TYPE_RW
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TIMEOUT_TARGET_LSP  8u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TIMEOUT_TARGET_LEN  8u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TIMEOUT_TARGET_TYPE DV1_FIELD_TYPE_RW
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TARGET_PORT_LSP     4u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TARGET_PORT_LEN     4u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TARGET_PORT_TYPE    DV1_FIELD_TYPE_RW
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TIME_UNIT_LSP       2u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TIME_UNIT_LEN       2u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TIME_UNIT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TASK_DONE_LSP       1u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TASK_DONE_LEN       1u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TASK_DONE_TYPE      DV1_FIELD_TYPE_RO
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TASK_EN_LSP         0u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TASK_EN_LEN         1u
#define DV1_MAC_TXRX_SAFETY_REG_RX_SAFETY_MAC_RX_TASK_EN_TYPE        DV1_FIELD_TYPE_RW

#define DV1_SAFE_IRPT_IP_MIB_RG_MIB_IP_GL_LSP  0u
#define DV1_SAFE_IRPT_IP_MIB_RG_MIB_IP_GL_LEN  3u
#define DV1_SAFE_IRPT_IP_MIB_RG_MIB_IP_GL_TYPE DV1_FIELD_TYPE_RO

#define DV1_SAFE_IRPT_IE_MIB_RG_MIB_IE_GL_LSP  0u
#define DV1_SAFE_IRPT_IE_MIB_RG_MIB_IE_GL_LEN  3u
#define DV1_SAFE_IRPT_IE_MIB_RG_MIB_IE_GL_TYPE DV1_FIELD_TYPE_RW

#define DV1_MIB_IRPT_IP_0_RG_MIB_IP_0_LSP  0u
#define DV1_MIB_IRPT_IP_0_RG_MIB_IP_0_LEN  27u
#define DV1_MIB_IRPT_IP_0_RG_MIB_IP_0_TYPE DV1_FIELD_TYPE_RW1C

#define DV1_MIB_IRPT_IE_0_RG_MIB_IE_0_LSP  0u
#define DV1_MIB_IRPT_IE_0_RG_MIB_IE_0_LEN  27u
#define DV1_MIB_IRPT_IE_0_RG_MIB_IE_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_MIB_IRPT_IP_1_RG_MIB_IP_1_LSP  0u
#define DV1_MIB_IRPT_IP_1_RG_MIB_IP_1_LEN  11u
#define DV1_MIB_IRPT_IP_1_RG_MIB_IP_1_TYPE DV1_FIELD_TYPE_RW1C

#define DV1_MIB_IRPT_IE_1_RG_MIB_IE_1_LSP  0u
#define DV1_MIB_IRPT_IE_1_RG_MIB_IE_1_LEN  11u
#define DV1_MIB_IRPT_IE_1_RG_MIB_IE_1_TYPE DV1_FIELD_TYPE_RW

#define DV1_MIB_IRPT_IP_2_RG_MIB_IP_2_LSP  0u
#define DV1_MIB_IRPT_IP_2_RG_MIB_IP_2_LEN  24u
#define DV1_MIB_IRPT_IP_2_RG_MIB_IP_2_TYPE DV1_FIELD_TYPE_RW1C

#define DV1_MIB_IRPT_IE_2_RG_MIB_IE_2_LSP  0u
#define DV1_MIB_IRPT_IE_2_RG_MIB_IE_2_LEN  24u
#define DV1_MIB_IRPT_IE_2_RG_MIB_IE_2_TYPE DV1_FIELD_TYPE_RW

#define DV1_SAFE_IRPT_IP_DISB_RG_DISB_IP_GL_LSP  0u
#define DV1_SAFE_IRPT_IP_DISB_RG_DISB_IP_GL_LEN  2u
#define DV1_SAFE_IRPT_IP_DISB_RG_DISB_IP_GL_TYPE DV1_FIELD_TYPE_RO

#define DV1_SAFE_IRPT_IE_DISB_RG_DISB_IE_GL_LSP  0u
#define DV1_SAFE_IRPT_IE_DISB_RG_DISB_IE_GL_LEN  2u
#define DV1_SAFE_IRPT_IE_DISB_RG_DISB_IE_GL_TYPE DV1_FIELD_TYPE_RW

#define DV1_DISB_IRPT_IP_0_RG_DISB_IP_0_LSP  0u
#define DV1_DISB_IRPT_IP_0_RG_DISB_IP_0_LEN  16u
#define DV1_DISB_IRPT_IP_0_RG_DISB_IP_0_TYPE DV1_FIELD_TYPE_RW1C

#define DV1_DISB_IRPT_IE_0_RG_DISB_IE_0_LSP  0u
#define DV1_DISB_IRPT_IE_0_RG_DISB_IE_0_LEN  16u
#define DV1_DISB_IRPT_IE_0_RG_DISB_IE_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_DISB_IRPT_IP_1_RG_DISB_IP_1_LSP  0u
#define DV1_DISB_IRPT_IP_1_RG_DISB_IP_1_LEN  16u
#define DV1_DISB_IRPT_IP_1_RG_DISB_IP_1_TYPE DV1_FIELD_TYPE_RW1C

#define DV1_DISB_IRPT_IE_1_RG_DISB_IE_1_LSP  0u
#define DV1_DISB_IRPT_IE_1_RG_DISB_IE_1_LEN  16u
#define DV1_DISB_IRPT_IE_1_RG_DISB_IE_1_TYPE DV1_FIELD_TYPE_RW

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_SAFETY_H_ */