/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_CLKRST_H_
#define DV1_RTKAS_REG_FIELD_FILE_CLKRST_H_

#ifdef DV1_FILE_CLKRST
/* File: clkrst */
#define DV1_CLK_RST_CLOCK_SELECTION_RG_CLK_SPI_MACPHY_1_SEL_LSP  13u
#define DV1_CLK_RST_CLOCK_SELECTION_RG_CLK_SPI_MACPHY_1_SEL_LEN  1u
#define DV1_CLK_RST_CLOCK_SELECTION_RG_CLK_SPI_MACPHY_1_SEL_TYPE DV1_FIELD_TYPE_RW
#define DV1_CLK_RST_CLOCK_SELECTION_RG_SPI_MACPHY_1_EN_LSP       12u
#define DV1_CLK_RST_CLOCK_SELECTION_RG_SPI_MACPHY_1_EN_LEN       1u
#define DV1_CLK_RST_CLOCK_SELECTION_RG_SPI_MACPHY_1_EN_TYPE      DV1_FIELD_TYPE_RW
#define DV1_CLK_RST_CLOCK_SELECTION_RG_CLK_SPI_MACPHY_0_SEL_LSP  9u
#define DV1_CLK_RST_CLOCK_SELECTION_RG_CLK_SPI_MACPHY_0_SEL_LEN  1u
#define DV1_CLK_RST_CLOCK_SELECTION_RG_CLK_SPI_MACPHY_0_SEL_TYPE DV1_FIELD_TYPE_RW
#define DV1_CLK_RST_CLOCK_SELECTION_RG_SPI_MACPHY_0_EN_LSP       8u
#define DV1_CLK_RST_CLOCK_SELECTION_RG_SPI_MACPHY_0_EN_LEN       1u
#define DV1_CLK_RST_CLOCK_SELECTION_RG_SPI_MACPHY_0_EN_TYPE      DV1_FIELD_TYPE_RW
#define DV1_CLK_RST_CLOCK_SELECTION_RG_DIV_FACTOR_CLK_CPU_LSP    4u
#define DV1_CLK_RST_CLOCK_SELECTION_RG_DIV_FACTOR_CLK_CPU_LEN    2u
#define DV1_CLK_RST_CLOCK_SELECTION_RG_DIV_FACTOR_CLK_CPU_TYPE   DV1_FIELD_TYPE_RW
#define DV1_CLK_RST_CLOCK_SELECTION_SEL_CLK_SPIC_SRC_LSP         0u
#define DV1_CLK_RST_CLOCK_SELECTION_SEL_CLK_SPIC_SRC_LEN         3u
#define DV1_CLK_RST_CLOCK_SELECTION_SEL_CLK_SPIC_SRC_TYPE        DV1_FIELD_TYPE_RW

#define DV1_CLK_RST_IP_ENABLE_EN_CLK_SYS_ROOT_LSP  2u
#define DV1_CLK_RST_IP_ENABLE_EN_CLK_SYS_ROOT_LEN  1u
#define DV1_CLK_RST_IP_ENABLE_EN_CLK_SYS_ROOT_TYPE DV1_FIELD_TYPE_RW
#define DV1_CLK_RST_IP_ENABLE_EN_CLK_SPIC_LSP      1u
#define DV1_CLK_RST_IP_ENABLE_EN_CLK_SPIC_LEN      1u
#define DV1_CLK_RST_IP_ENABLE_EN_CLK_SPIC_TYPE     DV1_FIELD_TYPE_RW
#define DV1_CLK_RST_IP_ENABLE_EN_CLK_OTP_CTL_LSP   0u
#define DV1_CLK_RST_IP_ENABLE_EN_CLK_OTP_CTL_LEN   1u
#define DV1_CLK_RST_IP_ENABLE_EN_CLK_OTP_CTL_TYPE  DV1_FIELD_TYPE_RW

#define DV1_CLKRST_RSV_0_CLKRST_RSV_0_LSP  0u
#define DV1_CLKRST_RSV_0_CLKRST_RSV_0_LEN  32u
#define DV1_CLKRST_RSV_0_CLKRST_RSV_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_1_CLKRST_RSV_1_LSP  0u
#define DV1_CLKRST_RSV_1_CLKRST_RSV_1_LEN  32u
#define DV1_CLKRST_RSV_1_CLKRST_RSV_1_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_2_CLKRST_RSV_2_LSP  0u
#define DV1_CLKRST_RSV_2_CLKRST_RSV_2_LEN  32u
#define DV1_CLKRST_RSV_2_CLKRST_RSV_2_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_3_CLKRST_RSV_3_LSP  0u
#define DV1_CLKRST_RSV_3_CLKRST_RSV_3_LEN  32u
#define DV1_CLKRST_RSV_3_CLKRST_RSV_3_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_4_CLKRST_RSV_4_LSP  0u
#define DV1_CLKRST_RSV_4_CLKRST_RSV_4_LEN  32u
#define DV1_CLKRST_RSV_4_CLKRST_RSV_4_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_5_CLKRST_RSV_5_LSP  0u
#define DV1_CLKRST_RSV_5_CLKRST_RSV_5_LEN  32u
#define DV1_CLKRST_RSV_5_CLKRST_RSV_5_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_6_CLKRST_RSV_6_LSP  0u
#define DV1_CLKRST_RSV_6_CLKRST_RSV_6_LEN  32u
#define DV1_CLKRST_RSV_6_CLKRST_RSV_6_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_7_CLKRST_RSV_7_LSP  0u
#define DV1_CLKRST_RSV_7_CLKRST_RSV_7_LEN  32u
#define DV1_CLKRST_RSV_7_CLKRST_RSV_7_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_8_CLKRST_RSV_8_LSP  0u
#define DV1_CLKRST_RSV_8_CLKRST_RSV_8_LEN  32u
#define DV1_CLKRST_RSV_8_CLKRST_RSV_8_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_9_CLKRST_RSV_9_LSP  0u
#define DV1_CLKRST_RSV_9_CLKRST_RSV_9_LEN  32u
#define DV1_CLKRST_RSV_9_CLKRST_RSV_9_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_10_CLKRST_RSV_10_LSP  0u
#define DV1_CLKRST_RSV_10_CLKRST_RSV_10_LEN  32u
#define DV1_CLKRST_RSV_10_CLKRST_RSV_10_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_11_CLKRST_RSV_11_LSP  0u
#define DV1_CLKRST_RSV_11_CLKRST_RSV_11_LEN  32u
#define DV1_CLKRST_RSV_11_CLKRST_RSV_11_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_12_CLKRST_RSV_12_LSP  0u
#define DV1_CLKRST_RSV_12_CLKRST_RSV_12_LEN  32u
#define DV1_CLKRST_RSV_12_CLKRST_RSV_12_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_13_CLKRST_RSV_13_LSP  0u
#define DV1_CLKRST_RSV_13_CLKRST_RSV_13_LEN  32u
#define DV1_CLKRST_RSV_13_CLKRST_RSV_13_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_14_CLKRST_RSV_14_LSP  0u
#define DV1_CLKRST_RSV_14_CLKRST_RSV_14_LEN  32u
#define DV1_CLKRST_RSV_14_CLKRST_RSV_14_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_15_CLKRST_RSV_15_LSP  0u
#define DV1_CLKRST_RSV_15_CLKRST_RSV_15_LEN  32u
#define DV1_CLKRST_RSV_15_CLKRST_RSV_15_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_16_CLKRST_RSV_16_LSP  0u
#define DV1_CLKRST_RSV_16_CLKRST_RSV_16_LEN  32u
#define DV1_CLKRST_RSV_16_CLKRST_RSV_16_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_17_CLKRST_RSV_17_LSP  0u
#define DV1_CLKRST_RSV_17_CLKRST_RSV_17_LEN  32u
#define DV1_CLKRST_RSV_17_CLKRST_RSV_17_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_18_CLKRST_RSV_18_LSP  0u
#define DV1_CLKRST_RSV_18_CLKRST_RSV_18_LEN  32u
#define DV1_CLKRST_RSV_18_CLKRST_RSV_18_TYPE DV1_FIELD_TYPE_RO

#define DV1_CLKRST_RSV_19_CLKRST_RSV_19_LSP  0u
#define DV1_CLKRST_RSV_19_CLKRST_RSV_19_LEN  32u
#define DV1_CLKRST_RSV_19_CLKRST_RSV_19_TYPE DV1_FIELD_TYPE_RO

#define DV1_CPU_CLOCK_CONTROL_RG_DIV_FACTOR_CLK_CPU_LSP  0u
#define DV1_CPU_CLOCK_CONTROL_RG_DIV_FACTOR_CLK_CPU_LEN  4u
#define DV1_CPU_CLOCK_CONTROL_RG_DIV_FACTOR_CLK_CPU_TYPE DV1_FIELD_TYPE_RW

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_CLKRST_H_ */