/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_CPU_AUX_VSFC_H_
#define DV1_RTKAS_REG_FIELD_FILE_CPU_AUX_VSFC_H_

#ifdef DV1_FILE_CPU_AUX_VSFC
/* File: cpu_aux_vsfc */
#define DV1_VSFC_CTRL_UVLO_DEG_FILTER_H2L_LSP  28u
#define DV1_VSFC_CTRL_UVLO_DEG_FILTER_H2L_LEN  3u
#define DV1_VSFC_CTRL_UVLO_DEG_FILTER_H2L_TYPE DV1_FIELD_TYPE_RW
#define DV1_VSFC_CTRL_FSS_DEG_FILTER_H2L_LSP   24u
#define DV1_VSFC_CTRL_FSS_DEG_FILTER_H2L_LEN   3u
#define DV1_VSFC_CTRL_FSS_DEG_FILTER_H2L_TYPE  DV1_FIELD_TYPE_RW
#define DV1_VSFC_CTRL_CPU_DEG_FILTER_LSP       20u
#define DV1_VSFC_CTRL_CPU_DEG_FILTER_LEN       3u
#define DV1_VSFC_CTRL_CPU_DEG_FILTER_TYPE      DV1_FIELD_TYPE_RW
#define DV1_VSFC_CTRL_FSS_DEG_FILTER_LSP       16u
#define DV1_VSFC_CTRL_FSS_DEG_FILTER_LEN       3u
#define DV1_VSFC_CTRL_FSS_DEG_FILTER_TYPE      DV1_FIELD_TYPE_RW
#define DV1_VSFC_CTRL_UVLO_DEG_FILTER_LSP      12u
#define DV1_VSFC_CTRL_UVLO_DEG_FILTER_LEN      3u
#define DV1_VSFC_CTRL_UVLO_DEG_FILTER_TYPE     DV1_FIELD_TYPE_RW
#define DV1_VSFC_CTRL_TRIG_SEL_LSP             8u
#define DV1_VSFC_CTRL_TRIG_SEL_LEN             3u
#define DV1_VSFC_CTRL_TRIG_SEL_TYPE            DV1_FIELD_TYPE_RW
#define DV1_VSFC_CTRL_DIV_SEL_LSP              4u
#define DV1_VSFC_CTRL_DIV_SEL_LEN              1u
#define DV1_VSFC_CTRL_DIV_SEL_TYPE             DV1_FIELD_TYPE_RW
#define DV1_VSFC_CTRL_GLB_EN_LSP               0u
#define DV1_VSFC_CTRL_GLB_EN_LEN               1u
#define DV1_VSFC_CTRL_GLB_EN_TYPE              DV1_FIELD_TYPE_RW

#define DV1_VSFC_CTRL2_SHFT_ITVL_LSP  4u
#define DV1_VSFC_CTRL2_SHFT_ITVL_LEN  4u
#define DV1_VSFC_CTRL2_SHFT_ITVL_TYPE DV1_FIELD_TYPE_RW
#define DV1_VSFC_CTRL2_FORCE_DIV_LSP  0u
#define DV1_VSFC_CTRL2_FORCE_DIV_LEN  1u
#define DV1_VSFC_CTRL2_FORCE_DIV_TYPE DV1_FIELD_TYPE_RW

#define DV1_VSFC_STATUS_NORMAL_ST_LSP  1u
#define DV1_VSFC_STATUS_NORMAL_ST_LEN  1u
#define DV1_VSFC_STATUS_NORMAL_ST_TYPE DV1_FIELD_TYPE_RO
#define DV1_VSFC_STATUS_IDLE_ST_LSP    0u
#define DV1_VSFC_STATUS_IDLE_ST_LEN    1u
#define DV1_VSFC_STATUS_IDLE_ST_TYPE   DV1_FIELD_TYPE_RO

#define DV1_VSFC_TRIG_CTRL_CORE_IDLE_DIV_EN_LSP  16u
#define DV1_VSFC_TRIG_CTRL_CORE_IDLE_DIV_EN_LEN  1u
#define DV1_VSFC_TRIG_CTRL_CORE_IDLE_DIV_EN_TYPE DV1_FIELD_TYPE_RW
#define DV1_VSFC_TRIG_CTRL_CORE_MIN_LSP          8u
#define DV1_VSFC_TRIG_CTRL_CORE_MIN_LEN          2u
#define DV1_VSFC_TRIG_CTRL_CORE_MIN_TYPE         DV1_FIELD_TYPE_RW
#define DV1_VSFC_TRIG_CTRL_FSS_MIN_LSP           4u
#define DV1_VSFC_TRIG_CTRL_FSS_MIN_LEN           3u
#define DV1_VSFC_TRIG_CTRL_FSS_MIN_TYPE          DV1_FIELD_TYPE_RW
#define DV1_VSFC_TRIG_CTRL_UVLO_MIN_LSP          0u
#define DV1_VSFC_TRIG_CTRL_UVLO_MIN_LEN          3u
#define DV1_VSFC_TRIG_CTRL_UVLO_MIN_TYPE         DV1_FIELD_TYPE_RW

#define DV1_VSFC_RECV_CTRL0_DET_RECV_SEL_LSP  0u
#define DV1_VSFC_RECV_CTRL0_DET_RECV_SEL_LEN  2u
#define DV1_VSFC_RECV_CTRL0_DET_RECV_SEL_TYPE DV1_FIELD_TYPE_RW

#define DV1_VSFC_RECV_CTRL1_LOWF_LSP        16u
#define DV1_VSFC_RECV_CTRL1_LOWF_LEN        16u
#define DV1_VSFC_RECV_CTRL1_LOWF_TYPE       DV1_FIELD_TYPE_RW
#define DV1_VSFC_RECV_CTRL1_CYCLE_LOWF_LSP  0u
#define DV1_VSFC_RECV_CTRL1_CYCLE_LOWF_LEN  16u
#define DV1_VSFC_RECV_CTRL1_CYCLE_LOWF_TYPE DV1_FIELD_TYPE_RW

#define DV1_VSFC_RECV_CTRL2_RECV1_LSP        16u
#define DV1_VSFC_RECV_CTRL2_RECV1_LEN        16u
#define DV1_VSFC_RECV_CTRL2_RECV1_TYPE       DV1_FIELD_TYPE_RWS
#define DV1_VSFC_RECV_CTRL2_CYCLE_RECV1_LSP  0u
#define DV1_VSFC_RECV_CTRL2_CYCLE_RECV1_LEN  16u
#define DV1_VSFC_RECV_CTRL2_CYCLE_RECV1_TYPE DV1_FIELD_TYPE_RW

#define DV1_VSFC_RECV_CTRL3_RECV2_LSP        16u
#define DV1_VSFC_RECV_CTRL3_RECV2_LEN        16u
#define DV1_VSFC_RECV_CTRL3_RECV2_TYPE       DV1_FIELD_TYPE_RW
#define DV1_VSFC_RECV_CTRL3_CYCLE_RECV2_LSP  0u
#define DV1_VSFC_RECV_CTRL3_CYCLE_RECV2_LEN  16u
#define DV1_VSFC_RECV_CTRL3_CYCLE_RECV2_TYPE DV1_FIELD_TYPE_RW

#define DV1_VSFC_RECV_CTRL4_RECV1_SW_LSP  0u
#define DV1_VSFC_RECV_CTRL4_RECV1_SW_LEN  16u
#define DV1_VSFC_RECV_CTRL4_RECV1_SW_TYPE DV1_FIELD_TYPE_RW

#define DV1_VSFC_SW_RECV_RECV_CYCLE_CNT_LSP  16u
#define DV1_VSFC_SW_RECV_RECV_CYCLE_CNT_LEN  16u
#define DV1_VSFC_SW_RECV_RECV_CYCLE_CNT_TYPE DV1_FIELD_TYPE_RO
#define DV1_VSFC_SW_RECV_SW_RECV_EN_LSP      2u
#define DV1_VSFC_SW_RECV_SW_RECV_EN_LEN      1u
#define DV1_VSFC_SW_RECV_SW_RECV_EN_TYPE     DV1_FIELD_TYPE_RW
#define DV1_VSFC_SW_RECV_RECV_ST_LSP         1u
#define DV1_VSFC_SW_RECV_RECV_ST_LEN         1u
#define DV1_VSFC_SW_RECV_RECV_ST_TYPE        DV1_FIELD_TYPE_RO
#define DV1_VSFC_SW_RECV_SW_RECV_FINISH_LSP  0u
#define DV1_VSFC_SW_RECV_SW_RECV_FINISH_LEN  1u
#define DV1_VSFC_SW_RECV_SW_RECV_FINISH_TYPE DV1_FIELD_TYPE_RWS

#define DV1_VSFC_PROF_CTRL0_PROF_EN_LSP        31u
#define DV1_VSFC_PROF_CTRL0_PROF_EN_LEN        1u
#define DV1_VSFC_PROF_CTRL0_PROF_EN_TYPE       DV1_FIELD_TYPE_RWS
#define DV1_VSFC_PROF_CTRL0_PROF_FNSH_SEL_LSP  30u
#define DV1_VSFC_PROF_CTRL0_PROF_FNSH_SEL_LEN  1u
#define DV1_VSFC_PROF_CTRL0_PROF_FNSH_SEL_TYPE DV1_FIELD_TYPE_RW
#define DV1_VSFC_PROF_CTRL0_CYCLE_PROF_LSP     0u
#define DV1_VSFC_PROF_CTRL0_CYCLE_PROF_LEN     20u
#define DV1_VSFC_PROF_CTRL0_CYCLE_PROF_TYPE    DV1_FIELD_TYPE_RW

#define DV1_VSFC_PROF_ST0_OVFL_TRIG_LSP  31u
#define DV1_VSFC_PROF_ST0_OVFL_TRIG_LEN  1u
#define DV1_VSFC_PROF_ST0_OVFL_TRIG_TYPE DV1_FIELD_TYPE_RO
#define DV1_VSFC_PROF_ST0_TRIG_CNT_LSP   0u
#define DV1_VSFC_PROF_ST0_TRIG_CNT_LEN   12u
#define DV1_VSFC_PROF_ST0_TRIG_CNT_TYPE  DV1_FIELD_TYPE_RO

#define DV1_VSFC_PROF_ST1_MIN_DURATION_LSP  16u
#define DV1_VSFC_PROF_ST1_MIN_DURATION_LEN  16u
#define DV1_VSFC_PROF_ST1_MIN_DURATION_TYPE DV1_FIELD_TYPE_RO
#define DV1_VSFC_PROF_ST1_MAX_DURATION_LSP  0u
#define DV1_VSFC_PROF_ST1_MAX_DURATION_LEN  16u
#define DV1_VSFC_PROF_ST1_MAX_DURATION_TYPE DV1_FIELD_TYPE_RO

#define DV1_VSFC_PROF_ST2_OVFL_DURATION_LSP  0u
#define DV1_VSFC_PROF_ST2_OVFL_DURATION_LEN  1u
#define DV1_VSFC_PROF_ST2_OVFL_DURATION_TYPE DV1_FIELD_TYPE_RO

#define DV1_VSFC_PROF_ST3_OVFL_WAKEUP_LSP    31u
#define DV1_VSFC_PROF_ST3_OVFL_WAKEUP_LEN    1u
#define DV1_VSFC_PROF_ST3_OVFL_WAKEUP_TYPE   DV1_FIELD_TYPE_RO
#define DV1_VSFC_PROF_ST3_WAKEUP_CNT_LSP     16u
#define DV1_VSFC_PROF_ST3_WAKEUP_CNT_LEN     12u
#define DV1_VSFC_PROF_ST3_WAKEUP_CNT_TYPE    DV1_FIELD_TYPE_RO
#define DV1_VSFC_PROF_ST3_OVFL_ALL_IDLE_LSP  15u
#define DV1_VSFC_PROF_ST3_OVFL_ALL_IDLE_LEN  1u
#define DV1_VSFC_PROF_ST3_OVFL_ALL_IDLE_TYPE DV1_FIELD_TYPE_RO
#define DV1_VSFC_PROF_ST3_ALL_IDLE_CNT_LSP   0u
#define DV1_VSFC_PROF_ST3_ALL_IDLE_CNT_LEN   12u
#define DV1_VSFC_PROF_ST3_ALL_IDLE_CNT_TYPE  DV1_FIELD_TYPE_RO

#define DV1_VSFC_PROF_ST4_OVFL_VOLT_2ND_DROOP_LSP  15u
#define DV1_VSFC_PROF_ST4_OVFL_VOLT_2ND_DROOP_LEN  1u
#define DV1_VSFC_PROF_ST4_OVFL_VOLT_2ND_DROOP_TYPE DV1_FIELD_TYPE_RO
#define DV1_VSFC_PROF_ST4_VOLT_2ND_DROOP_CNT_LSP   0u
#define DV1_VSFC_PROF_ST4_VOLT_2ND_DROOP_CNT_LEN   12u
#define DV1_VSFC_PROF_ST4_VOLT_2ND_DROOP_CNT_TYPE  DV1_FIELD_TYPE_RO

#define DV1_VSFC_INTST_SW_RECV_INTST_LSP  2u
#define DV1_VSFC_INTST_SW_RECV_INTST_LEN  1u
#define DV1_VSFC_INTST_SW_RECV_INTST_TYPE DV1_FIELD_TYPE_RW1C
#define DV1_VSFC_INTST_PROF_INTST_LSP     1u
#define DV1_VSFC_INTST_PROF_INTST_LEN     1u
#define DV1_VSFC_INTST_PROF_INTST_TYPE    DV1_FIELD_TYPE_RW1C

#define DV1_VSFC_INTEN_SW_RECV_INTEN_LSP  2u
#define DV1_VSFC_INTEN_SW_RECV_INTEN_LEN  1u
#define DV1_VSFC_INTEN_SW_RECV_INTEN_TYPE DV1_FIELD_TYPE_RW
#define DV1_VSFC_INTEN_PROF_INTEN_LSP     1u
#define DV1_VSFC_INTEN_PROF_INTEN_LEN     1u
#define DV1_VSFC_INTEN_PROF_INTEN_TYPE    DV1_FIELD_TYPE_RW

#define DV1_VSFC_SPARE_0_SPARE_REG0_LSP  0u
#define DV1_VSFC_SPARE_0_SPARE_REG0_LEN  32u
#define DV1_VSFC_SPARE_0_SPARE_REG0_TYPE DV1_FIELD_TYPE_RW

#define DV1_VSFC_SPARE_1_SPARE_REG1_LSP  0u
#define DV1_VSFC_SPARE_1_SPARE_REG1_LEN  32u
#define DV1_VSFC_SPARE_1_SPARE_REG1_TYPE DV1_FIELD_TYPE_RW

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_CPU_AUX_VSFC_H_ */