/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_INTERRUPT_TOP_H_
#define DV1_RTKAS_REG_FIELD_FILE_INTERRUPT_TOP_H_

#ifdef DV1_FILE_INTERRUPT_TOP
/* File: Interrupt Top */
#define DV1_RG_INTERRUPT_TOP_VERSION_RG_INTERRUPT_TOP_VERSION_LSP  0u
#define DV1_RG_INTERRUPT_TOP_VERSION_RG_INTERRUPT_TOP_VERSION_LEN  32u
#define DV1_RG_INTERRUPT_TOP_VERSION_RG_INTERRUPT_TOP_VERSION_TYPE DV1_FIELD_TYPE_RW

#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_NUM_LSP              7u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_NUM_LEN              8u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_NUM_TYPE             DV1_FIELD_TYPE_RW
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IP_LSP           6u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IP_LEN           1u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IP_TYPE          DV1_FIELD_TYPE_RWS
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IE_LSP           5u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IE_LEN           1u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_NUM_TOEXTCPU_IE_TYPE          DV1_FIELD_TYPE_RW
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_TRIG_LSP             4u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_TRIG_LEN             1u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_EVENT_TOEXTCPU_TRIG_TYPE            DV1_FIELD_TYPE_RWS
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_SW_INT_PULSE_INTERVAL_LSP           2u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_SW_INT_PULSE_INTERVAL_LEN           2u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_SW_INT_PULSE_INTERVAL_TYPE          DV1_FIELD_TYPE_RW
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_RG_INTERRUPT_TOP_EXT_INTR_MODE_LSP  0u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_RG_INTERRUPT_TOP_EXT_INTR_MODE_LEN  2u
#define DV1_RG_INTERRUPT_TOP_EXT_INTR_MODE_RG_INTERRUPT_TOP_EXT_INTR_MODE_TYPE DV1_FIELD_TYPE_RWS

#define DV1_RG_INTERRUPT_TOP_INTERNAL_IE_RG_INTERRUPT_TOP_INTERNAL_IE_LSP  0u
#define DV1_RG_INTERRUPT_TOP_INTERNAL_IE_RG_INTERRUPT_TOP_INTERNAL_IE_LEN  32u
#define DV1_RG_INTERRUPT_TOP_INTERNAL_IE_RG_INTERRUPT_TOP_INTERNAL_IE_TYPE DV1_FIELD_TYPE_RW

#define DV1_RG_INTERRUPT_TOP_EXTERNAL_IE_RG_INTERRUPT_TOP_EXTERNAL_IE_LSP  0u
#define DV1_RG_INTERRUPT_TOP_EXTERNAL_IE_RG_INTERRUPT_TOP_EXTERNAL_IE_LEN  32u
#define DV1_RG_INTERRUPT_TOP_EXTERNAL_IE_RG_INTERRUPT_TOP_EXTERNAL_IE_TYPE DV1_FIELD_TYPE_RW

#define DV1_RG_INTERRUPT_TOP_INTERNAL_IP_RG_INTERRUPT_TOP_INTERNAL_IP_LSP  0u
#define DV1_RG_INTERRUPT_TOP_INTERNAL_IP_RG_INTERRUPT_TOP_INTERNAL_IP_LEN  32u
#define DV1_RG_INTERRUPT_TOP_INTERNAL_IP_RG_INTERRUPT_TOP_INTERNAL_IP_TYPE DV1_FIELD_TYPE_RO

#define DV1_RG_INTERRUPT_TOP_EXTERNAL_IP_RG_INTERRUPT_TOP_EXTERNAL_IP_LSP  0u
#define DV1_RG_INTERRUPT_TOP_EXTERNAL_IP_RG_INTERRUPT_TOP_EXTERNAL_IP_LEN  32u
#define DV1_RG_INTERRUPT_TOP_EXTERNAL_IP_RG_INTERRUPT_TOP_EXTERNAL_IP_TYPE DV1_FIELD_TYPE_RO

#define DV1_RG_INTERRUPT_TOP_INTERNAL_POLARITY_RG_INTERRUPT_TOP_INTERNAL_POLARITY_LSP  0u
#define DV1_RG_INTERRUPT_TOP_INTERNAL_POLARITY_RG_INTERRUPT_TOP_INTERNAL_POLARITY_LEN  32u
#define DV1_RG_INTERRUPT_TOP_INTERNAL_POLARITY_RG_INTERRUPT_TOP_INTERNAL_POLARITY_TYPE DV1_FIELD_TYPE_RW

#define DV1_RG_INTERRUPT_TOP_EXTERNAL_POLARITY_RG_INTERRUPT_TOP_EXTERNAL_POLARITY_LSP  0u
#define DV1_RG_INTERRUPT_TOP_EXTERNAL_POLARITY_RG_INTERRUPT_TOP_EXTERNAL_POLARITY_LEN  32u
#define DV1_RG_INTERRUPT_TOP_EXTERNAL_POLARITY_RG_INTERRUPT_TOP_EXTERNAL_POLARITY_TYPE DV1_FIELD_TYPE_RW

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_INTERRUPT_TOP_H_ */