/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_RMA_H_
#define DV1_RTKAS_REG_FIELD_FILE_RMA_H_

#ifdef DV1_FILE_RMA
/* File: RMA */
#define DV1_RMA_CONTROL0_0_PORTMASK0_LSP  0u
#define DV1_RMA_CONTROL0_0_PORTMASK0_LEN  16u
#define DV1_RMA_CONTROL0_0_PORTMASK0_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL0_1_CPUMASK0_LSP  0u
#define DV1_RMA_CONTROL0_1_CPUMASK0_LEN  16u
#define DV1_RMA_CONTROL0_1_CPUMASK0_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL0_2_DFRMAPRI0_LSP  6u
#define DV1_RMA_CONTROL0_2_DFRMAPRI0_LEN  1u
#define DV1_RMA_CONTROL0_2_DFRMAPRI0_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL0_2_ACT0_LSP       3u
#define DV1_RMA_CONTROL0_2_ACT0_LEN       3u
#define DV1_RMA_CONTROL0_2_ACT0_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL0_2_RMAPRI0_LSP    0u
#define DV1_RMA_CONTROL0_2_RMAPRI0_LEN    3u
#define DV1_RMA_CONTROL0_2_RMAPRI0_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL1_0_PORTMASK1_LSP  0u
#define DV1_RMA_CONTROL1_0_PORTMASK1_LEN  16u
#define DV1_RMA_CONTROL1_0_PORTMASK1_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL1_1_CPUMASK1_LSP  0u
#define DV1_RMA_CONTROL1_1_CPUMASK1_LEN  16u
#define DV1_RMA_CONTROL1_1_CPUMASK1_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL1_2_DFRMAPRI1_LSP  6u
#define DV1_RMA_CONTROL1_2_DFRMAPRI1_LEN  1u
#define DV1_RMA_CONTROL1_2_DFRMAPRI1_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL1_2_ACT1_LSP       3u
#define DV1_RMA_CONTROL1_2_ACT1_LEN       3u
#define DV1_RMA_CONTROL1_2_ACT1_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL1_2_RMAPRI1_LSP    0u
#define DV1_RMA_CONTROL1_2_RMAPRI1_LEN    3u
#define DV1_RMA_CONTROL1_2_RMAPRI1_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL2_0_PORTMASK2_LSP  0u
#define DV1_RMA_CONTROL2_0_PORTMASK2_LEN  16u
#define DV1_RMA_CONTROL2_0_PORTMASK2_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL2_1_CPUMASK2_LSP  0u
#define DV1_RMA_CONTROL2_1_CPUMASK2_LEN  16u
#define DV1_RMA_CONTROL2_1_CPUMASK2_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL2_2_DFRMAPRI2_LSP  6u
#define DV1_RMA_CONTROL2_2_DFRMAPRI2_LEN  1u
#define DV1_RMA_CONTROL2_2_DFRMAPRI2_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL2_2_ACT2_LSP       3u
#define DV1_RMA_CONTROL2_2_ACT2_LEN       3u
#define DV1_RMA_CONTROL2_2_ACT2_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL2_2_RMAPRI2_LSP    0u
#define DV1_RMA_CONTROL2_2_RMAPRI2_LEN    3u
#define DV1_RMA_CONTROL2_2_RMAPRI2_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL3_0_PORTMASK3_LSP  0u
#define DV1_RMA_CONTROL3_0_PORTMASK3_LEN  16u
#define DV1_RMA_CONTROL3_0_PORTMASK3_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL3_1_CPUMASK3_LSP  0u
#define DV1_RMA_CONTROL3_1_CPUMASK3_LEN  16u
#define DV1_RMA_CONTROL3_1_CPUMASK3_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL3_2_DFRMAPRI3_LSP  6u
#define DV1_RMA_CONTROL3_2_DFRMAPRI3_LEN  1u
#define DV1_RMA_CONTROL3_2_DFRMAPRI3_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL3_2_ACT3_LSP       3u
#define DV1_RMA_CONTROL3_2_ACT3_LEN       3u
#define DV1_RMA_CONTROL3_2_ACT3_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL3_2_RMAPRI3_LSP    0u
#define DV1_RMA_CONTROL3_2_RMAPRI3_LEN    3u
#define DV1_RMA_CONTROL3_2_RMAPRI3_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL4_0_PORTMASK4_LSP  0u
#define DV1_RMA_CONTROL4_0_PORTMASK4_LEN  16u
#define DV1_RMA_CONTROL4_0_PORTMASK4_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL4_1_CPUMASK4_LSP  0u
#define DV1_RMA_CONTROL4_1_CPUMASK4_LEN  16u
#define DV1_RMA_CONTROL4_1_CPUMASK4_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL4_2_DFRMAPRI4_LSP  6u
#define DV1_RMA_CONTROL4_2_DFRMAPRI4_LEN  1u
#define DV1_RMA_CONTROL4_2_DFRMAPRI4_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL4_2_ACT4_LSP       3u
#define DV1_RMA_CONTROL4_2_ACT4_LEN       3u
#define DV1_RMA_CONTROL4_2_ACT4_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL4_2_RMAPRI4_LSP    0u
#define DV1_RMA_CONTROL4_2_RMAPRI4_LEN    3u
#define DV1_RMA_CONTROL4_2_RMAPRI4_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL5_0_PORTMASK5_LSP  0u
#define DV1_RMA_CONTROL5_0_PORTMASK5_LEN  16u
#define DV1_RMA_CONTROL5_0_PORTMASK5_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL5_1_CPUMASK5_LSP  0u
#define DV1_RMA_CONTROL5_1_CPUMASK5_LEN  16u
#define DV1_RMA_CONTROL5_1_CPUMASK5_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL5_2_DFRMAPRI5_LSP  6u
#define DV1_RMA_CONTROL5_2_DFRMAPRI5_LEN  1u
#define DV1_RMA_CONTROL5_2_DFRMAPRI5_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL5_2_ACT5_LSP       3u
#define DV1_RMA_CONTROL5_2_ACT5_LEN       3u
#define DV1_RMA_CONTROL5_2_ACT5_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL5_2_RMAPRI5_LSP    0u
#define DV1_RMA_CONTROL5_2_RMAPRI5_LEN    3u
#define DV1_RMA_CONTROL5_2_RMAPRI5_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL6_0_PORTMASK6_LSP  0u
#define DV1_RMA_CONTROL6_0_PORTMASK6_LEN  16u
#define DV1_RMA_CONTROL6_0_PORTMASK6_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL6_1_CPUMASK6_LSP  0u
#define DV1_RMA_CONTROL6_1_CPUMASK6_LEN  16u
#define DV1_RMA_CONTROL6_1_CPUMASK6_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL6_2_DFRMAPRI6_LSP  6u
#define DV1_RMA_CONTROL6_2_DFRMAPRI6_LEN  1u
#define DV1_RMA_CONTROL6_2_DFRMAPRI6_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL6_2_ACT6_LSP       3u
#define DV1_RMA_CONTROL6_2_ACT6_LEN       3u
#define DV1_RMA_CONTROL6_2_ACT6_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL6_2_RMAPRI6_LSP    0u
#define DV1_RMA_CONTROL6_2_RMAPRI6_LEN    3u
#define DV1_RMA_CONTROL6_2_RMAPRI6_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL7_0_PORTMASK7_LSP  0u
#define DV1_RMA_CONTROL7_0_PORTMASK7_LEN  16u
#define DV1_RMA_CONTROL7_0_PORTMASK7_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL7_1_CPUMASK7_LSP  0u
#define DV1_RMA_CONTROL7_1_CPUMASK7_LEN  16u
#define DV1_RMA_CONTROL7_1_CPUMASK7_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL7_2_DFRMAPRI7_LSP  6u
#define DV1_RMA_CONTROL7_2_DFRMAPRI7_LEN  1u
#define DV1_RMA_CONTROL7_2_DFRMAPRI7_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL7_2_ACT7_LSP       3u
#define DV1_RMA_CONTROL7_2_ACT7_LEN       3u
#define DV1_RMA_CONTROL7_2_ACT7_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL7_2_RMAPRI7_LSP    0u
#define DV1_RMA_CONTROL7_2_RMAPRI7_LEN    3u
#define DV1_RMA_CONTROL7_2_RMAPRI7_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL8_0_PORTMASK8_LSP  0u
#define DV1_RMA_CONTROL8_0_PORTMASK8_LEN  16u
#define DV1_RMA_CONTROL8_0_PORTMASK8_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL8_1_CPUMASK8_LSP  0u
#define DV1_RMA_CONTROL8_1_CPUMASK8_LEN  16u
#define DV1_RMA_CONTROL8_1_CPUMASK8_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL8_2_DFRMAPRI8_LSP  6u
#define DV1_RMA_CONTROL8_2_DFRMAPRI8_LEN  1u
#define DV1_RMA_CONTROL8_2_DFRMAPRI8_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL8_2_ACT8_LSP       3u
#define DV1_RMA_CONTROL8_2_ACT8_LEN       3u
#define DV1_RMA_CONTROL8_2_ACT8_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL8_2_RMAPRI8_LSP    0u
#define DV1_RMA_CONTROL8_2_RMAPRI8_LEN    3u
#define DV1_RMA_CONTROL8_2_RMAPRI8_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL9_0_PORTMASK9_LSP  0u
#define DV1_RMA_CONTROL9_0_PORTMASK9_LEN  16u
#define DV1_RMA_CONTROL9_0_PORTMASK9_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL9_1_CPUMASK9_LSP  0u
#define DV1_RMA_CONTROL9_1_CPUMASK9_LEN  16u
#define DV1_RMA_CONTROL9_1_CPUMASK9_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL9_2_DFRMAPRI9_LSP  6u
#define DV1_RMA_CONTROL9_2_DFRMAPRI9_LEN  1u
#define DV1_RMA_CONTROL9_2_DFRMAPRI9_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL9_2_ACT9_LSP       3u
#define DV1_RMA_CONTROL9_2_ACT9_LEN       3u
#define DV1_RMA_CONTROL9_2_ACT9_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL9_2_RMAPRI9_LSP    0u
#define DV1_RMA_CONTROL9_2_RMAPRI9_LEN    3u
#define DV1_RMA_CONTROL9_2_RMAPRI9_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL10_0_PORTMASK10_LSP  0u
#define DV1_RMA_CONTROL10_0_PORTMASK10_LEN  16u
#define DV1_RMA_CONTROL10_0_PORTMASK10_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL10_1_CPUMASK10_LSP  0u
#define DV1_RMA_CONTROL10_1_CPUMASK10_LEN  16u
#define DV1_RMA_CONTROL10_1_CPUMASK10_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_CONTROL10_2_DFRMAPRI10_LSP  6u
#define DV1_RMA_CONTROL10_2_DFRMAPRI10_LEN  1u
#define DV1_RMA_CONTROL10_2_DFRMAPRI10_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL10_2_ACT10_LSP       3u
#define DV1_RMA_CONTROL10_2_ACT10_LEN       3u
#define DV1_RMA_CONTROL10_2_ACT10_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_CONTROL10_2_RMAPRI10_LSP    0u
#define DV1_RMA_CONTROL10_2_RMAPRI10_LEN    3u
#define DV1_RMA_CONTROL10_2_RMAPRI10_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_PTP_CONTROL0_PTP_PORTMASK_LSP  0u
#define DV1_RMA_PTP_CONTROL0_PTP_PORTMASK_LEN  16u
#define DV1_RMA_PTP_CONTROL0_PTP_PORTMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_PTP_CONTROL1_PTP_CPUMASK_LSP  0u
#define DV1_RMA_PTP_CONTROL1_PTP_CPUMASK_LEN  16u
#define DV1_RMA_PTP_CONTROL1_PTP_CPUMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_PTP_CONTROL2_PTP_DFRMAPRI_LSP  6u
#define DV1_RMA_PTP_CONTROL2_PTP_DFRMAPRI_LEN  1u
#define DV1_RMA_PTP_CONTROL2_PTP_DFRMAPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_PTP_CONTROL2_PTP_ACT_LSP       3u
#define DV1_RMA_PTP_CONTROL2_PTP_ACT_LEN       3u
#define DV1_RMA_PTP_CONTROL2_PTP_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_PTP_CONTROL2_PTP_RMAPRI_LSP    0u
#define DV1_RMA_PTP_CONTROL2_PTP_RMAPRI_LEN    3u
#define DV1_RMA_PTP_CONTROL2_PTP_RMAPRI_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_MMRP_CONTROL0_MMRP_PORTMASK_LSP  0u
#define DV1_RMA_MMRP_CONTROL0_MMRP_PORTMASK_LEN  16u
#define DV1_RMA_MMRP_CONTROL0_MMRP_PORTMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_MMRP_CONTROL1_MMRP_CPUMASK_LSP  0u
#define DV1_RMA_MMRP_CONTROL1_MMRP_CPUMASK_LEN  16u
#define DV1_RMA_MMRP_CONTROL1_MMRP_CPUMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_MMRP_CONTROL2_MMRP_DFRMAPRI_LSP  6u
#define DV1_RMA_MMRP_CONTROL2_MMRP_DFRMAPRI_LEN  1u
#define DV1_RMA_MMRP_CONTROL2_MMRP_DFRMAPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_MMRP_CONTROL2_MMRP_ACT_LSP       3u
#define DV1_RMA_MMRP_CONTROL2_MMRP_ACT_LEN       3u
#define DV1_RMA_MMRP_CONTROL2_MMRP_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_MMRP_CONTROL2_MMRP_RMAPRI_LSP    0u
#define DV1_RMA_MMRP_CONTROL2_MMRP_RMAPRI_LEN    3u
#define DV1_RMA_MMRP_CONTROL2_MMRP_RMAPRI_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_MVRP_CVLAN_CONTROL0_MVRP_CVLAN_PORTMASK_LSP  0u
#define DV1_RMA_MVRP_CVLAN_CONTROL0_MVRP_CVLAN_PORTMASK_LEN  16u
#define DV1_RMA_MVRP_CVLAN_CONTROL0_MVRP_CVLAN_PORTMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_MVRP_CVLAN_CONTROL1_MVRP_CVLAN_CPUMASK_LSP  0u
#define DV1_RMA_MVRP_CVLAN_CONTROL1_MVRP_CVLAN_CPUMASK_LEN  16u
#define DV1_RMA_MVRP_CVLAN_CONTROL1_MVRP_CVLAN_CPUMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_MVRP_CVLAN_CONTROL2_MVRP_CVLAN_DFRMAPRI_LSP  6u
#define DV1_RMA_MVRP_CVLAN_CONTROL2_MVRP_CVLAN_DFRMAPRI_LEN  1u
#define DV1_RMA_MVRP_CVLAN_CONTROL2_MVRP_CVLAN_DFRMAPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_MVRP_CVLAN_CONTROL2_MVRP_CVLAN_ACT_LSP       3u
#define DV1_RMA_MVRP_CVLAN_CONTROL2_MVRP_CVLAN_ACT_LEN       3u
#define DV1_RMA_MVRP_CVLAN_CONTROL2_MVRP_CVLAN_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_MVRP_CVLAN_CONTROL2_MVRP_CVLAN_RMAPRI_LSP    0u
#define DV1_RMA_MVRP_CVLAN_CONTROL2_MVRP_CVLAN_RMAPRI_LEN    3u
#define DV1_RMA_MVRP_CVLAN_CONTROL2_MVRP_CVLAN_RMAPRI_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_MVRP_SVLAN_CONTROL0_MVRP_SVLAN_PORTMASK_LSP  0u
#define DV1_RMA_MVRP_SVLAN_CONTROL0_MVRP_SVLAN_PORTMASK_LEN  16u
#define DV1_RMA_MVRP_SVLAN_CONTROL0_MVRP_SVLAN_PORTMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_MVRP_SVLAN_CONTROL1_MVRP_SVLAN_CPUMASK_LSP  0u
#define DV1_RMA_MVRP_SVLAN_CONTROL1_MVRP_SVLAN_CPUMASK_LEN  16u
#define DV1_RMA_MVRP_SVLAN_CONTROL1_MVRP_SVLAN_CPUMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_MVRP_SVLAN_CONTROL2_MVRP_SVLAN_DFRMAPRI_LSP  6u
#define DV1_RMA_MVRP_SVLAN_CONTROL2_MVRP_SVLAN_DFRMAPRI_LEN  1u
#define DV1_RMA_MVRP_SVLAN_CONTROL2_MVRP_SVLAN_DFRMAPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_MVRP_SVLAN_CONTROL2_MVRP_SVLAN_ACT_LSP       3u
#define DV1_RMA_MVRP_SVLAN_CONTROL2_MVRP_SVLAN_ACT_LEN       3u
#define DV1_RMA_MVRP_SVLAN_CONTROL2_MVRP_SVLAN_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_MVRP_SVLAN_CONTROL2_MVRP_SVLAN_RMAPRI_LSP    0u
#define DV1_RMA_MVRP_SVLAN_CONTROL2_MVRP_SVLAN_RMAPRI_LEN    3u
#define DV1_RMA_MVRP_SVLAN_CONTROL2_MVRP_SVLAN_RMAPRI_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_GVRP_SVLAN_CONTROL0_GVRP_SVLAN_PORTMASK_LSP  0u
#define DV1_RMA_GVRP_SVLAN_CONTROL0_GVRP_SVLAN_PORTMASK_LEN  16u
#define DV1_RMA_GVRP_SVLAN_CONTROL0_GVRP_SVLAN_PORTMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_GVRP_SVLAN_CONTROL1_GVRP_SVLAN_CPUMASK_LSP  0u
#define DV1_RMA_GVRP_SVLAN_CONTROL1_GVRP_SVLAN_CPUMASK_LEN  16u
#define DV1_RMA_GVRP_SVLAN_CONTROL1_GVRP_SVLAN_CPUMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_GVRP_SVLAN_CONTROL2_GVRP_SVLAN_DFRMAPRI_LSP  6u
#define DV1_RMA_GVRP_SVLAN_CONTROL2_GVRP_SVLAN_DFRMAPRI_LEN  1u
#define DV1_RMA_GVRP_SVLAN_CONTROL2_GVRP_SVLAN_DFRMAPRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_GVRP_SVLAN_CONTROL2_GVRP_SVLAN_ACT_LSP       3u
#define DV1_RMA_GVRP_SVLAN_CONTROL2_GVRP_SVLAN_ACT_LEN       3u
#define DV1_RMA_GVRP_SVLAN_CONTROL2_GVRP_SVLAN_ACT_TYPE      DV1_FIELD_TYPE_RW
#define DV1_RMA_GVRP_SVLAN_CONTROL2_GVRP_SVLAN_RMAPRI_LSP    0u
#define DV1_RMA_GVRP_SVLAN_CONTROL2_GVRP_SVLAN_RMAPRI_LEN    3u
#define DV1_RMA_GVRP_SVLAN_CONTROL2_GVRP_SVLAN_RMAPRI_TYPE   DV1_FIELD_TYPE_RW

#define DV1_RMA_LA_CONTROL0_LA_PORTMASK_LSP  0u
#define DV1_RMA_LA_CONTROL0_LA_PORTMASK_LEN  16u
#define DV1_RMA_LA_CONTROL0_LA_PORTMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_LA_CONTROL1_LA_CPUMASK_LSP  0u
#define DV1_RMA_LA_CONTROL1_LA_CPUMASK_LEN  16u
#define DV1_RMA_LA_CONTROL1_LA_CPUMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_LA_CONTROL2_MARKER_SUBTYPE_LSP  24u
#define DV1_RMA_LA_CONTROL2_MARKER_SUBTYPE_LEN  8u
#define DV1_RMA_LA_CONTROL2_MARKER_SUBTYPE_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_LA_CONTROL2_LACP_SUBTYPE_LSP    16u
#define DV1_RMA_LA_CONTROL2_LACP_SUBTYPE_LEN    8u
#define DV1_RMA_LA_CONTROL2_LACP_SUBTYPE_TYPE   DV1_FIELD_TYPE_RW
#define DV1_RMA_LA_CONTROL2_LA_DFRMAPRI_LSP     6u
#define DV1_RMA_LA_CONTROL2_LA_DFRMAPRI_LEN     1u
#define DV1_RMA_LA_CONTROL2_LA_DFRMAPRI_TYPE    DV1_FIELD_TYPE_RW
#define DV1_RMA_LA_CONTROL2_LA_ACT_LSP          3u
#define DV1_RMA_LA_CONTROL2_LA_ACT_LEN          3u
#define DV1_RMA_LA_CONTROL2_LA_ACT_TYPE         DV1_FIELD_TYPE_RW
#define DV1_RMA_LA_CONTROL2_LA_RMAPRI_LSP       0u
#define DV1_RMA_LA_CONTROL2_LA_RMAPRI_LEN       3u
#define DV1_RMA_LA_CONTROL2_LA_RMAPRI_TYPE      DV1_FIELD_TYPE_RW

#define DV1_RMA_MSRP_CONTROL0_MSRP_RMA_PORTMASK_LSP  0u
#define DV1_RMA_MSRP_CONTROL0_MSRP_RMA_PORTMASK_LEN  16u
#define DV1_RMA_MSRP_CONTROL0_MSRP_RMA_PORTMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_MSRP_CONTROL1_MSRP_RMA_CPUMASK_LSP  0u
#define DV1_RMA_MSRP_CONTROL1_MSRP_RMA_CPUMASK_LEN  16u
#define DV1_RMA_MSRP_CONTROL1_MSRP_RMA_CPUMASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_RMA_MSRP_CONTROL2_MSRP_DF_RMA_PRI_LSP  6u
#define DV1_RMA_MSRP_CONTROL2_MSRP_DF_RMA_PRI_LEN  1u
#define DV1_RMA_MSRP_CONTROL2_MSRP_DF_RMA_PRI_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_MSRP_CONTROL2_MSRP_RMA_ACT_LSP     3u
#define DV1_RMA_MSRP_CONTROL2_MSRP_RMA_ACT_LEN     3u
#define DV1_RMA_MSRP_CONTROL2_MSRP_RMA_ACT_TYPE    DV1_FIELD_TYPE_RW
#define DV1_RMA_MSRP_CONTROL2_MSRP_RMA_PRI_LSP     0u
#define DV1_RMA_MSRP_CONTROL2_MSRP_RMA_PRI_LEN     3u
#define DV1_RMA_MSRP_CONTROL2_MSRP_RMA_PRI_TYPE    DV1_FIELD_TYPE_RW

#define DV1_RMA_TAG_SELECT_CONTROL_MSRP_RMA_ACPTUTAG_SEL_LSP        15u
#define DV1_RMA_TAG_SELECT_CONTROL_MSRP_RMA_ACPTUTAG_SEL_LEN        3u
#define DV1_RMA_TAG_SELECT_CONTROL_MSRP_RMA_ACPTUTAG_SEL_TYPE       DV1_FIELD_TYPE_RW
#define DV1_RMA_TAG_SELECT_CONTROL_MVRP_CVLAN_RMA_ACPTUTAG_SEL_LSP  12u
#define DV1_RMA_TAG_SELECT_CONTROL_MVRP_CVLAN_RMA_ACPTUTAG_SEL_LEN  3u
#define DV1_RMA_TAG_SELECT_CONTROL_MVRP_CVLAN_RMA_ACPTUTAG_SEL_TYPE DV1_FIELD_TYPE_RW
#define DV1_RMA_TAG_SELECT_CONTROL_MMRP_RMA_ACPTUTAG_SEL_LSP        9u
#define DV1_RMA_TAG_SELECT_CONTROL_MMRP_RMA_ACPTUTAG_SEL_LEN        3u
#define DV1_RMA_TAG_SELECT_CONTROL_MMRP_RMA_ACPTUTAG_SEL_TYPE       DV1_FIELD_TYPE_RW
#define DV1_RMA_TAG_SELECT_CONTROL_MSRP_RMA_ACPTTAG_SEL_LSP         6u
#define DV1_RMA_TAG_SELECT_CONTROL_MSRP_RMA_ACPTTAG_SEL_LEN         3u
#define DV1_RMA_TAG_SELECT_CONTROL_MSRP_RMA_ACPTTAG_SEL_TYPE        DV1_FIELD_TYPE_RW
#define DV1_RMA_TAG_SELECT_CONTROL_MVRP_CVLAN_RMA_ACPTTAG_SEL_LSP   3u
#define DV1_RMA_TAG_SELECT_CONTROL_MVRP_CVLAN_RMA_ACPTTAG_SEL_LEN   3u
#define DV1_RMA_TAG_SELECT_CONTROL_MVRP_CVLAN_RMA_ACPTTAG_SEL_TYPE  DV1_FIELD_TYPE_RW
#define DV1_RMA_TAG_SELECT_CONTROL_MMRP_RMA_ACPTTAG_SEL_LSP         0u
#define DV1_RMA_TAG_SELECT_CONTROL_MMRP_RMA_ACPTTAG_SEL_LEN         3u
#define DV1_RMA_TAG_SELECT_CONTROL_MMRP_RMA_ACPTTAG_SEL_TYPE        DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL0_0_USER0_RMA0_MASK_LSP  16u
#define DV1_USER0_RMA_CONTROL0_0_USER0_RMA0_MASK_LEN  16u
#define DV1_USER0_RMA_CONTROL0_0_USER0_RMA0_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL0_0_USER0_RMA0_LSP       0u
#define DV1_USER0_RMA_CONTROL0_0_USER0_RMA0_LEN       16u
#define DV1_USER0_RMA_CONTROL0_0_USER0_RMA0_TYPE      DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL0_1_USER0_PORTMASK0_LSP  0u
#define DV1_USER0_RMA_CONTROL0_1_USER0_PORTMASK0_LEN  16u
#define DV1_USER0_RMA_CONTROL0_1_USER0_PORTMASK0_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL0_2_USER0_CPUMASK0_LSP  0u
#define DV1_USER0_RMA_CONTROL0_2_USER0_CPUMASK0_LEN  16u
#define DV1_USER0_RMA_CONTROL0_2_USER0_CPUMASK0_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL0_3_USER0_RMA0_EN_LSP    7u
#define DV1_USER0_RMA_CONTROL0_3_USER0_RMA0_EN_LEN    1u
#define DV1_USER0_RMA_CONTROL0_3_USER0_RMA0_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL0_3_USER0_DFRMAPRI0_LSP  6u
#define DV1_USER0_RMA_CONTROL0_3_USER0_DFRMAPRI0_LEN  1u
#define DV1_USER0_RMA_CONTROL0_3_USER0_DFRMAPRI0_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL0_3_USER0_ACT0_LSP       3u
#define DV1_USER0_RMA_CONTROL0_3_USER0_ACT0_LEN       3u
#define DV1_USER0_RMA_CONTROL0_3_USER0_ACT0_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL0_3_USER0_RMAPRI0_LSP    0u
#define DV1_USER0_RMA_CONTROL0_3_USER0_RMAPRI0_LEN    3u
#define DV1_USER0_RMA_CONTROL0_3_USER0_RMAPRI0_TYPE   DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL1_0_USER0_RMA1_MASK_LSP  16u
#define DV1_USER0_RMA_CONTROL1_0_USER0_RMA1_MASK_LEN  16u
#define DV1_USER0_RMA_CONTROL1_0_USER0_RMA1_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL1_0_USER0_RMA1_LSP       0u
#define DV1_USER0_RMA_CONTROL1_0_USER0_RMA1_LEN       16u
#define DV1_USER0_RMA_CONTROL1_0_USER0_RMA1_TYPE      DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL1_1_USER0_PORTMASK1_LSP  0u
#define DV1_USER0_RMA_CONTROL1_1_USER0_PORTMASK1_LEN  16u
#define DV1_USER0_RMA_CONTROL1_1_USER0_PORTMASK1_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL1_2_USER0_CPUMASK1_LSP  0u
#define DV1_USER0_RMA_CONTROL1_2_USER0_CPUMASK1_LEN  16u
#define DV1_USER0_RMA_CONTROL1_2_USER0_CPUMASK1_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL1_3_USER0_RMA1_EN_LSP    7u
#define DV1_USER0_RMA_CONTROL1_3_USER0_RMA1_EN_LEN    1u
#define DV1_USER0_RMA_CONTROL1_3_USER0_RMA1_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL1_3_USER0_DFRMAPRI1_LSP  6u
#define DV1_USER0_RMA_CONTROL1_3_USER0_DFRMAPRI1_LEN  1u
#define DV1_USER0_RMA_CONTROL1_3_USER0_DFRMAPRI1_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL1_3_USER0_ACT1_LSP       3u
#define DV1_USER0_RMA_CONTROL1_3_USER0_ACT1_LEN       3u
#define DV1_USER0_RMA_CONTROL1_3_USER0_ACT1_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL1_3_USER0_RMAPRI1_LSP    0u
#define DV1_USER0_RMA_CONTROL1_3_USER0_RMAPRI1_LEN    3u
#define DV1_USER0_RMA_CONTROL1_3_USER0_RMAPRI1_TYPE   DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL2_0_USER0_RMA2_MASK_LSP  16u
#define DV1_USER0_RMA_CONTROL2_0_USER0_RMA2_MASK_LEN  16u
#define DV1_USER0_RMA_CONTROL2_0_USER0_RMA2_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL2_0_USER0_RMA2_LSP       0u
#define DV1_USER0_RMA_CONTROL2_0_USER0_RMA2_LEN       16u
#define DV1_USER0_RMA_CONTROL2_0_USER0_RMA2_TYPE      DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL2_1_USER0_PORTMASK2_LSP  0u
#define DV1_USER0_RMA_CONTROL2_1_USER0_PORTMASK2_LEN  16u
#define DV1_USER0_RMA_CONTROL2_1_USER0_PORTMASK2_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL2_2_USER0_CPUMASK2_LSP  0u
#define DV1_USER0_RMA_CONTROL2_2_USER0_CPUMASK2_LEN  16u
#define DV1_USER0_RMA_CONTROL2_2_USER0_CPUMASK2_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL2_3_USER0_RMA2_EN_LSP    7u
#define DV1_USER0_RMA_CONTROL2_3_USER0_RMA2_EN_LEN    1u
#define DV1_USER0_RMA_CONTROL2_3_USER0_RMA2_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL2_3_USER0_DFRMAPRI2_LSP  6u
#define DV1_USER0_RMA_CONTROL2_3_USER0_DFRMAPRI2_LEN  1u
#define DV1_USER0_RMA_CONTROL2_3_USER0_DFRMAPRI2_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL2_3_USER0_ACT2_LSP       3u
#define DV1_USER0_RMA_CONTROL2_3_USER0_ACT2_LEN       3u
#define DV1_USER0_RMA_CONTROL2_3_USER0_ACT2_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL2_3_USER0_RMAPRI2_LSP    0u
#define DV1_USER0_RMA_CONTROL2_3_USER0_RMAPRI2_LEN    3u
#define DV1_USER0_RMA_CONTROL2_3_USER0_RMAPRI2_TYPE   DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL3_0_USER0_RMA3_MASK_LSP  16u
#define DV1_USER0_RMA_CONTROL3_0_USER0_RMA3_MASK_LEN  16u
#define DV1_USER0_RMA_CONTROL3_0_USER0_RMA3_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL3_0_USER0_RMA3_LSP       0u
#define DV1_USER0_RMA_CONTROL3_0_USER0_RMA3_LEN       16u
#define DV1_USER0_RMA_CONTROL3_0_USER0_RMA3_TYPE      DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL3_1_USER0_PORTMASK3_LSP  0u
#define DV1_USER0_RMA_CONTROL3_1_USER0_PORTMASK3_LEN  16u
#define DV1_USER0_RMA_CONTROL3_1_USER0_PORTMASK3_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL3_2_USER0_CPUMASK3_LSP  0u
#define DV1_USER0_RMA_CONTROL3_2_USER0_CPUMASK3_LEN  16u
#define DV1_USER0_RMA_CONTROL3_2_USER0_CPUMASK3_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL3_3_USER0_RMA3_EN_LSP    7u
#define DV1_USER0_RMA_CONTROL3_3_USER0_RMA3_EN_LEN    1u
#define DV1_USER0_RMA_CONTROL3_3_USER0_RMA3_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL3_3_USER0_DFRMAPRI3_LSP  6u
#define DV1_USER0_RMA_CONTROL3_3_USER0_DFRMAPRI3_LEN  1u
#define DV1_USER0_RMA_CONTROL3_3_USER0_DFRMAPRI3_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL3_3_USER0_ACT3_LSP       3u
#define DV1_USER0_RMA_CONTROL3_3_USER0_ACT3_LEN       3u
#define DV1_USER0_RMA_CONTROL3_3_USER0_ACT3_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL3_3_USER0_RMAPRI3_LSP    0u
#define DV1_USER0_RMA_CONTROL3_3_USER0_RMAPRI3_LEN    3u
#define DV1_USER0_RMA_CONTROL3_3_USER0_RMAPRI3_TYPE   DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL4_0_USER0_RMA4_MASK_LSP  16u
#define DV1_USER0_RMA_CONTROL4_0_USER0_RMA4_MASK_LEN  16u
#define DV1_USER0_RMA_CONTROL4_0_USER0_RMA4_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL4_0_USER0_RMA4_LSP       0u
#define DV1_USER0_RMA_CONTROL4_0_USER0_RMA4_LEN       16u
#define DV1_USER0_RMA_CONTROL4_0_USER0_RMA4_TYPE      DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL4_1_USER0_PORTMASK4_LSP  0u
#define DV1_USER0_RMA_CONTROL4_1_USER0_PORTMASK4_LEN  16u
#define DV1_USER0_RMA_CONTROL4_1_USER0_PORTMASK4_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL4_2_USER0_CPUMASK4_LSP  0u
#define DV1_USER0_RMA_CONTROL4_2_USER0_CPUMASK4_LEN  16u
#define DV1_USER0_RMA_CONTROL4_2_USER0_CPUMASK4_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL4_3_USER0_RMA4_EN_LSP    7u
#define DV1_USER0_RMA_CONTROL4_3_USER0_RMA4_EN_LEN    1u
#define DV1_USER0_RMA_CONTROL4_3_USER0_RMA4_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL4_3_USER0_DFRMAPRI4_LSP  6u
#define DV1_USER0_RMA_CONTROL4_3_USER0_DFRMAPRI4_LEN  1u
#define DV1_USER0_RMA_CONTROL4_3_USER0_DFRMAPRI4_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL4_3_USER0_ACT4_LSP       3u
#define DV1_USER0_RMA_CONTROL4_3_USER0_ACT4_LEN       3u
#define DV1_USER0_RMA_CONTROL4_3_USER0_ACT4_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL4_3_USER0_RMAPRI4_LSP    0u
#define DV1_USER0_RMA_CONTROL4_3_USER0_RMAPRI4_LEN    3u
#define DV1_USER0_RMA_CONTROL4_3_USER0_RMAPRI4_TYPE   DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL5_0_USER0_RMA5_MASK_LSP  16u
#define DV1_USER0_RMA_CONTROL5_0_USER0_RMA5_MASK_LEN  16u
#define DV1_USER0_RMA_CONTROL5_0_USER0_RMA5_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL5_0_USER0_RMA5_LSP       0u
#define DV1_USER0_RMA_CONTROL5_0_USER0_RMA5_LEN       16u
#define DV1_USER0_RMA_CONTROL5_0_USER0_RMA5_TYPE      DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL5_1_USER0_PORTMASK5_LSP  0u
#define DV1_USER0_RMA_CONTROL5_1_USER0_PORTMASK5_LEN  16u
#define DV1_USER0_RMA_CONTROL5_1_USER0_PORTMASK5_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL5_2_USER0_CPUMASK5_LSP  0u
#define DV1_USER0_RMA_CONTROL5_2_USER0_CPUMASK5_LEN  16u
#define DV1_USER0_RMA_CONTROL5_2_USER0_CPUMASK5_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL5_3_USER0_RMA5_EN_LSP    7u
#define DV1_USER0_RMA_CONTROL5_3_USER0_RMA5_EN_LEN    1u
#define DV1_USER0_RMA_CONTROL5_3_USER0_RMA5_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL5_3_USER0_DFRMAPRI5_LSP  6u
#define DV1_USER0_RMA_CONTROL5_3_USER0_DFRMAPRI5_LEN  1u
#define DV1_USER0_RMA_CONTROL5_3_USER0_DFRMAPRI5_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL5_3_USER0_ACT5_LSP       3u
#define DV1_USER0_RMA_CONTROL5_3_USER0_ACT5_LEN       3u
#define DV1_USER0_RMA_CONTROL5_3_USER0_ACT5_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL5_3_USER0_RMAPRI5_LSP    0u
#define DV1_USER0_RMA_CONTROL5_3_USER0_RMAPRI5_LEN    3u
#define DV1_USER0_RMA_CONTROL5_3_USER0_RMAPRI5_TYPE   DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL6_0_USER0_RMA6_MASK_LSP  16u
#define DV1_USER0_RMA_CONTROL6_0_USER0_RMA6_MASK_LEN  16u
#define DV1_USER0_RMA_CONTROL6_0_USER0_RMA6_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL6_0_USER0_RMA6_LSP       0u
#define DV1_USER0_RMA_CONTROL6_0_USER0_RMA6_LEN       16u
#define DV1_USER0_RMA_CONTROL6_0_USER0_RMA6_TYPE      DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL6_1_USER0_PORTMASK6_LSP  0u
#define DV1_USER0_RMA_CONTROL6_1_USER0_PORTMASK6_LEN  16u
#define DV1_USER0_RMA_CONTROL6_1_USER0_PORTMASK6_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL6_2_USER0_CPUMASK6_LSP  0u
#define DV1_USER0_RMA_CONTROL6_2_USER0_CPUMASK6_LEN  16u
#define DV1_USER0_RMA_CONTROL6_2_USER0_CPUMASK6_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL6_3_USER0_RMA6_EN_LSP    7u
#define DV1_USER0_RMA_CONTROL6_3_USER0_RMA6_EN_LEN    1u
#define DV1_USER0_RMA_CONTROL6_3_USER0_RMA6_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL6_3_USER0_DFRMAPRI6_LSP  6u
#define DV1_USER0_RMA_CONTROL6_3_USER0_DFRMAPRI6_LEN  1u
#define DV1_USER0_RMA_CONTROL6_3_USER0_DFRMAPRI6_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL6_3_USER0_ACT6_LSP       3u
#define DV1_USER0_RMA_CONTROL6_3_USER0_ACT6_LEN       3u
#define DV1_USER0_RMA_CONTROL6_3_USER0_ACT6_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL6_3_USER0_RMAPRI6_LSP    0u
#define DV1_USER0_RMA_CONTROL6_3_USER0_RMAPRI6_LEN    3u
#define DV1_USER0_RMA_CONTROL6_3_USER0_RMAPRI6_TYPE   DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL7_0_USER0_RMA7_MASK_LSP  16u
#define DV1_USER0_RMA_CONTROL7_0_USER0_RMA7_MASK_LEN  16u
#define DV1_USER0_RMA_CONTROL7_0_USER0_RMA7_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL7_0_USER0_RMA7_LSP       0u
#define DV1_USER0_RMA_CONTROL7_0_USER0_RMA7_LEN       16u
#define DV1_USER0_RMA_CONTROL7_0_USER0_RMA7_TYPE      DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL7_1_USER0_PORTMASK7_LSP  0u
#define DV1_USER0_RMA_CONTROL7_1_USER0_PORTMASK7_LEN  16u
#define DV1_USER0_RMA_CONTROL7_1_USER0_PORTMASK7_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL7_2_USER0_CPUMASK7_LSP  0u
#define DV1_USER0_RMA_CONTROL7_2_USER0_CPUMASK7_LEN  16u
#define DV1_USER0_RMA_CONTROL7_2_USER0_CPUMASK7_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL7_3_USER0_RMA7_EN_LSP    7u
#define DV1_USER0_RMA_CONTROL7_3_USER0_RMA7_EN_LEN    1u
#define DV1_USER0_RMA_CONTROL7_3_USER0_RMA7_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL7_3_USER0_DFRMAPRI7_LSP  6u
#define DV1_USER0_RMA_CONTROL7_3_USER0_DFRMAPRI7_LEN  1u
#define DV1_USER0_RMA_CONTROL7_3_USER0_DFRMAPRI7_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL7_3_USER0_ACT7_LSP       3u
#define DV1_USER0_RMA_CONTROL7_3_USER0_ACT7_LEN       3u
#define DV1_USER0_RMA_CONTROL7_3_USER0_ACT7_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL7_3_USER0_RMAPRI7_LSP    0u
#define DV1_USER0_RMA_CONTROL7_3_USER0_RMAPRI7_LEN    3u
#define DV1_USER0_RMA_CONTROL7_3_USER0_RMAPRI7_TYPE   DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL8_0_USER0_RMA8_MASK_LSP  16u
#define DV1_USER0_RMA_CONTROL8_0_USER0_RMA8_MASK_LEN  16u
#define DV1_USER0_RMA_CONTROL8_0_USER0_RMA8_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL8_0_USER0_RMA8_LSP       0u
#define DV1_USER0_RMA_CONTROL8_0_USER0_RMA8_LEN       16u
#define DV1_USER0_RMA_CONTROL8_0_USER0_RMA8_TYPE      DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL8_1_USER0_PORTMASK8_LSP  0u
#define DV1_USER0_RMA_CONTROL8_1_USER0_PORTMASK8_LEN  16u
#define DV1_USER0_RMA_CONTROL8_1_USER0_PORTMASK8_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL8_2_USER0_CPUMASK8_LSP  0u
#define DV1_USER0_RMA_CONTROL8_2_USER0_CPUMASK8_LEN  16u
#define DV1_USER0_RMA_CONTROL8_2_USER0_CPUMASK8_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL8_3_USER0_RMA8_EN_LSP    7u
#define DV1_USER0_RMA_CONTROL8_3_USER0_RMA8_EN_LEN    1u
#define DV1_USER0_RMA_CONTROL8_3_USER0_RMA8_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL8_3_USER0_DFRMAPRI8_LSP  6u
#define DV1_USER0_RMA_CONTROL8_3_USER0_DFRMAPRI8_LEN  1u
#define DV1_USER0_RMA_CONTROL8_3_USER0_DFRMAPRI8_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL8_3_USER0_ACT8_LSP       3u
#define DV1_USER0_RMA_CONTROL8_3_USER0_ACT8_LEN       3u
#define DV1_USER0_RMA_CONTROL8_3_USER0_ACT8_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL8_3_USER0_RMAPRI8_LSP    0u
#define DV1_USER0_RMA_CONTROL8_3_USER0_RMAPRI8_LEN    3u
#define DV1_USER0_RMA_CONTROL8_3_USER0_RMAPRI8_TYPE   DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL9_0_USER0_RMA9_MASK_LSP  16u
#define DV1_USER0_RMA_CONTROL9_0_USER0_RMA9_MASK_LEN  16u
#define DV1_USER0_RMA_CONTROL9_0_USER0_RMA9_MASK_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL9_0_USER0_RMA9_LSP       0u
#define DV1_USER0_RMA_CONTROL9_0_USER0_RMA9_LEN       16u
#define DV1_USER0_RMA_CONTROL9_0_USER0_RMA9_TYPE      DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL9_1_USER0_PORTMASK9_LSP  0u
#define DV1_USER0_RMA_CONTROL9_1_USER0_PORTMASK9_LEN  16u
#define DV1_USER0_RMA_CONTROL9_1_USER0_PORTMASK9_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL9_2_USER0_CPUMASK9_LSP  0u
#define DV1_USER0_RMA_CONTROL9_2_USER0_CPUMASK9_LEN  16u
#define DV1_USER0_RMA_CONTROL9_2_USER0_CPUMASK9_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER0_RMA_CONTROL9_3_USER0_RMA9_EN_LSP    7u
#define DV1_USER0_RMA_CONTROL9_3_USER0_RMA9_EN_LEN    1u
#define DV1_USER0_RMA_CONTROL9_3_USER0_RMA9_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL9_3_USER0_DFRMAPRI9_LSP  6u
#define DV1_USER0_RMA_CONTROL9_3_USER0_DFRMAPRI9_LEN  1u
#define DV1_USER0_RMA_CONTROL9_3_USER0_DFRMAPRI9_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL9_3_USER0_ACT9_LSP       3u
#define DV1_USER0_RMA_CONTROL9_3_USER0_ACT9_LEN       3u
#define DV1_USER0_RMA_CONTROL9_3_USER0_ACT9_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER0_RMA_CONTROL9_3_USER0_RMAPRI9_LSP    0u
#define DV1_USER0_RMA_CONTROL9_3_USER0_RMAPRI9_LEN    3u
#define DV1_USER0_RMA_CONTROL9_3_USER0_RMAPRI9_TYPE   DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL0_0_USER1_RMA0_LSP  0u
#define DV1_USER1_RMA_CONTROL0_0_USER1_RMA0_LEN  24u
#define DV1_USER1_RMA_CONTROL0_0_USER1_RMA0_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL0_1_USER1_DFRMAPRI0_LSP  31u
#define DV1_USER1_RMA_CONTROL0_1_USER1_DFRMAPRI0_LEN  1u
#define DV1_USER1_RMA_CONTROL0_1_USER1_DFRMAPRI0_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL0_1_USER1_ACT0_LSP       28u
#define DV1_USER1_RMA_CONTROL0_1_USER1_ACT0_LEN       3u
#define DV1_USER1_RMA_CONTROL0_1_USER1_ACT0_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL0_1_USER1_RMAPRI0_LSP    25u
#define DV1_USER1_RMA_CONTROL0_1_USER1_RMAPRI0_LEN    3u
#define DV1_USER1_RMA_CONTROL0_1_USER1_RMAPRI0_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL0_1_USER1_RMA0_EN_LSP    24u
#define DV1_USER1_RMA_CONTROL0_1_USER1_RMA0_EN_LEN    1u
#define DV1_USER1_RMA_CONTROL0_1_USER1_RMA0_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL0_1_USER1_RMA0_MASK_LSP  0u
#define DV1_USER1_RMA_CONTROL0_1_USER1_RMA0_MASK_LEN  24u
#define DV1_USER1_RMA_CONTROL0_1_USER1_RMA0_MASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL0_2_USER1_PORTMASK0_LSP  0u
#define DV1_USER1_RMA_CONTROL0_2_USER1_PORTMASK0_LEN  16u
#define DV1_USER1_RMA_CONTROL0_2_USER1_PORTMASK0_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL0_3_USER1_CPUMASK0_LSP  0u
#define DV1_USER1_RMA_CONTROL0_3_USER1_CPUMASK0_LEN  16u
#define DV1_USER1_RMA_CONTROL0_3_USER1_CPUMASK0_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL1_0_USER1_RMA1_LSP  0u
#define DV1_USER1_RMA_CONTROL1_0_USER1_RMA1_LEN  24u
#define DV1_USER1_RMA_CONTROL1_0_USER1_RMA1_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL1_1_USER1_DFRMAPRI1_LSP  31u
#define DV1_USER1_RMA_CONTROL1_1_USER1_DFRMAPRI1_LEN  1u
#define DV1_USER1_RMA_CONTROL1_1_USER1_DFRMAPRI1_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL1_1_USER1_ACT1_LSP       28u
#define DV1_USER1_RMA_CONTROL1_1_USER1_ACT1_LEN       3u
#define DV1_USER1_RMA_CONTROL1_1_USER1_ACT1_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL1_1_USER1_RMAPRI1_LSP    25u
#define DV1_USER1_RMA_CONTROL1_1_USER1_RMAPRI1_LEN    3u
#define DV1_USER1_RMA_CONTROL1_1_USER1_RMAPRI1_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL1_1_USER1_RMA1_EN_LSP    24u
#define DV1_USER1_RMA_CONTROL1_1_USER1_RMA1_EN_LEN    1u
#define DV1_USER1_RMA_CONTROL1_1_USER1_RMA1_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL1_1_USER1_RMA1_MASK_LSP  0u
#define DV1_USER1_RMA_CONTROL1_1_USER1_RMA1_MASK_LEN  24u
#define DV1_USER1_RMA_CONTROL1_1_USER1_RMA1_MASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL1_2_USER1_PORTMASK1_LSP  0u
#define DV1_USER1_RMA_CONTROL1_2_USER1_PORTMASK1_LEN  16u
#define DV1_USER1_RMA_CONTROL1_2_USER1_PORTMASK1_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL1_3_USER1_CPUMASK1_LSP  0u
#define DV1_USER1_RMA_CONTROL1_3_USER1_CPUMASK1_LEN  16u
#define DV1_USER1_RMA_CONTROL1_3_USER1_CPUMASK1_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL2_0_USER1_RMA2_LSP  0u
#define DV1_USER1_RMA_CONTROL2_0_USER1_RMA2_LEN  24u
#define DV1_USER1_RMA_CONTROL2_0_USER1_RMA2_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL2_1_USER1_DFRMAPRI2_LSP  31u
#define DV1_USER1_RMA_CONTROL2_1_USER1_DFRMAPRI2_LEN  1u
#define DV1_USER1_RMA_CONTROL2_1_USER1_DFRMAPRI2_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL2_1_USER1_ACT2_LSP       28u
#define DV1_USER1_RMA_CONTROL2_1_USER1_ACT2_LEN       3u
#define DV1_USER1_RMA_CONTROL2_1_USER1_ACT2_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL2_1_USER1_RMAPRI2_LSP    25u
#define DV1_USER1_RMA_CONTROL2_1_USER1_RMAPRI2_LEN    3u
#define DV1_USER1_RMA_CONTROL2_1_USER1_RMAPRI2_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL2_1_USER1_RMA2_EN_LSP    24u
#define DV1_USER1_RMA_CONTROL2_1_USER1_RMA2_EN_LEN    1u
#define DV1_USER1_RMA_CONTROL2_1_USER1_RMA2_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL2_1_USER1_RMA2_MASK_LSP  0u
#define DV1_USER1_RMA_CONTROL2_1_USER1_RMA2_MASK_LEN  24u
#define DV1_USER1_RMA_CONTROL2_1_USER1_RMA2_MASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL2_2_USER1_PORTMASK2_LSP  0u
#define DV1_USER1_RMA_CONTROL2_2_USER1_PORTMASK2_LEN  16u
#define DV1_USER1_RMA_CONTROL2_2_USER1_PORTMASK2_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL2_3_USER1_CPUMASK2_LSP  0u
#define DV1_USER1_RMA_CONTROL2_3_USER1_CPUMASK2_LEN  16u
#define DV1_USER1_RMA_CONTROL2_3_USER1_CPUMASK2_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL3_0_USER1_RMA3_LSP  0u
#define DV1_USER1_RMA_CONTROL3_0_USER1_RMA3_LEN  24u
#define DV1_USER1_RMA_CONTROL3_0_USER1_RMA3_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL3_1_USER1_DFRMAPRI3_LSP  31u
#define DV1_USER1_RMA_CONTROL3_1_USER1_DFRMAPRI3_LEN  1u
#define DV1_USER1_RMA_CONTROL3_1_USER1_DFRMAPRI3_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL3_1_USER1_ACT3_LSP       28u
#define DV1_USER1_RMA_CONTROL3_1_USER1_ACT3_LEN       3u
#define DV1_USER1_RMA_CONTROL3_1_USER1_ACT3_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL3_1_USER1_RMAPRI3_LSP    25u
#define DV1_USER1_RMA_CONTROL3_1_USER1_RMAPRI3_LEN    3u
#define DV1_USER1_RMA_CONTROL3_1_USER1_RMAPRI3_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL3_1_USER1_RMA3_EN_LSP    24u
#define DV1_USER1_RMA_CONTROL3_1_USER1_RMA3_EN_LEN    1u
#define DV1_USER1_RMA_CONTROL3_1_USER1_RMA3_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL3_1_USER1_RMA3_MASK_LSP  0u
#define DV1_USER1_RMA_CONTROL3_1_USER1_RMA3_MASK_LEN  24u
#define DV1_USER1_RMA_CONTROL3_1_USER1_RMA3_MASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL3_2_USER1_PORTMASK3_LSP  0u
#define DV1_USER1_RMA_CONTROL3_2_USER1_PORTMASK3_LEN  16u
#define DV1_USER1_RMA_CONTROL3_2_USER1_PORTMASK3_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL3_3_USER1_CPUMASK3_LSP  0u
#define DV1_USER1_RMA_CONTROL3_3_USER1_CPUMASK3_LEN  16u
#define DV1_USER1_RMA_CONTROL3_3_USER1_CPUMASK3_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL4_0_USER1_RMA4_LSP  0u
#define DV1_USER1_RMA_CONTROL4_0_USER1_RMA4_LEN  24u
#define DV1_USER1_RMA_CONTROL4_0_USER1_RMA4_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL4_1_USER1_DFRMAPRI4_LSP  31u
#define DV1_USER1_RMA_CONTROL4_1_USER1_DFRMAPRI4_LEN  1u
#define DV1_USER1_RMA_CONTROL4_1_USER1_DFRMAPRI4_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL4_1_USER1_ACT4_LSP       28u
#define DV1_USER1_RMA_CONTROL4_1_USER1_ACT4_LEN       3u
#define DV1_USER1_RMA_CONTROL4_1_USER1_ACT4_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL4_1_USER1_RMAPRI4_LSP    25u
#define DV1_USER1_RMA_CONTROL4_1_USER1_RMAPRI4_LEN    3u
#define DV1_USER1_RMA_CONTROL4_1_USER1_RMAPRI4_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL4_1_USER1_RMA4_EN_LSP    24u
#define DV1_USER1_RMA_CONTROL4_1_USER1_RMA4_EN_LEN    1u
#define DV1_USER1_RMA_CONTROL4_1_USER1_RMA4_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL4_1_USER1_RMA4_MASK_LSP  0u
#define DV1_USER1_RMA_CONTROL4_1_USER1_RMA4_MASK_LEN  24u
#define DV1_USER1_RMA_CONTROL4_1_USER1_RMA4_MASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL4_2_USER1_PORTMASK4_LSP  0u
#define DV1_USER1_RMA_CONTROL4_2_USER1_PORTMASK4_LEN  16u
#define DV1_USER1_RMA_CONTROL4_2_USER1_PORTMASK4_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL4_3_USER1_CPUMASK4_LSP  0u
#define DV1_USER1_RMA_CONTROL4_3_USER1_CPUMASK4_LEN  16u
#define DV1_USER1_RMA_CONTROL4_3_USER1_CPUMASK4_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL5_0_USER1_RMA5_LSP  0u
#define DV1_USER1_RMA_CONTROL5_0_USER1_RMA5_LEN  24u
#define DV1_USER1_RMA_CONTROL5_0_USER1_RMA5_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL5_1_USER1_DFRMAPRI5_LSP  31u
#define DV1_USER1_RMA_CONTROL5_1_USER1_DFRMAPRI5_LEN  1u
#define DV1_USER1_RMA_CONTROL5_1_USER1_DFRMAPRI5_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL5_1_USER1_ACT5_LSP       28u
#define DV1_USER1_RMA_CONTROL5_1_USER1_ACT5_LEN       3u
#define DV1_USER1_RMA_CONTROL5_1_USER1_ACT5_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL5_1_USER1_RMAPRI5_LSP    25u
#define DV1_USER1_RMA_CONTROL5_1_USER1_RMAPRI5_LEN    3u
#define DV1_USER1_RMA_CONTROL5_1_USER1_RMAPRI5_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL5_1_USER1_RMA5_EN_LSP    24u
#define DV1_USER1_RMA_CONTROL5_1_USER1_RMA5_EN_LEN    1u
#define DV1_USER1_RMA_CONTROL5_1_USER1_RMA5_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL5_1_USER1_RMA5_MASK_LSP  0u
#define DV1_USER1_RMA_CONTROL5_1_USER1_RMA5_MASK_LEN  24u
#define DV1_USER1_RMA_CONTROL5_1_USER1_RMA5_MASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL5_2_USER1_PORTMASK5_LSP  0u
#define DV1_USER1_RMA_CONTROL5_2_USER1_PORTMASK5_LEN  16u
#define DV1_USER1_RMA_CONTROL5_2_USER1_PORTMASK5_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL5_3_USER1_CPUMASK5_LSP  0u
#define DV1_USER1_RMA_CONTROL5_3_USER1_CPUMASK5_LEN  16u
#define DV1_USER1_RMA_CONTROL5_3_USER1_CPUMASK5_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL6_0_USER1_RMA6_LSP  0u
#define DV1_USER1_RMA_CONTROL6_0_USER1_RMA6_LEN  24u
#define DV1_USER1_RMA_CONTROL6_0_USER1_RMA6_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL6_1_USER1_DFRMAPRI6_LSP  31u
#define DV1_USER1_RMA_CONTROL6_1_USER1_DFRMAPRI6_LEN  1u
#define DV1_USER1_RMA_CONTROL6_1_USER1_DFRMAPRI6_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL6_1_USER1_ACT6_LSP       28u
#define DV1_USER1_RMA_CONTROL6_1_USER1_ACT6_LEN       3u
#define DV1_USER1_RMA_CONTROL6_1_USER1_ACT6_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL6_1_USER1_RMAPRI6_LSP    25u
#define DV1_USER1_RMA_CONTROL6_1_USER1_RMAPRI6_LEN    3u
#define DV1_USER1_RMA_CONTROL6_1_USER1_RMAPRI6_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL6_1_USER1_RMA6_EN_LSP    24u
#define DV1_USER1_RMA_CONTROL6_1_USER1_RMA6_EN_LEN    1u
#define DV1_USER1_RMA_CONTROL6_1_USER1_RMA6_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL6_1_USER1_RMA6_MASK_LSP  0u
#define DV1_USER1_RMA_CONTROL6_1_USER1_RMA6_MASK_LEN  24u
#define DV1_USER1_RMA_CONTROL6_1_USER1_RMA6_MASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL6_2_USER1_PORTMASK6_LSP  0u
#define DV1_USER1_RMA_CONTROL6_2_USER1_PORTMASK6_LEN  16u
#define DV1_USER1_RMA_CONTROL6_2_USER1_PORTMASK6_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL6_3_USER1_CPUMASK6_LSP  0u
#define DV1_USER1_RMA_CONTROL6_3_USER1_CPUMASK6_LEN  16u
#define DV1_USER1_RMA_CONTROL6_3_USER1_CPUMASK6_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL7_0_USER1_RMA7_LSP  0u
#define DV1_USER1_RMA_CONTROL7_0_USER1_RMA7_LEN  24u
#define DV1_USER1_RMA_CONTROL7_0_USER1_RMA7_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL7_1_USER1_DFRMAPRI7_LSP  31u
#define DV1_USER1_RMA_CONTROL7_1_USER1_DFRMAPRI7_LEN  1u
#define DV1_USER1_RMA_CONTROL7_1_USER1_DFRMAPRI7_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL7_1_USER1_ACT7_LSP       28u
#define DV1_USER1_RMA_CONTROL7_1_USER1_ACT7_LEN       3u
#define DV1_USER1_RMA_CONTROL7_1_USER1_ACT7_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL7_1_USER1_RMAPRI7_LSP    25u
#define DV1_USER1_RMA_CONTROL7_1_USER1_RMAPRI7_LEN    3u
#define DV1_USER1_RMA_CONTROL7_1_USER1_RMAPRI7_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL7_1_USER1_RMA7_EN_LSP    24u
#define DV1_USER1_RMA_CONTROL7_1_USER1_RMA7_EN_LEN    1u
#define DV1_USER1_RMA_CONTROL7_1_USER1_RMA7_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL7_1_USER1_RMA7_MASK_LSP  0u
#define DV1_USER1_RMA_CONTROL7_1_USER1_RMA7_MASK_LEN  24u
#define DV1_USER1_RMA_CONTROL7_1_USER1_RMA7_MASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL7_2_USER1_PORTMASK7_LSP  0u
#define DV1_USER1_RMA_CONTROL7_2_USER1_PORTMASK7_LEN  16u
#define DV1_USER1_RMA_CONTROL7_2_USER1_PORTMASK7_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL7_3_USER1_CPUMASK7_LSP  0u
#define DV1_USER1_RMA_CONTROL7_3_USER1_CPUMASK7_LEN  16u
#define DV1_USER1_RMA_CONTROL7_3_USER1_CPUMASK7_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL8_0_USER1_RMA8_LSP  0u
#define DV1_USER1_RMA_CONTROL8_0_USER1_RMA8_LEN  24u
#define DV1_USER1_RMA_CONTROL8_0_USER1_RMA8_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL8_1_USER1_DFRMAPRI8_LSP  31u
#define DV1_USER1_RMA_CONTROL8_1_USER1_DFRMAPRI8_LEN  1u
#define DV1_USER1_RMA_CONTROL8_1_USER1_DFRMAPRI8_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL8_1_USER1_ACT8_LSP       28u
#define DV1_USER1_RMA_CONTROL8_1_USER1_ACT8_LEN       3u
#define DV1_USER1_RMA_CONTROL8_1_USER1_ACT8_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL8_1_USER1_RMAPRI8_LSP    25u
#define DV1_USER1_RMA_CONTROL8_1_USER1_RMAPRI8_LEN    3u
#define DV1_USER1_RMA_CONTROL8_1_USER1_RMAPRI8_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL8_1_USER1_RMA8_EN_LSP    24u
#define DV1_USER1_RMA_CONTROL8_1_USER1_RMA8_EN_LEN    1u
#define DV1_USER1_RMA_CONTROL8_1_USER1_RMA8_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL8_1_USER1_RMA8_MASK_LSP  0u
#define DV1_USER1_RMA_CONTROL8_1_USER1_RMA8_MASK_LEN  24u
#define DV1_USER1_RMA_CONTROL8_1_USER1_RMA8_MASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL8_2_USER1_PORTMASK8_LSP  0u
#define DV1_USER1_RMA_CONTROL8_2_USER1_PORTMASK8_LEN  16u
#define DV1_USER1_RMA_CONTROL8_2_USER1_PORTMASK8_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL8_3_USER1_CPUMASK8_LSP  0u
#define DV1_USER1_RMA_CONTROL8_3_USER1_CPUMASK8_LEN  16u
#define DV1_USER1_RMA_CONTROL8_3_USER1_CPUMASK8_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL9_0_USER1_RMA9_LSP  0u
#define DV1_USER1_RMA_CONTROL9_0_USER1_RMA9_LEN  24u
#define DV1_USER1_RMA_CONTROL9_0_USER1_RMA9_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL9_1_USER1_DFRMAPRI9_LSP  31u
#define DV1_USER1_RMA_CONTROL9_1_USER1_DFRMAPRI9_LEN  1u
#define DV1_USER1_RMA_CONTROL9_1_USER1_DFRMAPRI9_TYPE DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL9_1_USER1_ACT9_LSP       28u
#define DV1_USER1_RMA_CONTROL9_1_USER1_ACT9_LEN       3u
#define DV1_USER1_RMA_CONTROL9_1_USER1_ACT9_TYPE      DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL9_1_USER1_RMAPRI9_LSP    25u
#define DV1_USER1_RMA_CONTROL9_1_USER1_RMAPRI9_LEN    3u
#define DV1_USER1_RMA_CONTROL9_1_USER1_RMAPRI9_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL9_1_USER1_RMA9_EN_LSP    24u
#define DV1_USER1_RMA_CONTROL9_1_USER1_RMA9_EN_LEN    1u
#define DV1_USER1_RMA_CONTROL9_1_USER1_RMA9_EN_TYPE   DV1_FIELD_TYPE_RW
#define DV1_USER1_RMA_CONTROL9_1_USER1_RMA9_MASK_LSP  0u
#define DV1_USER1_RMA_CONTROL9_1_USER1_RMA9_MASK_LEN  24u
#define DV1_USER1_RMA_CONTROL9_1_USER1_RMA9_MASK_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL9_2_USER1_PORTMASK9_LSP  0u
#define DV1_USER1_RMA_CONTROL9_2_USER1_PORTMASK9_LEN  16u
#define DV1_USER1_RMA_CONTROL9_2_USER1_PORTMASK9_TYPE DV1_FIELD_TYPE_RW

#define DV1_USER1_RMA_CONTROL9_3_USER1_CPUMASK9_LSP  0u
#define DV1_USER1_RMA_CONTROL9_3_USER1_CPUMASK9_LEN  16u
#define DV1_USER1_RMA_CONTROL9_3_USER1_CPUMASK9_TYPE DV1_FIELD_TYPE_RW

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_RMA_H_ */