/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_SOURCE_MAC_LEARNING_H_
#define DV1_RTKAS_REG_FIELD_FILE_SOURCE_MAC_LEARNING_H_

#ifdef DV1_FILE_SOURCE_MAC_LEARNING
/* File: Source MAC Learning */
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_BKTFULLACT_LSP              26u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_BKTFULLACT_LEN              2u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_BKTFULLACT_TYPE             DV1_FIELD_TYPE_RW
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_TTLDROP_LSP                 25u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_TTLDROP_LEN                 1u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_TTLDROP_TYPE                DV1_FIELD_TYPE_RW
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_DAEQSA_DROP_LSP             24u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_DAEQSA_DROP_LEN             1u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_DAEQSA_DROP_TYPE            DV1_FIELD_TYPE_RW
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_MLTSA_DROP_LSP              23u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_MLTSA_DROP_LEN              1u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_MLTSA_DROP_TYPE             DV1_FIELD_TYPE_RW
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_BROSA_DROP_LSP              22u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_BROSA_DROP_LEN              1u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_BROSA_DROP_TYPE             DV1_FIELD_TYPE_RW
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_ZEROSA_DROP_LSP             21u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_ZEROSA_DROP_LEN             1u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_ZEROSA_DROP_TYPE            DV1_FIELD_TYPE_RW
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_LINK_DOWN_PORT_INVALID_LSP  20u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_LINK_DOWN_PORT_INVALID_LEN  1u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_LINK_DOWN_PORT_INVALID_TYPE DV1_FIELD_TYPE_RW
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_L2LRU_LSP                   19u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_L2LRU_LEN                   1u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_L2LRU_TYPE                  DV1_FIELD_TYPE_RW
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_AGEUNIT_LSP                 0u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_AGEUNIT_LEN                 19u
#define DV1_SOURCE_MAC_LEARNING_CONTROL0_AGEUNIT_TYPE                DV1_FIELD_TYPE_RW

#define DV1_SOURCE_MAC_LEARNING_CONTROL1_PMCPUMSK_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_CONTROL1_PMCPUMSK_LEN  16u
#define DV1_SOURCE_MAC_LEARNING_CONTROL1_PMCPUMSK_TYPE DV1_FIELD_TYPE_RW

#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_TRIGGER_LSP  18u
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_TRIGGER_LEN  1u
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_TRIGGER_TYPE DV1_FIELD_TYPE_RWS
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_MODE_LSP     16u
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_MODE_LEN     2u
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_MODE_TYPE    DV1_FIELD_TYPE_RW
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_VID_LSP      4u
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_VID_LEN      12u
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_VID_TYPE     DV1_FIELD_TYPE_RW
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_FID_LSP      0u
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_FID_LEN      4u
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL0_LUT_FLUSH_FID_TYPE     DV1_FIELD_TYPE_RW

#define DV1_ADDRESS_TABLE_FLUSH_CONTROL1_LUT_FLUSH_PMSK_LSP  0u
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL1_LUT_FLUSH_PMSK_LEN  16u
#define DV1_ADDRESS_TABLE_FLUSH_CONTROL1_LUT_FLUSH_PMSK_TYPE DV1_FIELD_TYPE_RW

#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_PORT_NUM_LSP      18u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_PORT_NUM_LEN      4u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_PORT_NUM_TYPE     DV1_FIELD_TYPE_RW
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_SPECIFY_MAC_LSP   17u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_SPECIFY_MAC_LEN   1u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_SPECIFY_MAC_TYPE  DV1_FIELD_TYPE_RW
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_SPECIFY_PORT_LSP  16u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_SPECIFY_PORT_LEN  1u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_SPECIFY_PORT_TYPE DV1_FIELD_TYPE_RW
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_MAC_47_32_LSP     0u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_MAC_47_32_LEN     16u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL0_LUT_SEARCH_MAC_47_32_TYPE    DV1_FIELD_TYPE_RW

#define DV1_ADDRESS_TABLE_SEARCH_CONTROL1_LUT_SEARCH_MAC_31_0_LSP  0u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL1_LUT_SEARCH_MAC_31_0_LEN  32u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL1_LUT_SEARCH_MAC_31_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_SPECIFY_FID_LSP  29u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_SPECIFY_FID_LEN  1u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_SPECIFY_FID_TYPE DV1_FIELD_TYPE_RW
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_HASH_ALG_LSP     28u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_HASH_ALG_LEN     1u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_HASH_ALG_TYPE    DV1_FIELD_TYPE_RW
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_VID_LSP          16u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_VID_LEN          12u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_VID_TYPE         DV1_FIELD_TYPE_RW
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_FID_LSP          12u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_FID_LEN          4u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_FID_TYPE         DV1_FIELD_TYPE_RW
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_IDX_START_LSP    0u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_IDX_START_LEN    12u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL2_LUT_SEARCH_IDX_START_TYPE   DV1_FIELD_TYPE_RW

#define DV1_ADDRESS_TABLE_SEARCH_CONTROL3_LUT_SEARCH_TRIGGER_LSP  0u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL3_LUT_SEARCH_TRIGGER_LEN  1u
#define DV1_ADDRESS_TABLE_SEARCH_CONTROL3_LUT_SEARCH_TRIGGER_TYPE DV1_FIELD_TYPE_RWS

#define DV1_ADDRESS_TABLE_SEARCH_RESULT_LUT_SEARCH_FOUND_LSP     12u
#define DV1_ADDRESS_TABLE_SEARCH_RESULT_LUT_SEARCH_FOUND_LEN     1u
#define DV1_ADDRESS_TABLE_SEARCH_RESULT_LUT_SEARCH_FOUND_TYPE    DV1_FIELD_TYPE_RO
#define DV1_ADDRESS_TABLE_SEARCH_RESULT_LUT_SEARCH_HIT_ADDR_LSP  0u
#define DV1_ADDRESS_TABLE_SEARCH_RESULT_LUT_SEARCH_HIT_ADDR_LEN  12u
#define DV1_ADDRESS_TABLE_SEARCH_RESULT_LUT_SEARCH_HIT_ADDR_TYPE DV1_FIELD_TYPE_RO

#define DV1_SA_LEARNING_INTERRUPT_STATUS_SAL_ENTRY_IDX_LSP       1u
#define DV1_SA_LEARNING_INTERRUPT_STATUS_SAL_ENTRY_IDX_LEN       13u
#define DV1_SA_LEARNING_INTERRUPT_STATUS_SAL_ENTRY_IDX_TYPE      DV1_FIELD_TYPE_RO
#define DV1_SA_LEARNING_INTERRUPT_STATUS_NEW_L2ENTRY_STATUS_LSP  0u
#define DV1_SA_LEARNING_INTERRUPT_STATUS_NEW_L2ENTRY_STATUS_LEN  1u
#define DV1_SA_LEARNING_INTERRUPT_STATUS_NEW_L2ENTRY_STATUS_TYPE DV1_FIELD_TYPE_RW1C

#define DV1_CONFLICT_INT_STATUS0_OVERWRITE_EN_LSP  3u
#define DV1_CONFLICT_INT_STATUS0_OVERWRITE_EN_LEN  1u
#define DV1_CONFLICT_INT_STATUS0_OVERWRITE_EN_TYPE DV1_FIELD_TYPE_RW
#define DV1_CONFLICT_INT_STATUS0_IDX_CNT_LSP       0u
#define DV1_CONFLICT_INT_STATUS0_IDX_CNT_LEN       3u
#define DV1_CONFLICT_INT_STATUS0_IDX_CNT_TYPE      DV1_FIELD_TYPE_RO

#define DV1_CONFLICT_INT_STATUS1_CONFLICT_PORTS_LSP  0u
#define DV1_CONFLICT_INT_STATUS1_CONFLICT_PORTS_LEN  16u
#define DV1_CONFLICT_INT_STATUS1_CONFLICT_PORTS_TYPE DV1_FIELD_TYPE_RWS

#define DV1_SOURCE_MAC_LEARNING_CONFLICT0_CONFLICT_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT0_CONFLICT_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT0_CONFLICT_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT1_CONFLICT_HASH_VALUE_LSP  17u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT1_CONFLICT_HASH_VALUE_LEN  9u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT1_CONFLICT_HASH_VALUE_TYPE DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT1_CONFLICT_VALID_LSP       16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT1_CONFLICT_VALID_LEN       1u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT1_CONFLICT_VALID_TYPE      DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT1_CONFLICT_MAC_47_32_LSP   0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT1_CONFLICT_MAC_47_32_LEN   16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT1_CONFLICT_MAC_47_32_TYPE  DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT2_CONFLICT_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT2_CONFLICT_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT2_CONFLICT_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT3_CONFLICT_HASH_VALUE_LSP  17u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT3_CONFLICT_HASH_VALUE_LEN  9u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT3_CONFLICT_HASH_VALUE_TYPE DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT3_CONFLICT_VALID_LSP       16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT3_CONFLICT_VALID_LEN       1u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT3_CONFLICT_VALID_TYPE      DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT3_CONFLICT_MAC_47_32_LSP   0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT3_CONFLICT_MAC_47_32_LEN   16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT3_CONFLICT_MAC_47_32_TYPE  DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT4_CONFLICT_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT4_CONFLICT_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT4_CONFLICT_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT5_CONFLICT_HASH_VALUE_LSP  17u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT5_CONFLICT_HASH_VALUE_LEN  9u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT5_CONFLICT_HASH_VALUE_TYPE DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT5_CONFLICT_VALID_LSP       16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT5_CONFLICT_VALID_LEN       1u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT5_CONFLICT_VALID_TYPE      DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT5_CONFLICT_MAC_47_32_LSP   0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT5_CONFLICT_MAC_47_32_LEN   16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT5_CONFLICT_MAC_47_32_TYPE  DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT6_CONFLICT_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT6_CONFLICT_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT6_CONFLICT_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT7_CONFLICT_HASH_VALUE_LSP  17u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT7_CONFLICT_HASH_VALUE_LEN  9u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT7_CONFLICT_HASH_VALUE_TYPE DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT7_CONFLICT_VALID_LSP       16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT7_CONFLICT_VALID_LEN       1u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT7_CONFLICT_VALID_TYPE      DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT7_CONFLICT_MAC_47_32_LSP   0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT7_CONFLICT_MAC_47_32_LEN   16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT7_CONFLICT_MAC_47_32_TYPE  DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT8_CONFLICT_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT8_CONFLICT_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT8_CONFLICT_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT9_CONFLICT_HASH_VALUE_LSP  17u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT9_CONFLICT_HASH_VALUE_LEN  9u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT9_CONFLICT_HASH_VALUE_TYPE DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT9_CONFLICT_VALID_LSP       16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT9_CONFLICT_VALID_LEN       1u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT9_CONFLICT_VALID_TYPE      DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT9_CONFLICT_MAC_47_32_LSP   0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT9_CONFLICT_MAC_47_32_LEN   16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT9_CONFLICT_MAC_47_32_TYPE  DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT10_CONFLICT_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT10_CONFLICT_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT10_CONFLICT_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT11_CONFLICT_HASH_VALUE_LSP  17u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT11_CONFLICT_HASH_VALUE_LEN  9u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT11_CONFLICT_HASH_VALUE_TYPE DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT11_CONFLICT_VALID_LSP       16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT11_CONFLICT_VALID_LEN       1u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT11_CONFLICT_VALID_TYPE      DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT11_CONFLICT_MAC_47_32_LSP   0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT11_CONFLICT_MAC_47_32_LEN   16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT11_CONFLICT_MAC_47_32_TYPE  DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT12_CONFLICT_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT12_CONFLICT_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT12_CONFLICT_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT13_CONFLICT_HASH_VALUE_LSP  17u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT13_CONFLICT_HASH_VALUE_LEN  9u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT13_CONFLICT_HASH_VALUE_TYPE DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT13_CONFLICT_VALID_LSP       16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT13_CONFLICT_VALID_LEN       1u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT13_CONFLICT_VALID_TYPE      DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT13_CONFLICT_MAC_47_32_LSP   0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT13_CONFLICT_MAC_47_32_LEN   16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT13_CONFLICT_MAC_47_32_TYPE  DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT14_CONFLICT_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT14_CONFLICT_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT14_CONFLICT_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_CONFLICT15_CONFLICT_HASH_VALUE_LSP  17u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT15_CONFLICT_HASH_VALUE_LEN  9u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT15_CONFLICT_HASH_VALUE_TYPE DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT15_CONFLICT_VALID_LSP       16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT15_CONFLICT_VALID_LEN       1u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT15_CONFLICT_VALID_TYPE      DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_CONFLICT15_CONFLICT_MAC_47_32_LSP   0u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT15_CONFLICT_MAC_47_32_LEN   16u
#define DV1_SOURCE_MAC_LEARNING_CONFLICT15_CONFLICT_MAC_47_32_TYPE  DV1_FIELD_TYPE_RO

#define DV1_OVERFLOW_INT_STATUS0_OVERWRITE_EN_LSP  3u
#define DV1_OVERFLOW_INT_STATUS0_OVERWRITE_EN_LEN  1u
#define DV1_OVERFLOW_INT_STATUS0_OVERWRITE_EN_TYPE DV1_FIELD_TYPE_RW
#define DV1_OVERFLOW_INT_STATUS0_IDX_CNT_LSP       0u
#define DV1_OVERFLOW_INT_STATUS0_IDX_CNT_LEN       3u
#define DV1_OVERFLOW_INT_STATUS0_IDX_CNT_TYPE      DV1_FIELD_TYPE_RO

#define DV1_OVERFLOW_INT_STATUS1_OVERFLOW_PORTS_LSP  0u
#define DV1_OVERFLOW_INT_STATUS1_OVERFLOW_PORTS_LEN  16u
#define DV1_OVERFLOW_INT_STATUS1_OVERFLOW_PORTS_TYPE DV1_FIELD_TYPE_RWS

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW0_OVERFLOW_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW0_OVERFLOW_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW0_OVERFLOW_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW1_OVERFLOW_VALID_LSP      16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW1_OVERFLOW_VALID_LEN      1u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW1_OVERFLOW_VALID_TYPE     DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW1_OVERFLOW_MAC_47_32_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW1_OVERFLOW_MAC_47_32_LEN  16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW1_OVERFLOW_MAC_47_32_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW2_OVERFLOW_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW2_OVERFLOW_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW2_OVERFLOW_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW3_OVERFLOW_VALID_LSP      16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW3_OVERFLOW_VALID_LEN      1u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW3_OVERFLOW_VALID_TYPE     DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW3_OVERFLOW_MAC_47_32_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW3_OVERFLOW_MAC_47_32_LEN  16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW3_OVERFLOW_MAC_47_32_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW4_OVERFLOW_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW4_OVERFLOW_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW4_OVERFLOW_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW5_OVERFLOW_VALID_LSP      16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW5_OVERFLOW_VALID_LEN      1u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW5_OVERFLOW_VALID_TYPE     DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW5_OVERFLOW_MAC_47_32_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW5_OVERFLOW_MAC_47_32_LEN  16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW5_OVERFLOW_MAC_47_32_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW6_OVERFLOW_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW6_OVERFLOW_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW6_OVERFLOW_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW7_OVERFLOW_VALID_LSP      16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW7_OVERFLOW_VALID_LEN      1u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW7_OVERFLOW_VALID_TYPE     DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW7_OVERFLOW_MAC_47_32_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW7_OVERFLOW_MAC_47_32_LEN  16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW7_OVERFLOW_MAC_47_32_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW8_OVERFLOW_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW8_OVERFLOW_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW8_OVERFLOW_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW9_OVERFLOW_VALID_LSP      16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW9_OVERFLOW_VALID_LEN      1u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW9_OVERFLOW_VALID_TYPE     DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW9_OVERFLOW_MAC_47_32_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW9_OVERFLOW_MAC_47_32_LEN  16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW9_OVERFLOW_MAC_47_32_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW10_OVERFLOW_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW10_OVERFLOW_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW10_OVERFLOW_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW11_OVERFLOW_VALID_LSP      16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW11_OVERFLOW_VALID_LEN      1u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW11_OVERFLOW_VALID_TYPE     DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW11_OVERFLOW_MAC_47_32_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW11_OVERFLOW_MAC_47_32_LEN  16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW11_OVERFLOW_MAC_47_32_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW12_OVERFLOW_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW12_OVERFLOW_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW12_OVERFLOW_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW13_OVERFLOW_VALID_LSP      16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW13_OVERFLOW_VALID_LEN      1u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW13_OVERFLOW_VALID_TYPE     DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW13_OVERFLOW_MAC_47_32_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW13_OVERFLOW_MAC_47_32_LEN  16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW13_OVERFLOW_MAC_47_32_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW14_OVERFLOW_MAC_31_0_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW14_OVERFLOW_MAC_31_0_LEN  32u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW14_OVERFLOW_MAC_31_0_TYPE DV1_FIELD_TYPE_RO

#define DV1_SOURCE_MAC_LEARNING_OVERFLOW15_OVERFLOW_VALID_LSP      16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW15_OVERFLOW_VALID_LEN      1u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW15_OVERFLOW_VALID_TYPE     DV1_FIELD_TYPE_RO
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW15_OVERFLOW_MAC_47_32_LSP  0u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW15_OVERFLOW_MAC_47_32_LEN  16u
#define DV1_SOURCE_MAC_LEARNING_OVERFLOW15_OVERFLOW_MAC_47_32_TYPE DV1_FIELD_TYPE_RO

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_SOURCE_MAC_LEARNING_H_ */