/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_FIELD_FILE_I2C_H_
#define DV1_RTKAS_REG_FIELD_FILE_I2C_H_

#ifdef DV1_FILE_I2C
/* File: I2C */
#define DV1_EXTERNAL_ACCESS_CONTROL_I2C_MODE_LSP             5u
#define DV1_EXTERNAL_ACCESS_CONTROL_I2C_MODE_LEN             1u
#define DV1_EXTERNAL_ACCESS_CONTROL_I2C_MODE_TYPE            DV1_FIELD_TYPE_RW
#define DV1_EXTERNAL_ACCESS_CONTROL_I2C_DEVICE_ADDR_2_0_LSP  2u
#define DV1_EXTERNAL_ACCESS_CONTROL_I2C_DEVICE_ADDR_2_0_LEN  3u
#define DV1_EXTERNAL_ACCESS_CONTROL_I2C_DEVICE_ADDR_2_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_I2C_EXTERNAL_ACCESS_STATUS_I2C_DATALEN_LSP  0u
#define DV1_I2C_EXTERNAL_ACCESS_STATUS_I2C_DATALEN_LEN  22u
#define DV1_I2C_EXTERNAL_ACCESS_STATUS_I2C_DATALEN_TYPE DV1_FIELD_TYPE_RO

#define DV1_I2C_EXTERNAL_ACCESS_ADDRESS_I2C_EAAR_LSP  0u
#define DV1_I2C_EXTERNAL_ACCESS_ADDRESS_I2C_EAAR_LEN  24u
#define DV1_I2C_EXTERNAL_ACCESS_ADDRESS_I2C_EAAR_TYPE DV1_FIELD_TYPE_RO

#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_MAX_PAGE_BYTES_LSP     17u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_MAX_PAGE_BYTES_LEN     1u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_MAX_PAGE_BYTES_TYPE    DV1_FIELD_TYPE_RO
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_FASTEND_LSP            16u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_FASTEND_LEN            1u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_FASTEND_TYPE           DV1_FIELD_TYPE_RO
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_CPUCODE_EXIST_LSP             15u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_CPUCODE_EXIST_LEN             1u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_CPUCODE_EXIST_TYPE            DV1_FIELD_TYPE_RO
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_AUTOLOAD_CONFIGURE_EXIST_LSP  14u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_AUTOLOAD_CONFIGURE_EXIST_LEN  1u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_AUTOLOAD_CONFIGURE_EXIST_TYPE DV1_FIELD_TYPE_RO
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_EEPROM_RANGE_2_0_LSP      10u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_EEPROM_RANGE_2_0_LEN      3u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_EEPROM_RANGE_2_0_TYPE     DV1_FIELD_TYPE_RO
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_SCK_FREQ_LSP              8u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_SCK_FREQ_LEN              2u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_SEL_SCK_FREQ_TYPE             DV1_FIELD_TYPE_RW
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_VALID_LSP              0u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_VALID_LEN              8u
#define DV1_EEPROM_AUTO_DOWNLOAD_CONTROL_EEPROM_VALID_TYPE             DV1_FIELD_TYPE_RW

#define DV1_EEPROM_CODE_SIZE_ADDR_CODEEA_LSP  0u
#define DV1_EEPROM_CODE_SIZE_ADDR_CODEEA_LEN  16u
#define DV1_EEPROM_CODE_SIZE_ADDR_CODEEA_TYPE DV1_FIELD_TYPE_RO

#define DV1_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_END_POS_LSP    16u
#define DV1_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_END_POS_LEN    16u
#define DV1_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_END_POS_TYPE   DV1_FIELD_TYPE_RW
#define DV1_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_START_POS_LSP  0u
#define DV1_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_START_POS_LEN  16u
#define DV1_EEPROM_AUTODOWNLOAD_MAC_POSTION_MAC_SEG_START_POS_TYPE DV1_FIELD_TYPE_RW

#define DV1_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_END_POS_LSP    16u
#define DV1_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_END_POS_LEN    16u
#define DV1_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_END_POS_TYPE   DV1_FIELD_TYPE_RW
#define DV1_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_START_POS_LSP  0u
#define DV1_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_START_POS_LEN  16u
#define DV1_EEPROM_AUTODOWNLOAD_PHY_POSTION_PHY_SEG_START_POS_TYPE DV1_FIELD_TYPE_RW

#define DV1_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_END_POS_LSP    16u
#define DV1_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_END_POS_LEN    16u
#define DV1_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_END_POS_TYPE   DV1_FIELD_TYPE_RW
#define DV1_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_START_POS_LSP  0u
#define DV1_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_START_POS_LEN  16u
#define DV1_EEPROM_AUTODOWNLOAD_LUT_POSTION_LUT_SEG_START_POS_TYPE DV1_FIELD_TYPE_RW

#define DV1_EEPROM_STATUS_EEPROM_VALID_FAIL_LSP     4u
#define DV1_EEPROM_STATUS_EEPROM_VALID_FAIL_LEN     1u
#define DV1_EEPROM_STATUS_EEPROM_VALID_FAIL_TYPE    DV1_FIELD_TYPE_RO
#define DV1_EEPROM_STATUS_SEL_EEPROM_ADDR_SIZE_LSP  3u
#define DV1_EEPROM_STATUS_SEL_EEPROM_ADDR_SIZE_LEN  1u
#define DV1_EEPROM_STATUS_SEL_EEPROM_ADDR_SIZE_TYPE DV1_FIELD_TYPE_RO
#define DV1_EEPROM_STATUS_EEPROM_COMPLETE_LSP       2u
#define DV1_EEPROM_STATUS_EEPROM_COMPLETE_LEN       1u
#define DV1_EEPROM_STATUS_EEPROM_COMPLETE_TYPE      DV1_FIELD_TYPE_RO
#define DV1_EEPROM_STATUS_NOEEPROM_LSP              1u
#define DV1_EEPROM_STATUS_NOEEPROM_LEN              1u
#define DV1_EEPROM_STATUS_NOEEPROM_TYPE             DV1_FIELD_TYPE_RO

#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_EXEC_CPU_LSP        31u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_EXEC_CPU_LEN        1u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_EXEC_CPU_TYPE       DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ACCMD_CPU_LSP       30u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ACCMD_CPU_LEN       1u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ACCMD_CPU_TYPE      DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATATYPE_CPU_LSP    29u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATATYPE_CPU_LEN    1u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATATYPE_CPU_TYPE   DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATALENGTH_CPU_LSP  24u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATALENGTH_CPU_LEN  5u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DATALENGTH_CPU_TYPE DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DEVADDR_CPU_LSP     18u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DEVADDR_CPU_LEN     3u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_DEVADDR_CPU_TYPE    DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_SUCCESS_CPU_LSP     17u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_SUCCESS_CPU_LEN     1u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_SUCCESS_CPU_TYPE    DV1_FIELD_TYPE_RW1C
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_RETRY_CPU_LSP       16u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_RETRY_CPU_LEN       1u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_RETRY_CPU_TYPE      DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_HIGH_CPU_LSP   8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_HIGH_CPU_LEN   8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_HIGH_CPU_TYPE  DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_LOW_CPU_LSP    0u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_LOW_CPU_LEN    8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_CONTROL_EEPROM_ADDR_LOW_CPU_TYPE   DV1_FIELD_TYPE_RWS

#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA3_LSP  24u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA3_LEN  8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA3_TYPE DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA2_LSP  16u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA2_LEN  8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA2_TYPE DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA1_LSP  8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA1_LEN  8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA1_TYPE DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA0_LSP  0u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA0_LEN  8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA0_CPU_DATA0_TYPE DV1_FIELD_TYPE_RWS

#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA7_LSP  24u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA7_LEN  8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA7_TYPE DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA6_LSP  16u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA6_LEN  8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA6_TYPE DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA5_LSP  8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA5_LEN  8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA5_TYPE DV1_FIELD_TYPE_RWS
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA4_LSP  0u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA4_LEN  8u
#define DV1_CPU_INDIRECT_ACCESS_EEPROM_DATA1_CPU_DATA4_TYPE DV1_FIELD_TYPE_RWS

#define DV1_I2C_8051_CPU_OCCUPY_STATUS_I2C_8051_OCCUPY_LSP  1u
#define DV1_I2C_8051_CPU_OCCUPY_STATUS_I2C_8051_OCCUPY_LEN  1u
#define DV1_I2C_8051_CPU_OCCUPY_STATUS_I2C_8051_OCCUPY_TYPE DV1_FIELD_TYPE_RWS
#define DV1_I2C_8051_CPU_OCCUPY_STATUS_I2C_CPU_OCCUPY_LSP   0u
#define DV1_I2C_8051_CPU_OCCUPY_STATUS_I2C_CPU_OCCUPY_LEN   1u
#define DV1_I2C_8051_CPU_OCCUPY_STATUS_I2C_CPU_OCCUPY_TYPE  DV1_FIELD_TYPE_RWS

#define DV1_I2C_DMY0_I2C_DMY_REG_0_LSP  0u
#define DV1_I2C_DMY0_I2C_DMY_REG_0_LEN  32u
#define DV1_I2C_DMY0_I2C_DMY_REG_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_REGACC_CHANNEL_CONTROL_SEL_PREM_LSP  0u
#define DV1_REGACC_CHANNEL_CONTROL_SEL_PREM_LEN  2u
#define DV1_REGACC_CHANNEL_CONTROL_SEL_PREM_TYPE DV1_FIELD_TYPE_RW

#define DV1_I2C_DMY1_I2C_DMY_REG_1_LSP  0u
#define DV1_I2C_DMY1_I2C_DMY_REG_1_LEN  32u
#define DV1_I2C_DMY1_I2C_DMY_REG_1_TYPE DV1_FIELD_TYPE_RW

#define DV1_MDC_MDIO_MASTER_CONTROL0_SEL_SMI_FREQ_LSP  9u
#define DV1_MDC_MDIO_MASTER_CONTROL0_SEL_SMI_FREQ_LEN  5u
#define DV1_MDC_MDIO_MASTER_CONTROL0_SEL_SMI_FREQ_TYPE DV1_FIELD_TYPE_RW
#define DV1_MDC_MDIO_MASTER_CONTROL0_SMI_TIMEOUT_LSP   8u
#define DV1_MDC_MDIO_MASTER_CONTROL0_SMI_TIMEOUT_LEN   1u
#define DV1_MDC_MDIO_MASTER_CONTROL0_SMI_TIMEOUT_TYPE  DV1_FIELD_TYPE_RS
#define DV1_MDC_MDIO_MASTER_CONTROL0_SEL_PREM_LSP      2u
#define DV1_MDC_MDIO_MASTER_CONTROL0_SEL_PREM_LEN      2u
#define DV1_MDC_MDIO_MASTER_CONTROL0_SEL_PREM_TYPE     DV1_FIELD_TYPE_RW

#define DV1_MDC_MDIO_MASTER_CONTROL1_PHYADDR_4_0_LSP  0u
#define DV1_MDC_MDIO_MASTER_CONTROL1_PHYADDR_4_0_LEN  5u
#define DV1_MDC_MDIO_MASTER_CONTROL1_PHYADDR_4_0_TYPE DV1_FIELD_TYPE_RW

#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_DATA_15_0_LSP    16u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_DATA_15_0_LEN    16u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_DATA_15_0_TYPE   DV1_FIELD_TYPE_RWS
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_REG_4_0_LSP      8u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_REG_4_0_LEN      5u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_REG_4_0_TYPE     DV1_FIELD_TYPE_RW
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PAGE_4_0_LSP     3u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PAGE_4_0_LEN     5u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PAGE_4_0_TYPE    DV1_FIELD_TYPE_RW
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PHY_REG_TYP_LSP  2u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PHY_REG_TYP_LEN  1u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_PHY_REG_TYP_TYPE DV1_FIELD_TYPE_RW
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_RWOP_LSP         1u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_RWOP_LEN         1u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_RWOP_TYPE        DV1_FIELD_TYPE_RW
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_CDM_LSP          0u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_CDM_LEN          1u
#define DV1_MDC_MDIO_MASTER_REG_ACCESS_CONTROL_0_CDM_TYPE         DV1_FIELD_TYPE_RWS

#define DV1_SPI_SLAVE_CONTROL_SPI_BURST_ENABLE_LSP  5u
#define DV1_SPI_SLAVE_CONTROL_SPI_BURST_ENABLE_LEN  1u
#define DV1_SPI_SLAVE_CONTROL_SPI_BURST_ENABLE_TYPE DV1_FIELD_TYPE_RW
#define DV1_SPI_SLAVE_CONTROL_SPI_DMY_CYCLE_LSP     0u
#define DV1_SPI_SLAVE_CONTROL_SPI_DMY_CYCLE_LEN     5u
#define DV1_SPI_SLAVE_CONTROL_SPI_DMY_CYCLE_TYPE    DV1_FIELD_TYPE_RW

#define DV1_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_TX_GEN_DATA_SEL_LSP  16u
#define DV1_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_TX_GEN_DATA_SEL_LEN  1u
#define DV1_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_TX_GEN_DATA_SEL_TYPE DV1_FIELD_TYPE_RW
#define DV1_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_WR_OP_LSP     8u
#define DV1_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_WR_OP_LEN     8u
#define DV1_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_WR_OP_TYPE    DV1_FIELD_TYPE_RW
#define DV1_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_RD_OP_LSP     0u
#define DV1_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_RD_OP_LEN     8u
#define DV1_SPI_SLAVE_CHECKSUM_CONTROL_CFG_SPI_CHKSUM_RD_OP_TYPE    DV1_FIELD_TYPE_RW

#define DV1_SPI_SLAVE_CHECKSUM_INTERRUPT_STATUS_SLV_CHKSUM_FAIL_INT_STS_LSP  0u
#define DV1_SPI_SLAVE_CHECKSUM_INTERRUPT_STATUS_SLV_CHKSUM_FAIL_INT_STS_LEN  1u
#define DV1_SPI_SLAVE_CHECKSUM_INTERRUPT_STATUS_SLV_CHKSUM_FAIL_INT_STS_TYPE DV1_FIELD_TYPE_RW1C

#define DV1_SPI_SLAVE_CHECKSUM_INTERRUPT_CONTROL_SLV_CHKSUM_FAIL_INT_EN_LSP  0u
#define DV1_SPI_SLAVE_CHECKSUM_INTERRUPT_CONTROL_SLV_CHKSUM_FAIL_INT_EN_LEN  1u
#define DV1_SPI_SLAVE_CHECKSUM_INTERRUPT_CONTROL_SLV_CHKSUM_FAIL_INT_EN_TYPE DV1_FIELD_TYPE_RW

#define DV1_SLAVE_INTERFACE_CHEKSUM_CONTROL_CFG_SLV_CHKSUM_MODE_LSP  0u
#define DV1_SLAVE_INTERFACE_CHEKSUM_CONTROL_CFG_SLV_CHKSUM_MODE_LEN  1u
#define DV1_SLAVE_INTERFACE_CHEKSUM_CONTROL_CFG_SLV_CHKSUM_MODE_TYPE DV1_FIELD_TYPE_RW

#define DV1_REGACC_CHANNEL_FSM_I2C_SM_NS_LSP  6u
#define DV1_REGACC_CHANNEL_FSM_I2C_SM_NS_LEN  6u
#define DV1_REGACC_CHANNEL_FSM_I2C_SM_NS_TYPE DV1_FIELD_TYPE_RO
#define DV1_REGACC_CHANNEL_FSM_I2C_SM_CS_LSP  0u
#define DV1_REGACC_CHANNEL_FSM_I2C_SM_CS_LEN  6u
#define DV1_REGACC_CHANNEL_FSM_I2C_SM_CS_TYPE DV1_FIELD_TYPE_RO

#define DV1_PSEUDO_REG_PAGE_NUMBER_PSEUDO_PG_NUM_LSP  0u
#define DV1_PSEUDO_REG_PAGE_NUMBER_PSEUDO_PG_NUM_LEN  8u
#define DV1_PSEUDO_REG_PAGE_NUMBER_PSEUDO_PG_NUM_TYPE DV1_FIELD_TYPE_RO

#define DV1_PSEUDO_REG_CMD_PSEUDO_CMD_REG_LSP  0u
#define DV1_PSEUDO_REG_CMD_PSEUDO_CMD_REG_LEN  32u
#define DV1_PSEUDO_REG_CMD_PSEUDO_CMD_REG_TYPE DV1_FIELD_TYPE_RO

#define DV1_PSEUDO_REG_DAT_PSEUDO_DAT_REG_LSP  0u
#define DV1_PSEUDO_REG_DAT_PSEUDO_DAT_REG_LEN  32u
#define DV1_PSEUDO_REG_DAT_PSEUDO_DAT_REG_TYPE DV1_FIELD_TYPE_RO

#define DV1_PSEUDO_REG_AUTH_CTRL_PSEUDO_AUTH_CTRL_LSP  0u
#define DV1_PSEUDO_REG_AUTH_CTRL_PSEUDO_AUTH_CTRL_LEN  32u
#define DV1_PSEUDO_REG_AUTH_CTRL_PSEUDO_AUTH_CTRL_TYPE DV1_FIELD_TYPE_RO

#endif
#endif /* DV1_RTKAS_REG_FIELD_FILE_I2C_H_ */