/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_LIST_FILE_MAC_TABLE_ACCESS_H_
#define DV1_RTKAS_REG_LIST_FILE_MAC_TABLE_ACCESS_H_

#ifdef DV1_FILE_MAC_TABLE_ACCESS
/* File: Table Access */
#define DV1_MAC_INDIRECT_CONTROL_FOR_INTERNAL_CPU               0x4A4C0000u
#define DV1_MAC_INDIRECT_CONTROL_FOR_INTERNAL_CPU_FIELDNUM      5u
#define DV1_MAC_INDIRECT_CONTROL_FOR_INTERNAL_CPU_DEFAULTVAL    0x0u
#define DV1_MAC_INDIRECT_DATA0_FOR_INTERNAL_CPU                 0x4A4C0004u
#define DV1_MAC_INDIRECT_DATA0_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DV1_MAC_INDIRECT_DATA0_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DV1_MAC_INDIRECT_DATA1_FOR_INTERNAL_CPU                 0x4A4C0008u
#define DV1_MAC_INDIRECT_DATA1_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DV1_MAC_INDIRECT_DATA1_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DV1_MAC_INDIRECT_DATA2_FOR_INTERNAL_CPU                 0x4A4C000Cu
#define DV1_MAC_INDIRECT_DATA2_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DV1_MAC_INDIRECT_DATA2_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DV1_MAC_INDIRECT_DATA3_FOR_INTERNAL_CPU                 0x4A4C0010u
#define DV1_MAC_INDIRECT_DATA3_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DV1_MAC_INDIRECT_DATA3_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DV1_MAC_INDIRECT_DATA4_FOR_INTERNAL_CPU                 0x4A4C0014u
#define DV1_MAC_INDIRECT_DATA4_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DV1_MAC_INDIRECT_DATA4_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DV1_MAC_INDIRECT_DATA5_FOR_INTERNAL_CPU                 0x4A4C0018u
#define DV1_MAC_INDIRECT_DATA5_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DV1_MAC_INDIRECT_DATA5_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DV1_MAC_INDIRECT_DATA6_FOR_INTERNAL_CPU                 0x4A4C001Cu
#define DV1_MAC_INDIRECT_DATA6_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DV1_MAC_INDIRECT_DATA6_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DV1_MAC_INDIRECT_DATA7_FOR_INTERNAL_CPU                 0x4A4C0020u
#define DV1_MAC_INDIRECT_DATA7_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DV1_MAC_INDIRECT_DATA7_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DV1_MAC_INDIRECT_DATA8_FOR_INTERNAL_CPU                 0x4A4C0024u
#define DV1_MAC_INDIRECT_DATA8_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DV1_MAC_INDIRECT_DATA8_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DV1_MAC_INDIRECT_DATA9_FOR_INTERNAL_CPU                 0x4A4C0028u
#define DV1_MAC_INDIRECT_DATA9_FOR_INTERNAL_CPU_FIELDNUM        1u
#define DV1_MAC_INDIRECT_DATA9_FOR_INTERNAL_CPU_DEFAULTVAL      0x0u
#define DV1_MAC_INDIRECT_DATA10_FOR_INTERNAL_CPU                0x4A4C002Cu
#define DV1_MAC_INDIRECT_DATA10_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA10_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA11_FOR_INTERNAL_CPU                0x4A4C0030u
#define DV1_MAC_INDIRECT_DATA11_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA11_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA12_FOR_INTERNAL_CPU                0x4A4C0034u
#define DV1_MAC_INDIRECT_DATA12_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA12_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA13_FOR_INTERNAL_CPU                0x4A4C0038u
#define DV1_MAC_INDIRECT_DATA13_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA13_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA14_FOR_INTERNAL_CPU                0x4A4C003Cu
#define DV1_MAC_INDIRECT_DATA14_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA14_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA15_FOR_INTERNAL_CPU                0x4A4C0040u
#define DV1_MAC_INDIRECT_DATA15_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA15_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA16_FOR_INTERNAL_CPU                0x4A4C0044u
#define DV1_MAC_INDIRECT_DATA16_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA16_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA17_FOR_INTERNAL_CPU                0x4A4C0048u
#define DV1_MAC_INDIRECT_DATA17_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA17_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA18_FOR_INTERNAL_CPU                0x4A4C004Cu
#define DV1_MAC_INDIRECT_DATA18_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA18_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA19_FOR_INTERNAL_CPU                0x4A4C0050u
#define DV1_MAC_INDIRECT_DATA19_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA19_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA20_FOR_INTERNAL_CPU                0x4A4C0054u
#define DV1_MAC_INDIRECT_DATA20_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA20_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA21_FOR_INTERNAL_CPU                0x4A4C0058u
#define DV1_MAC_INDIRECT_DATA21_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA21_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA22_FOR_INTERNAL_CPU                0x4A4C005Cu
#define DV1_MAC_INDIRECT_DATA22_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA22_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA23_FOR_INTERNAL_CPU                0x4A4C0060u
#define DV1_MAC_INDIRECT_DATA23_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA23_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA24_FOR_INTERNAL_CPU                0x4A4C0064u
#define DV1_MAC_INDIRECT_DATA24_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA24_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA25_FOR_INTERNAL_CPU                0x4A4C0068u
#define DV1_MAC_INDIRECT_DATA25_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA25_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA26_FOR_INTERNAL_CPU                0x4A4C006Cu
#define DV1_MAC_INDIRECT_DATA26_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA26_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA27_FOR_INTERNAL_CPU                0x4A4C0070u
#define DV1_MAC_INDIRECT_DATA27_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA27_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA28_FOR_INTERNAL_CPU                0x4A4C0074u
#define DV1_MAC_INDIRECT_DATA28_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA28_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA29_FOR_INTERNAL_CPU                0x4A4C0078u
#define DV1_MAC_INDIRECT_DATA29_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA29_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA30_FOR_INTERNAL_CPU                0x4A4C007Cu
#define DV1_MAC_INDIRECT_DATA30_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA30_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_DATA31_FOR_INTERNAL_CPU                0x4A4C0080u
#define DV1_MAC_INDIRECT_DATA31_FOR_INTERNAL_CPU_FIELDNUM       1u
#define DV1_MAC_INDIRECT_DATA31_FOR_INTERNAL_CPU_DEFAULTVAL     0x0u
#define DV1_MAC_INDIRECT_OCCUPY_STATUS                          0x4A4C0084u
#define DV1_MAC_INDIRECT_OCCUPY_STATUS_FIELDNUM                 3u
#define DV1_MAC_INDIRECT_OCCUPY_STATUS_DEFAULTVAL               0x0u
#define DV1_MAC_INDIRECT_CONTROL_FOR_EXTERNAL_DEVICE            0x4A4C0088u
#define DV1_MAC_INDIRECT_CONTROL_FOR_EXTERNAL_DEVICE_FIELDNUM   6u
#define DV1_MAC_INDIRECT_CONTROL_FOR_EXTERNAL_DEVICE_DEFAULTVAL 0x0u
#define DV1_MAC_INDIRECT_DATA0_FOR_EXTERNAL_DEVICE              0x4A4C008Cu
#define DV1_MAC_INDIRECT_DATA0_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DV1_MAC_INDIRECT_DATA0_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DV1_MAC_INDIRECT_DATA1_FOR_EXTERNAL_DEVICE              0x4A4C0090u
#define DV1_MAC_INDIRECT_DATA1_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DV1_MAC_INDIRECT_DATA1_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DV1_MAC_INDIRECT_DATA2_FOR_EXTERNAL_DEVICE              0x4A4C0094u
#define DV1_MAC_INDIRECT_DATA2_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DV1_MAC_INDIRECT_DATA2_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DV1_MAC_INDIRECT_DATA3_FOR_EXTERNAL_DEVICE              0x4A4C0098u
#define DV1_MAC_INDIRECT_DATA3_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DV1_MAC_INDIRECT_DATA3_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DV1_MAC_INDIRECT_DATA4_FOR_EXTERNAL_DEVICE              0x4A4C009Cu
#define DV1_MAC_INDIRECT_DATA4_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DV1_MAC_INDIRECT_DATA4_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DV1_MAC_INDIRECT_DATA5_FOR_EXTERNAL_DEVICE              0x4A4C00A0u
#define DV1_MAC_INDIRECT_DATA5_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DV1_MAC_INDIRECT_DATA5_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DV1_MAC_INDIRECT_DATA6_FOR_EXTERNAL_DEVICE              0x4A4C00A4u
#define DV1_MAC_INDIRECT_DATA6_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DV1_MAC_INDIRECT_DATA6_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DV1_MAC_INDIRECT_DATA7_FOR_EXTERNAL_DEVICE              0x4A4C00A8u
#define DV1_MAC_INDIRECT_DATA7_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DV1_MAC_INDIRECT_DATA7_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DV1_MAC_INDIRECT_DATA8_FOR_EXTERNAL_DEVICE              0x4A4C00ACu
#define DV1_MAC_INDIRECT_DATA8_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DV1_MAC_INDIRECT_DATA8_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DV1_MAC_INDIRECT_DATA9_FOR_EXTERNAL_DEVICE              0x4A4C00B0u
#define DV1_MAC_INDIRECT_DATA9_FOR_EXTERNAL_DEVICE_FIELDNUM     1u
#define DV1_MAC_INDIRECT_DATA9_FOR_EXTERNAL_DEVICE_DEFAULTVAL   0x0u
#define DV1_MAC_INDIRECT_DATA10_FOR_EXTERNAL_DEVICE             0x4A4C00B4u
#define DV1_MAC_INDIRECT_DATA10_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA10_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA11_FOR_EXTERNAL_DEVICE             0x4A4C00B8u
#define DV1_MAC_INDIRECT_DATA11_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA11_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA12_FOR_EXTERNAL_DEVICE             0x4A4C00BCu
#define DV1_MAC_INDIRECT_DATA12_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA12_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA13_FOR_EXTERNAL_DEVICE             0x4A4C00C0u
#define DV1_MAC_INDIRECT_DATA13_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA13_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA14_FOR_EXTERNAL_DEVICE             0x4A4C00C4u
#define DV1_MAC_INDIRECT_DATA14_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA14_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA15_FOR_EXTERNAL_DEVICE             0x4A4C00C8u
#define DV1_MAC_INDIRECT_DATA15_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA15_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA16_FOR_EXTERNAL_DEVICE             0x4A4C00CCu
#define DV1_MAC_INDIRECT_DATA16_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA16_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA17_FOR_EXTERNAL_DEVICE             0x4A4C00D0u
#define DV1_MAC_INDIRECT_DATA17_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA17_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA18_FOR_EXTERNAL_DEVICE             0x4A4C00D4u
#define DV1_MAC_INDIRECT_DATA18_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA18_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA19_FOR_EXTERNAL_DEVICE             0x4A4C00D8u
#define DV1_MAC_INDIRECT_DATA19_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA19_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA20_FOR_EXTERNAL_DEVICE             0x4A4C00DCu
#define DV1_MAC_INDIRECT_DATA20_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA20_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA21_FOR_EXTERNAL_DEVICE             0x4A4C00E0u
#define DV1_MAC_INDIRECT_DATA21_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA21_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA22_FOR_EXTERNAL_DEVICE             0x4A4C00E4u
#define DV1_MAC_INDIRECT_DATA22_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA22_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA23_FOR_EXTERNAL_DEVICE             0x4A4C00E8u
#define DV1_MAC_INDIRECT_DATA23_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA23_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA24_FOR_EXTERNAL_DEVICE             0x4A4C00ECu
#define DV1_MAC_INDIRECT_DATA24_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA24_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA25_FOR_EXTERNAL_DEVICE             0x4A4C00F0u
#define DV1_MAC_INDIRECT_DATA25_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA25_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA26_FOR_EXTERNAL_DEVICE             0x4A4C00F4u
#define DV1_MAC_INDIRECT_DATA26_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA26_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA27_FOR_EXTERNAL_DEVICE             0x4A4C00F8u
#define DV1_MAC_INDIRECT_DATA27_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA27_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA28_FOR_EXTERNAL_DEVICE             0x4A4C00FCu
#define DV1_MAC_INDIRECT_DATA28_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA28_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA29_FOR_EXTERNAL_DEVICE             0x4A4C0100u
#define DV1_MAC_INDIRECT_DATA29_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA29_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA30_FOR_EXTERNAL_DEVICE             0x4A4C0104u
#define DV1_MAC_INDIRECT_DATA30_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA30_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_INDIRECT_DATA31_FOR_EXTERNAL_DEVICE             0x4A4C0108u
#define DV1_MAC_INDIRECT_DATA31_FOR_EXTERNAL_DEVICE_FIELDNUM    1u
#define DV1_MAC_INDIRECT_DATA31_FOR_EXTERNAL_DEVICE_DEFAULTVAL  0x0u
#define DV1_MAC_BURST_OPERATION                                 0x4A4C010Cu
#define DV1_MAC_BURST_OPERATION_FIELDNUM                        3u
#define DV1_MAC_BURST_OPERATION_DEFAULTVAL                      0x0u
#endif
#endif /* DV1_RTKAS_REG_LIST_FILE_MAC_TABLE_ACCESS_H_ */