/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_LIST_FILE_HW_MISC_H_
#define DV1_RTKAS_REG_LIST_FILE_HW_MISC_H_

#ifdef DV1_FILE_HW_MISC
/* File: Hardware Misc */
#define DV1_HARDWARE_MISC                                 0x4A460000u
#define DV1_HARDWARE_MISC_FIELDNUM                        24u
#define DV1_HARDWARE_MISC_DEFAULTVAL                      0x9F001002u
#define DV1_DGL_DEBUG0                                    0x4A460004u
#define DV1_DGL_DEBUG0_FIELDNUM                           1u
#define DV1_DGL_DEBUG0_DEFAULTVAL                         0x0u
#define DV1_DGL_DEBUG1                                    0x4A460008u
#define DV1_DGL_DEBUG1_FIELDNUM                           1u
#define DV1_DGL_DEBUG1_DEFAULTVAL                         0x0u
#define DV1_INTERNAL_BONDING_DEBUG                        0x4A46000Cu
#define DV1_INTERNAL_BONDING_DEBUG_FIELDNUM               1u
#define DV1_INTERNAL_BONDING_DEBUG_DEFAULTVAL             0x0u
#define DV1_INTERNAL_STRAPPING_DEBUG0                     0x4A460010u
#define DV1_INTERNAL_STRAPPING_DEBUG0_FIELDNUM            1u
#define DV1_INTERNAL_STRAPPING_DEBUG0_DEFAULTVAL          0x0u
#define DV1_INTERNAL_READ                                 0x4A460014u
#define DV1_INTERNAL_READ_FIELDNUM                        3u
#define DV1_INTERNAL_READ_DEFAULTVAL                      0x0u
#define DV1_BIAS_CONTROL                                  0x4A460018u
#define DV1_BIAS_CONTROL_FIELDNUM                         7u
#define DV1_BIAS_CONTROL_DEFAULTVAL                       0x0u
#define DV1_HW_MISC_DMY_REG_0                             0x4A46001Cu
#define DV1_HW_MISC_DMY_REG_0_FIELDNUM                    1u
#define DV1_HW_MISC_DMY_REG_0_DEFAULTVAL                  0x0u
#define DV1_HW_MISC_DMY_REG_1                             0x4A460020u
#define DV1_HW_MISC_DMY_REG_1_FIELDNUM                    1u
#define DV1_HW_MISC_DMY_REG_1_DEFAULTVAL                  0x0u
#define DV1_GPHY_GPIO                                     0x4A460024u
#define DV1_GPHY_GPIO_FIELDNUM                            3u
#define DV1_GPHY_GPIO_DEFAULTVAL                          0x0u
#define DV1_DEBUG0                                        0x4A460028u
#define DV1_DEBUG0_FIELDNUM                               1u
#define DV1_DEBUG0_DEFAULTVAL                             0x0u
#define DV1_DEBUG1                                        0x4A46002Cu
#define DV1_DEBUG1_FIELDNUM                               1u
#define DV1_DEBUG1_DEFAULTVAL                             0x0u
#define DV1_DEBUG2                                        0x4A460030u
#define DV1_DEBUG2_FIELDNUM                               1u
#define DV1_DEBUG2_DEFAULTVAL                             0x0u
#define DV1_DEBUG3                                        0x4A460034u
#define DV1_DEBUG3_FIELDNUM                               1u
#define DV1_DEBUG3_DEFAULTVAL                             0x0u
#define DV1_DEBUG4                                        0x4A460038u
#define DV1_DEBUG4_FIELDNUM                               1u
#define DV1_DEBUG4_DEFAULTVAL                             0x0u
#define DV1_DEBUG5                                        0x4A46003Cu
#define DV1_DEBUG5_FIELDNUM                               1u
#define DV1_DEBUG5_DEFAULTVAL                             0x0u
#define DV1_DEBUG6                                        0x4A460040u
#define DV1_DEBUG6_FIELDNUM                               1u
#define DV1_DEBUG6_DEFAULTVAL                             0x0u
#define DV1_DEBUG7                                        0x4A460044u
#define DV1_DEBUG7_FIELDNUM                               1u
#define DV1_DEBUG7_DEFAULTVAL                             0x0u
#define DV1_HW_MISC_DMY_REG_2                             0x4A460048u
#define DV1_HW_MISC_DMY_REG_2_FIELDNUM                    1u
#define DV1_HW_MISC_DMY_REG_2_DEFAULTVAL                  0x0u
#define DV1_HW_MISC_DMY_REG_3                             0x4A46004Cu
#define DV1_HW_MISC_DMY_REG_3_FIELDNUM                    1u
#define DV1_HW_MISC_DMY_REG_3_DEFAULTVAL                  0x0u
#define DV1_HW_MISC_DMY_REG_4                             0x4A460050u
#define DV1_HW_MISC_DMY_REG_4_FIELDNUM                    1u
#define DV1_HW_MISC_DMY_REG_4_DEFAULTVAL                  0x0u
#define DV1_IO_CONTROL0                                   0x4A460054u
#define DV1_IO_CONTROL0_FIELDNUM                          1u
#define DV1_IO_CONTROL0_DEFAULTVAL                        0x0u
#define DV1_IO_CONTROL1                                   0x4A460058u
#define DV1_IO_CONTROL1_FIELDNUM                          1u
#define DV1_IO_CONTROL1_DEFAULTVAL                        0x0u
#define DV1_IO_CONTROL2                                   0x4A46005Cu
#define DV1_IO_CONTROL2_FIELDNUM                          2u
#define DV1_IO_CONTROL2_DEFAULTVAL                        0x0u
#define DV1_IO_CONTROL3                                   0x4A460060u
#define DV1_IO_CONTROL3_FIELDNUM                          1u
#define DV1_IO_CONTROL3_DEFAULTVAL                        0x0u
#define DV1_IO_CONTROL4                                   0x4A460064u
#define DV1_IO_CONTROL4_FIELDNUM                          1u
#define DV1_IO_CONTROL4_DEFAULTVAL                        0x0u
#define DV1_IO_CONTROL5                                   0x4A460068u
#define DV1_IO_CONTROL5_FIELDNUM                          2u
#define DV1_IO_CONTROL5_DEFAULTVAL                        0x0u
#define DV1_IO_CONTROL6                                   0x4A46006Cu
#define DV1_IO_CONTROL6_FIELDNUM                          1u
#define DV1_IO_CONTROL6_DEFAULTVAL                        0x0u
#define DV1_IO_CONTROL7                                   0x4A460070u
#define DV1_IO_CONTROL7_FIELDNUM                          1u
#define DV1_IO_CONTROL7_DEFAULTVAL                        0x1800u
#define DV1_IO_CONTROL8                                   0x4A460074u
#define DV1_IO_CONTROL8_FIELDNUM                          2u
#define DV1_IO_CONTROL8_DEFAULTVAL                        0x0u
#define DV1_IO_CONTROL9                                   0x4A460078u
#define DV1_IO_CONTROL9_FIELDNUM                          1u
#define DV1_IO_CONTROL9_DEFAULTVAL                        0x0u
#define DV1_IO_CONTROL10                                  0x4A46007Cu
#define DV1_IO_CONTROL10_FIELDNUM                         1u
#define DV1_IO_CONTROL10_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL11                                  0x4A460080u
#define DV1_IO_CONTROL11_FIELDNUM                         2u
#define DV1_IO_CONTROL11_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL12                                  0x4A460084u
#define DV1_IO_CONTROL12_FIELDNUM                         1u
#define DV1_IO_CONTROL12_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL13                                  0x4A460088u
#define DV1_IO_CONTROL13_FIELDNUM                         1u
#define DV1_IO_CONTROL13_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL14                                  0x4A46008Cu
#define DV1_IO_CONTROL14_FIELDNUM                         2u
#define DV1_IO_CONTROL14_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL15                                  0x4A460090u
#define DV1_IO_CONTROL15_FIELDNUM                         1u
#define DV1_IO_CONTROL15_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL16                                  0x4A460094u
#define DV1_IO_CONTROL16_FIELDNUM                         1u
#define DV1_IO_CONTROL16_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL17                                  0x4A460098u
#define DV1_IO_CONTROL17_FIELDNUM                         2u
#define DV1_IO_CONTROL17_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL18                                  0x4A46009Cu
#define DV1_IO_CONTROL18_FIELDNUM                         16u
#define DV1_IO_CONTROL18_DEFAULTVAL                       0x9000000u
#define DV1_IO_CONTROL19                                  0x4A4600A0u
#define DV1_IO_CONTROL19_FIELDNUM                         12u
#define DV1_IO_CONTROL19_DEFAULTVAL                       0x80000u
#define DV1_LDO_CONTROL0                                  0x4A4600A4u
#define DV1_LDO_CONTROL0_FIELDNUM                         13u
#define DV1_LDO_CONTROL0_DEFAULTVAL                       0x200400u
#define DV1_LDO_CONTROL1                                  0x4A4600A8u
#define DV1_LDO_CONTROL1_FIELDNUM                         16u
#define DV1_LDO_CONTROL1_DEFAULTVAL                       0x200400u
#define DV1_ADDLL_CONTROL0                                0x4A4600ACu
#define DV1_ADDLL_CONTROL0_FIELDNUM                       15u
#define DV1_ADDLL_CONTROL0_DEFAULTVAL                     0x2110000u
#define DV1_ADDLL_CONTROL1                                0x4A4600B0u
#define DV1_ADDLL_CONTROL1_FIELDNUM                       6u
#define DV1_ADDLL_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_ADDLL_CONTROL2                                0x4A4600B4u
#define DV1_ADDLL_CONTROL2_FIELDNUM                       10u
#define DV1_ADDLL_CONTROL2_DEFAULTVAL                     0x0u
#define DV1_ADDLL_CONTROL3                                0x4A4600B8u
#define DV1_ADDLL_CONTROL3_FIELDNUM                       15u
#define DV1_ADDLL_CONTROL3_DEFAULTVAL                     0x2110000u
#define DV1_ADDLL_CONTROL4                                0x4A4600BCu
#define DV1_ADDLL_CONTROL4_FIELDNUM                       6u
#define DV1_ADDLL_CONTROL4_DEFAULTVAL                     0x0u
#define DV1_ADDLL_CONTROL5                                0x4A4600C0u
#define DV1_ADDLL_CONTROL5_FIELDNUM                       10u
#define DV1_ADDLL_CONTROL5_DEFAULTVAL                     0x0u
#define DV1_ADDLL_CONTROL6                                0x4A4600C4u
#define DV1_ADDLL_CONTROL6_FIELDNUM                       15u
#define DV1_ADDLL_CONTROL6_DEFAULTVAL                     0x2110000u
#define DV1_ADDLL_CONTROL7                                0x4A4600C8u
#define DV1_ADDLL_CONTROL7_FIELDNUM                       6u
#define DV1_ADDLL_CONTROL7_DEFAULTVAL                     0x0u
#define DV1_ADDLL_CONTROL8                                0x4A4600CCu
#define DV1_ADDLL_CONTROL8_FIELDNUM                       10u
#define DV1_ADDLL_CONTROL8_DEFAULTVAL                     0x0u
#define DV1_SSC_0_CONTROL0                                0x4A4600D0u
#define DV1_SSC_0_CONTROL0_FIELDNUM                       5u
#define DV1_SSC_0_CONTROL0_DEFAULTVAL                     0x14002001u
#define DV1_SSC_0_CONTROL1                                0x4A4600D4u
#define DV1_SSC_0_CONTROL1_FIELDNUM                       4u
#define DV1_SSC_0_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_SSC_0_CONTROL2                                0x4A4600D8u
#define DV1_SSC_0_CONTROL2_FIELDNUM                       9u
#define DV1_SSC_0_CONTROL2_DEFAULTVAL                     0x30501u
#define DV1_SSC_0_CONTROL3                                0x4A4600DCu
#define DV1_SSC_0_CONTROL3_FIELDNUM                       10u
#define DV1_SSC_0_CONTROL3_DEFAULTVAL                     0x14Eu
#define DV1_SSC_0_CONTROL4                                0x4A4600E0u
#define DV1_SSC_0_CONTROL4_FIELDNUM                       12u
#define DV1_SSC_0_CONTROL4_DEFAULTVAL                     0x320003Du
#define DV1_SSC_1_CONTROL0                                0x4A4600E4u
#define DV1_SSC_1_CONTROL0_FIELDNUM                       5u
#define DV1_SSC_1_CONTROL0_DEFAULTVAL                     0x14002001u
#define DV1_SSC_1_CONTROL1                                0x4A4600E8u
#define DV1_SSC_1_CONTROL1_FIELDNUM                       4u
#define DV1_SSC_1_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_SSC_1_CONTROL2                                0x4A4600ECu
#define DV1_SSC_1_CONTROL2_FIELDNUM                       9u
#define DV1_SSC_1_CONTROL2_DEFAULTVAL                     0x30501u
#define DV1_SSC_1_CONTROL3                                0x4A4600F0u
#define DV1_SSC_1_CONTROL3_FIELDNUM                       10u
#define DV1_SSC_1_CONTROL3_DEFAULTVAL                     0x14Eu
#define DV1_SSC_1_CONTROL4                                0x4A4600F4u
#define DV1_SSC_1_CONTROL4_FIELDNUM                       12u
#define DV1_SSC_1_CONTROL4_DEFAULTVAL                     0x320003Du
#define DV1_SSC_2_CONTROL0                                0x4A4600F8u
#define DV1_SSC_2_CONTROL0_FIELDNUM                       5u
#define DV1_SSC_2_CONTROL0_DEFAULTVAL                     0x14002001u
#define DV1_SSC_2_CONTROL1                                0x4A4600FCu
#define DV1_SSC_2_CONTROL1_FIELDNUM                       4u
#define DV1_SSC_2_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_SSC_2_CONTROL2                                0x4A460100u
#define DV1_SSC_2_CONTROL2_FIELDNUM                       9u
#define DV1_SSC_2_CONTROL2_DEFAULTVAL                     0x30501u
#define DV1_SSC_2_CONTROL3                                0x4A460104u
#define DV1_SSC_2_CONTROL3_FIELDNUM                       10u
#define DV1_SSC_2_CONTROL3_DEFAULTVAL                     0x14Eu
#define DV1_SSC_2_CONTROL4                                0x4A460108u
#define DV1_SSC_2_CONTROL4_FIELDNUM                       12u
#define DV1_SSC_2_CONTROL4_DEFAULTVAL                     0x320003Du
#define DV1_SSC_3_CONTROL0                                0x4A46010Cu
#define DV1_SSC_3_CONTROL0_FIELDNUM                       5u
#define DV1_SSC_3_CONTROL0_DEFAULTVAL                     0x14002001u
#define DV1_SSC_3_CONTROL1                                0x4A460110u
#define DV1_SSC_3_CONTROL1_FIELDNUM                       4u
#define DV1_SSC_3_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_SSC_3_CONTROL2                                0x4A460114u
#define DV1_SSC_3_CONTROL2_FIELDNUM                       9u
#define DV1_SSC_3_CONTROL2_DEFAULTVAL                     0x70501u
#define DV1_SSC_3_CONTROL3                                0x4A460118u
#define DV1_SSC_3_CONTROL3_FIELDNUM                       10u
#define DV1_SSC_3_CONTROL3_DEFAULTVAL                     0x14Eu
#define DV1_SSC_3_CONTROL4                                0x4A46011Cu
#define DV1_SSC_3_CONTROL4_FIELDNUM                       12u
#define DV1_SSC_3_CONTROL4_DEFAULTVAL                     0x320007Du
#define DV1_SSC_4_CONTROL0                                0x4A460120u
#define DV1_SSC_4_CONTROL0_FIELDNUM                       6u
#define DV1_SSC_4_CONTROL0_DEFAULTVAL                     0x14002001u
#define DV1_SSC_4_CONTROL1                                0x4A460124u
#define DV1_SSC_4_CONTROL1_FIELDNUM                       4u
#define DV1_SSC_4_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_SSC_4_CONTROL2                                0x4A460128u
#define DV1_SSC_4_CONTROL2_FIELDNUM                       9u
#define DV1_SSC_4_CONTROL2_DEFAULTVAL                     0x30501u
#define DV1_SSC_4_CONTROL3                                0x4A46012Cu
#define DV1_SSC_4_CONTROL3_FIELDNUM                       10u
#define DV1_SSC_4_CONTROL3_DEFAULTVAL                     0x14Eu
#define DV1_SSC_4_CONTROL4                                0x4A460130u
#define DV1_SSC_4_CONTROL4_FIELDNUM                       12u
#define DV1_SSC_4_CONTROL4_DEFAULTVAL                     0x320003Du
#define DV1_SSC_5_CONTROL0                                0x4A460134u
#define DV1_SSC_5_CONTROL0_FIELDNUM                       6u
#define DV1_SSC_5_CONTROL0_DEFAULTVAL                     0x14002001u
#define DV1_SSC_5_CONTROL1                                0x4A460138u
#define DV1_SSC_5_CONTROL1_FIELDNUM                       4u
#define DV1_SSC_5_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_SSC_5_CONTROL2                                0x4A46013Cu
#define DV1_SSC_5_CONTROL2_FIELDNUM                       9u
#define DV1_SSC_5_CONTROL2_DEFAULTVAL                     0x30501u
#define DV1_SSC_5_CONTROL3                                0x4A460140u
#define DV1_SSC_5_CONTROL3_FIELDNUM                       10u
#define DV1_SSC_5_CONTROL3_DEFAULTVAL                     0x14Eu
#define DV1_SSC_5_CONTROL4                                0x4A460144u
#define DV1_SSC_5_CONTROL4_FIELDNUM                       12u
#define DV1_SSC_5_CONTROL4_DEFAULTVAL                     0x320003Du
#define DV1_SSC_6_CONTROL0                                0x4A460148u
#define DV1_SSC_6_CONTROL0_FIELDNUM                       6u
#define DV1_SSC_6_CONTROL0_DEFAULTVAL                     0x14002001u
#define DV1_SSC_6_CONTROL1                                0x4A46014Cu
#define DV1_SSC_6_CONTROL1_FIELDNUM                       4u
#define DV1_SSC_6_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_SSC_6_CONTROL2                                0x4A460150u
#define DV1_SSC_6_CONTROL2_FIELDNUM                       9u
#define DV1_SSC_6_CONTROL2_DEFAULTVAL                     0x30501u
#define DV1_SSC_6_CONTROL3                                0x4A460154u
#define DV1_SSC_6_CONTROL3_FIELDNUM                       10u
#define DV1_SSC_6_CONTROL3_DEFAULTVAL                     0x14Eu
#define DV1_SSC_6_CONTROL4                                0x4A460158u
#define DV1_SSC_6_CONTROL4_FIELDNUM                       12u
#define DV1_SSC_6_CONTROL4_DEFAULTVAL                     0x320003Du
#define DV1_DSS_0_CONTROL0                                0x4A46015Cu
#define DV1_DSS_0_CONTROL0_FIELDNUM                       6u
#define DV1_DSS_0_CONTROL0_DEFAULTVAL                     0x0u
#define DV1_DSS_0_CONTROL1                                0x4A460160u
#define DV1_DSS_0_CONTROL1_FIELDNUM                       5u
#define DV1_DSS_0_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_DSS_1_CONTROL0                                0x4A460164u
#define DV1_DSS_1_CONTROL0_FIELDNUM                       6u
#define DV1_DSS_1_CONTROL0_DEFAULTVAL                     0x0u
#define DV1_DSS_1_CONTROL1                                0x4A460168u
#define DV1_DSS_1_CONTROL1_FIELDNUM                       5u
#define DV1_DSS_1_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_DSS_2_CONTROL0                                0x4A46016Cu
#define DV1_DSS_2_CONTROL0_FIELDNUM                       6u
#define DV1_DSS_2_CONTROL0_DEFAULTVAL                     0x0u
#define DV1_DSS_2_CONTROL1                                0x4A460170u
#define DV1_DSS_2_CONTROL1_FIELDNUM                       5u
#define DV1_DSS_2_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_DSS_3_CONTROL0                                0x4A460174u
#define DV1_DSS_3_CONTROL0_FIELDNUM                       6u
#define DV1_DSS_3_CONTROL0_DEFAULTVAL                     0x0u
#define DV1_DSS_3_CONTROL1                                0x4A460178u
#define DV1_DSS_3_CONTROL1_FIELDNUM                       5u
#define DV1_DSS_3_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_DSS_4_CONTROL0                                0x4A46017Cu
#define DV1_DSS_4_CONTROL0_FIELDNUM                       6u
#define DV1_DSS_4_CONTROL0_DEFAULTVAL                     0x0u
#define DV1_DSS_4_CONTROL1                                0x4A460180u
#define DV1_DSS_4_CONTROL1_FIELDNUM                       5u
#define DV1_DSS_4_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_DSS_5_CONTROL0                                0x4A460184u
#define DV1_DSS_5_CONTROL0_FIELDNUM                       6u
#define DV1_DSS_5_CONTROL0_DEFAULTVAL                     0x0u
#define DV1_DSS_5_CONTROL1                                0x4A460188u
#define DV1_DSS_5_CONTROL1_FIELDNUM                       5u
#define DV1_DSS_5_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_DMY_RESIGSER_0                        0x4A46018Cu
#define DV1_HW_MISC_DMY_RESIGSER_0_FIELDNUM               1u
#define DV1_HW_MISC_DMY_RESIGSER_0_DEFAULTVAL             0x0u
#define DV1_HW_MISC_DMY_RESIGSER_1                        0x4A460190u
#define DV1_HW_MISC_DMY_RESIGSER_1_FIELDNUM               1u
#define DV1_HW_MISC_DMY_RESIGSER_1_DEFAULTVAL             0x0u
#define DV1_HW_MISC_DMY_RESIGSER_2                        0x4A460194u
#define DV1_HW_MISC_DMY_RESIGSER_2_FIELDNUM               1u
#define DV1_HW_MISC_DMY_RESIGSER_2_DEFAULTVAL             0x0u
#define DV1_HW_MISC_DMY_RESIGSER_3                        0x4A460198u
#define DV1_HW_MISC_DMY_RESIGSER_3_FIELDNUM               1u
#define DV1_HW_MISC_DMY_RESIGSER_3_DEFAULTVAL             0x0u
#define DV1_HW_MISC_DMY_RESIGSER_4                        0x4A46019Cu
#define DV1_HW_MISC_DMY_RESIGSER_4_FIELDNUM               1u
#define DV1_HW_MISC_DMY_RESIGSER_4_DEFAULTVAL             0x0u
#define DV1_HW_MISC_DMY_RESIGSER_5                        0x4A4601A0u
#define DV1_HW_MISC_DMY_RESIGSER_5_FIELDNUM               1u
#define DV1_HW_MISC_DMY_RESIGSER_5_DEFAULTVAL             0x0u
#define DV1_HW_MISC_DMY_RESIGSER_6                        0x4A4601A4u
#define DV1_HW_MISC_DMY_RESIGSER_6_FIELDNUM               1u
#define DV1_HW_MISC_DMY_RESIGSER_6_DEFAULTVAL             0x0u
#define DV1_HW_MISC_DMY_RESIGSER_7                        0x4A4601A8u
#define DV1_HW_MISC_DMY_RESIGSER_7_FIELDNUM               1u
#define DV1_HW_MISC_DMY_RESIGSER_7_DEFAULTVAL             0x0u
#define DV1_HW_MISC_DMY_RESIGSER_8                        0x4A4601ACu
#define DV1_HW_MISC_DMY_RESIGSER_8_FIELDNUM               1u
#define DV1_HW_MISC_DMY_RESIGSER_8_DEFAULTVAL             0x0u
#define DV1_HW_MISC_DMY_RESIGSER_9                        0x4A4601B0u
#define DV1_HW_MISC_DMY_RESIGSER_9_FIELDNUM               1u
#define DV1_HW_MISC_DMY_RESIGSER_9_DEFAULTVAL             0x0u
#define DV1_HW_MISC_DMY_RESIGSER_10                       0x4A4601B4u
#define DV1_HW_MISC_DMY_RESIGSER_10_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_10_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_11                       0x4A4601B8u
#define DV1_HW_MISC_DMY_RESIGSER_11_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_11_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_12                       0x4A4601BCu
#define DV1_HW_MISC_DMY_RESIGSER_12_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_12_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_13                       0x4A4601C0u
#define DV1_HW_MISC_DMY_RESIGSER_13_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_13_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_14                       0x4A4601C4u
#define DV1_HW_MISC_DMY_RESIGSER_14_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_14_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_15                       0x4A4601C8u
#define DV1_HW_MISC_DMY_RESIGSER_15_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_15_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_16                       0x4A4601CCu
#define DV1_HW_MISC_DMY_RESIGSER_16_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_16_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_17                       0x4A4601D0u
#define DV1_HW_MISC_DMY_RESIGSER_17_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_17_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_18                       0x4A4601D4u
#define DV1_HW_MISC_DMY_RESIGSER_18_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_18_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_19                       0x4A4601D8u
#define DV1_HW_MISC_DMY_RESIGSER_19_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_19_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_20                       0x4A4601DCu
#define DV1_HW_MISC_DMY_RESIGSER_20_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_20_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_21                       0x4A4601E0u
#define DV1_HW_MISC_DMY_RESIGSER_21_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_21_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_22                       0x4A4601E4u
#define DV1_HW_MISC_DMY_RESIGSER_22_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_22_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_23                       0x4A4601E8u
#define DV1_HW_MISC_DMY_RESIGSER_23_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_23_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_24                       0x4A4601ECu
#define DV1_HW_MISC_DMY_RESIGSER_24_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_24_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_25                       0x4A4601F0u
#define DV1_HW_MISC_DMY_RESIGSER_25_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_25_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_26                       0x4A4601F4u
#define DV1_HW_MISC_DMY_RESIGSER_26_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_26_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_27                       0x4A4601F8u
#define DV1_HW_MISC_DMY_RESIGSER_27_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_27_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_28                       0x4A4601FCu
#define DV1_HW_MISC_DMY_RESIGSER_28_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_28_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_29                       0x4A460200u
#define DV1_HW_MISC_DMY_RESIGSER_29_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_29_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_30                       0x4A460204u
#define DV1_HW_MISC_DMY_RESIGSER_30_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_30_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_31                       0x4A460208u
#define DV1_HW_MISC_DMY_RESIGSER_31_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_31_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_32                       0x4A46020Cu
#define DV1_HW_MISC_DMY_RESIGSER_32_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_32_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_33                       0x4A460210u
#define DV1_HW_MISC_DMY_RESIGSER_33_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_33_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_34                       0x4A460214u
#define DV1_HW_MISC_DMY_RESIGSER_34_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_34_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_35                       0x4A460218u
#define DV1_HW_MISC_DMY_RESIGSER_35_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_35_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_36                       0x4A46021Cu
#define DV1_HW_MISC_DMY_RESIGSER_36_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_36_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_37                       0x4A460220u
#define DV1_HW_MISC_DMY_RESIGSER_37_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_37_DEFAULTVAL            0x0u
#define DV1_HW_MISC_DMY_RESIGSER_38                       0x4A460224u
#define DV1_HW_MISC_DMY_RESIGSER_38_FIELDNUM              1u
#define DV1_HW_MISC_DMY_RESIGSER_38_DEFAULTVAL            0x0u
#define DV1_BOOTUP_MBIST_CONTROL0                         0x4A460228u
#define DV1_BOOTUP_MBIST_CONTROL0_FIELDNUM                29u
#define DV1_BOOTUP_MBIST_CONTROL0_DEFAULTVAL              0x0u
#define DV1_BOOTUP_MBIST_CONTROL1                         0x4A46022Cu
#define DV1_BOOTUP_MBIST_CONTROL1_FIELDNUM                2u
#define DV1_BOOTUP_MBIST_CONTROL1_DEFAULTVAL              0x0u
#define DV1_BOOTUP_MBIST_CONTROL2                         0x4A460230u
#define DV1_BOOTUP_MBIST_CONTROL2_FIELDNUM                1u
#define DV1_BOOTUP_MBIST_CONTROL2_DEFAULTVAL              0x0u
#define DV1_BOOTUP_MBIST_CONTROL3                         0x4A460234u
#define DV1_BOOTUP_MBIST_CONTROL3_FIELDNUM                1u
#define DV1_BOOTUP_MBIST_CONTROL3_DEFAULTVAL              0x0u
#define DV1_BOOTUP_MBIST_CONTROL4                         0x4A460238u
#define DV1_BOOTUP_MBIST_CONTROL4_FIELDNUM                1u
#define DV1_BOOTUP_MBIST_CONTROL4_DEFAULTVAL              0x0u
#define DV1_BOOTUP_MBIST_CONTROL5                         0x4A46023Cu
#define DV1_BOOTUP_MBIST_CONTROL5_FIELDNUM                1u
#define DV1_BOOTUP_MBIST_CONTROL5_DEFAULTVAL              0x0u
#define DV1_BOOTUP_MBIST_CONTROL6                         0x4A460240u
#define DV1_BOOTUP_MBIST_CONTROL6_FIELDNUM                1u
#define DV1_BOOTUP_MBIST_CONTROL6_DEFAULTVAL              0x0u
#define DV1_BOOTUP_MBIST_CONTROL7                         0x4A460244u
#define DV1_BOOTUP_MBIST_CONTROL7_FIELDNUM                1u
#define DV1_BOOTUP_MBIST_CONTROL7_DEFAULTVAL              0x0u
#define DV1_TCAM_BIST_CONTROL0                            0x4A460248u
#define DV1_TCAM_BIST_CONTROL0_FIELDNUM                   2u
#define DV1_TCAM_BIST_CONTROL0_DEFAULTVAL                 0x0u
#define DV1_TCAM_BIST_CONTROL1                            0x4A46024Cu
#define DV1_TCAM_BIST_CONTROL1_FIELDNUM                   8u
#define DV1_TCAM_BIST_CONTROL1_DEFAULTVAL                 0x7u
#define DV1_TCAM_BIST_CONTROL2                            0x4A460250u
#define DV1_TCAM_BIST_CONTROL2_FIELDNUM                   14u
#define DV1_TCAM_BIST_CONTROL2_DEFAULTVAL                 0x7u
#define DV1_IO_OUTPUT0                                    0x4A460254u
#define DV1_IO_OUTPUT0_FIELDNUM                           1u
#define DV1_IO_OUTPUT0_DEFAULTVAL                         0x0u
#define DV1_IO_OUTPUT1                                    0x4A460258u
#define DV1_IO_OUTPUT1_FIELDNUM                           1u
#define DV1_IO_OUTPUT1_DEFAULTVAL                         0x0u
#define DV1_IO_OUTPUT2                                    0x4A46025Cu
#define DV1_IO_OUTPUT2_FIELDNUM                           2u
#define DV1_IO_OUTPUT2_DEFAULTVAL                         0x0u
#define DV1_IO_OUTPUT3                                    0x4A460260u
#define DV1_IO_OUTPUT3_FIELDNUM                           1u
#define DV1_IO_OUTPUT3_DEFAULTVAL                         0x0u
#define DV1_IO_OUTPUT4                                    0x4A460264u
#define DV1_IO_OUTPUT4_FIELDNUM                           1u
#define DV1_IO_OUTPUT4_DEFAULTVAL                         0x0u
#define DV1_IO_OUTPUT5                                    0x4A460268u
#define DV1_IO_OUTPUT5_FIELDNUM                           3u
#define DV1_IO_OUTPUT5_DEFAULTVAL                         0x0u
#define DV1_IO_CONTROL20                                  0x4A46026Cu
#define DV1_IO_CONTROL20_FIELDNUM                         1u
#define DV1_IO_CONTROL20_DEFAULTVAL                       0x0u
#define DV1_SW_ECC0                                       0x4A460270u
#define DV1_SW_ECC0_FIELDNUM                              1u
#define DV1_SW_ECC0_DEFAULTVAL                            0x0u
#define DV1_SW_ECC1                                       0x4A460274u
#define DV1_SW_ECC1_FIELDNUM                              1u
#define DV1_SW_ECC1_DEFAULTVAL                            0x0u
#define DV1_SW_ECC2                                       0x4A460278u
#define DV1_SW_ECC2_FIELDNUM                              1u
#define DV1_SW_ECC2_DEFAULTVAL                            0x0u
#define DV1_SW_ECC3                                       0x4A46027Cu
#define DV1_SW_ECC3_FIELDNUM                              1u
#define DV1_SW_ECC3_DEFAULTVAL                            0x0u
#define DV1_SW_ECC4                                       0x4A460280u
#define DV1_SW_ECC4_FIELDNUM                              1u
#define DV1_SW_ECC4_DEFAULTVAL                            0x0u
#define DV1_SW_ECC5                                       0x4A460284u
#define DV1_SW_ECC5_FIELDNUM                              1u
#define DV1_SW_ECC5_DEFAULTVAL                            0x0u
#define DV1_SW_ECC6                                       0x4A460288u
#define DV1_SW_ECC6_FIELDNUM                              1u
#define DV1_SW_ECC6_DEFAULTVAL                            0x0u
#define DV1_SW_ECC7                                       0x4A46028Cu
#define DV1_SW_ECC7_FIELDNUM                              1u
#define DV1_SW_ECC7_DEFAULTVAL                            0x0u
#define DV1_SW_ECC8                                       0x4A460290u
#define DV1_SW_ECC8_FIELDNUM                              1u
#define DV1_SW_ECC8_DEFAULTVAL                            0x0u
#define DV1_ALE_ECC0                                      0x4A460294u
#define DV1_ALE_ECC0_FIELDNUM                             1u
#define DV1_ALE_ECC0_DEFAULTVAL                           0x0u
#define DV1_ALE_ECC1                                      0x4A460298u
#define DV1_ALE_ECC1_FIELDNUM                             1u
#define DV1_ALE_ECC1_DEFAULTVAL                           0x0u
#define DV1_ALE_ECC2                                      0x4A46029Cu
#define DV1_ALE_ECC2_FIELDNUM                             1u
#define DV1_ALE_ECC2_DEFAULTVAL                           0x0u
#define DV1_ALE_ECC3                                      0x4A4602A0u
#define DV1_ALE_ECC3_FIELDNUM                             1u
#define DV1_ALE_ECC3_DEFAULTVAL                           0x0u
#define DV1_ALE_ECC4                                      0x4A4602A4u
#define DV1_ALE_ECC4_FIELDNUM                             1u
#define DV1_ALE_ECC4_DEFAULTVAL                           0x0u
#define DV1_ALE_ECC5                                      0x4A4602A8u
#define DV1_ALE_ECC5_FIELDNUM                             1u
#define DV1_ALE_ECC5_DEFAULTVAL                           0x0u
#define DV1_ALE_ECC6                                      0x4A4602ACu
#define DV1_ALE_ECC6_FIELDNUM                             1u
#define DV1_ALE_ECC6_DEFAULTVAL                           0x0u
#define DV1_ALE_ECC7                                      0x4A4602B0u
#define DV1_ALE_ECC7_FIELDNUM                             1u
#define DV1_ALE_ECC7_DEFAULTVAL                           0x0u
#define DV1_ALE_ECC8                                      0x4A4602B4u
#define DV1_ALE_ECC8_FIELDNUM                             1u
#define DV1_ALE_ECC8_DEFAULTVAL                           0x0u
#define DV1_ALE_ECC9                                      0x4A4602B8u
#define DV1_ALE_ECC9_FIELDNUM                             1u
#define DV1_ALE_ECC9_DEFAULTVAL                           0x0u
#define DV1_SW_ECC_PRE_WRITE_STATUS0                      0x4A4602BCu
#define DV1_SW_ECC_PRE_WRITE_STATUS0_FIELDNUM             28u
#define DV1_SW_ECC_PRE_WRITE_STATUS0_DEFAULTVAL           0x0u
#define DV1_SW_ECC_PRE_WRITE_ALL_STATUS1                  0x4A4602C0u
#define DV1_SW_ECC_PRE_WRITE_ALL_STATUS1_FIELDNUM         13u
#define DV1_SW_ECC_PRE_WRITE_ALL_STATUS1_DEFAULTVAL       0x0u
#define DV1_SW_SRAM_MODE0                                 0x4A4602C4u
#define DV1_SW_SRAM_MODE0_FIELDNUM                        2u
#define DV1_SW_SRAM_MODE0_DEFAULTVAL                      0x0u
#define DV1_SW_SRAM_MODE1                                 0x4A4602C8u
#define DV1_SW_SRAM_MODE1_FIELDNUM                        2u
#define DV1_SW_SRAM_MODE1_DEFAULTVAL                      0x0u
#define DV1_SW_SRAM_MODE2                                 0x4A4602CCu
#define DV1_SW_SRAM_MODE2_FIELDNUM                        2u
#define DV1_SW_SRAM_MODE2_DEFAULTVAL                      0x0u
#define DV1_SW_SRAM_MODE3                                 0x4A4602D0u
#define DV1_SW_SRAM_MODE3_FIELDNUM                        2u
#define DV1_SW_SRAM_MODE3_DEFAULTVAL                      0x0u
#define DV1_SW_SRAM_MODE4                                 0x4A4602D4u
#define DV1_SW_SRAM_MODE4_FIELDNUM                        2u
#define DV1_SW_SRAM_MODE4_DEFAULTVAL                      0x0u
#define DV1_CLK_RST_CLOCK_ENABLE                          0x4A4602D8u
#define DV1_CLK_RST_CLOCK_ENABLE_FIELDNUM                 12u
#define DV1_CLK_RST_CLOCK_ENABLE_DEFAULTVAL               0x6FFu
#define DV1_HARDWARE_MISC2                                0x4A4602DCu
#define DV1_HARDWARE_MISC2_FIELDNUM                       12u
#define DV1_HARDWARE_MISC2_DEFAULTVAL                     0x0u
#define DV1_DEBUG_GROUP_SELECTION                         0x4A4602E0u
#define DV1_DEBUG_GROUP_SELECTION_FIELDNUM                16u
#define DV1_DEBUG_GROUP_SELECTION_DEFAULTVAL              0x0u
#define DV1_MII_TEST_DEBUG                                0x4A4602E4u
#define DV1_MII_TEST_DEBUG_FIELDNUM                       4u
#define DV1_MII_TEST_DEBUG_DEFAULTVAL                     0x0u
#define DV1_WRITE_LOCK                                    0x4A4602E8u
#define DV1_WRITE_LOCK_FIELDNUM                           2u
#define DV1_WRITE_LOCK_DEFAULTVAL                         0x0u
#define DV1_PAD_MUX_INFO_2                                0x4A4602ECu
#define DV1_PAD_MUX_INFO_2_FIELDNUM                       1u
#define DV1_PAD_MUX_INFO_2_DEFAULTVAL                     0xC00u
#define DV1_IO_CONTROL21                                  0x4A4602F0u
#define DV1_IO_CONTROL21_FIELDNUM                         2u
#define DV1_IO_CONTROL21_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL22                                  0x4A4602F4u
#define DV1_IO_CONTROL22_FIELDNUM                         2u
#define DV1_IO_CONTROL22_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL23                                  0x4A4602F8u
#define DV1_IO_CONTROL23_FIELDNUM                         2u
#define DV1_IO_CONTROL23_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL24                                  0x4A4602FCu
#define DV1_IO_CONTROL24_FIELDNUM                         2u
#define DV1_IO_CONTROL24_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL25                                  0x4A460300u
#define DV1_IO_CONTROL25_FIELDNUM                         2u
#define DV1_IO_CONTROL25_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL26                                  0x4A460304u
#define DV1_IO_CONTROL26_FIELDNUM                         2u
#define DV1_IO_CONTROL26_DEFAULTVAL                       0x0u
#define DV1_IO_OUTPUT6                                    0x4A460308u
#define DV1_IO_OUTPUT6_FIELDNUM                           2u
#define DV1_IO_OUTPUT6_DEFAULTVAL                         0x0u
#define DV1_IO_OUTPUT7                                    0x4A46030Cu
#define DV1_IO_OUTPUT7_FIELDNUM                           2u
#define DV1_IO_OUTPUT7_DEFAULTVAL                         0x0u
#define DV1_ADDLL_0_CTRL_HW_MISC                          0x4A460310u
#define DV1_ADDLL_0_CTRL_HW_MISC_FIELDNUM                 12u
#define DV1_ADDLL_0_CTRL_HW_MISC_DEFAULTVAL               0x0u
#define DV1_ADDLL_1_CTRL_HW_MISC                          0x4A460314u
#define DV1_ADDLL_1_CTRL_HW_MISC_FIELDNUM                 12u
#define DV1_ADDLL_1_CTRL_HW_MISC_DEFAULTVAL               0x0u
#define DV1_ADDLL_2_CTRL_HW_MISC                          0x4A460318u
#define DV1_ADDLL_2_CTRL_HW_MISC_FIELDNUM                 12u
#define DV1_ADDLL_2_CTRL_HW_MISC_DEFAULTVAL               0x0u
#define DV1_SW_ID_SEL                                     0x4A46031Cu
#define DV1_SW_ID_SEL_FIELDNUM                            2u
#define DV1_SW_ID_SEL_DEFAULTVAL                          0x1u
#define DV1_HW_MISC_RSV_0                                 0x4A460320u
#define DV1_HW_MISC_RSV_0_FIELDNUM                        1u
#define DV1_HW_MISC_RSV_0_DEFAULTVAL                      0x0u
#define DV1_HW_MISC_RSV_1                                 0x4A460324u
#define DV1_HW_MISC_RSV_1_FIELDNUM                        1u
#define DV1_HW_MISC_RSV_1_DEFAULTVAL                      0x0u
#define DV1_HW_MISC_RSV_2                                 0x4A460328u
#define DV1_HW_MISC_RSV_2_FIELDNUM                        1u
#define DV1_HW_MISC_RSV_2_DEFAULTVAL                      0x0u
#define DV1_HW_MISC_RSV_3                                 0x4A46032Cu
#define DV1_HW_MISC_RSV_3_FIELDNUM                        1u
#define DV1_HW_MISC_RSV_3_DEFAULTVAL                      0x0u
#define DV1_HW_MISC_RSV_4                                 0x4A460330u
#define DV1_HW_MISC_RSV_4_FIELDNUM                        1u
#define DV1_HW_MISC_RSV_4_DEFAULTVAL                      0x0u
#define DV1_HW_MISC_RSV_5                                 0x4A460334u
#define DV1_HW_MISC_RSV_5_FIELDNUM                        1u
#define DV1_HW_MISC_RSV_5_DEFAULTVAL                      0x0u
#define DV1_HW_MISC_RSV_6                                 0x4A460338u
#define DV1_HW_MISC_RSV_6_FIELDNUM                        1u
#define DV1_HW_MISC_RSV_6_DEFAULTVAL                      0x0u
#define DV1_HW_MISC_RSV_7                                 0x4A46033Cu
#define DV1_HW_MISC_RSV_7_FIELDNUM                        1u
#define DV1_HW_MISC_RSV_7_DEFAULTVAL                      0x0u
#define DV1_HW_MISC_RSV_8                                 0x4A460340u
#define DV1_HW_MISC_RSV_8_FIELDNUM                        1u
#define DV1_HW_MISC_RSV_8_DEFAULTVAL                      0x0u
#define DV1_HW_MISC_RSV_9                                 0x4A460344u
#define DV1_HW_MISC_RSV_9_FIELDNUM                        1u
#define DV1_HW_MISC_RSV_9_DEFAULTVAL                      0x0u
#define DV1_HW_MISC_RSV_10                                0x4A460348u
#define DV1_HW_MISC_RSV_10_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_10_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_11                                0x4A46034Cu
#define DV1_HW_MISC_RSV_11_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_11_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_12                                0x4A460350u
#define DV1_HW_MISC_RSV_12_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_12_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_13                                0x4A460354u
#define DV1_HW_MISC_RSV_13_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_13_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_14                                0x4A460358u
#define DV1_HW_MISC_RSV_14_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_14_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_15                                0x4A46035Cu
#define DV1_HW_MISC_RSV_15_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_15_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_16                                0x4A460360u
#define DV1_HW_MISC_RSV_16_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_16_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_17                                0x4A460364u
#define DV1_HW_MISC_RSV_17_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_17_DEFAULTVAL                     0x0u
#define DV1_INT_PHY_TOP_CTL_INDIR_ACCESS_CMD              0x4A460368u
#define DV1_INT_PHY_TOP_CTL_INDIR_ACCESS_CMD_FIELDNUM     7u
#define DV1_INT_PHY_TOP_CTL_INDIR_ACCESS_CMD_DEFAULTVAL   0x12u
#define DV1_INT_PHY_TOP_CTL_INDIR_ACCESS_WDATA            0x4A46036Cu
#define DV1_INT_PHY_TOP_CTL_INDIR_ACCESS_WDATA_FIELDNUM   1u
#define DV1_INT_PHY_TOP_CTL_INDIR_ACCESS_WDATA_DEFAULTVAL 0x0u
#define DV1_INT_PHY_TOP_CTL_INDIR_ACCESS_RDATA            0x4A460370u
#define DV1_INT_PHY_TOP_CTL_INDIR_ACCESS_RDATA_FIELDNUM   1u
#define DV1_INT_PHY_TOP_CTL_INDIR_ACCESS_RDATA_DEFAULTVAL 0xDEADBEEFu
#define DV1_BOOTUP_MBIST_CONTROL8                         0x4A460374u
#define DV1_BOOTUP_MBIST_CONTROL8_FIELDNUM                32u
#define DV1_BOOTUP_MBIST_CONTROL8_DEFAULTVAL              0x0u
#define DV1_BOOTUP_MBIST_CONTROL9                         0x4A460378u
#define DV1_BOOTUP_MBIST_CONTROL9_FIELDNUM                32u
#define DV1_BOOTUP_MBIST_CONTROL9_DEFAULTVAL              0x0u
#define DV1_I2C_SELECTION_CTRL                            0x4A46037Cu
#define DV1_I2C_SELECTION_CTRL_FIELDNUM                   2u
#define DV1_I2C_SELECTION_CTRL_DEFAULTVAL                 0x0u
#define DV1_DFT_PROTECTION_DFF_0                          0x4A460380u
#define DV1_DFT_PROTECTION_DFF_0_FIELDNUM                 1u
#define DV1_DFT_PROTECTION_DFF_0_DEFAULTVAL               0x0u
#define DV1_WAKEO                                         0x4A460384u
#define DV1_WAKEO_FIELDNUM                                5u
#define DV1_WAKEO_DEFAULTVAL                              0x1400032u
#define DV1_CPU_SIM_DUMMY_REG                             0x4A460388u
#define DV1_CPU_SIM_DUMMY_REG_FIELDNUM                    2u
#define DV1_CPU_SIM_DUMMY_REG_DEFAULTVAL                  0x1234u
#define DV1_TCAM_ERROR_HANDLE_CONTROL_REG                 0x4A46038Cu
#define DV1_TCAM_ERROR_HANDLE_CONTROL_REG_FIELDNUM        3u
#define DV1_TCAM_ERROR_HANDLE_CONTROL_REG_DEFAULTVAL      0x0u
#define DV1_EFUSE_DFF_REG_0                               0x4A460390u
#define DV1_EFUSE_DFF_REG_0_FIELDNUM                      1u
#define DV1_EFUSE_DFF_REG_0_DEFAULTVAL                    0x0u
#define DV1_EFUSE_DFF_REG_1                               0x4A460394u
#define DV1_EFUSE_DFF_REG_1_FIELDNUM                      1u
#define DV1_EFUSE_DFF_REG_1_DEFAULTVAL                    0x0u
#define DV1_EFUSE_DFF_REG_2                               0x4A460398u
#define DV1_EFUSE_DFF_REG_2_FIELDNUM                      1u
#define DV1_EFUSE_DFF_REG_2_DEFAULTVAL                    0x0u
#define DV1_EFUSE_DFF_REG_3                               0x4A46039Cu
#define DV1_EFUSE_DFF_REG_3_FIELDNUM                      1u
#define DV1_EFUSE_DFF_REG_3_DEFAULTVAL                    0x0u
#define DV1_EFUSE_DFF_REG_4                               0x4A4603A0u
#define DV1_EFUSE_DFF_REG_4_FIELDNUM                      1u
#define DV1_EFUSE_DFF_REG_4_DEFAULTVAL                    0x0u
#define DV1_EFUSE_DFF_REG_5                               0x4A4603A4u
#define DV1_EFUSE_DFF_REG_5_FIELDNUM                      1u
#define DV1_EFUSE_DFF_REG_5_DEFAULTVAL                    0x0u
#define DV1_EFUSE_DFF_REG_6                               0x4A4603A8u
#define DV1_EFUSE_DFF_REG_6_FIELDNUM                      1u
#define DV1_EFUSE_DFF_REG_6_DEFAULTVAL                    0x0u
#define DV1_EFUSE_DFF_REG_7                               0x4A4603ACu
#define DV1_EFUSE_DFF_REG_7_FIELDNUM                      1u
#define DV1_EFUSE_DFF_REG_7_DEFAULTVAL                    0x0u
#define DV1_EFUSE2OTP_FLAG                                0x4A4603B0u
#define DV1_EFUSE2OTP_FLAG_FIELDNUM                       5u
#define DV1_EFUSE2OTP_FLAG_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE5                                 0x4A4603B4u
#define DV1_SW_SRAM_MODE5_FIELDNUM                        2u
#define DV1_SW_SRAM_MODE5_DEFAULTVAL                      0x0u
#define DV1_SW_ECC9                                       0x4A4603B8u
#define DV1_SW_ECC9_FIELDNUM                              1u
#define DV1_SW_ECC9_DEFAULTVAL                            0x0u
#define DV1_IO_DBGO_PAD_VDDPST_P5                         0x4A4603BCu
#define DV1_IO_DBGO_PAD_VDDPST_P5_FIELDNUM                1u
#define DV1_IO_DBGO_PAD_VDDPST_P5_DEFAULTVAL              0x0u
#define DV1_IO_DBGO_PAD_VSSPST_P5                         0x4A4603C0u
#define DV1_IO_DBGO_PAD_VSSPST_P5_FIELDNUM                1u
#define DV1_IO_DBGO_PAD_VSSPST_P5_DEFAULTVAL              0x0u
#define DV1_IO_DBGO_PAD_VDDK_P5                           0x4A4603C4u
#define DV1_IO_DBGO_PAD_VDDK_P5_FIELDNUM                  1u
#define DV1_IO_DBGO_PAD_VDDK_P5_DEFAULTVAL                0x0u
#define DV1_IO_DBGO_PAD_GNDK_P5                           0x4A4603C8u
#define DV1_IO_DBGO_PAD_GNDK_P5_FIELDNUM                  1u
#define DV1_IO_DBGO_PAD_GNDK_P5_DEFAULTVAL                0x0u
#define DV1_IO_DBGO_PAD_VDDPST_P4                         0x4A4603CCu
#define DV1_IO_DBGO_PAD_VDDPST_P4_FIELDNUM                1u
#define DV1_IO_DBGO_PAD_VDDPST_P4_DEFAULTVAL              0x0u
#define DV1_IO_DBGO_PAD_VSSPST_P4                         0x4A4603D0u
#define DV1_IO_DBGO_PAD_VSSPST_P4_FIELDNUM                1u
#define DV1_IO_DBGO_PAD_VSSPST_P4_DEFAULTVAL              0x0u
#define DV1_IO_DBGO_PAD_VDDK_P4                           0x4A4603D4u
#define DV1_IO_DBGO_PAD_VDDK_P4_FIELDNUM                  1u
#define DV1_IO_DBGO_PAD_VDDK_P4_DEFAULTVAL                0x0u
#define DV1_IO_DBGO_PAD_GNDK_P4                           0x4A4603D8u
#define DV1_IO_DBGO_PAD_GNDK_P4_FIELDNUM                  1u
#define DV1_IO_DBGO_PAD_GNDK_P4_DEFAULTVAL                0x0u
#define DV1_IO_DBGO_PAD_VDDPST_P9                         0x4A4603DCu
#define DV1_IO_DBGO_PAD_VDDPST_P9_FIELDNUM                1u
#define DV1_IO_DBGO_PAD_VDDPST_P9_DEFAULTVAL              0x0u
#define DV1_IO_DBGO_PAD_VSSPST_P9                         0x4A4603E0u
#define DV1_IO_DBGO_PAD_VSSPST_P9_FIELDNUM                1u
#define DV1_IO_DBGO_PAD_VSSPST_P9_DEFAULTVAL              0x0u
#define DV1_IO_DBGO_PAD_VDDK_P9                           0x4A4603E4u
#define DV1_IO_DBGO_PAD_VDDK_P9_FIELDNUM                  1u
#define DV1_IO_DBGO_PAD_VDDK_P9_DEFAULTVAL                0x0u
#define DV1_IO_DBGO_PAD_GNDK_P9                           0x4A4603E8u
#define DV1_IO_DBGO_PAD_GNDK_P9_FIELDNUM                  1u
#define DV1_IO_DBGO_PAD_GNDK_P9_DEFAULTVAL                0x0u
#define DV1_IO_DBGO_PAD_VDDPST_SPI                        0x4A4603ECu
#define DV1_IO_DBGO_PAD_VDDPST_SPI_FIELDNUM               1u
#define DV1_IO_DBGO_PAD_VDDPST_SPI_DEFAULTVAL             0x0u
#define DV1_IO_DBGO_PAD_VSSPST_SPI                        0x4A4603F0u
#define DV1_IO_DBGO_PAD_VSSPST_SPI_FIELDNUM               1u
#define DV1_IO_DBGO_PAD_VSSPST_SPI_DEFAULTVAL             0x0u
#define DV1_SSC_7_CONTROL0                                0x4A4603F4u
#define DV1_SSC_7_CONTROL0_FIELDNUM                       6u
#define DV1_SSC_7_CONTROL0_DEFAULTVAL                     0x14002001u
#define DV1_SSC_7_CONTROL1                                0x4A4603F8u
#define DV1_SSC_7_CONTROL1_FIELDNUM                       4u
#define DV1_SSC_7_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_SSC_7_CONTROL2                                0x4A4603FCu
#define DV1_SSC_7_CONTROL2_FIELDNUM                       9u
#define DV1_SSC_7_CONTROL2_DEFAULTVAL                     0x30501u
#define DV1_SSC_7_CONTROL3                                0x4A460400u
#define DV1_SSC_7_CONTROL3_FIELDNUM                       10u
#define DV1_SSC_7_CONTROL3_DEFAULTVAL                     0x14Eu
#define DV1_SSC_7_CONTROL4                                0x4A460404u
#define DV1_SSC_7_CONTROL4_FIELDNUM                       12u
#define DV1_SSC_7_CONTROL4_DEFAULTVAL                     0x320003Du
#define DV1_SSC_8_CONTROL0                                0x4A460408u
#define DV1_SSC_8_CONTROL0_FIELDNUM                       6u
#define DV1_SSC_8_CONTROL0_DEFAULTVAL                     0x14002001u
#define DV1_SSC_8_CONTROL1                                0x4A46040Cu
#define DV1_SSC_8_CONTROL1_FIELDNUM                       4u
#define DV1_SSC_8_CONTROL1_DEFAULTVAL                     0x0u
#define DV1_SSC_8_CONTROL2                                0x4A460410u
#define DV1_SSC_8_CONTROL2_FIELDNUM                       9u
#define DV1_SSC_8_CONTROL2_DEFAULTVAL                     0x30501u
#define DV1_SSC_8_CONTROL3                                0x4A460414u
#define DV1_SSC_8_CONTROL3_FIELDNUM                       10u
#define DV1_SSC_8_CONTROL3_DEFAULTVAL                     0x14Eu
#define DV1_SSC_8_CONTROL4                                0x4A460418u
#define DV1_SSC_8_CONTROL4_FIELDNUM                       12u
#define DV1_SSC_8_CONTROL4_DEFAULTVAL                     0x320003Du
#define DV1_ALE_ECCUNUSED                                 0x4A46041Cu
#define DV1_ALE_ECCUNUSED_FIELDNUM                        2u
#define DV1_ALE_ECCUNUSED_DEFAULTVAL                      0x0u
#define DV1_MII_DET_RXC_EN                                0x4A460420u
#define DV1_MII_DET_RXC_EN_FIELDNUM                       7u
#define DV1_MII_DET_RXC_EN_DEFAULTVAL                     0x0u
#define DV1_MII_DET_TXC_EN                                0x4A460424u
#define DV1_MII_DET_TXC_EN_FIELDNUM                       7u
#define DV1_MII_DET_TXC_EN_DEFAULTVAL                     0x0u
#define DV1_P4_MII_DET_RXC_LOCK                           0x4A460428u
#define DV1_P4_MII_DET_RXC_LOCK_FIELDNUM                  2u
#define DV1_P4_MII_DET_RXC_LOCK_DEFAULTVAL                0x0u
#define DV1_P4_MII_DET_RXC_INT                            0x4A46042Cu
#define DV1_P4_MII_DET_RXC_INT_FIELDNUM                   2u
#define DV1_P4_MII_DET_RXC_INT_DEFAULTVAL                 0xFFFFu
#define DV1_P4_MII_DET_RXC_CNT                            0x4A460430u
#define DV1_P4_MII_DET_RXC_CNT_FIELDNUM                   2u
#define DV1_P4_MII_DET_RXC_CNT_DEFAULTVAL                 0x0u
#define DV1_P4_MII_DET_RXC_THR                            0x4A460434u
#define DV1_P4_MII_DET_RXC_THR_FIELDNUM                   2u
#define DV1_P4_MII_DET_RXC_THR_DEFAULTVAL                 0x0u
#define DV1_P9_MII_DET_RXC_LOCK                           0x4A460438u
#define DV1_P9_MII_DET_RXC_LOCK_FIELDNUM                  2u
#define DV1_P9_MII_DET_RXC_LOCK_DEFAULTVAL                0x0u
#define DV1_P9_MII_DET_RXC_INT                            0x4A46043Cu
#define DV1_P9_MII_DET_RXC_INT_FIELDNUM                   2u
#define DV1_P9_MII_DET_RXC_INT_DEFAULTVAL                 0xFFFFu
#define DV1_P9_MII_DET_RXC_CNT                            0x4A460440u
#define DV1_P9_MII_DET_RXC_CNT_FIELDNUM                   2u
#define DV1_P9_MII_DET_RXC_CNT_DEFAULTVAL                 0x0u
#define DV1_P9_MII_DET_RXC_THR                            0x4A460444u
#define DV1_P9_MII_DET_RXC_THR_FIELDNUM                   2u
#define DV1_P9_MII_DET_RXC_THR_DEFAULTVAL                 0x0u
#define DV1_P5_MII_DET_RXC_LOCK                           0x4A460448u
#define DV1_P5_MII_DET_RXC_LOCK_FIELDNUM                  2u
#define DV1_P5_MII_DET_RXC_LOCK_DEFAULTVAL                0x0u
#define DV1_P5_MII_DET_RXC_INT                            0x4A46044Cu
#define DV1_P5_MII_DET_RXC_INT_FIELDNUM                   2u
#define DV1_P5_MII_DET_RXC_INT_DEFAULTVAL                 0xFFFFu
#define DV1_P5_MII_DET_RXC_CNT                            0x4A460450u
#define DV1_P5_MII_DET_RXC_CNT_FIELDNUM                   2u
#define DV1_P5_MII_DET_RXC_CNT_DEFAULTVAL                 0x0u
#define DV1_P5_MII_DET_RXC_THR                            0x4A460454u
#define DV1_P5_MII_DET_RXC_THR_FIELDNUM                   2u
#define DV1_P5_MII_DET_RXC_THR_DEFAULTVAL                 0x0u
#define DV1_P4_MII_DET_TXC_LOCK                           0x4A460458u
#define DV1_P4_MII_DET_TXC_LOCK_FIELDNUM                  2u
#define DV1_P4_MII_DET_TXC_LOCK_DEFAULTVAL                0x0u
#define DV1_P4_MII_DET_TXC_INT                            0x4A46045Cu
#define DV1_P4_MII_DET_TXC_INT_FIELDNUM                   2u
#define DV1_P4_MII_DET_TXC_INT_DEFAULTVAL                 0xFFFFu
#define DV1_P4_MII_DET_TXC_CNT                            0x4A460460u
#define DV1_P4_MII_DET_TXC_CNT_FIELDNUM                   2u
#define DV1_P4_MII_DET_TXC_CNT_DEFAULTVAL                 0x0u
#define DV1_P4_MII_DET_TXC_THR                            0x4A460464u
#define DV1_P4_MII_DET_TXC_THR_FIELDNUM                   2u
#define DV1_P4_MII_DET_TXC_THR_DEFAULTVAL                 0x0u
#define DV1_P9_MII_DET_TXC_LOCK                           0x4A460468u
#define DV1_P9_MII_DET_TXC_LOCK_FIELDNUM                  2u
#define DV1_P9_MII_DET_TXC_LOCK_DEFAULTVAL                0x0u
#define DV1_P9_MII_DET_TXC_INT                            0x4A46046Cu
#define DV1_P9_MII_DET_TXC_INT_FIELDNUM                   2u
#define DV1_P9_MII_DET_TXC_INT_DEFAULTVAL                 0xFFFFu
#define DV1_P9_MII_DET_TXC_CNT                            0x4A460470u
#define DV1_P9_MII_DET_TXC_CNT_FIELDNUM                   2u
#define DV1_P9_MII_DET_TXC_CNT_DEFAULTVAL                 0x0u
#define DV1_P9_MII_DET_TXC_THR                            0x4A460474u
#define DV1_P9_MII_DET_TXC_THR_FIELDNUM                   2u
#define DV1_P9_MII_DET_TXC_THR_DEFAULTVAL                 0x0u
#define DV1_P5_MII_DET_TXC_LOCK                           0x4A460478u
#define DV1_P5_MII_DET_TXC_LOCK_FIELDNUM                  2u
#define DV1_P5_MII_DET_TXC_LOCK_DEFAULTVAL                0x0u
#define DV1_P5_MII_DET_TXC_INT                            0x4A46047Cu
#define DV1_P5_MII_DET_TXC_INT_FIELDNUM                   2u
#define DV1_P5_MII_DET_TXC_INT_DEFAULTVAL                 0xFFFFu
#define DV1_P5_MII_DET_TXC_CNT                            0x4A460480u
#define DV1_P5_MII_DET_TXC_CNT_FIELDNUM                   2u
#define DV1_P5_MII_DET_TXC_CNT_DEFAULTVAL                 0x0u
#define DV1_P5_MII_DET_TXC_THR                            0x4A460484u
#define DV1_P5_MII_DET_TXC_THR_FIELDNUM                   2u
#define DV1_P5_MII_DET_TXC_THR_DEFAULTVAL                 0x0u
#define DV1_P4_AD_DLL_DBG_OUT                             0x4A460488u
#define DV1_P4_AD_DLL_DBG_OUT_FIELDNUM                    2u
#define DV1_P4_AD_DLL_DBG_OUT_DEFAULTVAL                  0x0u
#define DV1_P5_AD_DLL_DBG_OUT                             0x4A46048Cu
#define DV1_P5_AD_DLL_DBG_OUT_FIELDNUM                    2u
#define DV1_P5_AD_DLL_DBG_OUT_DEFAULTVAL                  0x0u
#define DV1_P9_AD_DLL_DBG_OUT                             0x4A460490u
#define DV1_P9_AD_DLL_DBG_OUT_FIELDNUM                    2u
#define DV1_P9_AD_DLL_DBG_OUT_DEFAULTVAL                  0x0u
#define DV1_HW_MISC_RSV_18                                0x4A460494u
#define DV1_HW_MISC_RSV_18_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_18_DEFAULTVAL                     0x0u
#define DV1_SW_ECC10                                      0x4A460498u
#define DV1_SW_ECC10_FIELDNUM                             1u
#define DV1_SW_ECC10_DEFAULTVAL                           0x0u
#define DV1_SW_ECC11                                      0x4A46049Cu
#define DV1_SW_ECC11_FIELDNUM                             1u
#define DV1_SW_ECC11_DEFAULTVAL                           0x0u
#define DV1_SW_SRAM_MODE6                                 0x4A4604A0u
#define DV1_SW_SRAM_MODE6_FIELDNUM                        2u
#define DV1_SW_SRAM_MODE6_DEFAULTVAL                      0x0u
#define DV1_SW_SRAM_MODE7                                 0x4A4604A4u
#define DV1_SW_SRAM_MODE7_FIELDNUM                        2u
#define DV1_SW_SRAM_MODE7_DEFAULTVAL                      0x0u
#define DV1_SW_SRAM_MODE8                                 0x4A4604A8u
#define DV1_SW_SRAM_MODE8_FIELDNUM                        2u
#define DV1_SW_SRAM_MODE8_DEFAULTVAL                      0x0u
#define DV1_MII_DET_TXC_STATUS                            0x4A4604ACu
#define DV1_MII_DET_TXC_STATUS_FIELDNUM                   7u
#define DV1_MII_DET_TXC_STATUS_DEFAULTVAL                 0x0u
#define DV1_MII_DET_RXC_STATUS                            0x4A4604B0u
#define DV1_MII_DET_RXC_STATUS_FIELDNUM                   7u
#define DV1_MII_DET_RXC_STATUS_DEFAULTVAL                 0x0u
#define DV1_P10_MII_DET_RXC_LOCK                          0x4A4604B4u
#define DV1_P10_MII_DET_RXC_LOCK_FIELDNUM                 2u
#define DV1_P10_MII_DET_RXC_LOCK_DEFAULTVAL               0x0u
#define DV1_P10_MII_DET_RXC_INT                           0x4A4604B8u
#define DV1_P10_MII_DET_RXC_INT_FIELDNUM                  2u
#define DV1_P10_MII_DET_RXC_INT_DEFAULTVAL                0xFFFFu
#define DV1_P10_MII_DET_RXC_CNT                           0x4A4604BCu
#define DV1_P10_MII_DET_RXC_CNT_FIELDNUM                  2u
#define DV1_P10_MII_DET_RXC_CNT_DEFAULTVAL                0x0u
#define DV1_P10_MII_DET_RXC_THR                           0x4A4604C0u
#define DV1_P10_MII_DET_RXC_THR_FIELDNUM                  2u
#define DV1_P10_MII_DET_RXC_THR_DEFAULTVAL                0x0u
#define DV1_P10_MII_DET_TXC_LOCK                          0x4A4604C4u
#define DV1_P10_MII_DET_TXC_LOCK_FIELDNUM                 2u
#define DV1_P10_MII_DET_TXC_LOCK_DEFAULTVAL               0x0u
#define DV1_P10_MII_DET_TXC_INT                           0x4A4604C8u
#define DV1_P10_MII_DET_TXC_INT_FIELDNUM                  2u
#define DV1_P10_MII_DET_TXC_INT_DEFAULTVAL                0xFFFFu
#define DV1_P10_MII_DET_TXC_CNT                           0x4A4604CCu
#define DV1_P10_MII_DET_TXC_CNT_FIELDNUM                  2u
#define DV1_P10_MII_DET_TXC_CNT_DEFAULTVAL                0x0u
#define DV1_P10_MII_DET_TXC_THR                           0x4A4604D0u
#define DV1_P10_MII_DET_TXC_THR_FIELDNUM                  2u
#define DV1_P10_MII_DET_TXC_THR_DEFAULTVAL                0x0u
#define DV1_SW_SRAM_MODE9                                 0x4A4604D4u
#define DV1_SW_SRAM_MODE9_FIELDNUM                        2u
#define DV1_SW_SRAM_MODE9_DEFAULTVAL                      0x0u
#define DV1_SW_SRAM_MODE10                                0x4A4604D8u
#define DV1_SW_SRAM_MODE10_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE10_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE11                                0x4A4604DCu
#define DV1_SW_SRAM_MODE11_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE11_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE12                                0x4A4604E0u
#define DV1_SW_SRAM_MODE12_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE12_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE13                                0x4A4604E4u
#define DV1_SW_SRAM_MODE13_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE13_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE14                                0x4A4604E8u
#define DV1_SW_SRAM_MODE14_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE14_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE15                                0x4A4604ECu
#define DV1_SW_SRAM_MODE15_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE15_DEFAULTVAL                     0x0u
#define DV1_ALE_ECC10                                     0x4A4604F0u
#define DV1_ALE_ECC10_FIELDNUM                            1u
#define DV1_ALE_ECC10_DEFAULTVAL                          0x0u
#define DV1_ALE_ECC11                                     0x4A4604F4u
#define DV1_ALE_ECC11_FIELDNUM                            1u
#define DV1_ALE_ECC11_DEFAULTVAL                          0x0u
#define DV1_TXC_ECC0                                      0x4A4604F8u
#define DV1_TXC_ECC0_FIELDNUM                             1u
#define DV1_TXC_ECC0_DEFAULTVAL                           0x0u
#define DV1_ALE_ECC12                                     0x4A4604FCu
#define DV1_ALE_ECC12_FIELDNUM                            1u
#define DV1_ALE_ECC12_DEFAULTVAL                          0x0u
#define DV1_ALE_ECC13                                     0x4A460500u
#define DV1_ALE_ECC13_FIELDNUM                            2u
#define DV1_ALE_ECC13_DEFAULTVAL                          0x0u
#define DV1_DMAC_CONTROL                                  0x4A460504u
#define DV1_DMAC_CONTROL_FIELDNUM                         2u
#define DV1_DMAC_CONTROL_DEFAULTVAL                       0x0u
#define DV1_BOOTUP_MBIST_CONTROL10                        0x4A460508u
#define DV1_BOOTUP_MBIST_CONTROL10_FIELDNUM               25u
#define DV1_BOOTUP_MBIST_CONTROL10_DEFAULTVAL             0x0u
#define DV1_HW_MISC_RSV_19                                0x4A46050Cu
#define DV1_HW_MISC_RSV_19_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_19_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_20                                0x4A460510u
#define DV1_HW_MISC_RSV_20_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_20_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_21                                0x4A460514u
#define DV1_HW_MISC_RSV_21_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_21_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_22                                0x4A460518u
#define DV1_HW_MISC_RSV_22_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_22_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_23                                0x4A46051Cu
#define DV1_HW_MISC_RSV_23_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_23_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_24                                0x4A460520u
#define DV1_HW_MISC_RSV_24_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_24_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_25                                0x4A460524u
#define DV1_HW_MISC_RSV_25_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_25_DEFAULTVAL                     0x0u
#define DV1_HW_MISC_RSV_26                                0x4A460528u
#define DV1_HW_MISC_RSV_26_FIELDNUM                       1u
#define DV1_HW_MISC_RSV_26_DEFAULTVAL                     0x0u
#define DV1_IO_DBGO_PAD_VDDPST_GPIO0                      0x4A46052Cu
#define DV1_IO_DBGO_PAD_VDDPST_GPIO0_FIELDNUM             1u
#define DV1_IO_DBGO_PAD_VDDPST_GPIO0_DEFAULTVAL           0x0u
#define DV1_IO_DBGO_PAD_VSSPST_GPIO0                      0x4A460530u
#define DV1_IO_DBGO_PAD_VSSPST_GPIO0_FIELDNUM             1u
#define DV1_IO_DBGO_PAD_VSSPST_GPIO0_DEFAULTVAL           0x0u
#define DV1_IO_DBGO_PAD_VDDK_GPIO0                        0x4A460534u
#define DV1_IO_DBGO_PAD_VDDK_GPIO0_FIELDNUM               1u
#define DV1_IO_DBGO_PAD_VDDK_GPIO0_DEFAULTVAL             0x0u
#define DV1_IO_DBGO_PAD_GNDK_GPIO0                        0x4A460538u
#define DV1_IO_DBGO_PAD_GNDK_GPIO0_FIELDNUM               1u
#define DV1_IO_DBGO_PAD_GNDK_GPIO0_DEFAULTVAL             0x0u
#define DV1_IO_DBGO_PAD_VDDPST_LED                        0x4A46053Cu
#define DV1_IO_DBGO_PAD_VDDPST_LED_FIELDNUM               1u
#define DV1_IO_DBGO_PAD_VDDPST_LED_DEFAULTVAL             0x0u
#define DV1_IO_DBGO_PAD_VSSPST_LED                        0x4A460540u
#define DV1_IO_DBGO_PAD_VSSPST_LED_FIELDNUM               1u
#define DV1_IO_DBGO_PAD_VSSPST_LED_DEFAULTVAL             0x0u
#define DV1_IO_DBGO_PAD_VDDK_LED                          0x4A460544u
#define DV1_IO_DBGO_PAD_VDDK_LED_FIELDNUM                 1u
#define DV1_IO_DBGO_PAD_VDDK_LED_DEFAULTVAL               0x0u
#define DV1_IO_DBGO_PAD_GNDK_LED                          0x4A460548u
#define DV1_IO_DBGO_PAD_GNDK_LED_FIELDNUM                 1u
#define DV1_IO_DBGO_PAD_GNDK_LED_DEFAULTVAL               0x0u
#define DV1_IO_DBGO_PAD_VDDK_SPI                          0x4A46054Cu
#define DV1_IO_DBGO_PAD_VDDK_SPI_FIELDNUM                 1u
#define DV1_IO_DBGO_PAD_VDDK_SPI_DEFAULTVAL               0x0u
#define DV1_IO_DBGO_PAD_GNDK_SPI                          0x4A460550u
#define DV1_IO_DBGO_PAD_GNDK_SPI_FIELDNUM                 1u
#define DV1_IO_DBGO_PAD_GNDK_SPI_DEFAULTVAL               0x0u
#define DV1_IO_OUTPUT8                                    0x4A460554u
#define DV1_IO_OUTPUT8_FIELDNUM                           2u
#define DV1_IO_OUTPUT8_DEFAULTVAL                         0x0u
#define DV1_IO_OUTPUT9                                    0x4A460558u
#define DV1_IO_OUTPUT9_FIELDNUM                           2u
#define DV1_IO_OUTPUT9_DEFAULTVAL                         0x0u
#define DV1_IO_CONTROL27                                  0x4A46055Cu
#define DV1_IO_CONTROL27_FIELDNUM                         2u
#define DV1_IO_CONTROL27_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL28                                  0x4A460560u
#define DV1_IO_CONTROL28_FIELDNUM                         2u
#define DV1_IO_CONTROL28_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL29                                  0x4A460564u
#define DV1_IO_CONTROL29_FIELDNUM                         2u
#define DV1_IO_CONTROL29_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL30                                  0x4A460568u
#define DV1_IO_CONTROL30_FIELDNUM                         2u
#define DV1_IO_CONTROL30_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL31                                  0x4A46056Cu
#define DV1_IO_CONTROL31_FIELDNUM                         2u
#define DV1_IO_CONTROL31_DEFAULTVAL                       0x0u
#define DV1_IO_CONTROL32                                  0x4A460570u
#define DV1_IO_CONTROL32_FIELDNUM                         2u
#define DV1_IO_CONTROL32_DEFAULTVAL                       0x0u
#define DV1_SW_ECC12                                      0x4A460574u
#define DV1_SW_ECC12_FIELDNUM                             1u
#define DV1_SW_ECC12_DEFAULTVAL                           0x0u
#define DV1_SW_ECC13                                      0x4A460578u
#define DV1_SW_ECC13_FIELDNUM                             2u
#define DV1_SW_ECC13_DEFAULTVAL                           0x0u
#define DV1_MACPHY_SPI_ENDIAN_CONVERSION_0                0x4A46057Cu
#define DV1_MACPHY_SPI_ENDIAN_CONVERSION_0_FIELDNUM       3u
#define DV1_MACPHY_SPI_ENDIAN_CONVERSION_0_DEFAULTVAL     0x0u
#define DV1_MACPHY_SPI_ENDIAN_CONVERSION_1                0x4A460580u
#define DV1_MACPHY_SPI_ENDIAN_CONVERSION_1_FIELDNUM       3u
#define DV1_MACPHY_SPI_ENDIAN_CONVERSION_1_DEFAULTVAL     0x0u
#define DV1_MACPHY_SPI_0_ODD_PARITY_CONTROL0              0x4A460584u
#define DV1_MACPHY_SPI_0_ODD_PARITY_CONTROL0_FIELDNUM     1u
#define DV1_MACPHY_SPI_0_ODD_PARITY_CONTROL0_DEFAULTVAL   0x0u
#define DV1_MACPHY_SPI_0_ODD_PARITY_CONTROL1              0x4A460588u
#define DV1_MACPHY_SPI_0_ODD_PARITY_CONTROL1_FIELDNUM     2u
#define DV1_MACPHY_SPI_0_ODD_PARITY_CONTROL1_DEFAULTVAL   0x0u
#define DV1_MACPHY_SPI_1_ODD_PARITY_CONTROL0              0x4A46058Cu
#define DV1_MACPHY_SPI_1_ODD_PARITY_CONTROL0_FIELDNUM     1u
#define DV1_MACPHY_SPI_1_ODD_PARITY_CONTROL0_DEFAULTVAL   0x0u
#define DV1_MACPHY_SPI_1_ODD_PARITY_CONTROL1              0x4A460590u
#define DV1_MACPHY_SPI_1_ODD_PARITY_CONTROL1_FIELDNUM     2u
#define DV1_MACPHY_SPI_1_ODD_PARITY_CONTROL1_DEFAULTVAL   0x0u
#define DV1_SECUREACCESS_CONTROL                          0x4A460594u
#define DV1_SECUREACCESS_CONTROL_FIELDNUM                 3u
#define DV1_SECUREACCESS_CONTROL_DEFAULTVAL               0x0u
#define DV1_DGL_DEBUG2                                    0x4A460598u
#define DV1_DGL_DEBUG2_FIELDNUM                           1u
#define DV1_DGL_DEBUG2_DEFAULTVAL                         0x0u
#define DV1_SW_SRAM_MODE16                                0x4A46059Cu
#define DV1_SW_SRAM_MODE16_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE16_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE17                                0x4A4605A0u
#define DV1_SW_SRAM_MODE17_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE17_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE18                                0x4A4605A4u
#define DV1_SW_SRAM_MODE18_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE18_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE19                                0x4A4605A8u
#define DV1_SW_SRAM_MODE19_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE19_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE20                                0x4A4605ACu
#define DV1_SW_SRAM_MODE20_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE20_DEFAULTVAL                     0x0u
#define DV1_SW_SRAM_MODE21                                0x4A4605B0u
#define DV1_SW_SRAM_MODE21_FIELDNUM                       2u
#define DV1_SW_SRAM_MODE21_DEFAULTVAL                     0x15u
#define DV1_PB_TOKEN_CTRL                                 0x4A4605B4u
#define DV1_PB_TOKEN_CTRL_FIELDNUM                        2u
#define DV1_PB_TOKEN_CTRL_DEFAULTVAL                      0x0u
#define DV1_DFT_PROTECTION_DFF_1                          0x4A4605B8u
#define DV1_DFT_PROTECTION_DFF_1_FIELDNUM                 1u
#define DV1_DFT_PROTECTION_DFF_1_DEFAULTVAL               0x0u
#endif
#endif /* DV1_RTKAS_REG_LIST_FILE_HW_MISC_H_ */