/*
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * Copyright (c) 2024, Realtek Semiconductor Corp. All rights reserved.
 *
 * This software is a confidential and proprietary property of Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in
 * whole or in part, of this work and its derivatives without express
 * permission is prohibited.
 *
 * Realtek Semiconductor Corp. reserves the right to update, modify, or
 * discontinue this software at any time without notice. This software is
 * provided "as is" and any express or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for
 * a particular purpose are disclaimed. In no event shall Realtek
 * Semiconductor Corp. be liable for any direct, indirect, incidental,
 * special, exemplary, or consequential damages (including, but not limited
 * to, procurement of substitute goods or services; loss of use, data, or
 * profits; or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort (including
 * negligence or otherwise) arising in any way out of the use of this software,
 * even if advised of the possibility of such damage.
 */

#ifndef DV1_RTKAS_REG_LIST_FILE_FLOW_CONTROL_DIAG_H_
#define DV1_RTKAS_REG_LIST_FILE_FLOW_CONTROL_DIAG_H_

#ifdef DV1_FILE_FLOW_CONTROL_DIAG
/* File: Flow Control Diagnostic */
#define DV1_FLOWCTL_GLOBAL_PAGECNT_BEYOND_THRESHOLD_TIMES                     0x4A6C0000u
#define DV1_FLOWCTL_GLOBAL_PAGECNT_BEYOND_THRESHOLD_TIMES_FIELDNUM            2u
#define DV1_FLOWCTL_GLOBAL_PAGECNT_BEYOND_THRESHOLD_TIMES_DEFAULTVAL          0x0u
#define DV1_GLOBAL_OCCUPIED_RX_PAGE_PEAK_COUNTER                              0x4A6C0004u
#define DV1_GLOBAL_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                     2u
#define DV1_GLOBAL_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                   0x0u
#define DV1_SYSTEM_PAGE_COUNTER                                               0x4A6C0008u
#define DV1_SYSTEM_PAGE_COUNTER_FIELDNUM                                      2u
#define DV1_SYSTEM_PAGE_COUNTER_DEFAULTVAL                                    0x0u
#define DV1_DEBUG_COUNTER_RESET                                               0x4A6C000Cu
#define DV1_DEBUG_COUNTER_RESET_FIELDNUM                                      3u
#define DV1_DEBUG_COUNTER_RESET_DEFAULTVAL                                    0x0u
#define DV1_SYSTEM_PAGE_COUNTER_REAL                                          0x4A6C0010u
#define DV1_SYSTEM_PAGE_COUNTER_REAL_FIELDNUM                                 2u
#define DV1_SYSTEM_PAGE_COUNTER_REAL_DEFAULTVAL                               0x0u
#define DV1_SYSTEM_PAGE_COUNTER_REAL_PEAK                                     0x4A6C0014u
#define DV1_SYSTEM_PAGE_COUNTER_REAL_PEAK_FIELDNUM                            2u
#define DV1_SYSTEM_PAGE_COUNTER_REAL_PEAK_DEFAULTVAL                          0x0u
#define DV1_SYSTEM_TOTAL_GRANT_PAGE_COUNTER                                   0x4A6C0018u
#define DV1_SYSTEM_TOTAL_GRANT_PAGE_COUNTER_FIELDNUM                          2u
#define DV1_SYSTEM_TOTAL_GRANT_PAGE_COUNTER_DEFAULTVAL                        0x0u
#define DV1_SYSTEM_TOTAL_GRANT_PAGE_PEAK_COUNTER                              0x4A6C001Cu
#define DV1_SYSTEM_TOTAL_GRANT_PAGE_PEAK_COUNTER_FIELDNUM                     2u
#define DV1_SYSTEM_TOTAL_GRANT_PAGE_PEAK_COUNTER_DEFAULTVAL                   0x0u
#define DV1_PORT0_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES             0x4AEC0000u
#define DV1_PORT0_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM    2u
#define DV1_PORT0_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL  0x0u
#define DV1_PORT1_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES             0x4AEC0800u
#define DV1_PORT1_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM    2u
#define DV1_PORT1_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL  0x0u
#define DV1_PORT2_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES             0x4AEC1000u
#define DV1_PORT2_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM    2u
#define DV1_PORT2_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL  0x0u
#define DV1_PORT3_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES             0x4AEC1800u
#define DV1_PORT3_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM    2u
#define DV1_PORT3_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL  0x0u
#define DV1_PORT4_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES             0x4AEC2000u
#define DV1_PORT4_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM    2u
#define DV1_PORT4_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL  0x0u
#define DV1_PORT5_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES             0x4AEC2800u
#define DV1_PORT5_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM    2u
#define DV1_PORT5_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL  0x0u
#define DV1_PORT6_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES             0x4AEC3000u
#define DV1_PORT6_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM    2u
#define DV1_PORT6_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL  0x0u
#define DV1_PORT7_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES             0x4AEC3800u
#define DV1_PORT7_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM    2u
#define DV1_PORT7_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL  0x0u
#define DV1_PORT8_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES             0x4AEC4000u
#define DV1_PORT8_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM    2u
#define DV1_PORT8_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL  0x0u
#define DV1_PORT9_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES             0x4AEC4800u
#define DV1_PORT9_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM    2u
#define DV1_PORT9_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL  0x0u
#define DV1_PORT10_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES            0x4AEC5000u
#define DV1_PORT10_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM   2u
#define DV1_PORT10_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL 0x0u
#define DV1_PORT11_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES            0x4AEC5800u
#define DV1_PORT11_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM   2u
#define DV1_PORT11_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL 0x0u
#define DV1_PORT12_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES            0x4AEC6000u
#define DV1_PORT12_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM   2u
#define DV1_PORT12_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL 0x0u
#define DV1_PORT13_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES            0x4AEC6800u
#define DV1_PORT13_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM   2u
#define DV1_PORT13_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL 0x0u
#define DV1_PORT14_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES            0x4AEC7000u
#define DV1_PORT14_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM   2u
#define DV1_PORT14_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL 0x0u
#define DV1_PORT15_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES            0x4AEC7800u
#define DV1_PORT15_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_FIELDNUM   2u
#define DV1_PORT15_RX_OCCUPIED_PAGE_COUNTER_BEYOND_THRESHOLD_TIMES_DEFAULTVAL 0x0u
#define DV1_PORT0_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE                0x4AEC0004u
#define DV1_PORT0_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM       2u
#define DV1_PORT0_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL     0x0u
#define DV1_PORT1_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE                0x4AEC0804u
#define DV1_PORT1_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM       2u
#define DV1_PORT1_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL     0x0u
#define DV1_PORT2_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE                0x4AEC1004u
#define DV1_PORT2_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM       2u
#define DV1_PORT2_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL     0x0u
#define DV1_PORT3_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE                0x4AEC1804u
#define DV1_PORT3_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM       2u
#define DV1_PORT3_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL     0x0u
#define DV1_PORT4_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE                0x4AEC2004u
#define DV1_PORT4_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM       2u
#define DV1_PORT4_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL     0x0u
#define DV1_PORT5_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE                0x4AEC2804u
#define DV1_PORT5_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM       2u
#define DV1_PORT5_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL     0x0u
#define DV1_PORT6_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE                0x4AEC3004u
#define DV1_PORT6_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM       2u
#define DV1_PORT6_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL     0x0u
#define DV1_PORT7_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE                0x4AEC3804u
#define DV1_PORT7_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM       2u
#define DV1_PORT7_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL     0x0u
#define DV1_PORT8_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE                0x4AEC4004u
#define DV1_PORT8_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM       2u
#define DV1_PORT8_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL     0x0u
#define DV1_PORT9_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE                0x4AEC4804u
#define DV1_PORT9_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM       2u
#define DV1_PORT9_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL     0x0u
#define DV1_PORT10_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE               0x4AEC5004u
#define DV1_PORT10_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM      2u
#define DV1_PORT10_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL    0x0u
#define DV1_PORT11_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE               0x4AEC5804u
#define DV1_PORT11_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM      2u
#define DV1_PORT11_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL    0x0u
#define DV1_PORT12_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE               0x4AEC6004u
#define DV1_PORT12_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM      2u
#define DV1_PORT12_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL    0x0u
#define DV1_PORT13_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE               0x4AEC6804u
#define DV1_PORT13_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM      2u
#define DV1_PORT13_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL    0x0u
#define DV1_PORT14_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE               0x4AEC7004u
#define DV1_PORT14_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM      2u
#define DV1_PORT14_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL    0x0u
#define DV1_PORT15_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE               0x4AEC7804u
#define DV1_PORT15_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_FIELDNUM      2u
#define DV1_PORT15_CURRENT_COUNTER_WHEN_GLOBAL_REACH_PEAK_VALUE_DEFAULTVAL    0x0u
#define DV1_PORT0_OCCUPIED_RX_PAGE_PEAK_COUNTER                               0x4AEC0008u
#define DV1_PORT0_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                      4u
#define DV1_PORT0_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                    0x0u
#define DV1_PORT1_OCCUPIED_RX_PAGE_PEAK_COUNTER                               0x4AEC0808u
#define DV1_PORT1_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                      4u
#define DV1_PORT1_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                    0x0u
#define DV1_PORT2_OCCUPIED_RX_PAGE_PEAK_COUNTER                               0x4AEC1008u
#define DV1_PORT2_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                      4u
#define DV1_PORT2_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                    0x0u
#define DV1_PORT3_OCCUPIED_RX_PAGE_PEAK_COUNTER                               0x4AEC1808u
#define DV1_PORT3_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                      4u
#define DV1_PORT3_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                    0x0u
#define DV1_PORT4_OCCUPIED_RX_PAGE_PEAK_COUNTER                               0x4AEC2008u
#define DV1_PORT4_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                      4u
#define DV1_PORT4_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                    0x0u
#define DV1_PORT5_OCCUPIED_RX_PAGE_PEAK_COUNTER                               0x4AEC2808u
#define DV1_PORT5_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                      4u
#define DV1_PORT5_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                    0x0u
#define DV1_PORT6_OCCUPIED_RX_PAGE_PEAK_COUNTER                               0x4AEC3008u
#define DV1_PORT6_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                      4u
#define DV1_PORT6_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                    0x0u
#define DV1_PORT7_OCCUPIED_RX_PAGE_PEAK_COUNTER                               0x4AEC3808u
#define DV1_PORT7_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                      4u
#define DV1_PORT7_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                    0x0u
#define DV1_PORT8_OCCUPIED_RX_PAGE_PEAK_COUNTER                               0x4AEC4008u
#define DV1_PORT8_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                      4u
#define DV1_PORT8_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                    0x0u
#define DV1_PORT9_OCCUPIED_RX_PAGE_PEAK_COUNTER                               0x4AEC4808u
#define DV1_PORT9_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                      4u
#define DV1_PORT9_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                    0x0u
#define DV1_PORT10_OCCUPIED_RX_PAGE_PEAK_COUNTER                              0x4AEC5008u
#define DV1_PORT10_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                     4u
#define DV1_PORT10_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                   0x0u
#define DV1_PORT11_OCCUPIED_RX_PAGE_PEAK_COUNTER                              0x4AEC5808u
#define DV1_PORT11_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                     4u
#define DV1_PORT11_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                   0x0u
#define DV1_PORT12_OCCUPIED_RX_PAGE_PEAK_COUNTER                              0x4AEC6008u
#define DV1_PORT12_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                     4u
#define DV1_PORT12_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                   0x0u
#define DV1_PORT13_OCCUPIED_RX_PAGE_PEAK_COUNTER                              0x4AEC6808u
#define DV1_PORT13_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                     4u
#define DV1_PORT13_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                   0x0u
#define DV1_PORT14_OCCUPIED_RX_PAGE_PEAK_COUNTER                              0x4AEC7008u
#define DV1_PORT14_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                     4u
#define DV1_PORT14_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                   0x0u
#define DV1_PORT15_OCCUPIED_RX_PAGE_PEAK_COUNTER                              0x4AEC7808u
#define DV1_PORT15_OCCUPIED_RX_PAGE_PEAK_COUNTER_FIELDNUM                     4u
#define DV1_PORT15_OCCUPIED_RX_PAGE_PEAK_COUNTER_DEFAULTVAL                   0x0u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER0                                  0x4AEC000Cu
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                         6u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                       0x0u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER0                                  0x4AEC080Cu
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                         6u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                       0x0u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER0                                  0x4AEC100Cu
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                         6u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                       0x0u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER0                                  0x4AEC180Cu
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                         6u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                       0x0u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER0                                  0x4AEC200Cu
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                         6u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                       0x0u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER0                                  0x4AEC280Cu
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                         6u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                       0x0u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER0                                  0x4AEC300Cu
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                         6u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                       0x0u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER0                                  0x4AEC380Cu
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                         6u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                       0x0u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER0                                  0x4AEC400Cu
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                         6u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                       0x0u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER0                                  0x4AEC480Cu
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                         6u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                       0x0u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER0                                 0x4AEC500Cu
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                        6u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                      0x0u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER0                                 0x4AEC580Cu
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                        6u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                      0x0u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER0                                 0x4AEC600Cu
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                        6u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                      0x0u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER0                                 0x4AEC680Cu
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                        6u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                      0x0u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER0                                 0x4AEC700Cu
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                        6u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                      0x0u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER0                                 0x4AEC780Cu
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER0_FIELDNUM                        6u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER0_DEFAULTVAL                      0x0u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER1                                  0x4AEC0010u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                         6u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                       0x0u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER1                                  0x4AEC0810u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                         6u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                       0x0u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER1                                  0x4AEC1010u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                         6u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                       0x0u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER1                                  0x4AEC1810u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                         6u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                       0x0u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER1                                  0x4AEC2010u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                         6u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                       0x0u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER1                                  0x4AEC2810u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                         6u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                       0x0u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER1                                  0x4AEC3010u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                         6u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                       0x0u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER1                                  0x4AEC3810u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                         6u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                       0x0u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER1                                  0x4AEC4010u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                         6u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                       0x0u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER1                                  0x4AEC4810u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                         6u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                       0x0u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER1                                 0x4AEC5010u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                        6u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                      0x0u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER1                                 0x4AEC5810u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                        6u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                      0x0u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER1                                 0x4AEC6010u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                        6u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                      0x0u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER1                                 0x4AEC6810u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                        6u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                      0x0u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER1                                 0x4AEC7010u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                        6u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                      0x0u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER1                                 0x4AEC7810u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER1_FIELDNUM                        6u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER1_DEFAULTVAL                      0x0u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER2                                  0x4AEC0014u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                         6u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                       0x0u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER2                                  0x4AEC0814u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                         6u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                       0x0u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER2                                  0x4AEC1014u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                         6u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                       0x0u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER2                                  0x4AEC1814u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                         6u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                       0x0u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER2                                  0x4AEC2014u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                         6u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                       0x0u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER2                                  0x4AEC2814u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                         6u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                       0x0u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER2                                  0x4AEC3014u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                         6u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                       0x0u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER2                                  0x4AEC3814u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                         6u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                       0x0u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER2                                  0x4AEC4014u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                         6u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                       0x0u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER2                                  0x4AEC4814u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                         6u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                       0x0u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER2                                 0x4AEC5014u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                        6u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                      0x0u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER2                                 0x4AEC5814u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                        6u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                      0x0u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER2                                 0x4AEC6014u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                        6u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                      0x0u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER2                                 0x4AEC6814u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                        6u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                      0x0u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER2                                 0x4AEC7014u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                        6u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                      0x0u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER2                                 0x4AEC7814u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER2_FIELDNUM                        6u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER2_DEFAULTVAL                      0x0u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER3                                  0x4AEC0018u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                         6u
#define DV1_PORT0_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                       0x0u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER3                                  0x4AEC0818u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                         6u
#define DV1_PORT1_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                       0x0u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER3                                  0x4AEC1018u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                         6u
#define DV1_PORT2_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                       0x0u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER3                                  0x4AEC1818u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                         6u
#define DV1_PORT3_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                       0x0u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER3                                  0x4AEC2018u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                         6u
#define DV1_PORT4_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                       0x0u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER3                                  0x4AEC2818u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                         6u
#define DV1_PORT5_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                       0x0u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER3                                  0x4AEC3018u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                         6u
#define DV1_PORT6_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                       0x0u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER3                                  0x4AEC3818u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                         6u
#define DV1_PORT7_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                       0x0u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER3                                  0x4AEC4018u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                         6u
#define DV1_PORT8_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                       0x0u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER3                                  0x4AEC4818u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                         6u
#define DV1_PORT9_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                       0x0u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER3                                 0x4AEC5018u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                        6u
#define DV1_PORT10_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                      0x0u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER3                                 0x4AEC5818u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                        6u
#define DV1_PORT11_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                      0x0u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER3                                 0x4AEC6018u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                        6u
#define DV1_PORT12_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                      0x0u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER3                                 0x4AEC6818u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                        6u
#define DV1_PORT13_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                      0x0u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER3                                 0x4AEC7018u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                        6u
#define DV1_PORT14_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                      0x0u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER3                                 0x4AEC7818u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER3_FIELDNUM                        6u
#define DV1_PORT15_OCCUPIED_TX_QUEUE_COUNTER3_DEFAULTVAL                      0x0u
#define DV1_PORT0_CURRENT_COUNTER                                             0x4AEC001Cu
#define DV1_PORT0_CURRENT_COUNTER_FIELDNUM                                    2u
#define DV1_PORT0_CURRENT_COUNTER_DEFAULTVAL                                  0x0u
#define DV1_PORT1_CURRENT_COUNTER                                             0x4AEC081Cu
#define DV1_PORT1_CURRENT_COUNTER_FIELDNUM                                    2u
#define DV1_PORT1_CURRENT_COUNTER_DEFAULTVAL                                  0x0u
#define DV1_PORT2_CURRENT_COUNTER                                             0x4AEC101Cu
#define DV1_PORT2_CURRENT_COUNTER_FIELDNUM                                    2u
#define DV1_PORT2_CURRENT_COUNTER_DEFAULTVAL                                  0x0u
#define DV1_PORT3_CURRENT_COUNTER                                             0x4AEC181Cu
#define DV1_PORT3_CURRENT_COUNTER_FIELDNUM                                    2u
#define DV1_PORT3_CURRENT_COUNTER_DEFAULTVAL                                  0x0u
#define DV1_PORT4_CURRENT_COUNTER                                             0x4AEC201Cu
#define DV1_PORT4_CURRENT_COUNTER_FIELDNUM                                    2u
#define DV1_PORT4_CURRENT_COUNTER_DEFAULTVAL                                  0x0u
#define DV1_PORT5_CURRENT_COUNTER                                             0x4AEC281Cu
#define DV1_PORT5_CURRENT_COUNTER_FIELDNUM                                    2u
#define DV1_PORT5_CURRENT_COUNTER_DEFAULTVAL                                  0x0u
#define DV1_PORT6_CURRENT_COUNTER                                             0x4AEC301Cu
#define DV1_PORT6_CURRENT_COUNTER_FIELDNUM                                    2u
#define DV1_PORT6_CURRENT_COUNTER_DEFAULTVAL                                  0x0u
#define DV1_PORT7_CURRENT_COUNTER                                             0x4AEC381Cu
#define DV1_PORT7_CURRENT_COUNTER_FIELDNUM                                    2u
#define DV1_PORT7_CURRENT_COUNTER_DEFAULTVAL                                  0x0u
#define DV1_PORT8_CURRENT_COUNTER                                             0x4AEC401Cu
#define DV1_PORT8_CURRENT_COUNTER_FIELDNUM                                    2u
#define DV1_PORT8_CURRENT_COUNTER_DEFAULTVAL                                  0x0u
#define DV1_PORT9_CURRENT_COUNTER                                             0x4AEC481Cu
#define DV1_PORT9_CURRENT_COUNTER_FIELDNUM                                    2u
#define DV1_PORT9_CURRENT_COUNTER_DEFAULTVAL                                  0x0u
#define DV1_PORT10_CURRENT_COUNTER                                            0x4AEC501Cu
#define DV1_PORT10_CURRENT_COUNTER_FIELDNUM                                   2u
#define DV1_PORT10_CURRENT_COUNTER_DEFAULTVAL                                 0x0u
#define DV1_PORT11_CURRENT_COUNTER                                            0x4AEC581Cu
#define DV1_PORT11_CURRENT_COUNTER_FIELDNUM                                   2u
#define DV1_PORT11_CURRENT_COUNTER_DEFAULTVAL                                 0x0u
#define DV1_PORT12_CURRENT_COUNTER                                            0x4AEC601Cu
#define DV1_PORT12_CURRENT_COUNTER_FIELDNUM                                   2u
#define DV1_PORT12_CURRENT_COUNTER_DEFAULTVAL                                 0x0u
#define DV1_PORT13_CURRENT_COUNTER                                            0x4AEC681Cu
#define DV1_PORT13_CURRENT_COUNTER_FIELDNUM                                   2u
#define DV1_PORT13_CURRENT_COUNTER_DEFAULTVAL                                 0x0u
#define DV1_PORT14_CURRENT_COUNTER                                            0x4AEC701Cu
#define DV1_PORT14_CURRENT_COUNTER_FIELDNUM                                   2u
#define DV1_PORT14_CURRENT_COUNTER_DEFAULTVAL                                 0x0u
#define DV1_PORT15_CURRENT_COUNTER                                            0x4AEC781Cu
#define DV1_PORT15_CURRENT_COUNTER_FIELDNUM                                   2u
#define DV1_PORT15_CURRENT_COUNTER_DEFAULTVAL                                 0x0u
#define DV1_PORT0_CURRENT_COUNTER_REAL                                        0x4AEC0020u
#define DV1_PORT0_CURRENT_COUNTER_REAL_FIELDNUM                               2u
#define DV1_PORT0_CURRENT_COUNTER_REAL_DEFAULTVAL                             0x0u
#define DV1_PORT1_CURRENT_COUNTER_REAL                                        0x4AEC0820u
#define DV1_PORT1_CURRENT_COUNTER_REAL_FIELDNUM                               2u
#define DV1_PORT1_CURRENT_COUNTER_REAL_DEFAULTVAL                             0x0u
#define DV1_PORT2_CURRENT_COUNTER_REAL                                        0x4AEC1020u
#define DV1_PORT2_CURRENT_COUNTER_REAL_FIELDNUM                               2u
#define DV1_PORT2_CURRENT_COUNTER_REAL_DEFAULTVAL                             0x0u
#define DV1_PORT3_CURRENT_COUNTER_REAL                                        0x4AEC1820u
#define DV1_PORT3_CURRENT_COUNTER_REAL_FIELDNUM                               2u
#define DV1_PORT3_CURRENT_COUNTER_REAL_DEFAULTVAL                             0x0u
#define DV1_PORT4_CURRENT_COUNTER_REAL                                        0x4AEC2020u
#define DV1_PORT4_CURRENT_COUNTER_REAL_FIELDNUM                               2u
#define DV1_PORT4_CURRENT_COUNTER_REAL_DEFAULTVAL                             0x0u
#define DV1_PORT5_CURRENT_COUNTER_REAL                                        0x4AEC2820u
#define DV1_PORT5_CURRENT_COUNTER_REAL_FIELDNUM                               2u
#define DV1_PORT5_CURRENT_COUNTER_REAL_DEFAULTVAL                             0x0u
#define DV1_PORT6_CURRENT_COUNTER_REAL                                        0x4AEC3020u
#define DV1_PORT6_CURRENT_COUNTER_REAL_FIELDNUM                               2u
#define DV1_PORT6_CURRENT_COUNTER_REAL_DEFAULTVAL                             0x0u
#define DV1_PORT7_CURRENT_COUNTER_REAL                                        0x4AEC3820u
#define DV1_PORT7_CURRENT_COUNTER_REAL_FIELDNUM                               2u
#define DV1_PORT7_CURRENT_COUNTER_REAL_DEFAULTVAL                             0x0u
#define DV1_PORT8_CURRENT_COUNTER_REAL                                        0x4AEC4020u
#define DV1_PORT8_CURRENT_COUNTER_REAL_FIELDNUM                               2u
#define DV1_PORT8_CURRENT_COUNTER_REAL_DEFAULTVAL                             0x0u
#define DV1_PORT9_CURRENT_COUNTER_REAL                                        0x4AEC4820u
#define DV1_PORT9_CURRENT_COUNTER_REAL_FIELDNUM                               2u
#define DV1_PORT9_CURRENT_COUNTER_REAL_DEFAULTVAL                             0x0u
#define DV1_PORT10_CURRENT_COUNTER_REAL                                       0x4AEC5020u
#define DV1_PORT10_CURRENT_COUNTER_REAL_FIELDNUM                              2u
#define DV1_PORT10_CURRENT_COUNTER_REAL_DEFAULTVAL                            0x0u
#define DV1_PORT11_CURRENT_COUNTER_REAL                                       0x4AEC5820u
#define DV1_PORT11_CURRENT_COUNTER_REAL_FIELDNUM                              2u
#define DV1_PORT11_CURRENT_COUNTER_REAL_DEFAULTVAL                            0x0u
#define DV1_PORT12_CURRENT_COUNTER_REAL                                       0x4AEC6020u
#define DV1_PORT12_CURRENT_COUNTER_REAL_FIELDNUM                              2u
#define DV1_PORT12_CURRENT_COUNTER_REAL_DEFAULTVAL                            0x0u
#define DV1_PORT13_CURRENT_COUNTER_REAL                                       0x4AEC6820u
#define DV1_PORT13_CURRENT_COUNTER_REAL_FIELDNUM                              2u
#define DV1_PORT13_CURRENT_COUNTER_REAL_DEFAULTVAL                            0x0u
#define DV1_PORT14_CURRENT_COUNTER_REAL                                       0x4AEC7020u
#define DV1_PORT14_CURRENT_COUNTER_REAL_FIELDNUM                              2u
#define DV1_PORT14_CURRENT_COUNTER_REAL_DEFAULTVAL                            0x0u
#define DV1_PORT15_CURRENT_COUNTER_REAL                                       0x4AEC7820u
#define DV1_PORT15_CURRENT_COUNTER_REAL_FIELDNUM                              2u
#define DV1_PORT15_CURRENT_COUNTER_REAL_DEFAULTVAL                            0x0u
#define DV1_PORT0_CURRENT_COUNTER_REAL_PEAK                                   0x4AEC0024u
#define DV1_PORT0_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                          2u
#define DV1_PORT0_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                        0x0u
#define DV1_PORT1_CURRENT_COUNTER_REAL_PEAK                                   0x4AEC0824u
#define DV1_PORT1_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                          2u
#define DV1_PORT1_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                        0x0u
#define DV1_PORT2_CURRENT_COUNTER_REAL_PEAK                                   0x4AEC1024u
#define DV1_PORT2_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                          2u
#define DV1_PORT2_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                        0x0u
#define DV1_PORT3_CURRENT_COUNTER_REAL_PEAK                                   0x4AEC1824u
#define DV1_PORT3_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                          2u
#define DV1_PORT3_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                        0x0u
#define DV1_PORT4_CURRENT_COUNTER_REAL_PEAK                                   0x4AEC2024u
#define DV1_PORT4_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                          2u
#define DV1_PORT4_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                        0x0u
#define DV1_PORT5_CURRENT_COUNTER_REAL_PEAK                                   0x4AEC2824u
#define DV1_PORT5_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                          2u
#define DV1_PORT5_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                        0x0u
#define DV1_PORT6_CURRENT_COUNTER_REAL_PEAK                                   0x4AEC3024u
#define DV1_PORT6_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                          2u
#define DV1_PORT6_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                        0x0u
#define DV1_PORT7_CURRENT_COUNTER_REAL_PEAK                                   0x4AEC3824u
#define DV1_PORT7_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                          2u
#define DV1_PORT7_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                        0x0u
#define DV1_PORT8_CURRENT_COUNTER_REAL_PEAK                                   0x4AEC4024u
#define DV1_PORT8_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                          2u
#define DV1_PORT8_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                        0x0u
#define DV1_PORT9_CURRENT_COUNTER_REAL_PEAK                                   0x4AEC4824u
#define DV1_PORT9_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                          2u
#define DV1_PORT9_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                        0x0u
#define DV1_PORT10_CURRENT_COUNTER_REAL_PEAK                                  0x4AEC5024u
#define DV1_PORT10_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                         2u
#define DV1_PORT10_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT11_CURRENT_COUNTER_REAL_PEAK                                  0x4AEC5824u
#define DV1_PORT11_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                         2u
#define DV1_PORT11_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT12_CURRENT_COUNTER_REAL_PEAK                                  0x4AEC6024u
#define DV1_PORT12_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                         2u
#define DV1_PORT12_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT13_CURRENT_COUNTER_REAL_PEAK                                  0x4AEC6824u
#define DV1_PORT13_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                         2u
#define DV1_PORT13_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT14_CURRENT_COUNTER_REAL_PEAK                                  0x4AEC7024u
#define DV1_PORT14_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                         2u
#define DV1_PORT14_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT15_CURRENT_COUNTER_REAL_PEAK                                  0x4AEC7824u
#define DV1_PORT15_CURRENT_COUNTER_REAL_PEAK_FIELDNUM                         2u
#define DV1_PORT15_CURRENT_COUNTER_REAL_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT0_CURRENT_GRANT_COUNTER                                       0x4AEC0028u
#define DV1_PORT0_CURRENT_GRANT_COUNTER_FIELDNUM                              2u
#define DV1_PORT0_CURRENT_GRANT_COUNTER_DEFAULTVAL                            0x0u
#define DV1_PORT1_CURRENT_GRANT_COUNTER                                       0x4AEC0828u
#define DV1_PORT1_CURRENT_GRANT_COUNTER_FIELDNUM                              2u
#define DV1_PORT1_CURRENT_GRANT_COUNTER_DEFAULTVAL                            0x0u
#define DV1_PORT2_CURRENT_GRANT_COUNTER                                       0x4AEC1028u
#define DV1_PORT2_CURRENT_GRANT_COUNTER_FIELDNUM                              2u
#define DV1_PORT2_CURRENT_GRANT_COUNTER_DEFAULTVAL                            0x0u
#define DV1_PORT3_CURRENT_GRANT_COUNTER                                       0x4AEC1828u
#define DV1_PORT3_CURRENT_GRANT_COUNTER_FIELDNUM                              2u
#define DV1_PORT3_CURRENT_GRANT_COUNTER_DEFAULTVAL                            0x0u
#define DV1_PORT4_CURRENT_GRANT_COUNTER                                       0x4AEC2028u
#define DV1_PORT4_CURRENT_GRANT_COUNTER_FIELDNUM                              2u
#define DV1_PORT4_CURRENT_GRANT_COUNTER_DEFAULTVAL                            0x0u
#define DV1_PORT5_CURRENT_GRANT_COUNTER                                       0x4AEC2828u
#define DV1_PORT5_CURRENT_GRANT_COUNTER_FIELDNUM                              2u
#define DV1_PORT5_CURRENT_GRANT_COUNTER_DEFAULTVAL                            0x0u
#define DV1_PORT6_CURRENT_GRANT_COUNTER                                       0x4AEC3028u
#define DV1_PORT6_CURRENT_GRANT_COUNTER_FIELDNUM                              2u
#define DV1_PORT6_CURRENT_GRANT_COUNTER_DEFAULTVAL                            0x0u
#define DV1_PORT7_CURRENT_GRANT_COUNTER                                       0x4AEC3828u
#define DV1_PORT7_CURRENT_GRANT_COUNTER_FIELDNUM                              2u
#define DV1_PORT7_CURRENT_GRANT_COUNTER_DEFAULTVAL                            0x0u
#define DV1_PORT8_CURRENT_GRANT_COUNTER                                       0x4AEC4028u
#define DV1_PORT8_CURRENT_GRANT_COUNTER_FIELDNUM                              2u
#define DV1_PORT8_CURRENT_GRANT_COUNTER_DEFAULTVAL                            0x0u
#define DV1_PORT9_CURRENT_GRANT_COUNTER                                       0x4AEC4828u
#define DV1_PORT9_CURRENT_GRANT_COUNTER_FIELDNUM                              2u
#define DV1_PORT9_CURRENT_GRANT_COUNTER_DEFAULTVAL                            0x0u
#define DV1_PORT10_CURRENT_GRANT_COUNTER                                      0x4AEC5028u
#define DV1_PORT10_CURRENT_GRANT_COUNTER_FIELDNUM                             2u
#define DV1_PORT10_CURRENT_GRANT_COUNTER_DEFAULTVAL                           0x0u
#define DV1_PORT11_CURRENT_GRANT_COUNTER                                      0x4AEC5828u
#define DV1_PORT11_CURRENT_GRANT_COUNTER_FIELDNUM                             2u
#define DV1_PORT11_CURRENT_GRANT_COUNTER_DEFAULTVAL                           0x0u
#define DV1_PORT12_CURRENT_GRANT_COUNTER                                      0x4AEC6028u
#define DV1_PORT12_CURRENT_GRANT_COUNTER_FIELDNUM                             2u
#define DV1_PORT12_CURRENT_GRANT_COUNTER_DEFAULTVAL                           0x0u
#define DV1_PORT13_CURRENT_GRANT_COUNTER                                      0x4AEC6828u
#define DV1_PORT13_CURRENT_GRANT_COUNTER_FIELDNUM                             2u
#define DV1_PORT13_CURRENT_GRANT_COUNTER_DEFAULTVAL                           0x0u
#define DV1_PORT14_CURRENT_GRANT_COUNTER                                      0x4AEC7028u
#define DV1_PORT14_CURRENT_GRANT_COUNTER_FIELDNUM                             2u
#define DV1_PORT14_CURRENT_GRANT_COUNTER_DEFAULTVAL                           0x0u
#define DV1_PORT15_CURRENT_GRANT_COUNTER                                      0x4AEC7828u
#define DV1_PORT15_CURRENT_GRANT_COUNTER_FIELDNUM                             2u
#define DV1_PORT15_CURRENT_GRANT_COUNTER_DEFAULTVAL                           0x0u
#define DV1_PORT0_CURRENT_GRANT_COUNTER_PEAK                                  0x4AEC002Cu
#define DV1_PORT0_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                         2u
#define DV1_PORT0_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT1_CURRENT_GRANT_COUNTER_PEAK                                  0x4AEC082Cu
#define DV1_PORT1_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                         2u
#define DV1_PORT1_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT2_CURRENT_GRANT_COUNTER_PEAK                                  0x4AEC102Cu
#define DV1_PORT2_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                         2u
#define DV1_PORT2_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT3_CURRENT_GRANT_COUNTER_PEAK                                  0x4AEC182Cu
#define DV1_PORT3_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                         2u
#define DV1_PORT3_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT4_CURRENT_GRANT_COUNTER_PEAK                                  0x4AEC202Cu
#define DV1_PORT4_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                         2u
#define DV1_PORT4_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT5_CURRENT_GRANT_COUNTER_PEAK                                  0x4AEC282Cu
#define DV1_PORT5_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                         2u
#define DV1_PORT5_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT6_CURRENT_GRANT_COUNTER_PEAK                                  0x4AEC302Cu
#define DV1_PORT6_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                         2u
#define DV1_PORT6_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT7_CURRENT_GRANT_COUNTER_PEAK                                  0x4AEC382Cu
#define DV1_PORT7_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                         2u
#define DV1_PORT7_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT8_CURRENT_GRANT_COUNTER_PEAK                                  0x4AEC402Cu
#define DV1_PORT8_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                         2u
#define DV1_PORT8_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT9_CURRENT_GRANT_COUNTER_PEAK                                  0x4AEC482Cu
#define DV1_PORT9_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                         2u
#define DV1_PORT9_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                       0x0u
#define DV1_PORT10_CURRENT_GRANT_COUNTER_PEAK                                 0x4AEC502Cu
#define DV1_PORT10_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                        2u
#define DV1_PORT10_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                      0x0u
#define DV1_PORT11_CURRENT_GRANT_COUNTER_PEAK                                 0x4AEC582Cu
#define DV1_PORT11_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                        2u
#define DV1_PORT11_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                      0x0u
#define DV1_PORT12_CURRENT_GRANT_COUNTER_PEAK                                 0x4AEC602Cu
#define DV1_PORT12_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                        2u
#define DV1_PORT12_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                      0x0u
#define DV1_PORT13_CURRENT_GRANT_COUNTER_PEAK                                 0x4AEC682Cu
#define DV1_PORT13_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                        2u
#define DV1_PORT13_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                      0x0u
#define DV1_PORT14_CURRENT_GRANT_COUNTER_PEAK                                 0x4AEC702Cu
#define DV1_PORT14_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                        2u
#define DV1_PORT14_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                      0x0u
#define DV1_PORT15_CURRENT_GRANT_COUNTER_PEAK                                 0x4AEC782Cu
#define DV1_PORT15_CURRENT_GRANT_COUNTER_PEAK_FIELDNUM                        2u
#define DV1_PORT15_CURRENT_GRANT_COUNTER_PEAK_DEFAULTVAL                      0x0u
#define DV1_PORT0_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                        0x4AEC0030u
#define DV1_PORT0_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM               2u
#define DV1_PORT0_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL             0x0u
#define DV1_PORT1_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                        0x4AEC0830u
#define DV1_PORT1_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM               2u
#define DV1_PORT1_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL             0x0u
#define DV1_PORT2_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                        0x4AEC1030u
#define DV1_PORT2_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM               2u
#define DV1_PORT2_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL             0x0u
#define DV1_PORT3_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                        0x4AEC1830u
#define DV1_PORT3_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM               2u
#define DV1_PORT3_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL             0x0u
#define DV1_PORT4_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                        0x4AEC2030u
#define DV1_PORT4_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM               2u
#define DV1_PORT4_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL             0x0u
#define DV1_PORT5_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                        0x4AEC2830u
#define DV1_PORT5_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM               2u
#define DV1_PORT5_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL             0x0u
#define DV1_PORT6_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                        0x4AEC3030u
#define DV1_PORT6_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM               2u
#define DV1_PORT6_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL             0x0u
#define DV1_PORT7_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                        0x4AEC3830u
#define DV1_PORT7_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM               2u
#define DV1_PORT7_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL             0x0u
#define DV1_PORT8_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                        0x4AEC4030u
#define DV1_PORT8_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM               2u
#define DV1_PORT8_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL             0x0u
#define DV1_PORT9_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                        0x4AEC4830u
#define DV1_PORT9_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM               2u
#define DV1_PORT9_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL             0x0u
#define DV1_PORT10_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                       0x4AEC5030u
#define DV1_PORT10_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT10_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT11_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                       0x4AEC5830u
#define DV1_PORT11_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT11_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT12_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                       0x4AEC6030u
#define DV1_PORT12_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT12_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT13_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                       0x4AEC6830u
#define DV1_PORT13_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT13_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT14_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                       0x4AEC7030u
#define DV1_PORT14_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT14_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT15_FLOW_CONTROL_ENABLE_CONGESTION_TIMES                       0x4AEC7830u
#define DV1_PORT15_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT15_FLOW_CONTROL_ENABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT0_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                       0x4AEC0034u
#define DV1_PORT0_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM              3u
#define DV1_PORT0_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL            0x0u
#define DV1_PORT1_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                       0x4AEC0834u
#define DV1_PORT1_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM              3u
#define DV1_PORT1_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL            0x0u
#define DV1_PORT2_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                       0x4AEC1034u
#define DV1_PORT2_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM              3u
#define DV1_PORT2_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL            0x0u
#define DV1_PORT3_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                       0x4AEC1834u
#define DV1_PORT3_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM              3u
#define DV1_PORT3_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL            0x0u
#define DV1_PORT4_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                       0x4AEC2034u
#define DV1_PORT4_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM              3u
#define DV1_PORT4_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL            0x0u
#define DV1_PORT5_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                       0x4AEC2834u
#define DV1_PORT5_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM              3u
#define DV1_PORT5_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL            0x0u
#define DV1_PORT6_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                       0x4AEC3034u
#define DV1_PORT6_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM              3u
#define DV1_PORT6_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL            0x0u
#define DV1_PORT7_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                       0x4AEC3834u
#define DV1_PORT7_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM              3u
#define DV1_PORT7_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL            0x0u
#define DV1_PORT8_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                       0x4AEC4034u
#define DV1_PORT8_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM              3u
#define DV1_PORT8_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL            0x0u
#define DV1_PORT9_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                       0x4AEC4834u
#define DV1_PORT9_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM              3u
#define DV1_PORT9_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL            0x0u
#define DV1_PORT10_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                      0x4AEC5034u
#define DV1_PORT10_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT10_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT11_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                      0x4AEC5834u
#define DV1_PORT11_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT11_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT12_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                      0x4AEC6034u
#define DV1_PORT12_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT12_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT13_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                      0x4AEC6834u
#define DV1_PORT13_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT13_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT14_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                      0x4AEC7034u
#define DV1_PORT14_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT14_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT15_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2                      0x4AEC7834u
#define DV1_PORT15_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT15_FLOW_CONTROL_ENABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT0_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                       0x4AEC0038u
#define DV1_PORT0_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT0_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT1_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                       0x4AEC0838u
#define DV1_PORT1_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT1_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT2_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                       0x4AEC1038u
#define DV1_PORT2_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT2_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT3_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                       0x4AEC1838u
#define DV1_PORT3_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT3_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT4_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                       0x4AEC2038u
#define DV1_PORT4_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT4_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT5_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                       0x4AEC2838u
#define DV1_PORT5_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT5_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT6_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                       0x4AEC3038u
#define DV1_PORT6_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT6_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT7_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                       0x4AEC3838u
#define DV1_PORT7_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT7_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT8_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                       0x4AEC4038u
#define DV1_PORT8_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT8_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT9_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                       0x4AEC4838u
#define DV1_PORT9_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM              2u
#define DV1_PORT9_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL            0x0u
#define DV1_PORT10_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                      0x4AEC5038u
#define DV1_PORT10_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM             2u
#define DV1_PORT10_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL           0x0u
#define DV1_PORT11_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                      0x4AEC5838u
#define DV1_PORT11_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM             2u
#define DV1_PORT11_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL           0x0u
#define DV1_PORT12_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                      0x4AEC6038u
#define DV1_PORT12_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM             2u
#define DV1_PORT12_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL           0x0u
#define DV1_PORT13_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                      0x4AEC6838u
#define DV1_PORT13_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM             2u
#define DV1_PORT13_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL           0x0u
#define DV1_PORT14_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                      0x4AEC7038u
#define DV1_PORT14_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM             2u
#define DV1_PORT14_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL           0x0u
#define DV1_PORT15_FLOW_CONTROL_DISABLE_CONGESTION_TIMES                      0x4AEC7838u
#define DV1_PORT15_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_FIELDNUM             2u
#define DV1_PORT15_FLOW_CONTROL_DISABLE_CONGESTION_TIMES_DEFAULTVAL           0x0u
#define DV1_PORT0_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                      0x4AEC003Cu
#define DV1_PORT0_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT0_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT1_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                      0x4AEC083Cu
#define DV1_PORT1_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT1_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT2_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                      0x4AEC103Cu
#define DV1_PORT2_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT2_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT3_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                      0x4AEC183Cu
#define DV1_PORT3_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT3_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT4_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                      0x4AEC203Cu
#define DV1_PORT4_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT4_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT5_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                      0x4AEC283Cu
#define DV1_PORT5_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT5_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT6_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                      0x4AEC303Cu
#define DV1_PORT6_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT6_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT7_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                      0x4AEC383Cu
#define DV1_PORT7_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT7_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT8_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                      0x4AEC403Cu
#define DV1_PORT8_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT8_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT9_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                      0x4AEC483Cu
#define DV1_PORT9_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM             3u
#define DV1_PORT9_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL           0x0u
#define DV1_PORT10_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                     0x4AEC503Cu
#define DV1_PORT10_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM            3u
#define DV1_PORT10_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL          0x0u
#define DV1_PORT11_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                     0x4AEC583Cu
#define DV1_PORT11_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM            3u
#define DV1_PORT11_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL          0x0u
#define DV1_PORT12_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                     0x4AEC603Cu
#define DV1_PORT12_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM            3u
#define DV1_PORT12_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL          0x0u
#define DV1_PORT13_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                     0x4AEC683Cu
#define DV1_PORT13_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM            3u
#define DV1_PORT13_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL          0x0u
#define DV1_PORT14_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                     0x4AEC703Cu
#define DV1_PORT14_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM            3u
#define DV1_PORT14_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL          0x0u
#define DV1_PORT15_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2                     0x4AEC783Cu
#define DV1_PORT15_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_FIELDNUM            3u
#define DV1_PORT15_FLOW_CONTROL_DISABLE_CONGESTION_TIMES2_DEFAULTVAL          0x0u
#endif
#endif /* DV1_RTKAS_REG_LIST_FILE_FLOW_CONTROL_DIAG_H_ */