
########## Source file ##########
ifneq (,$(findstring RTK_MODULE_TBL_ACCESS, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_lut.c
endif

ifneq (,$(findstring RTK_MODULE_L2, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_l2.c
    SRCS += rtkas_api_l2.c
endif

ifneq (,$(findstring RTK_MODULE_PTP, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_ptp.c
    SRCS += rtl907xc_va_api_ptp.c
    SRCS += rtkas_api_ptp.c
endif

ifneq (,$(findstring RTK_MODULE_VLAN, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_svlan.c
    SRCS += rtl907xc_va_asicdrv_vlan.c
    SRCS += rtl907xc_va_api_vlan.c
    SRCS += rtkas_api_vlan.c
endif

ifneq (,$(findstring RTK_MODULE_DOT1X, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_dot1x.c
    SRCS += rtkas_api_dot1x.c
endif

ifneq (,$(findstring RTK_MODULE_CB_FRER, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_cb.c
    SRCS += rtl907xc_va_api_cb.c
    SRCS += rtkas_api_cb.c
endif

ifneq (,$(findstring RTK_MODULE_STACKING, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_stacking.c
    SRCS += rtl907xc_va_api_stacking.c
    SRCS += rtkas_api_stacking.c
endif

ifneq (,$(findstring RTK_MODULE_ROUTING, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_routing.c
    SRCS += rtkas_api_routing.c
endif

ifneq (,$(findstring RTK_MODULE_TSN, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_tsn_common.c
endif

ifneq (,$(findstring RTK_MODULE_ACL, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_acl.c
    SRCS += rtl907xc_va_asicdrv_acl.c
    SRCS += rtkas_api_acl.c
endif

ifneq (,$(findstring RTK_MODULE_OPFSM, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_opfsm.c
    SRCS += rtl907xc_va_asicdrv_opfsm.c
    SRCS += rtkas_api_opfsm.c
endif

ifneq (,$(findstring RTK_MODULE_ETHERNET_ACCESS, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_ethernet_access.c
    SRCS += rtl907xc_va_asicdrv_ethernet_access.c
    SRCS += rtkas_api_ethernet_access.c
endif

ifneq (,$(findstring RTK_MODULE_PORT_MIRROR, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_mirror.c
    SRCS += rtl907xc_va_asicdrv_mirror.c
    SRCS += rtkas_api_mirror.c
endif

ifneq (,$(findstring RTK_MODULE_STP, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_stp.c
    SRCS += rtkas_api_stp.c
endif

ifneq (,$(findstring RTK_MODULE_SINGLE_LOOP, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_single_loop.c
    SRCS += rtl907xc_va_api_single_loop.c
    SRCS += rtkas_api_single_loop.c
endif

ifneq (,$(findstring RTK_MODULE_QOS, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_qos.c
    SRCS += rtl907xc_va_asicdrv_qos.c
    SRCS += rtkas_api_qos.c
endif

ifneq (,$(findstring RTK_MODULE_QAV, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_qav.c
    SRCS += rtkas_api_qav.c
endif

ifneq (,$(findstring RTK_MODULE_ST_QBV, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_st.c
    SRCS += rtl907xc_va_asicdrv_st.c
    SRCS += rtkas_api_st.c
endif

ifneq (,$(findstring RTK_MODULE_PSFP, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_psfp.c
    SRCS += rtl907xc_va_asicdrv_psfp.c
    SRCS += rtkas_api_psfp.c
endif

ifneq (,$(findstring RTK_MODULE_PCIE, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_pcie.c
    SRCS += rtl907xc_va_asicdrv_pcie.c
    SRCS += rtkas_api_pcie.c
endif

ifneq (,$(findstring RTK_MODULE_PORT_ISOLATION, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_port_isolation.c
    SRCS += rtkas_api_port_isolation.c
endif

ifneq (,$(findstring RTK_MODULE_STORM_CTRL, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_storm_ctl.c
    SRCS += rtl907xc_va_asicdrv_storm_ctl.c
    SRCS += rtkas_api_storm_ctl.c
endif

ifneq (,$(findstring RTK_MODULE_LINK_AGGREGATION, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_link_aggregation.c
    SRCS += rtkas_api_link_aggregation.c
endif

ifneq (,$(findstring RTK_MODULE_MIB, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_mib.c
    SRCS += rtl907xc_va_api_mib.c
    SRCS += rtkas_api_mib.c
endif

ifneq (,$(findstring RTK_MODULE_INTERFACE, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_port.c
    SRCS += rtl907xc_va_api_interface.c
    SRCS += rtkas_api_interface.c
endif

ifneq (,$(findstring RTK_MODULE_SMI_MASTER, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_smi.c
    SRCS += rtl907xc_va_api_smi.c
    SRCS += rtkas_api_smi.c
endif

ifneq (,$(findstring RTK_MODULE_SPI_FLASH, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_flash.c
    SRCS += rtl907xc_va_api_spi_flash.c
    SRCS += rtkas_api_spi_flash.c
endif

ifneq (,$(findstring RTK_MODULE_SYSTEM, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_system.c
    SRCS += rtl907xc_va_asicdrv.c
    SRCS += rtl907xc_va_asicdrv_mem_ctrl.c
    SRCS += rtkas_api_system.c
endif

ifneq (,$(findstring RTK_MODULE_PHY_PORT, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_phy.c
    SRCS += rtl907xc_va_asicdrv_phy.c
    SRCS += rtkas_api_phy.c
endif

ifneq (,$(findstring RTK_MODULE_PHY_TEST_MODE, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_phy_test.c
    SRCS += rtkas_api_phy_test.c
endif

ifneq (,$(findstring RTK_MODULE_FLOWCTRL, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_flow_ctrl.c
    SRCS += rtl907xc_va_api_flow_ctrl.c
    SRCS += rtkas_api_flow_ctrl.c
endif

ifneq (,$(findstring RTK_MODULE_IGMP, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_igmp.c
    SRCS += rtkas_api_igmp.c
endif

ifneq (,$(findstring RTK_MODULE_OTP, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_otp.c
    SRCS += rtl907xc_va_api_otp.c
    SRCS += rtkas_api_otp.c
endif

ifneq (,$(findstring RTK_MODULE_SYS_BOOT, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_sys_boot.c
    SRCS += rtkas_api_sys_boot.c
    SRCS += rtl907xc_va_asicdrv_config.c
endif

ifneq (,$(findstring RTK_MODULE_SERDES, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_serdes.c
    SRCS += rtl907xc_va_asicdrv_serdes.c
    SRCS += rtkas_api_serdes.c
endif

ifneq (,$(findstring RTK_MODULE_MACPHY, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_macphy.c
    SRCS += rtkas_api_macphy.c
endif

ifneq (,$(findstring RTK_MODULE_MACSEC, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_api_mka.c
    SRCS += rtl907xc_va_api_macsec.c
    SRCS += rtl907xc_va_asicdrv_mka.c
    SRCS += rtl907xc_va_asicdrv_macsec.c
    SRCS += rtkas_api_mka.c
    SRCS += rtkas_api_macsec.c
endif

ifneq (,$(findstring RTK_MODULE_RESET, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_reset.c
    SRCS += rtl907xc_va_api_reset.c
    SRCS += rtkas_api_reset.c
endif

ifneq (,$(findstring RTK_MODULE_TCAM, $(CFLAGS)))
## Include file
    SRCS += rtl907xc_va_asicdrv_tcam.c
endif
